### ISSUE TITLE
Portals

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#1012]
Nether portal creation is already implemented by tigerw, but they don't transport an entity to another world yet. Since entities can't change worlds yet it should first be implemented.

EDIT:

Also we need to hook worlds to other worlds somehow, because how does the server know to wich world the entity should be transported?

**Comment by NiLSPACE** [comment]
This one can be closed already right?

**Comment by madmaxoft** [comment]
I guess so.
