### ISSUE TITLE
Enable precompiled headers with gcc and clang

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1046]
These compilers both support precompiled headers, which would speed up the compilation significantly. MSVC already uses precompiled headers, so the project is ready for the change, only the proper set of commandline arguments and possibly minor changes to the cmake file should be required to port this support to gcc and clang.

**Comment by peterbell10** [comment]
Any opinions on utilising [cotire][cotire]?  Highlighting the important features:
* Automatically generates a prefix header by tracking includes used by a CMake target.
* Automatically precompiles prefix header and applies resulting precompiled header to a CMake target.
* Supports C/C++ compilers Clang, GCC, Intel and Visual Studio C++.

Usage is as simple as adding this to CMakeLists.txt for each target:
```cmake
include(cotire)
cotire(MyTarget)
```

[cotire]: https://github.com/sakra/cotire

**Comment by tigerw** [comment]
> Cmake should help us with that.

And in the end it did. PCH enabled by default.
