### ISSUE TITLE
Implement trapdoor metadata

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#105]
Trapdoors currently need to support directional metadata (open with hinge to the side of a block), as well as support placing at the top of a block.

**Comment by theophriene** [comment]
Causes a server crash with failed assertion

Client version: 1.12.2
Server OS: Linux 4.15.0-74-generic x86_64 Ubuntu 18.04.3 LTS
Commit id: a867388
Using IPV6

#### Steps to reproduce
Place a trapdoor on a horizontal surface

#### Server log
[6297524e64d3032c|04:32:11] HandleRightClick: {16, 61, 15}, face 1, Hand: 0, HeldItem: trapdoor:0 * 1; Dist: 2.34
[6297524e64d3032c|04:32:11] Assertion failed: !"Unhandled block face!", file /home/minecraft/compilesite/cuberite/src/Blocks/BlockTrapdoor.h, line 86
/home/minecraft/Server/Cuberite(_Z15PrintStackTracev+0x2e)[0x555555e0e3a6]
/home/minecraft/Server/Cuberite(_ZN21cBlockTrapdoorHandler19BlockFaceToMetaDataE10eBlockFace+0x9e)[0x555555fa57ea]
/home/minecraft/Server/Cuberite(_ZN21cBlockTrapdoorHandler25GetPlacementBlockTypeMetaER15cChunkInterfaceR7cPlayeriii10eBlockFaceiiiRhS5_+0x35)[0x555555fa5725]
/home/minecraft/Server/Cuberite(_ZN12cItemHandler25GetPlacementBlockTypeMetaEP6cWorldP7cPlayeriii10eBlockFaceiiiRhS5_+0x14a)[0x555555f7553e]
/home/minecraft/Server/Cuberite(_ZN12cItemHandler16GetBlocksToPlaceER6cWorldR7cPlayerRK5cItemiii10eBlockFaceiiiRSt6vectorI9sSetBlockSaIS9_EE+0x85)[0x555555f74d33]
/home/minecraft/Server/Cuberite(_ZN12cItemHandler13OnPlayerPlaceER6cWorldR7cPlayerRK5cItemiii10eBlockFaceiii+0x2cf)[0x555555f74ad3]
/home/minecraft/Server/Cuberite(_ZN13cClientHandle16HandleRightClickEiii10eBlockFaceiii5eHand+0x82c)[0x555555cf6646]
/home/minecraft/Server/Cuberite(_ZN14cProtocol_1_1222HandlePacketBlockPlaceER11cByteBuffer+0x17e)[0x5555560199e2]
/home/minecraft/Server/Cuberite(_ZN16cProtocol_1_12_112HandlePacketER11cByteBufferj+0x5fe)[0x55555601d4d6]
/home/minecraft/Server/Cuberite(_ZN15cProtocol_1_9_015AddReceivedDataEPKcm+0xa51)[0x555555ff79e9]
/home/minecraft/Server/Cuberite(_ZN15cProtocol_1_9_012DataReceivedEPKcm+0xfe)[0x555555fed070]
/home/minecraft/Server/Cuberite(_ZN19cProtocolRecognizer12DataReceivedEPKcm+0x6c)[0x555556007c4c]
/home/minecraft/Server/Cuberite(_ZN13cClientHandle20ProcessProtocolInOutEv+0xd1)[0x555555cfc1db]
/home/minecraft/Server/Cuberite(_ZN13cClientHandle4TickEf+0xb4)[0x555555cf87be]
/home/minecraft/Server/Cuberite(_ZN6cWorld11TickClientsEf+0x395)[0x555555dcf49f]
/home/minecraft/Server/Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x4dc)[0x555555dce536]
/home/minecraft/Server/Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0x95)[0x555555dc5341]
/home/minecraft/Server/Cuberite(_ZN9cIsThread9DoExecuteEv+0x2f)[0x555555e04e89]
/home/minecraft/Server/Cuberite(_ZSt13__invoke_implIvM9cIsThreadFvvEPS0_JEET_St21__invoke_memfun_derefOT0_OT1_DpOT2_+0x67)[0x555555e0581a]
/home/minecraft/Server/Cuberite(_ZSt8__invokeIM9cIsThreadFvvEJPS0_EENSt15__invoke_resultIT_JDpT0_EE4typeEOS5_DpOS6_+0x4e)[0x555555e05337]
/home/minecraft/Server/Cuberite(_ZNSt6thread8_InvokerISt5tupleIJM9cIsThreadFvvEPS2_EEE9_M_invokeIJLm0ELm1EEEEDTcl8__invokespcl10_S_declvalIXT_EEEEESt12_Index_tupleIJXspT_EEE+0x43)[0x555555e05b7b]
/home/minecraft/Server/Cuberite(_ZNSt6thread8_InvokerISt5tupleIJM9cIsThreadFvvEPS2_EEEclEv+0x2c)[0x555555e05b1c]
/home/minecraft/Server/Cuberite(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJM9cIsThreadFvvEPS3_EEEEE6_M_runEv+0x1c)[0x555555e05aec]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd66f)[0x7ffff790566f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7ffff707a6db]
/lib/x8 #1056_64-linux-gnu/libc.so.6(clone+0x3f)[0x7ffff6da388f]
Cuberite: /home/minecraft/compilesite/cuberite/src/Blocks/BlockTrapdoor.h:86: static NIBBLETYPE cBlockTrapdoorHandler::BlockFaceToMetaData(eBlockFace): Assertion `0' failed.

Thread 9 "Cuberite" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffedffb700 (LWP 31979)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb)
