### ISSUE TITLE
1-block high mobs swim __in__ water, not on top.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#1064]
As described in the title.

![2014-06-07_11 39 25](https://cloud.githubusercontent.com/assets/1297699/3208413/8103724a-ee31-11e3-93ec-8d486ce62f89.png)

**Comment by SafwatHalaby** [comment]
The general issue is that short mobs have trouble with water. This is identical to #2014

**Comment by SafwatHalaby** [comment]
Combining this with #1241
