### ISSUE TITLE
Issue Megalist

### ISSUE THREAD

**Issue by skarlitz** [cuberite/cuberite#1109]
- [ ] Mobs don't make sounds when they move or do periodicals. (A zombie groaning occasionally, a sheep baaa'ing.)
- [x] Mobs not only move far too fast (As described in another issue), but also act as if they are on ice, slipping and sliding around. 
- [x] Splash potions don't get thrown (But ARE consumed)
- [ ] Sheep eating grass doesn't make noise
- [ ] Eye of Ender does... something? Looks like it's trying to open a schematic according to the console, when you right click with an Eye of Ender.
- [ ] Eye of Ender doesn't do intended functions (can't be thrown, can't be inserted into end portal frame.)
- [ ] End portal does nothing (I suppose this is intended, since the server is in beta. Just a reminder)
- [ ] Placing of certain blocks doesn't provoke the correct sound (Like soul sand sounding like stone when being placed)
- [ ] Withers don't attack anything at all, and are paralyzed in water (Or maybe just don't move because they have nothing to attack?)
- [x] Droppers/Dispensers' inventory names are wrong ("Dropspenser"). I am assuming this is intended. There is no discernable difference between the two blocks' functions. Dropper should drop items, dispenser should also drop items, but also fire/place them if they can. (Like arrows)
- [ ] Boats don't break on crash, and will stutter when over only 1 block of water.
- [ ] Villagers don't trade. 
- [x] Daylight sensors don't give signals proportional to the amount of sunlight there is. That, or redstone isn't updating when it should.
- [x] Comparators don't work.
- [x] Maps are blank (Completely white.)
- [x] Tripwire hook meta is messed up, they are always rearranged to face south.
- [x] Firing a bow occasionally crashes the server.
- [ ] Trying to use redstone on a hopper (Which would normally make it stop passing items) does not work
- [ ] Item frames occasionally stay when the block they are placed on is broken.
- [ ] Snow golems don't attack mobs like they should.
- [x] Throwing eggs, ender pearls, bottles of enchanting, fishing bobbers, and snowballs crashes the server. (Seems to be a projectile related problem, since firing a bow can also crash the server.
- [x] Beacons don't have a GUI.
- [x] Jukebox doesn't work.
- [ ] Leads aren't implemented.
- [x] Spawn a horse. The horse... fades in and out of view. Very rapidly. Like a strobe light.
- [x] Skeletons don't hold bows 
- [x] When Skeletons fire, arrows aren't shot correctly.

I will update with more as I find them. Good luck! I really love this server, even with all of its little quirks. :)

**Comment by SphinxC0re** [comment]
@skarlitz could you review your issue list and report if anything has changed?

**Comment by SafwatHalaby** [comment]
Marked " When Skeletons fire, arrows aren't shot correctly."  as fixed.

**Comment by PureTryOut** [comment]
Since clearly no one is going to keep this list properly updated, shouldn't this issue be closed?

**Comment by yangm97** [comment]
Or maybe it should get it's own milestone?

**Comment by madmaxoft** [comment]
Best if each outstanding item got its own issue; there's no "logical" link between them other than being reported in this list, so there's no need to keep them linked, other than perhaps mentioning this issue.

**Comment by sphinxc0re** [comment]
So, who does the duty of putting every line into a seperate issue?

**Comment by yangm97** [comment]
I'm going to. Also, shouldn't some of these be added to the "Good Survival" milestone?

**Comment by yangm97** [comment]
Skipped "Comparators don't work" because it seemed to work fine for me.

**Comment by yangm97** [comment]
Shall we close this one?

**Comment by madmaxoft** [comment]
I vote close, the individual sub-issues will track their progress, no need for the megalist to be open just because the issue happened to be reported together with other (unrelated) ones.

**Comment by MGlolenstine** [comment]
Some spawn eggs of the newer mobs, change to an empty spawn egg.

Also, the server lags strongly when the lever is put next to the piston(could be the problem with either one), and then we get the DeadLock kicking in.

**Comment by tigerw** [comment]
Thanks. Could you elaborate on the second one or upload a picture of the layout of the lever and piston?

**Comment by MGlolenstine** [comment]
Here you go.. Although it didn't crash this time.

http://prntscr.com/kdiaql
