### ISSUE TITLE
Project name idea

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#1146]
My idea is why you don't rename to mc-server project to Craft++.
 From c++.

_Collaborator edit: Eventually the name was changed to Cuberite._

**Comment by tigerw** [comment]
As per the new idea, shall we rename the mcserver organisation into Cuberite and move everything under the umbrella term?

**Comment by madmaxoft** [comment]
That's the general direction we were aiming for, but first we need to "impress" the others enough to agree to the change - so a new logo, webdesign etc.

**Comment by tigerw** [comment]
So many website redesigns :P

Does @FakeTruth and @tonibm19 and everyone else agree with an organisational name change? STR is in agreement, I think?

**Comment by madmaxoft** [comment]
There was no consensus yet. And I don't want to push the issue, until, as FakeTruth said, we have a viable alternative.

**Comment by tonibm19** [comment]
I agree.

**Comment by STRWarrior** [comment]
@with tigerw or xoft? ;) If the majority + FakeTruth want the name change then I'm not going to stop them, but I prefer the current name.

**Comment by SphinxC0re** [comment]
Agreed. If this matters in any way

**Comment by tonibm19** [comment]
I agree with tigerw, but FakeTruth should approve the idea I guess.

**Comment by SafwatHalaby** [comment]
>I think MCServer or MCS is natural to pronounce.
:|

**Comment by tigerw** [comment]
Pipeface!

**Comment by SafwatHalaby** [comment]
>Web searches for Screen can be very difficult, because of the way the word "screen" is used for many different purposes much more popularly known than the terminal multiplexer. Even in a technical, computer related context, a much more popular use of the word refers to the display, as in the case of the screen of a desktop computer's flat panel monitor. Using the term "GNU Screen" in a web search can mitigate this problem, though it is not a perfect solution and may exclude many useful results that do not couple the word "screen" with GNU. Additional problems may arise as the most popular search engines have started deprecating the availability of features allowing users to restrict results to those that include specific terms, such as where Google has stopped honoring the "+" operator (the same effect can be achieved by quoting a word instead of prepending it with '+').
By contrast, the name of tmux is a far more unique term that tends to return useful information in the top results of popular search engines. 

[From WikiVS](https://www.wikivs.com/wiki/screen_vs_tmux#Searchability), comparing Screen and Tmux.

**Comment by LogicParrot** [comment]
For the record: The name was eventually changed to Cuberite.

Retrospectively: I think my subconcious problem with the old name was not about whether new people find it in searches, rather, it was about whether existing users can find the help they're looking for. "Cuberite world setup is more likely to yield relevant results in comparison to "mcserver world setup".
