### ISSUE TITLE
Creepers explode through walls

### ISSUE THREAD

**Issue by bennasar99** [cuberite/cuberite#1170]
To reproduce (what I did)
-Make a house.
-Wait until night.
-When a creeper comes go near it, but inside the house.
-Pooom!!! Your house is distroyed.

**Comment by ahyattdev** [comment]
This issue still exists, except creepers will still explode if they start tracking you and you go inside and have a door between you and them closed. In vanilla, creepers will not explode if they can't see you.

**Comment by LogicParrot** [comment]
I believe there could be some line tracing bug. I recall zombies attacking me through 1-block thick walls in some setups in the past.

**Comment by tigerw** [comment]
#5082 should fix.
