### ISSUE TITLE
Mobs can't walk through open Trapdoors

### ISSUE THREAD

**Issue by Masy98** [cuberite/cuberite#1241]
Thats because they aren't set to "false" in the "IsSolid" list. But if we would do that they could walk through closed Trapdoors aswell... Anyone has a solution?

**Comment by SafwatHalaby** [comment]
Added to the [PathFinder to-do](http://forum.mc-server.org/showthread.php?tid=1571).

**Comment by SafwatHalaby** [comment]
I'm combining this with #2062
