### ISSUE TITLE
A few issues I'm having...

### ISSUE THREAD

**Issue by soccermitchy** [cuberite/cuberite#1243]
So today I started messing around with MCServer and I have some issues:
- [ ] 1 - I set myself as owner, but when one of my friends joined I couldn't see his name in the tab menu and I couldn't see his chats (he could see mine). He was the default group.
- [ ] 2 - A majority of chunks I have seen near spawn, on the default world settings, are the Arctic Plains biome (not sure, can't check right now)
- [x] 3 - Friendly mobs (not sure about harmful ones) tend to walk into walls alot

**Comment by SafwatHalaby** [comment]
[3] Is no longer an issue.

**Comment by mathiascode** [comment]
Closing this, since there haven't been more reports about these issues in recent years.
