### ISSUE TITLE
Add enchantment effects

### ISSUE THREAD

**Issue by tonibm19** [cuberite/cuberite#1257]
To complete the encanting system, enchantment effects should be implemented.
daniel0916 started with it, but he didn't finish it, so maybe his branch could be useful.
https://github.com/daniel0916/MCServer/tree/Enchanting (see commits)

**Comment by Rakete1111** [comment]
Could someone explain to me want Enchantment Effects are?
They don't appear to exist.
What do you mean?

**Comment by bearbin** [comment]
Probably so that enchantments will actually do something.

**Comment by Bond-009** [comment]
Duplicate of #915
