### ISSUE TITLE
Minecarts issues

### ISSUE THREAD

**Issue by tonibm19** [cuberite/cuberite#1259]
-Minecarts sometimes derail
-Minecarts dont go fast if inside there's a player speeding(with A).
-Speeding has to be done with A, not W. (something related to entity attaching?)

**Comment by source83** [comment]
I can't use carts too, I can push them and I can get them to move on power rails when I'm not in them.
When I'm in them, they won't budge.
git version cloned and compiled today on ubuntu server 15.10 x64

**Comment by SphinxC0re** [comment]
Minecarts are not fully implemented yet. Thanks for the report.

**Comment by tigerw** [comment]
When you're in the carts, what do you do to get them to move? The vanilla functionality of moving-by-up-against-a-wall-and-on-a-powered-rail doesn't work as @SphinxC0re implies, but if you put them on a slope, quickly get in, and accelerate them with powered rails, they should move.

**Comment by bearbin** [comment]
Closing as stale and not a definite problem. There are lots of other open issues about minecarts that duplicate this.
