### ISSUE TITLE
Auto-complete issues

### ISSUE THREAD

**Issue by Masy** [cuberite/cuberite#1274]
When Howaner and I are on the same server it auto-completes "a" to "Howaner" even though my name is "AntherusCraft"...

Example:
1.  /give a
2. [tab]
3. /give Howaner

very weird, even though there is an "a" in Howaner it still should auto-complete to "antheruscraft" :)

**Comment by Seadragon91** [comment]
Looks like I have found a small issue. If I type `/protection a` and press TAB, then the content in the chat bar is `/protection  /protection add`.

**Comment by SphinxC0re** [comment]
I like the idea of defining the command-tree in the ```info.lua``` file. Does anyone have an implementation plan?

**Comment by madmaxoft** [comment]
The Info.lua structure could add a `TabCompletionHandler` element to any (sub)command that would handle the specific tab completion for that command; the InfoReg.lua library would generate the generic tab completion for commands that have subcommands.

**Comment by SphinxC0re** [comment]
I edited my comment

**Comment by Titaniumtown** [comment]
bump, kind off a long time since the last post (5 years). Is there any plan on fixing this issue?

**Comment by Titaniumtown** [comment]
wait, nvm it works i think

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/cuberite/cuberite/issues/701
