### ISSUE TITLE
Add UUID-to-name lookup to cMojangAPI

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1278]
We need the lookup and caches to work both ways.

**Comment by NiLSPACE** [comment]
I used SqliteBrowser to see what's in the mojang API database, but I noticed that it doesn't get filled.

Also, is the `MojangAPI.sqlite` the cache that the [cMojangAPI](http://mc-server.xoft.cz/LuaAPI/cMojangAPI.html)'s documentation is talking about?

**Comment by worktycho** [comment]
It should be.

**Comment by madmaxoft** [comment]
The DB only gets filled if the server is in online mode or when a plugin makes a request.

And yes, that DB is the cache.

**Comment by NiLSPACE** [comment]
I've tried it both in online and offline mode, but there was never a record added.

**Comment by NiLSPACE** [comment]
Oh, nevermind, they only get added once you stop the server.

**Comment by madmaxoft** [comment]
I think they should be added immediately. Did you reload the SQLiteBrowser? (it tends to cache old data, you need to close it and open the file again)

**Comment by NiLSPACE** [comment]
Yes, I clicked refresh, and that works on everything else like the bans database, and my PreciousBlocks database.
