### ISSUE TITLE
Powered rails don't transmit redstone signals

### ISSUE THREAD

**Issue by ChriPiv** [cuberite/cuberite#1333]
Vanilla:
![2014-08-19_15 44 42](https://cloud.githubusercontent.com/assets/6672223/3966791/2605c5be-27a7-11e4-984d-a15bf3d16e56.png)

MCServer:
![2014-08-19_15 45 19](https://cloud.githubusercontent.com/assets/6672223/3966792/2b8f4b0e-27a7-11e4-9d96-d185ea064263.png)

**Comment by mathiascode** [comment]
Should no longer be an issue.
