### ISSUE TITLE
PPC Builds Don't Work

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#1343]
They fail with an error like `cannot determine endianness of platform`.

Ref: http://ci.bearbin.net/job/MCServer%20Linux-PPC/2/console

**Comment by SphinxC0re** [comment]
Closing since we aren't providing PPC architecture anymore

**Comment by Heath123** [comment]
So it won't work? Can I use an old version?

**Comment by tigerw** [comment]
Last I tried it compiled but we just need to update our SQLiteCpp library to get a crash fix. Do you have a compiler/machine to test with?

**Comment by Heath123** [comment]
Me? I wanted to run it on a Wii, which I haven't set up at the moment, and I also have an iMac G5 but I can't get Mac OS on that, just Linux

**Comment by tigerw** [comment]
Very cool, if you get to compiling the server do say how it went. I don't have any PPC devices to test with...

**Comment by Heath123** [comment]
You/I could probably use an emulator like QEMU, right?
