### ISSUE TITLE
Allow server to be started as a Windows Service

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1360]
Currently the executable can be run in the interactive session only, there's no way to run it as a service directly, one needs a wrapper program for that and there are problems with that (see http://forum.mc-server.org/showthread.php?tid=1560 ). We should add the support for running as a service when there's a special cmdline parameter added, and possibly another cmdline parameter to install the service, to make the setup easier.

**Comment by birkett** [comment]
Is there still interest in improving Service support?

I have created a service wrapper as a drop in replacement for srvany, and use this to run an MCServer instance: https://github.com/birkett/srvany-ng

I have also been looking at adding native service support to MCServer - if it's something that would be accepted in, I will continue working on it.

**Comment by madmaxoft** [comment]
It would be great to improve the windows service support. I'd love to have the main executable be able to be run as a service, and to have an extra pair of scripts for registering and unregistering the service (so that our users don't need to edit anything in regedit, as required by srvany).

I suggest using a new commandline parameter that would signalize to the executable that it should run as a service, and wrapping all of that functionality there.

**Comment by birkett** [comment]
Ill see what I can do.

The actual code to get it running as a service is pretty short and simple, and the stdin issues don't seem to be a problem any more.
