### ISSUE TITLE
Something tries to load a block with y-coord higher than 256

### ISSUE THREAD

**Issue by LO1ZB** [cuberite/cuberite#1378]
First of all, I'm happy that I can load the map "The Dropper" with MCServer, but when I connect to the Server, the console (and log) is getting flooded by the massage:
"Warn [00:22:43] cChunk::UnboundedRelGetBlockType: requesting a block with a_RelY out of range: 256"
And I'm getting the message "Unable to locate sign at x, y >= 256, z (like -419, 11006, -612)
I'm using minecraft 1.7.4 & my dailybuild from today (06.09.2014)

**Comment by Seadragon91** [comment]
Tested this. One of the coords is `-635 253 -696`. It will directly assert on teleporting to the coords, if running in debug mode.

**Comment by mathiascode** [comment]
Tested the map with latest master. Cannot reproduce anymore.
