### ISSUE TITLE
Add sponge interaction

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#1411]
http://minecraft.gamepedia.com/Sponge

The sponge should remove water in its vicinity.

**Comment by ard1998** [comment]
sponges still won't get wet

**Comment by earboxer** [comment]
Sponges have a limit to the number of water blocks they can absorb (65), and the distance that they can absorb out from (taxicab distance of 7 in all directions).

I'm thinking to do this properly:

1. Generate a list of connected waterblocks with taxicab distance 7 (recursive function, also note the distance, If you hit a block twice, store the smaller distance)
2. do a breadth first traversal, removing water until 65 blocks have been removed,
    or the list is empty. (Go through the list 7 times, each time removing the items that are closest)

**Comment by peterbell10** [comment]
@earboxer you might want to look into [flood fill](https://en.wikipedia.org/wiki/Flood_fill). I think this is only a slight variant of that algorithm.

A seed should track the remaining distance, starting at 7 and decresing by one each time. Then for each seed you check the 6 nearest neighbours for water and if so mark them as a seed. By using a queue to store seeds, you would get breadth first search by default.
