### ISSUE TITLE
Peonys top part gets generated on top of snow layers in the ice mountains

### ISSUE THREAD

**Issue by Masy** [cuberite/cuberite#1428]
![2014-09-12_21 37 14](https://cloud.githubusercontent.com/assets/7923485/4259681/fc40989c-3b08-11e4-8cc9-6007fe899ef6.png)

**Comment by SafwatHalaby** [comment]
![2015-11-30_17 17 40](https://cloud.githubusercontent.com/assets/5030488/11476467/91e4b5d8-978b-11e5-9baa-bb74586d00fe.png)

**Comment by SafwatHalaby** [comment]
![2015-11-30_17 34 49](https://cloud.githubusercontent.com/assets/5030488/11476480/a0f95e5c-978b-11e5-8378-c3dd84834a47.png)

**Comment by SafwatHalaby** [comment]
![2015-11-30_17 31 58](https://cloud.githubusercontent.com/assets/5030488/11476492/ae339c54-978b-11e5-958c-8c451b9fd119.png)

**Comment by SafwatHalaby** [comment]
Note that an elevated snow patch is always present beneath the peony. This could be related to [this](http://forum.mc-server.org/showthread.php?tid=2227&pid=23638#pid23638)

**Comment by tigerw** [comment]
uh, say, this feature = snow holograms?

**Comment by NiLSPACE** [comment]
I suspect that the height doesn't get updated when the peonys are generated. Because of that the snow generator thinks it can generate just fine.
