### ISSUE TITLE
Cuberite takes too long to build

### ISSUE THREAD

**Issue by archshift** [cuberite/cuberite#1453]
It doesn't seem like it should take this long to build, and I have a theory that it's because of unused `#include`s all over the damn place. We could use a tool like http://github.com/myint/cppclean or https://code.google.com/p/include-what-you-use/ to weed them out.

**Comment by worktycho** [comment]
This would be really beneficial and is a simple job.

**Comment by SafwatHalaby** [comment]
It's not just about excessive includes in general, 

it's also about #includes in headers, a small change in a header will recursively force all headers that include it (and all headers that include the headers that include it) to re-compile, along with all their .cpp files.

The solution is forward declarations, I think that every header file should have "usage instructions", similarly to what I've written in Path.h:
```
/* Wanna use the pathfinder? Put this in your header file:

// Fwd: cPath
enum class ePathFinderStatus;
class cPath;

Put this in your .cpp:
#include "...Path.h"
*/
```
That way, if someone wants to use a header in a header, it'll be obvious for them how to do it.

**Comment by worktycho** [comment]
Like everything in c++, there are two many caveats for that to be useful. For example, inline methods, classes that only use part of your interface, value parameters, value members.

**Comment by SafwatHalaby** [comment]
Yes, it can't cover all headers but it can cover many of them.

**Comment by SafwatHalaby** [comment]
But I disagree with saying that it isn't useful. It *is useful*, for example, whenever I changed Path.h, no one had to re-compile monster.cpp and it saved a few seconds, if we had that on all (or almost all) headers, it would have helped a lot more.

**Comment by SafwatHalaby** [comment]
Actually, now that I think of it, it saved a **lot** more than a few seconds now that I think of it: If monster.h had Path.h, whenever I changed something in Path.h, anything that includes monster.h would have to recompile, and that's a lot of things.

**Comment by madmaxoft** [comment]
We already have that in most places where it could be used. And no need to explain fwd declarations in a header ,everyone knows how to do those.

Safwat Halaby <notifications@github.com> wrote:

>But I disagree with saying that it isn't useful. It *is useful*, for
>example, whenever I changed Path.h, no one had to re-compile
>monster.cpp and it saved a few seconds, if we had that on all (or
>almost all) headers, it would have helped a lot more.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mc-server/MCServer/issues/1453#issuecomment-100519368

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by madmaxoft** [comment]
This issue is not about incremental builds, it's about full rebuilds (CI-style).

Safwat Halaby <notifications@github.com> wrote:

>Actually, now that I think of it, it saved a **lot** more than a few
>seconds now that I think of it: If monster.h had Path.h, whenever I
>changed something in Path.h, anything that includes monster.h would
>have to recompile, and that's a lot of things.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mc-server/MCServer/issues/1453#issuecomment-100519499

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by SafwatHalaby** [comment]
> This issue is not about incremental builds, it's about full rebuilds (CI-style).

Oh, ok.

**Comment by worktycho** [comment]
Do I need to open another issue for incremental builds then? Because whats really annoying is thing's like changing cClientHandle, and that forcing a rebuild of cItemHandler. cItemHandler feels like it depends on everything.

**Comment by SafwatHalaby** [comment]
I'll scan the code and see where we can put fwds instead of #includes.

**Comment by SafwatHalaby** [comment]
Regarding forward declarations: This is dirtier than I thought.

**Comment by tigerw** [comment]
You could go the worktycho route and write your own code parser complete with AI (get the pathfinder in it somehow) to intelligently forward-declare where applicable.

:)

**Comment by worktycho** [comment]
I only try to write code generators where the code is basically identical. Look at the broadcast functions, they are identical.

**Comment by SafwatHalaby** [comment]
>We already have that in most places where it could be used. And no need to explain fwd declarations in a header ,everyone knows how to do those.

You missed my point. I know we all know what fwds are. But suppose you want to include my header in your header: If you had a ready-to-use fwds that you just copied over, it would take 2 seconds.
On the other hand, if those weren't there, you'd have to investigate my header and figure out which fwds you need in your header. 

Come to think of it, would could take this one step forward and have a `_fwds.h` version of each header. E.g.:
```
//Monster.h:
#include <Path_fwds.h>

//Monster.cpp
#include <Path.cpp>
```

**Comment by SafwatHalaby** [comment]
How about `pimpl`?

**Comment by worktycho** [comment]
Would you like to pimpl cWorld? Spliting god objects is less work.

**Comment by SafwatHalaby** [comment]
I could give it a shot later, I'm having exams right now.

pimpl trades some compilation time for some minor overhead (a bit more pointer redirection and no header-inlined public functions). Do you think the trade-off is fine?

**Comment by madmaxoft** [comment]
Again, this would help only local recompilation, but not the CI full build.

**Comment by SafwatHalaby** [comment]
pimpl helps in full builds too, because it reduces the header file sizes, sometimes significantly. So each #include would cost less time. I'm not sure whether the improvement is a micro-improvement or a serious improvement though. Think it's worth trying? Also, is the minor performance overhead a concern?

**Comment by SafwatHalaby** [comment]
By the way, this is how I personally do it:

beep.cpp:
```
class Beep
{
public:
	Beep(int id);
	~Beep();
	void print();
protected:
	// Protected methods here
private:
	// pimpl.
	// Private methods and fields are inside the cpp.
	struct Private;
	std::unique_ptr<Private> m; 
};
```

beep.cpp:
```
#include "beep.h"

struct Beep::Private
{
    // Private fields here.
    int id;

    // Private functions here.
    void privateFunction()
    {
		printf("%d created.\n",this->id);
    }
};

Beep::Beep(int id)
{
	m = make_unique<Private>();
	m->id = id;
	m->privateFunction();
}

void Beep::print()
{
	printf("%d printing.\n",m->id);
}

Beep::~Beep()
{
	printf("%d destroyed.\n",m->id);
}
```

Note that a class's `mField` becomes `m->field`. A nice side-advantage is that reading a line of code with a function call is enough to deduce whether it's private or not. `m->Function()` is a private function, `Function()` is a public function.

**Comment by madmaxoft** [comment]
I'm just worried that we'll get to a situation similar to `cChunkMap`. Basically the entire thing is a pimpl-style redirection to `cChunkLayer`, and the cpp file is huge.

If there's any micro-optimization due to header file being smaller (which I doubt, with modern OS disk caching), it would be offset by the cpp file being larger and thus taking much more time to compile. I assume compiling cpp is an operation more costly than parsing a header.

**Comment by tigerw** [comment]
> Also, is the minor performance overhead a concern?
I would say it's a concern, as I understand that the advantage of compiled code is that time is spent in compilation and saved in execution. Trying to conform to design conventions seems an overcomplication to me.

**Comment by SafwatHalaby** [comment]
>I'm just worried that we'll get to a situation similar to cChunkMap. Basically the entire thing is a pimpl-style redirection to cChunkLayer, and the cpp file is huge.

The technique I've shown does not increase the cpp file size by more than a few lines. (the fields are migrated inside and there's a new struct, but that's all.). I wonder if it has any disadvantages I've missed though.

>If there's any micro-optimization due to header file being smaller...

You may be right, but we cannot be sure. Bear in mind that making e.g. globals.h 3 line smaller decreases the lines the compiler has to process by `3 * the number of files the have #include globals.h`, things like that can add up quickly.

**Comment by madmaxoft** [comment]
Last time I've seen some stats, the Borland C++ compiler was able to crunch through 50k lines in a second, and that was pre-C++11 and Pentium2-class CPU. So I suspect nowadays those 3 lines saved, even multiplied by our 200 source files, are absolutely nothing.

The only way to speed up builds on Linux is to use header preprocessing; on Windows it's already used and there's very little we can do to speed it up even more.

**Comment by SafwatHalaby** [comment]
Fair enough. Both `pimpl` and fwds would really help incremental builds though.

**Comment by SphinxC0re** [comment]
Can we close this?

**Comment by madmaxoft** [comment]
I think so, but I've been on that side since the start, we should ask @worktycho and @archshift and @SafwatHalaby if they're okay with closing this.

**Comment by worktycho** [comment]
Its still a problem, but the hardware we're using for builds has got faster, so it has less impact. I've moved over to believing that this and the issue with incremental builds is a symptom of the lack of modularization. Every single compilation unit has to pull in a ton of unrelated headers, either due to lack of forward declarations, or god objects. Getting rid of Globals.h on platforms that aren't using precompiled headers would have a huge impact.

**Comment by SafwatHalaby** [comment]
It's still a problem for incremental builds. Modifying `path.cpp` recompiles in a second. Modifying `path.h` can take 2 minutes to recompile. That's a bit inconvenient, and pimpl would have helped, but I can live with it.

**Comment by Seadragon91** [comment]
I tested the tool cppclean and checked the result file, there could be false positives. 
* 138 includes could be removed
* 47 could be changed to a forward declaration
* 54 forward declarations are not used
* Around 33 headers included twice (in cpp- and h-file or twice in h-file)
There are other things too, like `function declared but not defined`

Command, run from src directory:
`cppclean --include-path=. --include-path=src/Bindings/ --include-path=../lib/jsoncpp/include/ --include-path=../lib/ --include-path=../lib/polarssl/include/ --include-path=../lib/libevent/include/ --include-path=../lib/SQLiteCpp/include/ --include-path=../lib/TCLAP/include/ . > result.txt`

Would it be worth to do there anything?

**Comment by madmaxoft** [comment]
Definitely remove the includes that are duplicate or not needed (note that some platform-specific or configuration-specific dependancy might be present there that the tool didn't detect).

As for the forward declarations, change them if it makes sense; do it in a separate PR though so that the changes can be reviewed separately.
