### ISSUE TITLE
New Name Change

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#1464]
This is a proposal about changing the name of the project, rather than the server. The server would still be called MCServer, but it would be part of the Cuberite project.

This would involve moving the server to Cuberite/MCServer, and renaming the website to cuberite.org.

This would have all the advantages of changing the name but without any confusion, or loss of search engine rankings for the term "MCServer".

@FakeTruth, @tigerw Would you have any objections to this change?

**Comment by NiLSPACE** [comment]
I assume this can be closed right?

**Comment by tigerw** [comment]
I still hate you all ;-)

**Comment by SphinxC0re** [comment]
What do you mean? :triumph:

**Comment by NiLSPACE** [comment]
tigerw didn't like the name change. I didn't really care if it changed or not. As long as it was a nice name :)
