### ISSUE TITLE
Player moves too fast in creative mode

### ISSUE THREAD

**Issue by parabyte** [cuberite/cuberite#1468]
The latest changes in the server has indeed made it more stable. But also added this new bug. The player is moving way too fast in creative to be able to actually play comfortably.

**Comment by williamhatcher** [comment]
I'm pretty sure this has been solved by now, no?

**Comment by williamhatcher** [comment]
I'm pretty sure this has been solved by now, no?

**Comment by LogicParrot** [comment]
Probably. No one else reported this and creative seems to have normal speed in my tests.
