### ISSUE TITLE
Split up the code

### ISSUE THREAD

**Issue by w00tc0d3** [cuberite/cuberite#1475]
Hey,

Recently, I saw this project. I think it's a very cool idea, and it should definitely be continued. :)

However, I have a few remarks, namely:
- It might be better to split up the code in a core and a server repository; this way it's possible to write a client later on, and use the same codebase.
- The server has no plugin system for mods. I saw that plugins based on lua are supported, however, mods that add blocks, items, biomes, or any other functionality, aren't supported.

Over the next few days I'll try to fix bugs, and refactor the code in server, and core, in the case this idea gets accepted by the dev team.

Also, I'm a beginner when it comes to C++. I understand basic principles like pointers, OOP, pass-by-reference, but I'm by no means an outstanding programmer.

**Comment by mathiascode** [comment]
Closing due to age.
