### ISSUE TITLE
Mobs through gates

### ISSUE THREAD

**Issue by PoohSnack** [cuberite/cuberite#1505]
Chickens and pigs (only ones I've tested) are unable to get through open doors or open fence gates (even when enticed by feed). This is incorrect. 
A single block gap between double height blocks is (correctly) no barrier.

**Comment by SafwatHalaby** [comment]
This will be fixed as part of the AI overhaul, [see this](http://forum.mc-server.org/showthread.php?tid=1895).

**Comment by SafwatHalaby** [comment]
I've combined this with #2062
