### ISSUE TITLE
Mob collisions

### ISSUE THREAD

**Issue by PoohSnack** [cuberite/cuberite#1507]
Chickens, pigs and sheep can occupy the same space. Feeding several, they take up the same position, and merge to look like one.
Presumably not a bug, but just something still to be done. And likely part of a larger already-filed issue which I have not identified ?

I have been looking at the server from the point of view of a new survival player arriving in, say, Blockyland. Mining and crafting is largely fine, as is crop farming. The first big problems come trying to farm animals, particularly with no breeding yet.

If I seem to be picking some minor issues a little early, its because they are those first apparent to someone actually trying to play. And it isn't too soon for people to actually do that..I have started recommending blockyland to a few experimentally minded friends.

**Comment by SafwatHalaby** [comment]
I am planning to fix this by giving the PathFinder a higher G cost around other mobs, it should encourage them to spread. Didn't try it yet.

**Comment by SafwatHalaby** [comment]
In addition to the approach above, allowing the AI to ditch the pathfinder and simply move straight towards the player when a straight path exists reduces mob clipping. Mobs currently move snapped to the grid.

**Comment by SafwatHalaby** [comment]
This was fixed by someone. I can't tell which commit it was though. Does anyone know ?
