### ISSUE TITLE
API for Minigames

### ISSUE THREAD

**Issue by WebFreak001** [cuberite/cuberite#1508]
Lets face it: many plugins/servers are all about minigames. But every plugin uses another API for handling currency, arenas, player handling, etc. Wouldn't it be perfect to have an API for handling all that stuff? I mean even google has that thing and uses it for apps. Having an API like that for Plugins would be awesome because I think many new people will come then and try to create their own Minigame. (Global Point sharing across verified servers would be awesome too)

**Comment by mathiascode** [comment]
Closing due to age. If this is still something desirable, open a new issue.
