### ISSUE TITLE
PreSimulator forgets falling block meta

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#1516]
As seen here ![Pic](http://puu.sh/c4hXJ/f7e948ae4b.jpg) the pre simulator doesn't take meta's in consideration when making the sand fall.

**Comment by Seadragon91** [comment]
If I let red sand falling, it will be stay red. Fixed or a other problem?

**Comment by NiLSPACE** [comment]
This was an issue with the generator. I'm not sure if it was fixed.

**Comment by Seadragon91** [comment]
Okay didn't thought about the generator. Will look If I can check it.

**Comment by NiLSPACE** [comment]
I suggest using the ConstantBiome generator with the mesa biome.
