### ISSUE TITLE
Add Banners

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#1535]
http://minecraft.gamepedia.com/Banner

**Comment by theoduino** [comment]
I've begun work on this in my [repository](https://github.com/theoduino/cuberite/tree/banner). As of writing, I only have crafting of banners with no patterns, and no placing, but further work is underway.

**Comment by madmaxoft** [comment]
The wiki still doesn't fully explain how the banner stores its patterns when in the item form, and how exactly the emblazoning works (does it consume the item?)

**Comment by SphinxC0re** [comment]
The baner pattern is stored in a list of different changes made to the banner. http://minecraft.gamepedia.com/Banner#Block_entity

**Comment by madmaxoft** [comment]
But those are for the block entity, not for the item / pickup.

**Comment by madmaxoft** [comment]
Ah, the Player.dat format page has some info: http://minecraft.gamepedia.com/Player.dat_format#Item_structure
(in the Block Tags section)

**Comment by SphinxC0re** [comment]
Here is a little bit more information about the data structure: http://minecraft.gamepedia.com/Chunk_format#Banner

**Comment by LogicFan** [comment]
Is banner implementated now? I still cannot place any banner.
