### ISSUE TITLE
Server-side teleportation shouldn't call "HOOK_PLAYER_MOVING"

### ISSUE THREAD

**Issue by LO1ZB** [cuberite/cuberite#1538]
When a player got teleported, it shouldn't call "HOOK_PLAYER_MOVING" because it makes it impossible to know, if the player is moving normal, or if he got teleported. Couldn't a teleportation call a hook like "HOOK_PLAYER_TELEPORTING" or something simulator instead?

**Comment by joshi07** [comment]
i implemented the teleport hook, its calling both hooks (move + teleport) when you teleport. but only the moving hook when you move. but i dont know hot to do a pull request from my fork.

**Comment by joshi07** [comment]
there is a hook now #1790 for the teleport of all entities.

**Comment by avarun42** [comment]
Is this issue solved already then?

**Comment by Cl1608Ho** [comment]
Well, there is a hook for teleporting, but I'm not sure if a teleport still calls moving or not.
