### ISSUE TITLE
Redstone doesn't propagate through power rails

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1589]
When powering a powered rail, the power should propagate through the rail through several blocks; currently only one rail block is powered.

**Comment by simonwking** [comment]
Although this is an old issue has it been resolved yet?  I have a vast rail network which does not work on Cuberite but is fine on Vanilla.

**Comment by NiLSPACE** [comment]
There currently is a [Pull Request](https://github.com/cuberite/cuberite/pull/2542) open that **should** make it better, but according to @tigerw it doesn't fix it completely because of bugs.
