### ISSUE TITLE
Refactor the generator caches with templates

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1593]
The generator caches contain the same code, only with different classes and datatypes. Refactor them to use a single template-based implementation instead.

**Comment by SphinxC0re** [comment]
This has been solved with the prefabs, right?

**Comment by madmaxoft** [comment]
Not exactly, but it will not be too relevant once #2422 is merged. Leave it open until then.

**Comment by madmaxoft** [comment]
Closing, the PieceStructures generators have caused the various caches to diverge too much to be templateable.
