### ISSUE TITLE
README file in Cuberite directory is outdated.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#1599]
The protocol versions are incorrect, and it may point to the wrong website/contributors file.

**Comment by BijanKarrobi** [comment]
Is this issue still open or has it been resolved?  If it is open, which protocol versions are supported and which website/contributors would you like the file direct to?

**Comment by LogicParrot** [comment]
Is this referring to `README.md`? Looks pretty to date, to me.

**Comment by williamhatcher** [comment]
Please close this issue
