### ISSUE TITLE
End generator is broken

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#1627]
For a while now the End generator generates nothing but empty space.
It should look like something like this: ![Pic](http://hydra-media.cursecdn.com/minecraft.gamepedia.com/thumb/7/72/TheEnd.png/800px-TheEnd.png?version=5fd7be05609a0e9868517a536616f8ec)

**Comment by tigerw** [comment]
Possibly something to do with 5fb2526e0739fa27d925a686669f2c3aef56e825 on the 12th of November.

**Comment by NiLSPACE** [comment]
The End generation has changed in Minecraft with 1.9. It's now a center island with outer island much later on:
![map](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/thumb/d/d1/EnderIslandsRender.jpg/800px-EnderIslandsRender.jpg?version=2f9d48bf1d5d4e7847d6c232bc608d5c)
Note that the outer islands are generated indefinitely. Here is the information from the wiki: http://minecraft.gamepedia.com/The_End#Environment

**Comment by mathiascode** [comment]
Closing in favor of #4056
