### ISSUE TITLE
Hopper push hook creates error in console

### ISSUE THREAD

**Issue by Muph0** [cuberite/cuberite#1719]
Analogy to this issue https://github.com/mc-server/MCServer/issues/1641

My test plugin code looks just like this:

![image](https://cloud.githubusercontent.com/assets/10765858/5976723/92b915b0-a891-11e4-8ffa-ac1f4928300e.png)

Every time a hopper pushes an item, this error shows up:
[15:08:14] Lua engine: attempting to push a plain pointer, pushing nil instead.
[15:08:14] This indicates an unimplemented part of MCS bindings
[15:08:14] Stack trace:
[15:08:14] Stack trace end

The MyHopperPushingItem function executes ok, it's just spamming the console window.
tested on Win7 Home Premium & Raspberry pi

**Comment by Muph0** [comment]
I think it is similat to this one https://github.com/mc-server/MCServer/issues/1641
the problem is the HOOK_HOPPER_PUSHING_ITEM hook.

**Comment by Seadragon91** [comment]
Tested the hooks and didn't got any errors. Accessing the classes worked also fine.
