### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by XsFrozdY** [cuberite/cuberite#1722]
It would be awesome if the server could rank people automatically based on level, kills and/or block placement, a .ini file that is like: "(Promote: 1,2,3) for all, or (Promote: 1,2) for level and kills and so on"

Warps could be nice to have both the / command and signs, in addition if that plugin could handle multi-worlds aswell(I can ask Bergerkiller if you want to see if you could use his "myworlds" plugin that handles ALOT of great stuff, Link: http://dev.bukkit.org/bukkit-plugins/my-worlds/ I talk to him quite frequently on skype and he's not unresonable so I guess that it's a big possibillity that he'll allow you to use it link to MY tutorial I did for it: " https://www.youtube.com/watch?v=1IGYPoeMGv0 ").

Different inventories depending on what world you're in, for example, in the normal world, nether and the end you have your normal inventory, but in an added world you get another set of items that you had when you last left that world, this way you can have multi-worlds for different things, for example, you could then have an event world like survival games, one for creative and one for survival and you can't cheat by going to the creative world and then to any other and keep your inventory, just in those specific worlds.

**Comment by worktycho** [comment]
It is impossible to reuse bukkit plugins without a complete rewrite. Their are many fundamental differences between the plugin APIs, starting with the fact that we use lua and bukkit plugins are written in Java.

**Comment by XsFrozdY** [comment]
I know that Tycho, but the feature ideas belong to myworlds, and as I said, I'm quite certain that I could get berger to allow MCServer to use those features, I know that it needs to be rewritten, but hey, the ideas are there, it's only to put them into code

**Comment by worktycho** [comment]
Game Mechanics do not belong to anyone, so there's no need to ask permission. Thats what confused be. It would be unlikely that anyone would want to copy a bukkit plugin exactly enough to cause issues with copyright/design right.

**Comment by tigerw** [comment]
I suppose the way to approach this is to port MyWorlds to Lua and run it as a MCS plugin, implementing API hooks should any be found lacking (instead of rewriting the server :P).

The suggestion should therefore probably go into the forum's Plugin Requests section.

**Comment by XsFrozdY** [comment]
I didn't mean that they should rewrite the server, jusst do what they did with "core" "ProtectionAreas" and such, make it built-in.
