### ISSUE TITLE
Server Shutdown on Nether Build

### ISSUE THREAD

**Issue by ateufel** [cuberite/cuberite#1735]
Whenever i try to switch to the Nether World and MCServer tries to generated it, the Server crashes. This is what i got in my last log:

```
     [19:32:06] Preparing spawn (world_nether): 1.50% (6/400; 5.62 chunks/s)
     [19:32:07] Preparing spawn (world_nether): 4.50% (18/400; 11.15 chunks/s)
     [19:32:08] Preparing spawn (world_nether): 7.75% (31/400; 12.66 chunks/s)
     [19:32:09] Preparing spawn (world_nether): 11.25% (45/400; 13.46 chunks/s)
     [19:32:10] Preparing spawn (world_nether): 14.75% (59/400; 13.13 chunks/s)
     [19:32:11] Preparing spawn (world_nether): 18.25% (73/400; 13.12 chunks/s)
     [19:32:12] Preparing spawn (world_nether): 21.75% (87/400; 13.61 chunks/s)
     [19:32:13] Preparing spawn (world_nether): 25.25% (101/400; 13.30 chunks/s)
     [19:32:14] Preparing spawn (world_nether): 28.75% (115/400; 13.31 chunks/s)
     [19:32:15] Preparing spawn (world_nether): 32.00% (128/400; 12.92 chunks/s)
     [19:32:16] Preparing spawn (world_nether): 35.50% (142/400; 13.10 chunks/s)
     [19:32:17] Preparing spawn (world_nether): 39.00% (156/400; 13.18 chunks/s)
     [19:32:18] Preparing spawn (world_nether): 42.50% (170/400; 13.44 chunks/s)
     [19:32:19] Preparing spawn (world_nether): 46.00% (184/400; 13.71 chunks/s)
     [19:32:20] Preparing spawn (world_nether): 49.25% (197/400; 12.92 chunks/s)
     [19:32:21] Preparing spawn (world_nether): 52.50% (210/400; 12.70 chunks/s)
     [19:32:22] Preparing spawn (world_nether): 56.00% (224/400; 13.47 chunks/s)
     [19:32:24] Preparing spawn (world_nether): 59.50% (238/400; 13.27 chunks/s)
     [19:32:25] Preparing spawn (world_nether): 63.00% (252/400; 13.93 chunks/s)
     [19:32:26] Preparing spawn (world_nether): 66.50% (266/400; 13.20 chunks/s)
     [19:32:27] Preparing spawn (world_nether): 70.25% (281/400; 14.45 chunks/s)
     [19:32:28] Preparing spawn (world_nether): 74.00% (296/400; 14.19 chunks/s)
Err  [19:32:29] Deadlock detected, aborting the server
Err  [19:32:29]   D:    | MCServer has encountered an error and needs to close
Err  [19:32:29] Details | SIGABRT: Server self-terminated due to an internal fault
```

Btw, i am running the ARM build #12 from here: http://builds.cuberite.org/job/MCServer%20Linux%20armhf/lastSuccessfulBuild/artifact/MCServer/
(Raspberry 2)

**Comment by SphinxC0re** [comment]
The prebuilt binaries are only for the Raspberry PI. The RPI2 has a different processor architecture. You should try to compile it yourself and generate again.

**Comment by ateufel** [comment]
oh, makes sense. that would explain a lot...i will try compiling it then.

**Comment by ateufel** [comment]
Alright, i tried to compile on my Raspberry 2 and it generates the MCServer folder with a lot of stuff - but there is no MCServer executable and no settings.ini (well, i assume that one i could just create on my own). There are some "failed" and "not found" messages in the build process, even though it looks ok:

	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_IN6_SIN6_LEN
	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_IN6_SIN6_LEN - Failed
	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_IN_SIN_LEN
	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_IN_SIN_LEN - Failed
	-- Check size of struct sockaddr_storage
	-- Check size of struct sockaddr_storage - done
	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY
	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY - Success
	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_STORAGE___SS_FAMILY
	-- Performing Test EVENT__HAVE_STRUCT_SOCKADDR_STORAGE___SS_FAMILY - Failed
	-- Looking for include file pthread.h
	-- Looking for include file pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - found
	-- Found Threads: TRUE
	including polarssl
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/pi/MCServerRaspi2/Release

**Comment by ateufel** [comment]
Files in the generated MCServer folder:
 	-rw-r--r--  1 pi pi 28345 Feb  9 21:22 crafting.txt
	-rw-r--r--  1 pi pi  9265 Feb  9 21:22 favicon.png
	-rw-r--r--  1 pi pi  3782 Feb  9 21:22 furnace.txt
	-rw-r--r--  1 pi pi   396 Feb  9 21:22 .gitignore
	-rwxr-xr-x  1 pi pi   315 Feb  9 21:22 hg
	-rw-r--r--  1 pi pi   583 Feb  9 21:22 hg.supp
	-rw-r--r--  1 pi pi 15152 Feb  9 21:22 items.ini
	drwxr-xr-x  2 pi pi  4096 Feb  9 21:22 lang
	-rw-r--r--  1 pi pi  2754 Feb  9 21:22 monsters.ini
	drwxr-xr-x 16 pi pi  4096 Feb  9 21:22 Plugins
	-rw-r--r--  1 pi pi  2808 Feb  9 21:22 profile_run.cmd
	-rw-r--r--  1 pi pi   162 Feb  9 21:22 profile_run_debug.cmd
	-rw-r--r--  1 pi pi   149 Feb  9 21:22 profile_run_x64.cmd
	-rw-r--r--  1 pi pi   730 Feb  9 21:22 README.txt
	-rw-r--r--  1 pi pi   534 Feb  9 21:22 settings_apidump.ini
	-rwxr-xr-x  1 pi pi   375 Feb  9 21:22 vg
	-rw-r--r--  1 pi pi     0 Feb  9 21:22 vg.supp
	drwxr-xr-x  3 pi pi  4096 Feb  9 21:22 webadmin

**Comment by ateufel** [comment]
well, after removing the MCServer and Release folders and trying to compile again, i don´t get any file in MCServer anymore - only the empty folder gets created :(

**Comment by Seadragon91** [comment]
Small question did you run make in the Release folder?

**Comment by ateufel** [comment]
Yes, i followed this: https://github.com/mc-server/MCServer/blob/master/COMPILING.md

    mkdir Release
    cd Release
    cmake -DCMAKE_BUILD_TYPE=RELEASE ..

**Comment by Seadragon91** [comment]
Well I miss the command `make`.
```
Follow the instructions at CMake on Unix-based platforms, using Xcode as cmake's generator. If no generator is specified, CMake will use the Makefile generator, in which case you must build with the make command.
```

**Comment by tigerw** [comment]
About the new world (i.e. Nether spawning) code, it requires improvement as in it more or less blocks a world thread until the new world finishes generating. So, if generation is slow (such as it is on a RasPi), the deadlock detector thinks something froze and explodes. So that's a bug.

The build output looks awfully short; as the sea dragon said above, make sure to run `make -j 4` to build with 4 threads, if haven't done so already.

**Comment by bearbin** [comment]
You need to run make after cmake.

On 9 February 2015 at 21:18, Andreas Teufel <notifications@github.com>
wrote:

> Yes, i followed this:
> https://github.com/mc-server/MCServer/blob/master/COMPILING.md
>
> mkdir Release
> cd Release
> cmake -DCMAKE_BUILD_TYPE=RELEASE ..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1735#issuecomment-73592186>.
>



-- 

Alexander Harkness (bearbin)
Find my GPG key on the Ubuntu Keyserver - http://keyserver.ubuntu.com:11371/

**Comment by Seadragon91** [comment]
Well yes, I think it would be good to update the COMPILING.md a litte, to reflect the `make step` better.

**Comment by ateufel** [comment]
Oh. Well, i am sorry, i am a n00b with that Linux compiling stuff :)
So i ran "make -j 4" in the Release folder. Does not really work, here´s the whole console output this time:

	Scanning dependencies of target jsoncpp
	Scanning dependencies of target zlib
	Scanning dependencies of target SQLiteCpp
	Scanning dependencies of target lua
	[  0%] Building CXX object lib/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o
	[  0%] cc1plus: error: unrecognized command line option â-std=c++11â
	cc1plus: error: unrecognized command line option â-std=c++11â
	[  0%] lib/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/build.make:54: recipe for target 'lib/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o' failed
	make[2]: *** [lib/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o] Error 1
	CMakeFiles/Makefile2:363: recipe for target 'lib/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/all' failed
	make[1]: *** [lib/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/all] Error 2
	make[1]: *** Warte auf noch nicht beendete Prozesse...
	Building CXX object lib/jsoncpp/CMakeFiles/jsoncpp.dir/src/lib_json/json_value.cpp.o
	Building C object lib/zlib/CMakeFiles/zlib.dir/inftrees.c.o
	[  1%] cc1plus: error: unrecognized command line option â-std=c++11â
	cc1plus: error: unrecognized command line option â-std=c++11â
	lib/jsoncpp/CMakeFiles/jsoncpp.dir/build.make:54: recipe for target 'lib/jsoncpp/CMakeFiles/jsoncpp.dir/src/lib_json/json_value.cpp.o' failed
	make[2]: *** [lib/jsoncpp/CMakeFiles/jsoncpp.dir/src/lib_json/json_value.cpp.o] Error 1
	CMakeFiles/Makefile2:75: recipe for target 'lib/jsoncpp/CMakeFiles/jsoncpp.dir/all' failed
	make[1]: *** [lib/jsoncpp/CMakeFiles/jsoncpp.dir/all] Error 2
	[  1%] Building C object lib/zlib/CMakeFiles/zlib.dir/adler32.c.o
	Building C object lib/zlib/CMakeFiles/zlib.dir/inffast.c.o
	[  1%] Building C object lib/lua/CMakeFiles/lua.dir/src/lzio.c.o
	[  1%] Building C object lib/zlib/CMakeFiles/zlib.dir/gzread.c.o
	[  1%] Building C object lib/zlib/CMakeFiles/zlib.dir/gzwrite.c.o
	[  2%] Building C object lib/zlib/CMakeFiles/zlib.dir/gzlib.c.o
	[  2%] Building C object lib/lua/CMakeFiles/lua.dir/src/lauxlib.c.o
	[  2%] Building C object lib/zlib/CMakeFiles/zlib.dir/deflate.c.o
	[  2%] [  2%] Building C object lib/zlib/CMakeFiles/zlib.dir/zutil.c.o
	Building C object lib/zlib/CMakeFiles/zlib.dir/crc32.c.o
	[  2%] Building C object lib/zlib/CMakeFiles/zlib.dir/gzclose.c.o
	[  2%] Building C object lib/lua/CMakeFiles/lua.dir/src/ldump.c.o
	[  3%] Building C object lib/zlib/CMakeFiles/zlib.dir/uncompr.c.o
	[  3%] Building C object lib/zlib/CMakeFiles/zlib.dir/trees.c.o
	[  4%] [  4%] Building C object lib/lua/CMakeFiles/lua.dir/src/lopcodes.c.o
	Building C object lib/zlib/CMakeFiles/zlib.dir/inflate.c.o
	[  4%] Building C object lib/lua/CMakeFiles/lua.dir/src/lvm.c.o
	[  4%] Building C object lib/zlib/CMakeFiles/zlib.dir/infback.c.o
	[  5%] [  5%] Building C object lib/lua/CMakeFiles/lua.dir/src/lstate.c.o
	Building C object lib/zlib/CMakeFiles/zlib.dir/compress.c.o
	[  5%] Building C object lib/lua/CMakeFiles/lua.dir/src/ldebug.c.o
	Linking C static library libzlib.a
	[  6%] Building C object lib/lua/CMakeFiles/lua.dir/src/lstring.c.o
	[  6%] Built target zlib
	[  6%] [  6%] Building C object lib/lua/CMakeFiles/lua.dir/src/lparser.c.o
	Building C object lib/lua/CMakeFiles/lua.dir/src/loslib.c.o
	[  6%] Building C object lib/lua/CMakeFiles/lua.dir/src/lgc.c.o
	[  6%] [  7%] Building C object lib/lua/CMakeFiles/lua.dir/src/ltable.c.o
	Building C object lib/lua/CMakeFiles/lua.dir/src/lobject.c.o
	[  7%] [  7%] Building C object lib/lua/CMakeFiles/lua.dir/src/ltm.c.o
	Building C object lib/lua/CMakeFiles/lua.dir/src/ltablib.c.o
	[  7%] Building C object lib/lua/CMakeFiles/lua.dir/src/ldo.c.o
	[  7%] Building C object lib/lua/CMakeFiles/lua.dir/src/ldblib.c.o
	[  8%] Building C object lib/lua/CMakeFiles/lua.dir/src/lapi.c.o
	[  8%] Building C object lib/lua/CMakeFiles/lua.dir/src/linit.c.o
	[  8%] [  8%] Building C object lib/lua/CMakeFiles/lua.dir/src/liolib.c.o
	Building C object lib/lua/CMakeFiles/lua.dir/src/print.c.o
	[  9%] Building C object lib/lua/CMakeFiles/lua.dir/src/lundump.c.o
	[  9%] Building C object lib/lua/CMakeFiles/lua.dir/src/llex.c.o
	[  9%] Building C object lib/lua/CMakeFiles/lua.dir/src/lfunc.c.o
	[  9%] [  9%] Building C object lib/lua/CMakeFiles/lua.dir/src/lbaselib.c.o
	Building C object lib/lua/CMakeFiles/lua.dir/src/loadlib.c.o
	[ 10%] Building C object lib/lua/CMakeFiles/lua.dir/src/lmathlib.c.o
	[ 10%] Building C object lib/lua/CMakeFiles/lua.dir/src/lmem.c.o
	[ 10%] Building C object lib/lua/CMakeFiles/lua.dir/src/lcode.c.o
	[ 10%] Building C object lib/lua/CMakeFiles/lua.dir/src/lstrlib.c.o
	Linking C static library liblua.a
	[ 10%] Built target lua
	Makefile:113: recipe for target 'all' failed
	make: *** [all] Error 2

**Comment by SphinxC0re** [comment]
Did you do:

mkdir MCServer
cd MCServer
git clone https://github.com/mc-server/MCServer.git .
git submodule init
git submodule update

??

**Comment by madmaxoft** [comment]
Raspbian comes with gcc 4.6 by default, you need to upgrade to gcc 4.8 before building. Simply execute these commands one by one, then retry the `make` step:
```
sudo apt-get update
sudo apt-get install gcc-4.8 g++-4.8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 20
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
```

But I think an easier solution would be to add the nether world to the list of worlds in settings.ini:
```ini
[Worlds]
DefaultWorld=world
World=world_nether
```

**Comment by ateufel** [comment]
@SphinxC0re yup, i did all that.
@madmaxoft thanx for the info about gcc, will try that one later. also added the nether world to the settings.ini, great idea! it generated the nether world and i was able to move through the portal!

**Comment by ateufel** [comment]
should i close this issue or leave it open? it is a bug after all...

**Comment by madmaxoft** [comment]
Keep it open so that the bug is fixed.
Actually, I thought I fixed this some time ago, by disallowing portals into worlds that are not specified in settings.ini; I must have missed something.

**Comment by Seadragon91** [comment]
@madmaxoft 
The last build for armhf is 1 month and 15 days ago. If the fix is older than this build, then this build won't have the fix.

**Comment by bearbin** [comment]
Sorry about that. I've pushed off another armhf build and hopefully fixed
the issue for the future.

On 10 February 2015 at 11:19, Seadragon91 <notifications@github.com> wrote:

> @madmaxoft <https://github.com/madmaxoft>
> The last build for armhf is 1 month and 15 days ago. If the fix is older
> than this build, then this build won't have the fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1735#issuecomment-73683660>.
>



-- 

Alexander Harkness (bearbin)
Find my GPG key on the Ubuntu Keyserver - http://keyserver.ubuntu.com:11371/

**Comment by tigerw** [comment]
> Actually, I thought I fixed this some time ago, by disallowing portals into worlds that are not specified in settings.ini; I must have missed something.

It was discussed, and my point was that it would be inconsistent with what everyone would expect (portals work with no extra configuration).

**Comment by NiLSPACE** [comment]
Coming back to this. Moving through portals to a world that doesn't exist creates a deadlock due to the use cRoot::CreateAndInitializeWorld(). Shouldn't we disable that?

**Comment by madmaxoft** [comment]
There are two sides to this that need to be considered:
- A newbie user downloads MCServer and tries going to Nether. They should be able to do so without configuring anything in the server
- A server admin specifically configures worlds to their liking. They don't want a nether portal to create an unexpected new world.

So to fix this issue, I think these steps produce the best scenario results:
- When there's no DefaultWorld in settings.ini, three worlds get created - Overworld, Nether and End. They get linked properly in their world.ini settings
- When all worlds are loaded, their nether and end linkage is checked. If any points to an unknown world, an error is displayed in the console and the linkage is disabled.

Corner cases:
- DefaultWorld is defined, but the folder doesn't exist: do not create linkage
- World linkage points to the same world: report and disable the linkage

**Comment by NiLSPACE** [comment]
Sounds perfect.

**Comment by Kellerkind85** [comment]
Hi there,
are there news to this Issue?
I am still having a deadlock Error. and i am having it exactly at the same point as ateulfel on 74%.

There is a new folder called wolrd_nether or something like that. But its still crashing if i try to use my Portal.

**Comment by madmaxoft** [comment]
@Kellerkind85 you need to add the nether world (and possibly the end world, too) to the list of worlds in settings.ini:
```ini
[worlds]
DefaultWorld=world
World=world_nether
World=world_end
```

**Comment by Seadragon91** [comment]
This should be fixed as the `settings.ini` contains the three worlds and they are all generated on startup.
