### ISSUE TITLE
Cannot put equal sign in sign text

### ISSUE THREAD

**Issue by carc1n0gen** [cuberite/cuberite#1736]
Today i found out I cannot put an equal sign in the text of any signs.  Instead I get some weird special escaped text.

![Cannot enter equal sign in sign text](http://i60.tinypic.com/2aeys92.png)

**Comment by LO1ZB** [comment]
Could you make an screenshot at daytime?
I cant see a thing on it.

**Comment by carc1n0gen** [comment]
Here is a day time picture.

![day time picture](http://i60.tinypic.com/2wgbssk.png)

**Comment by madmaxoft** [comment]
Probably something with json formatting / escaping.

**Comment by Masy98** [comment]
thats the UFT8-code for an equal. The one for § is for example is \u00A7 and is needed i.e. if you want colored motd in bukkit because it doesn't accept "§".
