### ISSUE TITLE
Add a cServer:ScheduleTask() API function

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1754]
If a plugin needs to schedule server-global tasks, there's no way to do that other than scheduling it in a world's tick thread. This is less than optimal, since worlds are created only after plugins are initialized, so the code has a needless overhead.

We need a `cServer:ScheduleTask(NumTicksToWait, FunctionToCall)` API function which the plugins could call right in their `Initialize()` method.

This should be a relatively easy task, the implementation should mostly follow the `cWorld:ScheduleTask()` API function.

**Comment by Sulfatezzz** [comment]
Great idea!

**Comment by SamJBarney** [comment]
So how many tasks should get called per server tick? Or should we just blow through all of them?

**Comment by feyokorenhof** [comment]
I would like to try implementing this for my first contribution. However, this issue has been open for over 6 years x). 
Is it still a desired functionality?

**Comment by tigerw** [comment]
Yeah, it is needed. See the linked #4662 for a potential use-case. Thanks!

**Comment by feyokorenhof** [comment]
I'd be happy to give it a shot. I have the project running right now and I believe I have a basic understanding of the wanted behaviour. Would it be okay if I ask any questions, regarding the implementation, in this issue?

**Comment by tigerw** [comment]
Of course. I believe the implementation should be a transplant of the existing cWorld::QueueTask/ScheduleTask stuff but onto cServer.

**Comment by feyokorenhof** [comment]
I have copied those methods into the cServer class and I am able to call them from lua. The thing I noticed is that cWorld doesn't have those methods in a // tolua_being // tolua_end section even though it is still callable. 
Is there a method/file somewhere that exposes these functions to the plugins along with parameter types?
When I call Server:ScheduleTask(500, callable) I get an error saying that the parameter should be of time cTickTime.

**Comment by tigerw** [comment]
They are exported manually in Bindings/ManualBindings_World.cpp, exactly to export the cTickTime properly :)

**Comment by feyokorenhof** [comment]
Haha yeah I found the bindings a few minutes after I posted :). 

If I understand correctly, the cServer::TickQueuedTasks should also expose a cWorld instance to the lambda, not a cServer instance? In cWorld::TickQueuedTasks this is quite easy as you can just pas *this to get the world the command was issued in. 
Should the server implementation get the default world or should the user have the ability to specify a certain world?

Right now for testing I am just calling cRoot::Get()->GetDefaultWorld() to get the world and m_WorldAge to check if tasks are due.

**Comment by feyokorenhof** [comment]
Haha yes I found them right after I posted it. 

I think I got it working (kinda). I am testing it from within a lua plugin and I am able to call GetNumPlayers() and all the other cServer commands by scheduling a task.

One thing that isn't clear to me:

Since cServer doesn't have a property like m_WorldAge I am currently getting the default world and calling GetWorldAge() to determine if a task is due for execution. Is there a solution for this already or should the cServer also have some sort of 'age' property.

**Comment by tigerw** [comment]
Good point, in that case a `cTickTimeLong m_Uptime` field in cServer could work, tracked/updated similarly as m_WorldAge.

**Comment by feyokorenhof** [comment]
After some testing I think it works as expected. Now I have to figure out how pull requests work... :)

My commits to my fork messed up some formatting and I didn't create a new branch before I made my changes :/

**Comment by 12xx12** [comment]
To open up a PR you need to push the repository to the Server and then the webinterface will give you an option to create a PR. Then some automated processes will check the new code and then you can see your changes and we can suggest changes or accept it
