### ISSUE TITLE
Integrate git revision info into source

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1766]
We should integrate git revision info into the sources at build-time even for builds not produced in our CI / Jenkins builds.

This SO should provide us with everything we need:
http://stackoverflow.com/a/4318642/4084740

There's only one consideration, though - if the host compiling the sources doesn't have git installed (they downloaded the zip sources), the build should not fail, but it's acceptable for it to return (preferably reproducible) bogus values.

The git revision should then be output to the log on server startup and made accessible to Lua API.

**Comment by worktycho** [comment]
We already have the code for determining the git commit. See https://github.com/mc-server/MCServer/blob/master/CMakeLists.txt#L29 . The only reason that we don't do this at the moment for all builds is the idea was that if you build the source yourself then you should know what the version is.

**Comment by madmaxoft** [comment]
But that works only for when you run cmake - which doesn't happen when you pull changes from origin. The linked answer solves that as well, it is said to re-run every time your currently checked out commit changes.

This is useful for people who compile MCS for themselves, then update the sources to try a newer version etc. When they report bugs, it would be nice to have the information on their commit SHA.

**Comment by KingCol13** [comment]
This can be closed.
