### ISSUE TITLE
spectator mode bugs / missing features

### ISSUE THREAD

**Issue by Zauberfisch** [cuberite/cuberite#1772]
I have just finished installing and imported my existing world. 
It seems that npcs are aware of me even though I am in spectator mode. They follow me and creepers even explode.

details that might be relevant:
- Gamemode=3 (spectator mode, in world.ini)
- world folder is copied from vanilla server
- running windows x64
-  MCServer  build id: 182 (from commit a56b6906d60f5b511aeb93cf765359634e4bcf6e)

---

EDIT: I found a lot of other issues, so I collected them into a list:
- [ ] NPCs follow a spectator
- [ ] creepers will explode near a spectator
- [ ] spectator can attack/kill animals
- [ ] spectator can pick up items
- [ ] spectator can not spectate npcs (when you left click an npc as spectator, you should see the world through the eyes of the npc)
- [ ] spectator can interact with items as well (chests, doors)
- [ ] spectator can use inventory
- [ ] spectator can craft
- [ ] after re-aranging items in the inventory, a spectator is able to build (unlimited) blocks that he have in his inventory on slot 1. (eg 3 stone blocks in slot 1 => build unlimited stone blocks (seems to work with all items, but the item has to be moved to slot 1, other slots do not work))

**Comment by madmaxoft** [comment]
Nice catch, thank you.

**Comment by Zauberfisch** [comment]
do you guys prefer individual tickets or collections of related issues?

Because on the topic of spectator mode I noticed the following other issues:
- I can use my inventory
- I can attack/kill animals
- I can pick up items
- I can not spectate npcs (when you left click an npc as spectator, you should see the world through the eyes of the npc)

**Comment by madmaxoft** [comment]
In this case we'll use a single issue, because the entire spectator mode is kinda not implemented. It's there so you can choose it, but there's not much handling for it.

**Comment by Zauberfisch** [comment]
yeah, I am getting that feeling. will rename the issue and create a full list in the original message.

**Comment by Zauberfisch** [comment]
done.

Also, let me point out that I actually think spectator is an important feature.
We use spectator as a sort of soft white-listing (instead of whitelist or build protection) to allow others to connect to our server and take a look, but stop them from doing anything unless they receive build permissions from the admins.
