### ISSUE TITLE
Animal breeding doesn't work

### ISSUE THREAD

**Issue by Kellerkind85** [cuberite/cuberite#1785]
I really hope i don't start to bother you guys. You did a great Job with your Server. buuuut.....

Animals wont breed. They enter "love Mode" but then nothing happens. I saw this Problem in a Forum was already mentioned, but couldn't find it here so i write it down.

And Animals are able to climb over fences. I need to build them 2blocks hight to prevent it.
And i needet to build 2 fence doors... that kinda look silly but it will work for now.

**Comment by M10360** [comment]
From what I can tell, no animal breeding was ever implemented. Will look into the fence issue.

**Comment by Seadragon91** [comment]
Implemented in #2696.
