### ISSUE TITLE
Undefined Overflow/Cast Behavior in cBioGenMulticache hash function.

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#1798]
The `cBioGenMulticache` hash function uses casts to unsigned types on signed values and then multiples the results. The cast is undefined behaviour on its own and because it tends to result in a large value this then results in undefined behaviour in the multiplication. This should be changed to avoid casting negative values to unsigned.

**Comment by worktycho** [comment]
cHeiGenCache uses the same function so suffers from the same issues.

**Comment by gauraVsehgaL** [comment]
`static_cast<size_t>(a)` if `a` is negative then this would return `a+UINT_MAX+1` which will be very large result.So what should be done if `a` is negative.Should it not be casted down to `unsigned`.And i think when `a` is positive then there is no concern.

**Comment by madmaxoft** [comment]
Closing without a reason is somewhat rude, how do we know what's going on?

**Comment by worktycho** [comment]
Its fine when its my own issue.
