### ISSUE TITLE
MakeIntGen should be able to infer sizes

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#1825]
MakeIntGen should be able to Infer the sizes of the gen based on the size of the underlying generator.

Since every descendent of cIntGen knows how big the underlying generator should be based on the SizeX paramater, it should be trivial meta-programming to calculate the size of the generator based on the size of the underlying generator using a constexpr function.

**Comment by worktycho** [comment]
Not actually possible, because for a `cIntGen<X,Z>` there are actually two potential instances of`cIntGenZoom` we can apply to it. `cIntGenZoom<(X- 2) * 2, (Z - 2) * 2>` and `cIntGenZoom<(X-2) * 2 + 1, (Z - 2) * 2 + 1>`

**Comment by madmaxoft** [comment]
Isn't it the other way around? The zoom dictates the size of its underlying data source.

**Comment by worktycho** [comment]
Trying to do it in that direction has the problem that the operators are left associative but we want to build from the right. Only ways around that I'm aware of a polymorphic factories (Meaning heap allocations) and expression templates. Neither of which I'm a fan of.
