### ISSUE TITLE
Bonemeal shouldn't do an immediate growth

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#1827]
Hey.

If bonemeal is used, it shouldn't do an inmeditate growth anymore. There is now a chance for a growth of 2-5 stages. Trees also has a chance of growing. Here a link that contains a list.
http://minecraft.gamepedia.com/Bonemeal#Fertilizer

**Comment by madmaxoft** [comment]
I've reworded the issue for better clarity. My first impression was that "bonemeal stopped working" instead of "we should change bonemeal behavior".
