### ISSUE TITLE
Crash due to deadlock shortly after start

### ISSUE THREAD

**Issue by jbulow** [cuberite/cuberite#1850]
OS: Ubuntu 14.04.
MCServer: 1.8.3 (downloaded pre-built for linux 64-bit)

Started MCServer. Logged in to web gui (using https). Then add a player under "Player Ranks". Crash!

(I have not yet connected a minecraft client)

**Comment by madmaxoft** [comment]
Is there a message in the server's log? Any more info in the server output on-screen? Is there a Core file? Can you reproduce the issue reliably, does it happen again if you retry the steps you took?

**Comment by madmaxoft** [comment]
There's a guide on the forums for providing as much detail as possible for crashes, you might want to have a look: http://forum.mc-server.org/showthread.php?tid=631

**Comment by tigerw** [comment]
Migrating to #1853.
