### ISSUE TITLE
Unknown soundEvent (missing sounds) for certain mobs

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#1866]
Iron Golems, MagmaCubes and Guardians throw the following errors in Game Output:

When interacting with Guardians (hitting & killing): "Unable to play unknown soundEvent: minecraft:damage.thorns"

When interacting with MagmaCubes (hitting & killing): "Unable to play unknown soundEvent: minecraft:mob.MagmaCube.big". This can be solved by changing MagmaCube to magmacube. (also, MagmaCubes should use GetSizeName like slimes, to get the correct sound for big and small MagmaCubes)

**Comment by Tri125** [comment]
My pull request #1956 deal with the MagmaCubes sound.
