### ISSUE TITLE
No sound for lightning

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#1868]
Currently, there is no sound for lightning.

**Comment by pillsbury7901** [comment]
Hello, I would like to contribute. I am new to GitHub and would like to know how to get sarted reproducing this bug. I would very much appreiate any feedback. Thanks in advance.

**Comment by bearbin** [comment]
@pillsbury7901 If you haven't already, you should read this document: https://github.com/mc-server/MCServer/blob/master/CONTRIBUTING.md

The easiest way to reproduce this bug would be to start a server and change the weather to stormy, so that a lightning strike will occur every so often.

**Comment by bearbin** [comment]
Sorry, wrong document. You should read that one too, but this one is more important for a newcomer to the project: 

https://github.com/mc-server/MCServer/blob/master/GETTING-STARTED.md

**Comment by pillsbury7901** [comment]
Thank you for the response. I have been trying to compile MCServer for the past few days to no avail. Do you have any suggestions for compiling on a linux box? I believe the error is related to gcc but I have not been able to remedy this issue. Thanks again.

**Comment by worktycho** [comment]
Its probably a gcc version that does not support c++11. Check gcc --version, and if its less than gcc 4.8 then you need to install a more recent gcc.

**Comment by pillsbury7901** [comment]
This is what i feared. When I attempt to update with apt-get or aptitude it says that I have the latest version installed. I have downloaded gcc-5.1.0 and followed the installation instructions from the Documentation precisely but I am still getting the same error.

**Comment by worktycho** [comment]
If you've got multiple versions of gcc installed it may be that you're calling the wrong one. Try `which gcc` and if thats wrong, specify the path to the correct one when calling cmake, like `CC=<path/to/gcc> CXX=<path/to/g++> cmake`

**Comment by pillsbury7901** [comment]
Thank you. I will try this now.

**Comment by pillsbury7901** [comment]
Question, must I buy a Minecraft Client to debug and fix code for this project?

**Comment by madmaxoft** [comment]
There are tasks that don't require any interaction with the client; as far as I know @worktycho isn't using a client at all. But of course majority of tasks will require some form of verification through the client interface. So it really depends on what you want to be doing.
This particular task requires a client to verification that a fix is indeed working.
