### ISSUE TITLE
Issues with Chests

### ISSUE THREAD

**Issue by default0** [cuberite/cuberite#1871]
Chests and trapped chests cannot be opened if a non-solid block is on top of them (such as another chest, a lever, a trapdoor, a slab, a leaf, glass, etc).
Ender Chests can always be opened, even if a solid block is on top of them.

Further, placing down a chest or a trapped chest does not remove it from your inventory (it reappears the next time your inventory re-syncs).

**Comment by nounoursheureux** [comment]
@madmaxoft @tigerw @SphinxC0re it is fixed now so the issue should be closed :+1:
