### ISSUE TITLE
Server thinks a player is still connected after the connection was dropped/lost

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#1895]
From time to time it occurs that players have a bad connection and it is severed from or by the server. But the server still thinks that player is connected, indefinitely. If there are any checks to see if the client is still responding in time or if it's even there, they don't always work.

That player cannot re-connect and keep playing.
Kicking the player manually isn't possible, either:

```
[12:07:36] Executing console command: "kick Sledgie65"
[12:07:36] LUA: 2 - Plugins/Core/functions.lua:26: attempt to index a nil value players
```

**Comment by worktycho** [comment]
I don't know if this is the same issue or a separate issue but there is a race condition in cRoot::FindAndDoWithPlayer. Because the FindAndDoWithPlayer callback is called outside the cRoot::ForEachPlayer callback there is the possibility that a player could get deleted either before or during the FindAndDoWithPlayer callback.

**Comment by wiseoldman95** [comment]
Not sure if it's related but: I also observed that some servers never timeout inactive TCP connections, interestingly, other servers do, and they always send the same message before disconnecting you (forgot what that message is). It could be that the latter type of servers have activated a plugin which the former did not, or it could be a version thing, I am not entirely sure.

**Comment by jammet** [comment]
Got tonights latest build ... it's happening again.

In addition to that the player has lost his connection multiple times. Not sure if that has anything to do with the server, so... make of that what you will.

Tried to kick his ghost connections again because again, they kept him from rejoining.

```
[02:32:26] LUA: Plugins/Core/functions.lua:26: attempt to index a nil value
[02:32:26] Stack trace:
[02:32:26]   Plugins/Core/functions.lua(26): (no name)
[02:32:26]   [C](-1): FindAndDoWithPlayer
[02:32:26]   Plugins/Core/functions.lua(30): KickPlayer
[02:32:26]   Plugins/Core/kick.lua(16): (no name)
[02:32:26]   [C](-1): FindAndDoWithPlayer
[02:32:26]   Plugins/Core/kick.lua(20): (no name)
[02:32:26] Stack trace end
[02:32:26] Error in <attached> calling function <callback>()
```

**Comment by Howaner** [comment]
MCServer do nothing to close the connection at a kick.
So yeah, its a bug.

**Comment by SafwatHalaby** [comment]
@falkseidl made [this short bug demo video](https://www.youtube.com/watch?v=h88mpbLLYTw).

**Comment by SafwatHalaby** [comment]
I observed that `minecraft.planetx.com` DOES time you out, at least in plain-telnet connections, I didn't test it with a game client. 
What is special about `minecraft.planetx.com`, is it the version? Perhaps a plugin?

**Comment by SafwatHalaby** [comment]
I found the code responsible for kicking players at `minecraft.planetx.com`. Why isn't it triggered for other servers?
[src/ClientHandle.cpp, line 1904](https://github.com/mc-server/MCServer/blob/4888f671d15c47cf79b289a72fb5068cc6a6e35b/src/ClientHandle.cpp#L1904)

**Comment by jammet** [comment]
A friend keeps dropping out because of a faulty connection (on his side) still, but the server doesn't let him back in because the connection wasn't dropped by the server, too. So yeah, this is a problem.

**Comment by worktycho** [comment]
@jammet I closed the issue by accident.

**Comment by SafwatHalaby** [comment]
Should I mark the issue as "important"? (Meaning it should be fixed in testing before the next stable)

**Comment by mathwhiz1212** [comment]
Same issue on my server. Restarting is the only thing that fixes it.
