### ISSUE TITLE
It's raining too much

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#1900]
I know, this is a bit petty, but after running the server for two months. Almost every player keeps telling me to make it stop raining all the time. Make of that what you will ;). But I agree, it is indeed raining too much.

**Comment by madmaxoft** [comment]
I had the same impression, but never actually measured anything. I'm writing a small plugin to do the statistics:
https://github.com/madmaxoft/WeatherWatch

**Comment by jammet** [comment]
I'll run this. If you want to collect the data remotely, I'm cool with that too.

**Comment by madmaxoft** [comment]
I think it would be enough if you reload plugins after a day of running (thus generating the long-term statistics) and then upload the resulting logfile somewhere.

**Comment by jammet** [comment]
I can't reload, if I do that, according to the readme of NoChunkFall,
something bad will happen. Is stopping the server gonna do this, too? I
never use restart/reload, I just do a full 'stop', and while true; do sleep
5; ./MCServer ; done takes care of the rest.

**Comment by jammet** [comment]
And is it normal that nothing is written into weather.log the entire time?
The file is bank after the server has been running for several hours
already.

**Comment by NiLSPACE** [comment]
The file should only be written once the server reloads. At least that is what I suspect.

**Comment by jammet** [comment]
Stopped the server just to see what happened; we're not in a rush about
this. It writes the log quite nicely. I'll provide full 23h+  statistics
tomorrow or so. In the hours it's been running so far (9 hours or so):

```
World "world": weather changing from rain to sunny after 22485 ticks.
World "world": weather changing from sunny to rain after 26526 ticks.
World "world": weather changing from rain to sunny after 19237 ticks.
World "world": weather changing from sunny to rain after 20193 ticks.
World "world": weather changing from rain to sunny after 18551 ticks.
World "world": weather changing from sunny to rain after 21706 ticks.
World "world": weather changing from rain to sunny after 21285 ticks.
        Statistics for world "world":
                sunny has been active for 112528 ticks (43.65 %)
                It has become sunny 6 times and the average length was
18754 ticks.
                The weather has then transitioned to sunny 0 times, rainy 5
times and storm 0 times
                rain has been active for 139796 ticks (54.23 %)
                It has become rain 7 times and the average length was 19970
ticks.
                The weather has then transitioned to sunny 6 times, rainy 1
times and storm 1 times
                storm has been active for 5450 ticks (2.11 %)
                It has become storm 1 times and the average length was 5450
ticks.
                The weather has then transitioned to sunny 0 times, rainy 1
times and storm 0 times
```

**Comment by madmaxoft** [comment]
It doesn't flush the file explicitly, so it's up to the CRT / OS to decide whether to keep things in memory until more is written, or not. I guess I should add an explicit flush when the long-term statistics are written (and write those every hour or so).

I'm looking forward to your long stats.

**Comment by jammet** [comment]
Here's about a full day, give or take.

```
                sunny has been active for 718866 ticks (46.75 %)
                It has become sunny 34 times and the average length was 21143 ticks.
                The weather has then transitioned to sunny 1 times, rainy 33 times and storm 0 times
                rain has been active for 760147 ticks (49.44 %)
                It has become rain 43 times and the average length was 17677 ticks.
                The weather has then transitioned to sunny 33 times, rainy 0 times and storm 10 times
                storm has been active for 58600 ticks (3.81 %)
                It has become storm 10 times and the average length was 5860 ticks.
                The weather has then transitioned to sunny 0 times, rainy 10 times and storm 0 times
```

**Comment by DevToaster** [comment]
I'll write a workaround for NoChunkFall's reload issue eventually.  I believe a restart should be safe to use.  I also experience some excessive rain as well though.

**Comment by madmaxoft** [comment]
@jammet Could you `reloadplugins` and upload the entire weather log file somewhere?

**Comment by jammet** [comment]
Sorry I haven't been around as much for a few days. I'll let the server log another full week and then put it on pastebin for you :).

**Comment by jammet** [comment]
Not a full week yet but here are some more days for you:

http://pastebin.com/Wi6YUrTX

**Comment by SafwatHalaby** [comment]
Is this fixed?

**Comment by jammet** [comment]
Yes, the weather was completely overhauled a few months ago. :) :+1:

**Comment by SafwatHalaby** [comment]
:+1:
