### ISSUE TITLE
Change cChunk::m_BlockEntities into a std::map

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#1901]
Currently the block entities are stored in a list - that is highly inefficient for when there are more block entities in a chunk. A single chunk full of mobspawners takes a whopping 10 minutes to load on my laptop in a debug build; most of the time is spent checking whether a block entity exists at the specified coords (inside `cChunk::CreateBlockEntities()`)

**Comment by worktycho** [comment]
Probably better to use unordered_map. It has O(1) lookup and better temporal locality of memory accesses, but would require more allocations during the initial fill. Do you have any idea what the average number of block entities per chunk is? Then we could reserve that many elements ahead of time and avoid most of the allocations.

**Comment by madmaxoft** [comment]
I'd say the average is on the order of tens of entities, hundreds at most. The malicious chunk had over 30k block entities in it.

**Comment by worktycho** [comment]
So if we initially reserve 10 entities that malicious chunk would involve 12 reallocations with unordered_map, so not many.

**Comment by Seadragon91** [comment]
Closed by #3717.
