### ISSUE TITLE
Dyeing leather clothes is not working

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#1903]
You cannoy dye leather tunics, helmets, boots or pants. I'm also not sure if this is done via crafting.txt. Minecraft doesn't call those "somecolor dyed leather someclothing", just "Leather tunic - dyed".

**Comment by madmaxoft** [comment]
This might need a bit more research about how the dyed leather armor is actually stored. I don't think it's possible to represent this particular crafting operation by a crafting recipe (same as merging two half-broken items into a single repaired item cannot be reasonably done by a crafting recipe), it might be necessary to actually write this in a plugin or directly in the server C++ code.

**Comment by tigerw** [comment]
I expect something similar to how fireworks are done, with a template recipe combined with internal code to handle NBT population.

**Comment by SamJBarney** [comment]
[Algorithm](http://minecraft.gamepedia.com/Dyeing#Dyeing_armor)
[NBT Storage Example](http://minecraft.gamepedia.com/Player.dat_format#Display_Properties)

**Comment by SamJBarney** [comment]
The recipe is a position-less recipe: you can place the leather armor and the dye wherever you want within the crafting grid.

**Comment by jammet** [comment]
I don't know why or when this happened, but today the dye information
somehow got lost and my leather clothes reverted to their undyed look. I
fell to my death twice and picked the stuff up, but when I did this
intentionally to see if that was the reason, the dye was still there, so ...

 If this happens again and I find out why, I can post some info.

On Wed, Jul 15, 2015 at 10:31 PM, Julian Laubstein <notifications@github.com
