### ISSUE TITLE
Won't run nor compile on Mac OS X or Debian

### ISSUE THREAD

**Issue by NathanFlurry** [cuberite/cuberite#1906]
Hello,

I have a VPS running Debian and a Mac, and I can't see to make MCServer run on either of those. 

Here are the logs for the various attempts, named appropriately.

https://www.dropbox.com/sh/je8t2nnfdwqhccd/AADvW3fwj7U5EyOh1QdGQLf0a?dl=0

Note about attempting to execute the downloaded version of MCServer on Debian: I attempted to update libstdc++, but no source online seemed to do anything. 😕

If this could be fixed soon (or I'm doing something wrong), that would be wonderful, as I want to get started on my next server soon.

Thanks,
Nathan

**Comment by worktycho** [comment]
For OS X you might want to try the OSXlibcxx branch, which I've patched to use libc++ instead of libstdc++. This should fix the thread_local issue, but you will probably run into other issues first. I highly recommend upgrading you're compiler to either gcc 4.8 or higher or clang 3.0 or higher.

**Comment by Woazboat** [comment]
"(...)I attempted to update libstdc++, but no source online seemed to do anything."

You shouldn't need to fiddle with any sources. The debian repos should have everything you need. Just make sure you have libstdc++<version> and libstdc++<version>-dev (and libc6 + libc6-dev) installed. 
Assuming you're on wheezy (you should probably update, now that jessie is stable), just do:
apt-get install build-essentials libstdc++6 libstdc++6-4.7-dev libc6 libc6-dev

Or search for the package you need here: https://www.debian.org/distrib/packages

This will update your C/C++ standard library with everything that entails, so be careful!
(Oh, and you probably shouldn't always be running as root.)

**Comment by NathanFlurry** [comment]
@worktycho Hmm, it seems to do the exact same thing as it did before, except with this at the end:
~~~
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/MCServer.dir/FastRandom.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/MCServer.dir/all] Error 2
make: *** [all] Error 2
~~~

@Woazboat I've already tried that and successfully had it to work. Now when I attempt to run it, it prints this:
~~~
root@debian:~# apt-get install libstdc++6 libstdc++6-4.7-dev libc6 libc6-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version.
libstdc++6-4.7-dev is already the newest version.
libstdc++6-4.7-dev set to manually installed.
libc6 is already the newest version.
libc6-dev is already the newest version.
libc6-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.
~~~

Thanks for all the help!

**Comment by NathanFlurry** [comment]
Also, I just attempted to install it on a DigitalOcean Droplet (with the button on the main page). When it finished, it gave me a page with this data:
~~~
MCServer Information

You can log in to the webadmin at xxxxx with username admin and password xxxxx. You can also log in to the server via SSH with username minecraft and password xxxxx although it is recommended you set up SSH keys.

This page will self-destruct when you leave it, so please note down this information!
~~~

However, when I go to the IP address (including the port), it say the page can not be found.

In addition, when I log in via SSH and attempted to run the binary manually, it gives me this error:
~~~
minecraft@MCServer:~$ ./MCServer 
./MCServer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./MCServer)
./MCServer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./MCServer)
~~~

The Droplet is running `Ubuntu 14.04 x64 vmlinuz-3.13.0-43-generic`.

Any help fixing this would be great.

Thanks,
Nathan

**Comment by NathanFlurry** [comment]
I finally got it working on my DigitalOcean VPS. To be honest, I'm not 100% sure what I did to fix it, but it works now. Thanks!

**Comment by bearbin** [comment]
The issue with DigitalOcean has now been fixed at source. It just needed a more updated kernel.

**Comment by bearbin** [comment]
Now that debian 8 is debian stable everything should work a little better as well.

**Comment by NathanFlurry** [comment]
Just a quick note to everyone who runs across this thread: My issue with compiling on Mac OS X was that I forgot to add `-G Xcode` to `cmake -DCMAKE_BUILD_TYPE=RELEASE ..` (making the final command `cmake -DCMAKE_BUILD_TYPE=RELEASE .. -G Xcode`). In addition, you still have to build a couple other things with `xcodebuild`. To see the full instructions, look (here)[https://github.com/mc-server/MCServer/blob/master/COMPILING.md#osx].

Thanks and sorry for the confusion,
Nathan

**Comment by NathanFlurry** [comment]
I spoke to quickly. Every time I attempt to compile MCServer on a Mac (I got it working in Ubuntu just fine), I end up with this:

~~~
** BUILD FAILED **


The following build commands failed:
	CompileC Release/src/MCServer.build/Debug/MCServer.build/Objects-normal/x86_64/FastRandom.o src/FastRandom.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
~~~

I've tried it with the main branch and [@worktycho's branch for C++11](https://github.com/mc-server/MCServer/tree/cxx11upgrade). If someone could help me out, that'd be great.

Thanks again,
Nathan

**Comment by bearbin** [comment]
Can you try again with a fully updated version of gcc? It could be that
xcode ships with an outdated compiler.

On 7 May 2015 at 05:29, Nathan Flurry <notifications@github.com> wrote:

> I spoke to quickly. Every time I attempt to compile MCServer on a Mac (I
> got it working in Ubuntu just fine), I end up with this:
>
> ** BUILD FAILED **
>
>
> The following build commands failed:
>     CompileC Release/src/MCServer.build/Debug/MCServer.build/Objects-normal/x86_64/FastRandom.o src/FastRandom.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
>
> I've tried it with the main branch and @worktycho's branch for C++11
> <https://github.com/mc-server/MCServer/tree/cxx11upgrade>. If someone
> could help me out, that'd be great.
>
> Thanks again,
> Nathan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1906#issuecomment-99708972>.
>



-- 

Alexander Harkness (bearbin)
Find my GPG key on the Ubuntu Keyserver - http://keyserver.ubuntu.com:11371/

**Comment by worktycho** [comment]
@bearbin I think not given that most recent versions of OS X ship with gcc as a symlink to clang. This failure looks exactly like #1815, which has a fix, but was never implemented on the main server.

**Comment by bearbin** [comment]
@worktycho What I meant is to install a new updated version of gcc, from homebrew or some other source not the one shipped with the OS.

**Comment by worktycho** [comment]
And my point is that if he's on 10.9 or higher he is using clang when rather than gcc, so the problem is not the compiler front end. And if you read the error message, it mentions clang and the exact file that was the problem #1815, which combined with the fact that the fix for that was never implemented seems to be that the solution is to fix our issue with thread_local.
