### ISSUE TITLE
Zombies standing on flowers/mushrooms/grass do not burn in daylight

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#1926]
Also, breaking some mushrooms creates a shade on the block where the mushroom used to be.

**Comment by wiseoldman95** [comment]
Correction: Happens with all little objects like flowers, bushes, etc.

**Comment by SafwatHalaby** [comment]
This is probably not AI issue, it's probably a lighting issue. Destroying mushrooms reveals shades below. The AI is designed to avoid sunlight, so at daylight when they're burning they'll keep chasing you until stumbling across a mushroom. They perceive it as shade and take cover there. 

The AI is working just as one would expect: Remain in shade until it's safe to move without burning or until provoked.
To test my theory, I've put a zombie on a mushroom at daylight, it didn't move.
Once I set the time to night, it attacked me.

**Comment by SafwatHalaby** [comment]
Probably a related phenomena: It was raining and a squid jumped out of the water (Squid AI is currently dumb), the squid did not burn because of the rain, but after the squid came in contact with a bush, the squid was immediately set on fire.

One can conclude that bushes are acting like "trees"; they case shade, they protect from rain.

**Comment by LogicParrot** [comment]
Now that mobs are playable, this is becoming a nasty bug. Can anyone try fixing it?

**Comment by LogicParrot** [comment]
I should add that the symptoms of this are not just burning issues: Mobs chasing at daytime will suddenly stop, because they just stepped on a grass which they perceive as shade.

**Comment by madmaxoft** [comment]
This is most likely caused by the daylight lighting code considering these blocks opaque, so they have zero light value. Similar issue is when daylight passes through a single-block-wide hole which has a torch in it - it should spread as full daylight below the torch, but it doesn't.

**Comment by LogicParrot** [comment]
Would adding the proper entries at BlockInfo.cpp resolve it?

**Comment by LogicParrot** [comment]
~~Would adding the proper entries at BlockInfo.cpp resolve it?~~

Edit: Mushrooms are marked transparent, but they have the issue.

**Comment by LogicParrot** [comment]
Fixed.
