### ISSUE TITLE
cPlayer:MoveToWorld() still doesn't broadcast teleports under certain circumstances

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#1929]
Let's say that there is Player A and Player B and there are two worlds: World1 and World2.  If PlayerA logs in at World1 and PlayerB teleports to PlayerA from World2, the two players cannot see each other.      

Not really sure why this happens, but it does in this specific scenario.

**Comment by mathiascode** [comment]
World travel invisibility bugs were fixed.
