### ISSUE TITLE
Generator for single-prefab structures ($5)

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#1961]
MCServer should have a generator that can place structures like desert temples or witch huts. All these structures can probably use the same code, but with different prefabs, and different spawning conditions (In what biome can they spawn etc)

Structures:
- [Desert temple](http://minecraft.gamepedia.com/Desert_temple)
- [Jungle temple](http://minecraft.gamepedia.com/Jungle_temple)
- [Witch hut](http://minecraft.gamepedia.com/Generated_structures#Witch_hut)
- [Desert well](http://minecraft.gamepedia.com/Generated_structures#Desert_well)
- [Ocean monument](http://minecraft.gamepedia.com/Ocean_monument)

I believe all of these except the ocean monument are already in the [gallery server](http://forum.mc-server.org/showthread.php?tid=1372&pid=12382#pid12382)

**Comment by madmaxoft** [comment]
The ocean monument will most likely need a separate generator, since its insides vary a bit randomly.

NiLSPACE <notifications@github.com> wrote:

>MCServer should have a generator that can place structures like desert
>temples or witch huts. All these structures can probably use the same
>code, but with different prefabs, and different spawning conditions (In
>what biome can they spawn etc)
>
>Structures:
>* [Desert temple](http://minecraft.gamepedia.com/Desert_temple)
>* [Jungle temple](http://minecraft.gamepedia.com/Jungle_temple)
>* [Witch
>hut](http://minecraft.gamepedia.com/Generated_structures#Witch_hut)
>* [Desert
>well](http://minecraft.gamepedia.com/Generated_structures#Desert_well)
>* [Ocean monument](http://minecraft.gamepedia.com/Ocean_monument)
>
>I believe all of these except the ocean monument are already in the
>[gallery
>server](http://forum.mc-server.org/showthread.php?tid=1372&pid=12382#pid12382)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mc-server/MCServer/issues/1961

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by NiLSPACE** [comment]
Now that #2422 is implemented we only need the prefabs to close this right?

**Comment by madmaxoft** [comment]
I guess the `PieceStructures` generator could be manipulated into this, but it would feel like a hack, not to mention that using prefabs that way would break the checks currently being done in the GalExport plugin - namely that each area has at least one connector.

I'd prefer to have a separate generator, similar to `PieceStructures`, but serving only a single non-connected prefab, with its separate `IntendedUse` value so that the cubeset files can be distinguished from each other and GalExport can keep the checks. So, a new `SinglePrefabStructures` generator?

**Comment by bearbin** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=13663047)](https://www.bountysource.com/issues/13663047-generator-for-single-prefab-structures?utm_source=13663047&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by 12xx12** [comment]
this can be closed - use the bounty for the project 👍

**Comment by madmaxoft** [comment]
(If you add `fixes #1961` or `closes #1961` to a PR description, Github will automatically close the issue when the PR is merged)

**Comment by madmaxoft** [comment]
@12xx12 I think you need to claim the bounty on bountysource yourself, we can't "award" it to someone, unless they claim it first.

**Comment by 12xx12** [comment]
Yeah - i forgot about that.

I think i added a claim. It says that  the original issue has to be closed. Do we have to reopen and close again?
