### ISSUE TITLE
World filesize and TPS

### ISSUE THREAD

**Issue by FalkAlexander** [cuberite/cuberite#1978]
I've noticed, the tps of a world in mcserver drops drasticly and fluctuates if the size of the world is higher than 900mb.
How to reduce the world size? The world is ca. 1 day old, and 948 MB big. Can a specific Storage Schema or CompressionFactor help to reduce the worldsize or increase the tps?

**Comment by madmaxoft** [comment]
Do you have mobs enabled on your server? It could be that mobs are wandering off from the loaded chunks, causing additional chunks (and additional mobs) to be generated / loaded, pushing the issue even further.

**Comment by falkseidl** [comment]
Yes, mobs are enabled. But with compression factor 6 or higher it's running perfectly, without TPS problems.
So, maybe inform the Server Admins about this feature, if the TPS go often down, maybe as info in /tps.

**Comment by madmaxoft** [comment]
The compression factor defaults to 6, so it shouldn't be an issue in the first place. And anyway it shouldn't be causing that much lag at all, the storage runs in a separate thread so it should have minimal impact on the world tick thread.
