### ISSUE TITLE
SIGINT Should exit cleanly

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#1979]
When sending a SIGINT to MCServer, it closes as if it crashed, it doesn't save the latest block state, etc. SIGINT should be treated like the console `stop` command.

**Comment by tigerw** [comment]
I think this is fixed. SIGINT is trapped, server is terminated, and the signal is ignored.

Reference: https://github.com/cuberite/cuberite/commit/ea9de4bbb70192626b00a810482671cf14bd7f8c

**Comment by SafwatHalaby** [comment]
Works well, thanks :)
