### ISSUE TITLE
No mushrooms in mushroom island

### ISSUE THREAD

**Issue by FalkAlexander** [cuberite/cuberite#2005]
We've found the Mushroom Island biome, and saw that there were no mushrooms.

Screenshots: 
![2015-05-12_20 48 01](https://cloud.githubusercontent.com/assets/5732964/7595594/3e5b0d28-f8e8-11e4-8bbb-056b4fb544d9.png)

**Comment by tigerw** [comment]
They were all eaten by the mooshrooms, who then died of septicaemia :(

**Comment by falkseidl** [comment]
xD

**Comment by NiLSPACE** [comment]
I'm wondering if they should be implemented in the trees finisher, or have their own finisher. Any thoughts?

**Comment by madmaxoft** [comment]
It would make sense to add them to the tree finisher, especially because they should also be present in the dark forest biomes.

**Comment by NiLSPACE** [comment]
Yeah, good point.
