### ISSUE TITLE
CommandBlock is executing nothing

### ISSUE THREAD

**Issue by FalkAlexander** [cuberite/cuberite#2016]
If into a commandblock is a command written, whether a command from the server or from a plugin, it will not be executed.

I've tried the following syntax:
/say test
say test
"say test"
'say test'

**Comment by madmaxoft** [comment]
Command blocks' command handling is not implemented at all yet. It is currently being pondered, how exactly to implement it. Most likely we will add a third category of commands (in-game command, console commands and commandblock-commands) and let plugins register and handle those.

**Comment by tigerw** [comment]
There code executing the input as console commands appears to be there though. Presumably its not working?

**Comment by madmaxoft** [comment]
There's no console command `say`, so that's the reason. On the other hand, you could have a command block that executes `stop`. Yuck!

**Comment by NiLSPACE** [comment]
> There's no console command `say`

[There isn't?](https://github.com/mc-server/Core/blob/master/Info.lua#L850)

**Comment by madmaxoft** [comment]
It is completely new, it hasn't been there at the time of this report.

**Comment by NiLSPACE** [comment]
[Really? :)](https://github.com/mc-server/Core/blame/master/Info.lua#L850) it says `21 Aug 2014`

**Comment by madmaxoft** [comment]
I thought there wasn't. But still it is expecting a different set of parameters.

**Comment by NiLSPACE** [comment]
Looking at the handler, the command @falkseidl used should have worked: https://github.com/mc-server/Core/blob/master/console.lua#L319

**Comment by madmaxoft** [comment]
I give up, today's not my day :P

**Comment by tigerw** [comment]
> On the other hand, you could have a command block that executes  stop . Yuck!

The command blocks checks for the stop, reload, restart, ban, banip commands and doesn't execute them.

**Comment by mathiascode** [comment]
Can't reproduce.
