### ISSUE TITLE
Replace cProbabDistrib with std::discreate_distribution

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#2020]
Doing this would remove the requirement to maintain cProbabDistrib's complicated maths code, whilst the required adapter classes between our own Noise and the standard library distributions would open up the possibilty of using the other distributions.

**Comment by s32ialx** [comment]
sounds interesting but explain more of the benefits of other distributions... sell it.

**Comment by worktycho** [comment]
The main immediate advantage is not having to maintain our own implementation. But there are twenty other distributions available in the standard library. There's a list here: http://en.cppreference.com/w/cpp/numeric/random.

**Comment by s32ialx** [comment]
OH NO THE elusive RNG Monster. Forgive my ignorance but is this for item drop rates or the world generation?  I didn't even know prior to this that cProbabDistrib was for RNG.

**Comment by worktycho** [comment]
It the moment cProabDist is used in two places in the world distribution.

**Comment by NiLSPACE** [comment]
Are there maybe a performace test to see what's faster?

**Comment by peterbell10** [comment]
I'm closing this because I don't think it's possible.
Even if you could wrap a noise function to behave like a random number generator, you would find that the results of distributions [aren't portable](https://stackoverflow.com/questions/24550963/) and so wouldn't be suitable for world generation.
