### ISSUE TITLE
1.7.2 Block placement is broken

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2026]
Placing dirt works, placing anything else behaves weirdly:
Mobs don't detect the placed blocks, the placed blocks do appear in the server console (when verbose debug mode), and when leaving and rejoining, the blocks aren't there.

**Comment by madmaxoft** [comment]
This has already been reported once and we couldn't reproduce it on our side (but I can't find the issue, unfortunately). If you can reproduce it, perhaps you're the best suited to fix it.

**Comment by SafwatHalaby** [comment]
I would love to but I am still unfamiliar with the code base outside cEntity and its decedents.
What could be different here? Why would it happen on one computer but not on another?

**Comment by SafwatHalaby** [comment]
I reported that other issue, I was mistaken when I said I cannot re-produce it anymore, I simply didn't try anything other than dirt back then.

**Comment by NiLSPACE** [comment]
Can we close this?

**Comment by SafwatHalaby** [comment]
Let me re-check, I'll close if reproduction fails.

**Comment by SafwatHalaby** [comment]
I am still able to reproduce it.

**Comment by LogicParrot** [comment]
This is still 100% reproducible, interestingly, sometimes the **Client** crashes, too.
