### ISSUE TITLE
Food drains too quickly.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#2044]
Food appears to be mostly working, but it drains much more quickly than in the vanilla server.

**Comment by tigerw** [comment]
Some data is probably needed to ease fixing if this is a problem.

**Comment by NiLSPACE** [comment]
You can come online on bearbin's dev server and play a little survival ^^

When I was working on my island (digging and placing blocks) I barely used any food, but when traveling you use up allot.

**Comment by bearbin** [comment]
Yes, walking and running use far too much, but jumping/sitting use almost none.

**Comment by jammet** [comment]
It is tied to going up, too. Using ladders, or even the /fly command, when in survival mode.

**Comment by SamJBarney** [comment]
Shouldn't sitting still cost you nothing?

**Comment by LO1ZB** [comment]
I'll open a PR for a fix as soon as I sqashed the commits in my fork/branch
