### ISSUE TITLE
Foliage grows far too quickly.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#2045]
Title says it all.

**Comment by bearbin** [comment]
Trees and wheat also grow at night. They should only grow during the day or if illuminated by a torch.

**Comment by NiLSPACE** [comment]
I changed the name, because every type of plant grows too fast.

**Comment by s32ialx** [comment]
except grass grows to slow 1 hour and not even half of my patch of maybe 40x20 grew

**Comment by mathiascode** [comment]
Duplicate of #1667
