### ISSUE TITLE
Furnaces stay lit

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#2051]
When using a furnace the furnace stays lit, even after it finished. When relogging it returns to unlit, so it is client-side.

**Comment by tigerw** [comment]
A brief test seemed to show the block changing correctly. Could it be that the fuel wasn't all consumed yet, so it remained lit?

**Comment by bearbin** [comment]
No, all the fuel was consumed when I tested and it still stayed lit.

**Comment by NiLSPACE** [comment]
I noticed that when I remove the fuel the furnaces becomes unlit.

**Comment by bearbin** [comment]
I experienced this bug again, but this time it stayed lit even after a relog.
