### ISSUE TITLE
Shared pointer allocations should use std::make_shared

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#2068]
This allows the implementation to optimize the shared pointer allocation, and avoid a separate memory allocation for the ref count block.

**Comment by SafwatHalaby** [comment]
Side note: It should be noted that make_unique is not available in c++11

**Comment by worktycho** [comment]
Which is why there is a custom implementation is globals.h cpp14::make_unique

**Comment by SafwatHalaby** [comment]
Didn't know that, thanks.

**Comment by worktycho** [comment]
Its the only namespace in the project to avoid ADL issues.

**Comment by tigerw** [comment]
Appears fixed.
