### ISSUE TITLE
Proposal: Change logo.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#2090]
@madmaxoft designed us a new logo. Should we go ahead and replace both the grass block logo and the blue block logo with this new logo? Discuss.

Personally, I prefer the looks of this logo, and the copyright situation is much better. (@madmaxoft will freely license this one, the grass block one is not known to be licensed to the project, and the blue cube one was "donated to the project" according to FakeTruth.

![cuberite2 1](https://cloud.githubusercontent.com/assets/1297699/7754376/0b04def6-ffe4-11e4-898c-d8476b03f667.png)

**Comment by bearbin** [comment]
As a comparison, here are the old logos.

![](http://mc-server.org/assets/icon_256.png)

1[](http://forum.mc-server.org/images/clean/logo.png)

/\\ Ignore the text in that logo, it's just the cube we're talking about.

**Comment by NiLSPACE** [comment]
I really like the blue cube from the forum. It looks really modern. Since it was donated why not use it?

**Comment by SafwatHalaby** [comment]
I like the blue cube too. @madmaxoft 's logo is nice as a concept, but it looks cartoonish and needs some modernization.

**Comment by tigerw** [comment]
![Impasse](http://www.quickmeme.com/img/63/635205c2328913eea4963a89a26b8f6687f9e77f4a32b45085f8faf86dbf111e.jpg)

**Comment by bearbin** [comment]
@tigerw: You don't have an opinion yourself?

**Comment by SphinxC0re** [comment]
I don't really like the *new* logo. I always liked the grass cube but I think it might be a better choice to just make a *completely* new thing.

**Comment by jammet** [comment]
I may not be really part of this whole operation, but if I may?

While the logo is pretty neat, I don't see it having much relevance for Minecraft. When I see this (well known) geometric trickery, I think of a lot of things, but I do not think Minecraft. At all. I'm fairly good with graphics myself, and I think I could do something nice as well, but if there's one thing I know, it's that it doesn't feel great when you put time, work and effort into something and that's not recognised.

So again, the proposal looks *good*. It just .. isn't Minecraft-y.

Remember projects like WINE? "Wine is not an emulator". Some projects use these kinds of acronyms to come up with a name, and have some humor attached to it. More importantly right now though, is their icon: a glas of wine.

I could very well imagine a round silver platter with a block of dirt/grass on it, akin to that. 
Or a stylized hand, holding a block, as if giving it or holding it up.
Or a diamond sword in a block of stone.
The list goes on.

**Comment by tigerw** [comment]
Suggestion: as the Cuberite organisation is for everything, not necessarily MCS (inc. AnvilStats, ProtoProxy, etc.), it needn't be wholly relatable to Minecraft per se, but maybe the ecosystem and tools around it. The proposed logo with some anti-aliasing and flattening could serve well for this purpose. Furthermore, contrary to bearbin's suggestion, separate logos for the organisation and the software will help to maintain a distinction between the two - consider the logo of Google and the logos of Chrome, Android, and GMail.

A MCServer logo change, if required, may be something that requires an icon more related to MC as the game, or Minecraft Server software (consider #436 or #304).

At the present moment, assuming we agree with the geometric logo for Cuberite, attention may be drawn to MCS. While the current logos are fine, there are two versions, one for the forum and one for everywhere else, which is somewhat unorthodox and maybe inconsistent. Additionally, the blue cube seems to have text in it and is a fixed size image, which limits its ability to be used everywhere (unlike an SVG for example); this may be resolved by finding the author and their source files to regenerate the logo.

Finally, a potential issue with all the logos so far are that they go against the prevailing UI design style of flat, flat, flat. Whilst originality is good, to some, they may stand out as being unprofessionally designed.

Suggestions: Cuberite - smooth the current one and change its colour scheme to something more muted (?). Maybe add some detail and a circle around it. MCS - ideally get something flatter and simpler (I push #436 once more) and modify to be in whatever style the Cuberite one comes out to be.

**Comment by NiLSPACE** [comment]
I always found flat icons to look really ugly. It's like somebody didn't really want to put much attention to it, and just created something in paint. I believe FakeTruth once uploaded all formats for the blue cube (small 16x16, medium 32x32,64x64, etc).

**Comment by bearbin** [comment]
@jammet Good point. any oth those suggestions seem like good ideas, try one out and post it here.

@tigerw I thougth through it again and separate logos makes sense.

**Comment by SphinxC0re** [comment]
I am a little bit worried about this change because it doesn't solve our SEO problem.  If we just rename the organization we would end up with the same problem as before
(e.g. "How to disable mobs in MCServer")

**Comment by bearbin** [comment]
The organisation name change is necessary to change the server name anyway.

But this issue is a discussion of logos, not names.

**Comment by SafwatHalaby** [comment]
Two logos? The whole "organization name different from server name" feels like it's spawning needless complications.

**Comment by bearbin** [comment]
It does seem to be spawning needless complications, yes. 

We need to get everyone on the IRC at once and have a proper discussion and come to a solution about what we're going to do.

**Comment by nounoursheureux** [comment]
Relevant: http://forum.mc-server.org/showthread.php?tid=2000
