### ISSUE TITLE
Placing TNT in fire doesn't place the TNT

### ISSUE THREAD

**Issue by Rakete1111** [cuberite/cuberite#2092]
When a block has fire on it, you can't place TNT on it

**Comment by martindev2** [comment]
From what I can see the same applies if placing any other type of block on the fire. Comparing with single player creative mode, placing a block on top of fire just extinguishes the fire. I have added code for DoesIgnoreCollision to the firehandler to return true. Are there more behaviours to consider?

**Comment by tigerw** [comment]
Can't think of anything more, but do make a pull request for your changes!

**Comment by martindev2** [comment]
Thanks. I have submitted the pull request.
