### ISSUE TITLE
Grass grows underneath farmland.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#2095]

**Comment by bearbin** [comment]
I think that the issue is that farmland is designated as transparent here:

https://github.com/mc-server/MCServer/blob/master/src/BlockInfo.cpp#L207

But I can't quite remember what all the different definitions in that file do so I need somebody who knows more to change it.

**Comment by NerdyHydra** [comment]
Farmland is supposed to be partially transparent.

Hmm. Maybe we can add in a value "E_META_DIRT_FARMLAND = 4" into BlockID.h? This would make sure that the grass growing algorithm takes farmland into account when looking for viable blocks (BlockDirt.h line 93).

**Comment by madmaxoft** [comment]
@NerdyHydra I don't see how that would be pulled off. MC defines the farmland block type and meta values, we can't just change them at will. And adding a named constant won't do much unless the rest of the code is adapted to use it.

**Comment by SamJBarney** [comment]
Is farmland the only one that is causing it, or are there more?

**Comment by bearbin** [comment]
I assume it would be any transparent technically but visually opaque blocks (glowstone, etc).

**Comment by SamJBarney** [comment]
I just went over the list of transparent blocks, and these are the ones that could block it, but I'm not sure if they block it in vanilla:
* Carpet
* Daylight Sensor
* Enchantment Table
* Farmland
* Lava
* Piston
* Sticky Piston

Glowstone isn't marked as transparent.

Can someone verify these for me? I'm at work and can't test them out right now.

**Comment by bearbin** [comment]
The wiki seems to suggest that it is:

http://minecraft.gamepedia.com/Opacity#Types_of_transparent_blocks

**Comment by tigerw** [comment]
Ohai @SamJBarney, welcome back!

MCS transparent should mean "can't be seen through" as opposed to "doesn't occupy voxel fully", so glowstone shouldn't be transparent, neither should farmland or any of the ones above.

So if grass does a transparent check, with the correct code it will not grow under farmland.

**Comment by SamJBarney** [comment]
It's nice to be back, @tigerw .
So do you think that we have a bit of a misnomer by calling them transparent based on the contents?

According to the wiki: The growth of grass blocks is linked to how well lit the blocks directly above them are. Reducing that light with an opaque block, a partially transparent block or enough transparent blocks will kill a grass block, as well as prevent grass spreading to nearby dirt blocks.

So what needs to be done is a lighting check instead of testing what kind of block is on top.

**Comment by SamJBarney** [comment]
Fixed in https://github.com/cuberite/cuberite/pull/2261

**Comment by NiLSPACE** [comment]
But it isn't merged yet :|

**Comment by SamJBarney** [comment]
Sorry. I forgot that was the procedure.

**Comment by SamJBarney** [comment]
Fixed in https://github.com/cuberite/cuberite/pull/2280
I did it right this time!

**Comment by madmaxoft** [comment]
Just for info: We normally put "Fixes #NNN" as the comment to the PR, then when the PR gets merged, GitHub closes the referenced issue automatically.

**Comment by SamJBarney** [comment]
lol. ok
