### ISSUE TITLE
Players become invisible when entering the Nether

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2106]
All the time, when I join the server, and at that time it happens that one or more other players are connected to the Nether they:
1. do not show up on the player list
2. they chat does isn't shown to people who're not in the nether
3. more often than not, when they return from the nether, you will not be able to see them, and vice versa.

**Comment by beeduck** [comment]
Have you tried this with the End as well?

**Comment by jammet** [comment]
No. I haven't found the end in my server world yet. Cannot say if the behavior is the the same.
