### ISSUE TITLE
Sometimes blocks are only destroyed client side.

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2121]
This happened to me twice.
I am currently testing the PathFinder, and sometimes I destroy blocks to see if the mobs will alternate their path. On 2 occasions, the mobs did not do that, instead, they walked "in the air", as if the block wasn't destroyed. On those two occasions, I logged back out then logged back in, and the block that I thought I had removed was there. So the PathFinder was working fine, it's just that the server did not register the block destruction.

I often work with mobs, this could be a trigger. Perhaps blocks have a chance of behaving weirdly when destroyed while a mob is standing on them / touching them?

I can rarely reproduce this, so it could be troublesome to debug.

**Comment by SafwatHalaby** [comment]
Client 1.8.4

**Comment by jammet** [comment]
I know enchantments aren't *really* fully supported yet, but if you enchant a pick with the /enchant command to maximum efficiency and then use that on netherrock... you won't even see the blocks. It completely erases the blocks without spawning them for pickup.
Same with dirt, if you use a shovel with maximum efficiency.

Maybe that's related.

**Comment by KingCol13** [comment]
Possibly fixed by #4938 but more testing required to confirm.

**Comment by peterbell10** [comment]
The issue as described by jammet should certainly be fixed. IMO the original issues is not specific enough to test properly. So, I say close.
