### ISSUE TITLE
Animal mobs seem to turn into wolf mobs randomly

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2127]
I have absolutely zero proof, only the feeling that it happens.

1. Animals in my world seem to just randomly disappear.
2. Except the wolf population seems to be constantly on the rise.
3. I've seen groups of wolf spawn in rivers months ago.
4. Pens where sheep and pig had been in, now mostly have wolf in them.

So yes, I have no idea why, or if this just all purely random, but I have the strong feeling that all kinds of animal mobs convert to wolfs under certain conditions. My sheep in their pen have remained sheep for a long time now and nothing happened, so ... I'm out of ideas.

**Comment by SafwatHalaby** [comment]
Evolution.

**Comment by bearbin** [comment]
Wolves now no longer spawn in rivers.

**Comment by bearbin** [comment]
(or at least no longer generate there)

**Comment by jammet** [comment]
LOL. ;) Evolution!

**Comment by bearbin** [comment]
Test comment please ignore.

**Comment by SafwatHalaby** [comment]
Is this still an issue?

**Comment by jammet** [comment]
I can't say yet, because that never seems to happen when I pay attention to
it. It's just that ...

Never in all these months have I spawned wolfs manually. But I know for a
fact there weren't many, if any, at all, near the village.
Over time I just noticed ... Oh look, there's a wolf now. Where'd that come
from. Oh look, another wolf.

Then I was annoyed that the animals were all stuck in the river that goes
through the village.
And a few days later that river was full of wolves instead. All the other
animals seemed to have disappeared. I enabled the /fly cheat and passed
over areas I knew.
"There was  sheep and two cows here." I thought ... and I saw a sheep and
two wolfs ...

It's things like that. This kept happening throughout the entire time I
have been running this server. I'll be able to say in a few weeks if that
changed.

**Comment by SafwatHalaby** [comment]
Perhaps all animals despawn under some conditions except wolves?

**Comment by SafwatHalaby** [comment]
Perhaps your players hunt all animals except wolves?

**Comment by jammet** [comment]
No, that's not it. The entire region around the village had been completely
devoid of any animals except wolves several times, as they had a tendency
to find gaps in the ground that they could not get back out of. Sometimes,
after wondering where all the animals had gone, for weeks, I'd find such a
crevice and find it had surely about a hundred animals in there, all
occupying the same same. I used up a diamond sword removing them from down
there and filled the opening of the crevice with dirt each time I found
these "animal hazards", and each time I repopulated the entire region
manually, by spawning new groups of animals: sheeps, rabbits, chickens,
horses, bigs and cows.

Never in the entire time the server was running I spawned even a single
wolf. But they're everywhere there, now.

**Comment by SafwatHalaby** [comment]
Absence if evidence is evidence of absence :P

**Comment by jammet** [comment]
I'm not even sure it is still happening. But it absolutely did, back then.
Why're you looking at me as if I was one of those crazy catladies!
-snif-

**Comment by madmaxoft** [comment]
I think I remember seeing a bug where a wolf would get duplicated each time the chunk was loaded. This could have explained the behavior - all the other mobs despawned after some time, only the wolves got multiplied over and over again. I *think* the bug has been fixed.
