### ISSUE TITLE
Mask doesn't show up on skins

### ISSUE THREAD

**Issue by Rakete1111** [cuberite/cuberite#2149]
My skin has a mask (I think that's what it's called, the extra layer on top of the head) that shows up on every server except my test MCServer
![mcserver skin bug](https://cloud.githubusercontent.com/assets/8321423/7843005/28e6e776-04a7-11e5-84aa-2bb1fd34bb81.png)

**Comment by beeduck** [comment]
Can you post what it's supposed to look like and what it does look like?

**Comment by SafwatHalaby** [comment]
What it looks like is irrelevant. 1.8 introduced 2 layers of skin. The outer layer is missing in MCServer. I noticed that too. This is the [new template](http://hydra-media.cursecdn.com/minecraft.gamepedia.com/e/ef/1_8_texturemap_redux.png), MCServer ignores layer2, which is the "transparent" part.

**Comment by rowanan45** [comment]
So the overlay doesn't show up and this make my skin looks really weird....
MCServer doesn't support overlay(layer2)...

**Comment by rowanan45** [comment]
But now this bug is still not fixed...

**Comment by Pokechu22** [comment]
To get this to work, the [client settings](http://wiki.vg/Protocol#Client_Settings) packet's skin flags needs to be forwarded into the [displayed skin part mask in the player metadata](http://wiki.vg/Entities#Player).  Probably shouldn't be too hard.

**Comment by rowanan45** [comment]
Sound like easy for you but it too difficulty for me but i hope this bug can be fixed...
