### ISSUE TITLE
Some characters aren't shown correctly on signs

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#2170]
A few characters aren't shown correctly on signs. Some of them are:

& - Shows as \u0026
= - Shows as \u003d
' - Shows as \u0027
< - Shows as \u003c
.>  - Shows as \u003e

**Comment by jammet** [comment]
Yeah, things like that have been a bit of a pest for a while now.
I also noticed that sometimes, the text written on signs in worlds that used to be first made with the Mojang generators, are out in quotes for some reason.
