### ISSUE TITLE
Enchanting Table doesn't write the enchantment that you will have

### ISSUE THREAD

**Issue by Rakete1111** [cuberite/cuberite#2177]
It uses 1.7 behavior, paired with 1.8 behavior.

**Comment by 12xx12** [comment]
The author ment that the tootips which should be shown on hovering the enchantment options in the window are not displayed

**Comment by 12xx12** [comment]
the function cSlotAreaEnchanting::UpdateResult(cPlayer & a_Player) should send the message

**Comment by KingCol13** [comment]
I will attempt to fix this. Notes from #4934 :

A prerequisite to fixing this is fixing the PRNG for offered enchantments such that they cannot be altered: https://minecraft.gamepedia.com/Enchanting#Affecting_offered_enchantments.

A 4 byte seed should be stored in cPlayer and written on disconnect. This should be used to seed the PRNG state when calculating which enchantments to offer. This seed should only be incremented when an item is enchantment by that player.

Pseudocode for the PRNG can be found at: https://minecraft.gamepedia.com/Enchanting_mechanics. An alternative is:

`auto Noise = cNoise(PlayerSeed);
auto RandomNumer = Noise.IntNoise1D(SomeNumber);`

where SomeNumber should be derived from the values listed on the wiki link above.
