### ISSUE TITLE
Hoe does not work on all dirt blocks

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2187]
I've got a farm, and there are dirt blocks there, that I cannot successfully use the hoe on, to plant carrots, potatoes or wheat. 

It seems to be a position thing, as I can dig the dirt up, and put the dirt right back... but I still can't weed there.

This is happening at a place where I've planted melons.

**Comment by bearbin** [comment]
Interesting. This worked perfectly fine for me a week or 2 ago.

**Comment by jammet** [comment]
If you would like to experiment, my server is jammet.duckdns.org - I'd need to whitelist your name first.

**Comment by jammet** [comment]
Or maybe I already did that and just don't remember at the moment. I'll show you where I got a farm and the melons when you want me to, but they're not far from spawn.

**Comment by jammet** [comment]
I noticed, the only way to be able to replant something on these blocks is, to put another one ontop, and  remove it again. Then you can tile the dirt again.

**Comment by madmaxoft** [comment]
That would suggest that the server is out of sync with the client, regarding the block on top of the dirt block. Server thinks something's there, and therefore doesn't allow the hoe action, while client displays nothing there.

When you run again into such a situation, try to log out and back in, if another block appears on top of the dirt. Then try stopping and restarting the server, again to see if there's another block.

**Comment by jammet** [comment]
I've done hat several times to see if it is just that. Turns out, sadly no,
this is something else. You're all invited to check the freak show yourself
;).

**Comment by jammet** [comment]
I'm quite convinced now, that the server grows *invisible* melons, that cannot be touched either. You only harvest them if you place any other block in their stead and then chop that block away. You get melon slices. 

With these invisible melons occupying blocks on the dirt, it is no wonder  cannot use the hoe on the dirt. But if I actually harvest *visible* melons in that area, the server segfaults.

**Comment by madmaxoft** [comment]
Found out the cause. The melon-growing code treated melons the same as pumpkins, giving them various metadata values for direction. However, there is no metadata for a melon, it is directionless.

**Comment by jammet** [comment]
Thank you so much! :dancer:
