### ISSUE TITLE
Redstone not gates not working properly with repeaters nearby

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2191]
These two are perfectly valid clocks in Vanilla. In MCServer, they simply won't work. I recall a similar issue a very long time ago. Back then, Tiger fixed it, I think.
![2015-06-02_18 01 21](https://cloud.githubusercontent.com/assets/5030488/7939100/f0f544fc-0951-11e5-9d1f-19738085e494.png)
![2015-06-02_18 00 40](https://cloud.githubusercontent.com/assets/5030488/7939103/f4161f08-0951-11e5-9979-8e0fa80d326d.png)

**Comment by NiLSPACE** [comment]
The block powering doesn't work completely. Try putting another redstone dust above the block with the torch.

**Comment by SafwatHalaby** [comment]
This works in vanilla.

**Comment by SafwatHalaby** [comment]
This bug renders T-flip-flops useless.
![2015-06-02_18 43 19](https://cloud.githubusercontent.com/assets/5030488/7940094/594a8dbe-0957-11e5-96fa-2481fb8cc1d7.png)

**Comment by SafwatHalaby** [comment]
It's as if repeaters emit a "bug" to all 8 adjacent blocks, hitting redstone torches and making them lock in the on state.

**Comment by tigerw** [comment]
I think that this PR will fix it. I notice that the wire at the far side of the image has a joint which doesn't directly power the second raised stone block, but instead turns left before it and heads out towards the chickens/edge of the platform.

Combined with the above PR and ensuring the wire goes into that block, I managed to get some solid-state sandals by toggling the input wire.

Can't you make a sandal out of pistons too?

**Comment by jammet** [comment]
Does this mean redstone circuitry is being tackled? :) Can I get my hopes up? Two of my friends just experiment and play with redstone all the time and they're literally waiting for the day the stuff works just like in vanilla.

**Comment by tigerw** [comment]
Yeah, more or less :D

**Comment by SafwatHalaby** [comment]
Limmie test it first.

**Comment by tigerw** [comment]
Is Limmie part of your QA team? :P

**Comment by SphinxC0re** [comment]
LOL

**Comment by Haxi52** [comment]
This appears to work for me.
