### ISSUE TITLE
Eggs spawn adult chickens.

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2195]
Should be babies.

**Comment by jan64** [comment]
This is a bit harder, because i don't think we have any support for spawning/creating baby chickens atm.

**Comment by hallucino** [comment]
I can do it if nobody want to work on it.

**Comment by NiLSPACE** [comment]
Go ahead, you're the first ^^

**Comment by hallucino** [comment]
More generally spawn eggs don't work, right ?

**Comment by hallucino** [comment]
oh no ok it works :)

**Comment by SphinxC0re** [comment]
Isn't this solved

**Comment by NiLSPACE** [comment]
Yup
