### ISSUE TITLE
Chickens can fall through signs with water on them

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2196]
The following image is a valid chicken trap in vanilla. It is commonly used to collect eggs.
In MCServer, chickens fall through it.
![2015-06-02_18 35 48](https://cloud.githubusercontent.com/assets/5030488/7939917/45f2313c-0956-11e5-80a3-2673e300a15f.png)

**Comment by mathiascode** [comment]
Can't reproduce.
