### ISSUE TITLE
Lava kills chickens almost instantly.

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2197]
In vanilla, the chickens endure a bit before dying. 

This problem prevents automatic chicken cookers from working. These are devices which release lava through dispensers and recollect it almost instantly. In vanilla, this makes the chickens die of fire damage, releasing cooked chicken as a drop. In Cuberite, the dispenser can never re-collect the lava fast enough, and chickens die of lava damage. Death from lava damage does not drop cooked chicken (or perhaps when it does the drops would burn in the lava)

**Comment by jammet** [comment]
Ah, I am beginning to understand why my attempt to make a chicken cooker failed. I blamed the missing redstone circuitry.
