### ISSUE TITLE
Self Powering repeater

### ISSUE THREAD

**Issue by Haxi52** [cuberite/cuberite#2216]
A repeater powering a block and wire leading back into it self should remain on after external power applied. 
![2015-06-07_19 25 24](https://cloud.githubusercontent.com/assets/10181722/8026781/68822aba-0d4b-11e5-9fde-38aa462b9d73.png)

pushing the button in the image above should make the circuit stay on indefinitely.

**Comment by tigerw** [comment]
I think this got fixed sometime.

![Fixed](https://user-images.githubusercontent.com/2939130/79594366-cb45e900-80d4-11ea-8c90-e085274c5e15.png)

**Comment by bearbin** [comment]
Closing as not reproducible.
