### ISSUE TITLE
Transparent blocks should not block redstone wire

### ISSUE THREAD

**Issue by Haxi52** [cuberite/cuberite#2218]
Redstone wire traveling down one block should not be stopped by a transparent block, lower slab, or glowstone
![2015-06-07_19 34 18](https://cloud.githubusercontent.com/assets/10181722/8026806/9da53b1e-0d4c-11e5-9ace-7b07bafb6cbf.png)

Also noticed while testing, changing the block where the glass is, does not cause an update. allowing the lamp to power, then placing a solid block as below should cut off the signal.
![2015-06-07_19 38 48](https://cloud.githubusercontent.com/assets/10181722/8026812/db974980-0d4c-11e5-85e2-aa3368c41067.png)

**Comment by bearbin** [comment]
Fixed by #2848.

**Comment by jammet** [comment]
![2016-01-11_18 58 55](https://cloud.githubusercontent.com/assets/11940735/12247238/5dd4311c-b8b3-11e5-8fff-3dd063093dd4.png)

This mechanism only works once that one slab is removed. Related issue? One week old build - master.

**Comment by SphinxC0re** [comment]
The newest build should include the fix for that problem
