### ISSUE TITLE
Travis has old version of clang

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#2230]
Travis use in compiling clang 3.4, the newest available version is 3.6. I have looked into the .travis.yml files from other repositories. Here is a example, that contains how to install and use clang-3.6,

https://github.com/dirkvdb/ffmpegthumbnailer/blob/master/.travis.yml

**Comment by bearbin** [comment]
We don't have a need for clang 3.6, and dropping support for 3.4 with no reason to do so is not something we want to do I think.

**Comment by worktycho** [comment]
Really we want to be compiling with both. 3.4 for compat, and 3.6 for the new warnings.
