### ISSUE TITLE
Slime spawn in light

### ISSUE THREAD

**Issue by Haxi52** [cuberite/cuberite#2233]
Slime blocks are spawning in swamp biome during the day.

According to gamepedia: Slimes spawn in the Overworld in specific chunks below layer 40. They can also spawn in swamp biomes between layers 50-70 in light levels of 7 or less. (http://minecraft.gamepedia.com/Slime)

related to #1828 

This is on the first day the world was generated
![slime001](https://cloud.githubusercontent.com/assets/10181722/8123968/bdbcdc46-1098-11e5-9838-6b72f08e3a59.gif)

**Comment by JK2Kgit** [comment]
Hi i'm new.
Is it still actual if so i would like to give it a try.
