### ISSUE TITLE
Placing redstone torch against powered block should create 1 tick pulse

### ISSUE THREAD

**Issue by Haxi52** [cuberite/cuberite#2235]
In vanilla this turns on the right lamp for 1 tick.

![redstone003](https://cloud.githubusercontent.com/assets/10181722/8124010/8ca67e4a-1099-11e5-8c42-ced7d02ab2b5.gif)

the lamp under the lever to show it is in the "on" state.

**Comment by SphinxC0re** [comment]
And again @tigerw
