### ISSUE TITLE
Hopper multiplies items

### ISSUE THREAD

**Issue by chrischi1989** [cuberite/cuberite#2245]
I don't know if you're already aware about this (didn't found issues specifically regarding this) but if you put a stack of items into a hopper and have second hopper under it, the items from the first hopper will get multiplied in the second one.

Video: http://puu.sh/ipeUv/15e8281224.mp4

Version info:

MCServer  build id: 33
from commit id: 0cd64ab90b1e71fa179bd505f6027ca433d36d37 built at: 33

Greetings from Germany

**Comment by tigerw** [comment]
The infamous and prized duplication glitch :P
