### ISSUE TITLE
Add runtime loading possibility to cPrefabPiecePool

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#2247]
Make it possible to load pieces into `cPrefabPiecePool` at runtime. This will make it possible to make more configurable villages, trees and other structure generators.

Also, this way we can get rid of the hard-coded prefabs and instead use prefabs prepackaged with the server (but changeable by the admin).

**Comment by madmaxoft** [comment]
This will require a new file format for the prefabs, so that the whole collection of the prefabs can be saved as a single file. Rather than parsing the existing `cpp` export format, I have decided to create a new one from scratch, and take advantage of the existing Lua facilities in the server. The new `cubeset` format will be a Lua source file that will be organized quite similarly to the `cpp` file format. We'll let Lua parse the file and then query it for individual pieces. Unlike `cpp`, the `cubeset` format does support any kind of metadata attached to individual pieces, as well as the entire set itself. Therefore it could be used to represent various prefabs with various intended uses - the format could for example specify that this file is intended for villages, or trees, or standalone structures, it could specify accepted biomes, village road blocktypes, even parameters for the standalone piece generator.

Because it is a Lua format, it would even be possible to make it loadable by other Lua plugins - WorldEdit could be made to read the prefabs stored in such a file into its clipboard.

**Comment by NiLSPACE** [comment]
That sounds amazing. Will it also support entities/block entities?

**Comment by madmaxoft** [comment]
In the first version, no, it will be equivalent to what we currently have in the `cpp` exporter. Of course it will be possible to add anything later. I'm counting on supporting block entities in the very least, so that we can finally generate some loot in those chests. But I want to have this done as soon as possible because it will allow us to make use of the `cPieceGenerator` for very custom generators, and we can even change trees to use prefabs (which would mean the possibility of having custom villages, custom trees etc.)
