### ISSUE TITLE
Race condition in max player count

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#2257]
If more than one player attempts to join the server, in a short enough space of time, when the server is nearly at its max slot count, it can cause the server to allow more players on than the maximum.

**Comment by jan64** [comment]
![](https://i.imgur.com/Dtpuojd.png)

**Comment by tigerw** [comment]
Aha! std::atomic to the rescue!

@jan64 has a 502 player server? Or maybe just a bad gateway?

**Comment by worktycho** [comment]
Its more complicated, the biggest issue being that the check is done in cClientHandle::HandleHandshake, but the count isn't incremented until cPlayer::Authenticate.

**Comment by jackwilsdon** [comment]
Could we not increment the player count in `cClientHandle::HandleHandshake` and decrement it in `cPlayer::Authenticate` if authentication fails? Is `Authenticate` called even if the client disconnects after the handshake?

**Comment by worktycho** [comment]
Authenticate is not guaranteed to be called after the handshake, as far as I can tell.

**Comment by SamJBarney** [comment]
Increment on handshake, decrement on connection closed?

**Comment by worktycho** [comment]
What if the connections closed before handshake?
