### ISSUE TITLE
Dropper Inventory Item Glitch

### ISSUE THREAD

**Issue by Haxi52** [cuberite/cuberite#2260]
Some weird things only when in dropper inventory.
I'm middle mouse clicking to get a full stack.
When dropping in player inventory I lose the previously created stack.
If the created stack is halved (right click) I lose the half left in inventory.
Any stacks dropped into the dropper inventory are lost. (If created with middle or right clicks)
![dropperitems](https://cloud.githubusercontent.com/assets/10181722/8236597/08a03eb8-15af-11e5-99da-8f85fc1daf59.gif)

Here is the server output while doing the above clip. (everything after server time changed)
![serveroutput-dropperglitch](https://cloud.githubusercontent.com/assets/10181722/8236626/375449e8-15af-11e5-9ad9-97390f1f44d7.jpg)

**Comment by tigerw** [comment]
We haven't implemented middle-click-get-a-full-stack-in-creative yet, so any such actions will produce a desync between the server and the client inventories.
