### ISSUE TITLE
Peony in snow missing bottom

### ISSUE THREAD

**Issue by nichwall** [cuberite/cuberite#2265]
I created a new server, and noticed all of the tall flowers (peony) are missing their base.
![2015-06-19_13 01 41](https://cloud.githubusercontent.com/assets/5686638/8265842/d786461e-16d1-11e5-8667-8c4455d644e4.png)
I walked around for a while, and it seems that the bottom block is always snow layers (ID 78) with varying thicknesses. Breaking the snow base also breaks the top of the flower and sometimes drops a sunflower. I tried planting sunflowers, and they were planted correctly. Upon breaking the lower part of the sunflower, the top changes to a peony top, but is usually removed within a few ticks. Some of the time it stays like the rest of the peony tops from world generation, but without the snow layer on the bottom. The top remaining does not seem to be affected by whether the sunflower is planted next to another block.

**Comment by SamJBarney** [comment]
@nichwall Do you have a seed and position for this? I think I've fixed it, but I haven't run across any snow biomes yet to test it with.

**Comment by NiLSPACE** [comment]
Just set biome generator to constant, with the biome set to ice plains ;)

**Comment by nichwall** [comment]
@SamJBarney From the world referenced in my initial issue, the seed was `1128939074` and spawn position was `X=0.000000
Y=66.600000
Z=0.000000` according to my `world.ini`. I just cloned and recompiled (commit 118aec119853dfcae1dca90ad54c3720f9271bbc), but spawned in a Forest Hills biome. 
This time, I tried it with multiple tall grasses (Peony, Sunflower, Double Tallgrass, Large Fern, Rose Bush, and Lilac).
Whenever any of these were planted, the top block was destroyed, yielding a sunflower and the correct corresponding drop. (Peony yields Sunflower and Peony, Sunflower yields two Sunflowers, Rose Bush yields Rose Bush and Sunflower, Lilac yields Lilac and Sunflower, Double Tallgrass/Large Fern yield Sunflower) The remaining base yields no drops when destroyed.
![2015-07-13_19 49 14](https://cloud.githubusercontent.com/assets/5686638/8667391/a9aaf270-29c4-11e5-94f5-822b52ecbe77.png)
I'll be testing this out in other biomes in addition to Forest Hills, and will let you know what I find.

**Comment by SamJBarney** [comment]
That's probably due to a bug in the block code for the base block. I'll look into it.

**Comment by nichwall** [comment]
Alrighty. Just some additional information that I found for when you're looking at it. The server only lets you plant if the above block is clear, so it's at least checking the block above. But in all of my tests, planting on top of a block would cause the above bug, but if planted on the side of a block (in a corner), the bottom disappears and the top yields no drops.
