### ISSUE TITLE
new Testing branch?

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2266]
The brand changes did not make it into the testing branch (and some cool features like the AI).
We could either cherry-pick stuff, or start a brand new testing branch.

**Comment by worktycho** [comment]
Or we could try and stabalise the current one, so that we can advance the train. Specifically we need to fix all of  the issues in https://github.com/cuberite/cuberite/milestones/Testing-0.1, before any stable version can be released.

**Comment by SafwatHalaby** [comment]
Okay, how about cherry-picking all name changes then? We don't want the first Cuberite release to not be called Cuberite.

**Comment by madmaxoft** [comment]
I have a feeling that the current master is much more stable than testing, so it might make sense to actually drop the old testing and set it to current master.

**Comment by worktycho** [comment]
Why? We haven't fixed the bugs yet.

**Comment by madmaxoft** [comment]
We have fixed too many other bugs.

**Comment by worktycho** [comment]
We've also introduced a bunch of other features, which will have there own bugs. We need to keep track of the bugs so we can cherry-pick them, or we'll never get a stable testing.
