### ISSUE TITLE
Item multiplication bug (survival mode)

### ISSUE THREAD

**Issue by Nixtren** [cuberite/cuberite#2272]
Hi everyone,

It looks like Cuberite has an item multiplication bug. If you are on Survival and have a chest on your hand, you can right click to place the chest on the ground. The problem is, the chest doesn't actually disappear from your hand slot (it becomes invisible?). Basically I get an invisible chest in my hand, and I can right click unlimited times to place it on the ground, the result is tons of (visible) chests appearing.

The chest is just an example, my friend found some other items (not all) that have the same behavior.

The good thing is, I have created a plugin as a temporary solution to this problem, you can see and download it here:
https://gist.github.com/Nixtren/fc4bdb51d3a11a6431a7

**Comment by Seadragon91** [comment]
Duplication of #1700.

**Comment by madmaxoft** [comment]
Nice to see we're finally attracting the good kind of people, who see a problem, and not only repor it, but also try to fix it :)

**Comment by Nixtren** [comment]
It's the first time I messed around with the API/Plugin thing, it was fun.
I will be closing this issue since it's a duplicate of #1700.
By the way, I have updated the plugin, if you are using it you should update ASAP:
https://gist.github.com/Nixtren/fc4bdb51d3a11a6431a7
