### ISSUE TITLE
1.7.2 Crash when uknown item

### ISSUE THREAD

**Issue by OdnetninI** [cuberite/cuberite#2275]
If you connect and you kill a sheep using 1.7 versions, Minecraft Crashes.
You can connect with 1.8 and get the item, but with the item in the inventory, if you try to connect with 1.7, it crash again.

**Comment by Seadragon91** [comment]
Since mc 1.8, you get an item named [raw mutton](http://minecraft.gamepedia.com/Raw_Mutton) for killing a sheep. Minecraft 1.7 doesn't lnow that item and crashes.

**Comment by OdnetninI** [comment]
I know, but, if you are connected using 1.7 protocol, these items should not be sent to the client.

**Comment by OdnetninI** [comment]
Or, at least, send a Dummy item, for example: stone.

**Comment by Seadragon91** [comment]
Well the item gets sent. Normally you wouldn't be allowed to connect with 1.7 client to a 1.8 server, but cuberite has support for 1.7 and 1.8 items.
Solutions I have, would be to disallow the client to join a 1.8 server with 1.7 client, that is possible with a lua plugin. Another would be to disallow the pickup of items for players with 1.7 client, here would be the problems with chests that contains 1.8 items.

**Comment by Seadragon91** [comment]
Found the [version limiter](http://forum.mc-server.org/showthread.php?tid=1333&pid=11875#pid11875) plugin.

**Comment by OdnetninI** [comment]
Thanks, but I think that my idea should be added, because we could create a 1.7 and 1.8 server...

**Comment by Seadragon91** [comment]
Well I don't see much sense in supporting 1.7 and 1.8 clients for a server. Whats the benefits, in doing that? It would be necessary to add  away to cancel the sending of packets. I think the support for 1.7 is still in the server because ProtoProxy* has not been updated to 1.8.

* A proxy to log all packets between client / server for analyzing.

**Comment by OdnetninI** [comment]
For example: I'm a 1.7 Player, i don't like 1.8.

**Comment by ard1998** [comment]
I think this issue can be closed now.

**Comment by LogicParrot** [comment]
Related: #3201
