### ISSUE TITLE
compilation error on debian 7 64 bit RELEASE

### ISSUE THREAD

**Issue by tonibm19** [cuberite/cuberite#2281]
Scanning dependencies of target OSSupport
[ 26%] Building CXX object src/OSSupport/CMakeFiles/OSSupport.dir/CriticalSection.cpp.o
In file included from /MCServer/src/./Globals.h:248:0,
                 from /MCServer/src/OSSupport/CriticalSection.cpp:2:
/usr/include/c++/4.7/chrono: In instantiation of 'struct std::chrono::duration<int, std::ratio_multiply<std::ratio<1ll, 1000ll>, std::ratio<50ll> > >':
/MCServer/src/./Globals.h:451:62:   required from here
/usr/include/c++/4.7/chrono:227:2: error: static assertion failed: period must be a specialization of ratio
make[2]: *** [src/OSSupport/CMakeFiles/OSSupport.dir/CriticalSection.cpp.o] Error 1
make[1]: *** [src/OSSupport/CMakeFiles/OSSupport.dir/all] Error 2
make: *** [all] Error 2

**Comment by bearbin** [comment]
Just a FYI, debian 7 is no longer debian stable it is debian oldstable so you should upgrade to debian 8 if possible.

**Comment by tonibm19** [comment]
my vps provider doesn't support debian 8 and I have errors with dist-upgrade so...

**Comment by worktycho** [comment]
Looks like the std lib that gcc ships with on debian 7 doesn't support std::ratio_multiply. You'll need to either upgrade or switch to an alternative std::lib. I would recommend upgrading to gcc 4.8 or clang 3.4 as that's what we test against.
