### ISSUE TITLE
Appveyor fails

### ISSUE THREAD

**Issue by LO1ZB** [cuberite/cuberite#2297]
Appveyor tryes to build using "Visual Studio 14 2015"
https://ci.appveyor.com/project/madmaxoft/mcserver/build/1.0.1352#L44

cmake (Appveyor  log):
```
-- Building for: Visual Studio 14 2015
-- The CXX compiler identification is MSVC 19.0.22816.0
-- The C compiler identification is MSVC 19.0.22816.0
-- Check for working CXX compiler using: Visual Studio 14 2015
-- Check for working CXX compiler using: Visual Studio 14 2015 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler using: Visual Studio 14 2015
-- Check for working C compiler using: Visual Studio 14 2015 -- works
```

In my experiments last week, Cuberite did not compile using VS 14 2015

**Comment by NiLSPACE** [comment]
Perhaps we can try to fix Cuberite compiling on VS 2015 instead of making Appveyor use VS 2013.

**Comment by madmaxoft** [comment]
Everyone in the GitHub org should be able to make changes to the Appveyor project settings, if you login there with a GitHub account.

**Comment by LO1ZB** [comment]
@NiLSPACE  I reinstall VS 14 on my vm right now and try again later.

**Comment by worktycho** [comment]
@NiLSPACE I think we need to keep appveyor compiling with VS2013. VS2013 is our main limiter in what c++ features we can use, as both gcc 4.8 and clang 3.4 support a super-set of its feature.

**Comment by worktycho** [comment]
@madmaxoft I've just tried that, and its not giving me access to the settings.

**Comment by LO1ZB** [comment]
@worktycho only @bearbin is part of the cuberite team atm
https://github.com/orgs/cuberite/people

**Comment by madmaxoft** [comment]
@NiLSPACE was an owner, too. I just added @worktycho and and @tigerw 

I clicked through the Appveyor settings and couldn't find anything related to the VS version.

**Comment by bearbin** [comment]
I just copied how the MCServer organisation was, so anybody you added now weren't owners on the old one.

**Comment by LO1ZB** [comment]
@madmaxoft
http://www.appveyor.com/updates
"You can select build worker image in OS dropdown on Environment tab of project settings or if you use appveyor.yml"
```
os: Previous Windows Server 2012 R2

**Comment by madmaxoft** [comment]
The image had been set to `Windows Server 2012 R2`, I've now set it to `Previous Windows Server 2012 R2`. This is so confusing!

**Comment by LO1ZB** [comment]
switching to 'Previous Windows Server 2012 R2' did the trick.
https://ci.appveyor.com/project/madmaxoft/mcserver/build/1.0.1354
