### ISSUE TITLE
Pickaxe: Efficiency III is broken

### ISSUE THREAD

**Issue by Nanosync** [cuberite/cuberite#2299]
The state of the game will be out of sync when mining Netherrack. However, this works fine on Nether quartz.

edit: apparently it also glitches sometimes with the reason "too many blocks were destroyed per unit time - hacked client?". This glitch can be fixed by asking the client to restart the entire game.

**Comment by bearbin** [comment]
I think because netherrack is a 0/1-tick block to mine with efficiency 3, but nether quartz takes longer

**Comment by jammet** [comment]
Efficiency also is a problem on max level/diamond shovel, when digging dirt. The blocks disappear in the client, but some of them will return after a reconnect. These things are *too* effective somehow, the server doesn't seem to be able to keep up.

**Comment by KingCol13** [comment]
Confirmed fixed by #4938.
