### ISSUE TITLE
Cows do not breed

### ISSUE THREAD

**Issue by Nanosync** [cuberite/cuberite#2300]
Cows do not seem to breed even though they are fed with wheat.

**Comment by SphinxC0re** [comment]
@SafwatHalaby That's for you

**Comment by Seadragon91** [comment]
@Nanosync Here a thread about the AI of mobs
http://forum.mc-server.org/showthread.php?tid=1895

**Comment by SafwatHalaby** [comment]
I'm currently not working on stuff due to exams. I'll do it eventually :)

**Comment by SafwatHalaby** [comment]
Implemented in https://github.com/cuberite/cuberite/pull/2696.
