### ISSUE TITLE
More Nether Portal inconsistency

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2315]
Going through the nether used to be a pretty clean and mostly reliable process, but since a few weeks, the behaviour was changed, I arrive in half-loaded worlds and drift around for 10 seconds or so, and the nether portal on the other side already noticed I was standing in it and transported me back before I even arrived, unless I run forward and jump like crazy, hoping I don't stand in the portal anymore, even if I don't see it.

Then usually after an attempted infinite loop, it breaks and Nether portals don't do anything anymore. Also, a lot of the time I go through a gate, I see thousands of dirt blocks floating in the air for no reason. I've already wrote about a few other issues with the old Nether Portals (for instance travel distance was 1:1, instead of 1:8, which seems to have been fixed now).

I hope something can be done about this, right now the Nether is just about unusable. You step into that gate, be ready to meet your maker.

![2015-07-05_10 26 31](https://cloud.githubusercontent.com/assets/11940735/8510933/6ce956c6-2300-11e5-9f33-1550a35c1b8f.png)

**Comment by LogicParrot** [comment]
I'm closing this because each of the mentioned specific issues has its own issue.
 - Teleportation loops #2963 
 - Walls of leaves #2405
