### ISSUE TITLE
Implement vanilla style falling prevention when the current chunk is not loaded

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2316]
Cuberite should prevent entities from falling through blocks in unloaded chunks.
This is because entities, or at least players slowly fall when the chunks they are in are not loaded.
Vanilla does this. It is possible to save the location of an entity when entering an unloaded chunk, and teleporting him back when the chunk gets loaded.

This will fix a lot of nether portal problems we currently have, but it's not just portals, it's always when an entity enters an unloaded chunk.

http://forum.mc-server.org/showthread.php?tid=2044&pid=21678#pid21678

**Comment by NiLSPACE** [comment]
It wont fix the problem where players are teleported 1000 blocks in a different direction, but it will fix the problem where players fall beneath the portal.

**Comment by tigerw** [comment]
I think the slow-falling is done by the client already; what must be implemented is block clipping detection on the server.

**Comment by NiLSPACE** [comment]
Yup exactly. The clients slowly fall, which can cause them to clip into blocks.

**Comment by jammet** [comment]
It happens a lot on the server run on a Raspberry Pi 2. It's not that slow  a device, and even the Pi 1 can run the server just fine - and was capable of handling nether portal transitions before the changes made to the Portal scanner code in May.

**Comment by jammet** [comment]
It seems that the server currently has a chunk loading problem (performance wise). It might be related to the current problems. Still of course I would like to have that clipping protection. It just makes sense to have it.
