### ISSUE TITLE
Limit chunk load cascading

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#2322]
It is possible for the server to cascade loading chunks more or less indefinitely.

When a new world is generated, the water and lava on chunks' boundaries is set to non-stationary, so that when the neighboring chunk is loaded / generated, the liquids are properly woken up. However, this causes the neighbors to be generated, along with their new liquid edges, forcing yet further chunks to load / generate.

This way I had over 3000 chunks loaded in my server within some 10 minutes, without anyone ever connecting to the server.

**Comment by madmaxoft** [comment]
False alert, this only happens with @SamJBarney 's Wasteland plugin because it calls `cWorld:SetBlock()` within loaded chunks.

**Comment by tigerw** [comment]
Would your initial diagnosis also cause this problem?

**Comment by SamJBarney** [comment]
@tigerw I don't think so. We don't see that kind of behavior in the normal server, but it could be something that is happening.
One thing that could be done to test it is hooking into the chunk generation and placing a liquid at the edges of a chunk. If the chunk count explodes like it did with my Wasteland plugin, then @madmaxoft was correct with his original diagnosis.

**Comment by madmaxoft** [comment]
No, the fluids only convert (call `SetBlock`) after checking all their neighboring blocks, and the check fails if the chunk is not loaded.
