### ISSUE TITLE
Support ageable mob

### ISSUE THREAD

**Issue by hallucino** [cuberite/cuberite#2326]
I have not found any opened issue to tha.

We could have some ageable mobs for:
pig
rabbit
sheep
villager
horse
ocelot
wolf

If nobody is working on that, I can send a pull request.

**Comment by NiLSPACE** [comment]
Go ahead, I believe nobody is working on it :)

**Comment by jan64** [comment]
Related: #2195

**Comment by hallucino** [comment]
@NiLSPACE I will add the export of the following lua functions (cMonster):
GetAge
SetAge
IsBaby

Is it ok ?

If this modification + the usage of the HOOK_SPAWNING_MONSTER hook, we will be able to spawn baby mobs directly from lua.

**Comment by SphinxC0re** [comment]
Yep :+1:

**Comment by hallucino** [comment]
@SphinxC0re @NiLSPACE I don't know if the previous method is the best. I could also change SpawnMob function ? What do you think ?

**Comment by NiLSPACE** [comment]
Changing the SpawnMob function should work fine, though you'll have to check if the type of monster actually has a baby version.

Sorry that I didn't respond to you, the internet on our vacation suddenly shutdown, which is obviously even worse then the 1300ms ping we had previously (and currently have back).

**Comment by hallucino** [comment]
Ok I will close this CL, you can use baby mobs with Essentials:
https://github.com/mc-server/Essentials/issues/35

Have fun !

thx @NiLSPACE @SphinxC0re
