### ISSUE TITLE
Custom banners fail

### ISSUE THREAD

**Issue by mmdk95** [cuberite/cuberite#2332]
Server loses track of custom banners you try to create

```
**** window lost sync at item 5 in slotArea with 2
My item: -1:0:0 * 0
Their item: 425:15:15 *1
```

**Comment by NiLSPACE** [comment]
Yes, banners aren't implemented yet.

**Comment by mmdk95** [comment]
that explains a lot then

**Comment by mmdk95** [comment]
@NiLSPACE I have a question, if there is no name in the console can I assume it is not implemented?

**Comment by NiLSPACE** [comment]
I'm afraid I don't understand the question.

**Comment by mmdk95** [comment]
well, in the console of the running server, whenever you move an item in the crafting grid view, I get as output in the console "WindowClick: WinID [#]m SlotBum [#]m action [...] [itemname] x [#]"

when I do this with the unimplemented banner I see "WindowClick: WinID [#]m SlotBum [#]m action [...] 425:15 x [#]" So the item number instead of the name

Does that mean it is not implemented yet?

**Comment by NiLSPACE** [comment]
I think that just means that we haven't updated the itemtype to name list. Also, are you using a debug build, because you shouldn't get those messages in a release build.

**Comment by mmdk95** [comment]
Yeah, I was testing what this server couldn't do on the debug build, and that is an easy way to see if something is up

**Comment by SphinxC0re** [comment]
might be a duplicate of #1535

**Comment by mmdk95** [comment]
Yeah probably, close it
