### ISSUE TITLE
Right mouse button dragging of items in crafting grid broken for HOOK_PRE_CRAFTING

### ISSUE THREAD

**Issue by SamJBarney** [cuberite/cuberite#2345]
You can see this problem in action by installing my [Wasteland](https://github.com/SamJBarney/Wasteland) plugin and crafting 4 sticks in a square together.
Start by dropping each stick in individually just to see the recipe working.
Then clear the crafting window and right-click drag the recipe. You will see the resulting item does not show up.
Removing one of the sticks and placing it back in makes the resulting item show up.

Edit: The recipe is still usable. If you click on the empty result slot, you will get the crafted item. It is just not showing up.

**Comment by madmaxoft** [comment]
This is a client-side bug, MCServer is sending the slot contents correctly. I'll try to create a workaround for this.

**Comment by madmaxoft** [comment]
As a workaround, the server now sends the result slot twice. This seems to have fixed the 1.8 client.
