### ISSUE TITLE
Hunger is linked to going up

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2354]
There is a new skyscraper on my server and when you go all the way up using a ladder, you run completely out of food *twice*. That's ... crazy.

**Comment by tigerw** [comment]
Climbing a ladder is hard when the ladder in question is a 2D image and YOU HAVE NO FINGERS
![Steve](http://static.planetminecraft.com/files/resource_media/screenshot/1152/minecraft_guy___download___by_sureindragon-d3l7eco_1086219.jpg)

**Comment by tigerw** [comment]
In all seriousness, I would say this is another manifestation of #2044.

**Comment by bearbin** [comment]
Closed, dupe of #2044
