### ISSUE TITLE
Style checker checks style inside comments

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#2355]
For a scenario as follows:
```cpp
static const std::array<unsigned char, 4> BrightnessID = { 3, 0, 1, 2 };  // Deepest/darkest to lightest
```
The style checker reports the following violation: `1 .. 95: Add space around /`

Diagnosis: checker does not ignore comment and examines solidus present in "... Deepest**/**darkest ..."

**Comment by bearbin** [comment]
This was discussed initially when that rule was introduced, and you said it was OK I think :P

**Comment by tigerw** [comment]
#1954 - nah. xoft's just breakin' stuff

**Comment by tigerw** [comment]
Actually, since this was pretty much intentional, what does @madmaxoft say about it?

**Comment by madmaxoft** [comment]
I say this is a wanted feature. We want properly typographically correct formatted comments as well.

**Comment by tigerw** [comment]
I was never taught/had never read about slashes being written / typed with spaces around them.

http://english.stackexchange.com/questions/2131/should-i-write-comma-period-or-comma-period
