### ISSUE TITLE
Cactie grow too fast

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2358]

**Comment by SamJBarney** [comment]
http://minecraft.gamepedia.com/Cactus#Farming

**Comment by NiLSPACE** [comment]
More like "Everything that can grow grows too fast."

**Comment by SamJBarney** [comment]
Yeah. I think this will be the next bit I take on, once my current pull requests are complete.

**Comment by SphinxC0re** [comment]
@SamJBarney You need to be online on IRC for more instant response

**Comment by mathiascode** [comment]
Duplicate of #1667
