### ISSUE TITLE
Holding a food item should ignore non-functional blockinteraction

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2359]
ATM when you eat something while pointing at a block, eating fails or looks stupid

**Comment by madmaxoft** [comment]
But plugins... What if a plugin wants to redefine how items interact.

Consider the compass tool in WorldEdit. If we disabled all interactions for the tool (which would be logical at that time), the new behavior would not have been possible.

**Comment by SphinxC0re** [comment]
It's not about items in general, it's about food

**Comment by SamJBarney** [comment]
Which blocks are you pointing at? I can't seem to find one that does it

**Comment by SphinxC0re** [comment]
any while holding food and while you are hungry

**Comment by SamJBarney** [comment]
I'm not having that issue.

**Comment by madmaxoft** [comment]
I remember reading somewhere that eating while looking at a fence is glitching in the client, could that be the issue?

**Comment by SphinxC0re** [comment]
No, it's not just fences. If I point at any block, that isn't interactive while eating, it glitches horribly

**Comment by SamJBarney** [comment]
I just started having this issue. Oh my goodness it is horrible.

**Comment by SphinxC0re** [comment]
Yeah and many of my friends are complaining about this bug, too. Seems to be the main reason for them to not switch from Vanilla to Cuberite

**Comment by tigerw** [comment]
Appears to be fixed.
