### ISSUE TITLE
Default permissions are wrong (core.tp)

### ISSUE THREAD

**Issue by Tgwizman** [cuberite/cuberite#2369]
In WebAdmin, the permission group Teleport contained core.tp, but the permission in core's Info.lua file is core.teleport. Another issue with WebAdmin is that it doesn't allow you to remove a permission group from any rank. It gives me the error message: An internal error has occurred, no handler for subpage removegroup.

**Comment by madmaxoft** [comment]
The latter error is a problem in the Core plugin, I've copied the issue there.

The first issue is a problem with default permissions created when the server starts for the first time, and is rightfully reported here.
