### ISSUE TITLE
Allow plugins to register channels for cClientHandle for Forge compatibility 

### ISSUE THREAD

**Issue by SamJBarney** [cuberite/cuberite#2378]
Forge doesn't register each plugins channel individually. The initial REGISTER sent by a Forge client contains a list of all of the plugin channels, as far as I have been able to determine. This is also, I believe, how Forge server determines whether the client is compatible or not.

So being able to register plugin channels from a plugin is necessary for Forge compatibility.

**Comment by worktycho** [comment]
Can we please not put this in cClientHandle. channels need their own managing object

**Comment by SamJBarney** [comment]
I don't really care. I just want to be able to register channels.

**Comment by SamJBarney** [comment]
I mean, it would be great to register handlers for specific channels instead of iterating through all of the hooks.

**Comment by SamJBarney** [comment]
Just did a bit of digging. We're handling it correctly. Adding the ability to register channels from plugins won't help.
