### ISSUE TITLE
Remove interface cast in BlockTrapdoor.h

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#2386]
BlockTrapdoor.h uses the cast from interface to specific class, this should be removed:
```cpp
cWorld * World = (cWorld *) &a_WorldInterface;
```

Wait until the warning fixes PR is merged to avoid merge conflict.

**Comment by gauraVsehgaL** [comment]
I see the following code,
  `cWorld * World = static_cast<cWorld *>(&a_WorldInterface);`
Is this already fixed?

**Comment by madmaxoft** [comment]
No, it's not fixed. A proper fix would be to add the `BroadcastSoundParticleEffect()` function into `cBroadcastInterface` as a pure virtual function, then mark the `cWorld` implementation as `virtual override` of that. The cast can then be removed and the broadcast function called via `a_WorldInterface.GetBroadcastManager().Broadcast...()`
