### ISSUE TITLE
Error while compiling: error: r7 cannot be used in asm here

### ISSUE THREAD

**Issue by bramvdbogaerde** [cuberite/cuberite#2387]
Full log:
```
[  1%] Built target jsoncpp
[  5%] Built target zlib
[ 11%] Built target lua
[ 12%] Built target tolualib
[ 13%] Built target tolua
[ 14%] Built target sqlite
[ 15%] Built target SQLiteCpp
[ 16%] Built target expat
[ 16%] Built target luaexpat
[ 21%] Built target event
[ 26%] Built target event_core
[ 31%] Built target event_extra
[ 34%] Built target OSSupport
[ 35%] Built target Noise
[ 36%] Building C object lib/polarssl/library/CMakeFiles/mbedtls.dir/bignum.c.o
/root/cuberite/lib/polarssl/library/bignum.c: In function ‘mpi_mul_hlp’:
/root/cuberite/lib/polarssl/library/bignum.c:1131:1: error: r7 cannot be used in asm here
 }
 ^
lib/polarssl/library/CMakeFiles/mbedtls.dir/build.make:192: recipe for target 'lib/polarssl/library/CMakeFiles/mbedtls.dir/bignum.c.o' failed
make[2]: *** [lib/polarssl/library/CMakeFiles/mbedtls.dir/bignum.c.o] Error 1
CMakeFiles/Makefile2:690: recipe for target 'lib/polarssl/library/CMakeFiles/mbedtls.dir/all' failed
make[1]: *** [lib/polarssl/library/CMakeFiles/mbedtls.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
````

Platform: armv7l
OS: Ubuntu 14.10

**Comment by zackp30** [comment]
https://tls.mbed.org/kb/development/arm-thumb-error-r7-cannot-be-used-in-asm-here



If site ever goes down:


> Platform
> ARM (Thumb assembly)
> 
> What
> Depending on the GCC compiler options used, you can receive an error:
> 
> error: r7 cannot be used in asm here
> Reason
> The assembly code in bn_mul.h is optimized for the ARM platform and uses some registers, including r7 to efficiently do an operation. GCC also uses r7 as the frame pointer under ARM Thumb assembly.
> 
> Solution
> Add -fomit-frame-pointer to your GCC compiler options.
> 
> If you have already added -O, -O2, etc you do not need to add -fomit-frame-pointer as the optimization options already include it on most systems by default.

**Comment by bramvdbogaerde** [comment]
I tried that before but I added the flag in the wrong place.
It compiles now.
Thanks.

**Comment by madmaxoft** [comment]
@bramvdbogaerde so what exactly did you change? Something in the PolarSSL cmakelist?

**Comment by bramvdbogaerde** [comment]
I added the following line in "SetFlags.cmake" in the macro "set_flags":
add_flags_cxx("-fomit-frame-pointer")

**Comment by madmaxoft** [comment]
I'll need someone more Linux-educated. @worktycho ?
Is it safe to include that flag for all builds on all platforms? Should we add it  as-is, or inside a conditional block?

**Comment by worktycho** [comment]
The only reason it is turned off by default is that it can reduce the debug experience. I'd suggest wrapping in a flag to only be added on ARM in debug mode.

**Comment by madmaxoft** [comment]
Sounds reasonable.
