### ISSUE TITLE
Placing non-vanilla blocks possible

### ISSUE THREAD

**Issue by SamJBarney** [cuberite/cuberite#2389]
If I connect to a cuberite server with a forge client in creative, and I have mods installed that provide blocks, I can place non-vanilla blocks on a cuberite server. I'm sure this causes all kinds of issues with a vanilla client, but I haven't tested it yet.

**Comment by madmaxoft** [comment]
This is not a bug, this is a feature. We ignore all unknown blocks, consider them all solid nontransparent etc.
