### ISSUE TITLE
Add the Roofed Forest Biome

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#239]
Has dark grass and giant mushrooms with 2 by 2 dark oak trees
Has extremely dense trees and leaves; dark and dangerous under the canopy even during the day
Monsters will most likely be able to spawn during the day and the night
Monsters that spawned at night can survive during the day
Naturally spawns with giant mushrooms

- [x] Dark forests feature a much higher density in trees compared to other forest biomes
- [x] Oak, dark oak, and (sometimes) birch trees generate in these biomes;
- [x] both types of huge mushrooms generate among the trees, though the red variants are more common.
- [x]  Flower Generation: #4723 
     - [x] rose bushes
     - [x] peonies
     - [x] lilacs
     - [x] dandelions
     - [x] poppies

**Comment by NiLSPACE** [comment]
Roofed forest doesn't have 2x2 spruce trees. I'll change it :) Also, why is `Has dark grass` in this issue? I know it's true, but the server can't do anything with that information.

**Comment by madmaxoft** [comment]
I guess it's just a text copied from the wiki. The grass tint is client-side and is already working for the biome.

**Comment by 12xx12** [comment]
At this point it's missing
- [ ] the shroom
- [ ] some natural grass generation - the biome looks quite empty
