### ISSUE TITLE
Enchantment Table vs Book Shelves

### ISSUE THREAD

**Issue by JBar2000** [cuberite/cuberite#2395]
When stacking bookshelves to increase enchantment levels within the enchantment table:
1) only 2 rows of bookshelves are used. Third row high should be recognized
2) hiding a bookshelf in the corner also does not work.

**Comment by Outfenneced** [comment]
I know this is old, but in the sake of helping to clean up issues:
The third row height of bookshelves should not be counted according to http://minecraft.gamepedia.com/Enchantment_mechanics#Bookshelf_placement

Also, putting bookshelves in the corner does seem to work, there just needs to be an air block on the diagonal between the bookshelf and the enchanting table (there cannot be any block, not even a grass blade). Placing the bookshelves in the first configuration shown in the link above (a ring with one block left out) gives level 30 enchants.

There seems to be no issues here, tested with build ID 185.
