### ISSUE TITLE
Where are the Nether Beasties?

### ISSUE THREAD

**Issue by JBar2000** [cuberite/cuberite#2397]
Not finding Blazes.
Not finding Wither Skeletons.

**Comment by SphinxC0re** [comment]
I'm sorry @SafwatHalaby :wink: 
@JBar2000 Yeah this seems to be a problem with world generation and spawning. Thanks

**Comment by NiLSPACE** [comment]
If it's a problem with world generation and spawning then it shouldn't have the AI label right?

**Comment by SphinxC0re** [comment]
Isn't spawning part of the AI?
