### ISSUE TITLE
Add the Birch Forest Biome

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#240]
A forest made entirely of birch trees.

**Comment by NiLSPACE** [comment]
I believe we have implemented this already. Can anyone confirm?

**Comment by madmaxoft** [comment]
We do have a birch forest, but I'm not sure if we have all the variants (are there four of them? With the ones with the huge birches are most likely missing)

**Comment by NiLSPACE** [comment]
You mean #481 <- this?

**Comment by ard1998** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/16983916/22210064/df0b0a5e-e188-11e6-8180-a5743bba22b5.png) this one is added
