### ISSUE TITLE
Glitch while breaking the lower half of tall grass (2 block high grass)

### ISSUE THREAD

**Issue by LO1ZB** [cuberite/cuberite#2401]
Cuberite is sending the wrong meta/block id for the upper half of the 2 block high grass just befor it gets destroyed when you destroy the lower part of it.
![bug007](https://cloud.githubusercontent.com/assets/7173513/8934342/7e010b26-3547-11e5-851b-5de92ef5a588.gif)

**Comment by madmaxoft** [comment]
Are you sure that the server is actually sending the block change packet? It could be entirely client-side.

**Comment by LO1ZB** [comment]
I'm using vanilla 1.8.7, I saw it first with 1.8.0.
Since the proxy only supports 1.7.x, I cannot test what packets are send to the client.

**Comment by LO1ZB** [comment]
https://github.com/cuberite/cuberite/blob/master/src/Blocks/BlockBigFlower.h#L54
38:7 is the 'Pink Tulip' wich you can see in the gif

**Comment by madmaxoft** [comment]
Cuberite has its own packet logging, start the server with params `--log-comm-in`, `--log-comm-out` or `--log-comm` to log the packets (incoming, outgoing, both) to a file.

**Comment by LO1ZB** [comment]
ok I'll try that

**Comment by NiLSPACE** [comment]
I believe you see the same in vanilla. Could you try it there as well?

**Comment by SamJBarney** [comment]
I have seen this in vanilla before, but I think they fixed it in the newer versions

**Comment by LO1ZB** [comment]
Ok Ife got a log but I have no idea what packet I'm searching for

**Comment by madmaxoft** [comment]
You're searching for the player left-click packet being followed by a setblock or setblocks packets

**Comment by nichwall** [comment]
I've been looking at fixing this for a couple days, but have been traveling without internet. I don't know how useful this will be to you, but I've noticed that when attempting to place a block on the side of a block (instead of top), `ItemBigFlower.h` will prevent the bottom block from being placed, and instead a peony top is placed where the top should have gone.

**Comment by jammet** [comment]
I've seen this happening for several months, though didn't report it because it seems to be a minor thing. Though it might actually be related to issues like rosebushes missing the top part, and other flowers just being stumps, too.

**Comment by Woazboat** [comment]
Replacing the lower block of tall grass with another block causes the upper block to be transformed into a flower like described here, but the flower stays behind and isn't instantly destroyed. 
Breaking the flower that replaced the upper grass block also destroys the new block under it that was used to replace the lower grass block.
https://imgur.com/55szYmF

This is probably the cause of #1428

**Comment by mathiascode** [comment]
This is a client side issue in older MC versions. Tall grass in Cuberite has been fixed some years ago.
