### ISSUE TITLE
Boats are like submarines and can't be pushed on land

### ISSUE THREAD

**Issue by mmdk95** [cuberite/cuberite#2403]
When boats are placed on water they submerge. When you place them on land you can't push them.

They work fine when you are mounted on the boat (when placed on land that is)

**Comment by SphinxC0re** [comment]
Any objections about the milestone? @madmaxoft @worktycho @tigerw @NiLSPACE @bearbin

**Comment by madmaxoft** [comment]
Good enough. Although I have never used a boat in my games :P

**Comment by SphinxC0re** [comment]
?? What ?? It's the fastest way to travel trough water

**Comment by madmaxoft** [comment]
The fastest way is not to travel through water at all :P

We're getting off-topic, I'll delete these comments after a while.

**Comment by jammet** [comment]
Let's hope boats are going to be functional at some point. Right now, crossing oceans means a good hour of "fun", sometimes.

**Comment by madmaxoft** [comment]
The best way to cross an ocean is to dig down to level 10 and dig a straight tunnel, with rails :)

**Comment by jammet** [comment]
If you want a permanent link, that's right. :) But nothing beats the
adventures to be had with a boat. ;) Come on, throw me a bone ... no, not
literally ....

**Comment by madmaxoft** [comment]
:meat_on_bone:

**Comment by tigerw** [comment]
xoft uses meat_on_bone!

**Comment by madmaxoft** [comment]
It's super-defective

**Comment by jammet** [comment]
Om Nom Nom Nom!

**Comment by tigerw** [comment]
Everyone is in a jovial mood today.

**Comment by madmaxoft** [comment]
Just until @madmaxoft comes with a Del-hammer...

**Comment by SamJBarney** [comment]
In the meantime, you could always play with a forge client that has smart moving enabled, and bump up the swimming speed.

**Comment by jammet** [comment]
That'd be cheating! Can't do that no sir :). That's like playing Dr. Mario
when I wanna play Columns. ;)

**Comment by mathwhiz1212** [comment]
Same problem here, puts a real damper on escaping via water on a PvP server.

**Comment by Schwertspize** [comment]
Guys, currently you can easily escape by riding your horse in the water :) just to mention that

**Comment by mathiascode** [comment]
Doesn't seem to be an issue anymore.
