### ISSUE TITLE
Use Regular Expressions instead of pattern matching in the CheckBasicStyles-script

### ISSUE THREAD

**Issue by bibo38** [cuberite/cuberite#2407]
Like the title says, the current CheckBasicStyles.lua-script uses [pattern matching](http://www.lua.org/manual/5.2/manual.html#6.4.1) to verify the Code-style.
It has some nice things, like the *%* as an escape character, but lacks in terms of possibilities.

E.g. The hex-numbers should have even digits length(a todo in the script), but with Pattern matching, this is not possible.

So I would suggest to create annother script or change the existing script to use (PCRE) Regular Expressions.

**Comment by NiLSPACE** [comment]
But Lua doesn't have regex by default. We'd have to use a different language or download a regex library.

**Comment by bibo38** [comment]
Yeah, I know. I would prefer to use Perl.
Would it be a problem to use a different language(travis builds, ...)?

**Comment by NiLSPACE** [comment]
Travis might have to download the language first making the build time longer.

**Comment by madmaxoft** [comment]
I don't want yet another language in the project, there's already too many to learn. And I won't be able to maintain the checker in another language.
Why wouldn't Lua patterns be capable of checking even number of hex digits?
`0x[0-9a-f]([0-9a-f][0-9a-f])*` triggers for odd length.

**Comment by madmaxoft** [comment]
Oh, right, the pattern won't work, but it's still possible to check, we'll just need to add a new class of checkers that not only have a pattern, but also a processor function.

**Comment by bibo38** [comment]
Maintaining the new thing shouldn't be the problem.
Also we can use some existing languages to do the checks:
- Lua with [lrexlib](https://github.com/rrthomas/lrexlib)
- C++ with [std::regex](http://www.cplusplus.com/reference/regex/) or the more powerful [boost::regex](http://www.boost.org/doc/libs/1_58_0/libs/regex/doc/html/index.html)
- Javascript(has regex default support) executed via [NodeJS](https://nodejs.org/) or something similar.
- Java via the [Pattern class](http://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html)

Also readling/writing functions makes the code more complex... Even the indention thing is possible to check via one or two Regular expressions.

**Comment by madmaxoft** [comment]
I still think pure Lua is the best idea, since it's used for the bindings generation as well (so we already need to have it available).

Maintaining would be a problem if the lead developer insterested in the coding style woouldn't speak the tool's language :P

**Comment by bibo38** [comment]
So why not use lua with lrexlib or C++? These languages are the "main" languages and heavily used in this project.

**Comment by madmaxoft** [comment]
Because they need non-trivial installation (or are downright inaccessible) on some platforms. Note that the check script is used not only during the CI builds, it can also be used as the pre-commit hook or a standalone tool callable from an IDE. The more difficult we make the setup for these, the less they will be used by people.

**Comment by bibo38** [comment]
What about Java? It is used for the Android things and is trivial to execute? Also everyone who uses Minecraft has Java installed. And for those, who don't have the JDK you could provide a precompiled jar file...

**Comment by madmaxoft** [comment]
Usually there's no Java on RasPi and other server platforms. And we're writing the Cuberite server in C++ because the general view of Java is, let's say, unfavorable.

Why are you so intent on changing this? It works, what's the big deal?

**Comment by bibo38** [comment]
I just wanted to add some missing todos and maybe some other checks, which the script [doesn't detect](https://github.com/cuberite/cuberite/pull/2370#discussion_r34948316).
But when I saw the script, this things require writing your own checking code. So I came on the idea with Regexes...

**Comment by bibo38** [comment]
And also my intention was not to replace the script, but to create annother script, which checks for advanced styling issues.

**Comment by SamJBarney** [comment]
I personally think using lua with lrexlib might be beneficial
