### ISSUE TITLE
(Desert) Villages are somethimes partially submerged.

### ISSUE THREAD

**Issue by LO1ZB** [cuberite/cuberite#2409]
(Desert) Villages are somethimes partially submerged, when they cross a river.
![minecraft 1 8 7 30 07 2015 16_30_52](https://cloud.githubusercontent.com/assets/7173513/8986078/baea3b18-36da-11e5-910c-6135a3c02a12.png)
Seed: 1503938543 (Default world.ini)
X: 2345 Z: 1580

**Comment by NiLSPACE** [comment]
This is for all types of villages.

**Comment by SphinxC0re** [comment]
But they shouldn't

**Comment by NiLSPACE** [comment]
Of course, I was just pointing out that it happens with all types of villages. :)

**Comment by Haxi52** [comment]
![2015-09-26_11 54 25](https://cloud.githubusercontent.com/assets/10181722/10118756/c3a57950-6445-11e5-8082-4055deae6844.png)

Some buildings appear suspended above water as well.

**Comment by madmaxoft** [comment]
I'll try to fix this and provide a generic solution for the structure generator
