### ISSUE TITLE
LibEvent: nameserver has failed

### ISSUE THREAD

**Issue by hexparrot** [cuberite/cuberite#2418]
When starting up a self-compiled server, Cuberite opens without issue.  However, when a client attempts to connect, I get the following in the logs--and the connect attempt fails:

```
[19:04:53] Startup complete, took 4987ms!
[19:08:17] LibEvent: Nameserver [2001:4860:4860::8844]:53 has failed: Network is unreachable
[19:08:20] Cannot connect to sessionserver.mojang.com: Resource temporarily unavailable
[19:08:20] SecureRequest: Can't connect to sessionserver.mojang.com: 
[19:08:20] Kicking player hexparrot for "Failed to authenticate account!" 
```

Similar issue: https://github.com/cuberite/cuberite/issues/1998

This is on an odroid XU-4 (rpi-like ARM) running on ArchLinux.  The nameserver in the logs is the ipv6 address for the Google Public DNS, though it's nothing that I have set in the eth config, nor in the router (but I am using 8.8.8.8 and 8.8.4.4).

Is it possible to compile cuberite/libevent without utilizing ipv6?  Turning off ipv6 via system config seemed to have no effect--the same issue crops up upon user connect attempts.

```
[root@alarm ~]# sysctl -w net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6 = 1
[root@alarm ~]# sysctl -w net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6 = 1
[root@alarm ~]# sysctl -w net.ipv6.conf.lo.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6 = 1
[root@alarm ~]# reboot
```

Any ideas?

**Comment by madmaxoft** [comment]
No idea about this, it looks more like an issue in LibEvent.

**Comment by Seadragon91** [comment]
Can anyone confirm if that still occur? I haven't see that message since months again.

**Comment by fezde** [comment]
I have a similar behavior when starting Cubrite on a raspberry pi with tmux
The error I see when connecting to the server is:

>[17:51:51] LibEvent: Nameserver 127.0.0.1:53 has failed: request timed out.
>[17:51:51] LibEvent: All nameservers have failed
>[17:51:56] Cannot connect to sessionserver.mojang.com: "Resource temporarily unavailable"
>[17:51:56] SecureRequest: Can't connect to sessionserver.mojang.com: 

But this happens only when I start the server from /etc/rc.local using
>su - userName -c 'tmux new -d "cd /home/userName/Cuberite && ./Cuberite" '

When I start the Server from cli directly everything works.... *puzzled*

**Comment by madmaxoft** [comment]
We need to get rid of the LibEvent name resolution, it's too buggy to use. It doesn't work for Windows name resolution (cifs), it sometimes fails with weird reasons...

**Comment by Cl1608Ho** [comment]
Just a note worth throwing in: this is also buggy on some Android devices (for example mine, but not the one of a friend), although it's neither a request timeout nor a network is unreachable but a dns issue.

**Comment by bearbin** [comment]
Closing as mentioned in #2870
