### ISSUE TITLE
Add World:GetPlayerByName(PlayerName) function

### ISSUE THREAD

**Issue by tuberiumf** [cuberite/cuberite#2428]
I think, loop of all players in server  - very expensive for CPU, and i think it would be great if you add this function...

**Comment by worktycho** [comment]
That's all the c++ side of the server would do, so the cpu savings would be negligible. Also, I would quite like to keep our options open for restructuring the player object in the future, so I would object to adding this api.

**Comment by tuberiumf** [comment]
If server has 200 players online, cpu savings would be negligible anyway?

**Comment by worktycho** [comment]
yes.

**Comment by madmaxoft** [comment]
The biggest problem with this API is object lifetime, as usual - one thread grabs the cPlayer object using this API, while another thread deletes the object, because the player has just disconnected. BAM, instant crash.

The best we could currently do is `cWorld:DoWithPlayerByName(callbackFn)`

**Comment by tuberiumf** [comment]
And.. question about API, can i get some extra arguments with callback function?not only player,maybe  another

**Comment by NiLSPACE** [comment]
You can declare arguments above the function. The callback will still be able to use them.

```lua
local MyArgument1 = 5
local MyArgument2 = true
World:DoWithPlayer("NiLSPACE",
   function(a_Player)
      if (MyArgument2 and (MyArgument1 <6)) then
         a_Player:SendMessage("You have passed the random argument test")
      else
         a_Player:SendMessage("You have failed the random argument test")
      end
   end
)
```

**Comment by tuberiumf** [comment]
and if i have callback func in another lua file? it still working???

**Comment by NiLSPACE** [comment]
No, that wouldn't work sadly.

**Comment by tuberiumf** [comment]
ok, close this issue, and pls ask me in another :)
