### ISSUE TITLE
Outsource all librarys

### ISSUE THREAD

**Issue by SphinxC0re** [cuberite/cuberite#2429]
We should make every library a submodule since they are not part of the project itself.
 - [ ] CMake-Coverage
 - [ ] Expat
 - [x] JsonCpp
 - [x] LibEvent
 - [ ] Lua
 - [ ] LuaExpat
 - [x] PolarSSL
 - [ ] SQLite
 - [x] SQLiteCpp
 - [x] TCLAP
 - [ ] ToLua++
 - [ ] Zlib

**Comment by mrkillius24** [comment]
Totally going to waste valuable time reorganizing.
It works and is needed.
This issue is redundant

**Comment by SamJBarney** [comment]
I disagree @mrkillius24 
Organization is a key part of any project. What @SphinxC0re is suggesting is, in my opinion, something that should be given some thought.

**Comment by ApfelUser** [comment]
I disagree with you too @mrkillius24 and share @SamJBarney's opinion. It is also way easier to keep the library's up to date with git submodule's.

**Comment by SphinxC0re** [comment]
Yeah, that's what I mean: A library update is a library update and it should be an update that happens *just* on the library itself.

**Comment by tigerw** [comment]
I believe that all trivially submodularisable libraries have been given the submodule treatment. The rest aren't on GitHub, so the utility of creating a mirror (which their license may disallow) is questionable.

But I don't mind whatever you decide to do :P

**Comment by SphinxC0re** [comment]
The problem is, that I can't do anything about it. I'm *only* collaborator
