### ISSUE TITLE
Add AllowOnlyBungeeCord option in server settings

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#2432]
I think it would be easy and nice to add this option. If true, only players from bungee cord can connect to server :+1: .It would be very great and useful!

**Comment by madmaxoft** [comment]
I don't think this is strictly necessary. From what I understand, you normally only make the bungeecoord gate server available publically; the subservers are accessible only from the gate server and not from the general internet.

**Comment by tuberiumf** [comment]
yes, it necessary, because if hub has online-mode off, there login authorization on hub server, and other servers need be secured

**Comment by worktycho** [comment]
You still should not have direct minecraft connections to the subservers. All connections would be proxyed by the hub.

**Comment by tuberiumf** [comment]
Maybe you do this? As i know in source code, we able to check , Is it a bungee cord connection?

**Comment by NiLSPACE** [comment]
Can we really call this issue easy? I think it needs quite some changes in the network code.

**Comment by SphinxC0re** [comment]
I don't know why I added this label in the first place...

**Comment by NiLSPACE** [comment]
Perhaps because [the first post](https://github.com/cuberite/cuberite/issues/2432#issue-101061637) thought it would be easy :)
