### ISSUE TITLE
Bugged teleportation

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2438]
Two issues I'm having.

The syntax for the command does not seem to be working anymore.

/tp PlayerName X Y Z

That does give me the info on how to use the command, and does not teleport me. It also shows me that there is a parameter (-h) but doesn't say what it's for. Can't figure it out.

I can't teleport other players around anymore -- this used to work.

If I just teleport myself, via /tp x y z, that works, but has a maximung RANGE now. I used to be able to teleleport to -2200 64 300, from 0 0 0 and ... not a problem. Absolutely no problem.

Now it just teleports me to the exact same spot I'm already standing at. If I instead teleport only 1000 blocks away instead of to -2200, via /tp -1000 64 300, that works like a charm.

So ,... something is bugged about it.

**Comment by madmaxoft** [comment]
This is an issue in the Core plugin, re-reported there

**Comment by jammet** [comment]
Oh, alright. Sorry, I didn't know.
