### ISSUE TITLE
Gravel doesn't turn into flint

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#2453]
When breaking gravel, it never turns into flint. I only get gravel blocks.

**Comment by SamJBarney** [comment]
Perhaps the drop chance is too small?
https://github.com/cuberite/cuberite/blob/master/src/Blocks/BlockGravel.h#L19

**Comment by worktycho** [comment]
The chance over 100 blocks of getting no flint is 3 percent. How many blocks of gravel did you break?

**Comment by mathias-github** [comment]
Probably about 30 blocks. Tried placing and breaking a gravel block until I gave up.

**Comment by worktycho** [comment]
That will happen about one third of the time. Try more blocks.

**Comment by madmaxoft** [comment]
The chance is off, anyway. According to the official wiki, vanilla uses a 10% chance for dropping flint:
http://minecraft.gamepedia.com/Gravel

**Comment by jammet** [comment]
I know it's unrelated but it's just like with the weather. I don't know if it's supposed to be 50/50 sun/rain, but it feels like it's raining way too much. I had the weatherlogging plugin running for sometime and it's really 50/50 .... feels more like 70/30 with 30 being sun, to me. Sorry for offtopic.

**Comment by Seadragon91** [comment]
This issue can be closed.
