### ISSUE TITLE
Dying in Nether

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#2454]
When dying in the Nether, you don't respawn in the overworld. You stay in the Nether (and in worst cases you'll keep falling into lava when respawning).

**Comment by NiLSPACE** [comment]
How about we add another variable in the LinkedWorlds section where you can define the world you will be transported to if a player dies.
```ini
[LinkedWorlds]
OverworldName=world
EndWorldName=
OnDeathWorldName=world
```

**Comment by madmaxoft** [comment]
Sounds like a good idea to me.

**Comment by LogicParrot** [comment]
This extra option would only be relevant for players that never slept. Players who slept before should respawn in the world they slept in. I believe my solution in #3091 is better.
