### ISSUE TITLE
Squids go on dry land and die, burning

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2460]
I didn't see this until just now, so it must have been a very recent change.

Squids used to stand completely still before, because their AI wasn't working properly. Safwat, I think, wanted to take care of these at a later point. Now they've started to move again, and they all seem to think they're land creatures, so they go on dry land and burn...

**Comment by SafwatHalaby** [comment]
I thought I completely froze squids as a temporary solution.

**Comment by jammet** [comment]
I know you did, but that changed a while ago. Now they move around again. ^^' Some other change must have interfered.

![2015-09-25_13 32 38](https://cloud.githubusercontent.com/assets/11940735/10099442/f9b5b850-6389-11e5-8feb-8740248d1173.png)

**Comment by SafwatHalaby** [comment]
Found it. Guilty commit: https://github.com/cuberite/cuberite/pull/2446. @tigerw 's commit set the squids loose again because it changed the way `m_IsFollowingPath` behaves.

**Comment by SafwatHalaby** [comment]
Fixed in #2502.
