### ISSUE TITLE
Support block entities in cBlockArea instances

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#2461]
The `cBlockArea` class needs to read and write (and thus store, too) information about block entities contained within its data.

Implementing this may require slight changes into `cBlockEntity`-derived classes as well in order to support containment in a `cBlockArea`, without a `cWorld` instance assigned to them.

There should be a special `baBlockEntities` flag indicating whether block entities should be read from / written to world, similar to how `baTypes` and such are handled.

**Comment by NiLSPACE** [comment]
This would also fix mc-server/WorldEdit#51 and  mc-server/WorldEdit#79

**Comment by SphinxC0re** [comment]
What about saving entities in general?

**Comment by madmaxoft** [comment]
That's yet another issue.

**Comment by madmaxoft** [comment]
I've decided to start some work on this :)

**Comment by madmaxoft** [comment]
This is starting to be an awful lot of new code :P
