### ISSUE TITLE
Player kicked for using modded client

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2467]
Just thought I'd put this out there...

Minecraft 1.8 with the Voxelmap plugin.

[12:02:34] Kicking player ShadowBudgie for "Bad compression"

**Comment by madmaxoft** [comment]
Does it happen reproducibly, 100% of the time, or is it random?

**Comment by SphinxC0re** [comment]
Also the error message doesn't really hint that the mod is the problem. Unless VoxelMap is playing around with your compression

**Comment by madmaxoft** [comment]
It could be playing with the packets, which would be the reason for the failure. That's why we need reproducibility - we need to play around with it with ProtoProxy and find out what's wrong in the network data stream.

**Comment by jammet** [comment]
It does happen every time with that configuration.

**Comment by SamJBarney** [comment]
I've been using SmartMoving and other mods pretty successfully. Perhaps there is something specific to Voxelmap that is causing it. Is Voxelmap a clientside only mod?

**Comment by worktycho** [comment]
It might be worth generating an incoming packet log with the --log-comm flag.

**Comment by Gamerboy59** [comment]
I noticed this happens when joining with a liteloader modified client. Optifine works well e.g.

I can't say what wrong with it because there're no more errors displayed.

**Comment by madmaxoft** [comment]
I'm using LiteLoader + WECUI regularly and my dev servers, as well as the Gallery server, are okay with that.

Unless someone captures the communication (start the server with `--log-comm` parameter), there's not much I can do about it.

**Comment by Gamerboy59** [comment]
Just got this:

```Incoming data: 263 (0x107) bytes:```
```Next incoming packet is type 1 (0x1), length 261 (0x105) at state 2. Payload:```

Does it help? Or d you need anything else? You can reproduce it using (any) transformation mod (like VoxelMap).

**Comment by madmaxoft** [comment]
I'd need the entire log file.

**Comment by Gamerboy59** [comment]
Ok, got one. Please gimme your mail or what ever. Don't wanna post it in public.

**Comment by NiLSPACE** [comment]
You can email it to support@cuberite.org. It will be routed to some of the core members of Cuberite including @madmaxoft.

**Comment by Gamerboy59** [comment]
You just got an email. ;)

**Comment by SphinxC0re** [comment]
I didn't get an email @madmaxoft

**Comment by Gamerboy59** [comment]
From: Gamerboy59 . <myEmail>  
To: support@cuberite.org
 
Date: 15. November 2015 um 22:08 
Subject: Bad Compression

Check your spam folder.. I can send again if there's still no mail.

**Comment by NiLSPACE** [comment]
Weird, I didn't receive it either. Perhaps something is wrong with @madmaxoft's server. We'll have to wait until he comes online.

**Comment by madmaxoft** [comment]
No idea, I didn't get an email either. How large was it? I think the server rejects emails larger than 50 MB.

**Comment by Gamerboy59** [comment]
Ok, I did just send another one.

**Comment by SphinxC0re** [comment]
Nothing on my side

**Comment by NiLSPACE** [comment]
I just send a test message. It looks like it's broken :/

**Comment by Gamerboy59** [comment]
Did it help?

**Comment by NiLSPACE** [comment]
I'm not able to do things with this (just because I don't understand what it all means :P) @madmaxoft probably knows what's up :)

**Comment by Gamerboy59** [comment]
If it's finally fixed the issue can be closed. (but I don't know if it's fixed, couldn't test yet.)
