### ISSUE TITLE
lua51.dll missing

### ISSUE THREAD

**Issue by Cannash** [cuberite/cuberite#2468]
I downloaded the precompiled Windows 64-bit Cuberite server files, but when I extracted the contents of the zip and ran the Cuberite.exe, a window entitled "System Error" pops up. It says "The program can't start because lua51.dll is missing from your computer. Try reinstalling the program to fix this problem." I tried re-downloading the files, but that didn't fix anything. I have Windows 10 64-bit. I also tried the 32-bit server files, but the same error occurred.

**Comment by NiLSPACE** [comment]
Looks like something didn't go as planned in #2437

**Comment by Cannash** [comment]
I fixed it. I downloaded the lua binaries here: http://skylineservers.dl.sourceforge.net/project/luabinaries/5.1.4/Executables/lua5_1_4_Win64_bin.zip and put them in my Cuberite folder, and now it works.

**Comment by worktycho** [comment]
That should not be needed.

**Comment by madmaxoft** [comment]
Yeah, the Lua output folder hasn't been fixed
