### ISSUE TITLE
Forums Do not work, Cannot get any access.

### ISSUE THREAD

**Issue by aberts10** [cuberite/cuberite#2475]
I tried creating a account in the forums so i could start plugin development, and join the community, but the email verification system does not seem to be working, its not sending a email, and im coming here as a last resort, because this is a major 'issue'.

**Comment by NiLSPACE** [comment]
Okay, I've tried it as well and didn't get an email as well.

I've send a message to @FakeTruth. He's the one hosting the forum. Maybe he knows how to fix it.

**Comment by aberts10** [comment]
Thank you a lot!, You may want to make some sort of thread that talks about the issue, and gives a contact information to get ahold of the Administrators

**Comment by SphinxC0re** [comment]
Did FakeTruth successfully update the Forum?

**Comment by NiLSPACE** [comment]
@SphinxC0re Yes, we're now on MyBB version 1.8.6.

@aberts10 instead I think we should have one email that all the admins / moderators / developers know the password off. Something like cuberite@gmail.com or even better support@cuberite.org

**Comment by madmaxoft** [comment]
support [at) cuberite {dot] org has been established, redirects to FakeTruth, NiLSPACE and me.

**Comment by SphinxC0re** [comment]
Could you add me? @madmaxoft

**Comment by madmaxoft** [comment]
Added

**Comment by NiLSPACE** [comment]
I received your test message :)

Now I think we need to put it on the home page. Perhaps @bearbin also wants to receive emails?

**Comment by aberts10** [comment]
I would love to help with this server software, but im not that advanced with C++, or ASM...  the only thing id be good at is converting plugins from bukkit to this, which i am trying to contact MrCookieSlime to ask for permmision to use the name of his plugin for a Ported (mabye a bit less complex) version.

**Comment by SphinxC0re** [comment]
I didn't receive a test message. :disappointed:

**Comment by madmaxoft** [comment]
The message was sent before you were added, and I didn't want to spam with more messages. You'll just have to trust me :)

**Comment by SphinxC0re** [comment]
:cry: Okay

**Comment by bearbin** [comment]
@madmaxoft Could I be added to the support email?

**Comment by madmaxoft** [comment]
Added.
