### ISSUE TITLE
ppc problems

### ISSUE THREAD

**Issue by cyboerg42** [cuberite/cuberite#2476]
I've got some problems with cuberite on ppc (powerpc)... 

It compiled like a charm, and i can connect to the server. But it's very strange. - When i'm connected, there is no map, my cords are 0, -21400000......, 152.......... and when i'm tp myself to 0,70,0 there is also nothing. (The map file is ok (try'd on Windows), and it is loaded.) (and if i move myself the strange cords are comming again)

(( I will compile the dev version now. (those strange bugs came with the testing branch) ))

**Comment by madmaxoft** [comment]
This almost looks like a byte-order issue. It would certainly be interesting to see the dev version, if there are any relevant log messages.

You could start the server with a `--log-comm` parameter, this will produce communication logs, have a look at them if the coords there are reasonable.

**Comment by cyborg00222** [comment]
In the newest dev version those strange cords are not comming again. - But the time is very buggy :(

Also - cuberite can not connect to the MC session servers.

CommLogs : http://1drv.ms/1Lxc4NY

**Comment by tigerw** [comment]
Workaround in #5178.
