### ISSUE TITLE
Crash on server shutdown

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2481]
A player failed to connect, but the server thinks the player is already connected (in the player list).
I restart the server so the player can try again, then this happens.

[code]
[00:24:28] Shutting down server...
[00:24:29] Player DanderDark has left the game
[00:24:35] Unloading worlds...
[00:24:37]   D:    | MCServer has encountered an error and needs to close
[00:24:37] Details | SIGSEGV: Segmentation fault
[00:24:37] MCServer Jenkins gcc armhf Release (master) build id: #142
[00:24:37] from commit id: 76d2f85b9abe29deb9500ce45607bb53337a4c26 built at: Tue  8 Sep 09:13:20 CEST 2015
./Cuberite(_Z15PrintStackTracev+0x14)[0x1eb768]
./Cuberite(_Z14NonCtrlHandleri+0xd0)[0x1d90e8]
/lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0x0)[0x76cadb20]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
./Cuberite(_ZN6cChunkC1EiiP9cChunkMapP6cWorldPS_S4_S4_S4_R15cAllocationPoolIN10cChunkData13sChunkSectionEE+0xa4)[0x138584]
[00:24:37]   D:    | MCServer has encountered an error and needs to close
[00:24:37] Details | SIGABRT: Server self-terminated due to an internal fault
[00:24:37] MCServer Jenkins gcc armhf Release (master) build id: #142
[00:24:37] from commit id: 76d2f85b9abe29deb9500ce45607bb53337a4c26 built at: Tue  8 Sep 09:13:20 CEST 2015
./Cuberite(_Z15PrintStackTracev+0x14)[0x1eb768]
./Cuberite(_Z14NonCtrlHandleri+0xd0)[0x1d90e8]
/lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0x0)[0x76cadb20]
/lib/arm-linux-gnueabihf/libc.so.6(gsignal+0x40)[0x76cac8dc]
./start.sh: line 1: 13563 Aborted                 ./Cuberite
[/code]

**Comment by worktycho** [comment]
The server encountered an allocation failure on exit by the looks of it. cAllocationPool will recuse as long as the allocation fails. Looks like we finally need to add some logic to handle running out of memory.

**Comment by LogicParrot** [comment]
Servers shouldn't normally run out of memory after #3151.

**Comment by LogicParrot** [comment]
@madmaxoft I wonder if #3439 fixes this.

**Comment by tigerw** [comment]
Tentatively closing, the allocation pool is no more.
