### ISSUE TITLE
Digging up gravel gives you gravel OR flint, instead of both

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2483]
Since the drop rate for flint was corrected, I've dug around a bit and noticed that, probably for a long time, when you actually dig up gravel and you get a flint, you do not get the gravel also.

I had a 40 block long gravel path. Dug it up. Got 4 flints and 36 gravel.

**Comment by nichwall** [comment]
According to http://minecraft.gamepedia.com/Gravel, you should only get one drop, not both gravel and flint.

**Comment by jammet** [comment]
My apologies.... guess even after years and years of handling it, clearly I'm mistaken here. 
You're correct.

**Comment by nichwall** [comment]
It's all good. But it would make an interesting config file so you can get more flint for less searching.
