### ISSUE TITLE
Enhance Fishing Mechanics

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#249]
Changes to fishing mechanics
Items other than fish can be obtained by fishing.
Fish: 4 items total, including Raw Fish, Raw Salmon, Clownfish, and Pufferfish.
Treasure: 7 items total, including enchanted fishing rods, enchanted bow, enchanted books, name tags, tripwire hook, lilypads, and saddles.
Junk: 11 items total, including damaged fishing rods, water bottles, rotten flesh, string, leather, bowls, sticks, boots or damaged boots.
New enchantments for Fishing Rods that can change your luck when fishing.
Lure - reduces wait time to catch an item.
Luck of the Sea - increases chance of getting treasure and decreases chance of getting junk.

**Comment by Bond-009** [comment]
This can be closed now.

**Comment by bearbin** [comment]
Was the lure enchantment implemented?

**Comment by Bond-009** [comment]
Yes, https://github.com/cuberite/cuberite/blob/master/src/Items/ItemFishingRod.h#L240
