### ISSUE TITLE
Console says "Unknown build ID"

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2493]
```
[91d62f7b38e7d08c|13:56:35] --- Started Log ---
[91d62f7b38e7d08c|13:56:35] MCServer local build bui[91d62f7b38e7d08c|13:56:35] --- Started Log ---
[91d62f7b38e7d08c|13:56:35] MCServer local build build id: Unknown
[91d62f7b38e7d08c|13:56:35] from commit id: approx: Unknown built at: approx: Unld id: Unknown
[91d62f7b38e7d08c|13:56:35] from commit id: approx: Unknown built at: approx: Unknown
...
```

Why would that happen? I've built from source using cmake. Used Debug mode. 
Also, what is `91d62f7b38e7d08c`?

**Comment by madmaxoft** [comment]
That should be the build identification. It lists the last commit SHA1 checksum it can account for (when CMake was last run). For some reason it looks corrupt in your log.

The build id is only valid when coming from the official buildservers (then it's something like `Jenkins Win64 #128`; home builds always have an "`Unknown`")

**Comment by SafwatHalaby** [comment]
I think it's always corrupt, and cannot be traced back to a commit.

**Comment by madmaxoft** [comment]
It works correctly for me:
```
MCServer local build build id: Unknown
from commit id: approx: b6e28ad422321d9383001b429a415f625c81cf41 built at: approx: 2015-09-25 09:58:21 +0200
```

**Comment by worktycho** [comment]
In you log it looks like the server is running cRoot::Start twice in parallel, no idea why though.

As for the commit id, are you running the builds inside or outside the git repo? commit detection only works when doing builds inside the repo.

**Comment by SafwatHalaby** [comment]
The executables are inside the repo. The cmake build folder is outside the repo though, I'm not if that's related. (`cmake ../cuberite/ -DCMAKE_BUILD_TYPE=Debug`)

**Comment by worktycho** [comment]
That's what I meant. The way we fetch the commit ID is by running git rev-parse HEAD in the build directory. That doesn't work unless the build directory is a descendant of the repo. It might be worth changing that though.

**Comment by SafwatHalaby** [comment]
When it comes to commits, would git automatically ignore that directory?

**Comment by SafwatHalaby** [comment]
putting the cmake folder inside fixed this.

**Comment by madmaxoft** [comment]
Reopening. We should be able to fix the cmake command to work in any folder.
