### ISSUE TITLE
Feature request: improve weather

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2499]
Hilarious as the request may sound.

It is raining too much in Cuberite servers. So much that players all noticed it independently of each other. So people beg me to toggle to clear skies in the console. Statistics say it's exactly at 50/50 rain/sun. No I do not know if this is in line with vanilla or not. But it would be nice to either have some weather control that goes beyond rain being permanently off or on, or somehow change the behavior to more closely resemble that of the vanilla Mojang servers.

**Comment by SafwatHalaby** [comment]
[Forum reference.](http://forum.mc-server.org/showthread.php?tid=2137)
