### ISSUE TITLE
Add new types of fish.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#250]
Pufferfish
Restores Half Hunger
If eaten, you will be given Poison IV for 1 minute, Hunger III and Nausea II for 15 seconds.
Used to brew a water breathing potion
Salmon
Can be cooked and eaten
Uncooked: Restores Hunger
Cooked: Restores 3 x Hunger
Clownfish
Usage still unknown besides being eaten and used to tame Ocelots
Restores Half Hunger

Ties in with #249

**Comment by Alcamech** [comment]
Is this still an issue? I noticed that the following fish mentioned are already added along with the effects of eating them.

**Comment by Codetector1374** [comment]
I guess we should close this as the PR above fixed this?
