### ISSUE TITLE
Default direction of block entities like chest should be changed

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2506]
Hey,

The default direction of this blocks: ladder, furnace, chest and trapped chest should be 2 instead of 0.
[Allowed values](http://minecraft.gamepedia.com/Data_values#Ladders.2C_Furnaces.2C_Chests.2C_Trapped_Chests) are 2, 3, 4, and 5.
I had a problem with setting chests, because I had the meta value 0 and then the block was always invisible.
In bukkit other values then them above are not allowed. WorldEdit (java one) defaults to 2, if a invalid value is used. Bukkit defaults to 5, don't know why, but I think 2 is better.

**Comment by madmaxoft** [comment]
This should most likely go into the WorldEdit issue tracker, since it's primarily a WorldEdit issue, not the core server's

**Comment by Seadragon91** [comment]
Whats about `cWorld:SetBlock`? I used this method for creating chests and I had added the meta value 0 and this is a invalid one. I think this should be changed, because this would confuse developers, if they don't see the block entities. I had this problem and completely forgot the meta value. With plugins written in java for bukkit, I had never the problem of invisible block entities.

**Comment by madmaxoft** [comment]
My opinion is that the `SetBlock()` function should only ever touch the block's type. Mostly for performance reasons - if you know that the meta is correct, no need to (re)set it. If you don't know - then use the `SetBlockTypeMeta()` function.

True that this would be great to mention in the documentation for those functions.
