### ISSUE TITLE
Debug mode - Assertion error

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2510]
Hey,

I if generate a air world in debug mode, the server will crash at startup on this [line](https://github.com/cuberite/cuberite/blob/master/src/Chunk.cpp#L2612).

In [World.cpp](https://github.com/cuberite/cuberite/blob/master/src/World.cpp#L649) we decrease y by one and then we have `y = -1` and that's why the server crashes at line above.

Removing the assertion line, fixes this crash at startup.

Not sure if there will be other assertions that could occur in a air world with a server running in debug mode.

regards,
Seadragon91

**Comment by worktycho** [comment]
Also should we add starting with an air world as a CI test case to prevent this from reoccurring?
