### ISSUE TITLE
Falling through ground after activating Spectator mode

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#2520]
When switching from Creative mode to Spectator mode, the player falls through the ground into the void instead of flying. This doesn't occur when switching from Survival mode to Spectator mode.

**Comment by jammet** [comment]
Yes, it has been like that for a long time. I used to be able to fix this by typing /fly *very* quickly, but I came here today to report that /fly is broken.

**Comment by mathias-github** [comment]
The /fly command was moved from Core to the "Essentials" plugin some time ago, as the command doesn't exist in Vanilla Minecraft.

**Comment by jammet** [comment]
Thank you, I didn't know that. In the meantime I have had help to put fly back into my server. Still, hope the spectator mode is getting some love soon. It has other issues (like the teleport functions with the number keys cause a disconnect, and the option to see "through the eyes" of another player is missing, and last time I checked, people can still see you somehow in spectator mode).

**Comment by madmaxoft** [comment]
This should be fixed now by PR #2528. Can you verify please?

**Comment by jammet** [comment]
I'll check later when there's a build with this fix ready. :)

**Comment by jammet** [comment]
I would really like to give this a go, but there hasn't been a new build at builds.cuberite.org for RPi with this fix included yet, as far as I can tell. Am I mistaken, or what is the build process waiting for?

**Comment by jammet** [comment]
I probably just got it wrong. At least - using that build - I don't fall through the ground anymore. Looks good now. :)

**Comment by expandi-craftDev** [comment]
this bug just happened when i was testing my mod
