### ISSUE TITLE
[Generator].PregenerateDistance set to zero deadlocks server on startup

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#2521]
When the world.ini file specifies `[Generator].PregenerateDistance = 0`, the server deadlocks on startup, while waiting for the spawn loader to finish loading chunks.

Ref.: #1656

**Comment by NiLSPACE** [comment]
Would a simple 
```cpp
if (MaxIdx == 0)
{
   return;
}
```
[here](https://github.com/cuberite/cuberite/blob/0786fda18b08ee26a9bdcda7b17ef9979be4585a/src/SpawnPrepare.cpp#L56) fix it

**Comment by bearbin** [comment]
The bit of code you linked does go into an infinite loop when MaxIdx is 0, but that's not a deadlock, so IDK.

**Comment by SphinxC0re** [comment]
Woohoooo!!! Things are getting worked on :laughing:
