### ISSUE TITLE
/fly command is broken

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2524]
Suddenly Cuberite states "Unknown command" whenever /fly is attempted. I use that command to fly in spectator mode, because when entering it, you usually fall through the world and die. Also, /fly used to work in standard survival mode when you are admin. Was a pretty useful thing.

**Comment by NiLSPACE** [comment]
Isn't this a bug in Core or Essentials?

**Comment by SphinxC0re** [comment]
I think it's core but it might be already moved

**Comment by NiLSPACE** [comment]
Yeah, I believe it's already moved to Essentials.

**Comment by SphinxC0re** [comment]
That's a problem. The documentation for ```/fly``` is still included in the core docs

**Comment by jammet** [comment]
Does this mean I must use Essentials - the plugin, to get fly back? There is so much other stuff in there that I do not need, and would prefer not to have in use on the server.

**Comment by NiLSPACE** [comment]
Unfortunately that's exactly what it means, sorry ;) It's easy to fix though. Just copy [this](https://github.com/mc-server/Essentials/blob/master/cheat.lua#L151-L172) function somewhere in Core, and put the [fly command info](https://github.com/mc-server/Essentials/blob/master/Info.lua#L113-L119) in the Core's Info.lua (you might want to change the permission as well). It's an ugly solution for you, but it works ;) Keep in mind that every time you update Core you'll have to do this. Another option is to create a completely new plugin that implements fly command.

**Comment by NiLSPACE** [comment]
Closing since this issue isn't a problem from Cuberite.

**Comment by jammet** [comment]
:) Thanks for the help, and for clearing that up!!

**Comment by NiLSPACE** [comment]
Anytime ^^
