### ISSUE TITLE
Find a better path recalc algorithm

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2536]
@tigerw thinks the current recalc algorithm is needlessly complex. This is probably true.

I should find a simpler algorithm, but that simplicitly shouldn't come at the cost of performance/flexibility (so no 1-block-recalc).

References:
[Tiger's PR discussion](https://github.com/cuberite/cuberite/pull/2446)

[Recalc PR diff discussion](https://github.com/cuberite/cuberite/pull/2523#discussion-diff-41150490)

**Comment by SafwatHalaby** [comment]
Here's what I have in mind right now:

```
/** Coordinates for the ultimate, final destination. */
Vector3d m_FinalDestination;

/** Coordinates for the destination last given to cPath. */
Vector3d m_PathDestination;

// m_Path.distanceLeft() Returns how long the remaining path is.
// SOME_INT is a small constant, e.g. 3.


ePathFinderStatus cPathFinder::GetNextWayPoint(...)
{
    double acceptableDeviation = m_Path.distanceLeft() / SOME_INT;
    if ( (m_FinalDestination - m_PathDestination).Length() > acceptableDeviation)
    {
        // Recalc
    }
} 
```

**Comment by SafwatHalaby** [comment]
Tiger proposed something similar, except that instead of `.. > acceptableDeviation` we'd have `...> SOME_CONST`.

**Comment by SafwatHalaby** [comment]
Tiger proposed something similar, except that instead of `.. > acceptableDeviation` we'd have `...> SOME_CONST`.

I believe this is better because far away mobs need a bigger SOME_CONST while nearby ones need a smaller one.

**Comment by SafwatHalaby** [comment]
`acceptableDeviation` can be a non-linear function if needed.

**Comment by SafwatHalaby** [comment]
@tigerw , opinion?

**Comment by tigerw** [comment]
I think I've mentioned this already, but here's my thought on it:

If AcceptableDeviation is a function of distance, I think that for large values (and therefore low recalculation and large distances), you'll certainly get terrain in which even a destination change of one block will mean a completely different path, and so the mobile may realise very late that it needs to go back.

For a constant value, which was my proposal, you'll have potentially low performance but the entity is already on the right path.

**Comment by worktycho** [comment]
How about we take into account the position of the first n waypoints the last time we recalculated? If they are the same, then recalculate less frequently.

**Comment by SafwatHalaby** [comment]
What I tried to say earlier is that this problem is manifested in both methods in different forms. For a constant value, a player will be able to easily "pin" the mob by moving back and fourth between the two blocks which completely alter the path. This would make the mob dance back and fourth between two paths. For a non-constant value, depending on the terrain, the mob may escape the "pin zone" much more easily, which is an advantage (again, depending on the terrain).

Both forms aren't desired but aren't too serious to be worth worrying about imho.

**Comment by SafwatHalaby** [comment]
Here's a demonstration in which a non-const value is an advantage. Consider this terrain:
```
XXXXXZXXXXXX
X                      X
XXXXP  XXXXXX
       XXXXX
```
Z - A zombie.
P - A player.

There's an air block next to the player. Let the player jump back and fourth between the two blocks surrounding the air block.

If it's a low const, the zombie will get confused and keep moving left and right.

If we use the `acceptableDeviation` function, the zombie would pick a direction (say, left) and move left for a while, unaffected by the player jumps. Once the zombie decides to recalc, it already escaped the pinning zone and simply keeps moving towards the player.

In this specific case, `acceptableDeviation` behaves better than a const. It's the other way around in other cases.

**Comment by SafwatHalaby** [comment]
The ascii art was garbled, I'll post an image.

**Comment by worktycho** [comment]
I think acceptable deviation is the better strategy. If your in a situation where pinning is possible, the difference between the two paths is so small that taking the non-optimal path is not much of a problem. So we should try and get out of the pinning as soon as possible.

**Comment by SafwatHalaby** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5030488/10411096/a223e90a-6f63-11e5-9fce-e0d84b301eb8.png)

Purple - Rough pinning region
Green - Player
Red - Zombie

**Comment by SafwatHalaby** [comment]
>the difference between the two paths is so small that taking the non-optimal path is not much of a problem. 

When jumping is involved, there are cases where taking the non-optimal path is actually problem. A const recalc behaves better in such a case (I can show a diagram). However, I'm sure the cases where `acceptableDeviation` behaves better are a lot more common, because no jumping is involved.

**Comment by tigerw** [comment]
In that case, we shall consider realism. If I were a monster, I wouldn't know or follow the perfect path to a player; I'd instead get close, and if I realise he's unreachable, I'd go back bearing their taunting. Then I'd find a better path and pay them back in full for their slights.

So, I would say to just go with the variable deviation way.

**Comment by SafwatHalaby** [comment]
Do we have a consensus then? Can I start working on it?

> I'd go back bearing their taunting. Then I'd find a better path and pay them back in full for their slights.

That's one epic way to puit it.

**Comment by tigerw** [comment]
Yes consensus.

**Comment by SafwatHalaby** [comment]
The acceptable deviation (in the PR above) works surprisingly well, It recalcs less than before, and the mobs are *more* responsive to player movement than before.
