### ISSUE TITLE
Server crash in the PathFinder

### ISSUE THREAD

**Issue by LO1ZB** [cuberite/cuberite#2539]
The PathFinder trys to get a block that is out of boundarys of m_Map.
Stack Trace:
http://pastebin.com/rB3T0jNL
World:
https://www.dropbox.com/sh/7upzmuqo4xkhakj/AAArZGAyy0xTQR2ygbjkPrexa?dl=0
edit: (faster mirror):
https://mega.nz/#!9pZzxIiZ!vcxiLu2kKXDgrh30u7MYFH2LUuNrcGH4POYo1YPfevI

**Comment by worktycho** [comment]
Can you post the version info that is output at startup? The stack trace doesn't make much sense in the current version.

**Comment by LO1ZB** [comment]
Here you go:
[2ff71a74352eadca|22:45:10] Cuberite local build build id: Unknown
[2ff71a74352eadca|22:45:10] from commit id: approx: 1a572e6611ac8faa447e585d8655230b23b29c4e built at: approx: 2015-10-09 10:38:23 +0100

**Comment by worktycho** [comment]
The line IsSolid is on in the stacktrace is `(BlockType == E_BLOCK_NETHER_BRICK_FENCE) ||`. I think its Path.cpp line 142 thats the problem.

**Comment by worktycho** [comment]
Looks like the pathfinder is being passed an invalid y value. I'll add an assert to fail this earlier.

**Comment by worktycho** [comment]
Actually it might be pathing out of the world. Are there any holes in the bedrock or towers touching the top level of the world?

**Comment by worktycho** [comment]
@SafwatHalaby How is the pathfinder supposed to handle a hole in the bedrock?

**Comment by LO1ZB** [comment]
I try to load the world in singleplayer and check there

**Comment by mathias-github** [comment]
There are both blocks touching the top level of the world and holes in the bedrock. Some bedrock has been replaced with stone.

**Comment by LO1ZB** [comment]
Yes, there are holes into the void.

**Comment by worktycho** [comment]
From the stacktrace, it looks like a mob has fallen out of the world, and is trying to path its way back. My PR should fix that.

**Comment by SafwatHalaby** [comment]
@worktycho, if it's a source or destination, it should abort. Your PR took care of that.
If it's a hole along the way, it shouldn't process that node and should continue pathing its way around it. It may still find a path. Hence my comment at the PR.

**Comment by Woazboat** [comment]
I can reproduce this crash in the latest version (commit id: 3c272b55ea1239238ad9726bba9f7dc8b130e545).

Steps for reproduction:
Build a nether portal and go into the nether.
Stop and wait for ~half a minute for the server to crash.

Originally happened to me on a slightly older build (~2 weeks) and a slightly used map, but I could reliably reproduce the crash on a clean build and two freshly generated maps.

Stack trace:
http://pastebin.com/ieM1JPWE

#3  0x00007ffff6ba4652 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000a49954 in cChunk::GetBlock (this=0x5213d90, a_RelX=6, **a_RelY=-2**, a_RelZ=2)
    at /home/<username>/qtworkspace/cuberite_temp/cuberite/src/Chunk.cpp:2605
#5  0x0000000000a499a4 in cChunk::GetBlockTypeMeta (this=0x5213d90, a_RelX=6, **a_RelY=-2**, 
    a_RelZ=2, a_BlockType=@0x7fffce7f7603: 0 '\000', 
    a_BlockMeta=@0x7fffce7f7602: 0 '\000')
    at /home/<username>/qtworkspace/cuberite_temp/cuberite/src/Chunk.cpp:2618
#6  0x0000000000dda446 in cPathFinder::EnsureProperPoint (this=0x7fffc2b29fd8, 
    a_Vector=..., a_Chunk=...)

Server log file:
http://pastebin.com/pBGRJHBs

Coredump, executable and worlds:
https://dl.dropboxusercontent.com/u/16465859/crash_outofbounds.zip
