### ISSUE TITLE
Map nether coordinates to overworld coordinates and reverse when using portals

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2541]
> Locations in the Nether correlate to Overworld coordinates, but horizontal Overworld distances are scaled down by a ratio of 8:1 for travel in the Nether. Therefore, traveling one block in the Nether means traveling eight blocks in the Overworld.

– from http://minecraft.gamepedia.com/The_Nether

So the teleport function should take the type of world the player is currently in plus his position. Then the position gets mapped onto the destination world. After this procedure, the player gets teleported

**Comment by SafwatHalaby** [comment]
This is slightly more complicated when it comes to nether portals though, if there's a portal some distance away, the teleport should go there instead of going to the coords. Or something like that, there's a detailed description in the wiki.

**Comment by SphinxC0re** [comment]
I'm sorry, this is what I meant. Teleporting with the command should differ from teleporting with a portal

**Comment by SphinxC0re** [comment]
I believe, I've been a little fast with closing this. Actually I think that every *dimension* or every world template should have to define a traveling ratio relative to the *overworld*.

**Comment by madmaxoft** [comment]
Not sure if that is enough. What if you build a Nether portal in the End (and have those worlds properly linked through world.ini)? What should the ratio be?

Perhaps we should specify the coord ratio together with the world linkage in world.ini:
```ini
; In world/world.ini:
[LinkedWorlds]
NetherWorldName=world_nether
NetherWorldCoordRatio=0.0825

; in world_nether/world.ini:
[LinkedWorlds]
OverWorldName=world
OverWorldCoordRatio=16
```

This way we could even have asymetric ratios - 1:16 when entering the nether, but 8:1 when leaving, for example.

**Comment by SphinxC0re** [comment]
If you built a nether portal in the end, you'd probably end up calculating the cords by virtually traveling to the overworld and then traveling to the nether.

**Comment by LogicParrot** [comment]
Is there a practical use of asymetric ratios?

**Comment by SphinxC0re** [comment]
Essentially, Vanilla does it this way, so we should adapt this behavior

**Comment by LogicParrot** [comment]
Aren't vanilla's ratio's symmetric? (1:8 and 8:1)

**Comment by SphinxC0re** [comment]
Yes, between nether and overworld. But what about the end?

**Comment by LogicParrot** [comment]
>This way we could even have asymetric ratios - 1:16 when entering the nether, but 8:1 when leaving, for example.

By assymetric, xoft meant that that entering the world would have a different ratio than leaving that same world. I asked if that has any use at all.

(e.g. nether > overworld, ratio is 8, but overworld > nether, ratio is 5)

**Comment by SphinxC0re** [comment]
Then it would be against Vanilla mechanics to have asymmetric ratios. We should try to adapt Vanilla behavior as good as possible.

**Comment by tigerw** [comment]
Entity portalling uses vanilla ratios.
