### ISSUE TITLE
Long username kicks the whole server

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#2545]
Whenever someone with a username longer than 16 characters joins the server (authentication off), all players online disconnect with the following message:
![screenshot from 2015-10-13 19 42 07](https://cloud.githubusercontent.com/assets/8754153/10461602/bb27e772-71e2-11e5-86cc-43a1cd4bb38b.png)

and sometimes this one:
![screenshot from 2015-10-13 19 39 42](https://cloud.githubusercontent.com/assets/8754153/10461647/f2a03ed4-71e2-11e5-8847-d4ecbd291cc2.png)

**Comment by NiLSPACE** [comment]
How are we planning on fixing this? Do we block the user completely, or don't send the complete username to other players.

**Comment by SphinxC0re** [comment]
I'd say slice the username after the 16th char

**Comment by mathias-github** [comment]
@SphinxC0re I agree with you.

**Comment by madmaxoft** [comment]
So it seems there are at least two places where the string length is a problem. Pity that we don't know exactly which packets those are.
