### ISSUE TITLE
Teleportation - Server sends wrong chunks

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2547]
Using portals in the nether to return you to the normal world is delayed. When stepping into a portal on the nether side, you are seemingly first transported to the coordinates of the "other portal in the real world" without switching to the real world just yet. Instead Cuberite starts sending you the chunks that would be in the actual Nether instead of the normal world. So you'll be where you would be in the normal world, but it wastes time and bandwith by loading nether chunks of that location instead.

Edit: I split this into 3 issues. - @LogicParrot

**Comment by SafwatHalaby** [comment]
I often get stuck in a teleport loop on my laptop. One portal leads to another, and before I get a chance to move, I'm teleported back to where I came from, and so on.

**Comment by LogicParrot** [comment]
>Also, you still fall when the chunk isn't loaded, yet, and suffocate in some blocks. I've started to hollow out areas beneath portals to try and accommodate but it only works half the time. Nilspace tested this with me some time ago, for a while it seemed to work better, but I guess that was by chance.

Opened this in a a seperate issue: #2964

**Comment by LogicParrot** [comment]
>Then, once you have arrived in the normal world, the game will act as if you had been standing in the nether gate of that side for some time (loading time), and quite often, you are transported back before you even see the normal world. This can create an infinite loop. 

Opened this in a seperate issue: #2963

**Comment by jammet** [comment]
Thank you for re-organising those. :)

**Comment by LogicParrot** [comment]
You're welcome :) 
I'll be working on #2963 and #2964 soon.

**Comment by LogicParrot** [comment]
@jammet By editing this post you've removed the one issue I left here. (It had to do with server sending chunks of the wrong world).

**Comment by LogicParrot** [comment]
Edit: My bad, all good, nothing is wrong with the issue :)

**Comment by LogicParrot** [comment]
It appears that #3109 makes this more common. I believe this issue only occurs (or occurs more often) if the source and destination coords are not identical. This could indicate some stale values in cClientHandler's `m_sentChunks`. Just a wild guess.

**Comment by LogicParrot** [comment]
Might be somewhat related to #3182 , to `cChunkSender`, specifically.
