### ISSUE TITLE
Using /spawn in the Nether returns to you a flat nether.

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2548]
When using /spawn in the nether to leave it, you are not transported to the normal world. Instead of that, I end up in a place of endless bedrock in a world that looks like the nether, or at least has those colors.

**Comment by madmaxoft** [comment]
That would be the Nether's bedrock roof. The spawn coordinates generated at server first startup are wrong for Nether worlds, they always point to the highest non-air non-water non-lava block, which in the Nether is always the rooftop. We need to fix the algorithm to take Nether worlds into account. However, this won't fix existing worlds, they will need manual fixing. Go to the Nether world's world.ini and change the spawn coordinates manually (you'll notice that the Y coord is >127, you want below 125).

**Comment by jammet** [comment]
Ah, I see, I have adjusted the height. Thanks for the help :).
