### ISSUE TITLE
Disable deadlock detector by default.

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#2550]
It is now far more common for a detected deadlock to be caused by a long computation on the tick thread causing lag, then it is from an actual deadlock. We should disable the detector by default as the server can recover in these situations, if it is given long enough to finish its computation.

**Comment by madmaxoft** [comment]
I think we should keep it enabled, but enlarge the default timeout to, say, 5 minutes. If a tick thread takes 5 minutes to process a tick, it's something we want to know about as well.

worktycho <notifications@github.com> wrote:

>It is now far more common for a detected deadlock to be caused by a
>long computation on the tick thread causing lag, then it is from an
>actual deadlock. We should disable the detector by default as the
>server can recover in these situations, if it is given long enough to
>finish its computation.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cuberite/cuberite/issues/2550

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by jammet** [comment]
I've set it to 60 seconds a long long time ago, and I am glad the mechanism is still there, because deadlocks still happen. :)

**Comment by samoatesgames** [comment]
Is not also worth disabling deadlock detection in debug builds? as I tend to disable it when debugging anyway (though that might just be me).

**Comment by jammet** [comment]
Why do you disable the deadlock?

**Comment by worktycho** [comment]
Because the deadlock detector confuses crash reports when the problem is not a deadlock, just lag.

**Comment by Seadragon91** [comment]
I would suggest changing it to 60s or a few minutes, but not disabling it.

**Comment by SphinxC0re** [comment]
let's say two minutes

**Comment by jammet** [comment]
Will do.

**Comment by LogicParrot** [comment]
This was closed in th
