### ISSUE TITLE
Let the server bundle and minify plugins on startup

### ISSUE THREAD

**Issue by SphinxC0re** [cuberite/cuberite#2557]
it would be good, if the server would do some per-optimization on the plugins. The resulting file structure would be:
```
Plugins
   | - <Pluginname>
            | - src
            | - bin
   | - <Pluginname>
 ...
```
The server would start much faster e.g. with a bundled and optimized core plugin

**Comment by NiLSPACE** [comment]
It's possible that things won't work as expected when doing that though. Also, considering how fast plugins currently load it isn't really needed is it?

**Comment by madmaxoft** [comment]
I don't think this is possible, let alone necessary.
What kind of "per-optimization" [sic] do you have in mind? Compiling into bytecode?

For me, currently, the plugin load time (0.5 sec) is a fraction of the server startup time spent in loading the world (5 sec).

**Comment by SphinxC0re** [comment]
I thought about bundling and minifying the source code
```bash
for f in *.lua do
cat f >> bundle.lua
done

luamin -f bundle.lua > min_bundle.lua
mv min_bundle.lua > bundle.lua
```
As a shell script for example. Where luamin is a lua minifier

**Comment by madmaxoft** [comment]
According to this site:
http://luasrcdiet.luaforge.net/
monification results in about 18 % faster load. Which means we could shave 0.09 sec off the startup / reload time. Not worth it.
