### ISSUE TITLE
Why is cChunk not using multidimensional arrays?

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#2558]
Since everything's static, it seems reasonable that block, light, and metadata arrays are addressed more intuitively as [X][Y][Z] with the flat packing to a 1D array performed by the compiler.

**Comment by madmaxoft** [comment]
Because we want to use the same packing as the file and network format for performance reasons; that would only be achieved by using the non-intuitive `[Y][Z][X]`

**Comment by tigerw** [comment]
Alright, then address the 3D array as [Y][Z][X]. My point is why is the current format a 1D array?

**Comment by madmaxoft** [comment]
Because we want to have the potential ability to change the internal storage format (happened once, between 1.1 and 1.2 afaik) without having to rewrite a ton of code. That's what `cChunkDef::GetBlock` and `cChunkDef::GetNibble` et al are for.

**Comment by madmaxoft** [comment]
Additionally, it makes the chunk sparsing possible by inserting an abstraction layer between the storage and the manipulation.

**Comment by tigerw** [comment]
I don't see why you couldn't reproduce whatever abstraction you want with a multidimensional array.

**Comment by madmaxoft** [comment]
Good luck implementing chunk sparsing on a multidimensional array.

**Comment by tigerw** [comment]
Ah, I think I understand what you just said: @worktycho's chunk sparsing with segments is like cChunkLayer, essentially another implementation of a bucket map.

If only you'd let me replace both with an unordered_map; memory usage and readbility would be excellent even if performance would take a hit :P
