### ISSUE TITLE
Wiki write access

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#2570]
Hi, 
i Plan to rewrite / extend the wiki. may I have write access to the wiki?
thanks
- not sure if I'm right here, or if it's possible

**Comment by bearbin** [comment]
I don't know if anybody here has direct access to the wiki, but I can suggest that the users-manual project is here on GitHub and you can submit a PR there.

https://github.com/cuberite/users-manual

**Comment by bearbin** [comment]
Sorry, I misunderstood your question. 

I think you should be able to fork the github wiki, but I'm not entirely sure. I'll wait for some more opinions.

**Comment by Schwertspize** [comment]
I made my opinion clear in our forum. I would prefer using a github wiki because markdown is easier than html and we don't have to host and maintain it.

**Comment by williamhatcher** [comment]
We have obviously decided to host our own documentation. Let's close this issue
