### ISSUE TITLE
creeper displaying only white

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#2572]
if creeper stops explosions if he is in white phase, he stays  white.

**Comment by Schwertspize** [comment]
https://github.com/cuberite/cuberite/pull/2628

I think it's now fixed

**Comment by SphinxC0re** [comment]
Did you actually test this?

**Comment by Schwertspize** [comment]
no, but I thought the PR was tested and it's basically the same bug.

**Comment by Seadragon91** [comment]
Can confirm that this has been fixed.
