### ISSUE TITLE
Torches placed on mob spawner not removed, if spawner destroyed

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2573]
If I place a torch on a mob spawner and destroy the mob spawner the torch not falls down.

**Comment by Gargaj** [comment]
This is because technically they're not placed either; the spawner is a "usable" block, so when anyone rightclicks on it, the code goes into this branch: https://github.com/cuberite/cuberite/blob/master/src/ClientHandle.cpp#L1385 - and never reaches ```OnPlayerPlace```.
