### ISSUE TITLE
Chests duplicate when destroyed

### ISSUE THREAD

**Issue by fennesz** [cuberite/cuberite#2579]
Chests duplicate when destroyed, and when placed they are still in the inventory.

**Comment by SphinxC0re** [comment]
Can someone else test this?

**Comment by fennesz** [comment]
More info: I am running MCServer on a Raspberry Pi 2, where I did the compilation myself.

**Comment by Seadragon91** [comment]
Can not reproduce this.

We had a issue, where some blocks like chests weren't removed from inventory when placed.. Are you sure you have the latest changes from master branch?

**Comment by fennesz** [comment]
I ran this command:

bash -c "$(wget -O - https://raw.githubusercontent.com/cuberite/cuberite/master/compile.sh)"

**Comment by Seadragon91** [comment]
Could you test a build from the build?
http://builds.cuberite.org/job/Cuberite%20Linux%20raspi-armhf%20Master/

**Comment by fennesz** [comment]
I will later today.

**Comment by SphinxC0re** [comment]
@fennesz could you describe how you reproduce this behavior?

**Comment by Seadragon91** [comment]
I guess you have selected branch testing, in the selecting branch choice. The testing branch is 5 months old and doesn't include the fix,

**Comment by SphinxC0re** [comment]
The *testing* branch is kinda old. That's mostly because we haven't yet migrated to the new testing cycle. Use *master* instead
