### ISSUE TITLE
Walking down long sets of stairs is seen as falling.

### ISSUE THREAD

**Issue by source83** [cuberite/cuberite#2582]
When walking down a long stairs downward, the server sees this as the player falling.
So if you walk or run down a long enough set of stairs, the player is killed.

**Comment by fennesz** [comment]
Confirmed on the raspberry pi armhf build. Taking fall damage walking down stairs.

**Comment by SphinxC0re** [comment]
Nice catch! Thanks for the report.

**Comment by source83** [comment]
No Problem :D

**Comment by Gargaj** [comment]
One possible solution:
https://github.com/cuberite/cuberite/blob/master/src/Entities/Player.cpp#L480
Extend this bit with slabs AND stairs.

**Comment by source83** [comment]
In the code or the world itself ?

**Comment by Gargaj** [comment]
In the code, obviously.

**Comment by madmaxoft** [comment]
Does this mean that, currently, falling on a stairs block will not actually deal fall damage? Or am I reading it wrong?

**Comment by Schwertspize** [comment]
probably that too but the damage is dealed as soon as you level the set of stairs.  thus issue is more about a long set of stairs and you get fall damage as soon as you leave it.

**Comment by Gargaj** [comment]
Hahah, oh dear, that is confirmed.
Land on any halfblock (lower step of stairs, bed, cake, enchanting table, anything) from a great height and you take no damage - but as soon as you step off from it, SMACK, you get the whole damage of the fall :D

**Comment by Seadragon91** [comment]
Can confirm that :)

**Comment by SphinxC0re** [comment]
You could make a lot of good maps with this *feature* :wink:

**Comment by Schwertspize** [comment]
yeah... maybe we should add a config with that bug/feature :D

**Comment by SphinxC0re** [comment]
:+1:

**Comment by SafwatHalaby** [comment]
#2638 resolves this.

**Comment by Schwertspize** [comment]
Already closed ^^

**Comment by SafwatHalaby** [comment]
My mistake.
