### ISSUE TITLE
Give a plugin its own virtual environment

### ISSUE THREAD

**Issue by SphinxC0re** [cuberite/cuberite#2592]
This should include it's own root folder and wanted dependencies for the plugin. We could add a ```env.lua``` file to define a plugins dependencies and environmental variables

**Comment by NiLSPACE** [comment]
Why would we do that? Plugins can already access everything they want. If this is about memory cost then it isn't worth it. A plugin barely uses any memory.

**Comment by SphinxC0re** [comment]
It's not about memory management. It's about dependency management

**Comment by worktycho** [comment]
What environment does a plugin have? Filesystems are inherently shared and so is the main server.

**Comment by SphinxC0re** [comment]
The plugin woul have it's own root folder in the plugin folder. The ```env.lua``` would help letting the user configure the plugin and for the dev to set environment variables

**Comment by madmaxoft** [comment]
I still don't get it. What's a root folder, in your scheme?

The plugins already have a folder that is the "main" for them - all the Lua files from that folder are loaded, the plugin can query the name of the folder etc.

As for dependencies, the plugin still needs to check them manually anyway. If you want to document them somewhere, try Info.lua - if you come up with a nicely organized structure there.

What are those environment variables you're talking about? The OS env variables are per-process, a plugin cannot virtualize them.

**Comment by SphinxC0re** [comment]
Regarding the root folder I was talking about reading and writing files. Are plugins currently executed in their own closure? I not, that's what I meant with virtual environment

**Comment by madmaxoft** [comment]
Each plugin has its own Lua state, isolated from other plugins. They cannot interfere with each other except by `cPluginManager:CallPlugin()`.

It's rather impossible to redirect files for individual plugins, because the OS, if it even has a concept of working folder, has it defined on a per-process basis.

**Comment by SphinxC0re** [comment]
Okay. It was just an idea :smile: closing
