### ISSUE TITLE
Can not see maps in itemframes

### ISSUE THREAD

**Issue by heroldini** [cuberite/cuberite#2596]
hi,
if you have maps in item frames, you cant see it, after a login

![bug](https://cloud.githubusercontent.com/assets/15631492/10909344/ccb40424-8238-11e5-925e-2639bde3a528.jpg)

pick it up and have a look at one of this maps,
only after that you can see it in the frames too!

maybe the server did not send it to clients?

hope my 1st ever issue is correct :)

**Comment by bearbin** [comment]
How odd. Thanks for reporting this issue, and the format is correct. Somebody should look into it soon.
