### ISSUE TITLE
Invisible mobs, need to relog to see some of them

### ISSUE THREAD

**Issue by source83** [cuberite/cuberite#2598]
This is on a imported map from spigot.

**Comment by LogicParrot** [comment]
I've split this issue. The part about weird spawning is now at #2988

Can you explain how and when did you experience invisible mobs?

**Comment by source83** [comment]
Sorry about the late update.
This is also present on maps created by Cuberite as well.
Now and then, there spawns a mob somewhere that I can't see, but does attack me and deals me damage.
Skeletons, zombies, spiders etc..
I do hear them, but I can't see them until I relog.
Often it's a spider or n that attack me, I move off a bit, quickly relog, and they are visible.
Hope this helps, tell me how to log what info you need and it'll be done :)

**Comment by LogicParrot** [comment]
Closing in favor of #3696
