### ISSUE TITLE
Make 'Survival' the default gamemode

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2600]
We can keep 'Creative' as gamemode for debugging

**Comment by bearbin** [comment]
I think this is a good idea, survival mode is what most people want.

**Comment by SphinxC0re** [comment]
And for debugging it would still be nice to just fly around

**Comment by SafwatHalaby** [comment]
Also, for better survival, perhaps guardians and endermen should be disabled by default until their code is customized.

**Comment by SafwatHalaby** [comment]
Last time I checked, mob spawning was horrible, they'd spawn right next to you. If this is sitll the case, survival may not be mature enough to be the default yet.

**Comment by SphinxC0re** [comment]
Seems to be a good idea

**Comment by madmaxoft** [comment]
I don't care what the default is, once it's set in the world.ini, it stays, so I have no problem with changing the default.

**Comment by SafwatHalaby** [comment]
I think survival is horrible as long as the spawning issue isn't fixed.

**Comment by Seadragon91** [comment]
Yes the spawning should be fixed. Something like in ChunkStay, spawn the player after the chunk has been loaded.

**Comment by SafwatHalaby** [comment]
I meant that mobs spawn too close to players.

**Comment by Seadragon91** [comment]
Yes this too. Have read your's wrong. I have sometimes the problem that I spawn in the ground...

**Comment by LogicParrot** [comment]
Mobs no longer spawn too close to players.

**Comment by LogicParrot** [comment]
For the record: Spawning in ground/falling to underworld had been fixed long ago in #3097

**Comment by yangm97** [comment]
This is starting to look like a “Good Survival” milestone 😆
