### ISSUE TITLE
Segfault / can't connect because "I am online right now" 

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#2608]
If I join and abort it instantly, I can either connect and can't abort, or I can abort and everything is fine. that's what I thought. if I try to connect another time, if showed me I'm already online (that's number two). I thought one time error, tried to kick me and then just closed the server for a moment. kick did not work.
1. experienced once as I was trying to reproduce the original bug. segfault (i have no core dump, sorry) 
2. this one is more difficult. I can't connect because someone with my username is already online (not me). I can't kick this zombie player, he does nothing, the only thing I can do is closing the server and restarting. 

reproducing: it's more or less easy, a high ping is good for reproduction because otherwise you can't have a chance of clicking the abort button. just connect to the server, hit the abort button and repeat that until segfault or webadmin/console says you are online (and you can't reconnect). then ask someone else to test how it reacts ingame.

core dump, command output.... https://qraut.alkaid.uberspace.de/report.tar.gz
output_\* is the output I piped through tee (to get everything, may be useful too)

**Comment by Schwertspize** [comment]
anyone can fix it?

**Comment by LogicParrot** [comment]
Probably related to https://github.com/cuberite/cuberite/issues/2644

**Comment by mathwhiz1212** [comment]
Occasionally I have issues with the server saying that I am online when I am not and there is a zombie player with my username. Only a server restart will get rid of the zombie player. Other players have not reported issues but have occasionally become invisible with no apparent reason. Haven't had any issues in the past few days. We are using https://github.com/cuberite/cuberite/commit/e0e3f396f2c6861242a1b076d07c73da55d40160 currently.
