### ISSUE TITLE
Double wooden slab duping

### ISSUE THREAD

**Issue by Gargaj** [cuberite/cuberite#2610]
Empty inventory and only two wooden slabs on the hotbar
1. Place first slab
2. Put the second slab on it to turn it into double slab
3. Force inventory re-send (e.g. open a chest)
-> voila, new slab appears in inventory.

Cause:
The actual item-removal when an item is being used is ```OnPlayerPlace``` (https://github.com/cuberite/cuberite/blob/master/src/Items/ItemSlab.h#L94), but when turning a slab to a double slab, ```a_Player.PlaceBlock``` is called which doesn't change the inventory, etc.

**Comment by madmaxoft** [comment]
Nice catch and nice analysis. Seems like you're more than capable of fixing this on your own :)

**Comment by Gargaj** [comment]
No, I looked at it and have no idea what the conventions or proper course of action are. This is best trusted on someone who knows the codebase.

**Comment by Gargaj** [comment]
Would I be correct to assume that
```
a_Player.GetInventory().RemoveOneEquippedItem();
```
would be the code to use?
