### ISSUE TITLE
Piston pushes unpushable blocks

### ISSUE THREAD

**Issue by bibo38** [cuberite/cuberite#2612]
I've stumbled upon [this](https://github.com/cuberite/cuberite/blob/6e4122e551eeb41d3e950b363dd837d5586fe560/src/Blocks/BlockPiston.h#L117):

```
// Notice the lack of an E_BLOCK_ENDER_CHEST here; its because ender chests can totally be pushed / pulled in MCS :)
```

This made me thinking and I looked it up: http://minecraft.gamepedia.com/Piston#Pushing_blocks
And they are **not** pushable...
Also signs are not pushable and maybe some other blocks are missing too.

This should be easy to fix :wink:

**Comment by SphinxC0re** [comment]
Yeah but I think this is intentional ;)

**Comment by bibo38** [comment]
But I don't understand the intention. Shouldn't Cuberite simulate the Vanilla behaviour?
My thought is, that enderchests were not really implemented at that point and that this is an ironic statement.

**Comment by tigerw** [comment]
Yeah, it was intentional. There is no obligation to *fully* mimic vanilla, and this wasn't done since enderchests don't store their contents in their block entity, and so technically can be moved easily.

**Comment by madmaxoft** [comment]
I'm not so sure about the "easily" part, you still need to move the `cEnderChestEntity` representing the chest, so I'd say this is a bug. And we do want to mimic vanilla as close as possible.

**Comment by bibo38** [comment]
So should the EnderChests be moveable or not? You want to mimic vanilla as close as possible, so you should disable the Ender Chest moving.
Btw. You need also to consider, that this *could* break some builds, because if the enderchest is not moveable, a slimeblock ignores it, but when the enderchest is moveable, the slimeblock moving may fail.

P.S.: What about a configuration for such types of blocks, so that the users can itself decide, how much Cuberite should mimic vanilla.

**Comment by tigerw** [comment]
> I'm not so sure about the "easily" part, you still need to move the  cEnderChestEntity  representing the chest, so I'd say this is a bug. And we do want to mimic vanilla as close as possible.

Destroying and reconstructing an ender chest entity has no effect on its behaviour.

-----

I don't really mind if they are made non-moveable; vanilla doesn't provide an animation for it anyway, so movement is more of a disapparation-reapparation rather than a slide. I just request that it is not made configurable. *Please*, no more configuration.

**Comment by NiLSPACE** [comment]
While I prefer to have Cuberite as configurable as possible, I don't think we'd want these things configurable. If we'd want to make these stuff configurable we could just add something like this:
```ini
[Mechanics]
UnPushable=bedrock, obsydian, enderchest, ...
```
