### ISSUE TITLE
Cave spiders can poison without hitting

### ISSUE THREAD

**Issue by Gargaj** [cuberite/cuberite#2613]
```cAggressiveMonster::Attack``` is ```void```, so there's no feedback on whether the attack has succeeded or if it's still in cooldown. Because of this, ```cCaveSpider::Attack``` calls the ```super``` but poisons the target regardless.

**Comment by Gargaj** [comment]
(I can try doing a pull on this.)

**Comment by bibo38** [comment]
Great :smile: !
Better we have a dirty solution, than a bug more.
Looks like the Attack method is bad implemented, because the name suggests, that the monster attacks something.
