### ISSUE TITLE
Implement pushing / shoving

### ISSUE THREAD

**Issue by Gargaj** [cuberite/cuberite#2614]
Potential logic: if two mobs are within a certain distance (in 2D) to each other or to a player, increase the speed of the stationary one away from the other.

I looked into the source but haven't really figured out a way to do the distance check to several entities efficiently. (```ForEachEntityInBox``` maybe?)

**Comment by NiLSPACE** [comment]
You mean pushing a mob? That shouldn't be too hard to implement. Something like this should work: 
```cpp
void cPawn::Tick(...)
{
	class Pusher : public cEntityCallback
	{
	public:
		cEntity * m_Pusher;
		
		Pusher(cEntity a_Pusher) :
			m_Pusher(a_Pusher)
		{
		}
		
		virtual bool Item(cEntity * a_Entity) override
		{
			if (a_Entity->GetUniqueID() == m_Pusher->GetUniqueID())
			{
				return false;
			}
			
			if ((a_Entity->GetPosition() - m_Pusher->GetPosition()).SqrLength() > /* Some size */)
			{
				return false;
			}
			
			a_Entity->AddSpeed(a_Entity->GetPosition() - m_Pusher->GetPosition());
			return false;
		}
	} Callback(/*Current entity*/)
	
	GetWorld().ForEachEntityInBox(new cBoundingBox(GetPosition(), GetWidth(), GetHeight()), Callback);
}
```

**Comment by Gargaj** [comment]
I think the speed should be reciprocal to the distance i.e. you push them more when you are up close.

**Comment by Gargaj** [comment]
Also, should only push mobs, but not other players. (It used to be both but got changed around 1.5 i think?)
