### ISSUE TITLE
Taking damage in shallow water

### ISSUE THREAD

**Issue by Gargaj** [cuberite/cuberite#2622]
This happens because the damage dealt in ```cPlayer::SetTouchGround``` is called by ```cClientHandle::HandlePlayerPos``` (which is a network reaction), but the swimming flag is set in ```cEntity::SetSwimState``` (which is called in a tick). This asynchronism allows the player to register to have landed on the ground but not yet registered as swimming.

Here's a bit of extended logging of me jumping into a single block deep pool of water from a height:
```
[ddbc180b|17:00:40] Y: 74.249, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 74.171, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 74.016, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 73.785, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 73.481, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 73.104, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 72.657, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 72.140, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 71.555, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 70.903, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 70.186, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 69.405, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 68.561, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 67.655, IsSwimming: 0, TouchGround: 0
[ddbc180b|17:00:40] Y: 67.000, IsSwimming: 0, TouchGround: 1
[ddbc180b|17:00:40] Dealing 3 damage
[ddbc180b|17:00:41] Y: 67.000, IsSwimming: 1, TouchGround: 1
```

As you can see, the waterblock at Y=67 is registered as swimming, but one packet too late which deals me damage even though I landed in water.

**Comment by bearbin** [comment]
I believe that this behaviour is the same with vanilla - you need water to be at least 3 blocks high to avoid damage. Was this changed in a recent update?

**Comment by Gargaj** [comment]
This used to be true around 1.7, but got fixed since. Now you can land in ankle-high water from any height and be safe. (See most of the Dropper maps.)

**Comment by Gargaj** [comment]
@bearbin In fact way earlier, I was just being naive: https://bugs.mojang.com/browse/MC-1644
