### ISSUE TITLE
Replace all height validations with cChunkDef::IsValidHeight()

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2635]
! see #2634

**Comment by KillingSpark** [comment]
Hey i know this is pretty old but i'd like to know if this is still an issue, that is to be fixed. Since I have some free time at hand I'm available for dull work.

**Comment by madmaxoft** [comment]
The status is unknown - many of the checks have been replaced, but we don't know if all of them or not, so it is still an issue. Just search for `255`, `256` and `cChunkDef::Height` and if it makes sense, replace it.

**Comment by KillingSpark** [comment]
at least VS doesn't find any comparisons to the values 255/256 in any of the project files, that could be related to height validations. most of them are located in the polarssl or the bindings. I tried pretty much any combination of "<,<=" and "255,256" and spaces, so I'd say its pretty safe to assume, that this is nothing to worry about. But the number 256 still appears on many occasions in the generating process, as a magical number as some kind of size for the chunk. Im not 100% sure about how these are related to the height, as I'm not familiar with the whole map-generating topic.

**Comment by madmaxoft** [comment]
I think you should just search for `255` and `256`, not a comparison to them. For example `src/Blocks/BlockLeaves.h` line 169 uses the number 255 as the max chunk height, so it should be replaced with the `cChunkDef::Height - 1` constant. And there are possibly others.

The occurrences in the Generating folder usually have to do with the array sizes and bit-shifts, so they are not the chunk height.

**Comment by KillingSpark** [comment]
You're right, i found some cases. gonna look further tomorrow. Thanks for the tipp thoug

**Comment by madmaxoft** [comment]
This has been finished.
