### ISSUE TITLE
cIsThread::m_ShouldTerminate synchronisation

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#2636]
The variable is being set in the world thread when Stop() is called but accessed in Execute() from another thread. The variable is declared volatile but this provides no atomicity guarantees.

**Comment by madmaxoft** [comment]
We don't need any atomicity, we only need that the change in the flag's value is visible to the other thread at some (later) time.

**Comment by worktycho** [comment]
Unfortunately, we do need atomicity, because c++ doesn't protect us from torn reads, at which point we enter UB land.

**Comment by worktycho** [comment]
I'm not sure what we need in terms of memory barriers, so I've gone for sequential consistency for now, but we can probably downgrade that if it becomes a bottleneck.
