### ISSUE TITLE
Crash on first connect

### ISSUE THREAD

**Issue by DaMatrix** [cuberite/cuberite#2644]
Whenever a player connects to my server for the first time, the next player to disconnect causes a crash.
Log example:
[Log1.txt](https://github.com/cuberite/cuberite/files/34659/Log1.txt)
nic9f7l7/Log1.txt?dl=0

Running the server on a Pi B+, if that makes any difference.

**Comment by bearbin** [comment]
This sounds like a new issue in master and not in testing, thanks for submitting the log. Is there any chance you could submit a core-dump as well?

**Comment by DaMatrix** [comment]
Core-dump?... (sorry, I'm new to this :| )

**Comment by Schwertspize** [comment]
I also experienced something like that.
DaMatrix: before running cuberite, run 
    $ ulimit -c unlimited
to enable core dumps, after the crash you will see a file like core.9291 (the number is the pid). compress it and upload it somewhere
compressing:
    $ tar caf core.tar.gz core.9291
and upload the core.tar.gz

**Comment by DaMatrix** [comment]
Thanks, will post dump by tomorrow.

**Comment by DaMatrix** [comment]
Huh, I can't recreate the issue by deleting my player data and connecting.

**Comment by tigerw** [comment]
I found something potentially buggy:

libevent loop -> (player disconnects) -> ... -> cClientHandle::SocketClosed -> ...::Destroy()

Destroy() is called in a thread other than the tick.

**Comment by DaMatrix** [comment]
Ok, spamming with connections to the server and then disconnecting seems to cause it, and only on rpi. I've run a server on my desktop (AMD, windows) and my vps (Intel, debian) and cant reproduce it there.  Something in the ARM c++ library?  Or something like that.  Trying the latest binary to see if it fixes anything.

**Comment by LO1ZB** [comment]
This is happening since the cert update for me, too
http://pastebin.com/gNYfcJc6
Please tell me if you need the pdb/dmp or something else.

**Comment by DaMatrix** [comment]
Looks like it has something to do with  authentication.  Ill try turning it off and see if that solves anything.

-------- Original message --------

**Comment by DaMatrix** [comment]
um... bump.  Half my server network is still practically unusable because of this.

**Comment by LogicParrot** [comment]
@SphinxC0re Not every crash is testing.

**Comment by DaMatrix** [comment]
BUMP!!!!!!!!!!!!

**Comment by LogicParrot** [comment]
@DaMatrix I have no experience with the auth so I won't be of use fixing this. May I suggest you try to turn off authentication? This obviously wouldn't be optimal for everyone, but it should work. You can combine this with a [login plugin](https://forum.cuberite.org/thread-811.html).

**Comment by LogicParrot** [comment]
* I am assuming this is auth related. I might be completely wrong *

**Comment by LogicParrot** [comment]
Did it work fine with authentication off?

**Comment by DaMatrix** [comment]
No, turning auth off didn't do anything.  I honestly have no idea what it could be, other than spamming disconnect causes it.

**Comment by LogicParrot** [comment]
@DaMatrix Could you please provide a stracktrace?

 - Get a Debug Build
 - Run the debug build just like you run the regular Cuberite
 - When the debug build crashes, it will produce a lot more info in the log
 - Attach that log

Obtaining a debug build:
In the RaspberryPi console, run this:
```
sh -c "$(wget -O - https://raw.githubusercontent.com/cuberite/cuberite/master/compile.sh)"
```

If it asks you to install some dependencies, install them first.
When it asks you to choose a build, choose "d" (Debug). It will then download and  compile the source code and produce a debug build that you can run.

**Comment by SphinxC0re** [comment]
No, we are not providing debug builds yet

**Comment by LogicParrot** [comment]
I just noticed it's the deadlock detector. Would a stacktrace even help?

**Comment by SphinxC0re** [comment]
it would

**Comment by LogicParrot** [comment]
@tigerw Yes, it seems to be a call from outside the tick thread.

**Comment by DaMatrix** [comment]
...and my pi is refusing connections.  I'll follow up in about an hour when I've reinstall raspbian...

**Comment by DaMatrix** [comment]
*sigh*

**Comment by DaMatrix** [comment]
I got even less info in debug mode.  Look at this:

`[3f8a420f|19:50:43] Player DaPorkchop_ has left the game
[3f8a420f|19:50:43] Deleting cPlayer "DaPorkchop_" at 0x70c0d288, ID 39
[3f8a420f|19:50:43] Player 0x70c0d288 deleted
[3f8a420f|19:50:43] Sending a DC: "Server shut down? Kthnxbai"
[3f8a420f|19:50:43] ClientHandle at 0x67517550 deleted
Segmentation fault
pi@raspberrypi2-server:~/Debug/cuberite/Server $ `

**Comment by tigerw** [comment]
Probably something to do with our horrendous memory management.

I'm currently working on an improvement, that is, if I can get it merged with all the conflicts @LogicParrot is generating for me :P

Can you wait a few days?

**Comment by DaMatrix** [comment]
I can wait, but rather sooner than later :P

**Comment by LogicParrot** [comment]
@tigerw How about a `playersToRemove` lock protected queue, just like `playersToAdd`?

**Comment by LogicParrot** [comment]
@tigerw If you're working on something, perhaps we should coordinate to avoid merge conflicts and wasted manpower.

**Comment by tigerw** [comment]
To be perfectly honest, I haven't a clue what's causing the crashing, so I couldn't possibly comment on whether that will work.

However, the thing I'm working on aims to simplify the way threading is currently done (though judicious use of QueueTask) and as a side effect removes a few locks and various add/remove queues. It also changes a lot of ownership to smart pointers, so perhaps it could fix some lifetime issues.

**Comment by tigerw** [comment]
Unfortunately, the whole reason there are merge conflicts is because I can't seem to stop myself from working on one thing at a time, so the threading PR also involves pointers and entity lifetime :/

I think you should work on your current changes, and I will pull those in once they're done. (dat ParentChunk tho ;) )

**Comment by LogicParrot** [comment]
> libevent loop -> (player disconnects) -> ... -> cClientHandle::SocketClosed -> ...::Destroy()
> Destroy() is called in a thread other than the tick. Can mr xoft confirm?

Looks like the thread management PR is going to take a while. I'll fix this problem in the meantime.

**Comment by LogicParrot** [comment]
Potentially related to #2835.
