### ISSUE TITLE
Allow mobs to jump down up to 3 or 4 blocks

### ISSUE THREAD

**Issue by DaMatrix** [cuberite/cuberite#2646]
I have built a few grinders on my skyblock server, but although the mobs spawn normally, they never walk off the edge into the water unless pushed by other mobs.  Spiders are an exception, and seem to walk over the edge almost as the first thing they do after spawning.  I would say that this is an error in the 4 block entity-jump-limit, but mobs that spawn on top of the grinder seem to be more than willing to jump off the top and make feeble attempts at trying to ambush me. :P

**Comment by NiLSPACE** [comment]
This is because the pathfinder currently doesn't calculate jumps down. In vanilla if the drop is fewer than an X amount of blocks down the mob will jump down. It's in the ToDo list though: http://forum.mc-server.org/showthread.php?tid=1571

**Comment by DaMatrix** [comment]
Except they wont jump into the water (on the inside of the grinder), making many stacks of cobble essentially worthless.

**Comment by NiLSPACE** [comment]
The pathfinder simply doesn't calculate things like that in I'm afraid.

**Comment by DaMatrix** [comment]
:(

**Comment by SafwatHalaby** [comment]
I can easily allow the mobs to jump down up to 2 blocks. Would this be good enough?

**Comment by Seadragon91** [comment]
Let's change and try :)

**Comment by NiLSPACE** [comment]
Vanilla has it as well right? :)

I'm wondering though, @DaMatrix are you sure mobs walk of edges in vanilla? I thought they wouldn't walk off unless pushed. The only exception is blocks like trapdoors. In vanilla mobs see that as a solid block in their pathfinding, walk over it and fall down.

**Comment by SafwatHalaby** [comment]
Vanilla mobs jump down up to 3 blocks without harm. I could do that easily, but I rather do it after #2668 is finished to minimize collisions.

**Comment by NiLSPACE** [comment]
That makes sense. :)

**Comment by SafwatHalaby** [comment]
#2668 is finished. This should be easy.

**Comment by SafwatHalaby** [comment]
In vanilla, do mobs don't mind jumping 4 blocks?

**Comment by NiLSPACE** [comment]
I believe 3 blocks is the max amount of blocks a mob will jump down. Perhaps you'll have to test it first ;)

**Comment by madmaxoft** [comment]
In special circumstances mobs do jump down further - a creeper is willing to jump down many blocks just to explode in your face. At least I remember reading something like that in the wiki.

**Comment by NiLSPACE** [comment]
Oh, I forgot about that. Yes I believe they indeed do that.

**Comment by SafwatHalaby** [comment]
OP claims it's 4. We'll need to test this.

**Comment by DaMatrix** [comment]
Yeah sorry, its only three.  4 is enough to prevent a mob from crossing over the gap.
