### ISSUE TITLE
cRoot:GetPhysicalRAMUsage not supported on FreeBSD

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2649]
If the plugin PluginMemory is activated it will print the message
`GetPhysicalRAMUsage: Unknown platform, cannot query memory usage`
on FreeBSD.

I have FreeBSD running in virtualbox and could test code, if someone can add the support for FreeBSD.

**Comment by worktycho** [comment]
FreeBSD appears to require running the sysctl program to get this info. Writing code to run it and parsing its output is going to require access to a FreeBSD machine for debugging, so I don't think I can write it.

**Comment by Seadragon91** [comment]
I could install freebsd on my raspberry pi 2 and could you give access to it. Would this help?

**Comment by worktycho** [comment]
Possibly, though for me RL is going to be very busy for the next few weeks, so I'm not sure I'm going to be able to fix this soon.

**Comment by PureTryOut** [comment]
This issue is still present on FreeBSD. For me it happens when I open the webinterface.

**Comment by Seadragon91** [comment]
Added by #5213
