### ISSUE TITLE
Make it possible for plugins to change the "hardness" of blocks

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2651]
This could be used to simulate a world where everything is really hard to mine.

**Comment by madmaxoft** [comment]
I suppose you mean "damage" as in "time required to mine"? I'd probably call that "hardness" instead, because "damage" is already used as a synonym to "meta".

**Comment by SphinxC0re** [comment]
That would probably be better. In Minecraft alpha times it was called "damage", but "hardness" is probably better

**Comment by madmaxoft** [comment]
As discussed recently when the fastbreak anticheat was coded, this is not really doable server-side - the're no way to inform the client about the modified hardness of blocks. Closing as "can't do".
