### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cuberite/cuberite#2654]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [cMonster::ResetPathFinding](https://github.com/cuberite/cuberite/blob/445938e01dd8ae6fa37f1c4c57ac256506c603fb/src/Mobs/Monster.cpp#L414 "cMonster::ResetPathFinding function")
* [ZZZ_LeakFinder](https://github.com/cuberite/cuberite/blob/a26541a7c3ced0569098edd0aae61c097c2912f4/src/LeakFinder.h#L119 "destructor for ZZZ_LeakFinder")

**Comment by madmaxoft** [comment]
The leakfinder is a (3rd party) library, no need to go through it and make changes.

**Comment by SafwatHalaby** [comment]
The cMonster class is being overhauled at this very moment, and that line will no longer be there. In fact, m_Path will no longer be there.
