### ISSUE TITLE
nether segfault

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#2655]
I was experiencing a segfault produced by a friend of mine while trying to join the nether. possibly known, they "hit the ground too hard".

a tar.gz is available here: http://minecraft.ninslash.com/report.tar.gz ssl enabled with a testing certificate, you could trust it :)
in the tar archive there is the (I hope corresponding) log, a copy of the screen output and the core dump.

**Comment by Seadragon91** [comment]
I am not able to test the core file, without the executable that has been used. If possible could you try the steps from the section [live analysis](http://forum.mc-server.org/showthread.php?tid=631&pid=23265).

**Comment by Schwertspize** [comment]
if this does not help you, I'm sorry, I had broken my server Yesterday and had to recompile
