### ISSUE TITLE
Compiling fails on both Arch Linux and Ubuntu 15.10

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#2659]
Using Arch Linux, but also Ubuntu server 15.10, compilation fails.
```
CMakeFiles/Makefile2:1552: recipe for target 'src/Mobs/CMakeFiles/Mobs.dir/all' failed
make[1]: *** [src/Mobs/CMakeFiles/Mobs.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by worktycho** [comment]
Can you post the earlier output? There should be a message about why it failed.

**Comment by PureTryOut** [comment]
Well there is a lot of output, I posted it here. https://bpaste.net/show/1b3c9e1a1b3a

**Comment by worktycho** [comment]
try master, not testing.

**Comment by PureTryOut** [comment]
Oops I feel stupid now, it compiles fine. Sorry for bothering you!

**Comment by Schwertspize** [comment]
I think it's less your fault.
@cuberite/core-team we should probably add a note, that the testing branch is NOT state-of-the-art

**Comment by NiLSPACE** [comment]
But.. the testing branch just got removed by @worktycho
