### ISSUE TITLE
When does cMonster::wouldBurnAt crash

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2664]
I'm playing around with the AI (hopefully there'll be a PR soon), and this [line](https://github.com/cuberite/cuberite/blob/master/src/Mobs/Monster.cpp#L466) crashed several times.

The code I'm working at is changing rapidly, and I can no longer reproduce this. In general, what conditions must be met to make `cMonster::WouldBurnAt` crash? Would supplying a location which is too far off from the chunk cause that?

**Comment by madmaxoft** [comment]
It should never crash. The only reason I could think of is that the `a_Chunk` parameter is already `nullptr` while calling it.

**Comment by SafwatHalaby** [comment]
Thanks
