### ISSUE TITLE
Possibly not a bug so much as a workaround, Guardians and Squids burn to death on land.

### ISSUE THREAD

**Issue by Zee1234** [cuberite/cuberite#2665]
Guardians in vanilla take no damage out of whiter, while squids take damage, but not while on fire. Just pointing that out.

The chicken bug that is now an every mob bug would also go here, but it's been reported already elsewhere.

**Comment by SphinxC0re** [comment]
How? #2502

**Comment by SafwatHalaby** [comment]
This doesn't contradict #2502. I don't think he meant the squids go out on land.
