### ISSUE TITLE
The constants from family types are not available in lua

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2666]
Anyone has a idea why they [constants](http://api-docs.cuberite.org/cMonster.html#constants) are all nil?
The file Monster.h is added in AllToLua.pkg and tolua_begin is added inside there.

**Comment by Seadragon91** [comment]
I can access them this way `cMonster.mfPassive`. This should be accessible directly, or?

**Comment by madmaxoft** [comment]
They are supposed to be accessed that way.

**Comment by Seadragon91** [comment]
Okay thank you. Have worked with to many global constants and tried to use them this way :)
