### ISSUE TITLE
Experience orbs orbit player forever

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2667]
On some rare occasions, when touching an experience orb, it is not picked. Instead, it orbits the player until they logout.

**Comment by Schwertspize** [comment]
it happens in Vanilla too, some times (I only tried single player)

**Comment by SafwatHalaby** [comment]
Thanks. So this might be a client side issue.

**Comment by tigerw** [comment]
The server doesn't exactly replicate the behaviour of experience orbs, and the server certainly doesn't actually move them with as much grace as they should, so I would say most of the time the orbiting is due to the orbs not actually reaching the player serverside.

**Comment by madmaxoft** [comment]
The server doesn't move the orbs towards nearby players, the client assumes it does, and moves the orb, until it's close enough that the client just assumes it cal collect the orb, while it's still too far for the server. This does indeed sometime happen in vanilla as well, though not that often.

So this issue boils down to implementing the movement of the orbs towards the nearest player.

**Comment by tigerw** [comment]
I'm fairly certain STR or someone implemented that though.

**Comment by NiLSPACE** [comment]
Yeah, I was the one who implemented experience orbs. I was never able to recreate the physics from vanilla though. Because of that sometimes the experience orb starts moving for the client, but server doesn't think it does resulting in this bug.

**Comment by NiLSPACE** [comment]
A quick fix is to make an experience orb broadcast it's position once in a while. For example every 100 ticks or so. Of course we still have to implement the proper physics code eventually.
