### ISSUE TITLE
Server Cannot authenticate minecraft user.

### ISSUE THREAD

**Issue by luckcolors** [cuberite/cuberite#2675]
Hello.
I just setted up cuberite and i cannot login with my minecraft account:
1. tested again with the vanilla minecraft server and it logs me in correctly.
2. checked more than one time nslookup for the session.minecraft.net and i checked various minecraft status servers.
   I don't se how the game is not able to auth the users.
   Here's the error log:

[12:58:41] cMojangAPI::SecureRequest: Can't connect to sessionserver.mojang.com:
[12:58:41] Kicking player luckcolors for "Failed to authenticate account!"

**Comment by Seadragon91** [comment]
I have this problem sometimes too, but after a few more times I am able to login. I guess you tried to login a few times, too.

**Comment by luckcolors** [comment]
I mean @Seadragon91 if i was banned from the session server by too many login attempts there's no sense on why the vannilla server would work.

**Comment by SafwatHalaby** [comment]
@luckcolors Are you using the latest Cuberite?

**Comment by worktycho** [comment]
Also, mojang might be banning user agents, as we have a different user agent from vanilla.

**Comment by SphinxC0re** [comment]
I'm totally able to connect to my self compiled Cuberite

**Comment by Schwertspize** [comment]
maybe related to an api change because skins are not working too

**Comment by luckydonald** [comment]
Can confirm this. 
My account is a pre-majong account btw.

**Comment by worktycho** [comment]
@luckydonald Are you using a version before or after 2b27bf9? If you're not sure post the commit id output at startup. Because we've had some issues with the session server today to do with mojang changing their certificate, which updating to 2b27bf9 or later will fix. It is unclear whether this issue is related.

**Comment by luckydonald** [comment]
```shell
mac:~ luckydonald$ docker run --tty=true -i -p 25565:25565 -p 8080:8080 --name=mc s7b4/cuberite
[01:20:54] --- Started Log ---
[01:20:54] Cuberite Jenkins clang x64 Release (master) build id: #290
[01:20:54] from commit id: 68e575c917f03f04266df72f32836ac9df2ecdc0 built at: Sun  6 Dec 13:40:12 CET 2015
```

**Comment by luckydonald** [comment]
@worktycho I believe by running [https://raw.githubusercontent.com/cuberite/cuberite/master/easyinstall.sh](https://raw.githubusercontent.com/cuberite/cuberite/master/easyinstall.sh)

**Comment by luckydonald** [comment]
![```[01:28:35] SecureRequest: Can't connect to sessionserver.mojang.com: SSL handshake failed: -0x2700
[01:28:35] Kicking player luckydonald for "Failed to authenticate account!"
[01:28:45] SecureRequest: Can't connect to sessionserver.mojang.com: SSL handshake failed: -0x2700
[01:28:45] Kicking player luckydonald for "Failed to authenticate account!"```](https://cloud.githubusercontent.com/assets/2737108/11969771/5223a71a-a91f-11e5-8786-8f22b969e835.png)

**Comment by worktycho** [comment]
Yes, that version predates 2b27bf9. Try updating to the latest version.

**Comment by luckydonald** [comment]
@worktycho  So i just wait for jenkins to build a new package?

**Comment by worktycho** [comment]
The latest Jenkins build should have the fix.

**Comment by Seadragon91** [comment]
Closing as this was possible problem with the certificate change, that has been resolved.
