### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#2677]
Server crashes multiple times on /regen ingame (i bound it via /powertool and executed it 5 times in 5 secs)

http://minecraft.ninslash.com/crash.tar.gz 18 mb including my Server dir without worlds (including logs, core dump, binary

**Comment by NiLSPACE** [comment]
The link is invalid

**Comment by SphinxC0re** [comment]
Also, I don't think this is important because it is plugin related

**Comment by Schwertspize** [comment]
I know I lost it yesterday.
