### ISSUE TITLE
cBlockArea::MakeIndex: No check for out or range access, in Release mode

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2681]
In method [cBlockArea::MakeIndex](https://github.com/cuberite/cuberite/blob/master/src/BlockArea.cpp#L1882) we have assertions for Debug mode, but no check for Release mode. If a index access is out of range, the server ~~will~~ might crash immediately or on shutdown.

~~Would be the same check like the assertions and a log warning enough?~~

Edit: Okay this is not to easy to fix.

**Comment by madmaxoft** [comment]
We don't want that check in Release, because the operation is too heavily used in tight loops.

**Comment by Seadragon91** [comment]
Yes that makes sense.
