### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#2682]
hello. another crash (not the newest master, but the bug is present in master, i think)

http://minecraft.ninslash.com/crash-2015-11-23.tar.gz 16M contains server dir excluding worlds

**Comment by Seadragon91** [comment]
Okay this crash is this the [comment](https://github.com/cuberite/cuberite/issues/2286#issuecomment-115723697) in this issue #2286

**Comment by Schwertspize** [comment]
actually I experienced it as I was disconnected while being in a world. I think I did multiple /regen before or something like that
