### ISSUE TITLE
Add auto-save routine

### ISSUE THREAD

**Issue by SphinxC0re** [cuberite/cuberite#2689]
I don't know if the server automatically saves all worlds after some time, because there is no place where it's documented

**Comment by NiLSPACE** [comment]
Yes it does auto-save: https://github.com/cuberite/cuberite/blob/master/src/World.cpp#L996

It used to even spam the console because it was saving every 5 minutes.

**Comment by SphinxC0re** [comment]
Okay so a documentation failure

**Comment by NiLSPACE** [comment]
Barely anything about the configuration is documented, so yes ;)
