### ISSUE TITLE
cPlayer:GetPosition() returns a pointer to the Vector3d object

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2690]
I wanted to select 2 positions like WorldEdit. For that I used the function GetPosition() from cPlayer. The positions then I stored in a table to use it later.
Found then out that the function GetPosition returns a pointer to the Vector3d instead of a new Vector3d object :)

I use this workaround from the lua side.
`local position = Vector3d(Player:GetPosition())`
This would then create a new Vector3d object and not point to the current player position.

This should be changed, storing a player position as pointer can crash the server if accessed later and the player is not online :)

**Comment by Seadragon91** [comment]
Would it be enough to add in the documentation that it returns a pointer to the Vector3d object?

**Comment by madmaxoft** [comment]
No, we should return a brand new object for Lua's use, not a shared one with indeterminate lifetime.

**Comment by Seadragon91** [comment]
How can I create a copy of the `Vector3d` object? Using this below, returns strange coordinates,
`Vector3d Position = self->GetPosition();;`

**Comment by NiLSPACE** [comment]
```cpp
Vector3d cEntity:GetPosition()
{
    return Vector3d(m_Position);
}
```
?

**Comment by Seadragon91** [comment]
I tested your idea https://github.com/Seadragon91/cuberite/commit/30a62c24ca8322dc72e7fa3231246514ed739150, stil return incorrect coordinates.

**Comment by NiLSPACE** [comment]
Could you show the code used to view the coordinates?

**Comment by Seadragon91** [comment]
I added a plugin that runs a command to save the my position and then run another command to place a block there. And there I print the coordinates.

**Comment by NiLSPACE** [comment]
Could you show the code? I have a faint memory that I also had problems with Vector3X not having the expected values.

**Comment by Seadragon91** [comment]
I got it working. Used your code and let tolua export it. Then I looked into Bindings.cpp and added the code to ManualBindings :) https://github.com/Seadragon91/cuberite/commit/e247c7fc806e547d57b69fd3ea1c883a5bf25199

**Comment by Seadragon91** [comment]
Will create a pull request for this later. There are a few more methods that should return a copy instead of a pointer.
