### ISSUE TITLE
Split server config into seperate parts

### ISSUE THREAD

**Issue by SphinxC0re** [cuberite/cuberite#2691]
As the server grows the config file seems to grow into a huge lump so I suggest splitting the config into subdirectories.
```
settings/
 |- main.ini
 |- generators/
   |- composite.ini
   |- amplified.ini
   ...
 |- 
```

**Comment by madmaxoft** [comment]
The generators are per-world, so they need to be in the specific world folders. And I don't think the files are so large that they'd need splitting.

**Comment by NiLSPACE** [comment]
+-200 lines for the world.ini is reasonable. It's all split up in sections, so it's organized. Also, you're most likely to only look at it when setting it up, so there is no real reason to change it.

**Comment by SphinxC0re** [comment]
But what about plugins? It would be easier for them to just write in their own file when adding a new generator. In the world ini you would just define what generator to use and you could just configure the generators properties in the separate file.

**Comment by NiLSPACE** [comment]
I'd hate to configure my world that way. First open a file to enable a generator or finisher, and then open a different file to fine-tune it? I'd prefer to have it all in one file.

Also, It's pretty easy for plugins to use the world.ini:
```lua
local IniFile = cIniFile()
IniFile:ReadFile(World:GetIniFileName())
if (IniFile:GetValue("Generator", "BiomeGen") ~= "GeneratorByThisPlugin") then
   -- This world doesn't have the generator created by this plugin enabled.
   return
end

local Size = IniFile:GetValueSetI("Generator", "GeneratorByThisPluginSize", 120)
local Biomes = IniFile:GetValueSetI("Generator", "GeneratorByThisPluginBiomes", "plains,desert,hell")

-- Perhaps parse the configuration first or something

-- Save and enable the generator in this world.
Generators[World:GetName()] = {Size = Size, Biomes = Biomes}
```

**Comment by worktycho** [comment]
That isn't guaranteed to get the settings though. The server can change the settings whilst writing, and not write them back until shutdown.

**Comment by SphinxC0re** [comment]
Is this a good or a bad idea? Can I close this?

**Comment by madmaxoft** [comment]
@worktycho the server should write the settings relatively soon after loading them, so this race condition is rather unlikely to occur. Plugins are initialized in another phase.

@SphinxC0re I vote this should be closed as "won't fix", but let's hear the others, too.

**Comment by SafwatHalaby** [comment]
Closing since the consensus seems to be against this. Feel free to reopen.
