### ISSUE TITLE
Peony transforms into sunflower

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2701]
- Destroying a peony yields a sunflower drop.
- Placing a peony item spawns a 2-block peony. The upper block instantly breaks, and drops a sunflower and a peony.
#2401 and  #1428 are possibly related.

**Comment by SafwatHalaby** [comment]
[Related forum post here](http://forum.mc-server.org/showthread.php?tid=2227).

**Comment by Schwertspize** [comment]
if a peony is that what I think it is, try finding one and removing the lower block with eg worldedit

**Comment by Bond-009** [comment]
This is already fixed.
