### ISSUE TITLE
Slow chunk loading/generation when run under a virtual machine?

### ISSUE THREAD

**Issue by lighth7015** [cuberite/cuberite#2703]
It seems to me, that after running cuberite in a virtual machine (**VMware ESXi** in particular), either chunk loading or generation is rather slow.

Can we do anything do to speed up chunk loading and generation when run on a virtual machine like `VMware ESXi`, `KVM` or `Xen`?

I'm opening this ticket for discussion of the issue and what can be done to profile how cuberite handles chunk loading/generation and to see if we can tweak it any to offer performance gains when run inside virtual machines.

**Comment by SphinxC0re** [comment]
I did a test on ```KVM``` and worked out nicely. The speed was okay. Still virtual but okay.

**Comment by madmaxoft** [comment]
Unless you have some hard numbers to show for your claims, there's not much to be compared. 

Generally I haven't seen a noticeable decrease in the generator performance between a native executable running on my Windows workstation and an executable running in virtualboxed Linux on the same machine.

The easiest way to "profile" chunk generation is to remove the world's region files and let them regenerate upon server start, the server logs the chunk generator speed in the console. You can set `[SpawnPosition]`.`PregenerateDistance` to a higher number to generate a larger area on startup (it is the number of chunks to generate around the spawn in each direction). Compare the resulting chunk generator speed between the virtual machine and a comparable physical machine.

If you compile Cuberite in debug mode, the generator will log some speed statistics from time to time. Those are another point of possible comparison. Although debug builds are generally not too well suited for performance analysis, this can give an overview.

The world generator for each world runs in a single thread, the lighting generator for each worlds runs in another separate single thread, and the tick thread for each world in yet another separate thread. So if you want to get the max performance, you need to have at least `3 * NumWorlds` "cores" in your machine.

**Comment by tigerw** [comment]
Might be out of our remit, as long as the results are correct.
