### ISSUE TITLE
Stickypistons seem broken.

### ISSUE THREAD

**Issue by lighth7015** [cuberite/cuberite#2705]
Last night, I was screwing around with a friend of mine and he built this diamond structure using stickypistons on my dev server and we noticed that stickypistons don't properly reset after being toggled en masse. Some of the pistons are quite losing their extenders and failing to pull their cargo back into the default position and seem to be confused as to their current state.

I'm looking into what's exactly going on, and will post follow-ups as I figure things out.

**Comment by lighth7015** [comment]
UPDATE: Stickypistons do not properly push (**or** pull) other stickypistons that have blocks attached.

**Comment by SphinxC0re** [comment]
extended pistons are (by default) not pushable

**Comment by lighth7015** [comment]
Hop onto the server I told you about and you can see what I mean.

**Comment by lighth7015** [comment]
I have two stickypistons "stuck" together, and a block of diamond stuck to the piston that's stuck to the free piston; when I flip a lever, the block of diamond just sits there.

**Comment by bibo38** [comment]
@lighth7015 Can you please provide a sample image/world to test this bug?

![Sticky Piston + Sticky Piston + Diamond block](https://cloud.githubusercontent.com/assets/1812304/12218644/e40ebf3e-b725-11e5-833a-52573d14af56.png)
I don't know, if you mean this construction, but it works fine on my Cuberite Server.

**Comment by pwnorbitals** [comment]
If this issue cannot be reproduced, I suggest this issue be closed
