### ISSUE TITLE
IMPROVEMENT: Ensure only blocks can be placed with worldedit, minimizing the potential for server crash due to assert failures.

### ISSUE THREAD

**Issue by lighth7015** [cuberite/cuberite#2710]
I've crashed my development copy of Cuberite before by trying to worldedit a section of blocks into diamond drops because I forgot what item id# diamond blocks were.. Oops.

We should really ensure things like that are caught before it gets to the "Oh, abort()!" stage. :p

**Comment by NiLSPACE** [comment]
This isn't a Cuberite issue, but a WorldEdit issue: cuberite/WorldEdit#51

**Comment by worktycho** [comment]
Its a cuberite issue as well. Plugins should not be able to cause server crashes.

**Comment by madmaxoft** [comment]
It wasn't a crash as such, it was an assert (which is tolerable in my opinion)

**Comment by worktycho** [comment]
An assert is something that could cause a crash. So we don't want plugins able to cause assert failures.

**Comment by madmaxoft** [comment]
Yes, it is something to look into, true. I suppose it's just a case of "unknown block handler" or something similarly trivial.

**Comment by worktycho** [comment]
Its a bug, but low priority one.

**Comment by NiLSPACE** [comment]
I think the code that's using cBlockArea should check beforehand if the block is valid. Otherwise you'd have to check in the SetBlockType functions if the block is valid.

**Comment by worktycho** [comment]
That check should be in the lua wrapper for SetBlockType. Its not expensive compared to the cost of a lua FFI.

**Comment by mathiascode** [comment]
No longer causes a crash.
