### ISSUE TITLE
Chat action show_text for hoverEvent missing

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2716]
For the chat exists a action named `show_text` for the hoverEvent, that shows you text if you hover with the mouse over it.
Ref. http://wiki.vg/Chat

The problem Is that we need lots of more methods, to combine different actions. For example hover and run command, hover and suggest command, hover and url.

Example names of the methods.
```
AddShowTextPart
AddShowTextAndUrlPart
AddShowTextAndRunCommandPart
AddShowTextAndSuggestCommandPart
```

How you see it looks not good anymore. I think we should rethink the way of creating a message.

**Comment by madmaxoft** [comment]
We could make an `AppendTextPart`, `AppendUrlPart` etc. methods that would return the actual part that was appended, then that part could have some more methods, like `SetShowText`, `SetColor` and others, and also the `Append___Part` methods that would return a new part appended to the message. I think an example would be easier to understand:
```lua
a_Player:SendMessage(cCompositeChat("", mtInfo)
  :AppendTextPart("some text")
    :SetShowText("hover text")
    :SetColor(cChatColor.White)
  :AppendUrlPart("http://cuberite.org")
    :SetColor(cChatColor.LightBlue)
  :GetMessage()
)
```

Or, even better, create yet a new class, `cChatMessage`, which would be a simple array of `cChatMessagePart` classes, each representing a single part (of any type) in the message and with methods like `SetText`, `SetColor`, `SetClickEvent`, `SetHoverEvent` etc. Example usage:
```lua
a_Player:SendMessage(cChatMessage:Create()
  :AppendPart("Basic text")
    :SetColor(cChatColor.White)
  :AppendPart("Clickable url")
    :SetClickEvent("open_url", "http://cuberite.org")
    :SetColor(cChatColor.LightBlue)
  :AppendPart("Suggest a command")
    :SetClickEvent("suggest_command", "/time set day")
    :SetColor(cChatColor.Orange)
    :SetHoverEvent("show_text", "Set the world time to day")
  -- Either call :GetMessage() or make
  --    cPlayer:SendMessage() support sending messages by their last part
)
```
If the client supports nesting the `extra` sections into any depth, we could even merge the two classes into a single one, with the very same usage pattern.

**Comment by Seadragon91** [comment]
The second option looks well. For the style also a own method?

**Comment by madmaxoft** [comment]
I don't understand your question

**Comment by Seadragon91** [comment]
I mean with style to format the text: bold, underlined, italic.

**Comment by madmaxoft** [comment]
Yes, there will be style-setting methods, too.

**Comment by Seadragon91** [comment]
I have implemented this, without SetColor and SetStyle. It's possible to directly use cChatColor in the methods, looks like minecraft allows this.
This is an idea how it could be look.

https://github.com/Seadragon91/cuberite/tree/chat_message

**Comment by madmaxoft** [comment]
Could you move that commit / branch to the main repo (you should have write access) and start a PR for discussion? I like most of the changes but there are some points that could be addressed in a better way.

I don't like the naked pointers there, you should use `SharedPtr` instead to avoid manual memory management.
Currently your code doesn't support the chaining I sketched out. The `AppendPart` function returns the original `cChatMessage` instead of the newly added part, and there's no way to get from the part to its parent message anyway.
I think it would have been better to use the `cChatMessage` class for both the top-level message and the individual parts, and `cClientHandle:SendMessage` should first walk to the root of the message object given to it. Basically this:
```cpp
class cChatMessage
{
protected:
  /** The next part in the chain, nullptr when this is the last part. */
  SharedPtr<cChatMessage> m_NextPart;

  /** The previous part in the chain, nullptr when this is the first part. */
  cChatMessage * m_ParentPart;

public:
  /** Constructs a new top-level message object */
  cChatMessage(const AString & a_Text);

  /** Constructs a new child part for the given parent */
  cChatMessage(cChatMessage * a_ParentPart, const AString & a_Text);

  /** Returns the first part of the entire message chain. */
  cChatMessage * GetRoot(void) const;
};
```

**Comment by Seadragon91** [comment]
I don't understand your idea. Why need a parent and a next part. The simplest would be just list, where  we call then the methods on the last part in the list.

**Comment by madmaxoft** [comment]
If we want to support syntax like this:
```lua
cChatMessage:Create()
  :AppendPart("Basic text")
    :SetColor(cChatColor.White)
  :AppendPart("Clickable url")
    :SetClickEvent("open_url", "http://cuberite.org")
    :SetColor(cChatColor.LightBlue)
  :AppendPart("Suggest a command")
    :SetClickEvent("suggest_command", "/time set day")
    :SetColor(cChatColor.Orange)
    :SetHoverEvent("show_text", "Set the world time to day")
```
then we need to make modifications - your code will not work like this.

Have a look what would happen in Lua if you tried this code (marked with comments):
```lua
cChatMessage:Create()  -- returns a cChatMessage
  :AppendPart("Basic text")  -- returns a cChatMessagePart
    :SetColor(cChatColor.White)  -- returns the same cChatMessagePart
  :AppendPart("Clickable url")  -- ERROR: no such function in cChatMessagePart!
    :SetClickEvent("open_url", "http://cuberite.org")
    :SetColor(cChatColor.LightBlue)
  :AppendPart("Suggest a command")
    :SetClickEvent("suggest_command", "/time set day")
    :SetColor(cChatColor.Orange)
    :SetHoverEvent("show_text", "Set the world time to day")
```
Therefore I say it's easier to use a single class, cChatMessage, and represent further parts in the message as additional cChatMessage instances that are bound to the "root" message. With my style of code, this is what would happen while executing the Lua code:
```lua
a_Player:SendMessage(
cChatMessage:Create()  -- Creates the root cChatMessage
  :AppendPart("Basic text")  -- Adds a new part, cChatMessage (A), and returns it
    :SetColor(cChatColor.White)  -- Set A's color, returns A
  :AppendPart("Clickable url")  -- Adds a new part, cChatMessage (B), and returns it
    :SetClickEvent("open_url", "http://cuberite.org")  -- Sets B's properties, returns B
    :SetColor(cChatColor.LightBlue)
  :AppendPart("Suggest a command")  -- Adds a new part, cChatMessage (C), and returns it
    :SetClickEvent("suggest_command", "/time set day")  -- Sets C's properties
    :SetColor(cChatColor.Orange)
    :SetHoverEvent("show_text", "Set the world time to day")
)
-- SendMessage is called with C as the argument; in order to send the entire message, we need a way to get to the root from C
```
With my style, the entire message would be represented by this chain:
```
Root message object
+-- A ("Basic text")
    +-- B ("Clickable url")
        +-- C ("Suggest a command")
```
I hope this makes it clearer.

**Comment by SphinxC0re** [comment]
Are you missing a *finalize* method?

**Comment by Seadragon91** [comment]
I always return cChatMessage, not cChatMessagePart (this us only used internal).

**Comment by SphinxC0re** [comment]
Isn't that a violation of the *bulider pattern*?

**Comment by Seadragon91** [comment]
My current code in lua:
```
local cm = cChatMessage()
:AppendPart( cChatColor.Green .. "Welcome, on the server. Website: ")
:SetHoverEvent("show_text", cChatColor.LightBlue .. "Click on the link to open it.")
:AppendPart(cChatColor.Gold .. "https://cuberite.org")
:SetClickEvent("open_url", "https://cuberite.org")
```

**Comment by SphinxC0re** [comment]
I don't really care about pattern violations myself so just do it :laughing:

**Comment by madmaxoft** [comment]
Ah, I've read the code wrong. The documentation could use some love, in order to prevent such a confusion ("`cChatMessage::SetHoverEvent()`: sets the hover event for the last appended part" etc.)

Perhaps the class should be named differently, then? How about `cChatMessageBuilder`?

I was loosely following the builder pattern as well, but in two levels - one builder for appending the parts, and another builder for manipulating the parts. A single builder looks better, I have to admit.

So, again: move the code branch to the main repo and start a PR so that we can comment on it. And don't forget to add the Lua API docs, favorably with an example.

**Comment by Seadragon91** [comment]
Further discussions in #2764.
