### ISSUE TITLE
Animals don't follow you using leads

### ISSUE THREAD

**Issue by rekuen** [cuberite/cuberite#2729]
I' have noticed that animals don't cross an open fence gate when using food to make them follow you, they just turn around when are in front of a fence gate.

Also they don't follow me when I use a lead on them, I only test this under Survival using the latest build.

**Comment by SafwatHalaby** [comment]
Regarding gates, there's already an issue here: https://github.com/cuberite/cuberite/issues/2062
I'll rename this ticket and only keep the lead issue.

**Comment by rekuen** [comment]
OK, sorry for the duplicate.

**Comment by sagr4019** [comment]
is anybody still working on this?

**Comment by LogicParrot** [comment]
No, I am working on a big AI rewrite though, and if someone works in parallel on this, it would likely cause collisions.
