### ISSUE TITLE
`/butcher` command reports too many mobs

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2731]
The butcher command seems to be lying about the number of mobs killed. This is either some internal issue or a plugin issue.
![2015-12-11_22 09 59](https://cloud.githubusercontent.com/assets/5030488/11758117/211cd04a-a070-11e5-88db-1ea0e916db44.png)

**Comment by SafwatHalaby** [comment]
![2015-12-11_22 08 15](https://cloud.githubusercontent.com/assets/5030488/11758122/29c1a946-a070-11e5-842b-00d60652a4bc.png)

**Comment by SphinxC0re** [comment]
wrong repo. This probably has to go into Core

**Comment by madmaxoft** [comment]
Not necessarily, it could be a server issue - the mobs are reported although they're already gone, or different entities are enumerated. Needs investigation.

**Comment by SphinxC0re** [comment]
Hmm.. maybe I'm a little too fast :smile:

**Comment by NiLSPACE** [comment]
I've noticed this before. I believe it's because an entity is in an unloaded chunk. Since the chunk isn't ticked the entity doesn't get removed.

Also, @SphinxC0re if this were a problem in the plugin it would be in WorldEdit, not the Core ^ ^

**Comment by LogicParrot** [comment]
We might be able to take advantage of the newly added [cChunk::SafeRemoveEntity](https://github.com/cuberite/cuberite/commit/07b7fd4ad3fef714399009efd5d4a903a561a6f2#diff-af2ddf3aaa057bf2bbd7dbfe509c9918R265) here.

**Comment by LogicParrot** [comment]
SafeRemoveEntity was created precisely because of this problem: removal of entity in unloaded chunks.
