### ISSUE TITLE
Not able to place creative blocks

### ISSUE THREAD

**Issue by chrobione** [cuberite/cuberite#2736]
Hello,  

Hello All, 

If I need to make a git issue out of this I will, but I think it something I am doing to cause this.   

So I have two CentoOS 6.7 and an Ubuntu 14.04 servers 

Ubuntu4.04:
```
Cuberite local build build id: Unknown
[10:51:26] from commit id: approx: 68e575c917f03f04266df72f32836ac9df2ecdc0 built at: approx: 2015-12-06 13:40:45 +0100
```
CentOS 6.7 production
```
[18:09:44] Cuberite local build build id: Unknown
[18:09:44] from commit id: approx: 2b2e0f3b2c2e0f1b813caf7a7b769461001e0ec9 built at: approx: 2015-12-09 14:02:50 +0100

```
CentOS 6.7 Dev
```
[11:41:42] --- Started Log ---
[11:41:42] Cuberite local build build id: Unknown
[11:41:42] from commit id: approx: 68e575c917f03f04266df72f32836ac9df2ecdc0 built at: approx: 2015-12-06 13:40:45 +0100
```

My player is selected as Admin rank.

The issue is that blocks or items, that have not been picked up or used previously, and selected from the creative inventory do not seem to register with the server.  The blocks or items will show on the client in their placed location, until the client re-logs. 

If there is a second player watching, they will only see the other player glowing red as they are attempting to place blocks.  You will see arm movement but no block placement.    

Worldedit will place and remove blocks fine.

Breaking blocks/items work as expected and disappear.

If you use NEI to give yourself  items/block, they will work as expected.

I am not sure on how to further troubleshoot this issue, any help is very much appreciated.

Chrobi

**Comment by chrobione** [comment]
I am sorry.  I have narrowed it down to client side plugin causing the issues.  Pure unmodded minecraft works fine.

**Comment by lialosiu** [comment]
I has same problem at 1.7.10, but not at 1.8.9, maybe some different on 1.7 / 1.8 version

**Comment by LogicParrot** [comment]
Regarding the 1.7.x issue:
#2026
