### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2745]
I tested the windows builds from `http://builds.cuberite.org/` and have problem with the memory usage of them. I tested this on 2 computers (Win 7 x64)

The x86 build crashes seconds after I joined the server.
The x64 build increases the memory up to max RAM and later it crashes, too.

Self compiled builds works fine. Another thing is, the problem occurs after I join the server. I can pre-generate a world with over 10k chunks without any problems.

 Anyone can test this? Be careful it could freezes your computer and then it can be necessary to force a shutdown.

Edit: Any of the commit starting at this commit 6995af0 are the cause for a memory leak.

**Comment by LO1ZB** [comment]
I'll test this

**Comment by LO1ZB** [comment]
Callstack:
http://pastebin.com/gh5ptpQX

**Comment by Seadragon91** [comment]
Have bisected the builds and the windows builds is after this commit 6995af0 are all broken.

**Comment by Seadragon91** [comment]
@LO1ZB Yes I had also a deadloc with x64 build, but it's a memory leak.

**Comment by LO1ZB** [comment]
I've disabelt the deadlock detector lets see what happens. ;)

**Comment by Seadragon91** [comment]
Do you also look at the memory?

**Comment by LO1ZB** [comment]
I'll try to compile it localy and then run it ander the debugger.

**Comment by bearbin** [comment]
Is that commit when the builds broke or is it a problem in the source? It would seem strange to be that build, given that it was only changing crafting recipes.

**Comment by Seadragon91** [comment]
The commit is from the build page. The problem is between  6995af0 - e4a237b. I can not bisect it with git, because the memory leak doesn't occur in self compiled builds.

**Comment by Seadragon91** [comment]
I think the problem is here 8a5df43

**Comment by Seadragon91** [comment]
Could it be also possible, that something strange gone wrong in compiling?

**Comment by LO1ZB** [comment]
Wich version of Visual Studio are you using? The build server uses Visual Studio 2013 with the cmake flags 'cmake -G "Visual Studio 12 Win64" -T "v120_xp" . '

**Comment by Seadragon91** [comment]
Downloaded and installed VS 2013 and yea now I can compile builds the memory problem.
