### ISSUE TITLE
Chat auto complete -spaced commands duplicating first command when tabbing.

### ISSUE THREAD

**Issue by chrobione** [cuberite/cuberite#2747]
Issue:

When you press tab to auto-complete a multi-spaced command you will get initial command duplicated.

To duplicate this issue:
Cuberite server using Essentials plugin

open chat do "/time "  <-with space
press tab a couple of times and you will start getting "/time /time /time /time"

**Comment by Seadragon91** [comment]
Can confirm that problem.
