### ISSUE TITLE
OS X 10.10 build problems

### ISSUE THREAD

**Issue by benton** [cuberite/cuberite#2752]
I'm trying to build on OS X 10.10 according to the [OS X instructions](https://github.com/cuberite/cuberite/blob/master/COMPILING.md#osx). The command

```
cmake -DCMAKE_BUILD_TYPE=RELEASE .. -G Xcode
```

runs fine, but the next recommended command, `xcodebuild lib/polarssl/POLARSSL.xcodeproj`, refers to a nonexistent target...

```
╭─me@workstation ~/projects/cuberite/Release ‹2.2.2› ‹master*› 
╰─➤  xcodebuild lib/polarssl/POLARSSL.xcodeproj                                                           1 ↵
xcodebuild: error: Unknown build action 'lib/polarssl/POLARSSL.xcodeproj'.
```

Opening `Cuberite.xcodeproj` in Xcode and attempting to build the top-level project myself got me a bit further (I think). There are plenty of warnings about old-style casts, as per [PR 2417 ](https://github.com/cuberite/cuberite/pull/2417), but the only error appears to derive from a problematic macro expansion defined in [lauxlib.h](https://github.com/cuberite/lua/blob/master/src/lauxlib.h#L22):

```
if defined(LUA_COMPAT_GETN)
LUALIB_API int (luaL_getn) (lua_State *L, int t);
LUALIB_API void (luaL_setn) (lua_State *L, int t, int n);
#else
#define luaL_getn(L,i)          ((int)lua_objlen(L, i))
#define luaL_setn(L,i,j)        ((void)0)  /* no op! */
#endif
```

My C++ is rusty, and I don't know how to fix this, though it seems related to the old-style casting thing. I tried changing the `((int)lua_objlen(L, i))` to `(static_cast<int>(lua_objlen(L, i)))`, before running `cmake ...`, but that rendered the following `luaxlib.c`:

```
#if defined(LUA_COMPAT_GETN)
LUALIB_API int (luaL_getn) (lua_State *L, int t);
LUALIB_API void (luaL_setn) (lua_State *L, int t, int n);
#else
#             (static_cast<int>(lua_objlen(L, i)))
#define luaL_setn(L,i,j)        ((void)0)  /* no op! */
#endif
```

which Xcode still reports as an `Invalid processing directive`.

Should I be building the master branch, or is there some other OS X-specific branch?

**Comment by madmaxoft** [comment]
The `PolarSSL` project has renamed itself to `mbedTLS`, perhaps that needs changing (but it should be handled automatically by cmake - which is what happens when you open in xcode, I guess)

What is the exact error message? Can't really help you much without it.

There is no OSX-specific branch, `master` should build equally fine on all supported platforms. The only problem is, none of the core devs have a Mac to test :P

**Comment by SphinxC0re** [comment]
Oh, I have. :smile: I bought one just for testing on OS X. What version is your cmake? Did you install it with brew?

**Comment by benton** [comment]
When I open `Cuberite.xcodeproj` and try to build it in Xcode, there are only four errors: 

Xcode reports: `Use of old-style cast` 4 times for `Bindings/LuaChunkStay.cpp`. Here are the four lines that produce the casting error:

    int NumChunks = luaL_getn(L, a_ChunkCoordTableStackPos);
    ....
    int NumCoords = luaL_getn(L, -1);
    ...
    int ChunkX = luaL_checkint(L, -2);
    int ChunkZ = luaL_checkint(L, -1);

As you can see, these are produced by the macros `luaL_getn` and `luaL_checkint`. I tried to change these macro definitions to comply with the `static_cast` idiom as I described above, but incorrectly I fear. I'm not a C++ programmer, an Xcode user, or even really an OS X user -- I mostly run Ubuntu on my work-issued MacBook, and I'm trying to compile this software for someone else (My own Minecraft server is powered by Linux Cuberite running in a Docker image on ECS!). Nonetheless, I thought I'd give it a shot.

I'm using cmake 3.4.1 as installed by homebrew, and the current Xcode (7.2) with the older 10.10 SDK still installed at `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk`. So I'm pretty sure the cmake step is working OK.

**Comment by benton** [comment]
Update: a command-line build of the project, started with `xcodebuild -project Cuberite.xcodeproj`, produces the same errors:

        /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:43:18: error: use of old-style cast [-Werror,-Wold-style-cast]
                int NumChunks = luaL_getn(L, a_ChunkCoordTableStackPos);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:7:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.h:12:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaState.h:30:
        /Users/benton/projects/cuberite/src/../lib/lua/src/lauxlib.h:22:34: note: expanded from macro 'luaL_getn'
        #define luaL_getn(L,i)          ((int)lua_objlen(L, i))
                                         ^    ~~~~~~~~~~~~~~~~
        /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:81:18: error: use of old-style cast [-Werror,-Wold-style-cast]
                int NumCoords = luaL_getn(L, -1);
                                ^~~~~~~~~~~~~~~~
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:7:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.h:12:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaState.h:30:
        /Users/benton/projects/cuberite/src/../lib/lua/src/lauxlib.h:22:34: note: expanded from macro 'luaL_getn'
        #define luaL_getn(L,i)          ((int)lua_objlen(L, i))
                                         ^    ~~~~~~~~~~~~~~~~
        /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:93:15: error: use of old-style cast [-Werror,-Wold-style-cast]
                int ChunkX = luaL_checkint(L, -2);
                             ^~~~~~~~~~~~~~~~~~~~
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:7:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.h:12:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaState.h:30:
        /Users/benton/projects/cuberite/src/../lib/lua/src/lauxlib.h:104:29: note: expanded from macro 'luaL_checkint'
        #define luaL_checkint(L,n)      ((int)luaL_checkinteger(L, (n)))
                                         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~
        /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:94:15: error: use of old-style cast [-Werror,-Wold-style-cast]
                int ChunkZ = luaL_checkint(L, -1);
                             ^~~~~~~~~~~~~~~~~~~~
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.cpp:7:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaChunkStay.h:12:
        In file included from /Users/benton/projects/cuberite/src/Bindings/LuaState.h:30:
        /Users/benton/projects/cuberite/src/../lib/lua/src/lauxlib.h:104:29: note: expanded from macro 'luaL_checkint'
        #define luaL_checkint(L,n)      ((int)luaL_checkinteger(L, (n)))
                                         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~
        4 errors generated.

**Comment by liu1700** [comment]
![s](https://cloud.githubusercontent.com/assets/6064238/23494018/f8d67628-ff4a-11e6-9723-81bf21719a3d.png)

this might work，but here comes another error

~/cuberite/lib/TCLAP/include/tclap/ArgException.h:59:27: Dynamic exception specifications are deprecated

**Comment by bearbin** [comment]
Closing as stale, and Cuberite can now be built on modern OSX anyway.
