### ISSUE TITLE
cParsedNBT malformed file handing.

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#2756]
How should we handle a malformed NBT file? At the moment we have an assert for an invalid tag that is easily reached by a malformed file, but some invalid files only set the invalid flag.

Should we log the fact the file is malformed? If so at which log level?

Should we assert or abort?

**Comment by worktycho** [comment]
I think we should log a warning, set the invalid flag, and return.

**Comment by madmaxoft** [comment]
I think `cParsedNBT` itself should not log anything, it should quietly fail and set an error flag, and whoever called it should handle the situation - log a warning, abort the server, or silently ignore the problem, whatever. For this, it would be nice to have a detailed error message from `cParsedNBT`.

**Comment by worktycho** [comment]
So in addition to IsValid(), we should also have a getErrorMessage() function which returns what actually went wrong.

**Comment by madmaxoft** [comment]
Yes, that's the best.

**Comment by tigerw** [comment]
I find functions like GetLastError strange, probably because it seems like reusing one variable for multiple messages. Just saying.

**Comment by worktycho** [comment]
But there can only be one error per instance in this case, because each instance parses one file.

**Comment by tigerw** [comment]
I know, I know, but it just seems wrong and unsatisfactory that a message almost becomes not local to the procedure that generated it, but global, and that you can literally 'get' a message before there is even an error.

**Comment by worktycho** [comment]
The only alternatives are creating some form of either monad, or using exceptions. I know we can't use exceptions due to performance issues, so an either monad it would have to be.
