### ISSUE TITLE
Spawnpoint

### ISSUE THREAD

**Issue by methodds** [cuberite/cuberite#2762]
Hi,

no matter how often I create a new world, I always get the error "Did not find an acceptable spawnpoint. Generated a randowm spawnpoint position..". I am using the latest Windows version of Cuberite. Can you help me out please?

**Comment by Seadragon91** [comment]
Yes this message is confusing, but okay. The best would be to change it.
It means that a safe spawn point haven't been found at 0 64 0 and then the server it tries to find a better spawnpoint by increasing y.

**Comment by Seadragon91** [comment]
Forgot to mention, there is a rare deadlock around, you can see it, if the server doesn't show the message `Startup complete, took xxx ms`. If you have that problem, you will need to kill Cuberite. Start it then again, then it should work.
