### ISSUE TITLE
Tall grass glitch makes freshly placed block appear twice in client.

### ISSUE THREAD

**Issue by evotopid** [cuberite/cuberite#2763]
This might be a dupe of #2401 since it's also about issues with tall grass blocks altough the other issue seems to be more about protocol issues.
1. (I think this is what #2401 is about to some extent) if you destroy the upper (or lower) block of tall grass or try to place a second tall grass block ontop of another a flower drops.
2. You can actually dupe blocks using this method. Hold a block in hand and right click on the upper block of the tall grass, the block will be placed twice. (One block replacing the tall grass, one block being placed in front of that.) I tried this in creative and survival mode both having the same issue so it's an actual issues for survial servers.

**Edit:** Actually you can also right click on the lower of the two blocks to reproduce the duping issue.

**Comment by madmaxoft** [comment]
I think only one of those blocks are actually registered by the server, the other one is only client-side and should disappear when you log out and back in, right?

**Comment by evotopid** [comment]
You are right, it's a client issue and they dissappear after being placed. I am kind of sorry I don't know anymore what made me think I actually duped the block yesterday. *facepalm*

I think the issue is that vanilla behaviour is to replace the selected grass block but Cuberite actually treats it as a solid block and places its block in front of it so the client gets sent back from the server that there is now a new block in front of the old grass (because it actually is on the server) while the client also believes the grass block was replaced with the new block therefore showing the same block twice.

**Comment by SafwatHalaby** [comment]
> If a block falls in the forest and no server is around to hear it, does it make a sound?

@madmaxoft Here is what precisely happens.

#### Initial state
![2015-12-17_13 26 38](https://cloud.githubusercontent.com/assets/5030488/11868740/ccf0ec70-a4c2-11e5-9963-7a518bbdf8a3.png)

#### After placing blue block at the bottom part of the bush
![2015-12-17_13 26 46](https://cloud.githubusercontent.com/assets/5030488/11868750/df0ab1c0-a4c2-11e5-8575-279eeb80b556.png)

#### After a logout and re-login
![2015-12-17_13 26 38](https://cloud.githubusercontent.com/assets/5030488/11868757/e71b336c-a4c2-11e5-8a68-30336048fe56.png)

**Comment by SafwatHalaby** [comment]
I had initially attached the wrong screenshots. This is fixed now.

**Comment by madmaxoft** [comment]
This is still an issue that needs to be fixed in Cuberite, so that the block placement matches the client.

**Comment by peterbell10** [comment]
This was fixed by #3826.
