### ISSUE TITLE
Chunk generator very slow in biome Roofed Forest

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2766]
I have the problem if I enter a biome with Roofed Forest, the fps drops from 60 below 10. Also the chunk generator is slow, there.

Example seed: 19477766
Coord: -50 85 -70

![2015-12-17_20 22 16](https://cloud.githubusercontent.com/assets/14818618/11879623/c9f968aa-a4fc-11e5-8232-3a097cc4fa0b.png)

Please test this seed.

**Comment by madmaxoft** [comment]
I expect this to be caused by way too many leaf-block updates.

**Comment by Seadragon91** [comment]
Used worldedit to test that with the leaves, yes that could be it.

**Comment by worktycho** [comment]
The algorithm used for handling leaf decay checks is very inefficient.

If we could improve it to avoid rechecking blocks it would probably improve efficiency.

**Comment by LogicParrot** [comment]
The algorithm is not the bottleneck, it's the amount of times the algorithm is executed that's the problem. #3149 resolves this, but after visiting an affected area, it can take a couple of minutes for existing worlds' leaf metas to be properly sit, and during that time there would still be some performance issues.
