### ISSUE TITLE
Mob code too slow

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#277]
The new mob code (cMobCollector et al) is very slow, with debug versions of MCServer the ticks take as long as 1 sec each. This is not acceptable.

std::set and std::list are not good structures, we need more speed!

**Comment by tigerw** [comment]
It's still kinda slow there, probably could do with some optimisation.

**Comment by SafwatHalaby** [comment]
@SphinxC0re I prefer to assign myself to things I'm actually working on, this allows others to actually work on things I'm not working on. So not every AI thing should be auto-assigned to me.

**Comment by LogicParrot** [comment]
I is possible fact that monsters in unloaded chunks are not destroyed properly amplifies this issue. #2973
