### ISSUE TITLE
Spawn point generation not working correctly

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2781]
This is about the spawn generation, at startup of the server.

~~I debugged this and here [GetHeight()](https://github.com/cuberite/cuberite/blob/master/src/World.cpp#L676) returns always 0. The chunk is not null and is valid. Here [GetHeight()](https://github.com/cuberite/cuberite/blob/master/src/World.cpp#L653) returns the correct y coordinate.~~

Edit: GetHeight works okay.

**Comment by worktycho** [comment]
That would suggest a non-loaded heighmap. If you're using a debugger, could you check if cChunk::m_Heightmap has any values?

**Comment by Seadragon91** [comment]
Okay height map is okay. The problem is on this line:
`static const int LowestSpawnPoint = static_cast<int>(HighestSpawnPoint / 0.5f);`

`0.5f` should be `2.0f`. HighestSpawnPoint will be the value from `GetHeight`, example 64. What will be lowest value then? Yes 128.

Now my thought, does this fixes also the deadlock? The problem should be the for loop.

**Comment by Seadragon91** [comment]
Okay, I generated a few more worlds, still something not fully correct. The spawn generation code should be fully rechecked.

**Comment by worktycho** [comment]
If Lowest is greater than Highest then the loop won't execute.

**Comment by worktycho** [comment]
I think we need to switch the division to a multiply.

**Comment by Seadragon91** [comment]
Yes, that works...

**Comment by Seadragon91** [comment]
Found one more place with wrong division, also HighestSpawnPoint not really good. Working on a fix.
