### ISSUE TITLE
Mob path recalc acting weird

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2784]
~~Possibly~~ introduced in https://github.com/cuberite/cuberite/commit/2c0ca0b4c3152765f97e9bb3894b55694e979f32

Mobs are sometimes going to the wrong spot (Looks like a spot they have been in before). More info soon.

**Comment by SafwatHalaby** [comment]
I confirm ihttps://github.com/cuberite/cuberite/commit/2c0ca0b4c3152765f97e9bb3894b55694e979f32 is the cause.

**Comment by SafwatHalaby** [comment]
@worktycho can you detect any accidental logic changes? This shouldn't have changed the logic at all.

**Comment by SafwatHalaby** [comment]
One problem found so far: You did not reset m_PathPoints.
Maybe we should come up with a less error prone way to do this.

**Comment by tigerw** [comment]
Don't reuse cPath, recreate it?

**Comment by SafwatHalaby** [comment]
> Don't reuse cPath, recreate it?

That's exactly what it used to be like before this commit.

Is there a way to easily recreate `cPath` when it is stored in `cPathFinder` not as a pointer?

**Comment by worktycho** [comment]
Not really.

**Comment by SafwatHalaby** [comment]
One could use `Placement New` and manually call the destructor.

Or we could just revert this and be content with the unique_ptr we had.
