### ISSUE TITLE
PathFinder performance around fences

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2792]
`cPath::GetCell` will recursively call itself if you have stacked fences on top of one another. This can cause a performance bottleneck around huge fence-based structures.

**Comment by worktycho** [comment]
Provide  an optional parameter to say if you're reading or writing? The you don't need the recursive IsSolid call if you're just going to overwrite the solidity.

**Comment by SafwatHalaby** [comment]
The current way fences are handled is adhoc and unclean. I've refactored that (and a lot of other stuff) in a soon to be made PR. Basically, the new way is (if AIRBLOCK and FENCE BELOW) { ..etc.. }

**Comment by SafwatHalaby** [comment]
#2795 resolves this.
