### ISSUE TITLE
Jenkins freebsd builds failing 

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#2804]
Bearbins FreeBSD builds are failing due to libevent failing to detect the fixed size types.

**Comment by worktycho** [comment]
@bearbin: Could you set up FreeBSD builds to do prs and statuses?

**Comment by bearbin** [comment]
I should be able to, but I would want the main build to be stabilised first so all prs dont mysteriously fail.

**Comment by SphinxC0re** [comment]
Builds are working now
