### ISSUE TITLE
Mojang session-server issue

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2805]
SecureRequest: Can't connect to sessionserver.mojang.com: SSL handshake failed: -0x2700

I'm getting these warnings/error messages a lot in the server log now.

**Comment by worktycho** [comment]
Are you using a version before 2b27bf9? If so update to the latest version.

**Comment by bearbin** [comment]
This was an issue fixed yesterday. Have you downloaded the latest version of Cuberite?

Also, if you aren't subscribed to the [newsletter](https://newsletter.cuberite.org/subscribe.htm) please do. You can get informed of important fixes and issues.

**Comment by jammet** [comment]
My apologies. I've literally notices it was fixed 5 minutes after posting this. ;) Wanted to silently close it and save some grace. But it was already noticed! ;)
