### ISSUE TITLE
Portal usage cooldown

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2812]
Currently, it is very easy to get stuck in a Teleport loop between the Nether and the Overworld. Portal teleportation should have a ~5 second cooldown to prevent that.

**Comment by NiLSPACE** [comment]
I thought it had that already. I believe @tigerw implemented the portals.

**Comment by tigerw** [comment]
There should; evidently the logic isn't working correctly :/

**Comment by NiLSPACE** [comment]
It was always working for me. Perhaps it's OS dependent?

**Comment by SafwatHalaby** [comment]
It's not working on @jammet 's server too. So this isn't something I did ;)

**Comment by mathiascode** [comment]
Fixed in recent versions of Cuberite.
