### ISSUE TITLE
compile.sh no longer works on Centos

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2823]
See [this](http://forum.mc-server.org/showthread.php?tid=2242).

**Comment by LogicParrot** [comment]
Can anyone test `compile.sh` on Centos?

**Comment by Schwertspize** [comment]
I can

**Comment by LogicParrot** [comment]
Thank you. It should preferablly be tested with the standard repos, without any change to the package sources like Chrobione did in the forum post.

**Comment by LogicParrot** [comment]
I suspect it will work on centos 7, but will fail on centos 6.x because of an old gcc. @cuberite/core-team what minimum version clang do we need?

**Comment by Seadragon91** [comment]
In COMPILING.md is 4.8 for gcc/g++ the minimum version.

**Comment by worktycho** [comment]
4.9 is usually recommended. 4.8's c++11 support is a bit buggy.

**Comment by LogicParrot** [comment]
Thanks. But I asked about clang. If the clang version in the Centos 6.x repo is good enough for us, and gcc isn't, then I can make the script use clang instead of gcc if it detects centos 6.x.

**Comment by worktycho** [comment]
clang will work on 3.0 or greater I believe. But >=3.4 is better tested.
