### ISSUE TITLE
SSL assertion

### ISSUE THREAD

**Issue by Gargaj** [cuberite/cuberite#2826]
I've been getting assertion errors when trying to log in to my local debug server; I've traced the problem back to ```cMojangAPI::SecureRequest``` and added some debug info:
```
[b58cae9c|16:59:00] Trying to authenticate user Gargaj
[b58cae9c|16:59:00] [cBlockingSslClientSocket] Socket connected
[b58cae9c|16:59:00] [cBlockingSslClientSocket] Send (184)
[b58cae9c|16:59:00] [cBlockingSslClientSocket] Receive (1024)
[c966d884|16:59:01] [cBlockingSslClientSocket] Socket disconnected
[b58cae9c|16:59:01] [cBlockingSslClientSocket] Receive (1024)
```
What I suspect (guess) happens is that the SSL socket connects, then sends the request, reads some data back, after which the server drops the connection (which triggers ```cBlockingSslClientSocketLinkCallbacks::OnRemoteClosed```), the socket becomes disconnected, but ```cMojangAPI::SecureRequest``` doesn't know that and tries to read from it again.

Unsure how to fix it.

**Comment by madmaxoft** [comment]
Actually, now that I look at your log output, this seems like a problem in LibEvent - it first says the socket was closed, but then suddenly more data arrives on that socket.

**Comment by Gargaj** [comment]
The number in the parentheses isn't the incoming data size, it's the buffer size; I don't know if there's more data on the socket because the function asserts before it could actually try to read.

**Comment by madmaxoft** [comment]
Can you re-test with latest master (after #2831 was merged)? I believe it has been fixed.

**Comment by Gargaj** [comment]
master seems to work 10 out of 10 times
