### ISSUE TITLE
Spectator mode teleportation doesn't work

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#2834]
Whenever you try to teleport to another player using the teleportation feature in spectator mode (while in spectator mode, press any number to bring up the inventory, then select which player to teleport to), you get disconnected with the following message:

"Unknown [C->S] PacketType: 0x18"

**Comment by Seadragon91** [comment]
See this issue #1772. Spectator mode is not really existent.

**Comment by tigerw** [comment]
A new packet named “Spectate”...
