### ISSUE TITLE
Segfault cTCPLinkImpl::EventCallback

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2839]
I had yesterday a few segfaults at this position [TCPLinkImpl.cpp:L265](https://github.com/cuberite/cuberite/blob/master/src/OSSupport/TCPLinkImpl.cpp#L265). The windows crashdump that I have, shows that Self was empty.

Tried to reproduce it in a debug build, had no luck so far.

**Comment by Seadragon91** [comment]
Started the server and wanted to join it, the server crashed. Have attached the crashdump. Build id [220](https://builds.cuberite.org/job/Cuberite%20Windows%20x64%20Master/220/)

[Cuberite.exe.3192.dmp.zip](https://github.com/cuberite/cuberite/files/90314/Cuberite.exe.3192.dmp.zip)

**Comment by Seadragon91** [comment]
I get this crash now 1 of 4 times on login to the server.

**Comment by Seadragon91** [comment]
Would be enough to check if [`Self`](https://github.com/cuberite/cuberite/blob/8fc9cfa41101b6b99cbf1dda21be1a22980aab0f/src/OSSupport/TCPLinkImpl.cpp#L216) is nullptr and then only return?
The value of `a_What` is 0x11.

**Comment by madmaxoft** [comment]
Not really, this is a much deeper issue, because `Self` is supposed to be a `shared_ptr` and there's already a check for an empty one, so this really means we've hit undefined behavior somewhere along the way, most likely due to a data race.
