### ISSUE TITLE
Disconnected for "Bad compression"

### ISSUE THREAD

**Issue by mathias-github** [cuberite/cuberite#2841]
Whenever you add much data to an item, you get disconnected for "Bad compression". I tried to add  more than 14 different enchantments to an item using a command, but got disconnected with this error. The same error also appeared when pasting a large command in a command block.

**Comment by madmaxoft** [comment]
This is the item definition in player.json file that is supposed to trigger the error:
```
     {
         "Count" : 64,
         "Health" : 0,
         "ID" : 12,
         "RepairCost" : 0,
         "ench" : "0=32767;1=32767;2=32767;3=32767;4=32767;5=32767;6=32767;7=32767;8=32767;16=32767​;17=32767;18=32767;19=32767;20=32767;21=32767;32=32767;33=32767;34=32767;35=3276​7;48=32767;49=32767;50=32767;51=32767;61=32767;62=32767;"
      },
```
