### ISSUE TITLE
Grass spreads underground

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#2850]
![2016-01-09_22 13 31](https://cloud.githubusercontent.com/assets/1160867/12218483/ce82f496-b720-11e5-880f-c2ec013be893.png)

This only happens when it's day (not with torches). You can see it happening by executing a simple script like this:
```lua
function OnBlockSpread(...)
	print(...)
end

cPluginManager:AddHook(cPluginManager.HOOK_BLOCK_SPREAD, OnBlockSpread)
```

**Comment by madmaxoft** [comment]
So that is the cause of all those blockchange packets

**Comment by LogicParrot** [comment]
@madmaxoft that is not the only cause though. See #3110
