### ISSUE TITLE
Tamed wolf doesn't protect owner

### ISSUE THREAD

**Issue by JuliB15** [cuberite/cuberite#2854]
"*Tamed wolves will attack players or mobs that injure their owner*" (http://minecraft.gamepedia.com/Dog) They don't protect their owner. Is it possible to fix that?

**Comment by LogicParrot** [comment]
@cuberite/core-team  I could enhance the wolves beyond vanilla behavior. Would that be a good idea?

Attack mob when:
1. Owner is attacked (vanilla)
2. Mob is approaching player and is about to attack (e.g. less than 5 waypoints left)
3. Skeleton is about to shoot player.

**Comment by LogicParrot** [comment]
(this looks good to me regardless of the enhancement proposal, the potential enhancements would be in a seperate PR )

**Comment by NiLSPACE** [comment]
I don't think we should implement unexpected behavior if possible. Perhaps others disagree.

**Comment by LogicParrot** [comment]
Implemented vanilla wolf behavior for now.
Tamed wolves will now defend the owner and help the owner attack mobs.

**Comment by JuliB15** [comment]
Thx!!

**Comment by LogicParrot** [comment]
Yw :)
#2882 Should enhance wolf behavior significantly, once merged.
