### ISSUE TITLE
Cannot exit gracefully after start server with -d parameter

### ISSUE THREAD

**Issue by dogtopus** [cuberite/cuberite#2856]
Cuberite seems to ignore SIGTERM and SIGINT after started in daemon mode and cannot be shutting down gracefully

**Comment by LogicParrot** [comment]
#1979 related?

**Comment by worktycho** [comment]
Jut to confirm, your sending the signal directly to the pid, and not through a shell?

**Comment by dogtopus** [comment]
@worktycho
Yes, I tried both `kill $PID` and `killall Cuberite`

**Comment by LogicParrot** [comment]
Fixed in #2901
