### ISSUE TITLE
Slime block physics wrong

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2866]
Usually when you stand on a slime block and jump, it catapults you up further into the air. Or when you use a slime block and piston it upwards, it would launch you really high into the air.

Currently, once you step on slime blocks, you are slowed down to a crawl, and if you are trying to jump on it, most of the time you can't. Also, a piston beneath a slime block doesn't send you flying anymore, you fall off to the side, instead.

**Comment by pwnorbitals** [comment]
The behaviour looks correct now. This issue can probably be closed.
