### ISSUE TITLE
Breeding has stopped working

### ISSUE THREAD

**Issue by Drahoslav7** [cuberite/cuberite#2879]
Breeding has stopped working on my server after update few days ago.
When I feed pair of cows/sheeps/chickens it will show hearts, gives xp, but no baby animal is born.
I think it might be caused by #2863.

**Comment by LogicParrot** [comment]
Definitely seems related. #2877 should fix it.

**Comment by Drahoslav7** [comment]
I confirm that it's working now, good job.
