### ISSUE TITLE
SkyLight values are wrong.

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2890]
It seems `cWorld::GetBlockSkyLight` and `cChunk::GetSkyLight` both return either 0 or 15, never anything in between. This is why spiders are not working properly and are always agressive.

**Comment by LogicParrot** [comment]
It seems `cWorld::GetBlockLight` and `cChunk::GetSkyLight` both return either 0 or 15, never anything in the middle. This is why spiders are not working properly - they're always agressive.

**Comment by worktycho** [comment]
This is either a problem with the lighting code, or cChunkData. Does the cChunkData::m_Segment::m_BlockLight arrays contain anything?

**Comment by tigerw** [comment]
You may be misunderstanding the meaning of sky light. Sky light is determined by a position's distance from the nearest position that is in full view of the sky. It is not dependant on the time of day, which I assume you wish spider behaviour to be based upon.

For lighting based on time, consider the functions named somethingsomethingTimeAdjustedLight in cWorld and cChunk.

**Comment by LogicParrot** [comment]
@tigerw I see. Thanks for explaining this. I'll try it. What about `cChunk::GetBlockLight`?, if I remember currectly, it also returned values which made no sense to me.

**Comment by LogicParrot** [comment]
Also, could you explain the relationship between `cWorld::IsChunkLighted`, `cWorld::QueueLightChunk` and the above functions? Most of them are not well documented, or not at all.

**Comment by LogicParrot** [comment]
`cChunk::GetSkyLight` is behaving exactly as you describe.
I figured `cChunk::GetBlockLight` is for non-natural lights only.
I will document these two functions.

I still do not understand why `cWorld::IsChunkLighted`, `cWorld::QueueLightChunk` exist at the current spider code (but not at, say, the current zombie burning code).

**Comment by worktycho** [comment]
Unless ischunklighted returns true, the blocklight and skylight functions will just return zero. 

Queuelightchunk adds a chunk to the lightning queue, so that at some point in the future getblocklight and getskylight will return meaningful values.
