### ISSUE TITLE
Player stays online when pressing cancel while joining

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#2893]
When you join a server, but quickly press cancel the player can stay online. Here is a video:
https://www.youtube.com/watch?v=mxBWZzqAXLg
I'm sorry for the long wait at the player page, I was refreshing, but that wasn't really visible.

**Comment by Seadragon91** [comment]
I can this reproduce this, too. There are already issues with that problem, but cannot find them right now.

**Comment by NiLSPACE** [comment]
I remember that there was an issue where I'm suddenly disconnected but the server says I'm still online. It's very possible that these issues are related.
