### ISSUE TITLE
Lua: Problems while connecting to secured server

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#2902]
There are problems when connecting to a secured server. To replicate this you can enable the NetworkTest plugin and use `net sclient`

The plugin does connect with the server, but doesn't receive any data.

**Comment by NiLSPACE** [comment]
Okay, suddenly `net sclient` works perfectly now, but when I use `net sclient raw.githubusercontent.com` it doesn't work. 

I did change the header to `GET /cuberite/WorldEdit/master/Info.lua HTTP/1.0\r\nHost: " .. Host .. "\r\n\r\n` in the code, but when that also didn't give me any results I changed it back to `GET / HTTP/1.0\r\nHost: " .. Host .. "\r\n\r\n` and it still didn't work. 

Also, when I tried it on the gallery server's webadmin the connection is closed after one second without receiving any data.

**Comment by Seadragon91** [comment]
Could it also possible, that there is something not correct in polarssl?

**Comment by NiLSPACE** [comment]
It's possible, but wouldn't that mean that the authenticator shouldn't be working?

I also found that the faster my internet is the more chance I have in successfully checking my WorldEdit version.

**Comment by Seadragon91** [comment]
I have setup a https server with python and I was never be able to download a single file.

**Comment by NiLSPACE** [comment]
Interesting. I noticed that sometimes I do receive the Info.lua file after a long time and thus checked if the file is perhaps slowly coming in, but what actually happened is a rather large silence and then everything comes. Not at once though, if you look at the file you see it logs once every X lines.
[LOG_1453588248.txt](https://github.com/cuberite/cuberite/files/102066/LOG_1453588248.txt)

**Comment by madmaxoft** [comment]
I've merged a PR that seems to alleviate some of these problems, but still not completely.

**Comment by NiLSPACE** [comment]
Checking if there is a newer version works 100% of the time now, but downloading the zip still doesn't work.

**Comment by NiLSPACE** [comment]
Ooh, I've added `Connection: Keep-alive` and now it actually downloads the zip file properly.

**Comment by madmaxoft** [comment]
I believe this has been fixed, hasn't it?

**Comment by NiLSPACE** [comment]
Yes, it's working perfectly now. 😀
