### ISSUE TITLE
Burning/baking process slightly slower than in vanilla

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2904]
A few people pointed out that melting iron, baking food and all that -- it all seems to be a few seconds slower than vanilla. Looked at it myself and yes, I think they're right. This is a lot slower than what is normal. Making 1 charcoal takes 12 seconds on Cuberite at the moment, and I counted to 10 on vanilla.

**Comment by Bond-009** [comment]
I just tested this and it takes 10 seconds to melt something in Cuberite.
`Each smelting operation takes 10 seconds.`

**Comment by mathiascode** [comment]
Can't reproduce. This shouldn't be an issue anymore.
