### ISSUE TITLE
Strange achievement behavior when crafting with table of another user

### ISSUE THREAD

**Issue by apfohl** [cuberite/cuberite#2911]
I discovered a strange behavior in the achievement system. When I try to follow the achievements and craft something on a crafting table that has been created by another player, I don't get the achievements. When I craft the thing on a crafting table created by me, everything works fine.

Could you please take a look at this?

**Comment by apfohl** [comment]
I tried a little more. When I tried to craft the wooden sword to get the achievement, it was only possible, when no other crafting table is build but mine.

**Comment by bearbin** [comment]
If you could give me any more information about this bug it would be good. Everything worked fine for me.

There is a prerequisite for the sword achievement that you must have crafted a table previously, so maybe that was the issue?

**Comment by apfohl** [comment]
No, sorry. I was not able to reproduce this bug.
