### ISSUE TITLE
A block of snow created by 8 tiles can allow for snow to be temporarily placed in impossible places.

### ISSUE THREAD

**Issue by BitOfAByte** [cuberite/cuberite#2921]
This one is a little bit hard to explain, but if you create a block of snow by stacking up 8 tiles and then click on the side it will temporarily place a tile there. If you're in survival it will also take a tile out of your inventory.

This does not require the torches in the picture.

![2016-01-30_02 20 43](https://cloud.githubusercontent.com/assets/6497430/12694335/970717c6-c6f8-11e5-9d85-7682efcc3748.png)

When testing this we could only reproduce this with 2 out of the 3 people who tried this.

**Comment by peterbell10** [comment]
Fixed by #4022.
