### ISSUE TITLE
Snow tiles can be placed in water

### ISSUE THREAD

**Issue by bvanrosendale** [cuberite/cuberite#2922]
The snow tile can be temporarily be placed inside of a water block. This also removes the water block that was there. This does not happen in regular minecraft. (I also found a weird issue in vanilla where you can place snow in water by clicking on the side and it places it 1 block away from the side.)

**Comment by tigerw** [comment]
Tested in 1.12.2 and 1.16.5, could place thin snow layers in both water source and flowing water blocks; the snow was replaced a tick later. Please reopen if I tested the wrong thing!
