### ISSUE TITLE
Horses do not react to being tamed properly.

### ISSUE THREAD

**Issue by BitOfAByte** [cuberite/cuberite#2924]
Before a horse is teamed it can still be controlled by the player. When it is being controlled it can move much faster than it should be able to, as well as looking towards one point at all times, not the direction you are moving. It will buck off correctly.

After a few tries the horse will no longer buck you off, I think this is where the horse should be tamed but the particles do not appear. The horse moves in the same way as it did before.

After the horse reaches the "tamed" point and you dismount any attempts to mount the horse will result in the horse not being mounted and the camera being pointed in the direction that the horse is facing.

See this video to explain further.

https://youtu.be/3ERYeLDj5VI?t=7s

**Comment by LogicParrot** [comment]
Horses are messy. Horse beeding reference: https://github.com/cuberite/cuberite/pull/2696
