### ISSUE TITLE
Mobs die too fast in lava

### ISSUE THREAD

**Issue by BitOfAByte** [cuberite/cuberite#2925]
When a mob is spawned in lava and cannot escape it dies too quickly. A creeper should take 5 instances of damage from lava and then die, but it actually dies in 4. A zombie should take 6 instances of damage but it too dies in 4.

**Comment by BitOfAByte** [comment]
Seems to be related to #2197.

**Comment by LogicParrot** [comment]
I closed #2197 because this is more general.
