### ISSUE TITLE
Question about the software

### ISSUE THREAD

**Issue by TheDiamondYT1** [cuberite/cuberite#2938]
Hi, I see you build with CMake. How did you begin the project? An IDE? A command? I know how to build with CMake but how do I start the project, I'm assuming as CMake is for Linux I can't use visual studio to create the project.

**Comment by bearbin** [comment]
Have you read the compilation instructions?

https://book.cuberite.org/#compilinglinux

**Comment by LogicParrot** [comment]
I think the question is about importing the project to Visual Studio, and not about compiling.

**Comment by tigerw** [comment]
On Windows, the instructions provided will generate a VS solution file.

**Comment by TheDiamondYT1** [comment]
:+1:
