### ISSUE TITLE
Minecarts don't go around corners

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2945]
When Minecarts go straight forward, there's no problem, but going around corners did not work at all, testing it today. The cart just stops.

**Comment by rekuen** [comment]
Is working fine for me with player inside or not.

**Comment by jammet** [comment]
Maybe it's just because my carts are so slow. How do you get these powered rails to work? They don't do anything for me at all. In fact they just stop the minecart completely, on or off, regardless.

I just think the corners slow down the cart more than I remember. Nevermind then, I'll close this issue.

But again, why do powered rails work for you and not for me? It doesn't make any sense.

**Comment by rekuen** [comment]
Did you try the latest build from source? powered rails always have been working for me, but I update my server daily. For me just like vanilla, put the rail, put a redstone torch next to it to power it and it should work.

**Comment by rekuen** [comment]
My carts are also slow as hell, they don't accelerate for now, regular ones at least.

**Comment by jammet** [comment]
Yeah, I update all the time :). Generally, *some* powered rails seem to
work while others don't. And I cannot start the ride by placing a cart on a
powered rail that's currently not enabled, throw a switch and "zoooom there
it goes ...". Everything is really slow, and when it's not carts have a
tendency to just fly off the tracks (even on a completely level circuit).
It's really difficult to even push a cart so that it'll go on to some
powered rails, because most of the time it won't budge or go the wrong
direction, too. Not sure if it's intentional but sitting inside a cart, you
can propel it forward very very slowly just by pressing the forward key.
That's the only way right now, for me to properly test things because the
cart never really gets momentum with just pushing manually. :)

So yeah, the powered rails give me a really hard time here. I got them to
work, but the accleration is way too slow compared to vanilla, at this
point. If we had working physics, it would have been cool if I could
recreate old-school style accelerators for carts, if you remember those
perpetual constructions consisting of 2 carts colliding sideways with each
other.

Regardless, this really needs work :).
