### ISSUE TITLE
Disembarking Minecarts: can cause player desync/invisiblity among players

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#2948]
This might be closely tied to players being positioned in awkward positions upon disembarking. Players riding a cart and disembarking will sometimes not be visible to other players anymore, or will be partially visible (and won't show the other player the real position any longer). I've seen players walk right through walls, because the player was shown in a different position from where they really were at the time (one or two blocks off).

**Comment by tigerw** [comment]
Tentatively merging with #3258.
