### ISSUE TITLE
Forum password change

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2950]
Now that we have https, I advise all users, especially privileged users, to change their forum password as a precaution. This is not a Cuberite issue but I thought it's worth putting here.

Not mandatory, but highly advised. Tick your name once you do it :)
- [x] @bearbin  
- [ ] @FakeTruth 
- [x] @LogicParrot
- [x] @madmaxoft
- [x] @mathias-github  
- [x] @NiLSPACE
- [x] @SphinxC0re
- [x] @Seadragon91  
- [ ] @tigerw 
- [ ] @tonibm19 
- [ ] @worktycho

**Comment by LogicParrot** [comment]
Now that we have https, I advise all users, especially privileged users, to change their forum password as a precaution. This is not a Cuberite issue but I thought it's worth putting here. I'll close it after some time.

Not mandatory, but highly advised. Tick your name once you do it :)

- [ ] @bearbin  
- [ ] @FakeTruth 
- [x] @LogicParrot
- [ ] @madmaxoft 
- [ ] @NiLSPACE
- [ ] @SphinxC0re
- [ ] @Seadragon91   
- [ ] @tigerw 
- [ ] @tonibm19 
- [ ] @worktycho

**Comment by bearbin** [comment]
Ticked :)

A related concern would be the use of two-factor authentication on GitHub accounts. SphinxC0re and I are the only two users currently, and GH account security is a much larger issue than forum accounts.

**Comment by bearbin** [comment]
Actually, @LogicParrot and @NiLSPACE also have 2FA. Everyone else should hurry up :P

**Comment by LogicParrot** [comment]
It's worth noting that you need neither a mobile phone nor properiatary software for 2fa.
For a free phone software, use FreeOTP. ([Fdroid](https://f-droid.org/repository/browse/?fdfilter=totp&fdid=org.fedorahosted.freeotp) or [Playstore](https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp))

For using 2fa without a computer:
```
apt-get install oathtool
#now you can use:
oathtool --base32 --totp <my 2fa code> to generate a one-time code.
```

**Comment by mathias-github** [comment]
I've changed my forum password. Could someone else tick my name, since I don't have the permissions to do it?

**Comment by Schwertspize** [comment]
Actually, I don't have access but 2fa too :P 

The recommended app for 2fa is actually Google authenticator, I am using yubico authenticator, a Clone of that for my yubikey :) 

But where is the feature of 2fa if it's running in the same machine as you are accessing github WIth? If your pc gets compromised.....

**Comment by LogicParrot** [comment]
@Schwertspize You are right. It makes it less secure, but it still protects you from someone looking over your shoulder at the password. (They won't be able to type it on their own PC and log in).

**Comment by LogicParrot** [comment]
Ping @worktycho @tigerw @madmaxoft

**Comment by bearbin** [comment]
@LogicParrot Why did you close this issue?

**Comment by LogicParrot** [comment]
Sorry. I meant to de-assign myself.

**Comment by LogicParrot** [comment]
ping @tigerw
@tonibm19
@worktycho

**Comment by LogicParrot** [comment]
ping @tigerw
@tonibm19
@worktycho
