### ISSUE TITLE
Interspecies breeding is possible

### ISSUE THREAD

**Issue by Drahoslav7** [cuberite/cuberite#2957]
e.g: When I feed one sheep and one cow a little cow or sheep is born.
Cow with sheep might be somehow reasonable. But pig with chicken, that is not very natural.

**Comment by LogicParrot** [comment]
@Gargaj ;)

**Comment by LogicParrot** [comment]
The problem is that we compare them with `GetEntityType`, which returns an `etMonster` for all animals. Fix is easy, PR soon.
