### ISSUE TITLE
Update GETTING-STARTED.md

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2959]
I created a new tag. ingame-testing-needed. The name is self explanatory. ~~It is used for PRs only~~. It should be explained in "getting started" as it is great for beginners, just like the "easy" tag.

Edit: The idea is that maintainers put it on PRs, and essentially it's a "please test this, people" request. non-members can pull it, test it, and report back.

**Comment by LogicParrot** [comment]
Preferably, we should assume they don't know git well, and briefly explain how to pull the PR they'd like to test.

**Comment by Schwertspize** [comment]
@LogicParrot non-members of the project/group can't use tags.

But a git explanation would be nice

**Comment by LogicParrot** [comment]
@Schwertspize The idea is that maintainers put it on PRs, and essentially it's a "please test this, people" request. non-members can pull it, test it, and report back.

**Comment by Ajusa** [comment]
I like this idea. I would be fine with testing and uploaded video of the thing that was tested. If it speeds up development, I'll do it.
I also have a few computers to test it one and report back, so that is useful.

**Comment by LogicParrot** [comment]
Tester feedback significantly speeds up development. I'll be putting those tags whenever I can. You can keep an eye on them [here](https://github.com/cuberite/cuberite/issues?utf8=%E2%9C%93&q=label%3Aingame-testing-needed+).
