### ISSUE TITLE
Investigate teleportation loops

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2963]
Sometimes one can teleport back and fourth uncontrollably between worlds when stepping into a nether portal. There's already a code to prevent that, but it seems to be failing in some cases.

**Comment by LogicParrot** [comment]
> Then, once you have arrived in the normal world, the game will act as if you had been standing in the nether gate of that side for some time (loading time), and quite often, you are transported back before you even see the normal world. This can create an infinite loop. 
- @jammet

**Comment by LogicParrot** [comment]
Despite the fact that #3121 practically closes this by putting the player out of the teleportation range upon arrival at the destination, investigating why the prevention code did not work is still worth it.

**Comment by tigerw** [comment]
Again #3115 :P

**Comment by LogicParrot** [comment]
Oh. #3115 sounds awesome. I am in the process of checking it out. I wanted to get this temp-fixed in the meantime :)

**Comment by tigerw** [comment]
#3115 sounds like a certain developer needs to get ahold of himself and make his pull requests smaller.
