### ISSUE TITLE
Investigate unloaded chunk fall

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2964]
One can fall through unloaded chunks upon world travel, which means #2814 is incomplete.

**Comment by BitOfAByte** [comment]
I had this bug happen while teleporting to coordinates that were right next to a few other players.

**Comment by LogicParrot** [comment]
Interesting observation. Perhaps this is the problem: Chunks are already loaded server side, therefore the player is not freezed, but the chunks are not yet sent to the client, so the client falls into the ground, and since currently Cuberite trusts the client with location, the client ends up falling server side.

**Comment by LogicParrot** [comment]
Reference: #2814

**Comment by BitOfAByte** [comment]
I'm going to write up my whole experience as I remember it. Take this writing with a grain of salt because this happened a few days ago and I was not able to reproduce it.

> I was testing the way that being hit affects fall damage, so I had set coordinates in the air to teleport to. I teleported in the air with low health, and died from fall damage. I normally clicked respawn and then teleported to the coordinates where a couple people were helping me test. I did not load the world but began to fall into the earth. The people around me also saw me fall down. Somehow I returned to the spawn, either by teleporting to (0,100,0) or by using /kill. I used the same teleport command to get to the area where I had been testing and again I began to fall through the world. This happened a few times and I must have teleported back to the place I was testing 3-4 times. The chunks never loaded. I eventually left the server and re-connected and it was fixed.

**Comment by LogicParrot** [comment]
Thanks. I am going to work on this issue next.
