### ISSUE TITLE
Over-activating redstone blocks

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [cuberite/cuberite#2966]
In cuberite servers, the **redstone blocks activate adjacent full blocks strongly**. That behavior was added in vanilla snapshots lately, but **has been considered a bug** and was removed since. Please also patch that in cuberite as it has been messing up the redstone. Thanks!

**Comment by SphinxC0re** [comment]
So this is for the 1.9 milestone, am I right?

**Comment by InterplanetaryEngineer** [comment]
What do you mean by milestone? The bug already appears in the 1.8 version of cuberite though.

**Comment by Ajusa** [comment]
He is saying that Cuberite doesn't have this implemented correctly. He is also saying that one of the snapshots included it, but they dropped it as a bug, so it shouldn't happen

**Comment by SphinxC0re** [comment]
Thanks @Ajusa :smile: but I think I misunderstood this bug as a feature :laughing:

**Comment by Ajusa** [comment]
Ah, okay :D

**Comment by QUSpilPrgm** [comment]
This is fixed with #3214 for now
