### ISSUE TITLE
Tab convention

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2971]
We often get lots of whitespace in PRs because different IDEs treat tabs differently. We must establish a clear tab convention.

This PR is in fact only a one line change: https://github.com/cuberite/cuberite/pull/2969/files

**Comment by bearbin** [comment]
We already have a clear convention on tabs vs spaces, what we are really discussing is whitespace at the end of lines. I don't think we should have any, and we should bulk-update the codebase to fix all current instances. Does anybody else have a different opinion?

**Comment by LogicParrot** [comment]
No, we're discussing if empty lines in indentation blocks should be `\n` or `\t\t\t\n`.

**Comment by LogicParrot** [comment]
Edit: I misread your comment. What you said is pretty much the same.

**Comment by bearbin** [comment]
Yes, I was agreeing with you. Sorry for writing a confusing comment.

**Comment by LogicParrot** [comment]
I am also in favor of removing them. There is no sense keeping unneeded characters around.
