### ISSUE TITLE
Crash on C.H.I.P.

### ISSUE THREAD

**Issue by Ajusa** [cuberite/cuberite#2976]
C.H.I.P. is a tiny computer (think smaller faster rpi) that uses armv7. I just downloaded the binary (using the instructions on the cuberite book) and I am getting an error very quickly.
Here is a pastebin.
I will try to compile from source overnight
http://pastebin.com/WzaHarKC

**Comment by Ajusa** [comment]
Here are CHIP docs if you need more information about the hardware:
http://docs.getchip.com/#chip-hardware

**Comment by LogicParrot** [comment]
@Ajusa Try compiling instead. I think the armv7 is RaspberryPi-only. (Am I right @bearbin ?)

```
sh -c "$(wget -O - https://raw.githubusercontent.com/cuberite/cuberite/master/compile.sh)"
```

**Comment by bearbin** [comment]
Yes, the ARM build is Raspi only.

**Comment by LogicParrot** [comment]
Closing as this is not a real problem. @Ajusa please let us know if it works after you compile. That'd be the first C.H.I.P feedback :)

**Comment by Ajusa** [comment]
Ah, okay. On the Cuberite book, it made it sound like more than the rpi was supported for arm. Thanks guys! Compiling did seem to work, and the world is being generated :D
