### ISSUE TITLE
How to rank someone?

### ISSUE THREAD

**Issue by eszlarie** [cuberite/cuberite#2977]
I seem to be having trouble when I try to /rank myself in the console on my server, I did /rank (name) exactly and nothing happened, is there something im missing such as setting up these ranks that i need for permissions like an OP or admin?

**Comment by LogicParrot** [comment]
Hello. There are two ways to rank.
1. Executing `rank <player name>` from the console. Note that there is no leading slash. It is not `/rank`.
2. Using the webadmin GUI by browsing to `http://localhost:8080`.

Note that both techniques are mentioned in the [User Manual](https://book.cuberite.org/#2.1).

**Comment by LogicParrot** [comment]
I remember being confused about this myself, I'll add a note in the manual that there shouldn't be a leading slash.

**Comment by LogicParrot** [comment]
Done. @eszlarie does this resolve your issue?

**Comment by eszlarie** [comment]
No sadly as I do not know what to use for the username and password on http://localhost:8080, and the rank (player) does not work!

**Comment by eszlarie** [comment]
it says invalid rank

**Comment by eszlarie** [comment]
also I would like to know how to add ranks and my personal permissions for each rank.

**Comment by NiLSPACE** [comment]
Look at this to configure the webadmin: https://book.cuberite.org/#2.3

Also, the rank command is case sensitive.

Adding ranks and permissions can all be done via the webadmin.

**Comment by eszlarie** [comment]
You guys are fast to respond! The command just came up with the massage that there was no rank assigned to me.

**Comment by eszlarie** [comment]
I tried it with the knowledge of case sensitive :/

**Comment by NiLSPACE** [comment]
That's strange. Use `listranks` in the console to view all ranks. Perhaps it's actually `Admins` or `Admin` instead of `Owner`.

Also, you do have the `Core` plugin enabled right? If you do you get a `Initialized Core v....` message in the console.

**Comment by SphinxC0re** [comment]
There should be a section in the manual where the difference between console and ingame commands is described. So you won't have to rewrite the section over and over for each command

**Comment by eszlarie** [comment]
I got it working! Thanks, I realized I was not typing the actual rank in. One more thing, is everyone default when they join the server or are they listed as no rank? I would like to know just in case I need to make the spawn safe from griefing and such.

**Comment by NiLSPACE** [comment]
@SphinxC0re I'm not quite following you. What rewrite for what section for each command?

Also, the ingame commands and console commands are completely separate. It all depends on the plugin. I believe the only difference between the way you call them is that console commands usually don't have a `/` in front of it.


@eszlarie When new people join they are always the `Default` rank.

**Comment by SphinxC0re** [comment]
I'm just saying that it would be good to mention that console commands don't have a leading slash. At theoment there is a section in the manual where this is explained separately for one command. If you define this at the start, you just have to mention that the command is a console/ingame command

**Comment by madmaxoft** [comment]
Actually, new players are unranked, but one rank is considered Default (settable via webadmin) and that rank is applied.

The difference is that when the admin changes the default rank to something else, all the unranked players are changed, but those assigned to the Default rank will stay as Default (note Default as rank name vs default as rank property.)

NiLSPACE <notifications@github.com> wrote:

>@SphinxC0re I'm not quite following you. What rewrite for what section
>for each command?
>
>Also, the ingame commands and console commands are completely separate.
>It all depends on the plugin. I believe the only difference between the
>way you call them is that console commands usually don't have a `/` in
>front of it.
>
>
>@eszlarie When new people join they are always the `Default` rank.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cuberite/cuberite/issues/2977#issuecomment-180801893

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by NiLSPACE** [comment]
I guess it can all be summarized like this:

Difference between in-game and console commands
---
Most of the in-game commands are started with a slash (/). Console commands are usually called without this. Plugin developers are adviced to bind console commands without the slash to prevent confusion.


Also, thanks @madmaxoft, I didn't know that. I thought they were automagically saved because when looking at the Core's Player_Rank page there are allot of people without a special rank.
