### ISSUE TITLE
Two different slabs don't create a block

### ISSUE THREAD

**Issue by rekuen** [cuberite/cuberite#2979]
I've found that one you put one slab of one type, and then another of a different material, it doesn't make  a block but leaves a gap of half a block and puts the slab just obove the empty gap.

![2016-02-06_19 34 12](https://cloud.githubusercontent.com/assets/2090383/12868545/0d903ab0-cd09-11e5-927a-adc21cfb0212.png)

**Comment by SphinxC0re** [comment]
That's exactly like vanilla does it

**Comment by rekuen** [comment]
In that case sorry for opening the issue, i thought that was a some sort of bug as i saw on a video on youtube one guy putting two different slabs together. I made a search and indeed is what you said, vanilla doesn't allow to pile two different types. You can close the issue.
