### ISSUE TITLE
Plugin to give players text ranks in chat

### ISSUE THREAD

**Issue by eszlarie** [cuberite/cuberite#2982]
Im not sure this is exactly the place to post this but i did not see anywhere else I should have. Is there a plugin to give players an actual rank such as - [ Default ) [ playername ) or [ Admin ) [playername )? I am looking to make a PvP survival where there are ranks (possibly with other colors) and a spawn safeguarded by protection plugins.

**Comment by LogicParrot** [comment]
@eszlarie Questions are typically posted to the forums or to the IRC. This tracker is typically used for bug reports.
Forum: https://forum.cuberite.org/

@cuberite/core-team I think we should have a written policy regarding this. Are general questions in the issue tracker fine?

**Comment by eszlarie** [comment]
I am not quite sure where to put something like this, could you guide me or just answer this here? Would be much appreciated!

**Comment by NiLSPACE** [comment]
Personally I prefer to keep issues like #2950 and #2937 outside the issue tracker here on Github.

Sometimes it can be hard to judge for people if something should be asked in here, a different issue tracker or on the forum (like the current issue #2982), so I don't really mind it with these types of questions.

If you have the core plugin enabled I believe there is a `/rank` command that you can use.

**Comment by eszlarie** [comment]
I mean't like in the actual chat in game there is no way to tell ranked people apart.

**Comment by NiLSPACE** [comment]
Oh, the try my Chatter plugin: https://forum.cuberite.org/thread-1231-post-9657.html#pid9657

**Comment by eszlarie** [comment]
thanks a lot, now where should i place something like this in the forum?

**Comment by NiLSPACE** [comment]
Probably either [Cuberite Discussions](https://forum.cuberite.org/forum-5.html) or [Plugin Requests](https://forum.cuberite.org/forum-3.html)

**Comment by eszlarie** [comment]
One more thing, how do i use the Chatter plugin?

**Comment by eszlarie** [comment]
Are there commands? The page does not specify, It does load but I do not see changes in the chat.

**Comment by NiLSPACE** [comment]
It should create a config file. In there you ca change the chat. The forum page describes how.

**Comment by eszlarie** [comment]
The forum page does not explain how the plugin is added nor commands to use the plugin.... I do not know how people had got this working!

**Comment by eszlarie** [comment]
I got it working, thanks for trying although I found out that Notepad++ does not automatically save and that had been the issue...again, thanks.

**Comment by eszlarie** [comment]
I am sorry for so many questions but ONE FINAL THING! How do i add ranks? Such as the admin.

**Comment by LogicParrot** [comment]
@NiLSPACE I agree that those don't belong here. But I don't think regular questions should belong here either. It's like having two forums.

**Comment by NiLSPACE** [comment]
Ranks and stuff have to be changed in the webadmin. There is an interface for doing so.

**Comment by NiLSPACE** [comment]
@LogicParrot I prefer to keep regular questions out of here as well, but I don't really mind if newcomers don't know what the best place is.

**Comment by LogicParrot** [comment]
@NiLSPACE You're ignoring the slippery slope effect.
