### ISSUE TITLE
Player Ranks and Permissions

### ISSUE THREAD

**Issue by eszlarie** [cuberite/cuberite#2984]
When I attempt to add a permission such as gamemode it does not seem to work in game. I have tried it as gamemode, gamemode 1, core.gamemode, and core.gamemode 1. I also cannot seem to figure out how to get something like essentials to allow commands without giving a rank the everything.

**Comment by bearbin** [comment]
This issue should not be opened on the bug tracker, but instead on the forum: https://forum.cuberite.org. 

You can view the permissions for the core plugin here: https://github.com/cuberite/core

In your case, the correct permission is `core.changegm`.
