### ISSUE TITLE
Mob cleanup code is potentially removing livestock

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2991]
Livestock should not be removed if the player is too far. The mob code [here](https://github.com/cuberite/cuberite/blob/master/src/World.cpp#L1144) seems to be doing just that. 

@jammet and others, did you ever experience livestock disappearance?

**Comment by jammet** [comment]
I did notice a lot of chickens, dogs (and not as often) sheep disappearing -- but that over the stretch of an entire year. Sometimes for reasons unknown, entire areas were completely devoid of *any* life. 
But yeah, it seems that while the sheep do not disappear all at once, they seem to be dwindling in numbers. I've put pigs in a pen several months ago and they completely vanished. So do cows, in the new pen I made when we discovered the issue with fencegates. 

I can of course set up an experiment, and see how much is really going on. Create a web of tiny pens and put 1 cow, pig, sheep or chick in each, and keep checking them, if you like.

All in all, disappearing animals have been pretty much the norm for as long as I use Cuberite ...

**Comment by LogicParrot** [comment]
Thanks for the info. I've found a 100% reproducable way to despawn animals.
If all players are 2048 blocks away from a ticking chunk, the animals in it will despawn. So:

- Stand in the same chunk as an animal
- Teleport 2048 blocks away or more
- Animal will disappear

**Comment by jammet** [comment]
:( Yes. They're gone. All of them gone. So that's how it happened.
