### ISSUE TITLE
cChunk::MobCensus's intentions are not clear

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2993]
cChunk::MobCensus appears to fill a list with N*M entries. Where N is the number of mobs in chunk and M is the number of clients that loaded that chunk. Why?

I believe the original intention was to compare every mob with every single player on the server and fill out the distances between them.

It seems this is what the author of cWorld::TickMobs had assumed. This wrong assumption led to the writing of a malfunctioning mob destroyer. The mob destroyer is supposed to destroy faraway mobs, but in reality the destroyer works on teleports, but doesn't work when players walk away from mobs. That's because walking away has time to remove the player from `m_LoadedByClient` before the destroyer code runs, but teleportation does not.

**Comment by madmaxoft** [comment]
Closed without a reason?

**Comment by LogicParrot** [comment]
Closed because we talked about iterating all `m_LoadedByClient` vs iterating all online players in the current world in #2994.
