### ISSUE TITLE
Challenge: Crash the server via multiworld travel

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2997]
Multiworld travel has been recently stabilized. I invite everyone to try to crash the server via one of the following:
- The `/portal` command
- Nether portals or End portals
- world-travel related lua API commands

If you manage to crash it, please report this here.

**Comment by Ajusa** [comment]
Challenge accepted!
I'll do some testing today on my CHIP.

**Comment by jammet** [comment]
I'm not able to crash it. :) Not that I ever tried. Just have to be careful of the other problems atm.
