### ISSUE TITLE
Activator Rails don't work

### ISSUE THREAD

**Issue by rekuen** [cuberite/cuberite#2998]
Using tnt minecarts  and activator rails is supposed to activate the tnt cart once it passes over it (been powered), but nothing happens the server treats the activator rail as a regular one.

I've reproduced the same scenario in vanilla and latest cuberite source to make sure I wasn't doing anything wrong. It work in vanilla but not in cuberite.

**Comment by tigerw** [comment]
Simply not implemented yet, see #68.

Yes, issue 68. It's quite old.

**Comment by bearbin** [comment]
Dupe of #215, #68
