### ISSUE TITLE
Limit minecart max speed and powered rails not reducing speed

### ISSUE THREAD

**Issue by rekuen** [cuberite/cuberite#3000]
Minecarts are supposed not to go beyond 8 block per second even when being powered, right now it has no limit(or at least it seems like it) and every powered rail you put increases the minecart speed even more.

I mean is pretty funny like it is i've made a human rocket with a minecart, but the main side effect is that you end inside a wall, the minecart fly over the rail and when taking corners step out of the rails.

That plus powered rails not working also when are are not powered, make the minecart use pretty hard, when not powered the rails are supposed to reduce the speed to almost stop the minecart in one block. 

I mention this two things together because I think may be related to one another.

**Comment by SphinxC0re** [comment]
3000!

**Comment by jammet** [comment]
9001! <3

**Comment by mathwhiz1212** [comment]
Players on my server actually like this and have created an ultrafast transportation system. Although a limit of 50-75 blocks/s would be agreeable to all.

**Comment by Schwertspize** [comment]
By the way, I experienced another bug with minecart. Place it on a rail (on top of a mountain), then destroy the rail, get into the minecart and as long as you push the forward button, you got a slow, but still aircart (if you stop in mid air, you and the minecart fall down)

**Comment by jammet** [comment]
@mathwhiz1212 The limit should mirror that of the original. If you want them faster than that, I'm sure it can be done with some kind of modding.

**Comment by mathwhiz1212** [comment]
@jammet I will likely look into that if/when they put the same limit as vanilla.
