### ISSUE TITLE
API docs: Document difference between regular and static functions

### ISSUE THREAD

**Issue by ShrewdSpirit** [cuberite/cuberite#3006]
There's nothing about this in the API documentations. We don't know which functions in http://api-docs.cuberite.org/cRoot.html should be called on cRoot singleton instance. I think this should be documented

**Comment by Seadragon91** [comment]
In the Notes of the documentation is at start the text `(STATIC)`. Then you can use directly `cRoot` instead of `cRoot:Get()`

**Comment by ShrewdSpirit** [comment]
Oh! Thanks.
But shouldn't it be documented that static functions can be called on cRoot? So others don't get confused like me :D

**Comment by madmaxoft** [comment]
There are a lot of places where the API functions are static, it would be impractical to repeat the information on each such occurrence.

**Comment by ShrewdSpirit** [comment]
Oh, I see

**Comment by williamhatcher** [comment]
Please close this.
