### ISSUE TITLE
Changes in settings.ini ignored/reverted

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3008]
Yesterday I noticed that for some reason, my server's name was altered somehow. The color code was missing. settings.ini used to look like this:
Description=§1L§9o§1n§9e§1l§9y §eI§2s§el§6a§2n§ed §1M§9i§1n§9e§1c§9r§1a§9f§1t

That says "Lonely Island Minecraft" and has nice colors to go along with it.

Now it says: 
Description=1L§9o§1n§9e§1l§9y §eI§2s§el§6a§2n§ed §1M§9i§1n§9e§1c§9r§1a§9f§1t

The first color code is truncated.

Now. If I make ANY changes to this, it's immediately overwritten back to the truncated version without the color code again. Also, I wrote entire sentences, and they were  #gone; the only trace left would be that settings.ini~ file in the same directory, which still showed my changes. Something keeps overwriting the file with the old information, but where else is that stored?

**Comment by Schwertspize** [comment]
Could it be that there is not enough memory allocated for the description? But that would truncate it from the end I think

**Comment by jammet** [comment]
It's been working fine for a full year with all colors intact.

**Comment by jammet** [comment]
I don't know why, it's removing the starting colors. Even several of the same in a row. I always just get "onely Island Minecraft" or "1onely Island Minecraft" and other variations thereof. Haven't tried it with different colors but ...

**Comment by LogicParrot** [comment]
#2969 is responsible. @NiLSPACE  I should have used my initial own implementation and not `TrimString`

**Comment by LogicParrot** [comment]
@jammet Thanks for reporting this ! I will fix this asap.

**Comment by jammet** [comment]
:) Alright! Thanks so much!

**Comment by NiLSPACE** [comment]
What did your implementation do different compared to `TrimString`? Your method also just removed the trailing white spaces right?

**Comment by LogicParrot** [comment]
@NiLSPACE TrimString removes any leading char whose value is smaller than 32. `§` is made of two bytes: `-62, -89` signed. So they are removed.

**Comment by madmaxoft** [comment]
Then fix `TrimString` to consider the chars `unsigned`, I think that's the sensible thing to do.

**Comment by LogicParrot** [comment]
That would be enough for ASCII, but I wonder if it's enough with unicode. Is there any unicode character which is 2 bytes or more, where the first byte is <32 unsigned?

**Comment by LogicParrot** [comment]
Wikipedia says
`Clear distinction between multi-byte and single-byte characters: Code points larger than 127 are represented by multi-byte sequences, composed of a leading byte and one or more continuation bytes. The leading byte has two or more high-order 1s followed by a 0, while continuation bytes all have '10' in the high-order position.`

I believe this means we should be completely safe if we just consider the chars `unsigned`.

**Comment by LogicParrot** [comment]
>The high order bits of every byte determine the type of byte; single bytes (0xxxxxxx), leading bytes (11xxxxxx), and continuation bytes (10xxxxxx) do not share values.

**Comment by LogicParrot** [comment]
This is now working fine.
