### ISSUE TITLE
compile.sh todo

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3014]
Todo:
- [ ] Ask the user about how many threads they'd like to use.  If the user does not make a choice, resort to a sane default. Perhaps using some variant [of this](https://forum.cuberite.org/thread-2332-page-2.html#pid25009).
- [ ] Add commandline arguments. This allows convenient automatic unattended updates.

**Comment by mathwhiz1212** [comment]
Could you add an option to automate this?
For example I could run it like this:
./compile.sh --branch master --mode debug --threads 4

**Comment by mathwhiz1212** [comment]
Or so that we could set BRANCH=master and other variables needed to achieve above. The script would just need to check if the variables are different from default.

**Comment by mathwhiz1212** [comment]
Actually, command line arguments seem pretty simple. I think I'll try my hand at it when I get a chance.

http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash/14203146#14203146

**Comment by mathwhiz1212** [comment]
Command line arguments are done :) This is at least a starting point. It has code duplication but it isn't finished yet. Right now you can use ./compile.sh BRANCH BUILDTYPE ex. ./compile.sh master Debug
You can also run it like normal with ./compile.sh and it will act just like normal.
Code: https://livetolearntech.com:3000/joshua/cuberite-compile.sh/src/master/compile.sh

**Comment by LogicParrot** [comment]
Thanks :)
I'll check it out.

**Comment by mathwhiz1212** [comment]
@LogicParrot No problem :)
