### ISSUE TITLE
Repositories connected to mc-server Bountysource

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3028]
Some of the Cuberite repositories are connected to the old [mc-server](https://www.bountysource.com/teams/mc-server/issues) Bountysource page instead of the new Cuberite page.

**Comment by mathiascode** [comment]
Does anyone have access to the mc-server team on Bountysource (https://www.bountysource.com/teams/mc-server)? If so, could the team be removed and the repositories linked to the cuberite team instead?

**Comment by madmaxoft** [comment]
I have removed all the repositories from the mc-server organization on Bountysource, and updated the description to indicate the rename to Cuberite. I think it can stay like this, I haven't found a way to actually remove the team.

**Comment by mathiascode** [comment]
Thanks!
