### ISSUE TITLE
Webadmin doesn't  work

### ISSUE THREAD

**Issue by RFan95** [cuberite/cuberite#3039]
Hello

When I log in to webadmin I can only see the main page (https://IP:8080/webadmin).
If I try to open "Players" or "Chat" for example I get the message "404 not found".

**Comment by bearbin** [comment]
Thanks for opening an issue. Would it be possible to send over a screenshot of the issue?

**Comment by Kaboomki** [comment]
Hi, had the same problem with a fresh inststall on a new PI 3. When I open webadmin menu items with urls like
http://192.168.1.64:8080/Core/Manage%20Server

I got a 404 response.

However, the error disappeared after several minutes, when core was finally initialized.

**Comment by bearbin** [comment]
@Kaboomki The issue for you is that core is initialised slowly then - could you elaborate?

**Comment by williamhatcher** [comment]
Can we try testing this again or close this issue?

**Comment by bearbin** [comment]
I am going to suggest the world generation was slowing down webadmin opening. In any case, it worked eventually.
