### ISSUE TITLE
Minecarts continuously move/jerk forward on unpowered powerrails and detector rails

### ISSUE THREAD

**Issue by Woazboat** [cuberite/cuberite#3046]
Place some powerrails without powering them and put a minecart on them. If you push the minecart, it will keep on moving forward indefinitely at a very slow pace. Can also go up slopes this way.

https://gfycat.com/FairDishonestBobcat

Commit 3c671b9c23e1b78c0633f5375cb13079295d059f

**Comment by NiLSPACE** [comment]
![POWER](http://www.reactiongifs.com/r/unpwr.gif)

**Comment by rekuen** [comment]
Powerrails should stop the minecart if they aren't been powered. I open an issue with that problem and the speed limit #3000

**Comment by Woazboat** [comment]
Also happens on detector rails, although much slower.

**Comment by floriangosse** [comment]
Is there any progress on this bug?
