### ISSUE TITLE
Player skins aren't drawing correctly

### ISSUE THREAD

**Issue by dackage** [cuberite/cuberite#3053]
This is how I normally look:
![normal](https://cloud.githubusercontent.com/assets/17479942/13328182/f66225ca-dbb2-11e5-9d51-6fdc9c0cf8f4.png)
 This is how I look on a cuberite server:
![on_cuberite](https://cloud.githubusercontent.com/assets/17479942/13328201/0cd83cf4-dbb3-11e5-9f17-e839857bdf64.png)

Any fix to this?

I saw someone else post the issue (https://github.com/cuberite/cuberite/issues/2149) but it didn't seem to get much attention.

**Comment by bearbin** [comment]
The other issue hasn't been closed, so this is a dupe and so I'm going to close it. 

Thank you for telling us how you feel about the issue though, and any feedback is good feedback :)

**Comment by tigerw** [comment]
[Dr Seuss](https://img0.etsystatic.com/000/0/5761781/il_570xN.250500122.jpg)

**Comment by madmaxoft** [comment]
@dackage what is your Minecraft name? So that we can look up the skin and properties associated with your account - it seems you're using something extra in the skin that Cuberite doesn't yet support.
