### ISSUE TITLE
cPlayer: Using TeleportToCoords inflicts damage

### ISSUE THREAD

**Issue by Fighter19** [cuberite/cuberite#3054]
Looking at https://github.com/cuberite/Essentials/issues/53
I found that TeleportToCoords inflicts damage while the player is moving.

**Comment by Schwertspize** [comment]
you mean, if you teleport to a specific coordinate, you should ignore fall damage, or what else?

**Comment by Fighter19** [comment]
Yes. Although it's not only "fall damage" for example if you teleport up while moving you get damage. (Also if moving horizontally only)

**Comment by Schwertspize** [comment]
well, ok, this must definitely be fixed.... would you mind posting the "death reason", that would probably make fixing easier

Anyway, thanks

**Comment by Fighter19** [comment]
I hope this is what you meant:
"[name] fell to death"

**Comment by Fighter19** [comment]
Maybe make m_bIsTeleporting available and add something like into line 376 in Pawn.cpp ?:
FallDamageAbsorbed |= IsFlying || Player->IsClimbing() || Player->IsTeleporting();
