### ISSUE TITLE
Entities spawning on nether above Y 128 (nether's top), and mushrooms too.

### ISSUE THREAD

**Issue by tonibm19** [cuberite/cuberite#3055]
It's just that I've seen some ghasts and pigman over there.
There are also mushrooms.

Shouldn't there be no monsters or mushrooms there?

**Comment by NiLSPACE** [comment]
I believe mushrooms used to generate on the top of the nether, Isn't that the case anymore?

Also, I believe there shouldn't be any mobs spawning on bedrock.

**Comment by tonibm19** [comment]
Well, I'm not really sure, but... if it's like you say, how do the players get to those mushrooms if they cannot break bedrock?

**Comment by NiLSPACE** [comment]
I don't know, but I believe mushrooms used to generate on top of the nether even if people can't go there.

**Comment by tonibm19** [comment]
You're right.
https://bugs.mojang.com/browse/MC-1381

**Comment by madmaxoft** [comment]
Actually in vanilla mobs do spawn above 127, there are several farm designs based on that:
https://www.youtube.com/watch?v=6W8YgdRnHy8
https://www.youtube.com/watch?v=fPTA6gBoVO8
