### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#3058]
Everything seems fine, but CI thinks that it's failing 

The command "./CIbuild.sh" exited with 1.

**Comment by madmaxoft** [comment]
If you mean this build, for example:
https://travis-ci.org/cuberite/cuberite/jobs/112561856

Then it's really failing:
```
ERROR: Newly undocumented API symbols found:
cPlayer.IsTeleporting (function)
cPlayer.SetIsTeleporting (function)
```

**Comment by Fighter19** [comment]
Yes, I've created those because I needed those function to check for the collision inside ClientHandler.cpp I still don't know if it was a good idea.

**Comment by madmaxoft** [comment]
@Fighter19 The only problem is now that you made those functions exported to the Lua API (they are within the `// tolua_begin` and `// tolua_end` comments) and you haven't provided the API documentation for them. Just add the docs in the `$/Server/Plugins/APIDump/APIDesc.lua` file, there's information in that file on how to do that. You can check if you did it correctly locally, by enabling the APIDump plugin and issuing the `apicheck` command.

**Comment by Fighter19** [comment]
ok, thank you. I'll do that then.
