### ISSUE TITLE
message type and mob type enums are merged in lua api docs

### ISSUE THREAD

**Issue by warmist** [cuberite/cuberite#3066]
See: http://api-docs.cuberite.org/Globals.html#MobType
There is both mtError and mtMagmaCube.

**Comment by madmaxoft** [comment]
This should be easy enough to fix - each category should list the values, instead of using a regexp.

**Comment by benmxavier** [comment]
I will have a go at fixing this issue. This would be my first PR

**Comment by benmxavier** [comment]
I think I found the cause of the issue, on line 3059 of APIDesc.lua it reads
MobType =
				{
					Include = { "^mt.*" }, /* I believe this is the line causing the issue, pulling in all entities including the characters mt*/
					TextBefore = [[
						The following constants are used for distinguishing between the individual mob types:
					]],
				},
I am not sure how to change file to only output mot type enums while retaining the include syntax

**Comment by Seadragon91** [comment]
Don't see the duplicates anymore.
