### ISSUE TITLE
Minecraft 1.9 Protocol Support

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#3067]
We should support the newest protocol, even if we do not support the latest features.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=31538673)](https://www.bountysource.com/issues/31538673-minecraft-1-9-protocol-support?utm_source=31538673&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jammet** [comment]
This seems like a huge undertaking. Where do you start?

**Comment by madmaxoft** [comment]
Make a copy of the Protocol18x files, change the class name to `cProtocol190` and add a new branch to `cProtocolRecognizer` to recognize the 1.9 protocol version. Then modify all the `cProtocol190`'s functions to use the new packet numbers as documented by http://wiki.vg. Start by the packets needed for basic connection, comment out the rest, so that you can test early on.

**Comment by jammet** [comment]
Hope someone finds the muse and time to pull it off. Thanks for detailing
the process for a curious one, like me. :)

**Comment by sgtbigman** [comment]
I'm interested in taking this task on, even though I'm new to the project.

I've started some work for it on my end, but feel free to let me know if I should stop.

Thanks.

**Comment by madmaxoft** [comment]
Go ahead with it, @sgtbigman . If you feel you need any help, post an URL to your branch either here or in the forum and ask.

**Comment by sgtbigman** [comment]
Thanks.

Current work so far resides [here](https://github.com/sgtbigman/cuberite/tree/19-protocol-support).
**Note**: My commits and code will be far better/cleaner and up to standards when I actually make a PR, so ignore any mess for now. :smile: 

I successfully have the client connecting and able to see some of the game world (mostly the sun) at the moment. I am currently trying to get the SendSpawnMob part working correctly (mostly there). I'll let you know if I get stuck on that part for too long.

Thanks for giving the general outline of how to go about this, @madmaxoft; it has made the work far easier than I originally had foreseen!

**Comment by madmaxoft** [comment]
Does the 1.9 protocol really have a different chunk serialization?

**Comment by sgtbigman** [comment]
Yep, just discovered that and started working on a new serializer for it yesterday.

**Comment by aaronfranke** [comment]
I agree. Regardless of the features, clients using 1.9 should be able to join Cuberite servers.

**Comment by alwaysontop617** [comment]
Is 1.9 support added yet? I really want and love cuberite for 1.9

**Comment by sgtbigman** [comment]
I am still working on the new chunk data serialization (taking a bit longer than I originally thought to understand how it all works), but I am hoping to make some good progress on it and the rest of the protocol over the next few days.

My work is still on the branch I linked to in an earlier comment, so feel free to look it over, utilize it, leave suggestions, etc. I'll try to keep it up-to-date with any local changes, but it may be a day or so behind depending on when I push my latest changes/ideas.

Thanks.

**Comment by mathwhiz1212** [comment]
I am having issues with people trying to connect with 1.9. Thanks for working on it!

**Comment by alwaysontop617** [comment]
Yes, I currently can't run a spigot server so this will be great for the TFS(Tecflare.com Server)

**Comment by Pokechu22** [comment]
I probably should have checked in here a bit earlier, but I got a version set up that supports 1.9 (including chunk data!).  Wiki.vg's article on the new chunk format is pretty incorrect, and I'm planning on rewriting it eventually.

The part that I don't have worked out is handling the new inventory slot in a decent way.  I also don't have a good solution for the effect packet, which did have all of its IDs changed (which makes, among other things, the long fall effect interesting).  Mob eggs, as far as I can tell, are also broken, and boats don't seem to work.

I'm not too familiar with C++ so I may have done some stuff wrong, but I do have a version that should be good for building upon, which will be #3135.  I'll discuss my techniques there.

**Comment by bearbin** [comment]
@Pokechu22 Great work!

If you're interested in the $5 bounty, you need to head over to Bountysource to claim it .

**Comment by jammet** [comment]
That all sounds delightful! :) I'm so glad there's progress!

On Sat, Apr 9, 2016 at 8:58 AM, Alexander Harkness <notifications@github.com

**Comment by Pokechu22** [comment]
On a side note: The reason why it didn't appear on the server list is that it's using the legacy (1.6.4) ping format (particularly to disconnect).  This would require some changes to ProtocolRecognizer (which I have not made).  Also: #3135 has been submitted.

**Comment by alwaysontop617** [comment]
We should start our own game. We can have it written in c++. It can have servers, just like minecraft. maybe even better graphics.

**Comment by aaronfranke** [comment]
@alwaysontop617 So, basically Minetest?

**Comment by jammet** [comment]
Is certainly a great idea too, though I'd love to stick around with
Minecraft, too. :)

**Comment by LogicParrot** [comment]
I have cleaned the advertisement. @alwaysontop617 please use [this forum](https://forum.cuberite.org/forum-10.html) for this. Thanks :)

**Comment by bibo38** [comment]
Since this Issue has a bounty it would be nice to know, when the issue can be considered as fixed.
Some ideas:

- Joining and basic actions(building, destroying, ...?) works
- No client side crashes/disconnects.
- No server side disconnects
- Implementation of all Packets
- (1.9 Functionality)

**Comment by bearbin** [comment]
The simple answer is that this issue is fixed when the pull request gets merged, but what we actually need is just the protocol with no major flaws over the old and no crashes in the protocol code.

Personally, I'm in favour of merging it now since there are only minor improvements to go and it's a major improvement to players as a whole.

**Comment by Pokechu22** [comment]
I don't think it makes sense to merge _right_ now.  1.9.3-pre2 was released recently, and it turns out that it _also_ makes a few packet changes.  [Here's some automatic diffs](http://pokechu22.github.io/Burger/diff_1.9.2_and_1.9.3-pre2.html) generated via burger.

I think that it might make sense to wait until 1.9.3 is released (likely soon) while a few other things are finished up.

If it is useful, here's a checklist as to the current state:

- [x] Basic protocol
    - [x] Server list ping works
    - [x] Players can join
    - [x] Players can chat
    - [x] Chunks work
        - [x] The nether and end work
    - [x] Players can place, break, and interact with blocks
    - [x] New metadata for all entities is sent
    - [x] Players can use items
- [x] Gameplay functions
    - [ ] Vehicles
        - [x] Players can enter vehicles
        - [x] Players can get out of vehicles
    - [ ] Players can move vehicles reliably (boats - missing some packets namely for paddles)
    - [x] Spawn eggs
    - [ ] Potions
        - [x] Potion IDs are converted to the new format (partial - water bottles are buggy)
        - [ ] Brewing stands work
    - [ ] Wolves
        - [x] Wolves can be tamed
        - [ ] Wolves can sit down
        - [x] Wolves can be damaged without making the client freak out
    - [ ] Command blocks
        - [ ] New [`MC|AutoCmd`](http://wiki.vg/Plugin_channels#MC.7CAutoCmd) channel
        - [ ] Command block minecarts over the renamed [`MC|AdvCmd`](http://wiki.vg/Plugin_channels#MC.7CAdvCmd) (previously `MC|AdvCdm`) channel
        - [ ] Figure out why command blocks aren't even opening themselves
- [ ] 1.9 gameplay features
    - [ ] New 1.9 combat
    - [ ] Dual wielding
    - [ ] Relaying a player's hand preference to other 1.9 clients
    - [ ] New 1.9 entities
    - [ ] Boats
        - [ ] 2-player boats
        - [ ] Paddles
    - [ ] New 1.9 blocks
    - [ ] New 1.9 entities
    - [ ] New dragon fight
    - [ ] New pick block (grabbing from inside of inventory - [`MC|PickItem`](http://wiki.vg/Plugin_channels#MC.7CPickItem))
    - [ ] Command blocks
        - [ ] Chain command block
        - [ ] Conditional command block
        - [ ] Other new command block settings
        - [ ] Command block orientation
- [ ] 1.9 performance changes
    - [ ] Primary bit mask (This _really_ should also apply to 1.8 and 1.7 - internally it's also used; shouldn't be _too_ hard to implement but it would require a refactor)
    - [ ] Chunk section palettes (would require a _bigger_ refactor but also a bigger network savings)

**Comment by bearbin** [comment]
Is there any issue with just merging the protocol update, and then being able to work on the rest of the 1.9 features in parallel?

**Comment by Pokechu22** [comment]
Not really.  I don't think it's a good idea to try and get the 1.9 gameplay features in yet.  So merging it soon would make sense.  The one thing that's concerning is the potion IDs since it's partially breaking water bottles.

I do think that once that's fixed it would make sense to merge.

@sgtbigman is actually doing the kind of parallel work you suggest by [working on boats on a second branch](https://github.com/Pokechu22/cuberite/compare/protocol-1.9...sgtbigman:add-steer-boat-and-vehicle-move-support).  I think that parallel work on different parts makes sense.

**Comment by LogicParrot** [comment]
We do not support command blocks, you can ommit that part from the todo.

**Comment by aaronfranke** [comment]
Who is we? Why not?

**Comment by LogicParrot** [comment]
No particular reason. No one has implemented them yet.

**Comment by Pokechu22** [comment]
I'm pretty sure that regular command blocks are implemented since I have seen code for the old channel, `MC|AdvCdm`.  Command block minecarts aren't implemented though.

The degree of implementation isn't clear, but there is _some_ level of implementation.

**Comment by bibo38** [comment]
@Pokechu22 Yep command blocks are implemented. See #2016

**Comment by LogicParrot** [comment]
Sorry for the confusion.
