### ISSUE TITLE
Cuberite SSL implementation Important Vulnerabilities (webadmin)

### ISSUE THREAD

**Issue by rekuen** [cuberite/cuberite#3070]
As I was implementing Let's Encrypt certificates I run a test to and to my surprise I've seen that cuberite implementation of PolarSSL has several important vulnerabilities:

SSLv3 protocol should be disabled, it's not.
RC4 cipher should be disabled, it's not.

So it's vulnerable to PODDLE

The cipher preference can also be change I recommend following the Mozilla Foundation guidelines, and  PolarSSL  supports it, force the preference of strong ciphers first, and remove those like RC4 and others known to be weak.

https://tls.mbed.org/api/ssl_8h.html (search for mbedtls_ssl_conf_ciphersuites )

https://wiki.mozilla.org/Security/Server_Side_TLS

DH params are also 1024 by default, it should be at least 2048 to avoid Logjam Attack:
https://tls.mbed.org/kb/cryptography/providing-diffie-hellman-or-dhm-parameters

**Comment by mathwhiz1212** [comment]
This is an important issue.

**Comment by rekuen** [comment]
To disable SSL3 I think you just have to comment this line in config.h

https://github.com/mc-server/polarssl/blob/4f4c5b7450631e46a94cb89adf4a7737fbb178bc/include/polarssl/config.h#L1015

**Comment by rekuen** [comment]
But I think you should consider updating to the latest version of PolarSSL, as it has all these issues resolved in the default configuration.

**Comment by mathwhiz1212** [comment]
Someone could either change the name to include webadmin or add the tag webadmin.

**Comment by rekuen** [comment]
I've added the webadmin in the name, I can't add labels, but is more related to PolarSSL than the webadmin itself.

**Comment by tigerw** [comment]
Just update PolarSSL? Sounds 'easy' - I've added the label. Hopefully someone will find time to do it.

**Comment by Seadragon91** [comment]
I did an check for this and no it's not easy. Lots of renames, name `polarssl` changed to `mbedtls`:
* Names now starts with `mbedtls` at beginning
* Some variable doesn't exists anymore found new ones, but they also doesn't exists anymore, maybe support has been removed
