### ISSUE TITLE
Enhance horse riding

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#3071]
Currently you can't jump with horses

Horses are perfect water transportation, you can't go on land with them but you can travel exactly with the same speed through water as on land (which makes them very fast)

**Comment by jammet** [comment]
Sorry. I just seem to have made a dupicate of the jumping issue. That aside, I was able to ride horses on land. Just not across terrain that had steps in it. Haven't tried water, yet.

**Comment by Schwertspize** [comment]
Yep, you can ride them on land but you can't go up with them

**Comment by mathiascode** [comment]
Closing in favor of #703
