### ISSUE TITLE
Dispenser not placing boat/minecart/spawnegg

### ISSUE THREAD

**Issue by Schwertspize** [cuberite/cuberite#3077]
Note: this is not the current master, Its at lest one commit behind (that one was a webadmin fix I think, here commit sha: 39144480f588b60c246fbe0451b8002eaa6a0797) 

Dispensers should place some items like boats, minecarts or monsters (when dropping spawn eggs).

**Comment by QUSpilPrgm** [comment]
This is fixed with #3219
