### ISSUE TITLE
Stuck deadlocks

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3080]
Starting about two months ago, my server randomly freezes when a deadlock occurs. A "Deadlock detected, aborting the server" error appears in the chat, after that nothing happens.

**Comment by madmaxoft** [comment]
The server should really abort, and possibly even create a core dump. Have a look at the forum thread for reporting problems: https://forum.cuberite.org/thread-631.html , it lists some tools that can be used to provide more information. We'd be most interested in the stacktrace of all the threads at the time of the deadlock; there's not much else we can do without that.
