### ISSUE TITLE
Zombies at daytime

### ISSUE THREAD

**Issue by wraith11** [cuberite/cuberite#3082]
On my new installed Server (latest commit, on a RP2) zombies appearing at daytime. It seems that they were generated while a chunk generates.

This zombies are not burning in sunlight and not moving but they attack when I'm close. When I hit them they begin to burn and behave normal.

**Comment by NiLSPACE** [comment]
Zombies won't generate. Only passive mobs generate with the chunks. This means something is wrong in the spawn code of mobs.

**Comment by LogicParrot** [comment]
I believe this same old lighting issue: Grass is considered "dark". @wraith11 are those zombies standing on grass?

Reference: https://github.com/cuberite/cuberite/issues/1926

**Comment by wraith11** [comment]
Yes, you're right. They all standing on grass searching for "darkness".
So it's a dupe of #1926.
