### ISSUE TITLE
I get board when nothing

### ISSUE THREAD

**Issue by alwaysontop617** [cuberite/cuberite#3085]
Does anyone have a prebuild Cuberite Server that comes with plugins, spawn, etc. If so can you please send some to me, I really want to have a cuberite server but I do not have time to build one from scratch. My current server sucks, it can be accessed from tecflare.com.

**Comment by bearbin** [comment]
This is not the relevant place to ask this soft of issue. Please try the [forum](https://forum.cuberite.org).
