### ISSUE TITLE
Pathfinding: Unread variables

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3087]
@LogicParrot 
I see that the variables here are assigned again and later not used anymore.
[DoneEast ](https://github.com/cuberite/cuberite/blob/56f3fc954e02236522df7d7edde7273be387d21f/src/Mobs/Path.cpp#L221)
[DoneWest](https://github.com/cuberite/cuberite/blob/56f3fc954e02236522df7d7edde7273be387d21f/src/Mobs/Path.cpp#L237)
[DoneWest](https://github.com/cuberite/cuberite/blob/56f3fc954e02236522df7d7edde7273be387d21f/src/Mobs/Path.cpp#L253) <-- duplicated, do you mean DoneSouth?
[DoneNorth](https://github.com/cuberite/cuberite/blob/56f3fc954e02236522df7d7edde7273be387d21f/src/Mobs/Path.cpp#L269)

Looking at the code, I think they can be removed there, or?

**Comment by LogicParrot** [comment]
I kept them there to future-proof this and avoid nasty bugs if I (or someone) ever decide to rely on those values later on in that function. I assumed that the compiler will optimize them out.

**Comment by LogicParrot** [comment]
The DoneWest duplication is an error. Thanks.

**Comment by Seadragon91** [comment]
Okay thank you.
