### ISSUE TITLE
Files to include with server binaries

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3095]
There seems to be a few differences between the files included in the Windows and Linux/FreeBSD/OSX archives. Therefore, I wanted to discuss/ask which files that should be included.
- The Windows archive is missing the "lang" folder, as well as the "LICENSE, "CONTRIBUTORS", "README.txt" and "favicon.png" files found in the Linux/FreeBSD/OSX archive.
- The Linux/FreeBSD/OSX archive includes "install_windows_service.cmd" and "delete_windows_service.cmd" files (unintentional?), which are not included in the Windows archive.
- The "Licenses" folder in the Linux/FreeBSD/OSX archive is called "ThirdPartyLicenses" in the Windows archive

**Comment by mathiascode** [comment]
What is the purpose of the "lang" folder at the moment?

**Comment by yangm97** [comment]
I’d like to suggest that no files need to be distributed besides the binary, these files should be able to be generated by the binary on the first run, just like vanilla, spigot and probably others do.

**Comment by sphinxc0re** [comment]
Do they all generate every file? May I run Spigot standalone and end up with a bunch of files? That sounds pretty interesting 😁

**Comment by NiLSPACE** [comment]
In C# I can put files in the binary as an embedded resource, perhaps that is also possible in C++ across multiple platforms?

**Comment by madmaxoft** [comment]
I don't think there's an easy portable way for that in C++.

Most likely the easiest way for us to do that would be to extend the Lua processing done when generating bindings to also convert the data files into a C++ source file and compile that into the binary. Feels yucky, though.

**Comment by Pokechu22** [comment]
Here's a [relevant SO question regarding embedding when using CMake](http://stackoverflow.com/q/11813271/3991344).  Yea, it's not exactly easy to do it cleanly from that.

> Do they all generate every file? May I run Spigot standalone and end up with a bunch of files? That sounds pretty interesting 😁

Yes.  But note that many of the files are world files and such - dynamically generated.  It _does_ save configurations from their defaults (`server.properties`, plus `bukkit.yml` and `spigot.yml`) and a few similar things.  That said, in java those can be embedded directly into the JAR, which isn't as easy in C++.  For configurations, it makes sense to store defaults in the code, so it's (fairly) easy to automatically save them.

On the other hand, what we're referring to here are data files that would be harder to automatically generate - block/item configurations, for instance.  By harder I mean that they have defaults that change with each version, so saving them on the first load would be more difficult.

**Comment by sphinxc0re** [comment]
That came out wrong. I'm actually liking the idea 😁

**Comment by sphinxc0re** [comment]
It would be awesome because if you had cuberite installed globally on your system, you would be able to spawn new cuberite instances everywhere in a matter of seconds 👍

**Comment by madmaxoft** [comment]
On the other hand, launching the executable from the *wrong* location would suddenly be treated as a silent error :P

How about a compromise - a separate executable that has all the "resources" embedded, unpacks them when they're missing, and then runs the main executable (possibly also embedded)? Somewhat like an installer; those could be made in a platform-independent way using CPack (comes with CMake).

**Comment by sphinxc0re** [comment]
How about a subcommand set to spawn new servers like `cuberite new .` or `cuberite new test123` ?

**Comment by sphinxc0re** [comment]
It would be a little harder to start the server in the first place, but in the end it might be beneficial.

**Comment by yangm97** [comment]
I didn’t know C++ had issues with packing files... I was thinking about something along the lines of a  [systemd drop-in](http://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services). If the binary is run on an empty dir, then it creates no files besides world, mojang.sqlite, etc. and loads default settings from the binary. 

Not sure what could be done with the Prefabs folder and the like.
