### ISSUE TITLE
Ghost cPickups

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3106]
Many cPickups seem to be spawning in a world without mobs enabled. Interestingly, these cPickups seem to be moving, I can tell because `MoveEntityToNewChunk` keeps getting called for them.

**Comment by NiLSPACE** [comment]
> Many cPickups seem to be spawning in a world without mobs enabled. 

But what do mobs have to do with cPickups?

**Comment by LogicParrot** [comment]
They're the only source of pickups I could think of.

I failed to reproduce it after dozens of attempts. I am closing for now.

**Comment by NiLSPACE** [comment]
Breaking a block creates a pickup.

**Comment by tigerw** [comment]
Nevertheless, I can certainly anecdotally testify that every time I run `destroyentities` there is a disproportionate amount of pickups destroyed.

**Comment by LogicParrot** [comment]
Fair enough, I'm reopning.

**Comment by LogicParrot** [comment]
The "ghost pickups" aren't ghost pickups at all; they occur when fluids flood mineshafts. This happens pretty often though, we might be having too many mineshafts or too many underground fluids. Closing.
