### ISSUE TITLE
Disable spawning of Endermen by default

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3108]
Endermen have no real AI yet, and they are extremely buggy.

**Comment by mathias-github** [comment]
I don't think we should disable mobs that have unique drops, such as the slime.

**Comment by LogicParrot** [comment]
I removed the slime and the magmacube from the list. An enderman has a unique drop, but it is extremely buggy, I am in favor of disabling it despite the drop.

**Comment by LogicParrot** [comment]
I removed ghast, magma cube, slime from the list.
I think the enderman should stay on the list because it's extremely buggy, despite its unique drop.

Think anything else should be removed?

**Comment by tonibm19** [comment]
Maybe just remove them frim default settings.ini (or world.ini I dont remember now) so they can be enabled optionally

**Comment by bearbin** [comment]
I agree that this list of mobs should be disabled.

**Comment by mathias-github** [comment]
Withers drop Nether stars, which are used to craft beacons. Guardians drop prismarine shards, which are used for prismarine and sea lanterns.

**Comment by LogicParrot** [comment]
Updated the list. Anything else?

**Comment by LogicParrot** [comment]
Of the remaining mobs, only the Enderman actually spawns naturally. Renaming the post.

**Comment by jammet** [comment]
I think Ghasts might be candidates for such a list, at the moment they pretty much just shoot semi-randomly and spawn. It's easy to get rid of them with bow and arrow but, your call :).

**Comment by LogicParrot** [comment]
Although ghasts are brain damaged, they have a unique survival drop: The ghast tear, and they are not disruptive, unlike endermen. I believe keeping them is harmless.

**Comment by jammet** [comment]
I agree. :) They're huge, and sometimes they're in tiny corridors XD,
that's the only problem they pose.
