### ISSUE TITLE
Admin mode

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#3120]
I would like to have some kind of "admin mode". Currently running Spigot, there are several administration plugins that use certain tools to accomplish things. For example the plugin "Logblock" uses a wooden pickaxe, and WorldEdit uses a wooden axe. Some of these plugins may use tools in a way that makes it impossible for admins to use them regurarly.

Could in Cuberite a mode be added ("/admin on" ?) which plugins can hook into to enable the use of admin functions with these tools? If the mode is off, plugins won't do anything with the tool and it could be used regurarly. Admin mode could also save your inventory and switch you to creative mode.

Is this something feasible, or does it maybe belong in the core plugin?

**Comment by bibo38** [comment]
There is the concept of ranks in cuberite, which control the access to commands.
These ranks can be managed by the Core Plugins using the **/rank** command and I think, that in the default configuration an *admins* rank exists.

You can get the current rank by calling `cRankManager:GetPlayerRankName(PlayerUUID)` and set them by calling `cRankManager:SetPlayerRank(PlayerUUID, PlayerName, NewRank)`.

For an example look at the [rank-Command Implementation](https://github.com/cuberite/Core/blob/master/ranks.lua)

**Comment by LogicParrot** [comment]
>Some of these plugins may use tools in a way that makes it impossible for admins to use them regurarly.

In practice, no one uses wooden tools regularly. Is this worth the effort?

**Comment by bearbin** [comment]
Also, this would probably be better implemented in the plugin itself, so you could have, for example, the wooden sword from ThrowStuff activated, but the wooden shovel from KillDart deactivated, and switch between just by using `/ts tool` or `/kd tool`.

**Comment by bibo38** [comment]
@bearbin I agree. Should this be closed?

**Comment by PureTryOut** [comment]
@LogicParrot it's not just wooden tools, but I get it if you don't think it's worth the effort. Of course plugins could handle this mostly themselves, but in practice most plugins will not do this.
I guess I could just implement it myself in the plugins that I use and do that, since most is free software anyway.

Closing this for now
