### ISSUE TITLE
Fix player border

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3134]
The built in Cuberite border (Not to be confused with the 1.8 world border) works well for walking players. But for flying or teleporting players, it gets them stuck in infinite jitter.

**Comment by jammet** [comment]
Maybe this could be improved by putting a wall of unbreakable glass blocks as a barrier there. Limiting the world radius is helpful, just so you can be sure the files don't become larger than the drive the world is stored in, has maximum capacity. :) I use it and increase the world radius in small steps, when players ask.

**Comment by LogicParrot** [comment]
@jammet I've just got proper freezing for now. A wall of glass sounds cool, but that should probably not be in the Core plugin.

**Comment by jammet** [comment]
Is there something I should change?

**Comment by LogicParrot** [comment]
Updating the Core plugin if it's not up to date would be the only change required.
