### ISSUE TITLE
Startup is broken

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3141]
If you downloaded Cuberite in 13-14 April, please re-download the latest version from the site. Those builds had a startup problem. Downloads made after April 14, 11:15 UTC do not have this problem.

Startup was broken in a recent config update (https://github.com/cuberite/cuberite/pull/3137).
The change was reverted in https://github.com/cuberite/cuberite/pull/3140.

The problem caused a false alarm in the world linkage enforcer and prevented Cuberite from starting up. Builds between 13 and 14 of April are affected. If you downloaded Cuberite during that time, please re-download the latest version from the site. We are sorry for the inconvenience.

Also see: https://forum.cuberite.org/thread-2366.html#pid25684

Thank you, @jammet, for the fast report.

**Comment by jammet** [comment]
Oh, I'm just glad I was able to help, even not knowing I actually did. :)
Thanks so much for fixing it, too!
