### ISSUE TITLE
Why do we have cChunkLayer?

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3152]
What is the reason behind dividing `cChunkMap` into `cChunkLayer`s which are divided into `cChunk`s? 
Whatever the reason is, does it justify the disadvantage?: Random chunk access is `O(Layer Amount)`. This means that all `DoWithChunkByX` are inefficient. A chunkmap having a hash table (`std::unordered_map`) of chunks would be practically `O(1)`. 
Following the same reasoning, I think we should have a `unique id > entity pointer` hash table at cWorld. This would be a performance boost for the `doWithXByUUID` functions.

I did not perform any benchmarks, but I think it's possible that these functions would be pretty slow when a sufficient amount of players are logged in at the same time.

**Comment by Seadragon91** [comment]
Did you looked here? #2559

**Comment by LogicParrot** [comment]
Sorry, I missed that one. I will move the discussion there.
