### ISSUE TITLE
Raspberry Pi 2 compilation error

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3154]
The following error was [reported](https://botbot.me/freenode/cuberite/2016-04-20/) at the IRC by "ni8ls". It occurs after running the `compile.sh` script.
```
error: unknown warning option '-Werror=unused-command-line-argument'
      [-Werror,-Wunknown-warning-option]
src/HTTP/CMakeFiles/HTTPServer.dir/build.make:54: recipe for target 'src/HTTP/CMakeFiles/HTTPServer.dir/EnvelopeParser.cpp.o' failed
make[2]: *** [src/HTTP/CMakeFiles/HTTPServer.dir/EnvelopeParser.cpp.o] Error 1
CMakeFiles/Makefile2:1052: recipe for target 'src/HTTP/CMakeFiles/HTTPServer.dir/all' failed
```
Full log: https://gist.github.com/nilsmahlstaedt/9dd01a7cad9ea1428fc50beea8c284e4

**Comment by Schwertspize** [comment]
Outdated gcc. We can close this now 

[21:52] (ni8ls) the raspbian mirror is still on 4.6.3

**Comment by LogicParrot** [comment]
@tigerw @worktycho I think we really shouldn't mandate even newer compilers. I think I'm against c++14 at this time.

**Comment by tigerw** [comment]
Why? Direct everyone to easyinstall and make that work. Why *not* mandate newer compilers?

**Comment by LogicParrot** [comment]
Because people don't always have them and so do distros.

**Comment by LogicParrot** [comment]
Compiling is not limited to the devs. Compiling should be smooth for everyone who wishes to compile.

**Comment by LogicParrot** [comment]
Looks like the minimum gcc version we mandate already (4.8) already upports c++14. (But it requires a different flag: `-std=c++1y`), so people do not have to upgrade further if we decide to use it,I think. (unless there are some missing c++14 features implemented in newer version of gcc).

**Comment by worktycho** [comment]
As I keep saying, our language availability is primarily limited by VS. There is no point requiring newer linux compiliers, when we are restricted on windows to VS 2013, which doesn't support c++14 or even all of c++11.
