### ISSUE TITLE
cmake - Warn of old compilers

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3155]
### Expected behavior

cmake should refuse to start compilation when gcc is below 4.8 or clang is below 3.4 or VS is below 2013.
### Actual behavior

Things start compiling and fail unpredictabely mid-compile.

**Comment by worktycho** [comment]
Or alternatively we could add the check to the cmakelist, like the visual studio check.

**Comment by LogicParrot** [comment]
@worktycho sounds better.

**Comment by benmxavier** [comment]
#dibs
