### ISSUE TITLE
Clang minimum version?

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3157]
The minimum version of clang we require is not mentioned anywhere.

**Comment by Seadragon91** [comment]
I think clang 3.5 is a good minimum version.

**Comment by worktycho** [comment]
Since language support is primarily determined by visual studio, I think we should chose the minimum clang version with equivalent c++ support to our minimum clang version. Which is 3.4 as our minimum vs version is 2013.

And the smartChunkRam PR is failing because travis builds tests, not because it uses clang 3.4.

**Comment by worktycho** [comment]
There is no point requiring 3.5 unless there is a specific compiler bug you can point to, or a language feature supported by VS 2013 and clang 3.5 but not clang 3.4. c++14 is another issue, because we need to change to VS 2016 if want even partial support for c++14.

**Comment by Schwertspize** [comment]
What the **** are VS 2013 and VS 2016?

**Comment by Pokechu22** [comment]
@Schwertspize [Visual studio](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio)'s compilers (Visual studio 2013 and visual studio 2016)

**Comment by Schwertspize** [comment]
oh lol, micro~~soft~~evil

**Comment by LogicParrot** [comment]
So, we should update the readme and inform that clang 3.4 is minimum. Same goes for https://book.cuberite.org

**Comment by worktycho** [comment]
@Schwertspize They haven't finished c++11 yet. They've got most of it, and they did the easy bits of c++14 in the latest version, but they aren't feature complete yet.

**Comment by SphinxC0re** [comment]
See #3158

**Comment by LogicParrot** [comment]
Closed in #3158
