### ISSUE TITLE
Kick packet, can be ignored from client / Server doesn't close connection, correctly

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3159]
### Expected behavior

Connection to client should be fully closed, if the player has been kicked / banned from server.
### Actual behavior

Connection is not closed and player is still in the world.
### Steps to reproduce the behavior

Used this [minecraft client python](https://github.com/ammaraskar/pyCraft) to test packets.

**Comment by 109C** [comment]
That's odd, before when I tried this the server ended the connection after kicking me.

**Comment by Seadragon91** [comment]
Did you use your minecraft client?

**Comment by 109C** [comment]
I used the vanilla client with a proxy that just dropped all the kick / disconnect packets.

**Comment by Seadragon91** [comment]
Strange. I tested this with the python client a few times. Every time the client still was connected.

**Comment by tigerw** [comment]
I think fixed in #3115.

**Comment by Seadragon91** [comment]
I see that there was a call to [Destroy](https://github.com/cuberite/cuberite/commit/291370e367f9c51f894ff132860ac2b55727181f) a while ago, but it has been removed.

How could this problem be fixed?

**Comment by tigerw** [comment]
Fixed in a pull request that is yet to be merged because I've been too busy :(

**Comment by Seadragon91** [comment]
No way to block a unwanted player.

**Comment by Seadragon91** [comment]
If I connect with pycraft to the server and run `restart`. The server restarts and then aborts with the message that the server port is already in use. If I close pycraft before restarting it works fine.
