### ISSUE TITLE
Why does CMake use so many libraries on non-Windows builds?

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#3162]
Why the use libraries? The normal way seems to be to add all source files into a root `SOURCES` variable (via `PARENT_SCOPE` when necessary) and then add that to a singular executable to be linked.

The current libraries format is playing havoc with #3115 since it makes non-Bindings files depend on binding generation outputs (cRoot no longer holds mere pointers to Lua-related things), but nothing can find the generated files because custom-commands don't propagate generation rules to subfolders where the files are added.

**Comment by worktycho** [comment]
As a decoupling measure, to cause exactly the problems you are encountering. Because ideally, we want to minimize implementation dependencies of exactly the kind you get when you use values. Have you tried using unique_ptr?

**Comment by tigerw** [comment]
> Have you tried using unique_ptr?

I'm trying to *minimise* the amount of heap allocated objects :P

> ...to cause exactly the problems you are encountering...

C'mon, it was intentional? It surely can't be "automatic duration is fine, until you want to test things, at which point, everything must become pointers."

**Comment by worktycho** [comment]
Why do you want to reduce heap allocated objects? Your reducing the number of allocation that are made at startup by maybe 10-20, reducing startup by >0.01%. There are better things to save time on. Also, my philosophy is: eventually we want to test everything, however at the moment legacy makes testing most of the code base difficult, but we should try and add tests where possible. Increasing coupling to the biggest module for no visible performance gain is not worth it.

Of course if you can provide a profile which shows that a heap allocation is causing _significant_ performance issues, its a different matter.

**Comment by tigerw** [comment]
I have no evidence to suggest that there are any performance gains.

I want to reduce heap allocated objects because good practice articles say so and cRoot originally used them only to facilitate restarting, as the whole object was not originally recreated before #2427.

I don't know what to say about unit testing. If it's as you say - that it's all coupled tighter than a magnetic door lock - then I feel pursuing a goal of prettier CMake files and cRoot headers will realistically produce more returns.

**Comment by worktycho** [comment]
Good practice also recommends pimpl, interfaces, and testing.

**Comment by tigerw** [comment]
I just don't like reams of entirely unnecessary code. Just looking at the CMake files makes my head hurt. I nearly expired the last time you added a template definition to every, single, function of the redstone sim. That's all I'm trying to get at, and of course, picking and choosing which good practices I quote ;)

> recommends pimpl

please no pimples, I have enough of those already...

**Comment by peterbell10** [comment]
How about the opposite question: why isn't cuberite split into libraries on Windows builds?

**Comment by madmaxoft** [comment]
Mainly because of poor handling of the sub-libraries in MSVC, and because of (my) personal preferences :)

**Comment by madmaxoft** [comment]
We've had the split for over 4 years now. It's time for some retrospective, we should decide for one or the other, and convert to only use the same for all platforms.

I'd say that the original intent of making parts of the code parts independent has not been reached, and I don't think the library split is helping in any way with this at all.

I seem to remember another pro-library argument, that it makes the builds faster / more optimized on Linux; I don't have any data on this.

On the other hand, *some* parts of the server have been pulled out as libraries, with no dependencies to the original server. I believe that is the right way to go about it - when a functionality is properly enclosed, split it off as a library (but only then).

My anti-library point stands, they would make the project quite unwieldy in MSVC. Right now, the sources displayed in MSVC basically copy the on-disk structure; with libraries, they would have a different structure and files would be harder to find, when looking for them manually. I guess I would get used to it, if forced to, but unless I see a good enough reason, my **vote** is to **un-split**.

**Comment by tigerw** [comment]
My main concern is that the CMakeFiles don't look as complicated as the cpp files...

As Tycho says, testability is key; you said in #4591 that you were picking things out of the sources and stubbing the rest. Does this mean you compile the sources to test along with their mocked #includes, avoiding the need for interfaces and pimpl?

**Comment by madmaxoft** [comment]
Almost, but the other way around - the tests use the regular `#include`s, but provide their own (limited) implementation stubs, only for the stuff they actually need.
That basically shows that the current split into libraries isn't working anyway.

**Comment by madmaxoft** [comment]
I'm for interfaces where they make sense (block handlers would definitely benefit from a unified interface to getting and setting blocks). Pimpl seems like an overkill for a single-executable project, but if it makes sense in a particular place, why not. But please let's not derail this. We want to decide whether to split MSVC or un-split others.

**Comment by tigerw** [comment]
> derail this
_So, MINECART physics are still pretty broken right now..._

I would propose simplification by unsplitting and compiling all sources directly into the executable target.
