### ISSUE TITLE
ChunkLayers are never freed

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3166]
A chunk layer is a collection of up to 32x32 chunks. 

### Expected behavior
A chunk layer should be freed once it no longer has active chunks.

### Actual behavior
Chunk layers remain loaded forever.

### Steps to reproduce the behavior
Fly in a straight line and observe that `cChunkMap::RemoveLayer` is never called while the chunkLayer creation code in `cChunkMap::getLayer` is called.
To observe this, run in debug mode, put some line break in `cChunkMap::RemoveLayer` and in `cChunkMap::getLayer` at the chunk layer creation part.

**Comment by LogicParrot** [comment]
Does https://github.com/cuberite/cuberite/pull/2565 close this?

**Comment by sphinxc0re** [comment]
I'm not sure if chunky layers exist anymore since this commit

**Comment by LogicParrot** [comment]
Alright. Closing.
