### ISSUE TITLE
Crashing cuberite with a sticky piston, redstone, and a redstone block

### ISSUE THREAD

**Issue by robloxtester** [cuberite/cuberite#3168]
### Expected behavior
Piston should oscillate at 1 tick, just like on bukkit, spigot, etc

### Actual behavior
Piston oscillates at intervals below 1 tick, resulting in the server crashing.
https://www.youtube.com/watch?v=h65EHBxXC2k

### Steps to reproduce the behavior
Shown in the youtube video.

### Build + Commit ID
Cuberite build id: 295
commit id: 16d53a039b2bd590989477c0f8b25acecd988417

### Similar issues
Similar to issue #3080

**Comment by mathias-github** [comment]
Another similar issue: https://github.com/cuberite/cuberite/issues/2889

**Comment by SphinxC0re** [comment]
@tigerw that's probably an issue for you

**Comment by tigerw** [comment]
Indeed.

**Comment by madmaxoft** [comment]
Reopening, since PR #3226 was reverted.
