### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by MaksOuw** [cuberite/cuberite#3169]
Hello,

I'm currently trying to make Cuberite work on my NAS (Asustor, with ADM 2.6 freshly installed). In this version, I have Glibc 2.22, but my libstdc++ seems to be outdated (I miss GLIBCXX 3.4.18 - 3.4.19 - 3.4.20).

I installed Libstdc++ by OPKG (https://wiki.openwrt.org/doc/techref/opkg), ported on Asustor NAS.

Is there any plan to make it work with an oldest version of Libstdc++ ? Or should I have to recompile it on a machine with libstdc++ version like mine ?

I can't compile it on my NAS because there's no compile tools (I have make but not cmake). So I'm a bit blocked here.

Is there anyone who already find a solution to my problem ? The java version of MC Server sucks af :(

FYI, I used the easyinstall.sh script to get the last working build. Here's the buildinfo : 
Cuberite Linux x86 Master #473 https://builds.cuberite.org/job/Cuberite%20Linux%20x86%20Master/473/

uname -a
Linux NAS 3.4.26 #1 SMP PREEMPT Wed Apr 27 02:30:02 CST 2016 i686 GNU/Linux

Thanks by advance

**Comment by bibo38** [comment]
I've now compiled a version of Cuberite, which uses a static linked libstdc++ and libgcc.
Can you try this version on your NAS and give feedback?

P.S.: My CMake call:

    cmake -DCMAKE_CXX_FLAGS="-static-libstdc++ -static-libgcc" -DCMAKE_C_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_BUILD_TYPE=Release ..

**Comment by MaksOuw** [comment]
I would like to, but where can I find this version ?

**Comment by bibo38** [comment]
@MaksOuw I've edited my comment :smirk:

**Comment by MaksOuw** [comment]
@bibo38 OMG IT WORKS. You're amazing dude. Thanks for all !

What shall I do to update this build now ? When a new version of Cuberite is out, I had to rebuild with you cmake parameters right ?

**Comment by bibo38** [comment]
Nice to hear, that this version works :smile: !

To compile Cuberite manually just follow these easy steps:

- Get a Linux installation which is capable of compiling Cuberite(in my case [Ubuntu Mate 15.10](http://cdimage.ubuntu.com/ubuntu-mate/releases/15.10/release/) with build-essentials and cmake installed(`sudo apt-get install build-essentials cmake`))
- Clone Cuberite (`git clone https://github.com/cuberite/cuberite.git`)
- Go into the Cuberite folder and get the submodules (`git submodule update --recursive --init`)
- Make a build folder and go into the folder
- Run the CMake command(`cmake -DCMAKE_CXX_FLAGS="-static-libstdc++ -static-libgcc" -DCMAKE_C_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_BUILD_TYPE=Release ..`) to generate the Makefile
- Run `make` to compile the Cuberite
- Copy the Server(from the Cuberite folder) directory to the desired linux system


@madmaxoft @worktycho Would it make sense to link the libstdc++ and libgcc statically on every CI build? It would increase the filesize, but reduce the required libraries.

**Comment by MaksOuw** [comment]
Thank you ! I'll create a VM to get this machine and use it only when I need it :)

**Comment by worktycho** [comment]
I'd be cautious of linking the libraries statically, as it is a significant increase to the executable size. If it wouldn't be a problem for @bearbin having a x86 and ARMv6 (but not x86_64) static build in addition to the dynamic stdlib would be useful.

**Comment by stefaang** [comment]
I just got Cuberite running with opkg in entware-ng on a x86-64 platform.
https://community.wd.com/t/package-entware-the-ultimate-repo-with-about-2000-packages/213711/3

I'll have a look to create a guide here as well.

**Comment by stefaang** [comment]
It's not necessary to build Cuberite yourself, it's also possible to patch the Cuberite binary to use /opt/lib/ld-2.27.so from Entware.

    cd Server
    patchelf --set-interpreter /opt/lib/ld-linux-x86-64.so.2 Cuberite
    patchelf --set-rpath /opt/lib Cuberite

I'm using Entware and this trick to run Cuberite on a NAS with glibc-2.19 firmware (while cuberite requires glibc-2.20+).
