### ISSUE TITLE
JavaScript API

### ISSUE THREAD

**Issue by bibo38** [cuberite/cuberite#3171]
While reading #3003 and #3062 I've got the idea to create a JavaScript API for Cuberite.

Cons:

- A lot of work
- New dependencies

Pros:

- Many programmers know JavaScript from Websites, Unity, ...
- Webadmin: You could write Server and Client code in one file and create a transparent communication between Browser and Server, like [Meteor](https://www.meteor.com/).

**Comment by Schwertspize** [comment]
Normal js like in a browser or js like in node.js with npm modules and such?

**Comment by bibo38** [comment]
Node.js would be nice, if this would be possible :+1: . Otherwise I would aim for ECMAScript 6 or higher.

**Comment by worktycho** [comment]
Pros:
A JavaScript API would be possible and probably easier than #3062 as you don't have to deal with converting concepts, so you could hook into the existing toluapp Binding generation.
Cons:
Significant additional maintenance burden, all manual bindings would have to be written twice, (Unless you can patch cLuaState to also represent the javascript engine.
A javascript engine would be a significant dependecy, the only lightweight one I can find is duktape http://duktape.org, Something like V8 is never going to be accepted as a core server dependency.

**Comment by LogicParrot** [comment]
Lua is very straightforward, there is almost no learning curve for those who know any other programming language. It's a very light dependency, it's easy to maintain, it's very portable, and it's pretty much enough. What problem does this solve?

Whenever people suggest Cuberite should embed another language, I am reminded of [this](http://www.danielsen.com/jokes/objecttoaster.txt).

In my opinion, this is overkill.

**Comment by Pokechu22** [comment]
The main reason why a Java API would be useful is that it would support the many existing Bukkit plugins; adding other languages just because of different language features _generally_ is unnecessary.

Of course, you _could_ always take the java API, use [Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino), and then make your own JS api.  Or write a lua-based JS interpreter.  But at some point things like that get excessive.

**Comment by Seadragon91** [comment]
This issue is about java script not java.

**Comment by bearbin** [comment]
@Seadragon91 Pokechu22 was saying the Java API would be useful, but the JavaScript API would not be useful, since there no no plugins using JavaScript already.

**Comment by tonibm19** [comment]
Well, most people uses C# with unity.
And I think if Cuberite has to implement a new api, it should be java, or c++ in second olace.

**Comment by SphinxC0re** [comment]
I think implementing a JS API would be a good idea because JS is much more common to developers than lua.

**Comment by NiLSPACE** [comment]
But then the question is who will be maintaining the JS bindings?

**Comment by worktycho** [comment]
Maintenance is the key question. The maintenance burden would be reduced if the javascript engine could hook into the existing lua infrastructure (tolua, cLuaState), so most of the bindings could be shared, but it is still significant.

**Comment by worktycho** [comment]
I am neither in favor or against this proposal, but if I am persuaded it is valuable, I might implement it. [Duktape](duktape.org), the js interpreter I mentioned earlier, could probably be implemented with only minor changes to the manual bindings, mainly refactoring everything to the cLuaState infrastructure. It presents the same basic API of a stack, and I believe it would be possible to expose the same cLuaState API around duktape.

**Comment by worktycho** [comment]
In comparison a C/C++/Java APIs would be significantly more work, and would require most of the manual bindings to be rewritten.

**Comment by LogicParrot** [comment]
A Javascript developer can catch up with Lua in less then half a day. I am against this; It is a completely unnecessary bloat and the only supporting argument is "I want the language I like".

**Comment by worktycho** [comment]
Thats the problem. Every language that is different enough to actually have significant advantages over lua is different enough that maintaining the bindings is significantly more work.

**Comment by curioussavage** [comment]
As a mostly JS developer I wouldn't like this. What I would like is better documentation in some regards. and maybe a lua utility function library so I don't have to reinvent the wheel. For the webadmin it would be nice to have a lua html templating lib. I saw there is a plugin for luaRocks but it looks very experimental. That is why I think some helper librarys for general purpose stuff like map/reduce etc and templating would be nice to have out of the box.

**Comment by SamJBarney** [comment]
I am against adding a secondary binding, especially javascript. The Lua VM is nice and small, plus it is decently easy to extend, but javascript is a pain in the butt to work with.

**Comment by tigerw** [comment]
Hey, you're back again! :D

**Comment by madmaxoft** [comment]
Closing this, since the general feeling is against this.
