### ISSUE TITLE
Cuberite not working with vlan

### ISSUE THREAD

**Issue by Disinterpreter** [cuberite/cuberite#3175]
### Expected behavior

Cuberite must work with VLAN (because forge working)
### Actual behavior

Cuberite don't work with VLAN (i dunno why, ip doesn't work)
eth0      Link encap:Ethernet  HWaddr 08:00:**:**:**:**
          inet6 addr: 2a02:17d0:197:QQQ::QQ/128 Scope:Общий
          inet6 addr: fe80::a00:27ff:fec3:ba1e/64 Scope:Link
eth0.18   Link encap:Ethernet  HWaddr 08:00:QQQ:QQ:QQ:QQ
          inet addr:46.QQ.QQ.QQQ  Bcast:46.QQ.QQ.QQ Mask:255.255.255.224
          inet6 addr: fe80::a00:27ff:fec3:ba1e/64 Scope:Link
### Steps to reproduce the behavior
1. Create VLAN on router
2. Create VLAN on switch
3. Create VLAN on linux-machine (it's internet vlan)
4. Starting server
5. Try to connect

**Comment by worktycho** [comment]
Whats the output of netstat? IPv6 might be causing issues.

**Comment by Disinterpreter** [comment]
[](http://i.imgur.com/5KQvU54.png)

**Comment by worktycho** [comment]
And are you trying to connect on ipv4? That looks like we are only listening on v6 for some reason.

**Comment by Disinterpreter** [comment]
yes,  i want connect to ipv4, but external network ipv4 work only through vlan.

**Comment by source83** [comment]
I suspect I have the same problem, the VM I've got at a hosting company might (or most possibly is) using vlan's.

**Comment by source83** [comment]
"TCP: request_sock_TCP: Possible SYN flooding on port (my web interface port) Dropping request.  Check SNMP counters."
I get this every time I try to connect to the web interface or to the mc server itself.
What port I use, has so far not yielded any difference.

**Comment by source83** [comment]
Ignore my previous messages, I found that it worked with sysctl -w net.ipv4.tcp_syncookies="1"
