### ISSUE TITLE
Investigate cClientHandle related crashes

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3182]
This is a general issue. 

It appears that almost 100% of the current crashes happen in `cClientHandle` and its surrounding classes such as `cChunkSender`, `cTCPLinkImpl`. I've decided to investigate this and see if I can fix it. Also, I've created a milestone called "[cClientHandle stability](https://github.com/cuberite/cuberite/milestones/cClientHandle%20stability)" which will include all issues related to this.

Fixing this would be a major stability boost.

**Comment by LogicParrot** [comment]
@tigerw advertising #3155 in 3, 2 ...

**Comment by tigerw** [comment]
You first said 3155, and I was like, wait... that isn't quite right...

In any case, you've done it for me now :)
