### ISSUE TITLE
Tamed wolfes will not do through doors

### ISSUE THREAD

**Issue by ahyattdev** [cuberite/cuberite#3185]
### Expected behavior
The wolf will go through the door to follow the player

### Actual behavior
The wolf sees the door as a block it can't go through

### Steps to reproduce the behavior
Tame a wolf, put a door and a wall between you and the wolf

### Workaround
Make a 1 block tall opening next to the door as a "dog door"

**Comment by LogicParrot** [comment]
This is already covered by #2062 and #2793
