### ISSUE TITLE
Potential missing sounds in 1.9

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3190]
### Expected behavior
Normally you'd at least hear the sounds of mobs dying when you kill them.

### Actual behavior
You don't, right now, at least when connected using protocol 1.9. I suspect more such
problems exist.

**Comment by jammet** [comment]
Closed because this seems to be more wide spread and just listing individual sound problems would be  a bit much.

**Comment by LogicParrot** [comment]
This could be a 1.9-specific issue though

**Comment by LogicParrot** [comment]
Sorry, with my modifications, it's a dupe of #3189. Closing.
