### ISSUE TITLE
Creeper explosions cause grass blocks to drop themselves rather than dirt blocks

### ISSUE THREAD

**Issue by ahyattdev** [cuberite/cuberite#3194]
Client version:   1.9.4
Commit id: a4f327118b06ced1cd4510b7d20d34da83aa78a3
### Expected behavior

Grass drops will turn to dirt blocks in an explosion
### Actual behavior

They drop grass blocks
### Steps to reproduce the behavior

Have a creeper blow up on some grass and dirt

**Comment by ahyattdev** [comment]
Also, stone drops stone instead of cobblestone

**Comment by ahyattdev** [comment]
Not sure since when, but this issue is no longer present.

**Comment by mathiascode** [comment]
This issue is not fixed.

**Comment by tigerw** [comment]
Possibly a combination of shrapnel (spawns FallingSand entities with block type Grass) and #1001, causing those entities to drop said Grass as a pickup.
