### ISSUE TITLE
Double plant blocks duplicate when placed

### ISSUE THREAD

**Issue by pfgithub** [cuberite/cuberite#3195]
Client version:   1.9.4
Commit id:        f73de02684ce2c5f9fb2e8e36cfe65dc4ac91dea
### Expected behavior

When placing a double plant, both parts of the double plant are placed
### Actual behavior

The top half of the double plant dissapears and drops two double plant items of that type
### Steps to reproduce the behavior

Place any double plant

**Comment by peterbell10** [comment]
Can't reproduce, must've been fixed at some point.  Possibly by #3826.
