### ISSUE TITLE
Piston pushing has no animation

### ISSUE THREAD

**Issue by pfgithub** [cuberite/cuberite#3198]
Client version:   1.9.4
Commit id:        f73de02684ce2c5f9fb2e8e36cfe65dc4ac91dea
### Expected behavior

When a redstone signal is applied to a piston, an extending animation will be shown
### Actual behavior

When a redstone signal is applied to a piston, the block it's pushing teleports
### Steps to reproduce the behavior

Put a block infront of a piston and apply a redstone signal

**Comment by mathwhiz1212** [comment]
This is bug present using a 1.8.9 client and https://github.com/cuberite/cuberite/commit/fea664f2cfb25902bf1b64c29da1c27804b81c15

**Comment by beta-phenylethylamine** [comment]
It's also notable that (using 1.8.9), pistons don't push players. If the block that's "teleported" into the player is solid, the player is pushed out of the block (just like any case when a player finds themselves inside a solid block) and otherwise, they just stand inside it.
