### ISSUE TITLE
Cannot compile in DEBUG mode on FreeBSD

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#3200]
Error log is on the buildserver:

https://builds.cuberite.org/job/Cuberite%20FreeBSD%20x64%20ingame-testing-needed/4/console

**Comment by worktycho** [comment]
Somethings going wrong with cmake autodetection. Just a suggestion, but CMake may be choking on the spaces in the build dir name. Can you try renaming this, so we can see if its a problem with the build dir name.

**Comment by bearbin** [comment]
@worktycho You're right, it's the same issue as with the old main build, I totally forgot about it. I will rename the build dir.

Is there any way that we can fix cmake choking on spaces?

**Comment by worktycho** [comment]
Not that I know of.
