### ISSUE TITLE
Downloading cuberite will give scary warning / Expired cert

### ISSUE THREAD

**Issue by mathwhiz1212** [cuberite/cuberite#3203]
### Expected behavior

It would download normally.

### Actual behavior

The encryption certificate of builds.cuberite.org is expired as of this morning. May I suggest automatically renewing with [certbot](https://certbot.eff.org/).

It prints scary warnings like:

![cuberite-download](https://cloud.githubusercontent.com/assets/11021683/15331920/c4682886-1c20-11e6-995c-4bf10f28f2f5.png)

### Steps to reproduce the behavior

Try to download cuberite. https://builds.cuberite.org/job/Cuberite%20Linux%20x64%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz

**Comment by bearbin** [comment]
The problem is now solved. My certificate reminder provider failed to remind me, I need to get a new one...

**Comment by mathwhiz1212** [comment]
https://certbot.eff.org/ makes it easy to auto-renew if you have access to the server.
