### ISSUE TITLE
Getting Kicked by breaking too many Blocks

### ISSUE THREAD

**Issue by FlorianFH** [cuberite/cuberite#3205]
Commit id:        approx: a75fb13f99aff238fcc8c7471919f04e03945e47 built at: approx: 2016-05-16 10:23:11 +0100

Hi,
I use Cuberite on an Banana-Pi with
Linux bananapi 3.4.111-bananian #5 SMP PREEMPT Fri Mar 25 17:24:42 UTC 2016 

I played alone and was killing a Tree with an ironaxe during the Server crash with the message 
"Kicking player Ikillufs for "Too many blocks were destroyed per unit time - hacked client?""
After Server Restart, I lost my 18 Levels and all my items, i was set to worlds spwan point as a new player without archivements.

Today I was building a room with an stonepickaxe, the durability of this axe was 0 but always in my Hand/ Inventory. By Hacking one last Block the Server Kicks me. Now I am again a new player without Levels, Inventroy and Archivements.

``````
Info [08:15:53] Kicking player Ikillufs for "Too many blocks were destroyed per unit time - hacked client?"
Info [08:15:54] Player Ikillufs has left the game
Err  [08:16:14] Deadlock detected, aborting the server
Err  [08:16:14]   D:    | Cuberite has encountered an error and needs to close
Err  [08:16:14] Details | SIGABRT: Server self-terminated due to an internal fault
Err  [08:16:14] Cuberite local build build id: Unknown
Err  [08:16:14] from commit id: approx: a75fb13f99aff238fcc8c7471919f04e03945e47 built at: approx: 2016-05-16 10:23:11 +0100
 [08:16:14] Shutting down server...```
``````

I have stored the Logs and core files with my settings.ini and world.ini here:
[http://www.mediafire.com/download/ewddphl21yubd14/Hack_too_many_Blocks_190516.tar](url)

Thanks for helping me out

**Comment by bearbin** [comment]
Did the server crash, or did it just kick you?

**Comment by FlorianFH** [comment]
On this time the Server kick me and shutted down.
At the first time the Server-log says : 

`Info [22:14:29] Kicking player Ikillufs for "Too many blocks were destroyed per unit time - hacked client?"
Info [22:14:29] Player Ikillufs has left the game
Err  [22:14:49] Deadlock detected, aborting the server
Err  [22:14:49]   D:    | Cuberite has encountered an error and needs to close
Err  [22:14:49] Details | SIGABRT: Server self-terminated due to an internal fault
Err  [22:14:49] Cuberite local build build id: Unknown
Err  [22:14:49] from commit id: approx: a75fb13f99aff238fcc8c7471919f04e03945e47 built at: approx: 2016-05-16 10:23:11 +0100`

I think a Deadlock is like a Servercrash?

**Comment by Pokechu22** [comment]
A deadlock means that the server stopped responding (it took too long to complete a tick).

Most likely, the server was already frozen when you were trying to break the blocks, and thus breaking all of those blocks "at once" (to the server) would trigger that check.  If it's stuck on the same tick for 30 seconds, and you break 10 blocks in that tick, then that appears (to the server) as if you broke 10 blocks in what _normally_ is a 1/20th of a second.  The fact that the server froze is still a bug (and the fact that it destroyed your items probably is a bug), but it makes _some_ sense.

**Comment by FlorianFH** [comment]
Ok, this means to me, that thees problems cohere with my Banana-PI?
How can i prevent the deadlocks?

**Comment by spekdrum** [comment]
Now you can disable this check. I know it's not a solution but maybe it helps on slow machines.
Simply put this in settings.ini:
```
[AntiCheat]
LimitPlayerBlockChanges=0
```

**Comment by FlorianFH** [comment]
Ok @spekdrum i added your line to my settings.ini and keep playing slowlier to prevent me for freezing the server.
Thanks to all of you
