### ISSUE TITLE
Presence of shield crashes 1.8 clients

### ISSUE THREAD

**Issue by mathwhiz1212** [cuberite/cuberite#3206]
Client version:   1.8.9
Commit id:  https://github.com/cuberite/cuberite/commit/fea664f2cfb25902bf1b64c29da1c27804b81c15

### Expected behavior

It would work fine, maybe look weird.

### Actual behavior

It crashes any and all 1.8 clients.

### Steps to reproduce the behavior

Try to craft a shield using 1.8 client or craft a shield with a 1.9 client and put it in your hand then logout and login with a 1.8 client and watch it instantly crash.

**Comment by bearbin** [comment]
This is expected behaviour. For more discussion please see #3201

**Comment by mathwhiz1212** [comment]
ok

**Comment by LogicParrot** [comment]
I wouldn't call that "expected". It's the *current* behavior, yeah.
