### ISSUE TITLE
Pumpkins always look like Jackolanterns

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3209]
Client version:   1.9.4
Commit id:    a4f327118b06ced1cd4510b7d20d34da83aa78a3

Pumpkins growing at the farm now look like unlit Jackolanterns.

**Comment by madmaxoft** [comment]
Hasn't that always been the case? I mean, the pumpkins have always had direction data, and what would the purpose be other than to display the jack'o'lantern face?

**Comment by bearbin** [comment]
In fact, the 1.9 update removed unfaced pumpkins.

http://minecraft.gamepedia.com/15w31a

**Comment by bearbin** [comment]
http://minecraft.gamepedia.com/Pumpkin#History

**Comment by jammet** [comment]
My apologies, I could have sworn we've had faceless pumpkins up until now -- guess I've been mistaken and they had faces no matter what. Sorry.

**Comment by LogicParrot** [comment]
@jammet It seems you've had them until 1.9 removed them.
