### ISSUE TITLE
Lua function to get list of names of all the teams

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#3210]
Currently I'm trying to get rid of teams that do not appear in my database as well. As `cScoreboard:RemoveTeam()` requires a name of the team, which I don't know because it doesn't exist in my database, I have no way to remove said team. A way to retrieve a list of all the names of the teams would allow me to compare it to my database and thus fix the problem.

**Comment by PureTryOut** [comment]
Just a note, I've setup a $10 bounty for this issue on Bountysource.

**Comment by PlasmaPower** [comment]
Shouldn't be too hard, I should have this done soon.

**Comment by PlasmaPower** [comment]
Is there a good way to quickly check if my Lua bindings are working? I think I might have it done, but I'm not sure how to test it.

**Comment by madmaxoft** [comment]
Usually we put some kind of a simple test in the Debuggers plugin.
