### ISSUE TITLE
Kicked from server when mounting wild horse

### ISSUE THREAD

**Issue by onlybuilt4cubanlinx** [cuberite/cuberite#3213]
Client version:   1.9.4
Commit id:        (Found at the top of the server's console output)

mount wild horse
kicked from server

Join new survivor wold and mount a wild horse
![20160525150450_1](https://cloud.githubusercontent.com/assets/19557618/15552815/345c2218-228a-11e6-9690-6745b3637399.jpg)

**Comment by LogicParrot** [comment]
Horses are completely broken. I think they're a good candidate for being disabled by default until they are fixed.

**Comment by PureTryOut** [comment]
Since [the issue reporting broken behaviour when riding a horse](https://github.com/cuberite/cuberite/issues/703) is more than 2 years old, I indeed also think they should be disabled by default till they are fixed. This at least removes the hopes of people trying to ride them.

**Comment by PureTryOut** [comment]
I can report that this doesn't happen (anymore), running a 1.10 client on the latest git build. Horses are still really broken though.

**Comment by Bond-009** [comment]
I can't reproduce this issue with 1.9.4, maybe it has been fixed?

**Comment by bearbin** [comment]
Closing as stale, and non-reproducible.
