### ISSUE TITLE
No Fall damage or Drowning Damage

### ISSUE THREAD

**Issue by jungerm2** [cuberite/cuberite#3216]
Client version:   1.9.4
Commit id:        30e6425ed3e2d2c458158c9b8dd0838b60637c32

### Expected behavior
When the player jumps from a high place in survival, there should be fall damage.
when a player stays underwater without any protective gear and has no air left, he should take damage.

### Actual behavior
No damage is taken whatsoever.

### Steps to reproduce the behavior
Simply jump from a high place or stay underwater for a long time (In survival mode)

**Comment by fralix** [comment]
I tested with 1.8.9 and got drowning damage.

**Comment by jungerm2** [comment]
So it's only a 1.9.4 issue? Can anyone confirm this?

**Comment by SphinxC0re** [comment]
Since 1.9 isn't feature-complete ATM this might be just a 1.9 issue

**Comment by fralix** [comment]
tested with 1.9.4 - I get the drowning damage. I am unable to reproduce your 2nd part of the issue!

**Comment by M10360** [comment]
I'm betting it has something to do with this: https://bugs.mojang.com/browse/MC-212

**Comment by fralix** [comment]
I don't think so.
"MC-212" means, that you will not get fall damage if you quit the server / the world in the air. After that you only get the damage from the height you relogged in.

The issue here means, that you will not get **any** fall damage at all.
