### ISSUE TITLE
Minor segmentation fault issue (port allocation failed)

### ISSUE THREAD

**Issue by marcdraco** [cuberite/cuberite#3221]
Client version:   x.x.x
Commit id:  Unknown (see below)

This a MINOR issue. When the server (cuberite) is running and I try to run it again, it should clean exit when the port cannot be allocated.  (I'm experimenting with multiple servers on a single machine.)

I also note that port is requested quite late in the initialisation - perhaps it would be better to have this happen earlier? 
### Expected behavior

Clean exit
### Actual behavior

Segmentation fault

[18:20:42] Cannot listen on port 25565: 98 (Cannot bind IPv6 socket to port 25565: 98 (Address already in use)).
[18:20:42] Couldn't open any ports. Aborting the server
[18:20:42] Unloading worlds...
[18:20:43] Disabled TransAPI!
[18:20:43] [WorldEdit] Disabling WorldEdit v0.1.6
[18:20:43] Disabled Core!
[18:20:43] Cleaning up...
[18:20:43]   D:    | Cuberite has encountered an error and needs to close
[18:20:43] Details | SIGSEGV: Segmentation fault
[18:20:43] Cuberite local build build id: Unknown
[18:20:43] from commit id: approx: 98cc2a99875d99761308d8270e890faa40adf935 built at: approx: 2016-05-28 15:06:57 +0100
./Cuberite(_Z15PrintStackTracev+0xb)[0x1c9528]
./Cuberite[0x1bcf82]
/lib/arm-linux-gnueabihf/libc.so.6(+0x26ae0)[0xb6d6bae0]
[18:20:43]   D:    | Cuberite has encountered an error and needs to close
[18:20:43] Details | SIGABRT: Server self-terminated due to an internal fault
[18:20:43] Cuberite local build build id: Unknown
[18:20:43] from commit id: approx: 98cc2a99875d99761308d8270e890faa40adf935 built at: approx: 2016-05-28 15:06:57 +0100
./Cuberite(_Z15PrintStackTracev+0xb)[0x1c9528]
./Cuberite[0x1bcf82]
/lib/arm-linux-gnueabihf/libc.so.6(+0x26ae0)[0xb6d6bae0]
/lib/arm-linux-gnueabihf/libc.so.6(+0x178e6)[0xb6d5c8e6]
/lib/arm-linux-gnueabihf/libc.so.6(gsignal+0x25)[0xb6d6aee6]
/lib/arm-linux-gnueabihf/libc.so.6(abort+0xbd)[0xb6d6bbee]
### Steps to reproduce the behavior

Start a server.
Start a new server in the same directory! (Yes, I know this is not the done thing!)

**Comment by Seadragon91** [comment]
Cuberite reports correctly that no ports can't be opened. It stops the server but crashes because of a other problem.
Backttrace of all threads from debug build:
```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000000f2fd97 in epoll_wait (epfd=3, events=0x291a840, maxevents=32, timeout=-1)
    at /home/lukas/cpp/cuberite/lib/libevent/epoll_sub.c:64
#2  0x0000000000f2ee02 in epoll_dispatch (base=0x291adf0, tv=0x0)
    at /home/lukas/cpp/cuberite/lib/libevent/epoll.c:462
#3  0x0000000000f17d8e in event_base_loop (base=0x291adf0, flags=4)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:1943
#4  0x00000000009e306f in cNetworkSingleton::RunEventLoop (a_Self=0x1466808 <cNetworkSingleton::Get()::Instance>)
    at /home/lukas/cpp/cuberite/src/OSSupport/NetworkSingleton.cpp:159
#5  0x00000000009e5b82 in std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x29182c8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/functional:1399
#6  0x00000000009e5b35 in std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)>::operator()() (
    this=0x29182c8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/functional:1389
#7  0x00000000009e58f9 in std::thread::_State_impl<std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)> >::_M_run() (this=0x29182c0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/thread:196
#8  0x00007f5ea5e91cdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f5ea6160464 in start_thread (arg=0x7f5ea5822700) at pthread_create.c:333
#10 0x00007f5ea590b9df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 1 (Thread 0x7f5ea6c99b80 (LWP 780)):
#0  __pthread_kill (threadid=0, signo=9) at ../sysdeps/unix/sysv/linux/pthread_kill.c:39
#1  0x000000000096e18d in cRoot::Start (this=0x7fff87244468,
    a_OverridesRepo=std::unique_ptr<cSettingsRepositoryInterface> containing 0x0)
    at /home/lukas/cpp/cuberite/src/Root.cpp:308
#2  0x00000000009cf1aa in UniversalMain (
    a_OverridesRepo=std::unique_ptr<cSettingsRepositoryInterface> containing 0x0)
    at /home/lukas/cpp/cuberite/src/main.cpp:231
#3  0x00000000009cd723 in main (argc=1, argv=0x7fff87244968) at /home/lukas/cpp/cuberite/src/main.cpp:548
```
