### ISSUE TITLE
Falling block animation starts too high and ends too low.

### ISSUE THREAD

**Issue by fralix** [cuberite/cuberite#3222]
Client version:   1.8.9 (OptiFine) + 1.9.4 (Vanilla)
Commit id:        a567b36a8a6574208b30f8a22d3240d13a01bf63

### Expected behavior
If I place a block and he should fall down because of the gravity, he starts falling at the point I placed him and stops at the moment he hits the block below.

### Actual behavior
If I place a block and he falls down because of the gravity, the animation of the falling block starts too high and ends too low. (often it gets into the block below.)

### Steps to reproduce the behavior
Create a tower of 3 solid blocks and place a block with physics (e.g. sand, gravel, an anvil) and watch the falling animation. 
Make sure that "SandInstantFall" is disabled (=0) in the world.ini of the selected world to enable the falling animation!

**Comment by fralix** [comment]
I tried to fix the problem myself:

src/Simulator/SandSimulator.cpp - Line 56
from:
`Pos.y = itr->y;`
to
`Pos.y = itr->y - 0.1;`

That lets the block start at the correct position - but if the block stops falling at the ground it looks like a bug ;-)
I was not sure how to do better because if have to get closer to the code first. 

In general the falling animation doesn't look that smooth like in Vanilla Minecraft but I think this is fixable.

**Comment by Altenius** [comment]
I was able to fix this within the cFallingBlock class.

In src/Entities/FallingBlocks.cpp line 14:
`super(etFallingBlock, a_BlockPosition.x + 0.5f, a_BlockPosition.y + 0.5f, a_BlockPosition.z + 0.5f, 0.98, 0.98),`
to
`super(etFallingBlock, a_BlockPosition.x + 0.5f, a_BlockPosition.y, a_BlockPosition.z + 0.5f, 0.98, 0.98),`

**Comment by madmaxoft** [comment]
@Altenius  that looks like the correct solution, and is in line with my understanding of Minecraft entities - their position is given as XZ center and Y bottom. Please make a pull request with your change.

**Comment by fralix** [comment]
@Altenius sounds nice - thank you...

**Comment by fralix** [comment]
Hey, looks like it is not fixed.

Problems: The Animation starts exactly one block too low and if I remove a block, that is under something, the block above will not fall down with an animation.

I tested the animaton by settings blocks at the face of a 4 block high sand tower. Build was compiled an hour ago!

**Comment by LogicParrot** [comment]
I tested this, and it seems fixed. Are you sure you're using a recent version?

**Comment by fralix** [comment]
yes I built it a few days ago (one hour before my post). But I'll try this again!

To make sure I update the file I can easily delete src/Entities/FallingBlocks.cpp right?

**Comment by fralix** [comment]
[17cd3a55a964d453|09:42:04] --- Started Log ---
    [17cd3a55a964d453|09:42:04] Cuberite local build build id: Unknown
    [17cd3a55a964d453|09:42:04] from commit id: approx: 8107d5c3ac813622e8772357d908a712e37e3f07 built at: approx: 2016-07-29 20:40:24 +0100

is on the top of my log. Does it mean something is wrong with my update? I run compile.sh in debug and normal mode but the normal mode says "segmentation fault", the debug mode runs but looks outdated with the named date...

Got a video over here: https://openload.co/f/3NcN1DufrZs/cuberite_sand-animation.mkv (excuse the hoster but I don't like youtube)

**Comment by Seadragon91** [comment]
Looking at the commit id it's a week old: [8107d5c3ac813622e8772357d908a712e37e3f07](https://github.com/cuberite/cuberite/commit/8107d5c3ac813622e8772357d908a712e37e3f07)

**Comment by fralix** [comment]
Yes I know! But I don't know why my compile.sh stopped working. So the 1 week old commit still worked but if I run the script now it says that everything got updated and compiles it - but it looks like something is wrong...

**Comment by LogicParrot** [comment]
`compile.sh` was recently updated. It would be very helpful if you open an issue report what's wrong with it.

**Comment by fralix** [comment]
is there a way to find out if my compile.sh **is** updated? May be it isn't and something is no longer compatible!

**Comment by madmaxoft** [comment]
Running the script (either old or new) should update the sources, including the script itself.
As the last resort, you can always run `git rev-parse HEAD` at the cuberite source folder and it will tell you the exact commit number that you have there.

**Comment by fralix** [comment]
Ok I'll open an issue for the script if it should be updated.

**Comment by LogicParrot** [comment]
>is there a way to find out if my compile.sh is updated? May be it isn't and something is no longer compatible!

The old script should still be working fine.

**Comment by fralix** [comment]
I am sorry. Now I was able to update the server and everything is fine.

Sorry for reopening, it was not your fault :-)

Thanks for fixing and your support with the shell script.
