### ISSUE TITLE
Cannot edit CommandBlock's command on 1.9.2 client

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#3223]
Client version:   1.9.2
Commit id:        (Found at the top of the server's console output)
### Expected behaviour

Set CommandBlocksEnabled=1,
issue command '/give me command block'

right click to edit the commandblock's command, command editing window appears
### Actual behavior

Set CommandBlocksEnabled=1,
issue command '/give me command block'

right click to edit the commandblock's command, nothing happens
### Steps to reproduce the behaviour

As I thought it was a problem from me side, I joined cuberite's IRC and compared client versions with somebody else. When I reverted back to the 1.8.9 client, the problem was gone

**Comment by Pokechu22** [comment]
Somewhat known issue.

1.9 command blocks use a new plugin channel, [`MC|AutoCmd`](http://wiki.vg/Plugin_channels#MC.7CAutoCmd), to handle the new fields.  I don't think cuberite implements that message yet, only supporting the older [`MC|AdvCmd`](http://wiki.vg/Plugin_channels#MC.7CAdvCmd) which is used for command block minecarts.  (It previously was called `MC|AdvCdm` and was used for both).

Also, they made a change that in 1.9, command blocks don't immediately send their tile entity to the client.  Instead, they wait until the client right-clicks the tile entity and then they send the update tile entity message, and when the client receives that specific update tile entity message (_only_ for command blocks), the command block UI opens.  It's a weird change and I'm not completely sure why they made it.

**Comment by LouWade** [comment]
Thank you for replying so quickly ;)

**Comment by mathiascode** [comment]
Closing in favor of #3239
