### ISSUE TITLE
Minecraft 1.10 Protocol Support

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3229]
Now that Minecraft 1.10 is released (already), we should add protocol support for it.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=35062502)](https://www.bountysource.com/issues/35062502-minecraft-1-10-protocol-support?utm_source=35062502&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by mathwhiz1212** [comment]
Yes. I'm getting errors about users not being able to connect.

**Comment by Pokechu22** [comment]
Apart from the entity metadata changes, the actual protocol changes are minimal.  [Here's the pre-release protocol page](http://wiki.vg/index.php?title=Pre-release_protocol&oldid=7972).

But given the number of entity metadata changes it might be hard to quickly update (things got shifted).

**Comment by bearbin** [comment]
There is now a $15 bounty on this issue. https://www.bountysource.com/issues/35062502-minecraft-1-10-protocol-support

**Comment by tonibm19** [comment]
Is it really that difficult to add a new protocol?
I still remember the old days when new versions were added in a few weeks or days, and the one who did that (xoft probably) didn't receive a penny.
Now the changes between versions are less (thanks micro) and you get 15$! :P

**Comment by Pokechu22** [comment]
Adding the protocol itself isn't hard...  It's just that more recently, protocol updates have resulted in changing a bunch of constants, most painfully [entity metadata ones](http://wiki.vg/index.php?title=Pre-release_protocol&oldid=7972#Entity_Metadata).  Cuburite currently hardcodes _every single one_ of those IDs, which means that updating is pretty hard (the actual protocol changes are easy, but handling entities is still required).

**Comment by LogicParrot** [comment]
Also, adding the protocol itself has little end-user change, as long as the features themselves are not implemented. We haven't implemented any 1.9 features yet.

**Comment by tigerw** [comment]
@tonibm19 haven't seen you in some time! :)

**Comment by tonibm19** [comment]
@tigerw :D
It's been a long time...
How have you been?

**Comment by tigerw** [comment]
I've been *really* busy...

...testing.
