### ISSUE TITLE
Restart command crashes server

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3235]
Client version:   1.9.4
Commit id:        ec998e821fd905966ed14ed47a29520ec1d1d782

### Expected behavior
The restart command should restart the server.

### Actual behavior
Release mode: The server crashes, when the user reconnects after executing the restart command.
Debug mode: The server crashes on executing the restart command.
Edit: This crashes sometimes on a assert error.

### Steps to reproduce the behavior
```
1. Start the server
2. Connect to the server
3. Execute command restart (users get disconnected)
4. Reconnect to the server
```

**Comment by Seadragon91** [comment]
Bisected it down to this commit [98cc2a99875d99761308d8270e890faa40adf935](https://github.com/cuberite/cuberite/commit/98cc2a99875d99761308d8270e890faa40adf935)

**Comment by worktycho** [comment]
I say we revert that until @tigerw puts in a PR that we can discuss caching the handlers in.

**Comment by SphinxC0re** [comment]
I'm in for that
