### ISSUE TITLE
"1.9 regressions" milestone

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3241]
DId anyone remove that milestone? Why?

**Comment by SphinxC0re** [comment]
I did. Because there is already a milestone dedicated to 1.9. Also stop starting discussions on GH. Move this directly to the forum

**Comment by LogicParrot** [comment]
Those are two seperate milestones.

**Comment by LogicParrot** [comment]
`1.9` is for 1.9 features not yet implemented.
`1.9 regressions` is for 1.8 or 1.7 features that got ruined after the merge.

**Comment by SphinxC0re** [comment]
I don't think a separate milestone is necessary. Thoughts? @cuberite/core-team

**Comment by NiLSPACE** [comment]
I don't really think it's needed either.

I also agree with @SphinxC0re that these discussions should be done on the forum. Github issues should only be used if something is wrong in the code.

**Comment by LogicParrot** [comment]
`1.9 features` **have nothing to do** with `1.9 regressions` except that they were introduced in the same pull request. I should have named it `regressions` and @sphinxc0re wouldn't have noticed it and would have kept it seperate.

I repeat, regressions have nothing to do with `1.9` other than their coincidencal introduction in the same PR.

I like it when Cuberite actually gets better after each release, so I personally want to fix the regressions before every touching the 1.9 features, but now it's a bit harder to find them.  

I originally opened it as an issue in order to self-assign my self and fix it later when I get back to contributing. There was no intention for extensive discussion.

**Comment by LogicParrot** [comment]
I mean, look at https://github.com/cuberite/cuberite/issues/3186, does this have to do with 1.9 features?

It's no biggie though, ah well.
