### ISSUE TITLE
Tolua internal error when compiling

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#3269]
```
** tolua internal error: [string "../../lib/tolua++/src/bin/lua/package.lua"]:341: attempt to call global 'setfenv' (a nil value)
stack traceback:
	[string "../../lib/tolua++/src/bin/lua/package.lua"]:341: in function 'prep'
	[string "../../lib/tolua++/src/bin/lua/package.lua"]:253: in function 'Package'
	[string "../../lib/tolua++/src/bin/lua/doit.lua"]:55: in function <[string "../../lib/tolua++/src/bin/lua/doit.lua"]:27>
	[C]: in function 'xpcall'
	../../lib/tolua++/src/bin/lua/all.lua:25: in main chunk
	[C]: in function 'dofile'
	BindingsProcessor.lua:55: in function 'invokeToLua'
	BindingsProcessor.lua:990: in main chunk
	[C]: in ?.
```

Is this the fault of my code or tolua?

**Comment by madmaxoft** [comment]
That's most likely a problem with the build system, namely the changes I've introduced in PR #3204 . It tries to find the Lua interpreter in the build system and use it (which succeeded, judging by the stacktrace), but for some reason your Lua interpreter doesn't have the `setfenv()` builtin function. Can you run `lua -v` for me to see what version the interpreter is at? It should be `5.1` and the build system should refuse to use anything else.

**Comment by bearbin** [comment]
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio

**Comment by madmaxoft** [comment]
That would be the culprit. Lua 5.2 doesn't indeed have `setfenv()`.

I'll fix the build script; in the meantime if you want to build with system lua, do install the 5.1 version (`apt-get install lua5.1`) and make it the default Lua interpreter.
