### ISSUE TITLE
Add cuberite.org links for download/compile

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#3275]
i.e.

    wget download.cuberite.org | sh

**Comment by bearbin** [comment]
Service is now set up on the server:

https://download.cuberite.org
https://compile.cuberite.org

**Comment by madmaxoft** [comment]
I think the `download.cuberite.org` webserver should serve a 302 redirect to the HTML download page; the download script should have a (small) postfix to the URL. There is a possibility of people trying to visit the `download.cuberite.org` domain.

**Comment by bearbin** [comment]
GitHub pages doesn't do 302 redirects though, it would make it significantly more complicated. 

If you're worried about people being confused, adding a comment to the top of the script could be a solution?

**Comment by tigerw** [comment]
it's awfully Linux centric... Is this common practice?

**Comment by bearbin** [comment]
Yes, this is Linux only, but how often do you come across a Linux user who wants to download the server from the command line?

**Comment by madmaxoft** [comment]
How about using `dl.cuberite.org` for the script, then? And point `download.cuberite.org` to the `cuberite.org` frontpage.

**Comment by LogicParrot** [comment]
Relevant: https://github.com/cuberite/cuberite/pull/3278

>After this PR, An adversary can either comprimise Github.com or cuberite.org to infect downloaders by serving bad code, so by relying on two servers to serve the shell code, rather than one, we double the attack surface. Is this worth the aesthetical change?

**Comment by bearbin** [comment]
@madmaxoft download.cuberite.org never existed before, so I don't understand how users would be confused as to the purpose of the domain. And how would dl.cuberite.org be any better? 

I answered @"LogicParrot"'s concern in #3278.

**Comment by sphinxc0re** [comment]
Pointing `download.cuberite.org` to `cuberite.org` would be bad SEO because of duplicated content
