### ISSUE TITLE
No block update to client send after preventing item use with HOOK_PLAYER_USING_ITEM

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#3276]
**Client version:**   1.9.4
**Server OS:**        Linux
**Commit id:**        b403ad4d68eb1e730d5b514d3bfceea0de932bfa

I am trying to prevent players from using flint and tinder to set blocks on fire under certain conditions. Although whatever is supposed to happen (in this case setting a block on fire) is correctly blocked, the client still sees the fire. Relogging fixes this and the fire is gone.
#### Expected behavior

The client receiving a block update telling the block is not on fire
#### Actual behavior

The client receives no update and thinks the block is on fire
#### Steps to reproduce the behavior

Prevent fire from happening when a player uses flint and steel by using the HOOK_PLAYER_USING_ITEM hook. If you want to see if the fire is properly blocked or not, relog or use a second account.

**Comment by PureTryOut** [comment]
It doesn't update on placing water or lava using a bucket either, so it's definitely in the hook.

**Comment by pwnorbitals** [comment]
Is this still a problem on latest builds ?

**Comment by tigerw** [comment]
The code in cClientHandle::HandleRightClick looks like it'll resend blocks if the UsingItem hook was cancelled. Pending testing I believe this has been fixed.

**Comment by tigerw** [comment]
Hooked HOOK_PLAYER_USING_ITEM and returned true. Clientside fire/water extinguished.
