### ISSUE TITLE
compile.sh - cuberite doesn't update

### ISSUE THREAD

**Issue by fralix** [cuberite/cuberite#3294]
Server OS:       Linux Mint 17.3 with MATE-Desktop

### Expected behavior
If I run compile.sh, cuberite should update to the latest version and compile.

### Actual behavior
Cuberite downloads some sources but my commit is a week old!

    [273fcffe9f81a75e|15:35:55] --- Started Log ---
    [273fcffe9f81a75e|15:35:55] Cuberite local build build id: Unknown
    [273fcffe9f81a75e|15:35:55] from commit id: approx: 8107d5c3ac813622e8772357d908a712e37e3f07 built at: approx: 2016-07-29 20:40:24 +0100

### Steps to reproduce the behavior
Run compile.sh and look at the result of the compiled executable!

Additionally the normal mode got a Segmentation fault but the debug mode compiles normally so I can't give more details! (may be this is because it doesn't update correctly)

**Comment by LogicParrot** [comment]
Could you provide the `compile.sh` output?

**Comment by Schwertspize** [comment]
I assume it is a git error, that happens sometimes when non-code (stuff that is used while server running) is in the git repo. I also assume gut denies auto merging but wonder why execution resumes. Probably it's because our new compile.sh doesn't have the fixing 'code bracket' which makes the code stop when one command fails; without it the script would continue. As last I wonder why git stuff like ===== and HEAD at conflicts doesn't hinder compilation or anything. 

These were my thoughts as they occurred. I did check nothing like eg my assumption for compile.sh so please don't offend me if I'm wrong (I remember to have read through the code today but didn't notice the bracket but it may be there)

**Comment by fralix** [comment]
If I run compile.sh now.

```
Hello, this script will download and compile Cuberite.
On subsequent runs, it will update Cuberite.
The compilation and download will occur in the current directory.
If you're updating, you should run: <Path to Cuberite>/compile.sh
Compiling from source takes time, but it usually generates faster
executables. If you prefer ready-to-use binaries or if you want
more info, please visit:  http://cuberite.org/

Choose compile mode:
* (N)Normal:  Compiles normally.
              Generates the fastest build.

* (D)Debug:   Compiles in debug mode.
              Makes your console and crashes more verbose.  
              A bit slower than Normal mode. If you plan to help
              development by reporting bugs, this is preferred.
		

Note that the script will connect to the internet in order to fetch
code after this step. It will then compile your program.

Choose compile mode: (n/d): d

 --- Downloading Cuberite's source code from the master branch...
 --- Updating the master branch...
Von https://github.com/cuberite/cuberite
 * branch            master     -> FETCH_HEAD
Bereits auf 'master'
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
Already up-to-date.
 --- Updating submodules...
 --- Running cmake...
-- Lua 5.1 has NOT been found in your system, the build will use its own Lua implementation.
-- JsonCpp Version: 1.6.4
-- SQLITECPP_RUN_CPPLINT OFF
-- SQLITECPP_RUN_CPPCHECK OFF
-- SQLITECPP_RUN_DOXYGEN OFF
-- SQLITECPP_BUILD_EXAMPLES OFF
-- SQLITECPP_BUILD_TESTS OFF
-- GCC Version >= 2.95 enabling no-strict-aliasing
including polarssl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fralix/cuberite/cuberite/build-cuberite
 --- Compiling...
[  1%] Built target jsoncpp_lib_static
[  5%] Built target zlib
[  6%] Built target SQLiteCpp
[ 12%] Built target lua
[ 13%] Built target expat
[ 18%] Built target event_core
[ 23%] Built target event_extra
[ 38%] Built target mbedtls
[ 40%] Built target HTTPServer
[ 41%] Built target Items
[ 42%] Built target Blocks
[ 43%] Built target Protocol
[ 46%] Built target PolarSSL++
[ 48%] Built target Simulator
[ 56%] Built target Mobs
[ 56%] Built target IncrementalRedstoneSimulator
[ 60%] Built target BlockEntities
[ 62%] Built target UI
[ 63%] Built target tolualib
[ 64%] Built target sqlite
[ 64%] Built target luaexpat
[ 68%] Built target OSSupport
[ 69%] Built target tolua
[ 69%] Built target Noise
[ 71%] Built target WorldStorage
[ 74%] Built target Bindings
[ 80%] Built target Entities
[ 87%] Built target Generating
[100%] Built target Cuberite


-----------------
Compilation done!

Cuberite awaits you at:
/home/fralix/cuberite/cuberite/Server/Cuberite_debug

You can always update Cuberite by executing:
/home/fralix/cuberite/cuberite/compile.sh

Enjoy :)
```

```
git rev-parse HEAD
8107d5c3ac813622e8772357d908a712e37e3f07
```

But 8107d5c3ac813622e8772357d908a712e37e3f07 is outdated.

**Comment by LogicParrot** [comment]
Nothing seems out of the ordinary. Is there a chance you have *two* Cuberite folders for some reason, and are updating one of them but using the other one or executing `git rev-parse ` in the other one?

**Comment by Schwertspize** [comment]
@fralix for the next time when you post something somewhere and the system is half English and German. Prepend the command with LC_ALL=C (set the variable LC_ALL to C) which makes all commands run in their default language which is mostly English. ;) but I don't see any problem in the real output

**Comment by bearbin** [comment]
I'm closing this as @fralix has not updated in a month.

**Comment by fralix** [comment]
Oh sorry. sure. 
Can be closed as the new script looks working.
