### ISSUE TITLE
Unversioned file code_out.cpp after compilation

### ISSUE THREAD

**Issue by bibo38** [cuberite/cuberite#3296]
Client version:   Not required
Server OS:        Linux with gcc
Commit id:        ad9fc1767321fc0bd11aaa85f4e5d81177cca7cc

### Expected behavior

After a clean compilation of cuberite there should be no changed/added files in the VCS.

### Actual behavior

After a clean compilatio of cuberite the file `src/Bindings/code_out.cpp` is unversioned.

    On branch master
    Your branch is up-to-date with 'origin/master'.
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
    
    	src/Bindings/code_out.cpp
    
    nothing added to commit but untracked files present (use "git add" to track)

### Steps to reproduce the behavior

- Check out Cuberite
- Execute `cmake .. && make` in the build directory

**Comment by madmaxoft** [comment]
Oops, that would be a leftover of my playing with the bindings generator. The file is harmless, and as you noted, is unversioned, so it doesn't actually cause any trouble other than showing up on git's suggestions for staging.
I'll fix that.

**Comment by Seadragon91** [comment]
Beated by a second :)

**Comment by bibo38** [comment]
@madmaxoft I would furthermore suggest a test for the CI (TDD :wink:  )

**Comment by Seadragon91** [comment]
@bibo38 Interesting idea, just running `git status` and checking the output of the command would be enough :smiley:

**Comment by bibo38** [comment]
@Seadragon91 Or use `git status -s` to omit the text parsing. Eg. `if [[ $(git status -s) ]]` shoud trigger, when a modification happened. Otherwise the command returns nothing.

**Comment by Seadragon91** [comment]
On second thought, the file .gitignore would must be adapted, because of generated directories from the build process.

**Comment by Seadragon91** [comment]
@madmaxoft You are creating the pull request to add the file? You were quicker :)

**Comment by madmaxoft** [comment]
I'll create a PR to comment out the file's generating at all, it is not needed for the build process (it was only useful for me to see what ToLua++ actually sees before parsing).
