### ISSUE TITLE
Creation of the API Doc is broken

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3297]
Commit id:        f07dc71648eec56d88a35f42d55bfa8d007e8fab

### Expected behavior
The hooks and article links should working.

### Actual behavior
The hooks and article links are not working.

@tigerw mentioned it in the [forum](https://forum.cuberite.org/thread-434-post-26308.html#pid26308).

### Steps to reproduce the behavior
Browse to http://api-docs.cuberite.org/ and look at articles and hooks. All hooks are not documented and links are also missing.

Have looked into that and after reverting [Fixed RasPi builds of unit tests.](https://github.com/cuberite/cuberite/pull/3281) it works fine again.

I think the problem lies in the combination of `ASSERT` and `_DEBUG`. Example:
The 2 variables are only available in debug mode.
[LuaState.cpp#L1697L1700](https://github.com/cuberite/cuberite/blob/master/src/Bindings/LuaState.cpp#L1697L1700)
```
#ifdef _DEBUG
	auto srcTop = lua_gettop(a_SrcLuaState);
	auto dstTop = lua_gettop(m_LuaState);
#endif
```
but they are accessed here, in release mode:
[LuaState.cpp#L1706L1707](https://github.com/cuberite/cuberite/blob/master/src/Bindings/LuaState.cpp#L1706L1707)
```
ASSERT(lua_gettop(a_SrcLuaState) == srcTop + 3);
ASSERT(lua_gettop(m_LuaState) == dstTop + 1);
```

**Comment by Seadragon91** [comment]
This is strange, how can the code be compiled, when variables are not available in release mode?

**Comment by madmaxoft** [comment]
Very strange, looking into this...

**Comment by madmaxoft** [comment]
The API docs gerenate OK for me when compiled in Debug mode, now trying Release mode.

**Comment by madmaxoft** [comment]
And it fails in Release mode for me, too. wtf?

**Comment by madmaxoft** [comment]
`cFile:GetFolderContents()` is failing, it always returns the Cuberite's folder contents, no matter what folder you give it as the parameter. Therefore, the API descriptions from the subfolders aren't loaded.

**Comment by madmaxoft** [comment]
So the problem is almost a year old, I used `ASSERT` instead of `VERIFY`, and now with the RasPi fixes it finally became true that `ASSERT` isn't generated into Release builds, so the actual Lua params weren't read from the `cLuaState`.

Fixing...
