### ISSUE TITLE
Using cFile:GetFolderContents in combination with cFile:Delete can be dangerous

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3299]
### Expected behavior
The function `cFile:GetFolderContents` should return the content of a folder, but without the current folder and the upper folder..

### Actual behavior
The function `cFile:GetFolderContents` returns the content of a folder.
Problem here is that it also returns the current folder and the upper folder. In combination with `cFile:Delete`, it deletes the current folder and the upper folder
Example Plugin APIDump, has this problem [main_APIDump.lua#L1288L1289](https://github.com/cuberite/cuberite/blob/master/Server/Plugins/APIDump/main_APIDump.lua#L1288L1289)
```
API/Static/.
API/Static/..
API/Static/.gitignore
API/Static/decoda_debug_settings.png
API/Static/decoda_logo.png
API/Static/decoda_workspace.png
API/Static/zbs_logo.png
API/Static/zbs_workspace.png
```
The plugin APIDump loops over the content of the folder API/Static and deletes all files/folders in the current folder and in the upper folder.

### Steps to reproduce the behavior
1) Rename/Delete a already existing API folder in the root directory
2) Enable the plugin APIDump
3) Start the server
4) Run the command api

The folder API is not existent and in the sever console comes this message:
```23:13:01] Cannot output HTML API: API/index.html: No such file or directory```

### Scenario:
A developer writes a plugin where the player files are in a folder named `CTF/playefiles`. He is testing his reset function, that loops over the folder content and uses `cFile:Delete`. Only to find then out that his whole plugin is deleted.

### Solution
The function `cFile:GetFolderContents` shouldn't return the upper and current folder.

**Comment by madmaxoft** [comment]
I first wanted to reject this, on the basis that all OS APIs I know return those entries, but then decided that it is indeed pretty useless to include "." and ".." in the results and have each and every client code check for them explicitly. So the PR is ready for review.
