### ISSUE TITLE
Cuberite destroys/ignores custom motd.txt

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3302]
Every time I launch the current server version, it replaces my custom motd.txt with a default! When I make the file read-only, it's not being used entirely.

**Comment by NiLSPACE** [comment]
That is strange. It does look if the file exists before it writes it: https://github.com/cuberite/Core/blob/master/motd.lua#L9

**Comment by LogicParrot** [comment]
@jammet Did this ever work before?

**Comment by jammet** [comment]
Yes, up until now. It does work with this: 

[15:34:29] --- Started Log ---
[15:34:29] Cuberite Jenkins gcc armhf Release (master) build id: #492
[15:34:29] from commit id: a2a9341c24609e45e563427eecc1a927ee2b657a built at: Thu 21 Jul 13:03:23 CEST 2016

**Comment by LogicParrot** [comment]
As in, are you aware if MOTD ever worked for you before?

**Comment by jammet** [comment]
Yes, it's been working for over a year.

**Comment by Seadragon91** [comment]
@jammet Do you have the latest release? There was a bug introduced, that has broken the cFile API.

**Comment by jammet** [comment]
That happened when I tried a build from yesterday.  This one:

     [15:24:19] Cuberite Jenkins gcc armhf Release (master) build id: #512
     [15:24:19] from commit id: f07dc71648eec56d88a35f42d55bfa8d007e8fab built at: Sat  6 Aug 16:34:19 UTC 2016

**Comment by Seadragon91** [comment]
@jammet This commit contains the bug, after update and rebuild it should work again.

**Comment by jammet** [comment]
Confirmed, thank you for the quick help with this. <3
