### ISSUE TITLE
Compilation for ARM fails in DEBUG mode.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#3309]
https://builds.cuberite.org/job/cuberite/job/master/job/linux-odroid-c1/job/debug/6/console

```
/home/jenkins/workspace/cuberite/master/odroid-c1/debug/lib/polarssl/library/bignum.c: In function ‘mpi_mul_hlp’:
/home/jenkins/workspace/cuberite/master/odroid-c1/debug/lib/polarssl/library/bignum.c:1131:1: error: r7 cannot be used in asm here
 }
 ^
lib/polarssl/library/CMakeFiles/mbedtls.dir/build.make:192: recipe for target 'lib/polarssl/library/CMakeFiles/mbedtls.dir/bignum.c.o' failed
```

**Comment by madmaxoft** [comment]
There's not much we cam do for 3rd party libraries

**Comment by LogicParrot** [comment]
We could report this upstream.

**Comment by madmaxoft** [comment]
We should first check that it is not a misconfiguration on our side.

**Comment by peterbell10** [comment]
Looks like the build is [still broken](https://builds.cuberite.org/job/cuberite/job/master/job/linux-odroid-c1/job/debug/).  From [here](https://builds.cuberite.org/job/cuberite/job/master/job/linux-odroid-c1/job/debug/ws/lib/polarssl/library/CMakeFiles/mbedtls.dir/flags.make/*view*/) it seems that `-fomit-frame-pointer` is still not being set.

**Comment by peterbell10** [comment]
The [cmake docs](https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-linux) seem to suggest that `CMAKE_SYSTEM_PROCESSOR` should be set in the toolchain file but the [one from the build](https://builds.cuberite.org/job/cuberite/job/master/job/linux-odroid-c1/job/debug/ws/c1.cmake/*view*/) doesn't.

**Comment by bearbin** [comment]
What should I set the value to?

**Comment by peterbell10** [comment]
The docs just set it to `arm`.

**Comment by peterbell10** [comment]
Looks like mbedTLS's [CMakeLists.txt][1] also stomps over our compile flags.

[1]:https://github.com/cuberite/polarssl/blob/4f4c5b7450631e46a94cb89adf4a7737fbb178bc/CMakeLists.txt#L6-L27

**Comment by bearbin** [comment]
Well, I changed the buildserver files to set the flag, but no luck - https://builds.cuberite.org/job/cuberite/job/master/job/linux-odroid-xu4/job/debug/297/console

**Comment by Seadragon91** [comment]
Just as info mbetls has not been updated since over two years. I had tried it a few months ago, but the changes are big: https://github.com/cuberite/cuberite/issues/3070#issuecomment-299874012

**Comment by peterbell10** [comment]
I think we just need to use `target_compile_options` instead of using variables.
