### ISSUE TITLE
Can't harvest NetherFence

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3312]
You can't deconstruct the Netherfences, they just disappear.

**Comment by sphinxc0re** [comment]
Could you please stick to the issue template when creating issues

```markdown
Client version:   x.x.x
Server OS:        Windows/Linux/macOS/BSD/...
Commit id:        (Found at the top of the server's console output)


### Expected behavior


### Actual behavior


### Steps to reproduce the behavior
```

**Comment by jammet** [comment]
I think that makes very little sense with issues like this one, where everybody already knows I'm using the latest build, and what you were expecting when you encountered the bug.

However, I'll try. When issues get complicated, I certainly will, because then, the template is actually helpful.

**Comment by sphinxc0re** [comment]
Are you expecting everyone to know your current version, Server OS and commit? Please just use the template.

**Comment by LogicParrot** [comment]
We shouldn't enforce the template! This is just annoyance.
