### ISSUE TITLE
No Mobs spawning

### ISSUE THREAD

**Issue by lil070** [cuberite/cuberite#3314]
Client version:   1.9.4
Server OS:        Linux
Commit id:        58b29adc88343fe0821c008ba0f0bble8018574d

### first i was looking on google, for a solution the only thing that i found was checking the world.ini settings.
i checked them but they are al fine "i think"
(monsters)
VillagersShouldHarvestCrops=1
AnimalsOn=1
Types=bat, cavespiders, chicken....... etc etc

sorry for the bad english i'm dutch and dyslectic.

**Comment by LogicParrot** [comment]
Do you have issues with a 1.8.x client?

**Comment by LogicParrot** [comment]
>Do you have issues with a 1.8.x client?

Sorry, my bad. Since it's survival, it's unlikely to be a client version issue, because you should get hit by the mobs even if they're invisible. So the client version is most likely irrelevant.

We have issues with caves, mobs do not spawn there properly, see: #https://github.com/cuberite/cuberite/issues/2858

Mobs should be spawn properly at the surface, at night. I just tested with the exact same setup and there seemed to be no issues. Are you using plugins? Did you modify the default settings in any way? Is difficulty Peaceful?

**Comment by lil070** [comment]
this are the plugins
APIDump
Enable
ChunkWorx
Enable
Debuggers
Enable
DiamondMover
Enable
DumpInfo
Enable
Handy
Enable
HookNotify
Enable
MagicCarpet
Enable
NetworkTest
Enable
ProtectionAreas
Enable
TestLuaRocks

no i didn't change any settings so far
and where do i find the difficulty setting ?

**Comment by LogicParrot** [comment]
In `world.ini`: 
`WorldDifficulty=0` disables mobs, and `WorldDifficulty=1` is the default.

**Comment by lil070** [comment]
yea it's in 1=survival

**Comment by LogicParrot** [comment]
What is your `viewDistance`?

**Comment by lil070** [comment]
viewDistance=12

**Comment by lil070** [comment]
here is the full world.ini:

[SpawnProtect]
ProtectRadius=10

[WorldLimit]
LimitRadius=0

[Difficulty]
WorldDifficulty=0

[General]
Dimension=Overworld
IsDaylightCycleEnabled=1
Gamemode=0
Weather=0
TimeInTicks=403

[Broadcasting]
BroadcastDeathMessages=1
BroadcastAchievementMessages=1

[SpawnPosition]
MaxViewDistance=12
X=240
Y=83
Z=-94
PregenerateDistance=20

[Storage]
Schema=Default
CompressionFactor=0

[Plants]
MaxCactusHeight=3
MaxSugarcaneHeight=3
IsCactusBonemealable=0
IsCarrotsBonemealable=1
IsCropsBonemealable=1
IsGrassBonemealable=1
IsMelonStemBonemealable=1
IsMelonBonemealable=0
IsPotatoesBonemealable=1
IsPumpkinStemBonemealable=1
IsPumpkinBonemealable=0
IsSaplingBonemealable=1
IsSugarcaneBonemealable=0
IsBigFlowerBonemealable=1
IsTallGrassBonemealable=1

[Physics]
DeepSnow=1
ShouldLavaSpawnFire=1
TNTShrapnelLevel=2
WaterSimulator=Vanilla
LavaSimulator=Vanilla
SandInstantFall=0
RedstoneSimulator=Incremental

[Mechanics]
CommandBlocksEnabled=0
PVPEnabled=1
UseChatPrefixes=1
MinNetherPortalWidth=2
MaxNetherPortalWidth=21
MinNetherPortalHeight=3
MaxNetherPortalHeight=21

[Monsters]
VillagersShouldHarvestCrops=1
AnimalsOn=1
Types=bat, cavespider, chicken, cow, creeper, guardian, horse, mooshroom, ocelot, pig, rabbit, sheep, silverfish, skeleton, slime, spider, squid, wolf, zombie

[Weather]
MaxSunnyTicks=180000
MinSunnyTicks=12000
MaxRainTicks=24000
MinRainTicks=12000
MaxThunderStormTicks=15600
MinThunderStormTicks=3600

[LinkedWorlds]
NetherWorldName=world_nether
EndWorldName=world_end

[Generator]
Generator=Composable
BiomeGen=Grown
ShapeGen=BiomalNoise3D
CompositionGen=Biomal
Finishers=RoughRavines, WormNestCaves, WaterLakes, WaterSprings, LavaLakes, LavaSprings, OreNests, Mineshafts, Trees, Villages, TallGrass, SprinkleFoliage, Ice, Snow, Lilypads, BottomLava, DeadBushes, NaturalPatches, PreSimulator, Animals
BiomeGenCacheSize=16
BiomeGenMultiCacheLength=128
SeaLevel=62
BiomalNoise3DFrequencyX=40.000000
BiomalNoise3DFrequencyY=40.000000
BiomalNoise3DFrequencyZ=40.000000
BiomalNoise3DBaseFrequencyX=40.000000
BiomalNoise3DBaseFrequencyZ=40.000000
BiomalNoise3DChoiceFrequencyX=40.000000
BiomalNoise3DChoiceFrequencyY=80.000000
BiomalNoise3DChoiceFrequencyZ=40.000000
BiomalNoise3DAirThreshold=0.000000
BiomalNoise3DNumChoiceOctaves=4
BiomalNoise3DNumDensityOctaves=6
BiomalNoise3DNumBaseOctaves=6
BiomalNoise3DBaseAmplitude=1.000000
CompositionGenCacheSize=64
RoughRavinesGridSize=256
RoughRavinesMaxOffset=128
RoughRavinesMaxSize=128
RoughRavinesMinSize=64
RoughRavinesMaxCenterWidth=8.000000
RoughRavinesMinCenterWidth=2.000000
RoughRavinesMaxRoughness=0.200000
RoughRavinesMinRoughness=0.050000
RoughRavinesMaxFloorHeightEdge=8.000000
RoughRavinesMinFloorHeightEdge=30.000000
RoughRavinesMaxFloorHeightCenter=20.000000
RoughRavinesMinFloorHeightCenter=6.000000
RoughRavinesMaxCeilingHeightEdge=56.000000
RoughRavinesMinCeilingHeightEdge=38.000000
RoughRavinesMaxCeilingHeightCenter=58.000000
RoughRavinesMinCeilingHeightCenter=36.000000
WormNestCavesSize=64
WormNestCavesGrid=96
WormNestMaxOffset=32
WaterLakesProbability=25
LavaLakesProbability=10
MineShaftsGridSize=512
MineShaftsMaxOffset=256
MineShaftsMaxSystemSize=160
MineShaftsChanceCorridor=600
MineShaftsChanceCrossing=200
MineShaftsChanceStaircase=200
VillageGridSize=384
VillageMaxOffset=128
VillageMaxDepth=2
VillageMaxSize=128
VillageMinDensity=50
VillageMaxDensity=80
VillagePrefabs=PlainsVillage, SandVillage
BottomLavaLevel=10
PreSimulatorFallingBlocks=1
PreSimulatorWater=1
PreSimulatorLava=1
HeightGen=Biomal

[WaterSimulator]
Falloff=1
TickDelay=5
NumNeighborsForSource=2

[LavaSimulator]
Falloff=2
TickDelay=30
NumNeighborsForSource=-1

[FireSimulator]
BurnStepTimeFuel=500
BurnStepTimeNonfuel=100
Flammability=50
ReplaceFuelChance=50000

[Seed]
Seed=279630430

[WaterSprings]
HeightDistribution=0, 0; 10, 10; 11, 75; 16, 83; 20, 83; 24, 78; 32, 62; 40, 40; 44, 15; 48, 7; 56, 2; 64, 1; 255, 0
Chance=24

[LavaSprings]
HeightDistribution=0, 0; 10, 5; 11, 45; 48, 2; 64, 1; 255, 0
Chance=9

[Animals]
AnimalSpawnChunkPercentage=10

**Comment by LogicParrot** [comment]
Your `WorldDifficulty` is 0. It should be `1`.

**Comment by lil070** [comment]
so that means the normale web interface isn't working because the web settings already where on survival.

thanks anyway i'll do a restart and give it a shot.
give my a sec 👯

**Comment by LogicParrot** [comment]
It seems you are confusing gameMode and WorldDifficulty.
`WorldDifficulty` should be 1 for mob spawning.
`GameMode` should be 0 for survival.

**Comment by lil070** [comment]
oh wow you are right i'm a idiot.
thanks for your time!! it works !

**Comment by madmaxoft** [comment]
We should allow symbolic names in the settings, as well as those cryptic numbers, to avoid the confusion.

**Comment by LogicParrot** [comment]
#3315

**Comment by LogicParrot** [comment]
>We should allow symbolic names in the settings, as well as those cryptic numbers, to avoid the confusion.

Agreed.
