### ISSUE TITLE
Lambdas with Lua

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#3325]
xoft suggested that the use of cCallback classes with Lua bindings are inevitable.

I am wondering what exactly happens when you

``` lua
DoWithWorld("World One", function() ... end)
```

What gets passed as the second parameter? Can we translate that to `std::function`?

**Comment by tigerw** [comment]
Any ideas?

**Comment by madmaxoft** [comment]
I don't quite understand the question.
When you pass a Lua function to another Lua function, what you're really passing is called a "closure" - it's a function that also includes references to local variables of the calling site that the function internally uses (somewhat like lambda captures).
If what you're asking about is "what the C++ code sees", it sees a Lua "function value" type, which is just an opaque representation of the Lua capture. The `cLuaState::cCallback` class wraps that value into some plumbing that takes care of tracking whether the Lua state is still valid whenever the callback is called (consider a function scheduling a task with `cWorld:ScheduleTask()` and then the admin unloading the plugin before the task is to be executed. We can't walk all parts of the code that take callbacks and inform them "don't call this anymore"; instead we give them a callback that first checks whether the plugin is still valid.
And that's one of the main reasons why it can't be represented as a lambda. It has a fixed return type - it always returns a `bool` whether the function call was actually made. If you want any return values from the Lua side, you need to add them to the parameters after a `cLuaState::Return`:
```cpp
HasBeenCalled = callback.Call(Param1, Param1, cLuaState::Return, ReturnVal1, ReturnVal2);
```
That is a form highly incompatible with other C++ callbacks, so we really want to make sure we don't mix those two.

Of course, it should be fairly easy to actually wrap this callback inside a C++ lambada, there should be very minimal need for the glue classes (such as `LuaCommandHandler` in ManualBindings.cpp) if we decide to refactor everything to use `std::function`-style C++ callbacks.

Does this answer your question?
