### ISSUE TITLE
If you try to place blocks inside of you in 1.9 you will be pushed away.

### ISSUE THREAD

**Issue by mohe2015** [cuberite/cuberite#3340]
Client version:   1.9
Server OS:       Linux
Commit id:        approx: 07c5f09ecf2fdf0d84c7cf6862c37b6cc71d4d75 built at: approx: 2016-08-21 11:03:26 +0200

### Expected behavior
You can't place blocks inside of you in 1.9

### Actual behavior
You will be pushed away if you place a block inside of you in 1.9. In 1.8 it works fine.

### Steps to reproduce the behavior
Join server with 1.9. Place any block inside of you.

**Comment by tigerw** [comment]
Mojang seems to have let the server decide on whether a client can place a block in an entity or not.

**Comment by mohe2015** [comment]
But in 1.8 it works, maybe they changed that.

**Comment by tigerw** [comment]
Most certainly.

**Comment by mathiascode** [comment]
Duplicate of #3196
