### ISSUE TITLE
Prefabs: Blockmeta's are sometimes incorrect when rotating

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3367]
Client version:   1.9
Commit id:       5625598afac8db3b35d790b8d1228997b228f228

![2016-09-04_08 55 42](https://cloud.githubusercontent.com/assets/14818618/18229551/a815d292-727d-11e6-98ed-52972c7a6c11.png)

Seed: 784561775
Position: 900 65 -94

**Comment by NiLSPACE** [comment]
This is a know issue which affects all prefabs.

**Comment by Seadragon91** [comment]
Ah okay.

**Comment by bearbin** [comment]
@NiLSPACE Can you link the issue or reopen this if there isn't an existing issue?

**Comment by NiLSPACE** [comment]
It seems there is no issue for this on Github, so I'll link the post on the forum instead and re-open and rename this:

Forum post: https://forum.cuberite.org/thread-434-post-14560.html#pid14560

**Comment by madmaxoft** [comment]
This is caused by the rails block having bad `MirrorXY()` and `MirrorYZ()` functions - they were updated for the specialized rails (power, detector, activator) but the regular rails have a different set of rules.
