### ISSUE TITLE
will the server support the mod in the future?

### ISSUE THREAD

**Issue by W-Blacktail** [cuberite/cuberite#3368]
will the server support the mod in the future?

**Comment by madmaxoft** [comment]
The server already supports plugins. The API system is quite flexible and already can work with a number of client-side mods. We haven't had anyone try anything bigger yet.

**Comment by W-Blacktail** [comment]
e...i mean the server-side mod

**Comment by madmaxoft** [comment]
The plugins ARE server-side.

**Comment by LogicParrot** [comment]
Plugin guide: http://api-docs.cuberite.org/Writing-a-Cuberite-plugin.html

Could he be referring to textures?

**Comment by LogicParrot** [comment]
@W-Blacktail Perhaps you're talking about server side textures? #3349

**Comment by blacktailnomore** [comment]
sorry,I have a wrong expression.I mean the server run the mod like the cauldron or kcauldron more than the plugins,or the server is just a plugin-server?

**Comment by Pokechu22** [comment]
You mean mods from forge?  It currently does not support running them as-is, so you aren't able to put a forge mod into a mods folder and use it (you also can't do that with bukkit plugins as-is; cuberite has its own type of plugins written in lua).

However, it is _possible_ to rewrite forge mods in lua to be used with cuberite.

**Comment by blacktailnomore** [comment]
oh,i see,thanks for your reply.

**Comment by blacktailnomore** [comment]
another question:do you have a plan to support the 1.7.10?

**Comment by mathiascode** [comment]
Not anymore. We did support 1.7 until recently, but it contained a major bug (you couldn't place blocks).

**Comment by mathiascode** [comment]
If that's not a problem, commit ID 72aa50f710200832f97a0022dc70c5cd531b6aea is the last one to contain 1.7 support.
