### ISSUE TITLE
URLs for specific API commands

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3369]
Commit id:       f7029eddd4120f672c59a4b3a4395832f4de8863

When visiting http://api-docs.cuberite.org, I'd want to have links to individual commands via the hash part of the URL. e.g. `http://api-docs.cuberite.org/cPlayer.html#Freeze` Should lead to the player class's `Freeze` command.

This should be rather simple: Each command's first HTML table cell, `<td>X</td>` should be changed to:

```
<td id="X">
  <a href="PageURL#X">X</a>
</td>
```

Better methods are welcome.
This may require changes to the built in APIDump plugin, which is why I posted it here.

**Comment by NiLSPACE** [comment]
Shouldn't be too hard to do. Just add an anker tag here: https://github.com/cuberite/cuberite/blob/master/Server/Plugins/APIDump/main_APIDump.lua#L786

**Comment by Seadragon91** [comment]
@NiLSPACE Found 2 more places where it has to be added. For constants and also for member variables.

This are the changes that I tested and they works,
https://github.com/Seadragon91/cuberite/commit/eb1ceb0dc8f78bb3845cf3e2d85b0241c5a96352

**Comment by madmaxoft** [comment]
Careful, though. Do we want to simply mix all the symbols together (functions, constants, variables, enums) in this way, or should we prefix the anchor with something? Such as `Fn<Name><OverloadIndex>`? That way you could even link to a specific overload (parameter combination) of the function, in case it has more.

**Comment by madmaxoft** [comment]
@Seadragon91 I don't think that's how anchoring works, AFAIK you need to use `<a name="FunctionName">content</a>`

**Comment by bearbin** [comment]
@madmaxoft No, it does work like that, `#` can link to IDs. For an example, see https://book.cuberite.org

**Comment by madmaxoft** [comment]
Hmm, I guess I'm too old-school :P

**Comment by madmaxoft** [comment]
Then either convert all the anchors to use this syntax, or use the old one. Be consistent.

**Comment by Pokechu22** [comment]
[`<a name="">` is obsolete syntax in HTML5](http://www.w3.org/TR/html5/obsolete.html#obsolete-but-conforming-features) and `id` should be used instead.

**Comment by Seadragon91** [comment]
I added a table to track the function names and add `_<number>` to the anchor name for the overloaded functions, also added a title, if the mouse hover over it.
Has anyone a better idea for unique anchor names, or does this fit?

https://github.com/Seadragon91/cuberite/commit/7a3763a7415ef700ace90ff77337cde26dc93a0b

**Comment by madmaxoft** [comment]
Drop the if, use `TableOverloadedFunctions[func.Name] = (TableOverloadedFunctions[func.Name] or 0) + 1` and get the first overload numbered as well as a bonus :)

**Comment by Seadragon91** [comment]
This would then add a `_1` for all functions. Is that okay?

**Comment by madmaxoft** [comment]
It will number the functions incrementally

**Comment by Seadragon91** [comment]
Yes it will increment it, but I mean that now all functions that are not overloaded will have the `_<cnumber>.

**Comment by madmaxoft** [comment]
Yes, all the anchors will have the same format, rather than having two different formats. And if a function ever receives an overload, its anchored link will still work afterwards.
