### ISSUE TITLE
Reformat Lua API Desc to explicitly include param types

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#3375]
Currently the Lua API description (in the APIDump built-in plugin) has no machine-readable indication of the functions' parameters' and return values's types. We should provide an explicit declaration of the types.

Before:
```lua
FnName = { { Params = "Command, Handler, Permission, [HelpString]", Return = "bool", Notes = ...}, ... }
```

After:
```lua
FnName =
{
  {
    Params =
    {
      { Type = "string", Name = "Command" },
      { Type = "function", Name = "Handler" },
      { Type = "string", Name = "Permission" },
      { Type = "string", Name = "HelpString", Optional = true},
    },
    ...
  },
}
```

This is rather lengthy, but is worth it - from this format we could generate better docs and even extract the API info for automated plugin testing).

The reformatting would ideally be done by a script that could guess the common parameter types - it is already being done in the https://github.com/madmaxoft/ManualApiDump plugin.

**Comment by madmaxoft** [comment]
One slight problem - how to represent the situation when a function can return various types - "cTCPLink on success, false and error message on failure"?

**Comment by NiLSPACE** [comment]
Could we even generate our bindings with this?

**Comment by NiLSPACE** [comment]
Perhaps in the title attribute we could represent the types. In the `cTCPLink`'s case you'd get something like: `bool|string` when you hover above it.

Or if you meant how to represent them in the APIDesc File, perhaps something like this?:
````lua
FnName = 
{
	{
		Return = 
		{
			{
				{ Type = 'bool' }
			},
			{
				{ Type = 'bool' }
				{ Type = 'string' }
			}
		}
	}
}
```

**Comment by madmaxoft** [comment]
The thought of generating bindings has been there before, it could work for the simple stuff, for which we currently use the ToLua++ parser. The thing holding me back from implementing that is that there some undecided options about the process.

Yes, I meant the representation in the APIDesc file. Most likely the first of your examples, but not sure about how to represent the conditions, whether it should be machine-readable etc. Just needs more thinking.

**Comment by madmaxoft** [comment]
The automatic part of the conversion is done, I have put the script into a separate repo:
https://github.com/madmaxoft/ApiDescConvert

Now I'll need to go through the docs and manually fix whatever's left.
