### ISSUE TITLE
VarInts in cuberite are treated as unsigned when they are actually signed

### ISSUE THREAD

**Issue by Pokechu22** [cuberite/cuberite#3379]
This doesn't follow the issue template because it's version and OS unspecific and has no observable in-game effect - it's a code-only issue.

Per the [data types](http://wiki.vg/Data_types) article (emphasis mine), VarInts are signed:

> <table>
> <th>Name</th><th>Size (bytes)</th><th>Encodes</th><th>Notes</th></tr>
> <tr><th>VarInt</th><td>≥ 1<br>≤ 5</td><td>An integer between <b>-2147483648</b> and 2147483647</td><td><a href="http://developers.google.com/protocol-buffers/docs/encoding#varints">Protocol Buffer Varint</a>, encoding a <b>two's complement signed</b> 32-bit integer</td></tr>
> <tr><th>VarLong</th><td>≥ 1<br>≤ 10</td><td>An integer between <b>-9223372036854775808</b> and 9223372036854775807</td><td><a href="http://developers.google.com/protocol-buffers/docs/encoding#varints">Protocol Buffer Varint</a>, encoding a <b>two's complement signed</b> 64-bit integer</td></tr>
> </table>

However, `cByteBuffer`'s VarInt-related methods treat it as an unsigned type,  While this technically still works, it creates a lot of ugliness in some situations (for instance, the fuse value for creepers is `-1` when they're idle, but cuberite needs to write it as `0xFFFFFFFF`).

**Comment by madmaxoft** [comment]
Actually there are two styles of VarInts in protobuf. The ones MC uses are the "positive" ones - they were originally specified only for unsigned datatypes and encode `-1` as actually `0xffffffff`. And then there are "signed integer VarInts" that use zig-zag encoding; MC doesn't use those and we don't implement them. However, it would be quite misleading to implement current VarInts as accepting signed types.

**Comment by Pokechu22** [comment]
While it doesn't use the zig-zag encoding, it still is treated as signed in _all_ cases where Minecraft uses VarInts - java only has signed types.  I'd say it's more misleading to pretend that it isn't signed (or rather, that it's *ever* unsigned).

Want a demo?  Send a packet with an id of `0xc0000000`.  If anything would make sense to be unsigned, then it would be packet IDs (and packet lengths, but length doesn't display ingame when it's invalid).  You'll get a dirt screen:

![Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id -1073741824](https://cloud.githubusercontent.com/assets/8334194/18728225/3aeefdd8-8001-11e6-8e0b-3d62320cdfb3.png "Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id -1073741824")


I'd say the fact that packet IDs can be negative is a pretty good indication that all varints are signed (and I've looked at the code; they are).

Yes, `-1` is encoded as `0xffffffff`.  That's the way that it's actually encoded by the game, when the game uses `-1` (and it's `-1`, not `0xffffffff`).  The value isn't `0xffffffff` but instead `-1`, so we should be using `-1`, not `0xffffffff`.

**Comment by tigerw** [comment]
Seems like it's, largely, being used to send unsigned values; I'd say leave it as-is unless something definitely needs it. I'm not sure how WriteVarInt32 is implemented but changing it to a signed type might invite undefined/unspecified behaviour unless care is take with overflows and shifts.
