### ISSUE TITLE
Fishing rods crash server

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3385]
Client version:   1.10.2
Server OS:        Linux
Commit id:        b268db4caae1b5612ae0f3adabf164efc06de368
### Expected behavior

Fishing rods work normally without crashing a server.
### Actual behavior

Fishing rods crash the server when used.
### Steps to reproduce the behavior

Use a fishing rod.

**Comment by madmaxoft** [comment]
I can't reproduce this, tried server on both Linux and Windows, no matter what I do with the fishing rod, no crash.

**Comment by mathiascode** [comment]
Weird, seems like it's fixed now.
