### ISSUE TITLE
TeleportToCoords not working after player switches world

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3389]
Client version:   1.10.2
Server OS:        Linux
Commit id:        b268db4caae1b5612ae0f3adabf164efc06de368

### Expected behavior
Players should teleport to the correct coordinates specified in TeleportToCoords after switching worlds.

### Actual behavior
The player doesn't teleport to the coordinates, and stays at the spawn point. When the player doesn't have to switch worlds, it teleports to the correct coordinates.

### Steps to reproduce the behavior
Try commands like /tp, /warp in Core and Essentials.

**Comment by NiLSPACE** [comment]
I suspect this has nothing to do with TeleportToCoords, but rather with the switching worlds thingy. Once you use the /warp or /tp commands do you get a chat message from the server? Like `teleported you to x, y, z` or anything?

**Comment by mathiascode** [comment]
Yes. MoveToWorld activates, the player moves to the correct world, and the success message is shown in chat. The player does not teleport to the coordinates specified in TeleportToCoords though, only if you run the same command again while being located in the correct world.

**Comment by mathiascode** [comment]
This PR causes the problem: https://github.com/cuberite/cuberite/commit/5625598afac8db3b35d790b8d1228997b228f228

**Comment by mathiascode** [comment]
@LogicParrot, could you take a look whenever you have time?

**Comment by LogicParrot** [comment]
I found a fix. However, the core problem is that essential is uses a deprecated method.
Instead of 
```
MoveToWorld(X)
TeleportToCoords(myCords)
```
One can use:
```
ScheduleMoveToWorld(X, myCords)
```

**Comment by LogicParrot** [comment]
```
Steps to reproduce the behavior

Try commands like /tp, /warp in Core and Essentials.
```

`warp` was clearly not working across worlds, but is there anything wrong with `\tp`?

**Comment by mathiascode** [comment]
Since /tp uses the same method as Essentials' /warp, the same problem happens when the target player is in another world.

**Comment by LogicParrot** [comment]
Fixed in https://github.com/cuberite/Essentials/pull/64. Can you confirm?

**Comment by mathiascode** [comment]
It works now.
