### ISSUE TITLE
Linux version can not run on CentOS

### ISSUE THREAD

**Issue by ningwang747** [cuberite/cuberite#3390]
Client version:   null
Server OS:        CentOS7(Linux)
Commit id:        null

### Expected behavior
Turn on the server

### Actual behavior
Prompt ./Cuberite: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20 'not found (required by ./Cuberite)
But glibc is already install
### Steps to reproduce the behavior
Turn on the server

**Comment by Seadragon91** [comment]
Please check the compiler versions. For compile you need a minimum version of gcc/g++ 4.8 or clang 3.4.

**Comment by ningwang747** [comment]
I downloaded it at https://builds.cuberite.org/job/Cuberite%20Linux%20x64%20Master/

**Comment by Seadragon91** [comment]
The glibc version in centos is too old. Installing a new version is not recommended and it can break lots of packages.
I have installed centos 7 in virtualbox and searched the necessary packages to compile cuberite.
```
1) Install packages
yum install git cmake gcc gcc-c++

2) Clone cuberite
git clone --recursive https://github.com/cuberite/cuberite.git

3) cd cuberite
4) mkdir Release
5) cd Release
6) cmake -DCMAKE_BUILD_TYPE=RELEASE ..
7) make -j2
```
Hope that this works. Good luck

**Comment by ningwang747** [comment]
Thank

**Comment by Seadragon91** [comment]
If you try to compile it, please write if it works for you or if you still run in any problems.
