### ISSUE TITLE
World travel API has some bugs

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3398]
Commit id:        1e8cae641592cc4ae7b6f1b997c514f9d2be422b

We have problems with the world travel API.

##### cPlayer::MoveToWorld
MoveToWorld is exposed directly to plugins. This is not thread safe. I've mitigated this by wrapping some of `DoMoveToWorld` with `QueueTask`, but this is not enough. Also, it introduces a bug; it is dangerous for `QueueTask` to capture a `cPlayer`. Although `DoMoveToWorld` is marked obsolote in the API docs, it has no real alternative. See below. 

##### cPlayer::ScheduleMoveToWorld
This is supposed to be the safer alternative, but it's broken. It assumes it is always called by nether/end portal travel, therefore it may send the wrong respawn packets due to a wrong `a_shouldSendRespawn` flag.

I'll fix `ScheduleMoveToWorld`.

I think we should either remove `MoveToWorld ` from the API, or make it a wrapper for `ScheduleMoveToWorld`.

Related: #3179 #3396

**Comment by LogicParrot** [comment]
Closing and moving to forum, this will be more of a discussion.

**Comment by LogicParrot** [comment]
https://forum.cuberite.org/26815.html

**Comment by mathiascode** [comment]
Any progress?

**Comment by LogicParrot** [comment]
I was away for a while, so no. I'll check my todos and see which issue I should tackle first.
