### ISSUE TITLE
Block entity type mismatch: exp "Chest", got "TrappedChest".

### ISSUE THREAD

**Issue by FacuM** [cuberite/cuberite#3402]
Client version:   1.7.10
Server OS:        Linux
Commit id:       approx: 4e33569110d9a4e71b1d2fa4ea674225c8d36b88
### Expected behavior

No broken entities.
### Actual behavior

Block entity type mismatch: exp "Chest", got "TrappedChest".
### Steps to reproduce the behavior

None that I know, it has just started to happen from one startup to another. No new plugins added. Also note that it's a self-made build (from auto compilation script found at cuberite.org).

**Comment by LogicParrot** [comment]
Related: #3384

**Comment by madmaxoft** [comment]
This is a known issue with the world loader, it has trouble distinguishing regular chests from trapped chests. Not sure about the severity of the issue - it might be just a silly warning with no importance, or it could cause trapped chests to lose contents. Worst case, it could render trapped chests non-openable by the player.
