### ISSUE TITLE
Crash in cJson:Serialize / Server restarts in a endless loop

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3414]
Commit id:        (502b5ec)

Yep there are two possibilities 😄 

### Actual behavior
Server crashes or restarts in a endless loop.

### Steps to reproduce the behavior
Add this function to a plugin
```
function func(...)
	cJson:Serialize(arg)
end
```
Call it it from the function `Initialize`: `func(1)`

1) Server is not running.
Add the code and start the server, endless loop.

2) Server is running.
Add the code and run reload, server will crash.

**Comment by madmaxoft** [comment]
Could this be the same as #3413 , or does it still happen?

**Comment by Seadragon91** [comment]
This does still happen and its a other problem.

**Comment by madmaxoft** [comment]
A simple exception, because the table cannot be represented in Json. I'll change the API so that in case of errors, it will return `nil` and error message.
