### ISSUE TITLE
Logging a ghost of the user.

### ISSUE THREAD

**Issue by d3nwo** [cuberite/cuberite#3418]
Client version:   1.8 liteloader with optifine and an old mod that doesn't work
Server OS:        Linux
Commit id:        (f8f0dc4558a0a60766e8699b1b07dbebeaf5336a)
### Expected behavior

Log me in
### Actual behavior

Logging a ghost of me?
### Steps to reproduce the behavior
connect to a server after and disconnect before connecting.

**Comment by madmaxoft** [comment]
This is related to all the other `cClientHandle` issues.

**Comment by Seadragon91** [comment]
This still occurs, flood the server and players will still be connected,
