### ISSUE TITLE
Eradicate Compiler Warnings

### ISSUE THREAD

**Issue by Sofapriester** [cuberite/cuberite#342]
Remove all the compiler warnings, by fixing the underlying problems.

    Hi together,
    my compiler (make release=1) at Raspian (ARM) produced this warnings. Is this possibly relevant for you? Or is it not important?

    source/OSSupport/IsThread.cpp: In constructor ‘cIsThread::cIsThread(const AString&)’:
    source/OSSupport/IsThread.cpp:56:15: warning: converting to non-pointer type ‘pthread_t {aka long unsigned int}’ from NULL [-Wconversion-null]
    source/OSSupport/IsThread.cpp: In member function ‘void cIsThread::Stop()’:
    source/OSSupport/IsThread.cpp:114:18: warning: NULL used in arithmetic [-Wpointer-arith]
    source/OSSupport/IsThread.cpp: In member function ‘bool cIsThread::Wait()’:
    source/OSSupport/IsThread.cpp:128:18: warning: NULL used in arithmetic [-Wpointer-arith]
    source/OSSupport/IsThread.cpp:148:14: warning: converting to non-pointer type ‘pthread_t {aka long unsigned int}’ from NULL [-Wconversion-null]
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]

**Comment by madmaxoft** [comment]
I don't think this issue qualifies as "easy", since quite often the warnings have a rather twisted reason and fixing them takes a lot of thought about the possible corner cases.

**Comment by bearbin** [comment]
Close?

This is a recurring issue not a one-time fix.

**Comment by worktycho** [comment]
#2070 adds some significant changes to how -Werror is handled in the builds system, which prevents warnings from being reintroduced into fixed files. So it will be a one-time fix.

**Comment by worktycho** [comment]
We now have a lot of low hanging fruit. Particularly -Wshadows, -Wold-style-cast, -Wmissing-prototypes and -Wmissing-variable-declarations.

**Comment by SamJBarney** [comment]
I guess I will claim ownership of this one since I started working on reducing warning messages.

**Comment by madmaxoft** [comment]
I think this can be considered complete, with #3346 merged.
