### ISSUE TITLE
MoveToWorld doesn't always send player to spawn

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3420]
Client version:   1.10.2
Server OS:        Linux
Commit id:        733401ec5fe5acd0518df58daabb8702c5342ebf

### Expected behavior
Player is consistently sent to the new world's spawn point after switching worlds with MoveToWorld

### Actual behavior
Most of the time the player is sent to the spawn point of the new world, sometimes the player is sent to the same coordinates it was located at in the last world

### Steps to reproduce the behavior
Join flame.ga, and use the portals as well as /portal a few times.

**Comment by LogicParrot** [comment]
My memory is a bit foggy and I have some catching up to do, but I think I was trying to resolve this (or something related) by cleaning up the API, see here: https://github.com/cuberite/cuberite/pull/3401

**Comment by LogicParrot** [comment]
Furthermore, I think I remember seeing two function setting position and wondering if they always set it in the same order. (Potential leads: `freeze`, `doMoveToWorld`)

**Comment by mathiascode** [comment]
Does anyone have an idea why this is happening?

**Comment by LogicParrot** [comment]
I'll get to this once I deal with the mobs. Do you have any more info that could be helpful?

**Comment by mathiascode** [comment]
Hm, I can't reproduce this issue.

**Comment by mathiascode** [comment]
Most likely fixed, can't reproduce.
