### ISSUE TITLE
Log is opened too late. Results in no log output

### ISSUE THREAD

**Issue by Cl1608Ho** [cuberite/cuberite#3433]
Client version:   x.x.x
Server OS:        Android
Commit id:        something relatively new (doesn't matter cause of the wrong branch) 

### Expected behavior
Log should be opened at the very beginning and made sure to be open before starting other tasks like libevent. This may increase startup time by a few milliseconds, but a not working log or a log in an unknown state isn't good because log messages are silently dropped if the log isn't open yet. 

### Actual behavior
Log actually was opened after libevent initialise was called. 

### Steps to reproduce the behavior
Put a printf and a LOGINFO in that function, only the printf is shown

**Comment by mathiascode** [comment]
Is this still relevant?

**Comment by Cl1608Ho** [comment]
No clue! And goddamit was I writing bad bug reports back then :smiley:
