### ISSUE TITLE
player inventory cursor

### ISSUE THREAD

**Issue by d3nw0** [cuberite/cuberite#3436]
in wiki.vg it states
> To set the cursor (the item currently dragged with the mouse), use -1 as Window ID and as Slot.
This packet can only be used to edit the hotbar of the player's inventory if window ID is set to 0 (slots 36 through 44). If the window ID is set to -2, then any slot in the inventory can be used but no add item animation will be played.

If you try to set window id to -1 to change the player's holding item you will get a log warning with this message.
`SetSlot: requesting an invalid slot index: -1 out of 39. Ignoring.`

**Comment by NiLSPACE** [comment]
This is because we currently check if the slot index is above 0

**Comment by Cl1608Ho** [comment]
So the checks should check if the index is above -3 right? Does that cause any issues with for example array indexes? Apart from that, you can assign me :)

**Comment by NiLSPACE** [comment]
I believe it applies to every window as you have a cursor in each and every of them.

**Comment by Pokechu22** [comment]
It applies to all windows; however, it's _not a good idea_ (but still valid) to do it when there is no window open.  Window type `-2` is more complicated and probably shouldn't be used with plugins (it's only used for implementing the [MC|PickItem](http://wiki.vg/Plugin_channels#MC.7CPickItem) plugin channel).

It's probably better to create explicit `SetCursorItem` and `GetCursorItem` methods than to require `-1`.

**Comment by NiLSPACE** [comment]
Yeah, I agree. Make it a separate method.

**Comment by Pokechu22** [comment]
To be clearer: type `-1` works with all windows.  You just shouldn't use it when there is no window open, since that causes weird behavior when reopening inventories.

Type `-2` is for the player inventory and the player inventory only, and I'm 90% sure isn't designed for other types (but it may work with them).

**Comment by Seadragon91** [comment]
Closed by #3836. New API functions have been been added that can be used:
[GetDraggingItem](https://api.cuberite.org/cPlayer.html#GetDraggingItem_1) and [SetDraggingItem](https://api.cuberite.org/cPlayer.html#SetDraggingItem_1)
