### ISSUE TITLE
High lag when connected through a bungeecord proxy, with some timeouts

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3441]
Client version:   1.9.4
Server OS:        Linux (debian jessie)
Commit id:        ded59e9519c429c511866609d0e5e909f8e10aad

Everything, from chat, commands to interacting with the world or its entities lags baddly and the client eventually times out. Mojang authentication is disabled on both, cuberite and bungeecord. Enabling or disabling the bungeecord support in the cuberite settings didn't change the results.

### Steps to reproduce the behavior
Connect to a cuberite server using a bungeecord proxy server (tested with their latest release, the issue persists).

**Comment by yangm97** [comment]
Opened [a issue](https://github.com/SpigotMC/BungeeCord/issues/2001) on BungeeCord just in case.

**Comment by madmaxoft** [comment]
I'll have a look at this

**Comment by madmaxoft** [comment]
I've tried with all three (Cuberite, BungeeCord, Client) on the same computer and it works alright for me, no noticable lag at all. Can you describe your network topology? Do the servers run on different machines? When you ping them, what are the roundtrip times?

**Comment by yangm97** [comment]
I tried on my server and on my computer, both setups ran inside docker containers. At first I didn't think Docker had anything to do with it, since the spigot servers proxied just fine. I can upload my server files or PM you with my server IP, whichever is more comfortable to you.

**Comment by madmaxoft** [comment]
Ugh, Docker again, I guess I won't be able to dodge it this time. How do I install that thing, and how do I make Cuberite run in it? :P Is there a setup guide for us dinosaurs?

**Comment by yangm97** [comment]
First you will have to install docker following the [steps](https://docs.docker.com/engine/installation/linux/) for your distro. Then you will have to install [docker-compose](https://docs.docker.com/compose/install/). Also, add your user to the group docker so you don't need to use sudo when dealing with docker. 

I have stripped down some irrelevant bits from my environment (like the spigot survival server) and zipped the thing. I already set up gitlab-ci to build docker images for bungeecord, spigot and cuberite (though I wanted to add some documentation before making it public *shrugs*). You will only need to cd and docker-compose up inside this folder:

[tecnocraft copy.zip](https://github.com/cuberite/cuberite/files/609337/tecnocraft.copy.zip)

So... uhm... the stripped down version doesn't lag... that's rather embarrassing. I guess it may have something to do with CPU usage? volume mapping? permissions? At least I got the issue on a video with the original setup https://youtu.be/PKCHPONyrqE

The setup goes somewhat like this:
auth: spigot server with authme installed, once logged in will redirect you to lobby
lobby: another spigot server, has no plugins loaded
survival: spigot server with some plugins loaded
creative: cuberite creative server
survival2: cuberite survival server

On my video only survival2 lagged, even though it's kind of an exact copy of creative (same cuberite, same host os, most configs are the same, etc).

You will probably notice the docker-compose.yml from cuberite services have this:

```
tty: true
stdin_open: true
```

That's because cuberite starts and then (safely) stops if no tty and stdin are attached. This is the first server software I see having this behavior. Don't know if it's a bug or not.

I can also upload the whole thing somewhere if you want (±340MB 7zipped).

**Comment by yangm97** [comment]
I have rewritten most of my docker-compose.yml and re-created the volumes while trying to isolate the issue but it seems to be gone for good. I can't reproduce it anymore. Meanwhile, another issue popped out: spigot creates directories and then complains it can't write there. This doesn't happen when docker run is used instead of docker-compose, so I guess there could be something wrong with docker-compose itself. I'm going to close this until the issue happens again and is easier to reproduce.
PS: should I open a issue for the tty/stdin thing?

**Comment by madmaxoft** [comment]
For the tty/stdin, you need to run with the `-d` (or `--service`) parameter, this instructs the server to act as a daemon.

**Comment by yangm97** [comment]
Containerized services shouldn't run as daemons unfortunately. Docker requires the PID 1 processes to be always running, and when a service like nginx or cuberite tries to run as a daemon, that means PID1 is gone right after launching the service, and since docker thinks PID1 is your service it will shut down the whole container with exit code 0.

**Comment by Cl1608Ho** [comment]
The -d or service option only means it ignores a closed stdin..... Nothing more

Cuberite doesn't check if there is an stdin directly after starting but checks in the main loop and exits the program if the stdin is closed. That means that if you run it without a stdin it instantly exits. It should actually be done that if there is no stdin directly at start to ignore that check automatically

**Comment by yangm97** [comment]
I tried running Cuberite with the -d flag and the container shut down with exit code 0. Running without -d flag and stdin causes it to safely shut down right after startup. 
So far the only way to run it is with stdin open and not using the daemon mode.
