### ISSUE TITLE
Boats will stutter when over only 1 block of water, drive-able when falling (glide), and move fast on land

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3449]
Taken from #1109

**Comment by madmaxoft** [comment]
I think there have been changes to boats in Vanilla and they don't break (that often) anymore

**Comment by PureTryOut** [comment]
Indeed, they are much, much harder to break now (which is great). Now they basically only break when hitting land at full speed.

**Comment by yangm97** [comment]
I tried it myself. Tried crashing multiple times and even tried fall damage, did not break either.
While trying fall damage, I figured out I could not only control the boat midair but also control it on land.

**Comment by Seadragon91** [comment]
In 1.11.2 boats doesn't break anymore.

**Comment by yangm97** [comment]
What about the issue with stuttering on 1 block, flying boats, and the boat being “drive-able” on land? Where they fixed too?

**Comment by Seadragon91** [comment]
Oh sorry, then. I also see that the boat has no breaking animation like the minecart.

**Comment by mathiascode** [comment]
Boats can move slowly on land in vanilla.

**Comment by yangm97** [comment]
When I tested, it would move at a reasonable speed. Not sure if that changed since then.

**Comment by yangm97** [comment]
Updated the title with the possible remaining issues to avoid confusion.

**Comment by Pokechu22** [comment]
They move somewhat slowly on land (it was faster during some of the first 1.9 snapshots), but move very fast on ice and in mid-air in vanilla.  Note that all of the most of the logic is also clientside now.

**Comment by lyn1337** [comment]
They still "stutter" after commit f0c73e8466fbb52bb805dd839f5e4fd37d59af8
but apart from that, nothing odd.
