### ISSUE TITLE
cPlayer:CloseWindow() option to prevent tossing the currently held item

### ISSUE THREAD

**Issue by Cl1608Ho** [cuberite/cuberite#3463]
I would like to suggest an extra option to the `CloseWindow()` function to prevent a currently held item to be tossed. Basically I am trying to implement a clickable interface and `cLuaWindow:OnWindowSlotChanged` works fine for that because its called whenever an item is clicked inside of the window. However, closing the window immediately with `cPlayer:CloseWindow()` (to open another window) causes the server to toss the selected item so actually gives the player this item. I would like to prevent this behavior as it is useful for creating all kind of clickable GUIs

An alternative would be to allow the `OnPlayerTossingItem` hook to prevent this behavior

**Comment by Seadragon91** [comment]
Similar #813
