### ISSUE TITLE
Item lore modified in creative inventory

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#3467]
When using lore containing an empty line (two consecutive line-ends), it gets modified when the item is moved in creative inventory.

To observe, use the Debuggers' plugin's `/setlore` and `getlore` commands, and a 1.10.2 client.

Steps to reproduce:
Switch to creative.
Add an item to player hotbar.
Set lore on the item that includes two back-apostrophes: ```a``b```
Verify that the lore on the `cItem` is correct in Cuberite (`/getlore`)
Open (creative) inventory and move the item from one slot to another.
Check the lore on the moved item. The double-back-apostrophes are no longer there: ```a`b` ```

This is caused by the client ignoring multiple line-ends, handling them as a single one, and our inventory code trusting the client to move the item, so instead of keeping track of the item in hand while being moved, the CreativeInventoryAction packet's Item is being set into the slot (`cSlotAreaInventoryBase::Clicked()`)

**Comment by Pokechu22** [comment]
> This is caused by the client ignoring multiple line-ends, handling them as a single one, and our inventory code trusting the client to move the item, so instead of keeping track of the item in hand while being moved, the CreativeInventoryAction packet's Item is being set into the slot ( cSlotAreaInventoryBase::Clicked() )

The creative inventory does not move items.  It deletes them and recreates them.  Trying to validate the movement of items in creative is a Bad Idea&trade; as you're probably going to run into situations where there wasn't movement (eg, a player trashes one enchanted book and then grabs another book out of the creative inventory - to the server that's indistinguishable from them picking up an enchanted book and placing down one with different meta).

That said: The client supports multiple line ends.

![2016-11-27_15 55 46](https://cloud.githubusercontent.com/assets/8334194/20652997/0a9f665c-b4ba-11e6-8dd4-d19dcb310128.png)

(created by running `/give @p minecraft:feather 1 0 {display:{Lore:["Test","","","foo"]}}`).  Remember, lore isn't one string with `\n` in it - it's a list of strings.  It might be that cuberite is storing it as 1 long string, and then parsing it as iterating through all the lines and adding `\n` to the end of each - that could cause this behavior (I don't know how the client treats multiple `\n`s in text exactly, but I know it does do some kind of trimming similar to Java's [`String.split`](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#split\(java.lang.String\)).)

**Comment by peterbell10** [comment]
Fixed by #3882
