### ISSUE TITLE
Preformance Usage Chart

### ISSUE THREAD

**Issue by DarrenRainey** [cuberite/cuberite#3473]
For those interested in cuberite prefromace here is a chart I made for RAM/Swap (Bench marked On Nano Pi Neo - Raspberry  Pi clone)

![cubruite ram](https://cloud.githubusercontent.com/assets/6136439/21054476/d5f82f18-be25-11e6-8b6f-b3cc39f554d0.png)

**Comment by DarrenRainey** [comment]
System IDLE
2.3& cpu
68mb ram
0 swap

Cuberite (No players)
~5% CPU
204 mb ram
0 swap

Cubrite (1 player)
36% CPU
206 mb ram
0 swap

Load time around 35-45 seconds

**Comment by yangm97** [comment]
How did you make this beautiful chart? Also, shouldn't this be posted on the [forum](http://forum.cuberite.org/) instead?

**Comment by DarrenRainey** [comment]
I made it using Paint.net and open office with some data I got of my server using htop also I didn't realize there was a forum so ill go and post it there as well

**Comment by slang800** [comment]
close as non-issue?
