### ISSUE TITLE
Represent cItem::m_Lore as an AStringVector

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#3475]
Currently `cItem::m_Lore` is represented as a single string, which makes it impossible for Cuberite to make available the entire character set - one character needs to be set apart as the string separator when serializing / parsing the lore.

We should instead represent the lore as a full `AStringVector`, so that the full character set can be used for the lore. This change should be done as soon as possible, while there are not too many plugins actually using the `m_Lore` member.

**Comment by madmaxoft** [comment]
Options:
 - Add manual API binding for setting `m_Lore` that accepts both string and table, parses the string in the old way
 - Export the AStringVector Lore as a differently-named symbol, add a manual API binding for m_Lore that translates to and from the old way
 - Break the existing plugins (23 instances currently on GitHub: https://github.com/search?l=Lua&q=m_Lore&type=Code )

**Comment by NiLSPACE** [comment]
I'd think accepting both a string and a table is the best approach. Perhaps we could give a warning when a string is given?

**Comment by madmaxoft** [comment]
The problem with that is when a plugin attempts to read the value, we can't know if it expects a string or a table.

**Comment by madmaxoft** [comment]
Even that could be solvable - the return value could be a Lua table of all the Lore strings, with a `__tostring` meta-function that would return the concatenated strings (and possibly output a warning to the console). Not sure how that would behave with the current plugins.

**Comment by tigerw** [comment]
Sorry about this, I was at a loss for how to specify multiple lores when this was initially done. Now there is legacy backcompat. :(
