### ISSUE TITLE
leashed animals dont follow you

### ISSUE THREAD

**Issue by sagr4019** [cuberite/cuberite#3477]
Client version:   1.10.2 and all other versions
Server OS:        Linux
Commit id:        ff4be64edc85bffb2fe73790b1ce6413d5449990

### Expected behavior
If I leash a animal It should follow me

### Actual behavior
you can leash a animal but it dont follow you

### Steps to reproduce the behavior
crafting a lead and try to leash a pig for example

**Comment by Seadragon91** [comment]
Duplicate of #2729.
