### ISSUE TITLE
Support the 1.11 network protocol

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#3479]
Add support for the 1.11 network protocol.

Protocol docs: http://wiki.vg/index.php?title=Pre-release_protocol&direction=prev&oldid=8291

This issue is only about the protocol, not about the other features of that release.

  - [x] Protocol plumbing (new class, version number, client recognition)
  - [x] Fix packet IDs for normal gameplay (clients don't D/C)
  - [ ]  Skeletons are invisible
  - [ ]  Wither skeletons, villager zombies, skeleton horses and zombie horses don't spawn at the moment
  - [ ]  Spawn eggs are blank due to changes in vanilla entity names
  - [ ]  Mob spawners don't work due to changes in vanilla entity names
  - [ ]  Chests and enderchests are invisible

**Comment by Pokechu22** [comment]
The hard part will be... entities.  Even if you don't support Llamas, all horse variants got split into their own entities (with their own metadata).  Same with skeletons and zombies.

Also, [Protocol History](http://wiki.vg/Protocol_History#1.11) will help you out, and [Entities](http://wiki.vg/Entities) contains most of the 1.11 changes in a cleaner format than pre-release protocol.

**Comment by madmaxoft** [comment]
Okay, I've done the basics, now someone better than me could do the rest - the entities etc. :)

**Comment by mathiascode** [comment]
Minecraft 1.11.2 has been released with protocol version 316.

**Comment by madmaxoft** [comment]
![oh god why](http://cdn.pophangover.com/wp-content/uploads/2012/07/disgusted-oh-god-why-text.png)

**Comment by Pokechu22** [comment]
They the protocol version number because they added a new item (iron nuggets) and a few new metadata fields.  But there aren't any other changes that could affect the project - obviously, we'll need to make the entity changes at some point, but for now they don't matter.

**Comment by mathiascode** [comment]
These are the issues I've found when testing 1.11:
- Shooting into the ground many times with a bow disconnects the client
- Snowballs and enderpearls go through players and blocks
- Chests and enderchests are invisible (known issue)
- Every mob disconnects the client (known issue)
- Spawn eggs turn into blank spawn eggs

**Comment by mathiascode** [comment]
It seems like any kind of pickup kicks the client.

**Comment by mathiascode** [comment]
What needs to be fixed:
- Snowballs and enderpearls go through players and blocks
- Skeletons are invisible
- Wither skeletons, villager zombies, skeleton horses and zombie horses don't spawn at the moment
- Spawn eggs are blank due to changes in vanilla entity names 
- Mob spawners don't work due to changes in vanilla entity names
- Chests and enderchests are invisible

**Comment by madmaxoft** [comment]
I've rewritten the list into the main post as checkboxes.

I don't expect snowballs going through entities to be a protocol-specific issue, so I haven't included that item.

**Comment by mathiascode** [comment]
Enderpearls seem to work properly now. Actually, snowballs still hit entities, but there are no snowball particles. It looks like the snowball goes through things. In 1.10 and below, the particles show up.
