### ISSUE TITLE
Should StringSplit return iterators?

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#3502]
Just a thought. As we all know, copying is not as good as not copying, and StringSplit which I believe is oft-used, returns copies of parts of the original string.

Any thoughts on if it would be beneficial to performance and memory if iterators to positions in the input were returned? Or too much potential for disaster?

If we made the inputs const then I suppose an advanced optimiser could in theory effect some variant of copy elision by transforming the code to do this (i.e. return iterators) for us, but that seems like something that isn't coming for a long time.

**Comment by NiLSPACE** [comment]
It would break allot of plugins, so I'd say no.

**Comment by madmaxoft** [comment]
The exported API function could still behave the same, even if we changed the C++ side of the internals.

Still, I'd say this is a prime example of premature optimization. Do we have a use-case where we can see that `StringSplit` is causing poor performance? I very much doubt that, so let's not bother, unless you prove me wrong :)

**Comment by pwnorbitals** [comment]
Could be closed now
