### ISSUE TITLE
BroadcastSoundParticleEffect doesn't work

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3505]
### Expected behavior
Plugin developers can use BroadcastSoundParticleEffect in their plugins without issues.

### Actual behavior
BroadcastSoundParticleEffect does not work at the moment. The API documentation says that you should specify an effect ID, but it returns this error in the console:
```
error in function 'BroadcastSoundParticleEffect'.
     argument #2 is 'number'; 'const EffectID' expected.
```
This problem was introduced in 83870f9fc0e19da646f408a2d6636adfe4b5c002.

### Steps to reproduce the behavior
Use the super pickaxe in WorldEdit. Activate it by executing the command //, and break blocks using a pickaxe.

**Comment by Seadragon91** [comment]
How should this be fixed? Should we export `EffectID` to lua or overloading the method to accept a int instead like before again?

**Comment by NiLSPACE** [comment]
Perhaps it should be exported manually to accept integers. We might also want to create an enum for this. Having magic numbers in the code is ugly.

**Comment by Seadragon91** [comment]
There is already a enum for it:
https://github.com/cuberite/cuberite/blob/master/src/EffectID.h#L3

One problem is tolua doesn't like that enum def `enum class EffectID : Int32`

**Comment by Seadragon91** [comment]
Didn't saw the linked pull request...

**Comment by Seadragon91** [comment]
A few questions:
* Should we rename them? Currently they have no prefix and have underlines
* Changing the enum names, to particle and sound?

Source for the new group names:
http://wiki.vg/Protocol#Effect

**Comment by peterbell10** [comment]
Just FYI, I'm working on adding scoped enum support to tolua++.

**Comment by Seadragon91** [comment]
Okay thanks for the info. Just wanted to dig in tolua to look if I can implement that, hehe :)
