### ISSUE TITLE
Placing a rail above another rail is possible but shouldn't

### ISSUE THREAD

**Issue by mohe2015** [cuberite/cuberite#3507]
Client version:   1.10.2
Server OS:        Linux (Ubuntu 16.04 LTS)
Commit id:        c8b1d8a37d6073786df34836ed1e2c88652ac629

### Expected behavior
You can't place a rail above another rail.

### Actual behavior
If you try to place a rail above another rail the rail above appears very short and drops directly. It shouldn't be possible to even place it.
![2016-12-30_23 33 51](https://cloud.githubusercontent.com/assets/13287984/21573786/f46fac9a-cee8-11e6-95a6-dff15926faf4.png)

### Steps to reproduce the behavior
Try to place a rail above another rail.

**Comment by mathiascode** [comment]
Possibly related: #3196

This seems to happen with other blocks too, e.g. placing trapdoors on top of another block.
