### ISSUE TITLE
Purpur Stairs face one direction only

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3508]
Client version:   1.8 - 1.10
Server OS:        Linux
Commit id:       c8b1d8a37d6073786df34836ed1e2c88652ac629

### Expected behavior
Expected the Purpur Stairs to be pointing in the right direction based on where I'm stood.

### Actual behavior
The Purpur Stairs faced one direction only.
![purpur](https://cloud.githubusercontent.com/assets/518378/21574077/90449874-cee4-11e6-8280-4efcd0fc93c1.png)
### Steps to reproduce the behavior
I thoroughly tested each and every stair block and found the Purpur stairs to be the only ones facing in one direction only.

**Comment by mathiascode** [comment]
This happens because there is no code handling the purpur stairs yet. It will be fixed when #3503 is merged.

**Comment by HelenaKitty** [comment]
I figured that was the case, well I trust that #3503 will get merged!

**Comment by mathiascode** [comment]
This is fixed now.
