### ISSUE TITLE
Spelling error in furnace.txt

### ISSUE THREAD

**Issue by SadinDrapic** [cuberite/cuberite#3524]
Client version:   1.8.9
Server OS:        Windows 10
Commit id:       45ce828

### Steps to reproduce the behavior: in "furnace.txt", line 66, there is a writing mistake, item golden leggings is named "GoldLeggings" and it should be "GoldenLeggings".
("offending line: "GoldLeggings=                    GoldNugget""
![slika1](https://cloud.githubusercontent.com/assets/24959277/21719359/a932d664-d41d-11e6-8069-c010d3a4031d.png)
![slika2](https://cloud.githubusercontent.com/assets/24959277/21719360/a93662b6-d41d-11e6-8346-60d1d5790738.png)

**Comment by SadinDrapic** [comment]
And also when you smelt iron stuff, should get "IronNugget", item that doesnt exist. It just crashed my MC.

**Comment by mathiascode** [comment]
Already fixed in #3521. Iron nuggets were added in Minecraft 1.11.1, which Cuberite doesn't support yet.

**Comment by SadinDrapic** [comment]
Thanks! :D
