### ISSUE TITLE
Player::IsOnGround() does not return correct value if you are standing on the edge of a block

### ISSUE THREAD

**Issue by mohe2015** [cuberite/cuberite#3528]
This issue is one reason why the anticheat does not work correctly.

**Comment by madmaxoft** [comment]
The value only reflects what the client sends to the server, there is no server-side calculation at all.

**Comment by mohe2015** [comment]
Strange... Then I have to look into it again.

**Comment by NiLSPACE** [comment]
The client probably just looks if there is a block straight under him.
