### ISSUE TITLE
The End suffix doesn’t match bukkit/spigot/sponge

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3531]
When you start a bukkit-based sever, you get *worldname*_the_end while on cuberite you get *worldname*_end. I just noticed this when importing a world from a spigot, cuberite had generated another end world. This is a minor issue though it can annoy players coming from spigot/sponge/bukkit/whatever.

**Comment by NiLSPACE** [comment]
Strange, I could've sworn they used `<name>_end`.

**Comment by Pokechu22** [comment]
`world_the_end` is actually a bukkitism.  The vanilla server creates a `world` folder with `DIM1` for the end and `DIM-1` for the nether inside.  (Bukkit doesn't do that because it causes problems with multiworld).  I don't think that either server implementation uses `world_end`.

**Comment by yangm97** [comment]
That’s right. Updated the issue.

**Comment by Bond-009** [comment]
Fixed in #3538
