### ISSUE TITLE
./compile.sh on "Ubuntu on Windows"

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3532]
When I use ./compile it throws an error:
`./compile.sh: 121: ./compile.sh: Syntax error: word unexpected (expecting "in")`

**Comment by LogicParrot** [comment]
What operating System / distro are you using? And what shell?

**Comment by Bond-009** [comment]
I'm using bash on Ubuntu on Windows

**Comment by LogicParrot** [comment]
>Ubuntu on Windows

On a virtual machine, I presume?

**Comment by Bond-009** [comment]
No it isn't a virtual machine
https://www.google.be/#q=bash+on+ubuntu+on+windows

**Comment by LogicParrot** [comment]
The script was coded with real *NIX. Your best shot for now is compiling for [Windows](https://github.com/cuberite/cuberite/blob/master/COMPILING.md#windows), or [downloading a binary](https://cuberite.org/). The script is working fine on a Debian installation.

Still, I wonder why it fails at a `case` statement, and I wonder if we can make it work on "Ubunto for Windows".

Can anyone confirm the script is running well on regular Ubuntu?

**Comment by yangm97** [comment]
Ubuntu on Windows has the very same set of userspace binaries and (thinks) it’s running on top of a linux-compliant filesystem. The only difference between stock ubuntu and WSL (windows subsystem for linux) should be the missing linux kernel. Instead, system calls are “translated” and executed by windows kernel, kind like a reverse wine, though some features are still not implemented (ping would not work on very early builds for instance). 

I think the WSL github page has some debugging instructions, might be relevant for this issue.

**Comment by Bond-009** [comment]
It works in my Xubuntu virtual machine

**Comment by Cl1608Ho** [comment]
@yangm97 thats why I think compiling inside a wine-like environment and then running it inside that..... Performance-wise

**Comment by yangm97** [comment]
@Cl1608Ho performance is strangely good. Some Linux software run faster on Windows Kernel than on Linux (as seen on [phoronix](http://www.phoronix.com/scan.php?page=article&item=windows-10-lxcore&num=2)), GNU ping has less latency than win32 ping and some other things actually run faster on WSL than on windows itself (or so my Windows friend says). 

No wonders why Microsoft wants to move away from win32 to winRT...

**Comment by Seadragon91** [comment]
I tested this the script with arguments in "ubuntu on windows" and it works fine on my side.

**Comment by Bond-009** [comment]
Fixed by changing the line endings to LF

**Comment by LogicParrot** [comment]
Perhaps this should be reported upstream?
