### ISSUE TITLE
cClient:GetProtocolVersion always returns 4

### ISSUE THREAD

**Issue by ard1998** [cuberite/cuberite#3561]
Client version:   all supported
Server OS:        Windows
Commit id:        97980d11038e57faa905a27977545fb77ff2c5bd

### Expected behavior
`cClient:GetProtocolVersion` returns actual protocol version

### Actual behavior
`cClient:GetProtocolVersion` always returns 4

### Steps to reproduce the behavior
using my plugin https://github.com/ard1998/PlayerClientFilter

**Comment by madmaxoft** [comment]
(Edited the post to clarify the issue)

You're right, there's an oversight in this, it hasn't worked properly since the times of 1.7. I'll fix it shortly.
