### ISSUE TITLE
Peaceful mobs not spawning

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3582]
Client version:   1.9.4
Server OS:        RPi
Commit id:       1c31cb7eecc92d2fb218da8948e3201b618a46d2

### Expected behavior
Friendly mobs spawn.

### Actual behavior
They don't. In fact, all of them vanished without a trace after upgrading from a months older version to the current one, today.

**Comment by mathiascode** [comment]
What does the world.ini file of your world look like? Peaceful mobs should still spawn without issues.

**Comment by jammet** [comment]
Maybe this will help. I've rolled back to the old version for now.

`
[SpawnProtect]
ProtectRadius=10

[WorldLimit]
LimitRadius=400

[Difficulty]
; WorldDifficulty=2 is normal 1 is easy 0 is peaceful
WorldDifficulty=2

[General]
Dimension=Overworld
IsDaylightCycleEnabled=1
Gamemode=0
Weather=1
TimeInTicks=20860
UnusedChunkCap=1000
WorldAgeMS=2263086

[Broadcasting]
BroadcastDeathMessages=1
BroadcastAchievementMessages=1

[SpawnPosition]
MaxViewDistance=12
X=68.000000
Y=71.600000
Z=143.000000
PregenerateDistance=20

[Storage]
Schema=Default
CompressionFactor=6

[Plants]
MaxCactusHeight=3
MaxSugarcaneHeight=3
IsCactusBonemealable=0
IsCarrotsBonemealable=1
IsCropsBonemealable=1
IsGrassBonemealable=1
IsMelonStemBonemealable=1
IsMelonBonemealable=0
IsPotatoesBonemealable=1
IsPumpkinStemBonemealable=1
IsPumpkinBonemealable=0
IsSaplingBonemealable=1
IsSugarcaneBonemealable=0
IsBigFlowerBonemealable=1
IsTallGrassBonemealable=1
IsBeetrootsBonemealable=1

[Physics]
DeepSnow=1
ShouldLavaSpawnFire=1
TNTShrapnelLevel=2
WaterSimulator=Vanilla
LavaSimulator=Vanilla
SandInstantFall=0
RedstoneSimulator=Incremental

[Mechanics]
CommandBlocksEnabled=0
PVPEnabled=0
UseChatPrefixes=1
MinNetherPortalWidth=2
MaxNetherPortalWidth=21
MinNetherPortalHeight=3
MaxNetherPortalHeight=21

[Monsters]
; Types=wolf, bat, cavespider, chicken, cow, creeper, enderman, horse, mooshroom, ocelot, pig, sheep, silverfish, skeleton, slime, spider, squid, zombie
VillagersShouldHarvestCrops=1
AnimalsOn=1
Types=wolf, bat, cavespider, chicken, cow, horse, mooshroom, ocelot, pig, sheep, skeleton, spider, squid, zombie

[Weather]
MaxSunnyTicks=180000
MinSunnyTicks=12000
MaxRainTicks=24000
MinRainTicks=12000
MaxThunderStormTicks=15600
MinThunderStormTicks=3600

[LinkedWorlds]
; NetherWorldName=world_nether
; EndWorldName=world_end
NetherWorldName=world_nether
EndWorldName=world_end

[Generator]
Generator=Composable
BiomeGen=Grown
ShapeGen=BiomalNoise3D
CompositionGen=Biomal
Finishers=RoughRavines, WormNestCaves, WaterLakes, WaterSprings, LavaLakes, LavaSprings, OrePockets, Mineshafts, Trees, Villages, SprinkleFoliage, Ice, Snow, Lilypads, BottomLava, DeadBushes, NaturalPatches, PreSimulator, TallGrass, Animals
BiomeGenCacheSize=64
BiomeGenMultiCacheLength=4
SeaLevel=62
BiomalNoise3DFrequencyX=40.000000
BiomalNoise3DFrequencyY=40.000000
BiomalNoise3DFrequencyZ=40.000000
BiomalNoise3DBaseFrequencyX=40.000000
BiomalNoise3DBaseFrequencyZ=40.000000
BiomalNoise3DChoiceFrequencyX=40.000000
BiomalNoise3DChoiceFrequencyY=80.000000
BiomalNoise3DChoiceFrequencyZ=40.000000
BiomalNoise3DAirThreshold=0.000000
BiomalNoise3DNumChoiceOctaves=4
BiomalNoise3DNumDensityOctaves=6
BiomalNoise3DNumBaseOctaves=6
BiomalNoise3DBaseAmplitude=1.000000
CompositionGenCacheSize=64
WormNestCavesSize=64
WormNestCavesGrid=96
WormNestMaxOffset=32
WaterLakesProbability=25
LavaLakesProbability=10
MineShaftsGridSize=512
MineShaftsMaxOffset=256
MineShaftsMaxSystemSize=160
MineShaftsChanceCorridor=600
MineShaftsChanceCrossing=200
MineShaftsChanceStaircase=200
VillageGridSize=384
VillageMaxOffset=128
VillageMaxDepth=2
VillageMaxSize=128
VillageMinDensity=50
VillageMaxDensity=80
BottomLavaLevel=10
PreSimulatorFallingBlocks=1
PreSimulatorWater=1
PreSimulatorLava=1
RoughRavinesGridSize=256
RoughRavinesMaxOffset=128
RoughRavinesMaxSize=128
RoughRavinesMinSize=64
RoughRavinesMaxCenterWidth=8.000000
RoughRavinesMinCenterWidth=2.000000
RoughRavinesMaxRoughness=0.200000
RoughRavinesMinRoughness=0.050000
RoughRavinesMaxFloorHeightEdge=8.000000
RoughRavinesMinFloorHeightEdge=30.000000
RoughRavinesMaxFloorHeightCenter=20.000000
RoughRavinesMinFloorHeightCenter=6.000000
RoughRavinesMaxCeilingHeightEdge=56.000000
RoughRavinesMinCeilingHeightEdge=38.000000
RoughRavinesMaxCeilingHeightCenter=58.000000
RoughRavinesMinCeilingHeightCenter=36.000000
VillagePrefabs=PlainsVillage, SandVillage
OrePocketsBlocks=coalore:0:127:20:16 | ironore:0:64:20:8 | goldore:0:32:2:8 | redstoneore:0:16:8:7 | diamondore:0:15:1:7 | lapisore:0:30:1:6

[WaterSimulator]
Falloff=1
TickDelay=5
NumNeighborsForSource=2

[LavaSimulator]
Falloff=2
TickDelay=30
NumNeighborsForSource=-1

[FireSimulator]
BurnStepTimeFuel=500
BurnStepTimeNonfuel=100
Flammability=50
ReplaceFuelChance=50000

[Seed]
Seed=4711

[WaterSprings]
HeightDistribution=0, 0; 10, 10; 11, 75; 16, 83; 20, 83; 24, 78; 32, 62; 40, 40; 44, 15; 48, 7; 56, 2; 64, 1; 255, 0
Chance=24

[LavaSprings]
HeightDistribution=0, 0; 10, 5; 11, 45; 48, 2; 64, 1; 255, 0
Chance=9

[Animals]
AnimalSpawnChunkPercentage=10
`

**Comment by mathiascode** [comment]
Doesn't seem like anything is wrong there. Are you sure they aren't just spawning rarely?

**Comment by jammet** [comment]
I will check back after I get another chance to check for longer game play
duration. Will see what happens. :) Thank you.

**Comment by jammet** [comment]
So yeah, spawn eggs work as intended, but the entire world is basically devoid of non-monster life now. All dogs disappeared. All chickens and all sheep disappeared. No new ones whatsoever spawn in, except those from thrown chicken eggs or spawn eggs. ;(

If you like, you can watch the action by connecting to my server, if you still have the address. ;( Please help? Current commit is latest, again.

**Comment by mathiascode** [comment]
Could you send the IP via PM on the forum? My username there is "Mathias". This issue does seem very weird.

**Comment by LogicParrot** [comment]
Is this still an issue?

**Comment by bearbin** [comment]
Doesn't appear to be - peaceful mobs spawn just fine for me.

**Comment by LogicParrot** [comment]
Might be #3696

**Comment by jammet** [comment]
My server is doing well, and the creatures seem to be spawning.
