### ISSUE TITLE
Rails don't always reorient properly when corners formed.

### ISSUE THREAD

**Issue by Sheyin** [cuberite/cuberite#3588]
Client version:   1.10 (vanilla)
Server OS:        Windows 64
Commit id:       7c17f77c84711607bc0f2db5f2991887bf5c9b79 built at: 464

### Expected behavior
When rails are placed, and a corner is formed, the adjacent rail should rotate to continue the turn.

### Actual behavior
When the corner rail is placed, it (correctly) turns into a corner piece, but the next rail of the turn will not rotate to continue the turn.

### Steps to reproduce the behavior
Place two rails diagonal to one another as if forming a turn in the rails like below.  They should be facing the same direction.
![rails1](https://cloud.githubusercontent.com/assets/8756070/23337573/7200e664-fbb8-11e6-9e62-2f6578c2c7eb.jpg)

Place one rail adjacent to both pieces.  A corner piece will form and look like the image below.
![rails2](https://cloud.githubusercontent.com/assets/8756070/23337576/7972613e-fbb8-11e6-8cdd-f4c1ac3acf61.jpg)

**Comment by HelenaKitty** [comment]
I was about to write a bug report about the same problem, but it seems I no longer need to!

**Comment by sphinxc0re** [comment]
@Sheyin Thanks for the report! I wonder why noone ever encountered this bug...

**Comment by PascalMinder** [comment]
The is also the problem if two power rails should climb one block, only one is correct. The other stays horizontal.
