### ISSUE TITLE
Implement SRV records

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3592]
I read about implementing the 'cuberite new' subcommand as a way to spawn new instances of cuberite which could be useful as a virtual hosting solution. If you are going to implement such subcommand, then atleast add support for SRV records which can direct the connecting user to the corresponding Cuberite server.

Connecting directly via ports is often ugly, but if you have a hostname directing to the port then it looks cleaner.

**Comment by mathiascode** [comment]
I've been using an SRV record for my Cuberite server without issues.

**Comment by bearbin** [comment]
SRV records are a client side issue - closing as not applicable.
