### ISSUE TITLE
Server runs in a loop when the port is already bound

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3593]
Server OS:        Linux
Commit id:        1c31cb7eecc92d2fb218da8948e3201b618a46d2

### Expected behavior
The server should have shut down safely when it couldn't bind to the port.

### Actual behavior
Instead the server ran in a loop

### Steps to reproduce the behavior

Hold the port so nothing can bind to it, then start the Cuberite server and it should loop.

**Comment by madmaxoft** [comment]
This should be pretty easy to fix - the server already shows an error message if it cannot bind to any port, so add a call to terminate the server next to the log message. Marking as Easy.

**Comment by HelenaKitty** [comment]
Agreed!
