### ISSUE TITLE
Block can be placed on top of rails

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3594]
Client version:   1.11.2
Server OS:        Linux
Commit id:        1c31cb7eecc92d2fb218da8948e3201b618a46d2

### Expected behavior
I expected attempting to place blocks on top of rails to be traditional to Minecraft.

### Actual behavior
I was able to place blocks on top of the rails.

### Steps to reproduce the behavior
![2017-02-27_11 49 51](https://cloud.githubusercontent.com/assets/518378/23360519/b12b1cca-fce3-11e6-9450-27486aecd0f6.png)

**Comment by NiLSPACE** [comment]
What is the vanilla way?

**Comment by HelenaKitty** [comment]
In Vanilla, you can't place blocks on top of rails.

**Comment by madmaxoft** [comment]
Usually the client doesn't even send the relevant packets if it thinks you shouldn't be able to do something. This is probably the first case I see when it actually sends the packet and (perhaps) expects a negative answer?

**Comment by Bond-009** [comment]
I just tested this in Vanilla (1.11.2) and you can place blocks on rails.

**Comment by HelenaKitty** [comment]
Really? Thanks for confirming! Sorry for opening up an issue on this.

**Comment by Pokechu22** [comment]
However, I do remember being able to place rails on rails in cuberite (which is _not_ allowed in vanilla, but a packet is still sent); see #3507.  So it's possible that other blocks (say, torches) will also attempt to place on rails when they shouldn't.

**Comment by sphinxc0re** [comment]
So we should only allow solid blocks to be placed onto rails?

**Comment by Pokechu22** [comment]
I wouldn't say that exactly; in vanilla if you right-click a rail (or any other block that you can't place blocks on top of) with a torch (for example), then the torch will attach to the wall if there is one and fail to place otherwise.  It's an odd edge case, for sure...  I'd say it'd make more sense to update the code for *placing* rails (and other non-solid blocks) to reject placing on top of non-solid blocks, not the other way around.

**Comment by sphinxc0re** [comment]
What you are stating in case of the torch is just how torches work, isn't it?

**Comment by Pokechu22** [comment]
Yep. I'm not completely sure if that's how they work in cuberite, but I'm assuming they work that way too.  So it's basically just the same thing that needs to be done with rails, just with a different condition.

Can rails be placed on glass in cuberite?  (They can't in vanilla)
