### ISSUE TITLE
Option to update Cuberite logo

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3595]
I would like to update the Cuberite that appears next to the server entry in the Minecraft client to correspond with that of a community, however there is no option to do that. Is this possible, or does it go against licensing?

**Comment by Bond-009** [comment]
favicon.png
    This is the icon that will appear in the Minecraft server list. You may replace it with your own.

**Comment by Pokechu22** [comment]
Note that the icon is cached clientside; if I recall correctly you need to click "edit server" and there is a button to reset the icon.

**Comment by beezTEM** [comment]
What are the dimensions supposed to be of the new logo?

**Comment by Seadragon91** [comment]
It should be 64x64 pixels.

**Comment by williamhatcher** [comment]
Great. Let's add that to the handbook if it isn't already in it

**Comment by LogicParrot** [comment]
It already appears: https://book.cuberite.org/#2.1

But it does not indicate the required dimensions.

**Comment by LogicParrot** [comment]
Fixed in https://github.com/cuberite/users-manual/commit/84df09b2c30a31785cf89ab7f173340f3224ca09
