### ISSUE TITLE
API: ReplaceString(nil, nil, nil) causes the server to run in a endless loop

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3599]
Server OS:        Windows
Commit id:        83fa6cb

### Actual behavior
Server runs in a endless loop.

### Steps to reproduce the behavior
1) Add this code to a plugin inside a command handler: `ReplaceString(nil, nil, nil)`
2) Call the command

**Comment by Seadragon91** [comment]
No crash and server still runs, but the cpu is at 25% with no players on it.

**Comment by NiLSPACE** [comment]
Sounds like it went into an infinite loop for some reason.

**Comment by worktycho** [comment]
Looks like this might be some weirdness in the lua bindings, its unclear how tolua++ generated bindings for string functions handle being passed nil. Otherwise ther is not clear reason for ReplaceString to go into an infinite loop.
