### ISSUE TITLE
API: cWorld:SendBlockTo crashes the server

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3600]
Server OS:        Windows
Commit id:        83fa6cb

### Actual behavior
Server crashes if nil is passed instead of a player to the function.

### Steps to reproduce the behavior
1) Add this code to a plugin inside a command handler
2) Call the command
`cRoot:Get():GetDefaultWorld():SendBlockTo(1, 1, 1, nil)`

**Comment by worktycho** [comment]
We need to add an annotation to the to_lua parser for params that must be non-null. Also corresponding checking.
