### ISSUE TITLE
API: GetChar with incorrect params crashes the server

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3602]
Server OS:        Windows
Commit id:        83fa6cb

### Actual behavior
Using GetChar with incorrect params crashes the server,

### Steps to reproduce the behavior
Add this code to a plugin and start server:
`GetChar('VfLiOdisbBdpzsZwgd', -999999999999)`

**Comment by NiLSPACE** [comment]
Are there actually people using `GetChar`?

**Comment by madmaxoft** [comment]
I think we can safely remove this API function, since it is a subset of `string.sub`

**Comment by madmaxoft** [comment]
Most likely the performance is even worse than using `string.sub` directly.
