### ISSUE TITLE
API: cEntity:IsA(nil) crashes the server

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3603]
Server OS:        Windows
Commit id:        83fa6cb

### Actual behavior
Passing a nil value to `a_Entity:IsA()` crashes the server.

### Steps to reproduce the behavior
Add this code to a plugin and run it:
`cRoot:Get():GetDefaultWorld():ForEachEntity(function(a_Entity) a_Entity:IsA(nil) return true end)`

**Comment by worktycho** [comment]
Probably the same fundamental issue as #3599 tolua generated bindings have weird handling of nils for string parameters.
