### ISSUE TITLE
API: cStringCompression.UncompressStringZLIB with incorrect params crashes the server

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3605]
Server OS:        Windows
Commit id:        83fa6cb

### Actual behavior
Calling the function with incorrect params crashes the server.

### Steps to reproduce the behavior
Add this code to a plugin and run it:
`cStringCompression.UncompressStringZLIB('upyBepByLnDKZYmmUk', 999999999999)`

**Comment by worktycho** [comment]
Quick triage: There is currently no checking on any of the Uncompress functions that the buffer size is sane. The only real question is where to put it. My view is that we should have a sanity check in ManualBindings that returns an error to lua on failure, and an assert in cStringCompression. Additionally this is probably an issue with other APIs that provide a buffer size.
