### ISSUE TITLE
All my sheep are missing, left with only one cow!!

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3609]
Client version:   1.9
Server OS:        Linux
Commit id:        83fa6cb851536839ebd85b1e91fda928f47eb674

### Expected behavior

I come onto the server, and find all my sheep and cows where I left them.

### Actual behavior

Instead, I come on the server and find all my sheep have gone, and I am left with just one cow!

### Steps to reproduce the behavior

Unknown

![2017-03-01_16 31 27](https://cloud.githubusercontent.com/assets/518378/23469951/066d02ec-fe9d-11e6-9278-77c5c831612c.png)

![2017-03-01_16 31 37](https://cloud.githubusercontent.com/assets/518378/23469958/0bd12a6a-fe9d-11e6-9c4f-c34dcba53693.png)

**Comment by Bond-009** [comment]
#3215

**Comment by HelenaKitty** [comment]
Aaah, so this is a Vanilla issue, I never noticed this in Vanilla myself. I'm not getting the bug where they head to 0, 0, 0 though. Thank you very much!

**Comment by HelenaKitty** [comment]
Upon relog, the animals are now back in their pen!

![2017-03-01_16 49 58](https://cloud.githubusercontent.com/assets/518378/23470749/1f9325c4-fe9f-11e6-9d7c-2754870ec6d9.png)

**Comment by Bond-009** [comment]
Yes it happens in vanilla to but that doesn't mean it should also happen Cuberite.

**Comment by Pokechu22** [comment]
> Upon relog, the animals are now back in their pen!

Probably this is a different issue, then; invisible entities is odd behavior.

**Comment by HelenaKitty** [comment]
I also noticed that upon logging in, the animals move around in fast motion for a while.

**Comment by mathiascode** [comment]
Closing in favor of #3696
