### ISSUE TITLE
After switching from Survival mode to Creative mode, I can no longer fly

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3612]
Client version:   1.9
Server OS:        Linux
Commit id:        83fa6cb851536839ebd85b1e91fda928f47eb674

### Expected behavior

Player can fly after switching to Creative mode

### Actual behavior

Instead, the player can't fly

### Steps to reproduce the behavior

Unknown

**Comment by mathiascode** [comment]
This no longer happens.
