### ISSUE TITLE
API: cItemGrid has functions that crashes the server

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3614]
Server OS:        Windows
Commit id:        83fa6cb

### Actual behavior
Passing incorrect param crashes the server.

### Steps to reproduce the behavior
This three functions crashes the server:
`AddItem, GetNextUsedSlot and GetNextEmptySlot`

Added example code for every three of them. For testing add it to a command handler and run it.
```
cRoot:Get():GetDefaultWorld():SetBlock(10, 100, 10, E_BLOCK_CHEST, 0)
cRoot:Get():GetDefaultWorld():DoWithChestAt(10, 100, 10,
	function(a_ChestEntity)
		a_ChestEntity:GetContents():AddItem(cItem(1, 2), false, -999999999999)
	end)

cRoot:Get():GetDefaultWorld():SetBlock(10, 100, 10, E_BLOCK_CHEST, 0)
cRoot:Get():GetDefaultWorld():DoWithChestAt(10, 100, 10,
	function(a_ChestEntity)
		a_ChestEntity:GetContents():GetNextUsedSlot(-999999999999)
	end)
cRoot:Get():GetDefaultWorld():SetBlock(10, 100, 10, E_BLOCK_CHEST, 0)
cRoot:Get():GetDefaultWorld():DoWithChestAt(10, 100, 10,
	function(a_ChestEntity)
		a_ChestEntity:GetContents():GetNextEmptySlot(-999999999999)
	end)
```

**Comment by worktycho** [comment]
This looks like an underlying issue with bounds checking in tolua generated bindings. Specifically it contains an unchecked cast. To fix this to add bounds checking you will need to change https://github.com/cuberite/toluapp/blob/a45c5ab19707ae8f2935aab30c273389a7896c92/src/bin/lua/declaration.lua#L244. This effects all automatically bound integer parameters.
