### ISSUE TITLE
A Redstonesignal should go up even with a stair in the "way"

### ISSUE THREAD

**Issue by lixfel** [cuberite/cuberite#3615]
Client version:   1.10.2
Server OS:        Linux_x64
Commit id:        approx: 83fa6cb851536839ebd85b1e91fda928f47eb674

### Expected behavior
![2017-03-03_07 44 17](https://cloud.githubusercontent.com/assets/26159085/23541583/a9859218-ffe8-11e6-8a31-78d95f4fc4f0.png)

### Actual behavior
![2017-03-03_07 46 04](https://cloud.githubusercontent.com/assets/26159085/23541591/b3a26c30-ffe8-11e6-8f68-95f108e8862a.png)
With Slabs, Ladders, Torches... is it running normally (signal goes up), only with Stairs the signal isn't going up.

### Steps to reproduce the behavior
Build it like in the pictures.

**Comment by peterbell10** [comment]
Stairs were fixed by #3988 but all slabs except wood, red sandstone and purpur are still incorrect.

**Comment by mathiascode** [comment]
No longer an issue.
