### ISSUE TITLE
(1.11) Spawn eggs are reset upon opening and closing the creative inventory, meaning you can't grab them from it

### ISSUE THREAD

**Issue by Pokechu22** [cuberite/cuberite#3617]
Client version:   1.11.2
Server OS:        Windows
Commit id:        d0b956d8c48019228942534b54cab4c8224d82b9 (manually compiled)

### Expected behavior

Spawn eggs remain the same after closing and reopening the creative inventory.

### Actual behavior

Spawn eggs lose their mob data after closing and reopening the creative inventory.

### Steps to reproduce the behavior

1. Give yourself a spawn egg (for instance, `/give <name> 383 1 51` for a skeleton egg).
2. Right-click with the spawn egg, and observe that it successfully spawns a skeleton.
3. Open and close the creative inventory without doing anything else.
4. Observe that the spawn egg is now gray and labeled "Spawn", and doesn't work.

Alternatively:

1. Open the creative inventory, and switch to the Miscellaneous tab.
2. Grab a spawn egg.
3. Observe that the spawn egg is reset upon closing the inventory.

### Probable cause

1.11 changed entity IDs to use a `minecraft:entity` format instead of `Entity`.  Currently, cuberite remaps old _numeric_ spawn egg metadatas (such as 51) to textual ids such as `Skeleton` when sending them to 1.9 clients, and reverses that process when receiving.  However, the receiving portion doesn't handle the new IDs, causing them to be lost when parsed from 1.11.  Fixing this would require adding a new reader for them (in 1.11's protocol) like the 1.9 version, which probably shouldn't be too hard.  The hard part would be recognizing wither skeleton/zombie villager/etc, basically all of the split mobs, but that's not currently possible for other reasons.

**Comment by mathiascode** [comment]
Fixed in #3724
