### ISSUE TITLE
Mobs collide with Dead Bush

### ISSUE THREAD

**Issue by tomgie** [cuberite/cuberite#3618]
Client version:  1.11.2
Server OS:        Linux
Commit id:       #d0b956d

### Expected behavior
Mobs should not be able to collide with a dead bush when walking through it

### Actual behavior
Mobs collide with the Dead Bush as in it is a solid block.

### Steps to reproduce the behavior
Find any mob and place dead bushes around it, it will jump onto the dead bushes in its way.

**Comment by NiLSPACE** [comment]
Should be fairly easy. The dead bush is missing [here](https://github.com/cuberite/cuberite/blob/master/src/BlockInfo.cpp#L519).
