### ISSUE TITLE
Visual bug on placing blocks

### ISSUE THREAD

**Issue by willi123yao** [cuberite/cuberite#3626]
Client version:   1.8
Server OS:        Linux
Commit id:        9fa8477b73ce878c631ba875ec10746b4143ba75

### Expected behavior
The block should replace it and not create another one.

### Actual behavior
Only a single block should be placed, however there are 2 of them.

### Steps to reproduce the behavior
Take a dead bush or a double-tall grass and place a block on it. 

#### Notes:
However, it is actually only one block as when you break the additional block, the block over it will also break. If you break the original block it will be a single-hit-dig and there will be no drops.

####Screenshot:
_Before placing:_
![2017-03-17_11 20 54](https://cloud.githubusercontent.com/assets/26355099/24027625/dd780e54-0b03-11e7-9e93-fa3a77d64901.png)

_After placing:_
![2017-03-17_11 20 57](https://cloud.githubusercontent.com/assets/26355099/24027635/f76661e4-0b03-11e7-97f8-c2a746fe4490.png)

**Comment by madmaxoft** [comment]
That should be easy to fix, too, most likely a flag is missing for the dead bush block that it is click-through.

**Comment by willi123yao** [comment]
By the way, this is also the case for tall grass(2-block grass).

**Comment by Seadragon91** [comment]
Dead bush works, but I have a problem with double plants (`E_BLOCK_BIG_FLOWER`). There are 5 meta types, but only if it's 2 or 3 then it should be replaced.

How can I get the meta of the block? The function `DoesIgnoreBuildCollision` has no params.

**Comment by Seadragon91** [comment]
Found it, it's overloaded
