### ISSUE TITLE
Golden apples eating bug

### ISSUE THREAD

**Issue by willi123yao** [cuberite/cuberite#3627]
Client version:   1.8
Server OS:        Linux
Commit id:        9fa8477b73ce878c631ba875ec10746b4143ba75

### Expected behavior
In creative mode, it should be impossible to eat food at all.

### Actual behavior
When right-clicking golden apples in creative, it will get consumed after a few seconds

### Steps to reproduce the behavior
Go into creative mode, get a golden apple(enchanted or non-enchanted) and right-click. After 3 secs it will be consumed.

**Comment by Lightn1ng** [comment]
Can't reproduce here.
