### ISSUE TITLE
Objects in water occasionally moving the wrong way

### ISSUE THREAD

**Issue by Sheyin** [cuberite/cuberite#3632]
Client version:   1.89, 1.10
Server OS:        Windows
Commit id:        efa5d449bddadf74d59d0399a0c804f53bd6a99c

### Expected behavior
Objects in the water should flow in the same direction of the water.

### Actual behavior
It does flow with the water if it is inserted further down from the source, but stutters a bit along the way.  If it is dropped in the source block, the object will sometimes move backwards, away from the direction the water is flowing and out of the water. (before getting vacuumed up by the player)

### Steps to reproduce the behavior
Put a water source block down in a canal and drop an object in different points along the way.

![eggexperiment](https://cloud.githubusercontent.com/assets/8756070/24076332/82a0c4e6-0bfb-11e7-988a-d5ccb3dedc9b.jpg)

**Comment by peterbell10** [comment]
Fixed by #4160
