### ISSUE TITLE
Flying Horses

### ISSUE THREAD

**Issue by jbrannan565** [cuberite/cuberite#3635]
Client version:   1.11.2
Server OS:        Linux
Commit id:        ef85c2e686f79234f5f472b2f498e5bc3e07ce24

### Expected behavior
Horses fall when jumping off of ledges.

### Actual behavior
Horse will fly for indeterminate length, then gradually fall.

### Steps to reproduce the behavior
Climb up any hill while riding a horse, then run off of the hill.

**Comment by sphinxc0re** [comment]
Hi @jbrannan565 and thanks for your report. Please edit your initial message to include the basic information we need to resolve this.

**Comment by yangm97** [comment]
Once this is fixed, I want to see a plugin that brings it back 😂

**Comment by mathiascode** [comment]
Closing in favor of #703
