### ISSUE TITLE
Fireworks lose duration when restarting server

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3639]
Client version:   1.11.2
Server OS:        macOS

### Expected behavior
Fireworks keep their duration

### Actual behavior
Fireworks lose their duration

### Steps to reproduce the behavior
Place some fireworks in a chest or dispenser and restart the server.
When you open the chest / dispenser, the fireworks have lost their duration and can't be used.

**Comment by madmaxoft** [comment]
Duration or Durability (aka Damage)?

**Comment by Seadragon91** [comment]
Tested it, The flight duration is lost on world save, but not in player inventory.
