### ISSUE TITLE
Pick block doesn't work in creative inventory 

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3650]
Client version:   1.11.2
Server OS:        macOS and Linux
Commit id:        /

### Expected behavior
Hovering over an item in an inventory and clicking the pick block button when in creative gives the maximum stack of that item.

### Actual behavior
You get a ghost stack that disappears after some time.

### Steps to reproduce the behavior
Hover over an item in an inventory and click the pick block button when in creative

**Comment by djlw78** [comment]
If you can still pick it up as ghost block all it is, is a render error.

**Comment by Pokechu22** [comment]
To be clear: Is this pick-block drag (creating multiple stacks) within another inventory (eg, a chest), or is it a single pick-block in the main creative inventory?  Different packets are used in different situations.

**Comment by Bond-009** [comment]
Pick-block drag for creating multiple stacks.

**Comment by Pokechu22** [comment]
Right, that type of drag is weird - it can also be fired [in singleplayer](https://bugs.mojang.com/browse/MC-46584) by the Notchian client, even though it's illegal there.  ([ref on drags](http://wiki.vg/Protocol#Click_Window)).

It looks like this is a case of cuberite just not implementing that type of drag (only the left and right varieties are implemented), which is better than it being supposedly implemented but not working.
