### ISSUE TITLE
MoveToWorld and ScheduleMoveToWorld status

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3651]
What should we do with MoveToWorld and ScheduleMoveToWorld? Both of them have their own issues:
MoveToWorld:
- Unstable, crashes may occur https://github.com/cuberite/cuberite/issues/3649
- Sends respawn packet

ScheduleMoveToWorld:
- No crashes
- Doesn't send respawn packets
- World dimensions don't change when changing worlds, resulting in weird looking chunks

Both:
- Player not always sent to world spawn: https://github.com/cuberite/cuberite/issues/3420

ScheduleMoveToWorld was supposed to be removed in https://github.com/cuberite/cuberite/pull/3401, but many months have passed. What is the status of that?

**Comment by Seadragon91** [comment]
Also `MoveToWorld` is asynchronous. Doing a teleport after calling it, is not guaranteed to work as expected.

**Comment by LogicParrot** [comment]
@mathiascode , I'll try to investigate these issues and perhaps revive #3401 when I finish the mob PR.
