### ISSUE TITLE
Trying to sign up in the forums gives a database error.

### ISSUE THREAD

**Issue by bluebird173** [cuberite/cuberite#3652]
Didn't know where else to post this.

**Comment by NiLSPACE** [comment]
I can confirm this! @cuberite/core-team It seems the thanks plugin is giving us trouble. I tried deactivating it, but the error persists.

**Comment by NiLSPACE** [comment]
I've created an announcement on the forum so people know we're aware of the issue.

**Comment by mathiascode** [comment]
@sphinxc0re https://community.mybb.com/thread-68262-post-492704.html#pid492704

I don't have access to the database.

**Comment by sphinxc0re** [comment]
Okay, I'll fix it

**Comment by sphinxc0re** [comment]
The column already has a default value

**Comment by sphinxc0re** [comment]
Fixed

**Comment by madmaxoft** [comment]
I just tried and can confirm registrations are working properly again.
