### ISSUE TITLE
Make ping packet compatible with server status tools

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3653]
### Expected behavior
Cuberite servers show up as online on all server list/server status websites.

### Actual behavior
Very few server lists think Cuberite is running, most report a Cuberite server as offline.

Current response from a Cuberite server:
```
{
   "description" : {
      "text" : "Cuberite - in C++!"
   },
   "favicon" : "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAQAAAAAYLlVAAAC5ElEQVR42u2ZT0hUURTGX8vsqWnZiEhESe1CIKKAiqBNBIgEiRAQRLQJIiPMMJwsSG0opCgGKAJatTRwVy6lNlVAQNAuUptpdMaZUZvsV0w6d948353bnKePwO/u5t433++ee895f66VV6c1ZrHGbeyP65IiFgG1yN/ZE2DrtITBly+ERbBtHUAIsI3q4AC2EiZJnDCbJQAS82UlGagcQmaulGKAOgGAwFwIITd3Q9T7DxAiQgZTJblpDiGYuVazppEQmsshhOZyCK8KN0QaL81wgxzFmuM+c5XtCc3MtTPKUqypPPQAGf115QHqGSRtNBMn4udC5CLaSPRTowfoMJ7BNMX6hOppJspPvHS8MoDHrgoXww2gWisf/QXIco+QY2Qb71jWOMccfXsZkUfArQx3aECN3UA7b3lT8pe7eMYiSAD0WX2bLcUQjqubeMQPACmAXilu4U6oEHdVakoBzOubqhwpAP8BXpEoUxUatJUjy2sZwGlqua6FmMVLaSI0ckYGcCr/q0033//xFjRMY/7aszKA9kJPDb0kMFGCPlTZOicDOOHorSXMDDrF6S2p9uflAM5WTbcHRIwwta7xF2QAbR6PKoPkSnb7FewVx3bJAE5iYeVTbYT9jpFTmpvRIUbpX9oHPTKADkIMFVJtlINlAY7wEvXcVEdYBjDuKq+tWoDDODXDB79L8T4twFFcWluAA6sNkKBFC9DIl9UD+EYPNWU3oU0faf8BpunFNk7DJp7yy1+AF+zGMgaw2MN7v5dgkee0GAHsIEqu0iWwuUoMLy3wkGYtwE6eaMwnuMTG8q9mm7jIpAYiSvOKANsZZl6zhbupMn85raaHOF6a50HJHfErURbw0iRdytwMQEVCIDXzyj9Q2CKImDLXAwgh9OYyALUnrhHHVJNcVuYiAHckBGsuBVAQAnMpgIIQmAsBVIpOSM0VgABCZi4/sLCpYv3M6D8HCPzgMvCj28APrwM/vv8Nz2dq4bWzQNoAAAAASUVORK5CYII=",
   "players" : {
      "max" : 100,
      "online" : 0
   },
   "version" : {
      "name" : "Cuberite 1.8.x, 1.9.x, 1.10.x, 1.11.x",
      "protocol" : 0
   }
}
```

Vanilla Server:
`{"description":{"text":"A Minecraft Server"},"players":{"max":20,"online":0},"version":{"name":"1.11.2","protocol":316}}`

Used command: `(echo -e '\x06\x00\x00\x00\x00\x00\x01\x01\x00'; sleep 1)|nc -c localhost 25565`

### Steps to reproduce the behavior
Enter "gallery.xoft.cz" here: https://dinnerbone.com/minecraft/tools/status/

**Comment by mathiascode** [comment]
http://minecraft-mp.com started working after removing whitespace from the json response, but many others are still failing.

**Comment by madmaxoft** [comment]
Weird thing is, it seems to work for me locally:
```
xoft@blackbox:~/mcstatus$ python stat.py
The server has 0 players and replied in 48.882 ms
The server replied in 49.743 ms
Traceback (most recent call last):
  File "stat.py", line 19, in <module>
    query = server.query()
  File "/usr/local/lib/python2.7/dist-packages/mcstatus/server.py", line 82, in query
    raise exception
socket.timeout: timed out
```
(The exception and timeout is for the UDP socket test)

**Comment by mathiascode** [comment]
This tool fails to ping a Cuberite server about 50% of the time: https://mcsrvstat.us/server/gallery.xoft.cz

**Comment by Pokechu22** [comment]
Perhaps they don't like the protocol version being "0", though I'm not sure what the better version would be.

**Comment by mathiascode** [comment]
I changed the protocol version to the latest one, 316, like Vanilla, but there's no difference. I'm starting to wonder if there's another issue, since the server checker I mentioned in my last post still receives info correctly about 50% of the time.
