### ISSUE TITLE
Disconnects require a cooperating client

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#3669]
Client version:   Custom Bot
Server OS:        Linux
Commit id:        e796291564fa6c44b3e2a8ab25368c3b77960438

### Expected behavior
If the client fails to respond to a disconnect packet the server forcibly terminates the connection.

### Actual behavior
If the client fails to respond to a disconnect packet the server carries on and allows the client to continue playing.

### Steps to reproduce the behavior
Use a client that ignores disconnects, or patch protoproxy to filter them.

**Comment by Seadragon91** [comment]
Already reported that #3159.
