### ISSUE TITLE
a few hundred wolves too many

### ISSUE THREAD

**Issue by nebulousdog** [cuberite/cuberite#3670]
Client version:   `1.11.2`
Server OS:         `Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64)`
Commit id:        `6c420ce5570ca4ac2aa5cabf80c3fa743d11ecf2`

### Expected behavior
"normal" amount of wolves

### Actual behavior
many hundreds of wolves

### Steps to reproduce the behavior
I noticed a "few" extra wolves around than usual, but when we logged in today, there were many many hundreds. We've starting killing them with lava, but there are still enough to be lagging the server.

<img width="1440" alt="doges" src="https://cloud.githubusercontent.com/assets/2218331/25030969/0a9585f8-207e-11e7-85e9-7a10503b8a12.png">

This picture is from the country side, but where there are holes where they can get trapped, its horrifying.

/cc @gavindinubilo

**Comment by djlw78** [comment]
Congratulations. We are on the same page finding bugs when just doing normal stuff.
