### ISSUE TITLE
Water doesn't flow correctly

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3672]
Client version:   1.11.2
Server OS:        macOS/BSD
Commit id:        (Found at the top of the server's console output)

### Expected behavior

![screen shot 2017-04-17 at 10 20 27](https://cloud.githubusercontent.com/assets/21289123/25083476/9a24b2a8-2357-11e7-9a07-87e0d5cb4ca9.png)

### Actual behavior

![screen shot 2017-04-17 at 10 15 52](https://cloud.githubusercontent.com/assets/21289123/25083484/a153a14c-2357-11e7-8bb7-90e6130cc5a8.png)

### Steps to reproduce the behavior

Place water in a field with tall grass and double tall grass

**Comment by madmaxoft** [comment]
I think that behavior is correct, isn't it? Hard to tell from the screenshot, but it looks alright to me, except for the apparent water levels.

**Comment by NiLSPACE** [comment]
Could you create another picture on a complete flat surface?

**Comment by Bond-009** [comment]
Yeah, I just noticed the ground isn't even. I will test it when I come home.
