### ISSUE TITLE
Double tall grass doesn't drop the correct item when broken by water

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3673]
Client version:   1.11.2
Server OS:         macOS
Commit id:         Unknown

### Expected behavior
It should drop seeds.

### Actual behavior
It drops double plants with meta 4-7. 6-7 are non-existing metas
![screen shot 2017-04-18 at 18 13 07](https://cloud.githubusercontent.com/assets/21289123/25141079/b2436440-2462-11e7-85c6-fb48d52c578a.png)

### Steps to reproduce the behavior
Break double tall grass with water.

**Comment by djlw78** [comment]
If I find time will write up a Lua script that will listen for these items, remove them and drop the correct block in place. I cannot do this if the block doesn't actually exist though.

**Comment by erherhh4herh** [comment]
@djlw78 Shouldn't you just fix the issue instead of creating plugins? This server will never be stable if we just keep creating plugins to "Patch" things. Just my opinion, though.
