### ISSUE TITLE
MCPE?

### ISSUE THREAD

**Issue by NycuRO** [cuberite/cuberite#3674]
Hi and sorry for issue.

Can you create and one server in c++ for MCPE? 👍

**Comment by NiLSPACE** [comment]
We've discussed that before but determined that it would take too long to add support for Pocket Edition: #3570

**Comment by NycuRO** [comment]
No no, not add support for MCPE to Cuberite.


Create new software "Cuberite-MCPE" ;) @NiLSPACE

**Comment by NycuRO** [comment]
Now, exist one software for MCPE in C#: https://github.com/NiclasOlofsson/MiNET
But there is for developers and for minigames.
Not work Vanilla on there and Niclas (Owner) not like to add Vanilla Gameplay Support. :(

Can you create one software in C++ for MCPE with Vanilla Gameplay Support? 👍 
(That's my question)

**Comment by NiLSPACE** [comment]
Re-creating Cuberite for Pocket edition is an even larger task. It would also make us have to maintain two separate code-bases which is pretty much impossible with the size of the current team.

**Comment by NycuRO** [comment]
@NiLSPACE Hmm, i have other method.

Create other branch with replacement of Metadata, RakNet and Protocol PC to PE.

Replace PC components with PE codes. :D  
Generation, blocks and entity's it's same 80%.

**Comment by NiLSPACE** [comment]
That's still two code bases we'd have to maintain.

**Comment by NycuRO** [comment]
If i'm please you? :)

**Comment by Tee7even** [comment]
@NycuRO Maybe you'll stop searching for someone to spoon-feed you? ;)

**Comment by NycuRO** [comment]
It's for MCPE :P @Tee7even

**Comment by Tee7even** [comment]
Yeah, you're still doing the same thing, @NycuRO - looking for somebody to do the work for you.

**Comment by NycuRO** [comment]
Not for me , for MCPE :D

**Comment by yangm97** [comment]
Unless the java edition is discontinued for good, I don’t see Cuberite supporting MCPE anytime soon. The differences between the protocols are large enough to make it impossible to support both by the same team/project/whatever. 

You could try doing something like ProtocolSupport is doing (a plugin for Spigot that is adding MCPE support to Spigot) in Cuberite by yourself by making a lua plugin, or fork the project itself. You know, this is an open source project, you can actually do some coding and open a pull request to have your changes upstreamed. 

Asking people who is already stuffed with things to do (take a look at the number of issues open already), to do a whole big new thing isn’t going to help you or the MCPE FYI. Your best bet is to do something yourself or ask a friend of yours to do the work.

**Comment by Tee7even** [comment]
>You know, this is an open source project, you can actually do some coding and open a pull request to have your changes upstreamed.

Lol, for some reason (laziness), he can't. So that's what he's doing - asking people to work on his forks, add PE/Vanilla support to server softwares, code new ones, etc.

P.S.
>If you don't like that, you can create "recrutation" of members. Like: @MarfGamer, @XenialDan, @SalmonDE, @dktapps, @NiclasOlofsson, @Creeperface01, @fromgate, @Tee7even, @Snake1999, @PeratX, @boybook and others.

![image](https://cloud.githubusercontent.com/assets/6763610/25187366/7453be7c-252b-11e7-9bac-9b0d0e240bdf.png)

**Comment by PeratX** [comment]
What's going on?

**Comment by Snake1999** [comment]
What's going on?

**Comment by NiLSPACE** [comment]
In a nutshell: @NycuRO wants us to rewrite our project to play Pocket Edition on. This would not only be a large time consuming task, but also mean we'd have to maintain two separate code-bases.
