### ISSUE TITLE
Memory leak in StringUtils::AppendVPrintf

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3678]
Server OS:        Linux

Combined plugin APIFuzzing with valgrind and got a few results.
This one with call to `StringUtils::AppendVPrintf` appeared the most time.
```
==7409== 31 bytes in 1 blocks are definitely lost in loss record 1 of 2
==7409==    at 0x4C2C1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==7409==    by 0x545DAE8: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate$
==7409==    by 0x545F072: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append$
==7409==    by 0x9973E2: AppendVPrintf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>$
==7409==    by 0x997874: Printf[abi:cxx11](char const*, ...) (StringUtils.cpp:133)
==7409==    by 0xA1328A: cLuaState::CheckParamString(int, int) (LuaState.cpp:1750)
==7409==    by 0xB30B96: tolua_cJson_Parse(lua_State*) (LuaJson.cpp:279)
==7409==    by 0xEF8633: luaD_precall (ldo.c:319)
==7409==    by 0xF0FD1D: luaV_execute (lvm.c:587)
==7409==    by 0xEF8DD2: luaD_call (ldo.c:377)
==7409==    by 0xEF2FBE: f_call (lapi.c:800)
==7409==    by 0xEF7D64: luaD_rawrunprotected (ldo.c:116)
```

Reproduce:
1) Add this code to a plugin: `cJson:Parse(nil)`
2) Start cuberite under valgrind and it should print the output above

**Comment by djlw78** [comment]
Who is the main developer anyway I see owners and no one says I'll fix that.

**Comment by djlw78** [comment]
So why can't you just fix it? Mr. "[Owner]"? Basically this just lost the buffer.

**Comment by worktycho** [comment]
@djlw78 If is so simple would you like to tell us how the internal buffer of a std::string instance got lost.

@Seadragon91 It definably inside a std::string and we do some nasty stuff with strings there, but my suspicion is that tolua is doing something with this string on the error path. Should be all RAII though.

**Comment by djlw78** [comment]
@worktycho Sorry. I just can see that it's a lua string buffer translation glitch. Here I'll keep quite for you.

**Comment by madmaxoft** [comment]
Lua is using `setjmp` / `longjmp` for implementing its error raising, perhaps that messes with C++'s RAII. I'll have a look at this.

**Comment by madmaxoft** [comment]
Yes, it's caused by Lua using `longjmp`, at least on Windows.

I'll try if we can switch Lua to use exceptions instead, and what side-effects it might have.

**Comment by Seadragon91** [comment]
I don't see any memory increase by spamming with the functions. We could also just ignore it.

**Comment by madmaxoft** [comment]
The memory increase is supposedly minimal - about a hundred bytes per error (size of the formatted string).  Yes, the report is about `std::string`'s buffer, because the object doesn't get destroyed, its destructor is not called due to the `longjmp` in `tolua_error()`.

**Comment by madmaxoft** [comment]
I'm not that much worried about this specific memory leak. I'm more worried about broken RAII in all situations where Lua could raise an error.

**Comment by madmaxoft** [comment]
I've managed to switch Lua to use C++ exceptions. Calling conventions and C++ ABI is a major headache.
