### ISSUE TITLE
pressure plate not working with fence gate

### ISSUE THREAD

**Issue by mkeedlinger** [cuberite/cuberite#3679]
Client version:   1.11.2
Server OS:        Ubuntu 16.04 LTS
Commit id:        7960d142ca3e28e0e4550faf131398899dca90dc

### Expected behavior
Adjacent pressure plate should trigger opening of the fence gate.

### Actual behavior
Fence gate has no reaction to pressure plate activation.

### Steps to reproduce the behavior
See here: https://i.imgur.com/TTgHxC6.gifv
(or [here](https://imgur.com/a/PEzlI) if that doesn't work)

**Comment by Etmix** [comment]
I was able to reproduce the issue.
Oakwood fence gates work, others don't.
The type of pressure plate doesn't seem to matter.

**Comment by mkeedlinger** [comment]
Thanks!
