### ISSUE TITLE
Custom Client Feature

### ISSUE THREAD

**Issue by djlw78** [cuberite/cuberite#3681]
Client version:   1.11.2
Server OS:        Windows
Commit id:        7960d142ca3e28e0e4550faf131398899dca90dc

### Suggestion/Request
A feature in the config to disallow client mods. 

_If you need help making the code ill give you some examples._

**Comment by madmaxoft** [comment]
This would ideally be a plugin.

How can you tell whether the client is modded, does it send any identification? Of the individual mods? Do we want a whitelist which mods we allow?

**Comment by djlw78** [comment]
Basically tell the client that forge (client) mods aren't allowed then kicks them.

**Comment by Seadragon91** [comment]
@djlw78 The question from @madmaxoft still remains. If the mod doesn't send any notification (e.g. per plugin channel), then it's impossible to know if the client is modded.

**Comment by Pokechu22** [comment]
Forge has [a login handshake](http://wiki.vg/Minecraft_Forge_Handshake) (and a somewhat complex one, actually - that documentation necessarily entirely up to date).  But it's intended to negotiate mods - kicking users is, and I will say this in all situations, **bad user experience design** and shouldn't be done.

**Comment by djlw78** [comment]
Ya .-.

**Comment by Seadragon91** [comment]
With BungeeCord and this [plugin](https://forums.spongepowered.org/t/spongepls-bungeecord-forge-support/9891) you can detect if a player tries to connect with a forge client.

Not sure if a forge client sends info about the plugin channel if it's connected. Then a plugin could be written to detect this and kick the client.

**Comment by djlw78** [comment]
@Seadragon91 ok
