### ISSUE TITLE
APIDoc: Hook function name

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3698]
Currently every hook where a function is registered begins with `My`. I find that confusion, can I remove it?
Example:
```
cPluginManager:AddHook(cPluginManager.HOOK_SPAWNED_ENTITY, MyOnSpawnedEntity);
```

**Comment by madmaxoft** [comment]
Why is that confusing? I remember seeing this (`MyFunctionSomething`) in a multitude of documentation.

It might be better to include some basic function definition before the AddHook call. Something along the lines of:
```lua
function MyOnSpawnedEntity(World, Entity)
  -- Insert code here
end

...

cPluginManager:AddHook(cPluginManager.HOOK_SPAWNED_ENTITY, MyOnSpawnedEntity)
```

**Comment by Seadragon91** [comment]
This already exists and they have no `My` at start. We could add the missing `My` to them.
