### ISSUE TITLE
Spawn eggs don't work in 1.11

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3723]
Client version:   1.11.2
Server OS:        Linux
Commit id:        758622336e6c8d7aa2d4b34d8eedc4aaed54a4f6

### Expected behavior
Spawn eggs can be used in Minecraft 1.11.

### Actual behavior
Spawn eggs turn blank as soon as you put them in your inventory.

### Steps to reproduce the behavior
This is caused by a change of entity names in Minecraft 1.11. In src/Protocol/Protocol_1_9.cpp, this piece of code takes care of spawn eggs in 1.9 and above:
```
	if (a_Item.m_ItemType == E_ITEM_SPAWN_EGG)
	{
		// Convert entity ID to the name.
		eMonsterType MonsterType = cItemSpawnEggHandler::ItemDamageToMonsterType(a_Item.m_ItemDamage);
		if (MonsterType != eMonsterType::mtInvalidType)
		{
			Writer.BeginCompound("EntityTag");
			Writer.AddString("id", cMonster::MobTypeToVanillaName(MonsterType));
			Writer.EndCompound();
		}
}
```
Since MobTypeToVanillaName sends the wrong entity names in 1.11, the eggs don't work. What would be the best way to fix this issue?

**Comment by Seadragon91** [comment]
Working on fixing this.

**Comment by Pokechu22** [comment]
The spawn-egg conversion code (and the similar potion conversion code) is fairly hacky, and was created with the intent that _eventually_ cuberite would migrate to a more dedicated spawn-egg item metadata, rather than storing the numeric type and then converting it there.  I'd recommend fixing it that way (it would also allow support for other properties of spawn eggs, such as fully customizing the entity through `EntityTag`).

**Comment by Seadragon91** [comment]
With an NBT edtor, I only see the `id` in `EntityTag`.

**Comment by Seadragon91** [comment]
Okay sorry, now I see what you mean.

**Comment by Seadragon91** [comment]
Yes that's a problem. There was a discussion in forum to use Json to store NBT data, because for the API side. This would be also required for this part.

I think for now I will get the spawn eggs working, with conversion to mob type and back. The changes are trivial.

**Comment by Pokechu22** [comment]
You're allowed to put as much NBT as you want in there (though, I recall `Position` not being allowed).  For instance, `/give @p minecraft:spawn_egg 1 0 {EntityTag:{id:"minecraft:pig",Health:1}}` (previously, `/give @p minecraft:spawn_egg 1 0 {EntityTag:{id:"Pig",Health:1}}`) summons a pig with only 1 health.

**Comment by Seadragon91** [comment]
Here the link: https://forum.cuberite.org/thread-2626.html.
