### ISSUE TITLE
Compiling x64 version

### ISSUE THREAD

**Issue by erherhh4herh** [cuberite/cuberite#3728]
Client version:   Unknown
Server OS:        Windows 10 x64
Commit id:        b02886a9010950e1bb320598568b7f5adafdd3ca

### Expected behavior
x64 compile option

### Actual behavior
http://i.imgur.com/QeZhBGR.png

### Steps to reproduce the behavior
type "cmake ."
open .sln

I can't create a profile with x64 architecture because it throws errors. Any help is greatly appreciated.

**Comment by madmaxoft** [comment]
This is a `cmake` limitation. You need to specify to cmake on commandline that you want the Win64 build:
`cmake -G "Visual Studio 15 2017 Win64" .`
Note that you need to invoke this in a clean source folder; if you invoked cmake in a folder already, you'll need to remove the CMakeCache.txt file and CMakeFiles folder.
