### ISSUE TITLE
Experience orbs cannot be collected

### ISSUE THREAD

**Issue by spekdrum** [cuberite/cuberite#3740]
Client version:   1.11.2
Server OS:        Windows
Commit id:        bc6e2100c1cb5c695856e2a86afd202dec715967

### Expected behavior
Experience orbs should be able to be collected. This was working on recent versions.

### Actual behavior
They fly arround the player with no effect.

### Steps to reproduce the behavior
Kill any monster in survival mode and go to get the experience orb.

**Comment by spekdrum** [comment]
If you revert commit 2c3c1f15273835923d9bd4950a19ee88a95ee0f4 it works again.

**Comment by mathiascode** [comment]
This is already fixed in master.

**Comment by spekdrum** [comment]
Did you tried bc6e2100c1cb5c695856e2a86afd202dec715967? it's current master and doesn't work :/

**Comment by mathiascode** [comment]
You're right, it doesn't always work. Sometimes the player can collect a few XP orbs, but other times the orbs just fly around the player.

**Comment by liquid600pgm** [comment]
When enough orbs fly around the player, the player then gets the XP.

**Comment by spekdrum** [comment]
As I said, if you revert commit 2c3c1f1 it works again. So it seems the problem is related with the new tracer logic.

**Comment by spekdrum** [comment]
Changing FindClosestPlayer 'a_CheckLineOfSight' parameter (as shown below) it works. The problem is with cLineBlockTracer::LineOfSightTrace function, called if a_CheckLineOfSight is true. This is not really a definitive solution, but it works :P
``` 
void cExpOrb::Tick(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)
{
	cPlayer * a_ClosestPlayer(m_World->FindClosestPlayer(Vector3f(GetPosition()), 5, **false**));
	if ((a_ClosestPlayer != nullptr) && (!a_ClosestPlayer->IsGameModeSpectator()))
	{
```

**Comment by spekdrum** [comment]
Also this cExpOrb::Tick should be limited in order to avoid this calculations 20 times a second. There is no need to do this so frequently.
