### ISSUE TITLE
Stupid zombie AI

### ISSUE THREAD

**Issue by liquid600pgm** [cuberite/cuberite#3742]
Client version:   1.11.2
Server OS:        Raspbian Jessie Lite
Commit id:        `a0341d561a177bcd1ed45229129065556c261049`

### Expected behavior

Zombies normally running around, MOVING towards the player with their AI working.

### Actual behavior

Zombies stay in place, they just ignore the player, but if one walks into them the player gets attacked.

### Steps to reproduce the behavior

Spawn a zombie and switch to survival mode.

**Comment by NiLSPACE** [comment]
Mobs were recently broken but were fixed again in #3720. Once a new build is released they should move again. Keep in mind that the AI in Cuberite isn't really that great though.

**Comment by mathiascode** [comment]
It's fixed in new builds. Please download the latest version.

**Comment by liquid600pgm** [comment]
I have already built from source and it is fixed. Thanks.
