### ISSUE TITLE
light bug

### ISSUE THREAD

**Issue by SebastienDeaure** [cuberite/cuberite#3746]
Client version:   1.11.2/1.9
Server OS:        Linux

When I start the server the blocks are dark even if it's the day, and when I place a block the light comes back around it.
It's maybe because of the walls (they go to the 26 th layer).
a screen :
https://image.noelshack.com/fichiers/2017/22/1496580946-2017-06-04-14-42-54.png

I hope I have been clear, and someone can help me.

**Comment by madmaxoft** [comment]
Could you provide the world and the coords of this place? Are there any (see-through) blocks at the top? How did you create the world, manually in the client, or using worldedit? Is the world originally made by cuberite, or was it imported from another software?

**Comment by SebastienDeaure** [comment]
I generate a flat world with cuberite, I made the walls with world edit, and I have done a roof with barrier blocs.

**Comment by madmaxoft** [comment]
The barrier blocks are the most likely cause of this, the Cuberite lighting algorithm doesn't know about them yet.

**Comment by SebastienDeaure** [comment]
ok thanks but is it the samle with glass blocs ?

**Comment by madmaxoft** [comment]
Unfortunately yes, any block other than air will cause this bug.

The lighting algorithm, once it finds a non-air block, starts the regular 1-shade-per-block gradient.

**Comment by SebastienDeaure** [comment]
Ok, I will find another way to do that.

**Comment by madmaxoft** [comment]
Oh, don't close the issue, it is a valid bug that needs fixing.
