### ISSUE TITLE
Unsupported Protocol 335

### ISSUE THREAD

**Issue by JohnHenry91** [cuberite/cuberite#3750]
Client version:   1.12
Server OS:        Linux

When I will connect my own server after the latest update the client showes me that he cant connect to my server because the protocol 335 is unsupported and I should use one of these versions: 1.8,1.9.,1.10, 1.11

**Comment by Seadragon91** [comment]
Well the reason is because the mc version 1.12 version was released today and cuberite has no support for it. Please use a older version in the meantime.
