### ISSUE TITLE
Microsoft will unify most 'Minecraft' platforms this summer

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3762]
https://www.engadget.com/2017/06/11/minecraft-better-together-bedrock-engine-ps4-xbox-360/

> "Our goal is to unite all Minecraft players," Merriam.

Microsoft may be going to (finally) unify the minecraft protocol. If they do so, I propose that this issue is used to discuss what this means for cuberite, and threat other issues about this topic as duplicates.

**Comment by yangm97** [comment]
It’s not clear (to me) if the java version is going to be included on the first wave but it’s known that

> The PlayStation 4 and Xbox 360 versions of Minecraft are not included in the initial Better Together update.

**Comment by Pokechu22** [comment]
> The Better Together update puts almost every version **on the Bedrock Engine**. Almost.

The Bedrock engine is MCPE/Windows 10; it doesn't include the java version.

**Comment by yangm97** [comment]
By the looks either Java, X360 and PS4 will speak the unified protocol on future waves or they are simply going to drop support for them sooner or later. They did show up interest keeping java feature parity though.

But… it’s Microsoft, so they could end up doing something else entirely. Time will tell I guess.

**Comment by mathiascode** [comment]
If I understood correctly, the unified Bedrock engine will just become "Minecraft" instead of PE/Win10/whatever edition, and PC Minecraft will become Minecraft Java Edition.

**Comment by lukeeey** [comment]
Bump

**Comment by mathiascode** [comment]
Closing in favor of #4191
