### ISSUE TITLE
CI: use cross compilation to make better use of the build main server

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3768]
I may be late to the party but I just found a docker image that allows all sorts of cross build: https://github.com/multiarch/crossbuild

That means one could possibly build Cuberite for multiple targets from a linux server, without virtualizing OSes. 

The supported targets list include most, if not all cuberite build targets

## Supported targets

Triple                 | Aliases                             | linux | osx | windows
-----------------------|-------------------------------------|-------|-----|--------
x86_64-linux-gnu       | **(default)**, linux, amd64, x86_64 |   X   |     |
arm-linux-gnueabi      | arm, armv5                          |   X   |     |
arm-linux-gnueabihf    | armhf, armv7, armv7l                |   X   |     |
aarch64-linux-gnu      | arm64, aarch64                      |   X   |     |
mipsel-linux-gnu       | mips, mipsel                        |   X   |     |
powerpc64le-linux-gnu  | powerpc, powerpc64, powerpc64le     |   X   |     |
x86_64-apple-darwin    | osx, osx64, darwin, darwin64        |       |  X  |
x86_64h-apple-darwin   | osx64h, darwin64h, x86_64h          |       |  X  |
i386-apple-darwin      | osx32, darwin32                     |       |  X  |
x86_64-w64-mingw32     | windows, win64                      |       |     |   X
i686-w64-mingw32       | win32                               |       |     |   X

@bearbin what do you think?

**Comment by bearbin** [comment]
This already happens. The RasPi builds and other ARM builds are cross-compiled currently.

**Comment by yangm97** [comment]
What about the windows and macOS builds?

**Comment by bearbin** [comment]
I believe the table indicates that you may only build for windows or mac on a windows or mac host. Since the build server already has windows and mac hosts, there would be no point in getting new ones to use with docker.

**Comment by yangm97** [comment]
Hm, nope. Actually macOS doesn’t even run docker natively, it runs under a linux VM. So I believe it does cross OS compilation.

**Comment by yangm97** [comment]
Just checked that: helloworld.c compiles on linux with macOS as target and runs just fine. Should be the same with windows too.

**Comment by bearbin** [comment]
That's better than I thought - this could actually be rather useful.

There's no immediate need to change over the builds, but when I have time I might set up cross-compiled builds so there is no dependency on donated build servers. The build system is already mostly migrated to docker anyway so it shouldn't be too difficult.

**Comment by bearbin** [comment]
I'm going to close this issue now, as being open in this repository is just causing clutter, but thank you for bringing this to my attention.
