### ISSUE TITLE
Double tall grass and large fern top parts drop sunflower

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3778]
Client version:   1.8.9 and 1.12
Server OS:        macOS
Commit id:        0f21bda12cdb06fb2bcf35ec345fc1dab5e07c9a

### Expected behavior
When broken normally, all variants will drop 0 or 1 seeds.
http://minecraft.gamepedia.com/Grass

### Actual behavior
It drops a sunflower.

### Steps to reproduce the behavior
Break the top part of double tall grass or large fern.

**Comment by Seadragon91** [comment]
Could you please check if you have the latest master and test it again?

**Comment by Bond-009** [comment]
I don't know what happend but it doesn't drop a sunflower anymore, it drops nothing which is technically still an issue.

**Comment by Seadragon91** [comment]
Ah sorry I didn't see that fern can drop seeds, then yes that should be corrected.

**Comment by Bond-009** [comment]
I noticed that I was in creative, so I download the latest binary from the site instead of building myself and tested again (this time in survival) and it still drops sunflowers when you break the top block of double tall grass or large ferns.
And I tested in vanilla if large ferns drop seeds and they don't.

**Comment by Bond-009** [comment]
Am I the only one that has the problem that double tall grass and large ferns drop when you break the top parts?
https://youtu.be/yNcZfP9oniY

**Comment by peterbell10** [comment]
I'm getting the same issue.  But I've noticed if you place the "Double Tallgrass" item, it doesn't drop sunflowers any more.  So to repro you need either natural generated double tall grass or you need to get it from bonemealing normal tall grass.

**Comment by madmaxoft** [comment]
It would be interesting to see how a Vanilla-generated world behaves in Cuberite in this respect, too. Both Vanilla-generated and Vanilla-bonemealed.

**Comment by peterbell10** [comment]
Just tried both and they didn't drop sunflowers so I guess this really a world gen/bonemeal issue.

**Comment by Bond-009** [comment]
Euh, I tried to and they drop seeds for me :)

**Comment by Bond-009** [comment]
I can confirm, they dropped seeds for me.
