### ISSUE TITLE
Beds are invisible after re-login

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3787]
Client version:   1.12
Server OS:        macOS
Commit id:        bb020bbe78434a221f6d404d7f83e5bd804ed541

### Expected behavior
Beds should be visble after re-login.

### Actual behavior
Beds are invisible after re-login.

### Steps to reproduce the behavior
Place a bed, re-login -> the bed is invisible.

**Comment by Seadragon91** [comment]
Bed have changed in 1.12 and have now colors. Maybe a problem with meta data.

**Comment by Bond-009** [comment]
When you click on them they are visible again.

**Comment by madmaxoft** [comment]
In 1.12 beds have an accompanying BlockEntity, perhaps that's the reason.

**Comment by Seadragon91** [comment]
I guess change it to a block entity?
* New block entity cBedEntity
* Export to lua
* Functions Get-/SetColor
