### ISSUE TITLE
LavaSimulator=Vaporise in the Nether stops the server

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3788]
Client version:   1.12
Server OS:         macOS
Commit id:         bb020bbe78434a221f6d404d7f83e5bd804ed541

### Expected behavior
If you set LavaSimulator to Vaporise in the Nether it should vaporise all lava.

### Actual behavior
The client becomes unresponsive and the server stops after a little while.

### Steps to reproduce the behavior
Set LavaSimulator to Vaporise in the world.ini of your Nether world.
![screen shot 2017-06-19 at 22 05 40](https://user-images.githubusercontent.com/21289123/27305306-6fd9740e-5541-11e7-8f1f-c67a8cf2eb28.png)

**Comment by madmaxoft** [comment]
Does it stop gracefully, or with an error?
I'd expect a (false positive) deadlock - the Vaporise simulator would try to remove all the lava in the Nether at once and it's just too much work, so it would seem to DeadlockDetect like the server deadlocked.

**Comment by Bond-009** [comment]
It stops without an error or the usual stop output

**Comment by Bond-009** [comment]
I tried again and it didn't stop or deadlock.

**Comment by madmaxoft** [comment]
I assume you've tried again on the same world - it already had most of the lava vaporised, so it didn't take so long anymore. If you delete the `world_nether/region` files, so that the world re-generates, it should make the server unresponsive again.

**Comment by Bond-009** [comment]
No, I tested it on a completely new world. (Even a new binary)

**Comment by madmaxoft** [comment]
Then perhaps you hit a world seed that had very little lava at the spawn region?
Because there has been no change in the simulator at all, makes no sense for this issue to suddenly disappear.

**Comment by Bond-009** [comment]
The only thing that I didn't do this time was force-close the client. And maybe someone else should try this and see if they can reproduce this.
