### ISSUE TITLE
Optimize cBlockArea writing

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#3793]
Currently when writing `cBlockArea`'s contents into a chunk, each changed block is broadcast to all clients as a separate packet directly when it's changed.

Instead, we should postpone the sending and then broadcast all the changes in a single multi-block-change packet.

Note that this somewhat collides with `cBlockEntity` writing, the block entities need to be broadcast to all clients after all the blocks changes have been broadcast.

**Comment by peterbell10** [comment]
If I'm reading it right: `cBlockArea`'s contents are written in `cChunk::WriteBlockArea` using `FastSetBlock` which defers broadcasting until the next tick with `m_PendingBlockChanges`.  Also `WriteBlockArea` is called while the chunk map holds `m_CSChunks` locked and the same lock is held when ticking the chunk.

So unless I'm missing something the block changes should be sent as a single multi-block change packet per chunk as is, right?

**Comment by worktycho** [comment]
Yes, the change is only sent as one packet. This doesn't mean there aren't some serious inefficiencies in how the copy is done like recalculating block offsets, checking bounds and contentiously reevaluating the heightmap, but sending multiple packets is not the problem.

**Comment by madmaxoft** [comment]
Right, I've read that code wrong, so this is not an issue.
