### ISSUE TITLE
cBlockInfo mutability

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#3797]
`cBlockInfo::Get` currently returns a mutable reference to a `cBlockInfo` object.  

I'm wondering if the ability to modify these is intended as I can see some potential problems.  For example: changing `m_LightValue` could invalidate lighting, changing `m_IsSolid` could invalidate mob pathing etc.

Is the ability for plugins to change these intentional? If so, should lighting and pathing be recalculated?

**Comment by Seadragon91** [comment]
I think they should be only readable. Don't see any use why it should be possible to change them.

**Comment by madmaxoft** [comment]
I'm for read-only-izing them, too.

**Comment by madmaxoft** [comment]
I suppose the original intent was to allow plugins to support custom blocks, but that would need so much more that this is currently not feasible.
