### ISSUE TITLE
Add support for new entity names

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3799]
Forum-post: https://forum.cuberite.org/thread-2980-post-28333.html#pid28333

Cuberite only reads entities that don't have the prefix `minecraft:`.
I want to add the support for them. Idea of method format:
`bool CheckEntityType(const char * a_IDTag, size_t a_IDTagLength, const AString & a_Type1, const AString & a_Type2 = "");`

`a_Type1` and `a_Type2` are the entity types to check, e.g. `boat` or `minecraft:boat`. The second one is optional. Is this okay so?

**Comment by madmaxoft** [comment]
I'd prefer if you used the same approach as in #3784 - the `CheckEntityType` receives a `const AStringVector &` parameter specifying all accepted type names.
