### ISSUE TITLE
Top of rose bush and peony are not visible on client

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#3825]
Client version:   confirmed with 1.9.0 and 1.11.2
Server OS:        Windows
Commit id:        3352706

### Expected behavior
Both blocks are visible even after relog.

### Actual behavior
The bottom block is visible but the top is not.  If you place a block where the top should be it is there on the client but disappears on relog.
Note this happens for rose bushes and peony but none of the other big flowers.
![2017-06-30_14 31 42](https://user-images.githubusercontent.com/13238737/27737683-fc21f1d6-5da0-11e7-8335-e5dc64856af6.png)

### Steps to reproduce the behavior
Place a rose bush or peony and relog.

**Comment by Seadragon91** [comment]
I think I found the problem. The upper meta part of the big flower should be only a 8. In [ItemBigFlower.h#L46](https://github.com/cuberite/cuberite/blob/a944ac3b067464db026890e27d0c8dced6c8545e/src/Items/ItemBigFlower.h#L46) 8 this is passed as meta value:
`a_EquippedItem.m_ItemDamage & 0x07) | 0x08`
Passing the correct `0x08` fixes that problem, can you confirm that, too?

**Comment by peterbell10** [comment]
I tried this and it worked though some questions from #3778 might need to be reconsidered if that is the fix.

**Comment by Seadragon91** [comment]
Okay can confirm that the upper meta in vanilla is indeed 10. Why 10 and not 8, what are they adding?

**Comment by Seadragon91** [comment]
Can the fix for the placed top meta be included in your pull request?

**Comment by peterbell10** [comment]
I tried adding this but it doesn't work with the interface for `DoesIgnoreBuildCollision`.  You need access to the block below but it doesn't give you a block position.

**Comment by Seadragon91** [comment]
Why do you need to access the block below?

**Comment by peterbell10** [comment]
The grassy flowers ignore collision but not the others and if all the top blocks have meta value 10 then you need the meta value from the block below.

I was thinking of changing the function to something like:
```virtual bool DoesIgnoreBuildCollision(cChunkInterface & a_ChunkInterface, Vector3i a_Pos, cPlayer & a_Player, NIBBLETYPE a_Meta);```

**Comment by madmaxoft** [comment]
Performance-wise, is it better to pass in a `Vector3i`, a `const Vector3i &` or three `int`s? And how tight a loop does it have to be to be noticeable?
