### ISSUE TITLE
Mobs don't move through opened fence gates

### ISSUE THREAD

**Issue by spekdrum** [cuberite/cuberite#3830]
### Expected behavior
Mobs should move through opened fence gates

### Actual behavior
Mobs do no cross them as if they were solid blocks.

### Steps to reproduce the behavior
Go creative, build a little fence perimeter with a fence gate. Put a cow inside. Open the fence gate. Try to attract the cow with a wheat at the other side of the fence gate.

**Comment by Bond-009** [comment]
Same issue as #2062 and #2793

**Comment by spekdrum** [comment]
Oops!
