### ISSUE TITLE
You see too deep into water

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3849]
Client version:   1.12
Server OS:        macOS
Commit id:        approx: 6a1984112146a14c96f43e9cdf758f5104d6d2a3

### Expected behavior
This is a screenshot is taken in Vanilla:
![screen shot 2017-07-13 at 15 34 27](https://user-images.githubusercontent.com/21289123/28169377-6dbddd82-67e2-11e7-8db2-5b5baf6c959e.png)

### Actual behavior
This is a screenshot is taken in Cuberite:
![screen shot 2017-07-13 at 15 35 55](https://user-images.githubusercontent.com/21289123/28169411-89e6677c-67e2-11e7-9078-98f54cccdf89.png)

### Steps to reproduce the behavior
Look into water

## Note
It looks the same as in Vanilla with night vision:
![screen shot 2017-07-13 at 15 34 42](https://user-images.githubusercontent.com/21289123/28169481-b933d424-67e2-11e7-944d-7ddff6624578.png)

**Comment by madmaxoft** [comment]
This is most likely caused by my changes in the lighting - they cause the water to be considered daylight-transparent for lighting purposes and so give a full daylight all the way down to the ocean floor.

**Comment by Pokechu22** [comment]
Agreed, this is almost definitely lighting.  The cuberite verison looks like vanilla with night vision.
