### ISSUE TITLE
Some blocks of multi-block structures stay after explosions

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3863]
Client version:   1.12
Server OS:        Linux
Commit id:        approx: 53d5afb83ca5425ad60a9867ec3b0cca0e794ac8

### Expected behavior
The top part destroys together with the lower part.

### Actual behavior
![2017-07-21_12 23 46](https://user-images.githubusercontent.com/21289123/28459936-e64d58ee-6e0f-11e7-953c-17cecbc1fa02.png)
![2017-07-21_13 01 06](https://user-images.githubusercontent.com/21289123/28461774-93cc3d20-6e18-11e7-9c64-5d956f6729c4.png)
![2017-07-21_13 23 47](https://user-images.githubusercontent.com/21289123/28461778-98bbcc38-6e18-11e7-9a2c-efd45574c962.png)

### Steps to reproduce the behavior
Try to explode only the lower part of the block.

If you replicate this there is a 1/4 chance that the tnt will move in the right direction and only explode the lower part.
![2017-07-21_13 04 53](https://user-images.githubusercontent.com/21289123/28461782-9c2e587c-6e18-11e7-842d-82658694fc39.png)

**Comment by madmaxoft** [comment]
I wonder if a similar thing is possible in vanilla. Difficult to test, though.
I suppose a similar thing would happen with other multi-block structures, such as doors.

**Comment by Bond-009** [comment]
I tested some more and it works with beds, doors, snow and ferns (which should be the same as grass)

**Comment by Seadragon91** [comment]
I think for bed the problem is that the cBlockArea doesn't remove block entities.

**Comment by tigerw** [comment]
#4418 probably related too.

**Comment by tigerw** [comment]
Explosions use Block Areas, and Block Areas use FastSetBlock, so unsurprising that nothing updates.
