### ISSUE TITLE
[ASK]Do a Gui in lua (exemple dead list or Select GUI)

### ISSUE THREAD

**Issue by davedevils** [cuberite/cuberite#3867]
Hello,

I have try to do a list from gui for change world ...

But i no see api about gui and for me it's very important to have custom gui (for death match for exemple), so if people can say if gui is begin or need work , or what packet i need to do i will be happy to try it to add in core.

So anyone can be explain if custom gui is begin or not ?

For me it's the most important part for do server now in 2017 :/

Thanks

**Comment by NiLSPACE** [comment]
You can use the cLuaWindow for this: https://api.cuberite.org/cLuaWindow.html

**Comment by davedevils** [comment]
I will try it see if work good

**Comment by 109C** [comment]
There doesn't seem to be a way to stop players from taking the items from the window.

**Comment by davedevils** [comment]
yes i have see player can grab item , i look if i can do for block this

**Comment by williamhatcher** [comment]
I think you can register a hook that emits when an item is added to a player's inventory. Check to see if they have your GUI open, and when an item from your GUI gets added to their inventory, remove it (or decrement it by one) and put it back in your GUI.

**Comment by davedevils** [comment]
i not see how do correctly , because if they have allready same item like apple , you delete legit apple too

**Comment by Seadragon91** [comment]
I will look to open a  pull request for that. Have a branch that implements new hooks where it's possible to deny the click action in every window.

**Comment by lkolbly** [comment]
@Seadragon91 It would appear that I, ignorant of your work, had a similar branch going on. I just opened PR #3901 in case you want to take a peek and see how much I duplicated your work :P

My PR implements it as a callback on the cLuaWindow object, instead of a hook.

Anyway, I thought I'd mention that in case you want to steal any ideas from it.
