### ISSUE TITLE
HOOK_LOGIN causes client to hang and timeout, instead of getting kicked

### ISSUE THREAD

**Issue by satoshinm** [cuberite/cuberite#3868]
Client version:   1.12
Server OS:        macOS
Commit id:        6e8ec2fe340f8fc63f9394a4701aeace6e7e2701

### Expected behavior

From https://api.cuberite.org/OnLogin.html: "If the function returns true, no other plugins are called for this event and the client is kicked."

### Actual behavior

Instead of getting kicked, the client hangs on "Logging in..." for some time, then fails with "Timed out". 

<img width="966" alt="screen shot 2017-07-22 at 4 23 59 pm" src="https://user-images.githubusercontent.com/26856618/28495171-2edabe68-6efa-11e7-95e0-85cba6a6bdb7.png">

### Steps to reproduce the behavior

Tested with this plugin:

```lua
function Initialize(Plugin)
    cPluginManager.AddHook(cPluginManager.HOOK_LOGIN, OnLogin)
    return true
end

function OnLogin(Client, ProtocolVersion, UserName)
    LOG("Received HOOK_LOGIN")
    -- Client:Kick("Kicking client")
    return true
end 
```

Returning true from HOOK_LOGIN denies the login, this part works, but there seems to be a missing kick packet or something along those lines, because the client just hangs instead of being properly kicked.

If I comment out the Client::Kick call (wherein I tried to specify a custom kick message, is this possible? **edit**: kicking in HOOK_PLAYER_JOIN works as expected), the server does log that it sent the kick message:

```
Log: [827c124d61017f6c|16:27:10] Client "::ffff:127.0.0.1" connected!
Log: [827c124d61017f6c|16:27:10] New ClientHandle created at 0x10de11388
Log: [29da2fe1e6426e34|16:27:10] Received HOOK_LOGIN
Log: [29da2fe1e6426e34|16:27:10] Sending a DC: "Kicking client"
```

but it doesn't appear on the client. After the client times out, there is an assertion failure in the cClientHandle destructor:

Error: [827c124d61017f6c|16:27:40] Assertion failed: m_State == csDestroyed, file cuberite/src/ClientHandle.cpp, line 115
Assertion failed: (0), function ~cClientHandle, file cuberite/src/ClientHandle.cpp,

**Comment by bearbin** [comment]
The cause of this issue is [here](https://github.com/cuberite/cuberite/blob/master/src/ClientHandle.cpp#L706), I believe.

`Destroy()` is called, which waits for `m_CSState` to be unlocked, but it is not unlocked until after `Destroy()` runs.
