### ISSUE TITLE
Represent UUIDs numerically with a dedicated class 

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#3870]
Somewhat related to  #2264.  Maybe @worktycho has even tried this before.

Currently UUIDs are stored and passed around as strings which I think has a few issues:
 * There is little to no validation of the UUIDs.
 * Mixed usage of short and dashed UUIDs means something like `DoWithPlayerByUUID` might fail even if the UUID is correct.
 * Slight waste of memory.  With SSO strings, `sizeof(AString)` is likely more than the 16 bytes needed to store a UUID and that's before the actual string is allocated.

Having a strongly typed UUID class which parses and stores the UUID in numeric form could solve all of these issues.  The current lua API could even be kept by manually binding the lua side too and from strings.

**Comment by worktycho** [comment]
I failed to do so in the end due to getting burned out on the project last year. I totally agree this should be done, and maybe now I could try again.

**Comment by peterbell10** [comment]
I've actually done a fair bit of work on this already.   I just can't get anything to compile yet because the bindings are all broken...

**Comment by madmaxoft** [comment]
As long as the Lua API is kept compatible with the old code, I'm for this change.

**Comment by peterbell10** [comment]
I've got some working lua bindings but passing an invalid UUID is now an error.  So it's not 100% compatible but any code that was passing around invalid UUIDs was probably incorrect to begin with. 
Would that be OK?

**Comment by madmaxoft** [comment]
That's perfect. Just make sure that the error is understandable.

I assume you added a cLuaState::GetStackValue(cUUID *) overload that accepts both a cUUID object and a string on the stack.
