### ISSUE TITLE
Info.lua documentation lacks information about command categories

### ISSUE THREAD

**Issue by williamhatcher** [cuberite/cuberite#3887]
The [documentation](https://api.cuberite.org/InfoFile.html) on Info.lua does not mention command categories at all. This can leave people wondering why InfoDump creates a "General" subheading in the commands section.

**Comment by NiLSPACE** [comment]
Good catch. An example of this can be found in WorldEdit: https://github.com/cuberite/WorldEdit/blob/master/Info.lua

**Comment by williamhatcher** [comment]
Thanks. Can I make a few edits to the docs and submit a pull request?

**Comment by NiLSPACE** [comment]
Of course :)

**Comment by williamhatcher** [comment]
I can't seem to find the source code for the documentation! Am I looking in the wrong place?

**Comment by williamhatcher** [comment]
#3895 should be a solution for this issue.

**Comment by williamhatcher** [comment]
#3895 is a step in the right direction to closing this issue.

**Comment by williamhatcher** [comment]
PR #3895 should close this issue, right?
