### ISSUE TITLE
Can't connect to running server

### ISSUE THREAD

**Issue by alienbrett** [cuberite/cuberite#3891]
Client version:   1.12
Server OS:        Arch linux
Commit id:        2ef8a62339c80d7859042a056fefbb91c857f643

### Expected behavior
Cuberite server starts and LAN and localhost clients connect to server and webadmin portal

### Actual behavior
Starts up and displays no serious errors, except SSL certificate and the like. However, clients can't connect from localhost or on the LAN network. Also, even with the webadmin enabled, localhost and outside clients still can't access the webpage.

Refreshing the server list on a LAN client while the server is running hangs and doesn't display "can't connect to server". Also, the webadmin requests from the LAN hang also- they can't connect but aren't immediately rejected.

### Steps to reproduce the behavior
I'm not sure how this bug happened, because on a different Arch linux machine using commit 2ef8a62339c80d7859042a056fefbb91c857f643 works fine and permits connections

**Comment by williamhatcher** [comment]
Have you checked firewall rules? I don't know enough about linux firewall rules, but could one prevent localhost connections from going through?
Can you try compiling cuberite on the desired machine itself?

**Comment by bearbin** [comment]
Since there have been no updates, I am closing this issue as a suspected firewall issue. Perhaps see issue #3288 as reference.
