### ISSUE TITLE
Minecraft 1.12.1 is unsupported

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3904]
Client version:   1.12.1
Server OS:        Linux
Commit id:       07f25253a2190abfb10a27e25a72eb052421992f

Shameless plug: Couldn’t there be a setting to allow cuberite to (try to) accept connections from unknown protocol versions?

**Comment by mathiascode** [comment]
Packet IDs have changed again, so you would only get kicked. http://wiki.vg/index.php?title=Pre-release_protocol&oldid=13267

**Comment by Bond-009** [comment]
I'm taking a crack at it: https://github.com/Bond-009/cuberite/tree/1.12.1

**Comment by Seadragon91** [comment]
@Bond-009 Good luck :)

**Comment by yangm97** [comment]
@mathiascode what the… wasn’t there a time where 0.0.x releases were retro-compatible? Damn Microsoft.

**Comment by Pokechu22** [comment]
@yangm97 They needed to change the protocol to fix a (very bad) dupe bug with the recipe book.

It's worth noting that a protocol verison number change usually indicates an imcompatability (be it in the protocol or blocks/items lists) when it happens with a full release (though in development, they change them constantly).  Attempting to accept unknown versions would cause problems in almost every release situation.

**Comment by tigerw** [comment]
> a (very bad) dupe bug with the recipe book

🙃
