### ISSUE TITLE
Move plugins into their own repositories

### ISSUE THREAD

**Issue by williamhatcher** [cuberite/cuberite#3928]
Currently only 3 plugins reside in their own repositories.
Can we possibly move all the other plugins into their own repositories?
I know several of them are rarely used and/or updated, but that would provide consistency, and make updating them easier.

**Comment by Bond-009** [comment]
I would do the opposite and move `ChatLog` (which is only 1 lua file of 31 lines) from its own repo into this one.

**Comment by williamhatcher** [comment]
We'd have to use judgement.
But if I had to go through all the C++ checks when I'm proposing a pull request for a plugin, then that'd get old real fast.

**Comment by Bond-009** [comment]
`ChatLog` still has the exact same code as when it was first created (which was more than 3 years ago), so the chance that you would need to change anything to that plugin is **very** small. As for the other plugins they are 3 files at max and IMO not worthy of there own repo.

**Comment by bearbin** [comment]
In general, I am a fan of submodular plugins. However, the plugins left in this repository are mostly development tools, and some of them (APIDump in particular) are deeply connected to the state of the code in the main repo so separating them out would not be advantageous.

I don't see a pressing need to change from the status quo, but I am not strongly opposed to the idea.

**Comment by yangm97** [comment]
The real question is why development plugins end up in non-debug builds.

**Comment by williamhatcher** [comment]
I'm working on implementing `ChatLog`'s functionality into the Core plugin itself.
Things like `DumpInfo` and `HookNotify` should still probably be included for plugin devs. Maybe we can have 3 builds: release, debug, and plugin development?

**Comment by williamhatcher** [comment]
Implementing ChatLog's functionality into the Core plugin would require a system for enabling and disabling it, (and therefore saving that option) which adds unnecessary complication to the plugin.

I guess we can close this issue then.
