### ISSUE TITLE
"UnusedChunkCap" and RAM Tweaks

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#3944]
Some tweaks could be employed for the world.ini `UnusedChunkCap` setting:

1. Raspberry Pis are the most RAM sensitive officially supported devices. I think the UnusedChunkCap should have a different default for Raspberry Pis. We should perform in-game testing to find the optimal spot for the average case scenario.

2. To make this task easier and to make chunk unloads less obscure to interested end-users, we need a "verboseUnloads" flag in `world.ini` when makes the console print save cycle details.

3. I am searching for possibly simpler alternatives for the unmerged smart chunk unload PR (#3151) that are friendlier and more intuitive than `UnusedChunkCap`. Ideally, the user should just specify the maximum RAM they are willing to allocate to Cuberite. Complex logic should be self contained in just one class and not spread across the codebase unlike #3151.

**Comment by LogicParrot** [comment]
Pseudocode ideas. From simple to complex.

Super simple version:
```
If (last save cycle was more then 5 minutes ago) then: perform a save cycle.
if (Actual ram  > Ram specified in the config file) then:  perform a save cycle.
```

Throttling version:
```
If (last save cycle was more then 5 minutes ago) then: perform a save cycle.
if (Actual ram usage  > Ram specified in the config file AND cooldown is 0) then: perform a save cycle, increase cnt.
else reset cnt.
if (cnt > some constant) then:
  we conclude save cycles aren't helping, and the RAM is being used by something else,
  not the chunks. We're just overloading the disk by saving. cooldown = some constant.

if (cooldown > 0) cooldown -= 1;
```

Don't-save-them + adaptive version.
```
init():
EstimatedAverageChunkSize=1mb

If (last save cycle was more then 5 minutes ago) then: save all chunks.
if (Actual ram usage  > Ram specified in the config file):
  desired_ram_freeing_amount = current ram - Ram specified in the config file
  number of chunks to free =  desired ram freeing amount / EstimatedAverageChunkSize
  pre_save_ram = current_ram
  saveAndFreeSomeChunks(number of chunks to free)
  post_save_ram = current_ram
  actual_ram_freeing_amount = post_save_ram - pre_save_ram

   EstimatedAverageChunkSize = actual ram freeing amount / number of chunks to free
```

**Comment by worktycho** [comment]
Only problem with this approach is you need some way of getting total process RAM usage, which is complicated. Just on linux the simplest approach seems to be reading the resident set size or proportional set size from the `/proc` fs.
Additionally we need to talk about the relationship between virtual memory allocated and physical memory provided. This is complex enough that a save cycle may not reduce our physical usage, or may cause it to go up if we have got paged out (which is arguably a bad state already). I mentioned in the getting the value section we could measure resident set size, proportional set size or virtual memory allocated, do any of these make sense to use?

**Comment by worktycho** [comment]
With the don't save them all approach, we need to work out how that plays out with worlds, because at the moment the worlds unload independently. If we use that algorithm in place, each world will attempt to free enough memory on its own to bring the process under the cap, which may result in unfair behaviors where one world ends up with significantly more memory than others.

**Comment by tigerw** [comment]
hai tycho!

RAM? looks like we're overcomplicating things again ;)

**Comment by worktycho** [comment]
RAM is complicated, which is why I'm trying to avoid suggesting ideas, only explain the impacts of @LogicParrots suggestions.

**Comment by pwnorbitals** [comment]
Bumping as probably outdated issue

**Comment by tigerw** [comment]
OK, feel free to re-open.
