### ISSUE TITLE
Mobs not burning in daylight

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#3945]
Client version:   1.8.9
Server OS:        Linux
Commit id:        approx: 9936d07d9b9f24721576ca01d8c846145894e43e

### Expected behavior
The mobs should burn.

### Actual behavior
![2017-08-22_12 25 39](https://user-images.githubusercontent.com/21289123/29561346-62f898f2-8735-11e7-8159-bcb9c397343b.png)

### Steps to reproduce the behavior
Look for mobs at daytime.

**Comment by LogicParrot** [comment]
Could you try this without snow beneath?

**Comment by Bond-009** [comment]
Just tested it, it's indeed the snow that is causing the problem.

**Comment by LogicParrot** [comment]
It could be the snow. Or it could be an old lighting issue involving half-blocks like grass, mushrooms, snow. Some patches may have been previously for the latter, I'll check.

**Comment by LogicParrot** [comment]
Reference: #1926

**Comment by LogicParrot** [comment]
A good way to start investigating this would be this lighting bug workaround code: https://github.com/cuberite/cuberite/pull/3102
