### ISSUE TITLE
Contributing sections should have links to our other repos

### ISSUE THREAD

**Issue by williamhatcher** [cuberite/cuberite#3949]
CONTRIBUTING.md should have links to repos for
- The website
- User Manual
- The Plugin Repository (plugins.cuberite.org)
- All included plugins

And others

**Comment by bearbin** [comment]
Probably you mean GETTING-STARTED.md when you say CONTRIBUTING.md (which is just code style and technical info). The user manual is already included there.

There could be a bit more information about contributing to plugins, however.

**Comment by madmaxoft** [comment]
I think this info belong into the CONTRIBUTING file, perhaps under a separate section just before the code style conventions. If I wanted to contribute somehow, this is the file I'd look at, not the GETTING-STARTED

**Comment by williamhatcher** [comment]
Yep

**Comment by williamhatcher** [comment]
I don't mean links to the manual, I mean the link to its repo

**Comment by williamhatcher** [comment]
Also, it would be nice if the website and book linked to their respective repos at the bottom with the commit hash

**Comment by bearbin** [comment]
@xoft, the contributing.md file directs new developers to the getting-started.md file, so there shouldn't be any need for duplication.

@williamhatcher, doing that for the website is not possible. For the book, it is possible: submit a PR if you want.

**Comment by williamhatcher** [comment]
@bearbin, I did it, Website included.

Thanks, @javascript

**Comment by madmaxoft** [comment]
@bearbin Exactly, it directs **developers**. But people maintaining the webpage or the manual / book would not consider themselves developers, and the links make it seem like the file is only for those willing to work on the C++ side of things, anyway. My previous comment stands.

**Comment by williamhatcher** [comment]
I think liking to the repos is enough for right now.
