### ISSUE TITLE
Refactor code that uses cTracer to use cLineBlockTracer

### ISSUE THREAD

**Issue by SamJBarney** [cuberite/cuberite#395]
Just a little note to myself to remind me to document it.

**Comment by SamJBarney** [comment]
You'd be surprised. It's next on my TODO list.

Besides, if I hadn't posted it, no one would have had a good place to comment on how bad my memory is ;P

**Comment by NiLSPACE** [comment]
Before you start it might be worth discussing if we should remove the `cTracer` class. the `cLineBlockTracer` is much better, and actualy makes sense.

**Comment by SamJBarney** [comment]
True. Have all of the places where cTracer is being used been updated to use cLineBlockTracer?

**Comment by NiLSPACE** [comment]
No, not everywhere. This is what Visual Studio found:
```
Entity.cpp at line 1007
Enderman.cpp at line 57
World.cpp at line 2699
AggressiveMonster.cpp at line 78
```
And of course all the Lua bindings.

**Comment by SamJBarney** [comment]
I guess I could make it my next TODO to update those instead of documenting cTracer.
