### ISSUE TITLE
Commands broken if authentication mode is off

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3974]
Client version:   1.12.1
Server OS:        Windows

### Expected behavior
Commands should work in game if authentication mode is off.

### Actual behavior
Get always trying to execute forbidden command. This has been broken by [Add cUUID class](https://github.com/cuberite/cuberite/pull/3871)

### Steps to reproduce the behavior
Get clean server:
1) Switch Authenticate to 0 in settings.ini
2) Start server
3) Login with client
4) Run `op <player name>` from console -> Should give the player admin rights
5) Try to run command `/rank` in game -> Will print `trying to execute forbidden command` in console

Running `/rank <player name>` from console shows that player has admin rights.

**Comment by Gorgaras** [comment]
I have a problem!! when i try to type /spawn it says forbidden command: insufficient privileges ''/spawn''


Can someone help me :(

**Comment by madmaxoft** [comment]
Please don't spam unrelated issues on GitHub, use the forum for questions.
https://forum.cuberite.org

**Comment by ChunkiestAtom3** [comment]
When this is done, how is it fixed to no longer show the forbidden message?
