### ISSUE TITLE
Rename cEntity::m_IsSubmerged to m_IsHeadInWater

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#3987]
The member variable should be renamed to match its intended purpose. The getter should be renamed, too, but needs to keep the old Lua binding as well as the new, with the old one emitting a log message with a lua stack trace (see src/Bindings/ManualBindings.cpp)

**Comment by bearbin** [comment]
I think that m_IsSubmerged is actually a good name, as the member variable applies for all entities rather than just mobs with heads.

Perhaps a better name would be `m_IsUnderWater` and `m_IsInWater` substituting `m_IsSubmerged` and `m_IsSwimming` respectively?

**Comment by LogicParrot** [comment]
Suggestion:

```
GetWaterState(); // returns enum{NOT_IN_WATER, PARTIALLY_IN_WATER, FULLY_SUBMERGED}
```

**Comment by bearbin** [comment]
Good idea, I will do that.

**Comment by madmaxoft** [comment]
Not a good name because it doesn't specify that only water is checked (not lava), and only the head position is checked. Even for mobs that apparently have no heads.
As for the water state, is there an expectation of any different handling for HeadPartiallyInWater and HeadFullySubmerged? If not, there's no need for complicating things.

**Comment by bearbin** [comment]
> As for the water state, is there an expectation of any different handling for HeadPartiallyInWater and HeadFullySubmerged? If not, there's no need for complicating things.

What do you mean by this? Neither of my proposed solutions make this distinction. (There is not currently an expectation of different handling, and if a need was to arise the implementation would be simple)

**Comment by LogicParrot** [comment]
Submerged mobs drown. Mobs partially in water do not. The distinction is needed.

**Comment by LogicParrot** [comment]
Perhaps the distinction is only needed internally though, in cMonster/cEntity, and not in a public function.

**Comment by lkolbly** [comment]
It might be useful to know in a plugin, though.

**Comment by madmaxoft** [comment]
Note the wording: HEAD submerged vs HEAD PARTIALLY submerged. I, too, don't think a distinction is needed.

@LogicParrot How exactly do you define PARTIAL submersion for a mob?

As for the returned enum, what if the mob has its head stuck in a (suspended) water block, but its feet are in air? Another distinction - the mob should drown, but its movement shouldn't be impeded by fluid resistance. So basically it's about two bools - `IsDrowning` and `IsImpededByFluid`

**Comment by LogicParrot** [comment]
>@LogicParrot How exactly do you define PARTIAL submersion for a mob?

The mob is touching water, and the distance between the mob feet and the water surface is less than the mob height.

**Comment by LogicParrot** [comment]
>Note the wording: HEAD submerged vs HEAD PARTIALLY 

I was totally neglecting the head, either the MOB is fully submerged or not. I think that's good enough.

**Comment by LogicParrot** [comment]
I think it's pretty simple. 3 States:
- Not touching water
- Touching water (swimming)
- Touching water with feet deep down such that the head is below the surface (submerged/diving/choking).

**Comment by madmaxoft** [comment]
There's still a state when the mob is inside a water block but has feet in the air, and it should drown in that case.

**Comment by bearbin** [comment]
@LogicParrot / @madmaxoft Are either of the PRs referenced earlier an adequate solution to the problem?

**Comment by madmaxoft** [comment]
I'm inclined to favor #3996 , possibly with changing the IsSubmerged to include when the head is inside a lava block, too.

**Comment by bearbin** [comment]
@LogicParrot or anybody else - any opinion?

>  possibly with changing the IsSubmerged to include when the head is inside a lava block, too.

I don't think it's really necessary to add more functionality to an already deprecated method, unless there's a strong reason to do so.

**Comment by madmaxoft** [comment]
The reason (and a reason for un-deprecating): IsSubmerged should be used to decide whether an entity drowns. AFAIK entities drown in lava, too.

**Comment by bearbin** [comment]
Really? I've never noticed an air level indicator in lava.

**Comment by madmaxoft** [comment]
I can't test in-game, but I assume you drown in lava. Wiki will probably have this info.

**Comment by madmaxoft** [comment]
Weird, it really seems that entities don't drown underwater.
https://minecraft.gamepedia.com/Damage#Drowning

**Comment by bearbin** [comment]
So the code as is in #3996 would be fine for you then?

**Comment by madmaxoft** [comment]
yes

**Comment by bearbin** [comment]
@LogicParrot What are your thoughts on this?

What about you @tigerw?

**Comment by LogicParrot** [comment]
Wouldn't it be less confusing to name them `topTouchingWater` and `bottomTouchingWater` ?

**Comment by LogicParrot** [comment]
(both the variables and the API functions)

**Comment by LogicParrot** [comment]
Other than that, looks fine to me. Though I wonder if any 3+ height mobs would ever need to react to water touching their mid-section in Vanilla (perhaps for some mob grinder). The current functions don't support checking that. But we can always create an `IsAnythingTouchingWater` if we ever find out it is needed.

**Comment by Pokechu22** [comment]
You can run into that issue even with 2-high mobs: if they are standing on a slab, with a water block above it, and then air, both their head and feet will be in air, but their body will still be in water.

**Comment by bearbin** [comment]
Maybe it would be better to use code similar to this?

https://github.com/cuberite/cuberite/blob/4e7325c9e237bfa8626cdd7f7b7533328acb583d/src/Entities/Entity.cpp#L1214

But before that we need to come to a consensus on whether to use the enum or the individual variables.

**Comment by bearbin** [comment]
Any more thoughts wrt the suggested code above, and enum/individual variables?

**Comment by madmaxoft** [comment]
I'd go with whatever we need to use the information for. So far all I can think of is these two use cases:
 1, If mob is touching any lava or fire block, set it on fire (unless it also touches water (?))
 2, If mob has a certain point in their height ("mouth") within a water block, make them drown.

So for these, it makes sense to have a set of `bool` variables + getters: `IsInWater`, `IsInLava`, `IsInFire`, and `IsDrowning`

**Comment by bearbin** [comment]
That sounds good to me. I'll implement that, unless anybody else has a different idea.
