### ISSUE TITLE
Core plugin commands not working

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#3990]
Client version:   1.12.1
Commit id:        700bbdabf53ab3b47151271526570f4a862b87f2

Multiple basic commands do not work. `gamemode` example:

```
#Ingame
> /gm c
< [INFO] Player not found

#Console
>gm creative <playername>
> Executing console command: "gm c <redacted playername>"
< Player not found
```

This is game breaking for some people. Marked important.

**Comment by Infinisil** [comment]
Other commands that do NOT work: `/give`, `/tp`, `/ban`, `/kill`

Commands with player names that DO work: `/op`

**Comment by LogicParrot** [comment]
Problematic Pull request is #3948, commit https://github.com/cuberite/cuberite/commit/496c337cdfa593654018c171f6a74c28272265b5
