### ISSUE TITLE
Crash when flying above ~256 blocks

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#4006]
Client version:   1.12.1
Server OS:        Linux
Commit id:        approx: b12f4ef7d58cfe4d815feb2db1f88f223c7f2a61

### Actual behavior
The server crashed.

### Steps to reproduce the behavior
Keep flying up.

#### Core dump + exec + log files:
[cuberite_crash.tar.gz](https://github.com/cuberite/cuberite/files/1285283/cuberite_crash.tar.gz)

**Comment by Seadragon91** [comment]
Occurs here [Entity.cpp#L1692](https://github.com/cuberite/cuberite/blob/master/src/Entities/Entity.cpp#L1692)

**Comment by bearbin** [comment]
:( It's an easy fix though.
