### ISSUE TITLE
WebAdmin doesn't manage ranks properly

### ISSUE THREAD

**Issue by GTP95** [cuberite/cuberite#4015]
Client version:   x.x.x
Server OS:        Android
Commit id:        c334824199fcddde9f5a712a08a54db798965890

I did two things that could have messed up with permissions: I didn't gracefully stopped the server and I attempted a Cuberite binary update (I will check if is the "Download and install Cuberite binary" option that causes the problem). After doing that my user's data got at least partially reset, because I found myself at the spawn point with empty inventory (but I could also have previously put everything inside a chest, I'm not 100% sure) and I didn't have sufficient permissions to run privileged commands (I was Admin before this issue). I later discovered that also my home location was reset ("home" command's output told me that I hadn't a home). Anyway the problem here is that I tried to give me back operator status using WebAdmin, but in the "Player ranks" section I was still listed as admin. I tried to "edit" my rank, select admin and then save but it din't work, reloading the server didn't make any difference. To get back my Admin rank I had to issue the "op" command from console. It worked, but now I'm listed twice in the Cuberite WebAdmin interface. 
Seems that Cuberite WebAdmin reads and writes permissions from/to a different place or in a different way than the server, so their status could be inconsistent under particular circumstances.

**Comment by GTP95** [comment]
Related to this problem: so far only to players (me and another) have ever logged into the server (I'm sure because has withelist turned on) but in the players folder there are 3 subfolders, does this means that the server thinks that there are 3 users?

**Comment by peterbell10** [comment]
Have you at some point switched from using authentication to not?
That's Core - Server Settings - Authentication - Authenticate in WebAdmin.

**Comment by GTP95** [comment]
No, I've never disabled authentication.

**Comment by peterbell10** [comment]
You say you updated Cuberite recently but do you know when your previous version was from?  There was a bug related to ranks between the 25th and 29th of August that could've caused this.

If you gave me the two different UUIDs for a single player then I could confirm.

**Comment by madmaxoft** [comment]
Actually, just have a look at the json files in there, each should have a `lastknownname` element specifying the player name.

**Comment by GTP95** [comment]
lastknownname has value "7heKiller" for both players. Where do I find the UUIDs?

**Comment by peterbell10** [comment]
When you go to edit the player rank in WebAdmin it should appear just above the current rank

**Comment by madmaxoft** [comment]
The UUID is actually the filename, in combination with the folder name. For example, the file `players\7a\037f55-cce2-30d7-8dcd-c9ed0af1cbd5.json` belongs to the UUID `7a037f55-cce2-30d7-8dcd-c9ed0af1cbd5`

**Comment by GTP95** [comment]
The two UUIDs (taken from WebAdmin) are 58592795383445931162406342746232 and f8f9279fd83e4f93bb624a634274623c. The first one looks broken.

**Comment by peterbell10** [comment]
You're right, the first one is broken.  Notice that if you take the letters from the second UUID and assign the letters a through f the values 0 through 5 then you get the first UUID.  This is exactly the issue fixed by #3974.
