### ISSUE TITLE
If plugin manipulates world on startup server crashes

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4042]
Commit id:        e883aa828c304600fcd707b50df9515011311db8

### Expected behavior
Server should not crash.

### Actual behavior
Server crashes.

### Steps to reproduce the behavior
Load this plugin code:
```
function Initialize(a_Plugin)
	a_Plugin:SetName("Crash")
	cRoot:Get():GetDefaultWorld():SetBlock(0, 100, 0, 1, 0)
	return true
end
```

Ref, forum post:
https://forum.cuberite.org/thread-2937.html

**Comment by sphinxc0re** [comment]
Could this be related to #3572 ?

**Comment by Seadragon91** [comment]
No your plugin accesses the chunk over a hook. The code here accesses a world that is not fully loaded.

**Comment by peterbell10** [comment]
The order in `cRoot::Start` is:
 * Worlds are loaded
 * Plugins are initialised
 * Worlds are started

In the period between loading and starting, doing almost anything with a world will probably crash the server.  I think the fundamental problem is that `cWorld` isn't properly constructed without being started.  In fact I think it would hang on destruction if `Start` wasn't called first.  

I suggest `cWorld::Start` be removed and it's work be done in the constructor.  I think it's either that or add `nullptr` checks to every function in `cWorld`.

**Comment by NiLSPACE** [comment]
I believe there was a reason why worlds were not started at the time they are loaded. @madmaxoft do you know the reason?

**Comment by Seadragon91** [comment]
One good reason I can think of is the chunk generator.

**Comment by peterbell10** [comment]
What do you mean by that?  No chunks are generated before `cWorld::InitializeSpawn` is called, right?

**Comment by madmaxoft** [comment]
This is from the time when there was no `cWorld::InitializeSpawn`, its work was done within `cWorld::Start` and therefore in order to give the plugins a chance to register the world-generator hooks before the spawn initialization, they needed to be loaded before starting the world.

The startup sequence is rather brittle, with many special requirements that are not immediately obvious, so I would advise against changing it unless there's a really good reason for that. If you think moving the work of `cWorld::Start` into the constructor will not affect things, give it a try, but beware that a lot of testing will be needed.

**Comment by madmaxoft** [comment]
Here's the first ever discussion of plugins interacting with the terrain generation, the issue is somewhat noticed there already. If you want to go history-spelunking :)
https://forum.cuberite.org/thread-464.html

**Comment by peterbell10** [comment]
Looking at the git history:
 * The `LoadWorlds` - `StartWorlds` split happened in d832996e198605c20760c72433e35beca3192a5a, at which point `cWorld::Start` didn't exist and [`cWorld`'s constructor](https://github.com/cuberite/cuberite/blob/d832996e198605c20760c72433e35beca3192a5a/source/cWorld.cpp#L226-L305) did all the work.

 * `cWorld::Start` was introduced in 4c5590636cf4a311f03e735878557b1e7b3362dd which is from #93 which is ostensibly just about threading.

Now the question is: why did @madmaxoft split it?  Maybe the additional threads introduced some complex dependency that wasn't documented.  But then again it's entirely possible that the `Start`-`Stop` interface was put there purely to mimic the `cIsThread` interface.

**Comment by madmaxoft** [comment]
It was split exactly for the reason that plugins may want to register for the chunk generating hook before a world is loaded.

**Comment by peterbell10** [comment]
The change came more than a year after the hook though...

**Comment by madmaxoft** [comment]
Can't change everything at once :)
