### ISSUE TITLE
Stone pressure plates don't open/close doors anymore

### ISSUE THREAD

**Issue by floriangosse** [cuberite/cuberite#4046]
Client version:   1.12.2
Server OS:        Linux (Docker)
Commit id:        e883aa828c304600fcd707b50df9515011311db8

### Expected behavior

Step on stone pressure plate will open/close door next to trigger.

### Actual behavior

All doors which are controlled by a stone pressure plate will be opened when a users joins the server. The doors can't be opened/closed anymore when step on a stone pressure plate. The players have to do it manually like without trigger.

### Steps to reproduce the behavior

Don't have a way to reproduce it. I upgraded to build 901 and used client 1.12.2 and it didn't work anymore.

**Comment by Bond-009** [comment]
I can only reproduce this issue with stone pressure plates.
![screenshot from 2017-09-25 18-09-35](https://user-images.githubusercontent.com/21289123/30818764-c7b8be8c-a21c-11e7-929a-ba9838f26f8e.png)

**Comment by floriangosse** [comment]
Yes, you're right. I found it out after I created the issue and forgot to update it.

**Comment by madmaxoft** [comment]
Can you remember which build you used before, in which it worked? So that we can bisect which commit has caused the issue.

**Comment by Bond-009** [comment]
I looked at the file history of `PressurePlateHandler.h` and maybe e225b7f8262df48ad4d7094bc295add3007b0649 or 60dfaa09679219868e58a44d6d86f5d8d524ce24 by @peterbell10 could have caused this issue. That are the only real changes in the logic in the last 2 years.

**Comment by floriangosse** [comment]
Thank you. :)
