### ISSUE TITLE
New logged in players are not visible by other players

### ISSUE THREAD

**Issue by floriangosse** [cuberite/cuberite#4049]
Client version:   1.12.2
Server OS:        Linux (Docker)
Commit id:        4b14a5b4c1182fddb400476dc5c5b7dcdbd7367c

### Expected behavior

The players can see each other.

### Actual behavior

New logged in players are not visible by other players.

### Steps to reproduce the behavior

1. Player 1 logs in
1. Player 2 logs in
1. Player 2 moves in front of Player 1

* Player 1 can't see Player 2
* Player 2 can see Player 1

**Comment by XenonPK** [comment]
Confirmed on latest master, running on OpenSUSE Tumbleweed.

**Comment by timwoj** [comment]
I'm experiencing this as well. The players can actually see each other, if they spawn near the same location. The players don't move though, but they spin around in place as if they are moving and turning around the world.

**Comment by jammet** [comment]
Same here. There are very rare moments when people can  see each other, but usually they just don't. That wouldn't be so bad, if half of the other mobs wouldn't also be invisible most of the time. Currently this is the biggest issue overall. You can't have invisible creatures everywhere, that makes the game virtually unplayable in survival mode.

**Comment by nixi-awoo** [comment]
This problem persists in the (currently) [latest version](https://github.com/cuberite/cuberite/tree/96b72ab88ec2610a41707b9705808d3c1c46046a). Players who switched gamemodes became invisible for other players. If one player reconnects, he sees others, but becomes invisible to others instead.

**Comment by bearbin** [comment]
I'm guessing that this bug might be related to https://github.com/cuberite/cuberite/issues/4082, according to [wiki.vg](http://wiki.vg/Protocol#Spawn_Player) the client will not spawn a player in response to a spawn player packet unless the player list item has been sent first.

**Comment by mathiascode** [comment]
After testing old builds, commit https://github.com/cuberite/cuberite/commit/5d64451f74af1839177f9b93d76cd393b7a58ad1 seems to have introduced the issue.

**Comment by mathiascode** [comment]
I've come to the following conclusion:
- Server-wise the player's position is always correct

Two players are standing next to each other.
- When one of the players move to another world with the /portal command, then teleport to the other player with /tp, both players can still see each other.
- When one player teleports somewhere else with e.g. /tp 44444 65 444444, then teleports back to the other player, the other player can't see the player who teleported to them.
- When one player moves to another world with /portal, then teleports to another location e.g. /tp 44444 65 444444, and then teleports back to the other player, the other player can't see the player who teleported to them.

**Comment by Greeny2408** [comment]
I still have this issue when using /portal to another world, the other player inside this world cant see me.

**Comment by mathiascode** [comment]
This is not fixed, can still reproduce using methods in https://github.com/cuberite/cuberite/issues/4049#issuecomment-378675634

**Comment by mathiascode** [comment]
Should be fixed now.

**Comment by Titaniumtown** [comment]
I am still having the issue. Is there any fix?

**Comment by tigerw** [comment]
Should this be reopened ?

**Comment by Titaniumtown** [comment]
No, it works now!
