### ISSUE TITLE
Velocity dead-stop

### ISSUE THREAD

**Issue by erherhh4herh** [cuberite/cuberite#4062]
Client version:   1.12.2
Server OS:        Windows 10 64-bit
Commit id:        76a0971279de47c5a1d8510848e88e57cc6eed72

Jump as usual no matter velocity and land orientation
### Expected behavior

Lands and cancels jump
### Actual behavior

Jump from high area, hold jump button until you hit the ground.
### Steps to reproduce the behavior

Video of the occurrence: https://youtu.be/OV-1N5fz5qM

**Comment by madmaxoft** [comment]
I'm afraid I don't see what's wrong.

**Comment by NiLSPACE** [comment]
When he hits the ground he is unable to immediately jump again.

**Comment by erherhh4herh** [comment]
NiLSPACE is correct. It resembles early poor bukkit anti-cheats...
