### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by lukeeey** [cuberite/cuberite#4064]
What is the perormance over Java softwares like Spigot or Glowstone or C# softwares like MiNET? why should i use Cuberite?

(I know this is not the place to ask, but you should really add a CONTRIBUTING.md :P)

**Comment by bearbin** [comment]
Please use the [forum](https://forum.cuberite.org) for these types of questions.

Also, we do have a CONTRIBUTING.md

**Comment by lukeeey** [comment]
It's not showing the usual banner about reading contributing guidlines.
