### ISSUE TITLE
Webadmin footer covering content in Safari

### ISSUE THREAD

**Issue by ePirat** [cuberite/cuberite#4068]
Server OS:        Linux
Commit id:        c54bf40

### Expected behavior
The footer of the webadmin should be after the content, or at least, not covering it, without the ability to scroll.

### Actual behavior
Scrolling a long page to the bottom, the footer covers the content.
Scrolling down further is impossible, so the save button can't be clicked.

<img width="1122" alt="screenshot" src="https://user-images.githubusercontent.com/323210/32693399-d4f578dc-c72a-11e7-8e23-43ccbe6c8c17.png">

### Steps to reproduce the behavior
Open a longer page, like `/Core/Plugins` in Safari 11.0.2 and scroll to the bottom.

**Comment by ePirat** [comment]
A simple workaround is to set `padding-bottom: 65px;` for `.row2`.

**Comment by bearbin** [comment]
@ePirat, can you test with my change in #4107?

**Comment by willi123yao** [comment]
Tested your change, problem persists in Safari browser. However, ePirat's solution seems to be working.
