### ISSUE TITLE
Double click to stack items doesn't prioritize items in crafting table/grid

### ISSUE THREAD

**Issue by 9caihezi** [cuberite/cuberite#4084]
Client version:   1.12.2
Server OS:        Windows
Commit id:        0dd172b80ffc949cf87119ad2003589d7eb82c46

### Expected behavior
With stack-able items in crafting table/grid, double click same items in inventory, stacks the item from crafting table/grid and then inventory.
E.g., I have 4 cobble stone in crafting table/grid, a stack of 60 and a stack of 64 cobble stones in inventory. After double click the stack of 60 cobble stones, The stack becomes 64, which takes 4 from crafting table/grid.

### Actual behavior
I have 4 cobble stone in crafting table/grid, a stack of 60 and a stack of 64 cobble stones in inventory. After double click the stack of 60 cobble stones, The stack becomes 64, which takes 4 from the other stack. Unfortunately the client would assume the items in crafting table/grid stacked away, they temporarily disappears, and drops on ground after closing the window.

### Steps to reproduce the behavior
As described above.

**Comment by KoshNaranek** [comment]
I guess this is the same thing like "shift-right-click" in crafting-output?
Stack of wood on the bench - shift right-click SHOULD get a stack of wooden planks - it works but the bench isn't updated correctly and there still is wood on the bench until it's clicked...? Just asking...

**Comment by peterbell10** [comment]
@KoshNaranek That is handled by a slightly different code path internally. So it should really be in a separate issue.
