### ISSUE TITLE
Golden apple does not take effect

### ISSUE THREAD

**Issue by 9caihezi** [cuberite/cuberite#4087]
Client version:   1.12.2
Server OS:        Windows/Linux/macOS/BSD/...
Commit id:        all

### Expected behavior
Eat a golden apple, got corresponding effect

### Actual behavior
Eating (enchanted) golden apple has no effect.

### Steps to reproduce the behavior
As above.

The golden apple handler is special, but it's changed in commit 10d42a2452e19ca98506df4d85c0e8f37b3e8981.

A bonus bug: the item is consumed before the saturation check. Which means, not consuming the food when saturated relies on client side check and the check in HandleRightClick. If there's a buggy implementation of golden apple, the food can be consumed in vain.

IMHO, consuming the item should be in cPlayer::FinishEating, otherwise there's no clean way to have the item consumed with recursive call of EatItem function.

**Comment by peterbell10** [comment]
I was a bit confused because golden apples seemed to work fine.  Missing in the steps to reproduce is that the player can't be hungry. If the player isn't hungry when they eat the apple, the status effects aren't applied.

Both notch and normal golden apples have the same issue.

**Comment by 9caihezi** [comment]
Which version(client &server) are you running?
In my test, it doesn't work whether or not the player is hungry.

**Comment by peterbell10** [comment]
Cuberite on latest master (0dd172b80ffc949cf87119ad2003589d7eb82c46) and Minecraft 1.12.2
