### ISSUE TITLE
Forum is down

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4091]
The forum seems to be timing out. Any idea why? @sphinxc0re

**Comment by ThuGie** [comment]
its been offline since at least yesterday if not sooner

**Comment by Cl1608Ho** [comment]
Tuesday or Wednesday was when I noticed it first.

**Comment by mathiascode** [comment]
The whole VPS is unresponsive. I can't connect to FTP. We have to wait for @sphinxc0re to check what the issue is, since he hosts the forum.

**Comment by sphinxc0re** [comment]
I'm really sorry for the downtime 🤕

**Comment by mathiascode** [comment]
No worries!
