### ISSUE TITLE
opening chest -> Armor replaced

### ISSUE THREAD

**Issue by KoshNaranek** [cuberite/cuberite#4092]
Client version:   1.12.2
Server OS:        Raspbian Stretch
Commit id:        0dd172b80ffc949cf87119ad2003589d7eb82c46

### Expected behavior
--
### Actual behavior
<img width="580" alt="bildschirmfoto 2017-12-16 um 13 18 33" src="https://user-images.githubusercontent.com/34599995/34070363-47a428f6-e265-11e7-96c5-899e372a9102.png">
<img width="665" alt="bildschirmfoto 2017-12-16 um 13 19 06" src="https://user-images.githubusercontent.com/34599995/34070365-49a09ac2-e265-11e7-9a11-6556a5df4213.png">

opening a double chest (no redstone) sometimes causes strange things. 
The armor is "gone".
Instead player holds "line1" from the chest and the item lower left corner as a shield.
(had 7 sand - they disappeared when clicking) 

The Items stay in the "workbench" even if inventory is closed.

When items that replaced the armor are dropped, they return back to what they've been.

<img width="541" alt="bildschirmfoto 2017-12-16 um 13 52 14" src="https://user-images.githubusercontent.com/34599995/34070535-66f06a78-e268-11e7-9d15-f64e42ff8a8a.png">

dropped them into a fire  :-( so ... 5 lost) 

Seems there are 2 variables mixed up...

### Steps to reproduce the behavior
Happend twice ... not sure

**Comment by Seadragon91** [comment]
I had the same problem multiple times, too.
This are the challenges from the skyblock plugin, The items should be at the second row in the above inventory:
![2020-03-23_19 59 51](https://user-images.githubusercontent.com/14818618/77388194-b2753c80-6d8f-11ea-82c5-75b6900182c9.png)

Here I had the items from the chest in my inventory:
![2020-03-22_08 14 47](https://user-images.githubusercontent.com/14818618/77388259-ea7c7f80-6d8f-11ea-890d-dd7331dbc960.png)
