### ISSUE TITLE
Pull Requests aren't displaying CI status

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#4097]
### Actual behavior
Builds are triggered correctly on [TravisCI][Travis], [CircleCI][Circle] and [AppVeyor][AppV] yet PR's don't link to the build at all.  Instead, the CI checks are stuck on "Waiting for status to be reported".

See: #4080, #4083, #4085, #4086, #4089, #4094, #4095 and #4096

[Travis]:https://travis-ci.org/cuberite/cuberite/pull_requests
[Circle]:https://circleci.com/gh/cuberite/cuberite
[AppV]:https://ci.appveyor.com/project/madmaxoft/mcserver/history

**Comment by bearbin** [comment]
I believe that this is due to the Cuberite organisation [third party application access policy](https://help.github.com/articles/about-oauth-app-access-restrictions/). I enabled the access restrictions a while ago, and I believe that they have stopped the CIs from updating build status.

I have enabled access for travis again and poked it, so hopefully that should start working again. Somebody with a CCI or AppVeyor account will need to request a grant of permissions for them too.

**Comment by peterbell10** [comment]
I pushed a test commit to #4095 and it seems to be linking to travis properly now.

**Comment by madmaxoft** [comment]
I've managed to get CircleCI working, but I can't find a way to enable AppVeyor. I have no idea how to request the permission grant from there.

**Comment by 9caihezi** [comment]
Now it's working, but clang compiler complains about nullptr:

```
In file included from /home/travis/build/cuberite/cuberite/tests/CompositeChat/CompositeChatTest.cpp:7:
In file included from /home/travis/build/cuberite/cuberite/src/CompositeChat.h:7:
In file included from /home/travis/build/cuberite/cuberite/lib/jsoncpp/include/json/json.h:11:
/home/travis/build/cuberite/cuberite/lib/jsoncpp/include/json/reader.h:217:76: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  bool addError(const std::string& message, Token& token, Location extra = 0);
                                                                           ^
                                                                           nullptr
1 error generated.
make[2]: *** [tests/CompositeChat/CMakeFiles/CompositeChat-exe.dir/CompositeChatTest.cpp.o] Error 1
make[1]: *** [tests/CompositeChat/CMakeFiles/CompositeChat-exe.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by bearbin** [comment]
Appveyor is now fixed.
