### ISSUE TITLE
Stamping on farmland does not revert it back to dirt

### ISSUE THREAD

**Issue by 9caihezi** [cuberite/cuberite#4109]
Client version:   1.12.2
Server OS:        Windows
Commit id:        f0b05e78f70fa883bfdc74568bd7bf914025306c

### Expected behavior
Jump on farmland, farm land becomes dirt.

### Actual behavior
Nothing

### Steps to reproduce the behavior
Described as before.

**Comment by peterbell10** [comment]
Duplicate of #1179

**Comment by bearbin** [comment]
Closing as duplicate.
