### ISSUE TITLE
Cannot place more than one lapis in enchanting table

### ISSUE THREAD

**Issue by 9caihezi** [cuberite/cuberite#4112]
Client version:   1.12.2
Server OS:        Windows
Commit id:        f0b05e78f70fa883bfdc74568bd7bf914025306c

### Expected behavior
As described.

### Actual behavior
As described.

### Steps to reproduce the behavior
As described.

**Comment by tympaniplayer** [comment]
I'm taking a look at this one now. Both slots in the window are treated the same right now which is the root cause of the problem.
