### ISSUE TITLE
Dig block with an armor in hand damages the armor.

### ISSUE THREAD

**Issue by 9caihezi** [cuberite/cuberite#4119]
Client version:   x.x.x
Server OS:        Windows/Linux/macOS/BSD/...
Commit id:        (Found at the top of the server's console output)

### Expected behavior
Hold an armor in hand, dig an dirt block, the armor keeps the durability.

### Actual behavior
The armor lost one durability.

### Steps to reproduce the behavior
As described.

I cannot think of any case that the armor should be damaged in cPlayer::UseEquippedItem() function.

**Comment by bearbin** [comment]
It appears that the whole item durability system is broken - getting the damage for using an item does not take into account what kind of item it is.
