### ISSUE TITLE
UrlClient-test failures on TravisCI apple builds

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#4124]
Client version:   N/A
Server OS:        macOS
Commit id:       Anything after 5b6b04375270f3f3ba90780ecf692d56af157e49 (When apple was added to travis)

### Expected behavior
UrlClient-test always passes.

### Actual behavior
UrlClient-test will sometimes fail outright, other times it deadlocks and the travis worker times out.
[The first case](https://travis-ci.org/cuberite/cuberite/builds/303659238) was a timeout and happened very soon after apple was added to travis.
[This one](https://travis-ci.org/cuberite/cuberite/jobs/321859533) actually failed with a segfault though timing out seems more common.

### Steps to reproduce the behavior
Unknown.

**Comment by peterbell10** [comment]
Looks like this is still happening:
https://travis-ci.org/cuberite/cuberite/jobs/333420151

**Comment by tigerw** [comment]
https://travis-ci.org/cuberite/cuberite/jobs/407388570

Evidently Mac OS's fault.

**Comment by madmaxoft** [comment]
Still there, and getting more frequent.
(link unavailable, job was restarted several times)

**Comment by tigerw** [comment]
Seems like that fixed it.
