### ISSUE TITLE
Cannot Connect via TCPv4

### ISSUE THREAD

**Issue by dibi73** [cuberite/cuberite#4134]
Client version:   Windows, 1.2.8
Server OS:        Raspbian
Commit id:        d7de2dccf0d0cd50588f5b43773d4e7fc5bd94a6
### Expected behavior
I want to connect from my PC to my raspberry-Minecraftserver. 

### Actual behavior
no connection possible to the pi with minecraft.
pi@minecraftpi:~/Server $ netstat -a | grep 255
tcp6       0      0 [::]:25565              [::]:*                  LISTEN 
only on TCP6 (you can see it on [::] i suppose)

the webserver works !
pi@minecraftpi:~/Server $ netstat -a | grep http
tcp6       0      0 [::]:http-alt           [::]:*                  LISTEN  
--> Windows10+Edge can access via tcpv6, i think.

### Steps to reproduce the behavior
Installed Rasbian. 
wget http://builds.cuberite.org/job/Cuberite%20Linux%20raspi-armhf%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz
tar -xvzf Cuberite.tar.gz
rm Cuberite.tar.gz
started Server, stopped it
edited webadmin.ini, changed password
started Server

--> webserver works, minecraft-connection does not work

**Comment by peterbell10** [comment]
This sounds similar to #3288.  Can you try the [suggested fix](https://github.com/cuberite/cuberite/issues/3288#issuecomment-320366916):
```
sysctl -w net.ipv4.tcp_syncookies="1"
```

**Comment by dibi73** [comment]
Thank you for the hint, but I have searched the forum already yesterday and tried that.
i have also found a hint with disabling the firewall ufw: I dont have installed a firewall so that cannot be the Problem, too.

**Comment by Cl1608Ho** [comment]
Just to make that clear, ufw isn't the firewall itself, it's an easier way to access iptables, which is integrated in the kernel. Dunno about your setup but  netstat should always list the server, even if there was a firewall.

**Comment by dibi73** [comment]
thank you for that information. but i still cannot connect from the client to my Server.

**Comment by peterbell10** [comment]
Looking at the code, both the game server and webadmin use "dual stack" sockets which accept connections via IP v4 and v6.  According to [this Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=612582), netstat only shows dual stack as listening on v6 so I don't think that's the issue.

I've tried it on my own RaspberryPi.  At first I can't connect but after enabling `tcp_syncookies` and rebooting the pi, I can connect fine.

If that doesn't work for you then I'm not sure what else it could be but a firewall issue, especially as you can connect to webadmin fine.

**Comment by Pokechu22** [comment]
Um...

> Client version: Windows, 1.2.8

Cuberite only supports Java Edition; Bedrock Edition/Pocket Edition/Windows 10 Edition isn't supported.  Things won't work if you try to use PE with it (for instance, PE uses UDP instead of TCP, and has a whole different protocol beyond that)

**Comment by peterbell10** [comment]
Ah, I hadn't even considered the windows 10 version.  Maybe the readme should be updated to say:
>Cuberite is compatible with the ~vanilla~ Java Edition Minecraft client
