### ISSUE TITLE
Generated cactuses are only one block tall in desert biomes

### ISSUE THREAD

**Issue by Cocosushi6** [cuberite/cuberite#4135]
Client version:   All supported (1.8->1.12.2)
Server OS:        Raspbian 9 Stretch (GNU/Linux)
Commit id:        757231cc6e777b8f4717d1467ef7efa01c7fde15

### Expected behavior
Cactuses structures are 1, 2 or 3 block tall
![2018-01-06_17 25 07](https://user-images.githubusercontent.com/15072840/34641619-0e08047a-f307-11e7-9ed8-1dd548593fb9.png)
(image taken in a local Minecraft world)

### Actual behavior
Cactuses structures are only 1 block tall 
![2018-01-06_17 25 44](https://user-images.githubusercontent.com/15072840/34641620-10cf9b6e-f307-11e7-8b2a-6779cce2fe56.png)
(image taken on Cuberite instance)

### Steps to reproduce the behavior
Simply getting into a desert biome with cactuses. Seed of the world with the bug is 300388357.

### Notes
I am more or less at ease with C++, and would love to solve this bug by myself. The sources being quite large, could I have some clues about where to find the files involved ? Thank you very much !

**Comment by Bond-009** [comment]
I think that this is the file: https://github.com/cuberite/cuberite/blob/master/src/Generating/FinishGen.cpp#L803

**Comment by bearbin** [comment]
You beat me by a minute :|

**Comment by Cocosushi6** [comment]
Great ! Thanks :)

**Comment by Cocosushi6** [comment]
Ok, I think I solved it - it also takes in account the MaxCactusHeight parameter in world.ini (here tested with 10 as max value) : 

![2018-01-07_01 01 31](https://user-images.githubusercontent.com/15072840/34645158-6f211da2-f346-11e7-9dff-1d16503e2bb1.png)
I will make a PR as soon as I have time !
