### ISSUE TITLE
Cmake build issues.

### ISSUE THREAD

**Issue by bionext03** [cuberite/cuberite#4141]
Change dir names in CMakeLists.txt 
tolua++ > toluapp
mbedtls > polarssl

**Comment by peterbell10** [comment]
Can I get a bit more information:
* Which CMakeLists.txt are you talking about
 * What error are you getting

**Comment by bionext03** [comment]
CMakeLists.txt in the main directory and mbedtls.cmake in main_dir/lib.

Errors:
"tolua++ is missing in folder lib/tolua++. Have you initialized and updated the submodules / downloaded the extra libraries?"
because when the directory is cloned the link is downloaded toluapp;
and  "mbedtls is missing in folder lib/mbedtls . Have you initialized the submodules / downloaded the extra libraries?"
because when the directory is cloned the link is downloaded polarssl;

**Comment by bionext03** [comment]
CMakeLists.txt in the main directory and mbedtls.cmake in main_dir/lib.

Errors:
"tolua++ is missing in folder lib/tolua++. Have you initialized and updated the submodules / downloaded the extra libraries?"
because when the directory is cloned the link is downloaded toluapp;
and  "mbedtls is missing in folder lib/mbedtls . Have you initialized the submodules / downloaded the extra libraries?"
because when the directory is cloned the link is downloaded polarssl ;

**Comment by peterbell10** [comment]
Can you try running the following from the cuberite directory:
```
git submodule sync
git submodule update --init
```

**Comment by bionext03** [comment]
Ok, wait.


>Суббота, 13 января 2018, 21:02 +08:00 от peterbell10 <notifications@github.com>:
>
>Can you try running the following from the cuberite directory:
>git submodule sync
>git submodule update --init
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Виктор Большаков

**Comment by bionext03** [comment]
Thanks, it worked.

**Comment by peterbell10** [comment]
Great, closing as fixed.
