### ISSUE TITLE
Boots don't get damaged when taking falling damage

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#4142]
Client version:   1.12.2
Server OS:        Linux
Commit id:       4242431407459e91f725de9cb7fb1e2ffade216d

### Expected behavior
The boots should take damage.

### Actual behavior
They don't take damage

### Steps to reproduce the behavior
Jump from a cliff

**Comment by Pokechu22** [comment]
I'm pretty sure that that's vanilla behavior but I'll have to double-check.

**Comment by Bond-009** [comment]
Looks like you are right, thanks.
