### ISSUE TITLE
Android builds down

### ISSUE THREAD

**Issue by Cl1608Ho** [cuberite/cuberite#4165]
Although https://cuberite.org/status reports android builds are working, individual compilation fails. The script however does not exit on a compile failure, so Jenkins continues building and doesn't report an error.

Is this related to #4163?

**Comment by peterbell10** [comment]
The PR fixed a different issue.  Both are related to #4152 though.

**Comment by peterbell10** [comment]
Looks like libevent/libevent#475, I'll see if I can cherry-pick the fixes again.
