### ISSUE TITLE
Stairs are solid.

### ISSUE THREAD

**Issue by bionext03** [cuberite/cuberite#4166]
![2018-01-22_16 41 05](https://user-images.githubusercontent.com/18181530/35211974-85ab0dea-ff93-11e7-94a6-573d489aa22d.png)

Is it a bug or so conceived? I think it's because the stairs are solid.

**Comment by bionext03** [comment]
The error has been fixed. It remains only one difference, the stairs are not placed on the glass. But I think it's even better.

**Comment by bearbin** [comment]
Ah, that is a separate issue, thanks for bringing it to my attention, I'll push another commit to that PR to fix it.

**Comment by bionext03** [comment]
Ok.
