### ISSUE TITLE
Using same UUID (compat to spigot/bukkit etc) 

### ISSUE THREAD

**Issue by sa-tasche** [cuberite/cuberite#4177]
Client version:   1.12.2
Server OS:        Windows
Commit id:        95108c134d410040efadfa6bb00c8ce3486fb7fa built at: 629

### Why?
It can help to import existent worlds with entities owned by a player.

### Expected behavior
If the UUID is 5 in spigot/bukkit/paperclip(/vanlilla?)
Than it is the same in cuberite

### Actual behavior
Another UUID is generated -> another player

### Steps to reproduce the behavior
Start cuberite and another MC server (spigot/bukkit/paperclip)

### Alternative solution
Map a current Cuberite UUID to any other.

**Comment by peterbell10** [comment]
If you run Cuberite with authentication enabled then it should get the player's UUID from Mojang's authentication server.  This would be consistent with vanilla/anything else using authentication.

Is that what you're looking for?

**Comment by sa-tasche** [comment]
No. I want to play offline with same inventory etc.

BTW - but another issue: My animal stock and all my tamed wolfs are all gone :`(

**Comment by peterbell10** [comment]
After a bit of searching it looks like it would be a trivial code modification to get this working. However, this would break existing Cuberite worlds and permissions settings so it's a non-trivial decision which way to go.


Here's a summary of the required changes based on the information from http://wiki.vg/Protocol#Spawn_Player 
>In offline mode, UUID v3 is used with the String `OfflinePlayer:<player name>`

The string would need to be changed here:
https://github.com/cuberite/cuberite/blob/f0c735e8466fbb52bb805dd839f5e4fd37d59af8/src/ClientHandle.cpp#L284-L288

Also, this non-conformity would have to be removed from `cUUID::GenerateVersion3`:
https://github.com/cuberite/cuberite/blob/f0c735e8466fbb52bb805dd839f5e4fd37d59af8/src/UUID.cpp#L273-L276

**Comment by madmaxoft** [comment]
Wouldn't we also lose the ability to detect whether the UUID is for an online player or an offline player? Currently this is inferred from the UUID type.

**Comment by peterbell10** [comment]
This wouldn't involve changing the type of offline UUIDs, both Cuberite and vanilla use version 3 UUIDs for offline.  The main difference is just the string being md5 hashed.
