### ISSUE TITLE
Lua API: "argument #1 is 'cPluginManager'; 'cPluginManager' expected."

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#4188]
Client version:   1.12.2
Server OS:        Linux
Commit id:        7e9695ecb018cab152794e5a23b96f0acc65cab4

### Expected behavior

When calling `cRoot:Get():GetPluginManager():CallPlugin(args)`, I expect the given command with arguments to be executed from a different plugin providing an API.

### Actual behavior

```
LUA: Plugins/TestMinigame/main.lua:29: error in function 'CallPlugin'.
     argument #1 is 'cPluginManager'; 'cPluginManager' expected.
```

Seeing I run `cRoot:Get():GetPluginManager():CallPlugin(args)` rather than `cRoot:Get():GetPluginManager().CallPlugin(args)`, this should work fine (otherwise it'll complain that the first argument is a string instead).

### Steps to reproduce the behavior

Just call `cRoot:Get():GetPluginManager():CallPlugin(args)` from anywhere.

**Comment by peterbell10** [comment]
According to the [API docs][docs], `CallPlugin` is static so the correct calling convention should be `cPluginManager:CallPlugin(args)`.  Can you try that?

[docs]: https://api.cuberite.org/cPluginManager.html

**Comment by PureTryOut** [comment]
Makes sense. However:

```
LUA: Plugins/TestMinigame/main.lua:29: error in function 'CallPlugin'.
     argument #3 is 'nil'; 'string' expected.
```

And yes, the 3rd argument isn't `nil`, I'm 100% sure.

**Comment by PureTryOut** [comment]
Ha, you're right. My mistake, thanks for your help!

**Comment by madmaxoft** [comment]
The static API functions' error reporting is weird, I have some fixes stashed, but they aren't ready yet.
