### ISSUE TITLE
XP Orb doesn't do what it appears to do.

### ISSUE THREAD

**Issue by leeadama** [cuberite/cuberite#4216]
Client version:   1.12.2
Server OS:        Android
Commit id:       98d807187bbaec4cd65dbe7c1ecac0435efb6df0

### Expected behavior
XP orb should fly to Player and be picked up.

### Actual behavior
XP orb appears to fly to Player but isn't picked up.  It just kind of fly's around the player.

In reality it is actually sitting on the ground near the spot where the monster died.  It isn't picked up until I walk forward over that spot.  You can hear it "Ping" even though you can't see it.

After you walk forward and pick it up the visible orb disappears.

Occasionally I can't find where the Orb actually is and the "Flying" orb will stay with me for 5 minutes or so until something times out and it goes away.

### Steps to reproduce the behavior
Kill something from a slight distance, through a doorway, etc.  Observe the behavior of the XP Orb.  Walk toward where the monster was.  Hear the XP Orb be picked up only after you move over the right spot.

You can see it here : https://youtu.be/O-sVAOsDNHw

**Comment by tigerw** [comment]
Unfortunately the fancy physics of XP orbs is completely unimplemented serverside, I think what you see is a client prediction of what should be happening. We'll get on to it, eventually...
