### ISSUE TITLE
Change to Circle CI 2.0

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#4221]
Circle CI 1.0 will stop working August 31.
```
We’re sunsetting CircleCI 1.0: August 31, 2018 is the final day for 1.0 builds.
Refer to CircleCI 2.0 Hello World document for users and developers to get started with CircleCI 2.0. 
```
This issue is blocking #4214 since the current Ubuntu image being used doesn't have clang-tidy in its package repo.
As a temporary fix someone with acces to the Circle CI Project settings could change the Ubuntu image to 14.04
Ref: https://circleci.com/docs/1.0/build-image-trusty/

**Comment by peterbell10** [comment]
I think I've set Circle to 14.04, can you try pushing to #4214?
