### ISSUE TITLE
World Files not loading in server

### ISSUE THREAD

**Issue by pufflegamerz** [cuberite/cuberite#4222]
Client version:   1.12.2
Server OS:        Windows
Commit id:        629

### Expected behavior
Server spawn should load perfectly

### Actual behavior
I spawn on nowhere. I eventually fall to my death.

### Steps to reproduce the behavior
Drag world files into Cuberite world folder

I made a world spawn offline in Minecraft. I then drag it into the CubeRite world folder. I then start the server and I am not in the spawn. Is this a bug? I really don't want to rebuild a new spawn.

**Comment by bibo38** [comment]
Looks like #3878 .

Also note that Cuberite saves its spawn coordinates in the `world.ini` (see #2702 ). Maybe you didn't delete the `world.ini`, which caused Cuberite to use the spawn coordinates from the old world (because `world.ini` wasn't overridden).

**Comment by Pufflegamerz** [comment]
Ok I'll try that.
