### ISSUE TITLE
cMonster.StringToMobType is not dynamic

### ISSUE THREAD

**Issue by DesCuddlebat** [cuberite/cuberite#4230]
Client version:   (irrelevant but) 1.10.2
Server OS:        (also irrelevant but) Linux
Commit id:        b9fdaf8a942ea2f79e48e3f735ba8916f3364e70

### Expected behavior
Method cMonster.StringToMobType is documented as static, which would be an expected implementation.

### Actual behavior
Method cMonster.StringToMobType actually takes itself as the first argument, therefore is not static.

### Steps to reproduce the behavior
.. do I have to?

**Comment by peterbell10** [comment]
> .. do I have to?

Yes, reproducing a bug is often the most important step. It's best to know exactly how you're trying to call `StringToMobType`.

If you are literally putting something like `cMonster.StringToMobType("bat")`, as you've put in the issue, then this isn't expected to work. The correct calling convention uses a colon (`:`) like this `cMonster:StringToMobType("bat")`.

**Comment by DesCuddlebat** [comment]
Hello,

I am sorry messing this up, got confused by the fact that Lua "static" functions apparently do take a hidden self argument despite being static...? Can't find it very intuitive :D Anyway thanks! Closing, there's nothing of interest really
