### ISSUE TITLE
When you blow up dispensers with TNT, dispencer drops without texture

### ISSUE THREAD

**Issue by Rijenkii** [cuberite/cuberite#4233]
Client version:   1.12.2
Server OS:        Linux
Commit id:        b9fdaf8a942ea2f79e48e3f735ba8916f3364e70

### Expected behavior
Dispenser should drop with texture

### Actual behavior
This
![2018-05-22_19 28 52](https://user-images.githubusercontent.com/5338332/40362321-6285f868-5df6-11e8-8861-81e98c41db59.png)

### Steps to reproduce the behavior
1. Blow up some dispensers with TNT
2. Observe

**Comment by changyongGuo** [comment]
Hi,

This bug is caused by error meta data during create dispenser pickup, I will submit a patch for this.

Best regards
Changyong
