### ISSUE TITLE
Observers always face up

### ISSUE THREAD

**Issue by rijenkii** [cuberite/cuberite#4234]
Client version:   1.12.2
Server OS:        Linux
Commit id:        b9fdaf8a942ea2f79e48e3f735ba8916f3364e70

When placed, observers always face up
![2018-05-22_19 49 14](https://user-images.githubusercontent.com/5338332/40363248-352d2546-5df9-11e8-9306-964d4ea28a7e.png)

**Comment by madmaxoft** [comment]
Observers are not implemented at all in Cuberite (what are they, anyway? :)

**Comment by Bond-009** [comment]
@madmaxoft IIRC They were first added to PE as a proper BUD block and were later added to the Java version.
```
In Java Edition, an observer will detect changes in its target's block ID or data value, or the breaking or placing of a block (i.e. changes in its basic block state, but not its extended/actual block state). This means that changes like the age of crops will be detected, since they are part of the basic block state that is converted to metadata when the world is saved; however, changes such as the shape of a fence will not be detected, since those are part of the extended block state, which is not saved when the world is saved. 
```
Ref: https://minecraft.gamepedia.com/Observer
