### ISSUE TITLE
In the linux, there is a little problem that changing text color

### ISSUE THREAD

**Issue by brother0105** [cuberite/cuberite#4238]
Client version:   
Server OS:        Windows/Linux
Commit id:        
Hello, it is not very serious problem. If i run cuberite in linux, my command text color is changed to previous message's color

### Expected behavior
![image](https://user-images.githubusercontent.com/37765909/41139092-7de0f702-6b20-11e8-830e-819133227f31.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/37765909/41139099-8466c502-6b20-11e8-9473-6332324d98ee.png)

**Comment by Cl1608Ho** [comment]
Imo this is not a bug, it's how the posix terminal works (colors are created by special characters that basically state "color everything in red from now on"). While this can be worked around ha sending a color reset code after every message (and in front of every message as it's done now) I would not recommend this workaround.

**Comment by NiLSPACE** [comment]
Are you sure? We can just add the reset character [here](https://github.com/cuberite/cuberite/blob/757231cc6e777b8f4717d1467ef7efa01c7fde15/src/Logger.cpp#L49-L51) and it's done.

**Comment by peterbell10** [comment]
Looking at the code for `cColouredConsoleListener` it looks like it's already supposed to reset the colours.

https://github.com/cuberite/cuberite/blob/757231cc6e777b8f4717d1467ef7efa01c7fde15/src/LoggerListeners.cpp#L21-L26

If it isn't working properly then it's probably an issue with `cLinuxConsoleListener`.
cLinuxConsoleListener

**Comment by Cl1608Ho** [comment]
Uh oh didn't know that :)
