### ISSUE TITLE
Lilypads displace blocks above them

### ISSUE THREAD

**Issue by csunday95** [cuberite/cuberite#4254]
Client version:   1.12.2
Server OS:       Linux (CentOS7)
Commit id:        06eb5cc70da76f6a95afa9c9a3d692ca39e39a76

### Expected behavior
Lilypad cannot be placed if a block occupies the space above the water upon which it would reside

### Actual behavior
Lilypad is allowed to be placed upon the water and the block above is converted to an item

### Steps to reproduce the behavior
(1) Place a water source block in the ground and break a single block next to it
(2) place a block over the water source block
(3) attempt to place a lilypad from the empty space next to the source block that was broken in step 1 (required to get an angle on the source block)

**Comment by ProjectBM** [comment]
Seems like this is still an issue. 

Can I take a look at this?

**Comment by tigerw** [comment]
Sure, the lilypad handler is in Items\ItemLilypad.h
