### ISSUE TITLE
Players aren't shown in the correct place

### ISSUE THREAD

**Issue by MGlolenstine** [cuberite/cuberite#4275]
Client version:   x.x.x
Server OS:       Linux(RPi2b)
Commit id:        1e014a54dc4a9298b407a83146940cf5118f89a9

### Expected behavior
Player should be shown to other players on the position player is in on their own screen

### Actual behavior
Player is a block and a half lower for other players, than he is on their screen

### Steps to reproduce the behavior
Two players join the game, the "bug" happens right away

EDIT: It got fixed after rejoining, but happens again when another player joins.

**Comment by remy99c** [comment]
Same issue on my arch box.

**Comment by tigerw** [comment]
What client version?

Tentatively closing as manifestation of #3258.
