### ISSUE TITLE
Player Progress will not be saved.

### ISSUE THREAD

**Issue by DanHCraft** [cuberite/cuberite#4284]
Client version:   1.12.2
Server OS:        Windows 10 Build 17134.165
Commit id:        c86722325a4c216f5c6544b4622f9a2220582318

### Expected behavior
After leaving the server the server should write the progress of the player to his .JSON File.

### Actual behavior
After leaving the server the console write:
**Error writing player "DanHCraft" to file "players/4c/ac39e7-e6d9-4173-be8c-206f9078939c.json" - cannot open file. Player will lose their progress.**
After reconnect the progress is loosen.

### Steps to reproduce the behavior
Installed Plugins:
- Core v.15
- ChatLog v.3
- Essentials v.2
- WorldEdit v.0.1.12
- Portal-v2 v.3.0.1

The Server is localhost.
Just connect, do something, leave and reconnect.

**Comment by darekols** [comment]
i did an fresh install and the same problem happen to me.  Solution for this as a creating folder named "players" and then inside it another folder "e3".


![cuberite_folder_players](https://user-images.githubusercontent.com/16227021/44006990-c6fd60ce-9e8d-11e8-9718-8f6148f407a8.png)
