### ISSUE TITLE
support wasm plugins

### ISSUE THREAD

**Issue by unmellow** [cuberite/cuberite#4299]
this might not be possible but what if you could write plugins in wasm then I could use just about any language to write plugins (assuming I compiled the runtimes) and to those that don't know [this](https://webassembly.org/) is wasm

**Comment by bearbin** [comment]
[There are no plans to support any additional plugin languages at present](https://github.com/cuberite/cuberite/issues/734)

**Comment by unmellow** [comment]
but if you support only wasm people can use [this](https://github.com/vvanders/wasm_lua) for lua and you'd only be supporting the one language

**Comment by bearbin** [comment]
That may be true, but it would take a long time to replicate the current plugin API in another language (even if it was only the one) and there is really no advantage to supporting multiple languages, as discussed earlier. Lua is not a difficult language and fits our needs - there is no requirement to share code outside of the Cuberite plugin ecosystem.

**Comment by madmaxoft** [comment]
Not to mention that wasm docs are written in "will be", "will support" etc., giving the impression that it is not actually finished yet.
