### ISSUE TITLE
Why hasn't anyone worked on 1.13-support

### ISSUE THREAD

**Issue by HoiTemmieColeg** [cuberite/cuberite#4304]
I know this isnt an issue but there hasnt really been any news about 1.13 and i want to know whats going on

**Comment by madmaxoft** [comment]
Basically 1.13 is such a big change that it's discouraging anyone from even thinking about it.

**Comment by HoiTemmieColeg** [comment]
oh lol

i kinda wanna help but i dont really know how to code

):
