### ISSUE TITLE
Not exactly cuberite code issue, but at this moment I have no other option to post this issue.

### ISSUE THREAD

**Issue by mich4s** [cuberite/cuberite#4305]
![image](https://user-images.githubusercontent.com/13378121/48122496-01443400-e278-11e8-9d20-347713f219ac.png)

**Comment by Maesto** [comment]
Seems like the SQLServer is down. Does the Cuberite Project need some hosting capacity? I could spare some.

```
ping -c 3 104.41.1.8
PING 104.41.1.8 (104.41.1.8) 56(84) bytes of data.
--- 104.41.1.8 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 38ms
```

**Comment by bearbin** [comment]
The issue is with the SQL server as you suspect. Unfortunately although a new hosting provider is a necessity we also need to do some setup and remediation which I don't think @tigerw has had time for recently. Hopefully he might be able to do some work on it over the Christmas period.

**Comment by Maesto** [comment]
Well my offer stands. Im happy to help. Just tell me. Either here or in the cuberite irc.

**Comment by misaalanshori** [comment]
it seems like this issue is still not fixed, and i couldn't download plugins. are there a mirror or a direct link?

**Comment by misaalanshori** [comment]
or could i just download/clone it from github directly?

**Comment by Maesto** [comment]
Last time I set up Cuberite, i just searched on GitHub directly.

**Comment by tigerw** [comment]
Plugins repo was fixed: https://github.com/cuberite/plugin-repository/issues/43

![Search working](https://user-images.githubusercontent.com/2939130/91097844-57a28280-e658-11ea-85d6-8255b04d6b8c.png)
