### ISSUE TITLE
Lava placed in water

### ISSUE THREAD

**Issue by 837951602** [cuberite/cuberite#4306]
Client version:   1.8.8
Server OS:        Windows
Commit id:        6c3dd41717664c75bf77392dd4a4df3b35678fa5|669

Placing lava in water facing to a solid block makes the pointed space(place where block appear if placing dirt)turn into lava and current place into obsidian.

It only appear in client and fix when relog. For different behavior between client and server
![elava](https://user-images.githubusercontent.com/24836316/49323857-911a8c80-f55d-11e8-852c-d48bbd20c4aa.png)

**Comment by earboxer** [comment]
Yeah, that's a weird bug...

**Comment by 837951602** [comment]
It's not weird at all. Client place while sending packet, and server need to undo the placement if the placing is invalid or undesired
