### ISSUE TITLE
Implement Elytra

### ISSUE THREAD

**Issue by PaulCoral** [cuberite/cuberite#4311]
Client version:   1.8 -> 1.12
Server OS:        Raspbian OS & Ubuntu
Commit id:        6c3dd41717664c75bf77392dd4a4df3b35678fa5

### Expected behavior
Elytra should glide

### Actual behavior
Elytra doesnt glide

### Steps to reproduce the behavior
try to glide with elytra

**Comment by lepaincestbon** [comment]
No?

**Comment by lepaincestbon** [comment]
Any news?

**Comment by tigerw** [comment]
No one working on yet to my knowledge, is this an important feature for you? If so we might be able to prioritise it.

**Comment by lepaincestbon** [comment]
> No one working on yet to my knowledge, is this an important feature for you? If so we might be able to prioritise it.

No, it was just know the state right now, but im not really interested right.
Feel free to close this issue if it is not a priority right now
