### ISSUE TITLE
Memory not freeing

### ISSUE THREAD

**Issue by Athelios** [cuberite/cuberite#4314]
Client version:   1.12.2
Server OS:        Linux
Commit id:        6c3dd41717664c75bf77392dd4a4df3b35678fa5

### Expected behavior

Memory should be freed when chunks unload.

### Actual behavior

Memory only increasing and unloading chunks doesn't free any memory.

### Steps to reproduce the behavior

Download Linux version of Cuberite.
Fly over the world.
Watch memory increasing and not freeing when chunks unload.

**Comment by peterbell10** [comment]
In the World.ini file there should be a setting "UnusedChunkCap" which defaults to 1000.
If you set this to a lower number, Cuberite should be more aggresive about freeing unused chunks.

Does this help?

**Comment by Athelios** [comment]
The "UnusedChunkCap" setting doesn't help. It unloads chunks more aggresive but that's not the problem. The problem is that even when chunks are unloaded they keep memory allocated. I think it is problem with Linux build of Cuberite.
