### ISSUE TITLE
ghast's cannot fly

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#4317]
Client version:   1.12
Server OS:        Mac OS
Commit id:        4f26f653e1ae168a050f3eca3e8073eca3f10367

### Expected behavior
Ghats float around

### Actual behavior
They do not float.

### Steps to reproduce the behavior
Spawn in a Ghat

**Comment by Nikita11790** [comment]
this seems to happen with all flying mobs

**Comment by mathiascode** [comment]
Fixed in #4547
