### ISSUE TITLE
Random explosions of dirt particles above the ground

### ISSUE THREAD

**Issue by Guigui220D** [cuberite/cuberite#4318]
Client version:   1.12.2
Server OS:        Debian 9
Commit id:        7d512f21913b3ed7dee2a025fdc1dea77a08d83b

### Actual behavior
There are random explosions of dirt particules as if someone was breaking dirt blocks, but in random places above the ground in the overworld. I see it every few seconds.
Edit : it also makes the sound of dirt when it's destroyed

### Steps to reproduce the behavior
I just compiled and started the server and it does that on its own.

![2019-03-10_20 58 23](https://user-images.githubusercontent.com/24529384/54090754-e8f43b00-4377-11e9-8bb0-2eb0605b578a.png)
![2019-03-10_20 57 59](https://user-images.githubusercontent.com/24529384/54090755-f01b4900-4377-11e9-933f-6e1d1aca7c38.png)

**Comment by Guigui220D** [comment]
It also makes the sound of dirt being dug

**Comment by mathiascode** [comment]
Weird issue. Happened right next to me twice while fishing.
