### ISSUE TITLE
port wont change

### ISSUE THREAD

**Issue by x35gaming** [cuberite/cuberite#4327]
Client version:   1.12.2
Server OS:        Kubuntu 18.04
Commit id:        6c3dd41717664c75bf77392dd4a4df3b35678fa5 built at: Mon Oct 15 16:57:50 UTC 2018

when i change ipv4 ports to`4500` it goes back to `25565`
### Steps to reproduce the behavior
* go to your server webadmin
* go to core>server settings
* change ipv4 ports to your desired port

**Comment by krankenbyte** [comment]
+1, faced as well, investigated, turns out webadmin writes `port=` to the config instead of `ports=`
