### ISSUE TITLE
End portal block entity

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#4334]
Client version:   1.12.3
Server OS:        All
Commit id:        24a8456f79aa35cfe8c3859c880e1bffeae088c6

End portal blocks need an associated block entity, otherwise they are invisible to clients.

Related: #4126

**Comment by mathiascode** [comment]
Probably the same case for enchantment tables. The book disappears when relogging.

**Comment by tigerw** [comment]
End portals need block entities now? Interesting; what sort of state do they have?

**Comment by peterbell10** [comment]
Enchanting table has a custom name field in the block entity:
https://minecraft.gamepedia.com/Enchanting_Table#Block_entity

End portal doesn't have anything stored...
https://minecraft.gamepedia.com/End_Portal_(block)#Block_entity

**Comment by tigerw** [comment]
Thanks!
