### ISSUE TITLE
Request: Implement v8 engine support.

### ISSUE THREAD

**Issue by nathan130200** [cuberite/cuberite#4339]
Cuberite will support Javascript engine for plugins? Lua is too old...

https://chromium.googlesource.com/v8/v8.git
https://v8.dev/docs/embed

**Comment by madmaxoft** [comment]
It will not. The discussion has been going over and over, there's no advantage.

**Comment by nathan130200** [comment]
This is a joke right? For me it means three things, they do not know how they will implement, even laziness, or the code is polluted to the point that it can not be changed without something break... But bye!

**Comment by madmaxoft** [comment]
Just search the forum for the discussions about this, I'll try to sum things up very short:

Probably the biggest arguments against supporting multiple languages for plugins is the maintenance cost. We're already stretched thin just on keeping the server barely alive, not to mention on par feature-wise with Vanilla. There's no manpower to keep multiple API implementations in sync.

It might not see like it, but actually implementing bindings to another language is a lot of work, and I mean A LOT. Have a look at the Bindings folder in the sources: https://github.com/cuberite/cuberite/tre...c/Bindings - that's just a tip of what has to be done for one language. There's a lot of other supplemental code that generates some glue code automatically, and an enormous amount of thinking went into how to properly interface things. Thread safety and callbacks are just a small example of all the hurdles that needed to be overcome.

What benefits do you see from bringing another language into the mix? The community has been happy with Lua for quite some time, and calling Lua "too old" or "not performant" is really out of place - it is still the most used scripting language for gamedev, it is very actively developed yet still has an API that is both powerful and stable.
