### ISSUE TITLE
Can't download any plugin from official website

### ISSUE THREAD

**Issue by Xayanix** [cuberite/cuberite#4350]
As above, MySQL error.

**Comment by tsarevpp** [comment]
I got the same error just yesterday. You might have more luck by downloading from the forum!
https://forum.cuberite.org/forum-2.html

**Comment by tonibm19** [comment]
hi admin

you hope you doing well

thanks for contacting me

i really was a wonderfull day on your office

i hope we can talk together again

vanessa

**Comment by madmaxoft** [comment]
Workaround: Most plugins listed on the website have a GitHub repo, so you can download from there.

@tigerw We really need you to either fix this, or disable the plugins site altogether.

**Comment by tigerw** [comment]
ok ok

**Comment by tonibm19** [comment]
* Google!

Hi

thanks for join us!

Reg Google

**Comment by tigerw** [comment]
what's with the deleted comments

**Comment by peterbell10** [comment]
Their email is spamming e.g. https://github.com/cuberite/cuberite/pull/4398#issuecomment-534618484

**Comment by mathiascode** [comment]
I'm in favor of disabling plugins.cuberite.org altogether. One less service to worry about, and doesn't seem like there is much interest in this.

**Comment by madmaxoft** [comment]
Until we get a more reliable plugin repo, disabling the current site would be preferred, from my point of view.

**Comment by mathiascode** [comment]
Is the repository stable enough to be pushed in favor of the forum section again? I appreciate all the work, but a two year outage period is a bit unacceptable.

**Comment by bearbin** [comment]
Not casting any judgement on replacing the plugins section of the forum with the repository or not; but this issue as written is now resolved.

**Comment by tigerw** [comment]
It's not stable enough yet, and the good user feedback received haven't all been implemented.

I would recommend going back to listing it as Plugins Repo (Beta).

**Comment by madmaxoft** [comment]
It seems the site is down now.

@tigerw how shall we report failures to you?

**Comment by bearbin** [comment]
There is an email forward set up for the pluginrepo at `plugins` with the relevant domain for the project.

**Comment by tigerw** [comment]
We'll work out all of the bugs eventually. This one was caused by an unexpected squeely port change.
