### ISSUE TITLE
Starting Cuberite without a input stream

### ISSUE THREAD

**Issue by javaarchive** [cuberite/cuberite#4355]
Client version:   12.2.2
Server OS:        Linux(forgot to add)
Commit id:        9dc1343bda0592f2d27bb216eb21fdec97f73945

### Expected/Actual behavior
Apparently, when the server starts, it runs everything without an input stream. This results in Cuberite closing immediately. 
![image](https://user-images.githubusercontent.com/20248577/61832306-8e8ae100-ae25-11e9-8ea6-778901d4f7f8.png)
I have confirmed this by adding the line `read -p "Press enter to continue"` after the line that executes Cuberite, this line has no effect and the end of the batch file still executes. 
Is there any way to start Cuberite so that it ignores the input stream without `-d`?
### Steps to reproduce the behavior
Remix my code at https://glitch.com/~lightweight-mc
Then check the logs

**Comment by tigerw** [comment]
The server assumes that someone pressed Ctrl+D to indicate end-of-transmission when the input stream closes, so starts shutting down.

What's hosting Cuberite in this image? It might be possible to add some sort of workaround, but without input how does it indicate the server to cleanly shut down?

**Comment by ePirat** [comment]
> It might be possible to add some sort of workaround, but without input how does it indicate the server to cleanly shut down?

You can do that by handling SIGINT and do the graceful shutdown when that signal is received, no?

**Comment by tigerw** [comment]
Sure, that probably happens already. I was just curious what the host was and what it specifically is doing.

**Comment by javaarchive** [comment]
From my expirence with hosting other applications on glitch.com, applications are usually stopped with signals. I am not sure which signal is used, but the signal works for most web applications.

**Comment by javaarchive** [comment]
There might be some way to create "fake" input stream before running cuberite in the bash script as a workaround, but starting cuberite without an input stream may never be implemented, because it is not necessary for most people since most users will run it directly from their terminal.
