### ISSUE TITLE
Refactor TakeDamageInfo::FinalDamage to float

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#4357]
Currently, `TakeDamageInfo::FinalDamage` is an `int` and calculations with it are imprecise (often using `*= 1.5` etc. in damage calculations). It would be best if the damage was represented as a `float` instead, and only when finally applied to an entity, it was rounded to an `int`.

**Comment by Aplaus228** [comment]
it seems like a good first pool request.
I can try to do this.
