### ISSUE TITLE
Errors in source....

### ISSUE THREAD

**Issue by crazybytes** [cuberite/cuberite#4369]
hMods = (HMODULE*) malloc( sizeof(HMODULE) * (TTBUFLEN / sizeof HMODULE) );

????????????????

changed to:

hMods = (HMODULE*) malloc( sizeof(HMODULE) * (TTBUFLEN / sizeof( HMODULE)) );

What is this?

**Comment by madmaxoft** [comment]
The WinStackWalker source is adapted from a [different project](https://github.com/JochenKalmbach/StackWalker), by the time it was used it was just an article on CodeProject. None of us know or care how exactly it works, we only modified it slightly to match our source code formatting and removed some unnecessary stuff.

**Comment by crazybytes** [comment]
Ok. I compiled it under Ubuntu (windows powershell..) and it went ok.
But then i have an unix executable.
I have cross compiler under Ubuntu for compiling ffmpeg with a script that
does the thing, but i don't know how to use it for other apps.
But windows is diff.
I use also mingw and cmake. I tried some options from forums but nothing.
Maybe its a diff. mingw32 compiler i am using (seh version), so i try other.
I'm interested in the source because i am working on some nbt code (.mca
region files Minecraft) for reading and writing .mca region files, nbt
files, chunks etc.
So if you know something about how to compile with mingw under windows
please let me know. Because my other stuff (large source code program) is
also working with it, and i like to integrate some stuff....
Thanks for your reaction.
Gerard.
Closed.


Op di 13 aug. 2019 om 02:53 schreef Mattes D <notifications@github.com>:

**Comment by crazybytes** [comment]
Ok. I put -fstack-protector to the linker flags in cmake-gui. The stack
errors are gone.
Now i work on undefined reference to `GetFileVersionInfoSize' and some
other...
Just letting you know. Maybe you can put it in the compiler info.

Op di 13 aug. 2019 om 12:12 schreef Gerard Wensink <gerardwensink@gmail.com

**Comment by crazybytes** [comment]
dd to linker flags......
-lversion

Now only left is:
undefined reference to `GetAdaptersAddresses'
Let you know when found...

**Comment by crazybytes** [comment]
Add to linker flags...

Op di 13 aug. 2019 om 12:45 schreef Gerard Wensink <gerardwensink@gmail.com
>:

> dd to linker flags......
> -lversion
>
> Now only left is:
> undefined reference to `GetAdaptersAddresses'
> Let you know when found...
>
