### ISSUE TITLE
Seen this one before...

### ISSUE THREAD

**Issue by crazybytes** [cuberite/cuberite#4370]
Compiled under Ubuntu, no problem. Everything works.
Compiling under window with Visual Studio also works of course.
Bill Gates owns GitHub, owns, Minecraft, and owns Windows....and Visual Studio.

But with cmake/mingw compiler, you need to adapt code, change some pointers, brackets, add some libs etc etc etc, then 

when it compiles, i seen this thing before, 

BUT NOTHING WORKS. 
Because you need Visual.... And buy it, from Bill, otherwise you will and cannot compile a c program under windows that works, then you get this:

https://drive.google.com/open?id=1yYRBTv-65RAJ5DR9uF27_ohgTFQfmE23

**Comment by crazybytes** [comment]
Like 95% of GitHub won't work on windows.

You know how to cross-compile your thing under Ubuntu, for windows?
(Blah blah, check the net, get lost in the jungle... bye)

**Comment by crazybytes** [comment]
What a about a fine source code project on GitHub, owned by Microsoft, that has 95% of source codes, that won't work with free compiler. 

So everybody is using Visual eh?

Because its 'free', like msdos. 
Then 20 years later you have 'free' os that is like a unprotected target for abuse, and nothing works, you have to buy a compiler. Because windows makes others out of competition.

because 95% of all sources don't compile with mingw under windows, or you have to fool around for  2 weeks to get the job done.

Why not a menu, or list, with need this, do that, under windows,

AND THEN IT JUST WORKS FINE!!!!!!!!!!!!!!!

Tell me why it is not that way.
You work for bill gates? 

I can not compile your program with professional compiler (free) under windows.

your just a set of commercial bastards filling this commercial system with this source.
so you work (or are) for the devil.

So, make it compile under windows!!! With free compiler, which is good and fast.

If all your programmers who worked on this shit can realize a working source code object on github that works with mingw/cmake, 

your a bunch of loosers.

https://drive.google.com/open?id=1yYRBTv-65RAJ5DR9uF27_ohgTFQfmE23

Here is the devils mark.

Should say "Error 666"

**Comment by crazybytes** [comment]
Now:

Check the internet for the solution.

And spend doing that your time forever.

**Comment by crazybytes** [comment]
Because, like windows is a black box, nobody knows whats in it. Even not Bill Gates himself, so he's not to blame.

but visual is also a black box! No source code available. So you never know what it produces......
Maybe some product is created that works.
But maybe it works 'to good', you understand?

**Comment by ForTheReallys** [comment]
Maybe instead of calling it the "devil's mark", you could try to submit a patch?

**Comment by madmaxoft** [comment]
You may want to hold off the alcohol before posting on GitHub.

From your inconsistent blabbering I figure you have problems compiling on Windows, and you're avoiding MSVC. True, that's a scenario we haven't tested yet, so perhaps there are problems. But we would need a sober description of the problem, with exact error messages (and possibly their translations to English). If it compiles fine but doesn't run, I suspect problems with the compiler setup. Does a simple "hello world" compiled by that compiler work?

One possible culprit that could be responsible for mystery failures is if the compiler used a C runtime that limits the thread stack space, we've seen that with people who try musl instead of glibc on Linux. Cuberite is rather demanding on thread stack space (need to fix that).

**Comment by crazybytes** [comment]
I found the issue.

Besides some changes in code, and adding some usual dll,s

it needed libssp-0.dll also.
Found out by accident. When path to dll dir was set it suddenly worked. Starting from windows did not have the path set.

but windows or program shows not the standard dll missing error. but a vague one......

**Comment by crazybytes** [comment]
-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32  -lssp -lversion -liphlpapi

-fstack-protector

added. 
and used extra dll. against the vague 0x00000000a error...

libssp-0.dll

And changed some code and errors in code like sizeof something, instead of sizeof(something)

Must be bug in unix.....
