### ISSUE TITLE
Cuberite adapted (bugs/pointer decl./float conversion)

### ISSUE THREAD

**Issue by crazybytes** [cuberite/cuberite#4371]
Compiling under linux goes ok. 
But not for mingw.
So code adapted, and cmaked/compiled(64bits).
Ready for codeblocks.

The cuberite converted: https://github.com/crazybytes/CUBERITE-MINGW
The cuberite converted: https://github.com/crazybytes/CUBERITE-MINGW
The cuberite converted: https://github.com/crazybytes/CUBERITE-MINGW

See also https://github.com/crazybytes/PACMAN-CUBERITE on how to integrate into other sources.

Also take a look at a memory leak finder for playing with nbt file structures from 
https://github.com/IDidMakeThat/libnbt
changed to:
https://github.com/crazybytes/MCA-NBT-EDIT

**Comment by madmaxoft** [comment]
This is worthless, please either provide a pull request, or stop bothering us with incoherent rants.

**Comment by crazybytes** [comment]
O really? Well, i'm so sorry to hurt your feelings as it seems.
Pull request? I don't know what it is.
Maybe i look into it sometime, or somebody could help me telling me (with a
non-negative attitude) what to do.

Or you are visual-c reseller for ms?

Op vr 16 aug. 2019 om 09:54 schreef Mattes D <notifications@github.com>:

**Comment by crazybytes** [comment]
Maybe you can do it for me? I'm not so good at working together with
negative people.

Op vr 16 aug. 2019 om 10:05 schreef Gerard Wensink <gerardwensink@gmail.com

**Comment by madmaxoft** [comment]
You obviously know how to work with git, so you're most of the way there, already. Fork the Cuberite repository here on GitHub, then make your changes to it using your normal git + compiler combination. After committing and pushing the changes to your fork, you can open a pull request directly from GitHub.

**Comment by crazybytes** [comment]
Ok. Thanks. I will get into that.

Op ma 19 aug. 2019 om 12:01 schreef Mattes D <notifications@github.com>:
