### ISSUE TITLE
Get a list of all item types

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#4372]
For the upcoming 1.13 compatibility, we'll need a list of all the item types currently in the game. Later on, this list shall be turned into an ItemTypeRegistry, just like the blocks in the BlockTypeRegistry: https://github.com/cuberite/cuberite/blob/9a1ed26893e51aa693bc61602ce9555d04789800/src/Blocks/BlockHandler.cpp#L714-L1390

For now, only the list of item types in the simple format below is sufficient, linked as a gist.
```
...
minecraft:iron_boots
minecraft:iron_sword
...
```

Use the minecraft wiki or the server generators ( https://wiki.vg/Data_Generators ) as the source for the data.

**Comment by Aplaus228** [comment]
I would want to do it.

**Comment by madmaxoft** [comment]
Alright, it's yours. If you use a script of some kind to process the data from the Generators to the final form, perhaps link to a gist of that script, too, so it can be used next time after a major change.

**Comment by Aplaus228** [comment]
I don't know  I done its correct or not I just parsed item.ine and wrote all [item](https://github.com/Aplaus228/item/blob/master/Items.txt) to other files.
If I have done it wrong pls give me advise for the correct way.

**Comment by madmaxoft** [comment]
Unfortunately no, items.ini is written by us and for some items the names are wrong. Also, it doesn't contain the new 1.13 and 1.14 items. You'll need to use either the minecraft wiki or the generators as the source, since those are the only reliable source of full item list.
The output format you produced is exactly what we want, only the contents are wrong.

**Comment by Aplaus228** [comment]
I run the server as"java -Xms1G -Xmx1G -jar server.jar reports Item List" and server just run.
how I understand when I ran the server how above it creates reports/item.json, but in me not. 
how correctly can I run the server for this purpose?

**Comment by NiLSPACE** [comment]
I created this: https://gist.github.com/NiLSPACE/1d81efb06b63a0e14fe3978bf72a5eaf

Method: execute
```js
new Array(...document.querySelectorAll("#minecraft_items em"))
.map(x => x.innerText)
.filter((value, index, self) => self.indexOf(value) === index)
.join("\n")
```

on https://www.digminecraft.com/lists/item_id_list_pc.php

**Comment by madmaxoft** [comment]
How much do we trust that webpage to provide complete and correct data? I'd have preferred using the Generators, but am willing to accept this if you vouch for them.

**Comment by NiLSPACE** [comment]
I've never heard of them. I just googled for Minecraft 1.14 item list.

**Comment by Pokechu22** [comment]
Information on data generators: https://wiki.vg/Data_Generators

You need to run the server with `java -cp minecraft_server.jar net.minecraft.data.Main`.

**Comment by Aplaus228** [comment]
here the list of all [items](https://github.com/Aplaus228/item/blob/master/allItem.txt).
I ran Mojang and parse all item from all files.

**Comment by madmaxoft** [comment]
Thanks, @Aplaus228 , could you also provide the script you used for the parsing? So that when the next Minecraft version comes out, we can re-apply it.

**Comment by Seadragon91** [comment]
@madmaxoft I also took a look and it's not that easy. The file from @Aplaus228  is missing the item `minecraft:acacia_leaves` for example.

**Comment by Seadragon91** [comment]
@Aplaus228 The correct file to be parsed is `registries.json` in `generated\reports`. There is a key named `minecraft:item` and this should contain all items. I oversaw that file...

**Comment by Aplaus228** [comment]
@Seadragon91 
I Don't Know-how to correctly run the server I have taken the server from  https://www.minecraft.net/en-us/download/server/ and just run I was trying run server with different ways but nothing happened,
also I have never seen generated\reports in my own directory.

**Comment by Seadragon91** [comment]
If you only want the reports from the server. Run this command
`java -cp server.jar net.minecraft.data.Main --reports`
For everything:
``java -cp server.jar net.minecraft.data.Main --all``

You can then find the file `registries.json` in folder `generated\reports`.

**Comment by holysh1t** [comment]
I made a little python script: https://gist.github.com/holysh1t/3e5267aa9d15cc2c43d01992cffb6e0b
Its rudimentary but it works, just give the server.jar url as a command line argument and it will generate a items.txt with all items in the requested format. (wget, Java and... Python required)

**Comment by madmaxoft** [comment]
@holysh1t Could you post the resulting file as well?

**Comment by holysh1t** [comment]
@madmaxoft sure: https://gist.github.com/holysh1t/98134746596b35dbbf90aac642db1644

**Comment by Seadragon91** [comment]
I think it would looks better if the items are sorted: `items.sort()`

**Comment by holysh1t** [comment]
@Seadragon91 https://gist.github.com/holysh1t/f1483fdb1ad84621ec6693a2825e6cb4

**Comment by tigerw** [comment]
Thanks!
