### ISSUE TITLE
Faster Appveyor builds

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#4378]
Currently the Appveyor builds take between 15 and 30 minutes (increased substantially since the upgrade in fcc836f2a5ca39a68aa60c7fb0fa637044a5346b). Most of the time is spent in the cmake configuring phase, when cmake tries to detect various headers, macros etc., mainly for libEvent.

It might be possible to improve build speed either by providing the relevant entries on the command line, or by pre-populating the cache.

**Comment by peterbell10** [comment]
Wait, does cuberite now require VS2017? Any chance of bumping the standard as well?

**Comment by madmaxoft** [comment]
Cuberite itself doesn't require VS2017, but the tests currently do. There was a weird error regarding `initializer_list` in the test (and I suppose it would have occurred later on in the main code as well):
https://ci.appveyor.com/project/madmaxoft/mcserver/builds/26917859#L777

I already bumped the standard to C++17 in #4377 , at least in the PBA tests (so that I can use structured binding for returning multiple values from a function.

**Comment by madmaxoft** [comment]
So we can't bump the standard right now due to the cross-building tools for raspberry pi on the build server. I'm removing the C++17 features from the PR.

**Comment by madmaxoft** [comment]
We could probably move back to MSVC2013, thus run on the faster Appveyor infrastructure.

**Comment by peterbell10** [comment]
If you're already switching things around then it might be the time to move to VS 2015. See #4031

**Comment by madmaxoft** [comment]
Could be. I think the Appveoyr worker VMs do have VS2015 together with VS2013, so it could be the same (faster) VM than the VS2017 one. I probably won't be switching things around much, I just tried to use some C++17 features and failed :)

**Comment by madmaxoft** [comment]
The builds could be made much faster if we used a build cache. The LibEvent project uses it successfully, so it could probably be adapted from there: https://github.com/libevent/libevent/blob/master/appveyor.yml
