### ISSUE TITLE
found bug.

### ISSUE THREAD

**Issue by Wr0ngPass** [cuberite/cuberite#4380]
Client version:   1.12.2
Server OS:        Windows
Commit id:        74579fbadf0f89154cba5d9157a57f59fcda8f70

### Expected behavior
1. Mob AI is very well, dont work correctly..
Ghast not flying, ender dragon too, villager is not trade and not spawn on the world,
2. Spawn eggs not working, tnt is not working correctly. 
3. Sound when skeleton take you damage played is not correctly.
4.  player does not hear when damage another player. 
5. village spawning empty.
6. When i damaged anithing neutral mobs, his not running.
7. golden apple and potion is not working.
This topic started.

**Comment by Wr0ngPass** [comment]
8. eye of ender not working.

**Comment by Wr0ngPass** [comment]
9.Powered rails is not working correctly.

**Comment by Wr0ngPass** [comment]
10. elytra not working.

**Comment by Wr0ngPass** [comment]
11. Boat is not working correctly.

**Comment by madmaxoft** [comment]
Yes, we know. Please check the forum first for the list of known issues.

**Comment by Wr0ngPass** [comment]
> Yes, we know. Please check the forum first for the list of known issues.

Okay, how i can help us?

**Comment by Wr0ngPass** [comment]
ohh. i can spawn fire in the air :D

**Comment by Titaniumtown** [comment]
should this issue be closed?

**Comment by mathiascode** [comment]
Might as well. Some of the mentioned issues are solved, but if the remaining ones are important, they should be split into new, separate issues.
