### ISSUE TITLE
Chunk generator creates different data on different platforms / build-types

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#4384]
While implementing #4382 it by chance became obvious that our default Nether generator generates different data in Debug and Release builds on Linux. We need to find out why and fix it, the assumption has always been that the generator is platform- and build-type-independent.

As the first step, a new test needs to be made to check the generators, how many of them are affected. Then, fix all those that fail the test.

**Comment by madmaxoft** [comment]
It seems that Linux Release builds are the ones that produce different chunk data than all the others (Win Debug, Win Release, Linux Debug). At least it's reproducible on my Linux as well, so I can attempt to fix it.

**Comment by madmaxoft** [comment]
Houston, we have a problem. This arises due to undefined behavior in `cNoise`, it uses signed-integer arithmetic and yet it depends on overflows (which the C++ standard says are undefined behavior) [1].

Fixing this properly would most likely result in changing ALL terrain generation. Not sure if we want that - so far we've managed to never change generation as long as the generator settings are the same.

[1]: https://stackoverflow.com/a/16188846/4084740

**Comment by madmaxoft** [comment]
I managed to find a workaround, but still would like to fix this properly one way.

**Comment by peterbell10** [comment]
Could you do the arithmetic in `unsigned` (for which overlow is well defined) and then cast to `int`?

**Comment by madmaxoft** [comment]
That would be the proper fix, but I'm not sure whether it would change the current generation, or not.

**Comment by madmaxoft** [comment]
Moved the more general issue to a separate issue, this one will be closed when the generator hotfix is merged.
