### ISSUE TITLE
Crash server with large chat message

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4409]
### Expected behavior
Server should kick the client for trying to send a to large chat message or packet .

### Actual behavior
Server crashes.

### Steps to reproduce the behavior
Use that [python script](https://github.com/Seadragon91/pyCraft/blob/ddos_commands/run_chat_message.py)  with pycraft, don't forget to switch off `Authentication`.

**Comment by Seadragon91** [comment]
Looks like there are a other few issues that have the same error
`Verification failed: m_Out.WriteVarUTF8String(a_Value), file /home/lukas/cpp/cuberite/src/Protocol/Packetizer.h, line 118``

Issues: #4337 and #4323

**Comment by madmaxoft** [comment]
Good job analysing this.
