### ISSUE TITLE
Piston's handle can be destroyed seperately from the piston itself

### ISSUE THREAD

**Issue by 91khr** [cuberite/cuberite#4418]
Client version:   1.12.2
Server OS:        Windows
Commit id:       83013d19ca77f8ff736ed7b9e85d2c7b3250476a

> English is not my native language, please excuse typing errors.

When I tried to remove a redstone machine using TNTs, I found that an activated piston was without its handle.

### Expected behavior

When the handle of a piston is destroyed, the piston will also be destroyed.

### Steps to reproduce the behavior

1. Put a piston and activate it;
1. Put a TNT and surround it with stones to reduce explosion power;
1. Activate the TNT to destroy the piston's handle.

**Comment by madmaxoft** [comment]
This should be fixed when #4417 gets merged.

**Comment by 91khr** [comment]
Thanks.

**Comment by tigerw** [comment]
Tracked in #3863.

**Comment by tigerw** [comment]
Ref #4845.
