### ISSUE TITLE
Host API docs on Github Pages

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4425]
It could be interesting to see if we can host the API docs (https://api.cuberite.org) on Github Pages, instead of relying on the current hosting method (HTTPS proxy to another server if I remember correctly). A potential way would be to utilize Travis to push the contents of APIDump's API folder to another repo on Github, which has Github Pages enabled.

Rough example/idea: https://stackoverflow.com/questions/51925941/travis-ci-how-to-push-to-master-branch

**Comment by madmaxoft** [comment]
I don't see a reason why. The current solution works fine (and it allows me to add more files to the webhosting, such as the list of undocumented symbols for API checking). GH pages is primarily meant for webpages that store their history in git; we don't need the history, so storing in git is pure waste.

**Comment by mathiascode** [comment]
Fair enough, no need to change a workflow that works.
