### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by lukacat10** [cuberite/cuberite#4435]
Client version:   1.12.2
Server OS:        Windows
Commit id:        approx: fb2ef33c89e40e66365db7642bfa06258a61d5ab

### Expected behavior
A working server

### Actual behavior
Server crashes while running idle with a player connected, not moving at all and not interacting.

### Steps to reproduce the behavior
Not sure how easy it is to reproduce

This occurred while debugging, which gives me the opportunity to dive into what exactly caused the issue.

The error occurred in cIncrementalRedstoneSimulatorChunkData:
File RedstoneSimulatorChunkData.h @ line 18
The line itself is very basic:
`m_ActiveBlocks.push_back(a_Position);`

Just wanted to mention that no redstone was ever used in the server.

The error is:

> 0xC0000005: Access violation writing location 0x000000000000000C.

When diving into the internals of the vector, it occurred in the implementation of vector @ line 638, which failed to construct something, due to garbage value in the Vector3 provided.

I haven't modified the Cuberite code yet. This exception occurred while running the original code from the master branch.

I saved the dump, and will share it if needed.

**Comment by Seadragon91** [comment]
This looks similar like issue #4402

**Comment by lukacat10** [comment]
Yea, it is the same, thanks
