### ISSUE TITLE
Feature tracker

### ISSUE THREAD

**Issue by hmlendea** [cuberite/cuberite#4441]
It would be nice if there was a feature tracker, where we could see a list of vanilla Minecraft server features, and whether they are fully implemented, partially implemented, or not implemented at all in Cuberite.

**Comment by madmaxoft** [comment]
There's a very rough feature comparison at https://wiki.vg/Server_List ; if you want more fine-grained, we first need the actual list of features that should be considered, then we can fill such list out with yes or no.

**Comment by hmlendea** [comment]
Thanks, it's good enough as is, at least for me.
I was interested what entities / items / features were missing and it seems that that info is already there. So it seems to me like this is a pre 1.9 version of Minecraft.

I think this issue can be closed.
