### ISSUE TITLE
Connections time out in Android 9+

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4457]
Investigate why connections to the server (Webadmin included) time out on some Android 9 and Android 10 devices.

**Comment by Cl1608Ho** [comment]
This is pretty surely because of battery "optimizations" on the device, google's been encouraging optimizations which might limit phone functionality for the past years and vendors are increasingly overshooting the target. The only reliable exception are apps which use the google cloud platform, simply because google is whitelisting that. I don't see much that can be done on our side.

**Comment by mathiascode** [comment]
Doesn't explain why MCServer or a simple webserver outside Cuberite works just fine. Cuberite binds to the ports, there's just no data being transmitted. I think there are most likely issues in Cuberite itself, possibly related to some libs.

**Comment by mathiascode** [comment]
I just attempted to run Cuberite in a Termux terminal. Same issue.

**Comment by madmaxoft** [comment]
Could it be related to http vs https?

**Comment by mathiascode** [comment]
I don't think so. All incoming TCP connections seem to be affected. UDP connections work fine.

**Comment by KiralyCraft** [comment]
I stumbled across this as well. It looks like it doesn't listen on TCPv4 ports. I'm running LineageOS 16.0. Attaching screenshots:

https://imgur.com/a/fbnZeWL

**Comment by mathiascode** [comment]
Removing these lines simulates the issue on other devices. https://github.com/cuberite/cuberite/blob/master/src/OSSupport/TCPLinkImpl.cpp#L155-L156

**Comment by mathiascode** [comment]
Worth investigating: https://github.com/cuberite/cuberite/blob/be1f06520ca6fb0c1f804c81d55858a57d3b86e6/src/OSSupport/TCPLinkImpl.cpp#L315-L338

**Comment by mathiascode** [comment]
@KiralyCraft Doesn't seem to be the issue. I forced Cuberite to bind to TCPv4, still doesn't accept connections.

**Comment by mathiascode** [comment]
Not even cServerHandleImpl's Callback is firing... Everything seems to work as normal when binding ports, netstat output looks the same on a working and non-working Android device, but absolutely nothing seems to come through from clients.

**Comment by tigerw** [comment]
libevent bug?
