### ISSUE TITLE
random lag invisible players chat not sending

### ISSUE THREAD

**Issue by Zeenjayli** [cuberite/cuberite#4461]
Client version:   1.12.2
Server OS:        MineOS Turnkey(current)
Commit id:        (Found at the top of the server's console output)

### Expected behavior
all players should be visible as no mods or anything to make players invisible used.
when a connected player outside the LAN types message in chat, it should be received near instant to the server and relayed to other clients in and outside the LAN

### Actual behavior
players will randomly be invisible based on who joined last or all visible when someone new joins.

(based on 2 players in instance alone than 3rd joining)
if one would leave and reconnect the older client would be visible to the newer but not the same for the older client who was now unable to see the newest client, when 3rd person joined mega lag but everyone was now visible to each other (have not had any more clients joint to further)

### Steps to reproduce the behavior
I am unsure this does not seem normal behaviour for the standard settings I have it's a mostly fresh server. the only thing is I'm running MineOS Turnkey not windows and it constantly is unable to tell if the cuberite server is online or not and how much ram it is using

**Comment by mathiascode** [comment]
The invisible player issue should be fixed. If you still experience the other issues, open separate bug reports for them.
