### ISSUE TITLE
TNT misbehaving

### ISSUE THREAD

**Issue by Zeenjayli** [cuberite/cuberite#4462]
Client version:  1.12.2
Server OS:        MineOS Turnkey (current)
Commit id:        (Found at the top of the server's console output)

### Expected behavior
TNT explodes in water without causing block destruction and launches the player

### Actual behavior
TNT explodes but causes block destruction

### Steps to reproduce the behavior
make a 3x3 area with water covering the inside, dispense TNT into the inside edges

**Comment by maxluchterhand1** [comment]
X X X                   X X X                     X T X
X X X          ->     X W X             ->    T W T 
X X X                   X X X                      X T X

 
                               Water                  TNT into
3x3 Area    ->       covering        ->     "inside 
                               inside                    edges"


Is this what you mean? I assume not, and if not, please provide a more clear explanation on how to reproduce this behaviour.

**Comment by maxluchterhand1** [comment]
I don't quite understand how to reproduce this behaviour. 
3x3, or do you mean 3 x 3 x 3?
Water covering the inside? Do you mean like, water in the middle?
What are "inside edges"
