### ISSUE TITLE
the world went something wrong

### ISSUE THREAD

**Issue by issac4892** [cuberite/cuberite#4465]
Client version:   x.x.x
Server OS:        Rasberrypi(Ubuntu Server)
Commit id:        f5af0e2e04317f75d2eef2427b1abe73c0f13d29

### Expected behavior
the blocks are not right(ex. when i place tnt it becomes a water0

### Actual behavior
the right blocks(i downloaded lots of time, and also i tried to build it by my self)

### Steps to reproduce the behavior
![Uploading image.png…]()

**Comment by tonibm19** [comment]
Welcome to Google!

Hi

thanks for join us!

Reg Google
