### ISSUE TITLE
Cuberite executable is missing after compile script

### ISSUE THREAD

**Issue by BraydonKains** [cuberite/cuberite#4470]
Client version: N/A
Server OS: Linux, Fedora 31
Cuberite Commit id: (Found at the top of the server's console output)

### Expected behavior
The Cuberite executable is in the Server directory after running a release build through compile.sh

### Actual behavior
The Cuberite executable is missing

### Steps to reproduce the behavior
I didn't do anything other than run the compile script and then re run it to verify. I ran a release build with 2 compile cores. 

### Server Log
N/A

Cloning and compiling manually worked fine, so this bug is likely something to do with the compile script.

**Comment by mathiascode** [comment]
Is the executable in ./build-cuberite/Server? The behavior was recently changed to create separate Server folders with executables for every build directory, but it seems like we forgot to update the compile script to display the correct path.

**Comment by BraydonKains** [comment]
Thanks @mathiascode! Since compiling it myself works fine I haven't checked, but I imagine the behavior of the script and the output being different is an issue regardless. I can verify next time I am at my server machine.
