### ISSUE TITLE
Crops don't grow underground.

### ISSUE THREAD

**Issue by Greaper88** [cuberite/cuberite#4492]
Client version: 1.12.2
Server OS: Windows 7
Cuberite Commit id: 5a2163d7e6ffa0c5c568be41257fb726d452b3b9

### Expected behavior
Planting crops underground in farmland with semi-adequate lighting allows for crops to grow, albeit slowly.

### Actual behavior
Crops will not grow, but will instead "decay." The planted seeds will disappear, but no seeds will be dropped.

### Steps to reproduce the behavior
Place a dirt block in a cave, farm it, put some water and a torch next to it. Seed should grow, but does not.

### Server log
```
N/A
```

**Comment by maxluchterhand1** [comment]
Hey, I tried to reproduce this, however my crops grew just fine underground with a torch beside them. Compiled the server on Linux, using game version 1.12.2

**Comment by peterbell10** [comment]
Maybe a case of the lighting not being updated?

**Comment by Greaper88** [comment]
Looks like it was quietly fixed.... LOL. or inadvertently fixed by something else. I had 3 other players on my server observing the lack of growth. Now the crops are growing.

**Comment by bearbin** [comment]
That sounds like it was indeed a case of the lighting not being updated somehow.
