### ISSUE TITLE
HOOK_BLOCK_TO_PICKUPS doesn't provide the Digger parameter

### ISSUE THREAD

**Issue by nikkedoy98** [cuberite/cuberite#4499]
Client version: 1.12.2
Server OS: Linux (5.6.0-2-MANJARO)
Cuberite Commit id: 5a2163d7e6ffa0c5c568be41257fb726d452b3b9

### Expected behavior
Item is delivered to inventory when block is broken by player while using this callback:
```
function GiveItems(World, Digger, BlockX, BlockY, BlockZ, BlockType, BlockMeta, Pickups)
	if Digger:IsPlayer() then
		Digger:GetInventory():AddItems(Pickups, true)
		return true
	end
end
```
Worked in older version (commit: 180a43d09721a32ad502f5e583d3b2d797501c00)
### Actual behavior
Item drops down and doesn't come to inventory showing error in console:
```
LUA: Plugins/HNPrison/main.lua:30: attempt to index local 'Digger' (a boolean value)
Stack trace:
 Plugins/HNPrison/main.lua(30): (no name)
Stack trace end
Error in <attached> calling function <callback>()
```

### Steps to reproduce the behavior
1. Create Cuberite server (5a2163d7e6ffa0c5c568be41257fb726d452b3b9)
2. Add plugin with HOOK_BLOCK_TO_PICKUPS and this callback
```
function GiveItems(World, Digger, BlockX, BlockY, BlockZ, BlockType, BlockMeta, Pickups)
	if Digger:IsPlayer() then
		Digger:GetInventory():AddItems(Pickups, true)
		return true
	end
end
```
3. Break block in Survival mode
4. Boom! Doesn't work.
### Server log
https://gist.github.com/nikkedoy98/3c95eaf607f57b72ec7094915c3b6669

Relevant part of server log:

```
LUA: Plugins/HNPrison/main.lua:30: attempt to index local 'Digger' (a boolean value)
Stack trace:
 Plugins/HNPrison/main.lua(30): (no name)
Stack trace end
Error in <attached> calling function <callback>()
```

**Comment by maxluchterhand1** [comment]
Could you supply a plugin with which this behaviour occurs?

**Comment by nikkedoy98** [comment]
Sure! Here it is:
[PickupTest.zip](https://github.com/cuberite/cuberite/files/4348840/PickupTest.zip)

**Comment by madmaxoft** [comment]
We've got even worse fundamental problem. The BlockToPickups hook may be called even when no-one is breaking anything, just to query "what would happen if this block was broken?". But the hook has no way of knowing whether this is "for real" or "for test".

**Comment by maxluchterhand1** [comment]
Does it really just get called to query what would happen if the block was broken? From where does this call happen?
During testing, I could only see the plugin getting called when either a player was breaking something, or the water physic were breaking stuff.

**Comment by madmaxoft** [comment]
Currently the core server doesn't use that functionality, but it is ready for it. See `cWorld::PickupsFromBlock` that indirectly calls this hook. There is direct contradiction in the documentation, `PickupsFromBlock` says "theoretically", while the hook docs say "block about to be dug". I'm inclined to change the hook so that it is "theoretically" as well, because a plugin can use OnPlayerBreakingBlock for the "actually breaking".
