### ISSUE TITLE
Ghasts drown and Generators not working

### ISSUE THREAD

**Issue by Riku32** [cuberite/cuberite#4503]
Client version: Windows
Server OS: Windows/Linux/macOS/BSD/...
Cuberite Commit id: 5a2163d7e6ffa0c5c568be41257fb726d452b3b9

### Expected behavior
Ghast/end dragon flies and shoots at you
End dungeon and other structures generate
End generates with islands and cities

### Actual behavior
Ghast/dragon sinks to the floor
The end does not generate properly and is a square
The end is a pole instead of an island

### Steps to reproduce the behavior
Go to the nether/end

**Comment by mathiascode** [comment]
Closing in favor of #4056
