### ISSUE TITLE
Problem with spaces in permission system

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4520]
### Expected behavior
Using webadmin and adding a permission to a group should work, it should not matter if there are spaces at start or end.

### Actual behavior
Permissions are added with spaces. Took me a while to find out that...

### Steps to reproduce the behavior
I had copied the permission from the github README page of plugin Core and there is a space a the end.

It looks like all methods have the same problem..

Will work on a pull request.

**Comment by Seadragon91** [comment]
Before I change it all, it it okay to use `TrimString` for all the affected exported methods in `cRankManager`?

**Comment by bearbin** [comment]
That should be fine, as long as it makes sense in context.

**Comment by Seadragon91** [comment]
Should that be better fixed fixed in plugin Core?

**Comment by mathiascode** [comment]
Probably better to validate in the Core plugin in my opinion.

**Comment by Seadragon91** [comment]
Okay.
