### ISSUE TITLE
Chunks are not sent to clients at times

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4531]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: 00ae9604e11e2f0859fb219029c903662fe27bfd

### Expected behavior
Chunks are always visible for clients.

### Actual behavior
Chunks aren't always sent to clients, rendering block textures invisible.

### Steps to reproduce the behavior
Happens to random chunks when traveling in a world sometimes. A consistent way to reproduce is to teleport to a location, e.g. /tp 55555 64 33333, and immediately teleport somewhere else, e.g. /spawn.

**Comment by mathiascode** [comment]
If you teleport quick enough, chunks sometimes don't exist, and the player is stuck in a frozen state until relogging.

**Comment by mathiascode** [comment]
Player freezing is done intentionally here:
https://github.com/cuberite/cuberite/blob/00ae9604e11e2f0859fb219029c903662fe27bfd/src/Entities/Player.cpp#L414-L417

**Comment by tigerw** [comment]
Copied from https://github.com/cuberite/cuberite/issues/5245#issuecomment-867948533

> Having fully loaded the chunks in your area, when teleporting to a faraway location and immediately back, the server doesn't send chunks anymore. This is because after chunks are fully loaded, an internal value is set to your current chunk to stop further chunk streaming. Teleporting away and back unloads every chunk clientside, but because that internal value is unchanged, chunk streaming remains stopped.

To fix this m_LastSentChunk is reset to a bogus value whenever the player's current chunk doesn't match.
