### ISSUE TITLE
SetHotbarSlot in Lua API not behaving normally

### ISSUE THREAD

**Issue by RedNicStone** [cuberite/cuberite#4541]
Client version: 1.12.2 Impact
Server OS: Fedora 28
Cuberite Commit id: 0d444b62c96f3e2edf00116361e76792e9a41c63

### Expected behavior
After calling
```lua
[cInventory]:SetHotbarSlot(slotNr, cItem)
```
the Item in the Hotbar should be changed.

### Actual behavior
The Item is not changed, SetSlot() works fine.

### Steps to reproduce the behavior
Write an plugin an call the SetHotbarSlot() function.

### Server log
[No Errors]

Thanks for helping!

**Comment by RedNicStone** [comment]
For me,
```lua
Player:GetInventory():SetHotbarSlot(1, cItem(E_ITEM_BOW))
```
does not work for me, see #help@discord

**Comment by madmaxoft** [comment]
@RedNicStone Perhaps you should provide a minimum example plugin in which it doesn't work for you.

**Comment by RedNicStone** [comment]
```lua
function Initialize(Plugin)
  Plugin:SetName("testplugin")
  cPluginManager:BindCommand("/give_bow", "testplugin.give", Give, " ~ giveme an bow")
end
function Give(Split, a_Player)
  a_Player:GetInventory():SetHotbarSlot(1, cItem(E_ITEM_BOW))
end
```
At least it didn't work yesterday

**Comment by peterbell10** [comment]
Your plugin doesn't load properly because you don't `return true` from `Initialize`.

Working version:
```lua
function Initialize(Plugin)
  Plugin:SetName("testplugin")
  cPluginManager:BindCommand("/give_bow", "testplugin.give", Give, " ~ giveme an bow")
  return true
end

function Give(Split, a_Player)
  a_Player:GetInventory():SetHotbarSlot(1, cItem(E_ITEM_BOW))
  return true
end
```

Also make sure your plugin is actually loaded by your server.

**Comment by RedNicStone** [comment]
> Your plugin doesn't load properly because you don't `return true` from `Initialize`.
> 
> Working version:
> 
> ```lua
> function Initialize(Plugin)
>   Plugin:SetName("testplugin")
>   cPluginManager:BindCommand("/give_bow", "testplugin.give", Give, " ~ giveme an bow")
>   return true
> end
> 
> function Give(Split, a_Player)
>   a_Player:GetInventory():SetHotbarSlot(1, cItem(E_ITEM_BOW))
>   return true
> end
> ```
> 
> Also make sure your plugin is actually loaded by your server.

1. I just forgot that
2. I didn't test that code, as i said
3. This isn't the issue

But anyway it works like a charm now, the problem was there for sure but now its gone.
Don't ask me. ¯\_(ツ)_/¯
