### ISSUE TITLE
Unbreak mob spawners

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4550]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: b7e88e2c9f96f31e29a85c3d7ef312fb4bd8c549

As far as I can tell, mob spawners currently don't spawn anything due to a couple of failing checks.

**Comment by mathiascode** [comment]
cMobSpawnerEntity::GetNearbyPlayersNum is broken (always returns 0)
cMobSpawnerEntity::GetNearbyMonsterNum is broken (always returns 0)
cMobSpawner::CanSpawnHere prevents mob spawner spawning, since it contains code to prevent mobs from spawning within 24 blocks of the player.

**Comment by mathiascode** [comment]
I tried to fix it, but gave up for now. #3736 should also be looked into.

**Comment by MeMuXin** [comment]
What about a new argument to cMobSpawner::CanSpawnHere... Like a_IgnorePlayers??

**Comment by peterbell10** [comment]
IMO we should have two different functions for :
1. Are we too close to a Player for a natural spawn (don't call for mob spawners)
2. Can this mob type spawn at this block

I'm also a bit confused why `CanSpawnHere` randomly fails for some mob types. e.g. for oscellots:

https://github.com/cuberite/cuberite/blob/b7e88e2c9f96f31e29a85c3d7ef312fb4bd8c549/src/MobSpawner.cpp#L233-L244

As far as I can tell, this doesn't actually change the spawn rate in any way.

**Comment by mathiascode** [comment]
The current situation:
cMobSpawner::CanSpawnHere is only called directly by mob spawners

Natural mob spawning calls cMobSpawner::TryToSpawnHere, which in turn calls cMobSpawner::CanSpawnHere.
