### ISSUE TITLE
Add nether wart to nether fortress

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4554]
As far as I can tell, nether wart used to appear in nether fortresses, but seems to have been removed at some point.

**Comment by mathiascode** [comment]
Actually, it should still be there. Maybe I have to search a bit more.

**Comment by mathiascode** [comment]
@madmaxoft Any idea if there's something wrong with the NetherFort prefab? I can't seem to find any MidStaircase parts, which should include nether wart.

**Comment by madmaxoft** [comment]
It should still be there (note the `c` letter mapping): https://github.com/cuberite/cuberite/blob/2b32bb0b1928704499aa187ed3bff7433264e742/Server/Prefabs/PieceStructures/NetherFort.cubeset#L1990-L2069

**Comment by mathiascode** [comment]
Found some.
