### ISSUE TITLE
Empty chests in villages

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4559]
Client version: 1.12.2
Server OS: Ubuntu 16.04 server i386
Cuberite Commit id: **2b32bb0b1928704499aa187ed3bff7433264e742**

### Expected behavior
I expected to found some cool stuff in chests of a village

### Actual behavior
All chests are empty, will be cool if they can be filled with some random stuff as we can found in vanilla servers.

### Steps to reproduce the behavior
Find a village with chests and open them

**Comment by mathiascode** [comment]
Duplicate of #1097
