### ISSUE TITLE
Too high probability of big tree growth

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4560]
Client version: 1.12.2
Server OS: Ubuntu Server 16.04 i386
Cuberite Commit id: **2b32bb0b1928704499aa187ed3bff7433264e742**

### Expected behavior
Less big trees growth, more normal trees

### Actual behavior
In my sense, the probability of getting a big tree growth is too high, indeed, approximatively more than one of two trees on approx 100 trees planted are big trees, which is a lot !

### Steps to reproduce the behavior
Plants lot of trees

**Comment by madmaxoft** [comment]
Do you have any statistics for vanilla? Otherwise there's nothing to compare to.

**Comment by Xenoxis** [comment]
Yes you're right, i don't have any explicit numbers to give you :(
But try to experiment it on cuberite server and then on vanilla, you should see a difference.

**Comment by mathiascode** [comment]
Tree type? What counts as a big tree in this case (there are the really big ones when placing saplings 2x2)?

**Comment by Xenoxis** [comment]
No, by "big trees" i mean Oak ones with branches, not ones in jungles or with 2x2 blocks base

**Comment by kittenfromvoid** [comment]
Can I take probability from original minecraft source or should I just test it?

**Comment by kittenfromvoid** [comment]
@Xenoxis I tried reproducing it and I really can't

**Comment by madmaxoft** [comment]
You shouldn't look at the vanilla sources at all when developing Cuberite (for legal reasons).

There doesn't seem to be any data in the minecraft wiki regarding the probability of a larger (branched) trees. We assume that the probablility is the same for growing trees from saplings as it is for generating the trees in new chunks; this has been guesstimated at 3/16 (18.75 %):
https://github.com/cuberite/cuberite/blob/d0f38f52cbd97828d9cadaf12d33c886b8d00383/src/Generating/Trees.cpp#L397-L404

**Comment by RyanRussell00** [comment]
I did some independent testing of how often "big trees" occcured:
Cuberite: 8 / 40 =  20%
Vanilla Minecraft: 4 / 40 = 10%

If this issue is still open, I'm interested in looking into this and seeing if I can resolve it.
@madmaxoft

**Comment by mtan37** [comment]
Anyone actively working on this? I am new and want give it a shot

**Comment by 12xx12** [comment]
Hi, thank you for your interest in the project.

There is no open PR at the moment so go ahead.

If you need further help feel free to ask. Either her or on the discord or forums.

**Comment by Stefan-TU** [comment]
Hi, how does this issue look?

**Comment by mtan37** [comment]
@Stefan-TU I am no longer planning to work on this, feel free to take it

**Comment by tonitch** [comment]
following this page https://www.minecraftforum.net/forums/minecraft-java-edition/survival-mode/223343-tree-science-definitive-guide-up-to-date-for-1

it should be 1/10 chance of big tree (so more like 10%)

**Comment by LhAlant** [comment]
> There doesn't seem to be any data in the minecraft wiki regarding the probability of a larger (branched) trees. We assume that the probablility is the same for growing trees from saplings as it is for generating the trees in new chunks; this has been guesstimated at 3/16 (18.75 %):

I don't understand why the probability is 3/16. From the snippet of code you profided, a small tree will be spawned if the noise returns something less than 0x60000000. The `IntNoise3dInt` function returns an integer from 0x00 to 0x7fffffff. Shouldn't the probability of a large tree spawning be of 1 - 6/8 = 25% ?

https://github.com/cuberite/cuberite/blob/7e83dd073e0bc322b975df66d061a6f7fe059bf1/src/Noise/Noise.h#L254C1-L259C2

Anyway, if my math is right, this is an easy fix, just changing the 0x60000000 constant to 0x73333333. to match the 10% found by @tonitch



> following this page https://www.minecraftforum.net/forums/minecraft-java-edition/survival-mode/223343-tree-science-definitive-guide-up-to-date-for-1
> 
> it should be 1/10 chance of big tree (so more like 10%)
