### ISSUE TITLE
Snow behaviour

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4562]
Client version: 1.12.2
Server OS: Ubuntu 16.04 i386
Cuberite Commit id: 2b32bb0b1928704499aa187ed3bff7433264e742

### Expected behavior
Broking snow on the floor with spade, and then place an a block should work.
Attempt to place a block on snow will automatically broke the snow block and place yours instead

### Actual behavior
Currently, when you place a block after broking snow, the snow block reappears and your block isn't placed.
If you try to place block on snow, your block is placed above the snow block.

### Steps to reproduce the behavior
Found some snow biomes, use tool to broke the snow, then try to place blocks

**Comment by Xenoxis** [comment]
It seems to appears with only the spade (high breaking speed for snow) and when you broke more than one snow block without released left-click

**Comment by mathiascode** [comment]
Something in https://github.com/cuberite/cuberite/pull/4417 broke snow behavior.

**Comment by KingCol13** [comment]
Fixed in #4938 .
