### ISSUE TITLE
Snow Can Spawn on E_BLOCK_STONE_SLAB

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4565]
Client version: 1.12.2
Server OS: Ubuntu server i386
Cuberite Commit id:  7d8da81b92f0a9dcd7ae35628d3896ca565a9b45

### Expected behavior
Snow cannot spawn on Cobblstone Slab

### Actual behavior
Snow can spawn on Cobbletone Slab (and more precisely on all E_BLOCK_STONE_SLAB blocks)

![2020-03-27_20 26 57](https://user-images.githubusercontent.com/19935648/77797676-c364cd00-7071-11ea-9b88-d55d02ebdf2b.png)

Pull Request to fix : #4564

**Comment by bearbin** [comment]
Fixed by #4564
