### ISSUE TITLE
Explosions send all players up in the sky

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4575]
Client version: 1.12.2
Server OS: Ubuntu server 16.04 i386
Cuberite Commit id:  fce548139b8c4643cd28f636d5c497d2ca8cd230

### Expected behavior
An explosion shouldn't shoot the player in the sky, and should be only for players around the explosions

### Actual behavior
If a player is around and touch by an explosion, all players (at least in the same world) are sent in the sky with a very huge power, all players mean players that are far from the explosion

### Steps to reproduce the behavior
At least 2 players I believe, TNT, Ghasts or something else that can cause an explosion

**Comment by mathiascode** [comment]
Some issue with GetSpeed() at https://github.com/changyongGuo/cuberite/blob/5bcf079946922bb05ec2ecdb206db296f10704da/src/World.cpp#L1447. Happens more often since Ghasts started flying.

**Comment by mathiascode** [comment]
Also see https://github.com/cuberite/cuberite/issues/4527

**Comment by Xenoxis** [comment]
It happen with creeper explosions also

**Comment by Xenoxis** [comment]
This bug make the game quite unplayable with more than 3 players, everyone is send up in the sky
