### ISSUE TITLE
Invisibles mobs

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4576]
Client version: 1.12
Server OS: Linux
Cuberite Commit id: fce548139b8c4643cd28f636d5c497d2ca8cd230

### Actual behavior
Sometimes, a specific mob is invisible for all players, it need a server restart to fix it

### Steps to reproduce the behavior
Unknown

**Comment by mathiascode** [comment]
Known issue with unknown cause. https://github.com/cuberite/cuberite/issues/3696
