### ISSUE TITLE
Crash when leaving the game

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#4577]
Client version: 1.12.2
Server OS: Linux (debian bullseye/clang 9.0.1-10)
Cuberite Commit id: 31ace87d

The server crashed immediately after leaving. It appeared that somehow the Player was destroyed before the ClientHandle. The issue was reproducible for a while, even when changing some parts of the code. However after clearing my working directory and trying to compile from fresh the issue disappeared. I guess this could be some compilation artifact but I don't know how that would interfere with the lifetime of cPlayer.

### Server log
```
[7359a5658c0d6291|16:56:34] Client bearbin @ ::ffff:127.0.0.1 disconnected
[d43d95798065f534|16:56:34] Client bearbin @ ::ffff:127.0.0.1 (0x7fd23c000d90) has been queued for destruction, destroying now.
[d43d95798065f534|16:56:34] Destroy: destroying client 0x7fd23c000d90, "bearbin" @ ::ffff:127.0.0.1
[d43d95798065f534|16:56:34] Player bearbin has left the game
[d43d95798065f534|16:56:34] Deleting cPlayer "bearbin" at 0x7fd204002210, ID 42
[d43d95798065f534|16:56:34] Player 0x7fd204002210 deleted
Player not in waiting list!
[d43d95798065f534|16:56:34] Removing player bearbin from world "world"
[d43d95798065f534|16:56:34] Assertion failed: m_PlayerPtr, file /home/bearbin/cuberite/cuberite/src/ClientHandle.cpp, line 191
./Cuberite(_Z15PrintStackTracev+0x1c)[0xb71bfc]
```

**Comment by madmaxoft** [comment]
Could be related: #4578

**Comment by peterbell10** [comment]
Reported only 1 minute later as well. What a coincidence.

> The issue was reproducible for a while, even when changing some parts of the code. However after clearing my working directory and trying to compile from fresh the issue disappeared.

Might be a race condition somewhere. How consistent was it before rebuilding?

**Comment by bearbin** [comment]
It happened every time, I tried it probably 10 times before I stopped being able to reproduce it.

**Comment by Seadragon91** [comment]
Looks like maybe similar problem like issue #4568

**Comment by peterbell10** [comment]
@bearbin did you rebuild in release instead of debug?

**Comment by bearbin** [comment]
Yes...
