### ISSUE TITLE
XP levels resets after crossing a Nether Portail

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4585]
Client version: 1.12.2
Server OS: Ubuntu 16.04 Server 
Cuberite Commit id:  6116f899dee33a6d7bd887f7a57ace17df2ab94f

### Expected behavior
When a player cross the nether portail, all of his stuff (including xp level) should be the same in the overworld and in the nether (this can be false with some plugins and specifics configurations)

### Actual behavior
Going into the Nether and then return to the overworld reset my XP

### Steps to reproduce the behavior
Apparently going into the Nether and return in the Overworld, don't know if it always happens or sometimes with particular conditions

**Comment by Bond-009** [comment]
Maybe a client issue, since vanilla servers have the same issue.

**Comment by Xenoxis** [comment]
Really ? It it's the case, cuberite can maybe fix it by force the update of the bar by sending to players when they cross a world an xp amount of 0 ?

**Comment by Xenoxis** [comment]
:+1:
