### ISSUE TITLE
Spider are 1 block width

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4589]
Client version: 1.12.2
Server OS: Ubuntu Linux i386
Cuberite Commit id:  6116f899dee33a6d7bd887f7a57ace17df2ab94f

### Expected behavior
Spider should be 2 block width size

### Actual behavior
They are 1 block size, can pass through 1 block hole

**Comment by bearbin** [comment]
I also encountered this issue, but I believe it is an instance of #3747 - at least spiders have a defined width of 1.4 blocks which is >1.

**Comment by peterbell10** [comment]
Yup, this is a duplicate of #3747.
