### ISSUE TITLE
Potions don't work

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4599]
Client version: 1.12.2
Server OS: Ubuntu server 16.04 i386
Cuberite Commit id: 318d31dc394da9faea11544ad6e485f1b5eabbdb

### Expected behavior
Potions should works

### Actual behavior
Potions doesn't works

### Steps to reproduce the behavior
Try to make any potions

**Comment by mathiascode** [comment]
So is this just an issue with creating potions in brewing stands, or do potions not apply any effects in general?

**Comment by Xenoxis** [comment]
Yes, we cannot creating potions in brewing stands
