### ISSUE TITLE
Enchantments aren't saved for an item

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4614]
Client version: 1.12.2
Server OS: Ubuntu server 16.04 i386
Cuberite Commit id: aac592f98598aae327d07b2a1bb155e33c6d51b1

### Expected behavior
When a item is placed in the enchantment table, all available enchantments are saved and cannot be reloaded or refreshed.
Video of vanilla behaviour : [Vanilla Enchantment Behaviour.zip](https://github.com/cuberite/cuberite/files/4431221/Vanilla.Enchantment.Behaviour.zip)

### Actual behavior
Enchantments aren't saved and can be refreshed just by putting out the lapis lazulis.
Video of cuberite behaviour : [Cuberite Enchantment Behaviour.zip](https://github.com/cuberite/cuberite/files/4431219/Cuberite.Enchantment.Behaviour.zip)

### Steps to reproduce the behavior
Try to enchant a item

**Comment by KingCol13** [comment]
Fixed in #4937 .
