### ISSUE TITLE
The sun is going wild

### ISSUE THREAD

**Issue by GefaketHD** [cuberite/cuberite#4631]
Client version: 12.2.2
Server OS: Linux
Cuberite Commit id: 16b3de94c89edae2ba8ff7ad6baa6b322c4571af

### Expected behavior
Setting the time sets the time with no problems whilst setting one number over and over would set the sun to always the same position.

### Actual behavior
Seems pretty random...sometimes the sun starts jittering. Sometimes the same number causes different positions of the sun.
It just stops jittering if you provide the same number twice. But even then the position can vary.

Here are 2 examples of my brother and me discovering this:
https://medal.tv/clips/22030763/d1337onm8phI
https://medal.tv/clips/22030809/d1337dBBz6e0

### Steps to reproduce the behavior
Set the time of the sun to 2 different positions quickly over and over again.

### Server log
```
-
```

**Comment by madmaxoft** [comment]
This is most likely a problem in the Core plugin that handles the `/time` command, most likely caused by the animation. Tracked in the Core plugin's repository: https://github.com/cuberite/Core/issues/228

**Comment by bearbin** [comment]
This was fixed in Core, and update in this repo by b9c9698d.
