### ISSUE TITLE
Water breaks redstone still after it's gone again

### ISSUE THREAD

**Issue by GefaketHD** [cuberite/cuberite#4635]
Client version: 12.2.2
Server OS: Linux
Cuberite Commit id: 16b3de94c89edae2ba8ff7ad6baa6b322c4571af

### Expected behavior
If you place water and destroy e.g. a redstone repeater with it, get rid of the water and place the repeater at the exact same position like before, the repeater can get lit again.

### Actual behavior
...can't get lit again until a server restart (at least that's the only way I could manage to get it working again)

### Steps to reproduce the behavior
Place a repeater, power it, destroy it with water and try to power it again.

### Server log
```
-
```

**Comment by tigerw** [comment]
I can't seem to reproduce this, I did, in a 1 deep, 5 wide trough:

```
Torch Repeater Dirt Repeater Air
```
```
Torch Repeater Dirt Repeater Water
```
```
Torch Repeater Dirt Water Water
```
```
Torch Repeater Dirt Water Dirt
```
```
Torch Repeater Dirt Water Air
```
```
Torch Repeater Dirt Air Air
```
```
Torch Repeater Dirt Repeater Air
```

And the repeater lights for me.

**Comment by GefaketHD** [comment]
![2020-04-10_14 56 18](https://user-images.githubusercontent.com/18399895/78992517-af25d300-7b3b-11ea-866c-825b3c80d457.png)
![2020-04-10_14 56 25](https://user-images.githubusercontent.com/18399895/78992519-b0570000-7b3b-11ea-85b0-3debb18f2f20.png)
![2020-04-10_14 57 07](https://user-images.githubusercontent.com/18399895/78992522-b0570000-7b3b-11ea-957d-77ac6c21851c.png)

**Comment by GefaketHD** [comment]
I didn't describe the problem correctly, I'm sorry.

**Comment by tigerw** [comment]
I can reproduce, thanks!

**Comment by tigerw** [comment]
I think I know the cause, we're not deleting an entry from the mechanism delay list when the repeater gets rekt by the water. So the delay keeps ticking down and goes negative.

**Comment by GefaketHD** [comment]
Does this apply for every redstone-mechanism?

**Comment by GefaketHD** [comment]
Aaah because the `update` function of the repeater is not called again, when it is destroyed? So the entry still remains?

**Comment by GefaketHD** [comment]
So this applies for redstone torches and comparators too probably. Did not test it.

**Comment by tigerw** [comment]
Probably everything that uses delays. I hypothesise that [this](https://github.com/cuberite/cuberite/blob/master/src/Simulator/IncrementalRedstoneSimulator/RedstoneSimulatorChunkData.h#L46) line should also delete from `m_MechanismDelays`.

**Comment by GefaketHD** [comment]
Sounds like the perfect place for it. Even though I am pretty new to the project and don't even know all the places. :)

**Comment by GefaketHD** [comment]
I will test it

**Comment by GefaketHD** [comment]
I wasn't able to break it after that added line. PR incoming. :+1:
