### ISSUE TITLE
Lamp gets turned off when a repeater is placed diagonally

### ISSUE THREAD

**Issue by GefaketHD** [cuberite/cuberite#4639]
Client version: 12.2.2
Server OS: Linux
Cuberite Commit id: 0d722701861ad9acfa7d36c5156fd184e3ba6bee

### Expected behavior
The lamp doesn't care about a repeater diagonally.

### Actual behavior
See screenshots:
![2020-04-10_22 12 58](https://user-images.githubusercontent.com/18399895/79020215-87a12b80-7b78-11ea-9181-d7f08b582569.png)
![2020-04-10_22 12 54](https://user-images.githubusercontent.com/18399895/79020214-87089500-7b78-11ea-8235-879730056752.png)

### Steps to reproduce the behavior
Place everything down as shown on the screenshots.

### Server log
```
-
```

**Comment by tigerw** [comment]
Nice catch.

Looks like the wire is trying serverside to "connect directly" to the repeater and in doing so make a 90-degree bend that stops the lamp from getting power; it's disregarding that the repeater has its side facing the wire, but direct connection is only from the front and back.
