### ISSUE TITLE
Cactus drops when placed on something else than sand or another cactus

### ISSUE THREAD

**Issue by GefaketHD** [cuberite/cuberite#4641]
Client version: 12.2.2
Server OS: Linux
Cuberite Commit id: 0d722701861ad9acfa7d36c5156fd184e3ba6bee

### Expected behavior
Cactus would just not be placable. Players hand wouldn't even move.

### Actual behavior
The attempt is made to place the cactus and it just drops as a block.
I think this is _kind of_ similar to the issue with dropping levers, buttons, etc. on glass, lilypads, halfslabs, but it might be not, because the other pieces are not solid blocks.

### Steps to reproduce the behavior
Place a cactus e.g. on grass.

### Server log
```
-
```

**Comment by Titaniumtown** [comment]
I think you mean minecraft 1.12.2 not 12.2.2.

**Comment by GefaketHD** [comment]
Nah, I‘m from the future-now that you mention it: I think that might be the reason it‘s bugging. 😝

Joke: yeah I mean 1.12.2 :)

**Comment by morsmordere** [comment]
I would like to work on the fix for this issue.
