### ISSUE TITLE
Feature request: Per-user view distance

### ISSUE THREAD

**Issue by Titaniumtown** [cuberite/cuberite#4649]
I feel like the title is self explanatory, being able to set view distance per-player.

**Comment by mathiascode** [comment]
This should already be possible with the /viewdistance command, as well as ClientHandle:SetViewDistance in the API.

**Comment by madmaxoft** [comment]
Also, each client sends their preferred view distance, and Cuberite takes that into consideration (although never going higher or lower than the configured minimum / maximum).

If you want to have persistent per-client view distance, I think that's a good idea for a plugin - keep the requested view distances in a sqlite DB and re-apply them when the client reconnects.
