### ISSUE TITLE
Writing cBlockArea doesn't update BlockEntities

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#465]
Writing a cBlockArea into the world needs to check block entities - existing ones may have been overwritten and new ones may need creating.

An easy way to verify this: combine the Debuggers plugin with Gallery plugin. Debuggers place a sign at each chunk's corner, then Gallery, when claiming an area, overwrites everything with the predefined area schematic; the sign is lost, yet the block entity stays even after server restart and is sent to the client; the client then complains "sign at X, Y, Z not found"

**Comment by pwnorbitals** [comment]
Is this still an existing bug ? @madmaxoft, can you still reproduce ?

**Comment by NiLSPACE** [comment]
The code to delete them is there, so this is fixed: https://github.com/cuberite/cuberite/blob/master/src/Chunk.cpp#L423-L434

It was added in #3795
