### ISSUE TITLE
Rethink the method on how to rotate blocks on placing them

### ISSUE THREAD

**Issue by GefaketHD** [cuberite/cuberite#4651]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: c9a9b3c9d0d4fed0b02d9935923bfd7dcbc45d1e

### Expected behavior
Blocks are placed on the server exactly as the client would expect them to be placed.

### Actual behavior
The rotation of a block depends serversided only on the angle the player is looking when a block is placed - if it is above or below 50 degrees.
So this issue just exists so everyone could provide an idea. :) If there is such a thing like an "not very important" - tag: apply it to this one please :)

I am currently on it to do some testing and math and research and stuff to figure out, what other factors are important for the placement of the blocks when playing singleplayer for instance.

(Is there any way to read the rotation the clients wants the block to have?)

### Steps to reproduce the behavior
Place blocks and watch them get rotated after a split second by the server.

### Server log
```
-
```

**Comment by tigerw** [comment]
> Is there any way to read the rotation the clients wants the block to have?

I think it's a matter of getting the right pitch constant to compare against

**Comment by MeMuXin** [comment]
What about the opposite of the JawPitch of the player??... If payer is looking East, the block should be facing West

**Comment by GefaketHD** [comment]
> > Is there any way to read the rotation the clients wants the block to have?
> 
> I think it's a matter of getting the right pitch constant to compare against
The Problem is, that it is not only the pitch that matters.

**Comment by GefaketHD** [comment]
That's what I'm trying to say: It is not possible to get the correct rotation of the block every time if you only look at the pitch. It's also the distance between the player and the place, where the block will be placed. But due to me not being smart enough to do the calculations on my tests, I can't tell how it should be calculated.

**Comment by madmaxoft** [comment]
The player position and rotation is the only thing that can matter with placing blocks. The client only sends those, so the server must figure values out based on them (the client also helpfully sends the position of the cursor within the clicked block face, but the server could very well calculate that, too).

So this means you have found some corner cases where our block placement logic doesn't match the client's block placement logic. We cannot fix this unless you provide very specific observations:
- item / block type you're placing
- exact player position (at least 3 decimal places)
- exact player rotation (the F3 debug screen shows it as "Facing", two values)
- what got placed by the server
- what got placed by the client

**Comment by GefaketHD** [comment]
Yeah, that is what im saying: it is not only the pitch of the head. On cuberite, the rotation of the block is determined with a 50 degree threshold on the pitch. If it is above, it gives a different rotation that below 50 degrees. But that is not always correct. I was testing a lot and I will provide a PR and idea behind it, as soon as I can say more.

I did intense testing with an observer, but every block like furnace or piston would have behaved the same way.
I could give you a list of positions and rotation or pitch, but I rather find the solution for it. I can make a video on it if that would help...but you could just simply test it out yourself...and "feel" it.

**Comment by GefaketHD** [comment]
I also said: the issue should be marked as "not very important", because everything is working, it is just not as the client would expect it to behave. And I made this issue so everyone could have a thought about it and share the information here. Maybe we can find the right formula together. :)

**Comment by tigerw** [comment]
I did some investigation and it seems the final direction indeed depends on the player's position relative to the block to be placed.

X + Z: getting too far away always places a block in a cardinal direction, never up or down.
Y: being above or below the block to be placed changed whether it was placed up or down, or in a cardinal direction.

in fact I'm not convinced the pitch actually matters at all.
