### ISSUE TITLE
Elytra

### ISSUE THREAD

**Issue by FusixGit** [cuberite/cuberite#4654]
Hello. At what stage is the implementation of elytra gliding now? What did you stop at? Maybe I can help with the implementation.

**Comment by madmaxoft** [comment]
I don't think work on elytra has even started. Sure, you can go ahead and do it, although there may be other things that could use more immediate attention.

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/cuberite/cuberite/issues/4311
