### ISSUE TITLE
Feature request: Armor points

### ISSUE THREAD

**Issue by GefaketHD** [cuberite/cuberite#4659]
In vanilla you get a row of armor-points when you have armor on. In cuberite this isn't implemented yet.

**Comment by peterbell10** [comment]
Duplicate of #4098

**Comment by GefaketHD** [comment]
Oh...

**Comment by Titaniumtown** [comment]
smol brain, always search your issue before making an issue.

**Comment by GefaketHD** [comment]
:) Thank you
