### ISSUE TITLE
Remove BiomeDef.h and ChunkDef.h from Globals.h

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#4667]
The two headers are by no means anything needed globally, so they should be instead included only in the places they are actually needed, rather than Globals.

Right now, any change in ChunkDef.h causes recompilation of even OSSupport code, for example, which is definitely needless.

**Comment by KrystilizeNevaDies** [comment]
Ill get this done

**Comment by bearbin** [comment]
Fixed in #4885
