### ISSUE TITLE
Extend HOOK_PLAYER_FISHING and HOOK_PLAYER_FISHED with Experience amount

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#4671]
The `HOOK_PLAYER_FISHING` and `HOOK_PLAYER_FISHED` hooks should get a new parameter, `ExperienceAmount`, that specifies the amount of experience the player gets for the fishing operation' `HOOK_PLAYER_FISHING` should also be able to change the amount.

**Comment by npresley0506** [comment]
Hey, I'm a student doing a final project for my class that requires me to work on an open-source project. Mind if I try grabbing this one and taking a crack at it?

**Comment by bearbin** [comment]
@npresley0506 Of course, we always encourage new contributors. This issue isn't asssigned to anyone so it's free for you to work on. As a new contributor you should take a look at the [getting started](https://github.com/cuberite/cuberite/blob/master/GETTING-STARTED.md) and [contributing](https://github.com/cuberite/cuberite/blob/master/CONTRIBUTING.md) files for some guidance and help with the project. If you have any other questions I recommend joining the Discord group or the forum as there are several contributors there that could offer help.

**Comment by feyokorenhof** [comment]
I don't know if this is still being worked on but I'd be happy to take a look.

**Comment by bearbin** [comment]
Unless there's a PR for an issue, or it's actively under discussion/assignment, it's probably not being worked on. Feel free to have a go :)

**Comment by bearbin** [comment]
Fixed by #5345
