### ISSUE TITLE
Day count in f3 not implemented

### ISSUE THREAD

**Issue by Titaniumtown** [cuberite/cuberite#4737]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: e053f72db824a16c1cb59107315001473058e2bc

### Expected behavior
There should be a number in the f3 menu stating how many in game days have past.

### Actual behavior
The Day count is always 0.

### Steps to reproduce the behavior
Open f3 on server running cuberite

**Comment by morsmordere** [comment]
I would like to work on this feature request.

**Comment by idomori** [comment]
Is this still an issue for you?

**Comment by Titaniumtown** [comment]
yes
