### ISSUE TITLE
Error with compile.sh

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4753]
Server OS: Ubuntu 16.04 server i386
Cuberite Commit id: 9e8598fb1ca359143600d6bb2e8b317126a86bcc

### Expected behavior
Attempting to compile without errors as i've done many times

### Actual behavior
Since recently, i cannot compile the code anymore, the error that show is :
`fatal: the reference isen't a tree : b8cb8889aab726a35c49472228256f7bb1d44388
Cannot extract 'b8cb8889aab726a35c49472228256f7bb1d44388' in the sub-module path 'lib/jsoncpp' `

I've try to delete the repository of cuberite, and then re-clone it, without any success
@madmaxoft tell me to do `git submodule update --init`, without success.
An another member tell me to clone the repository with `--recursive` at the end of the command line, without success either

### Steps to reproduce the behavior
Try to compile with the `compile.sh` tool in Linux (MacOS will show the same error i guess)

**Comment by peterbell10** [comment]
>I've try to delete the repository of cuberite, and then re-clone it, without any success

Did you delete the entire `cuberite` directory, or just the contents?  You might have missed the `.git` folder if you only deleted the contents.

**Comment by Xenoxis** [comment]
@peterbell10 I've delete the whole directory

**Comment by peterbell10** [comment]
Can you try again.

**Comment by Xenoxis** [comment]
Have you changed anything ? Cause it seems to compile without any errors ...

**Comment by peterbell10** [comment]
Yes, I set the master branch of `lib/jsoncpp` to the submodule commit. I'm guessing your git was doing some kind of shallow checkout which didn't include the correct commit.
