### ISSUE TITLE
No item drops with eff V pickaxe

### ISSUE THREAD

**Issue by Titaniumtown** [cuberite/cuberite#4757]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: 99d96337da2852b3163108334eba84e1ba806cb7

### Expected behavior
Item drops when I break block with eff V diamond pickaxe.

### Actual behavior
Of the blocks I've tested, it seems like sandstone is affected, I should do more testing. The block is destroyed, but no item is produced to be picked up.

### Steps to reproduce the behavior
Mine block

**Comment by morsmordere** [comment]
I would like to work on the fix for this issue.

**Comment by Titaniumtown** [comment]
I don't really know what could be causing it

**Comment by idomori** [comment]
There is also another problem that is probably related to this issue.
In survival mode, after you destroy sandstone blocks (applies to red sandstone as well) with an eff V pickaxe of any kind (no drops as per OP),
if you put a different block at the same position as the sandstone block you just destroyed,
the block will return to your hotbar (instantaneously, not picked up from the ground) and the sandstone will reappear at that position.

This is produced in version 1.12

**Comment by Titaniumtown** [comment]
I have had a similar issue as well @idomori

**Comment by KingCol13** [comment]
When I relog after mining the sandstone it reappears, so I think this is a de-sync issue. Perhaps the server not registering that they are mined while the client renders them as mined. Sandstone is very fast to mine with Eff V, maybe that's related.

**Comment by KingCol13** [comment]
I'm investigating this, should be fixed soon.

When blocks should be instantly mined, the client only sends a "started digging" packet (status 0) and no "finished digging" packet (status 2). These packets are received by `cClientHandle::HandleLeftClick` which then calls `cClientHandle::HandleBlockDigStarted` which then uses `cBlockInfo::IsOneHitDig(a_OldBlock)` to decide whether the block should be instantly broken. Currently which blocks are one-hittable are just listed as true/false in BlockInfo.cpp.

We need to take into account efficiency and other modifiers found here: https://minecraft.gamepedia.com/Breaking#Speed in the `IsOneHitDig` method, or replace it with one that does. A larger list of items which can be insta-mined and under which conditions can be found at https://minecraft.gamepedia.com/Instant_mining.
