### ISSUE TITLE
Questions about cuberite's strategy on the reimplementation of minecraft's mechanics, and the clashing behavior of different versions of minecraft

### ISSUE THREAD

**Issue by Titaniumtown** [cuberite/cuberite#4768]
So I've just thought of this. What's the strategy on reimplementating minecraft's mechanics? Should this project "improve" things where it can? Or replicate vanilla behavior as close as possible? 

Just as a thought experiment, say cuberite becomes completely vanilla-compatible, and is deployed on a server like 2b2t (just as an example of a server that greatly needs a performance boost). Some behavior would be 1.12.2+ like (for instance the upcoming PR #4545). At least I feel like the project should replicate the vanilla game as close as possible (bugs and all) to make the server more inciting for survival-based servers. 

Maybe to address this issue of wanting a drop in replacement with vanilla behavior, there could be different "modes" the server is set to. For instance a config file could have "MODE=cuberite" for the latest behavior, and "MODE=1.12.2-vanilla" for a 1.12.2 server that replicates vanilla functionality. And a "MODE=1.12.2-latest" for 1.12.2 functionality with vanilla-bugs fixed. This "1.12.2-vanilla" mode would replicate vanilla 1.12.2 bugs (like specific vanilla-only dupes and stuff).

And when new functionality is pushed (like #4545) it can be "turned on" when the mode that implements those features is specified.

Hope someone can understand this stream of consciousness.

Edit: thought of another solution (might not very ideal) we could split the project into other branches, so if someone needs a 1.8 server, they can download, and build the 1.8 branch

**Comment by tigerw** [comment]
This is certainly a thousand mile (km?) view :)
You know already that we're doing all we can to just keep up with Vanilla changes, and whether a feature mirrors vanilla or improves on it is at the discretion of the contributor. This does mean that users can only use the latest behaviour, but doing anything else might have to be another backlog task.

**Comment by mathiascode** [comment]
I don't feel like having different modes is a good idea, there are already too many config options. As for different branches, history shows that they will just end up abandoned in the end. In my opinion, we should introduce/change functionality as it appears in the latest vanilla version at that time.

**Comment by Titaniumtown** [comment]
Ok, thanks @tigerw and @madmaxoft for your input!
