### ISSUE TITLE
1.13 server "brand"

### ISSUE THREAD

**Issue by Titaniumtown** [cuberite/cuberite#4773]
Client version: 1.13
Server OS: Linux
Cuberite Commit id: d0f38f5

I was testing for #4539 and I noticed in the f3 menu that the server identifies itself as "null". I cant seem to find any info about it (or maybe i don't know the terminology) and what is needed to send that info. the f3 menu should display "cuberite".

**Comment by Pokechu22** [comment]
You need to send a [`minecraft:brand`](https://wiki.vg/Plugin_channels#minecraft:brand) plugin message (previously `MC|Brand`).

**Comment by Titaniumtown** [comment]
I will look into that, thanks! I'll try to make this a PR! I am still learning C++

**Comment by Titaniumtown** [comment]
Currently it has the line "SendPluginMessage("minecraft:brand", "\x08""Cuberite");"

Shouldn't that address the issue I'm having? I don't really know what's wrong! @tigerw do you know anything about this?

**Comment by tigerw** [comment]
If it's on 1.13, the implementation of SendPluginMessage is currently empty because the packet format changed, so nothing actually gets sent to the client. Still to be implemented :)

https://github.com/cuberite/cuberite/blob/4603c623c252f8ca561b0543d5dd74b5d7430a75/src/Protocol/Protocol_1_13.cpp#L182-L185

**Comment by Titaniumtown** [comment]
oh lol, didnt see that :)

**Comment by 12xx12** [comment]
I'd like to do that. 
I started writing my own sever for fun before i found your project

**Comment by 12xx12** [comment]
this can be closed - fixing commit was merged
