### ISSUE TITLE
Compiling errors on Ubuntu

### ISSUE THREAD

**Issue by icYFTL** [cuberite/cuberite#4777]
Client version: x.x.x
Server OS: Linux
Cuberite Commit id: d8406c7c58b1da053bf0c4d3d73429cd931082a7

### Expected behavior
Built server

### Actual behavior
Tried to build server with `COMPILING.md` on 2 VDS (Ubuntu 18.04 LTS & Ubuntu-20.04-amd64).
Got this at the end of building on both VDS:
`
...  
/usr/bin/ld: lib/liblualib.a(ldebug.c.o): plugin needed to handle lto object
/usr/bin/ld: lib/liblualib.a(linit.c.o): plugin needed to handle lto object
/usr/bin/ld: lib/liblualib.a(lstate.c.o): plugin needed to handle lto object
/usr/bin/ld: internal error ../../ld/ldlang.c 7101
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/Cuberite.dir/build.make:865: Server/Cuberite] Error 1
make[1]: *** [CMakeFiles/Makefile2:824: CMakeFiles/Cuberite.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

### Steps to reproduce the behavior
make

**Comment by tigerw** [comment]
Hm, looks like it's trying to invoke the stock `ld` on link time optimised objects, which it doesn't understand?

Try deleting your build folder and reconfiguring with `cmake -DWHOLE_PROGRAM_OPTIMISATION=No ..`

**Comment by icYFTL** [comment]
Danke, @tigerw

**Comment by tigerw** [comment]
No problem, though I wonder why cmake isn't finding the correct `ld`... 🤔
