### ISSUE TITLE
The End Dimension 

### ISSUE THREAD

**Issue by Titaniumtown** [cuberite/cuberite#4778]
What's going on with the end dimension? I tried going there, and when I got to the end, it was just a singular chunk full of end stone. Is anyone working on that?

**Comment by tigerw** [comment]
It's an artistic interpretation of the meaning of something.

Exactly *what* it's a meaning of you will have ample time to consider, seeing as the exit portal isn't generated.

**Comment by tigerw** [comment]
I don't think anyone's working on that right now.

**Comment by peterbell10** [comment]
Closing as duplicate of #4056

Someone would need to make a generator for end terrain and implement the dragon. Quite a bit of work I think.
