### ISSUE TITLE
Magic with webserver

### ISSUE THREAD

**Issue by icYFTL** [cuberite/cuberite#4779]
Client version: x.x.x
Server OS: Linux
Cuberite Commit id: d8406c7c58b1da053bf0c4d3d73429cd931082a7

### Expected behavior
Any reply from webserver

### Actual behavior
So. I upped the Cuberite on my VDS.

Also, I configured nginx for proxying.
```
location /minecraft {
                include proxy_params;
                proxy_pass http://localhost:5421;
        }

```
When I attached to the proccess, I got non default 404 reply.
![image](https://user-images.githubusercontent.com/27778089/87807238-b1957880-c860-11ea-8114-9be9c0d8c8b0.png)

When I'm trying to start the Cuberite in background I got 503 status code from nginx.

Server was built from source code:
`cmake -DWHOLE_PROGRAM_OPTIMISATION=No -DCMAKE_BUILD_TYPE=RELEASE ..`
`make -j`nproc``

### Steps to reproduce the behavior
`./Cuberite` or `./Cuberite &`

### Server log
```
...
Info [19:54:14] WebAdmin is running on port(s) 5421
     [19:54:14] Startup complete, took 1137ms!
     [19:54:19] Shutting down server...
     [19:54:20] Disabled Core!
     [19:54:20] Cleaning up...
     [19:54:20] Shutdown successful!
     [19:54:20] --- Stopped Log ---
```
Nginx log
```
[17/Jul/2020:19:54:17 +0300] "GET /minecraft_web HTTP/1.1" 200 52 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
```
Also, the same situation with curl on local.

**Comment by tigerw** [comment]
Did the server shut itself down or did you stop it?
Can you connect to it directly without the proxy?

**Comment by icYFTL** [comment]
@tigerw 

When I try to start the server in background `(with & parameter)` server shuts down by itself. But if I try to start the server without background - It works. I mean server works, I can join to it through minecraft client, but web-panel doesn't work. 

`Can you connect to it directly without the proxy?`
`Also, the same situation with curl on local.`

**Comment by tigerw** [comment]
For running the service as a dæmon, there's a `-d`/`--service` option: `./Cuberite --service`. Could you try that?

-----

Regarding potential bug with being placed into the background, this is what I'm getting (platform WSL, winver 19041)

`$ ./Cuberite &`

* Server starts.
* Connections are accepted, webadmin accessible.
* Server logs are printed to terminal despite being "in background".

Press ↵ carriage return.

* Message appears in terminal:
* `[1]+  Stopped                 ./Cuberite`
* Server stops responding to connections.

`$ fg`

* Message appears in terminal:

```./Cuberite
[12:59:22] Shutting down server...
[12:59:22] Disabled Core!
[12:59:22] Cleaning up...
[12:59:22] Shutdown successful!
[12:59:22] --- Stopped Log ---```

**Comment by icYFTL** [comment]
@tigerw, I also tried `-d`

**Comment by icYFTL** [comment]
Run `./Cuberite --service` helped. But nginx still return non default 404 error. Will try to solve it.

**Comment by madmaxoft** [comment]
Does nginx rewrite the URLs so they're root-based when they arrive at Cuberite? Because Cuberite expects and supports only being at the root of the virtual host.

I'm running Cuberite webserver behind an Apache forwarding server successfully, Cuberite is running in plain `http` mode (no certificate), Apache has a separate virtual host which it TLS-strips and forwards to Cuberite.

**Comment by madmaxoft** [comment]
Okay, closed, but what's the resolution?

**Comment by icYFTL** [comment]
> Okay, closed, but what's the resolution?

I think that trouble on my side, (invalid nginx proxying). Problem with background has been solved by `--service` flag. 

If I solve it, I send resolution here.
