### ISSUE TITLE
Change thread_local random generator to per-cWorld

### ISSUE THREAD

**Issue by tigerw** [cuberite/cuberite#4782]
Seems like every time we generate a random there is a call to `GetRandomProvider` which queries a thread local variable. Given most requests to get a random number are during World Tick and have access to the tick thread's cWorld, and accessing thread local storage isn't free, we should consider storing a per-World random generator, and calling the existing `GetTickRandomNumber` to access it.

Opening issue because I saw random generation take up ~5% CPU time in a profile, though not necessarily related.

**Comment by peterbell10** [comment]
What were you profiling? On an idle server then all it's doing is ticking random blocks in  the spawn area. The real heavy lifting is when players moving around and causing terrain generation, saving and loading chunks, lighting, etc.

**Comment by tigerw** [comment]
I had around a 20x20 chunk area loaded, was testing a redstone contraption.

Sure it's probably small but every lidl matters, right? don't want to do work we don't have to on the tick thread :)

**Comment by peterbell10** [comment]
Okay, but you'd save far more by not keeping a 20x20 chunk area loaded :) If it was loaded by a player then then the server would be doing a lot more work anyway, so I'm not sure the data point is relevant.

As for the overhead of TLS, compiler explorer tells me it's just a single memory load & add to get the address:
https://godbolt.org/z/M33o8M

More productive ways to improve random gen performance would be to use a faster random engine like [xoshiro256](https://en.wikipedia.org/wiki/Xorshift#xoroshiro128+) or [PCG](https://en.wikipedia.org/wiki/Permuted_congruential_generator).

**Comment by tigerw** [comment]
Those engines are really cool, thanks for the link!

it'd probably be more code if we're storing a RandomWrapper in there instead of an int but whatever, redstone's SolidBlock + Wire handling was far and away the biggest timesinks in that profile; I'll try to optimise them first.

**Comment by peterbell10** [comment]
>it'd probably be more code if we're storing a RandomWrapper in there instead of an int

The only difference between `thread_local` and `static` is how it calculates the address. For class types it will also check a guard variable to see if it's been constructed yet but that's also true for `static` in exactly the same way.

**Comment by tigerw** [comment]
ya sure but a cWorld member variable wouldn't be static
I believe we even had a m_TickRand in cWorld before that GetTickRandomNumber used, what happened to it?

**Comment by tigerw** [comment]
oh you removed it xD
#3754
nevermind then, accessing cWorld everywhere is probably too cubersome.
