### ISSUE TITLE
[Bug] respawn in water doesn't give you in water physics

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4787]
Client version: 1.13.2
Server OS: Windows
Cuberite Commit id: fb3d3dac1ec0f698e328b40fdcb0a483910b57a2

### Expected behavior
When logging out after death and then logging back in and then respwaning in water you should have wather physics and a "oxygen bar". Or it might have been me shuting down the server - might check that out and change issue

### Actual behavior
- no oxygen bar
- normal jumping physics
- no under water optical effects
- you get damage after the appropiate amount of time

### Steps to reproduce the behavior
- set you spwan point above water that deep you can drown
- die
- log out
- log back in
- respawn

**Comment by madmaxoft** [comment]
You know, when you close something, it's a nice habit to write the reason for the close.

**Comment by 12xx12** [comment]
@madmaxoft it seemed to be intended behaviour at tis point because the water physics were all over the play to none existent whatever i did

**Comment by mathiascode** [comment]
Currently an issue in 1.13.2.

**Comment by 12xx12** [comment]
@mathiascode shall i open this up again?

@madmaxoft sorry again for irritating you - I wasn't shure wether this was relevant or not
