### ISSUE TITLE
[BUG] Bone Meal in Dispenser changes crops from age 0 to age 7

### ISSUE THREAD

**Issue by 0ddlyoko** [cuberite/cuberite#4803]
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: 46398f4671012a0d913bd7bc0c70ffdc2645f2ac 

### Expected behavior
- It should goes from 0 to 2 - 4 and not directly to 7

### Actual behavior
- Crops go from age 0 to age 7

### Steps to reproduce the behavior
- Put Potato / Carrot / Seeds / Melon / Pumpkin on a farmland block
- Put a Dispenser that looks to the block above the farmland
- Put Bone Meal inside the Dispenser
- Power on the Dispenser

### Server log
```
/
```

**Comment by tigerw** [comment]
Thanks for all the testing :)

**Comment by 0ddlyoko** [comment]
> Thanks for all the testing :)
Np, I'll try to fix a lot of bugs when I have time 😄
