### ISSUE TITLE
Can't login to webadmin interface

### ISSUE THREAD

**Issue by platofan23** [cuberite/cuberite#4825]
Client version: x.x.x
Server OS: Linux/Raspbain
Cuberite Commit id: (Found at the top of the server's console output)

### Expected behavior
Logging in the webinterface working

### Actual behavior
[User:john]
Password=cuberiteRocks

[WebAdmin]
Ports=8080
Enabled=1

this is my webadmin.ini. But password and username Login is not working

### Steps to reproduce the behavior
Trying to login into the web interface

### Server log
```
Relevant part of server log
```

**Comment by tigerw** [comment]
I assume the server was restarted after setting the password?
Any weird invisible characters in the webadmin.ini file maybe? What's the file's line ending?
Can you attach the webadmin.ini file?

**Comment by tigerw** [comment]
Closing for now.
