### ISSUE TITLE
[Bug] No Noteblock Playback in 1.8.9

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4827]
Client version: 1.8.9
Cuberite Commit id: a3594f22c29f046ecb756b560da7fd5931dea970

### Expected behavior
Noteblocks Play sound

### Actual behavior
Noteblocks Play no sound. The animation is still there

### Steps to reproduce the behavior
- place noteblock
- right click it

**Comment by tigerw** [comment]
We're hardcoding protocol-specific soundeffect strings -.-

ENUMS! We need more ENUMS! >:D

**Comment by 12xx12** [comment]
I did some digging for something else and saw that the client supports also numeric identifiers  for sound values but this should be covered more easily then string stuff

**Comment by tigerw** [comment]
> This isn't implemented at all

This can be said for many things in Cuberite xD

**Comment by 12xx12** [comment]
I have the feeling the list of implemented things is shorter then the imaginary list of things to implement

**Comment by Pokechu22** [comment]
Noteblocks shouldn't be using sound effect packets at all; they should be using the [block action](https://wiki.vg/Block_Actions#Note_Block) ([pre-1.13](https://wiki.vg/index.php?title=Block_Actions&oldid=12934#Note_Block)).  That also triggers the particle effect, which doesn't happen with a sound effect packet.

**Comment by tigerw** [comment]
Tracked at #4827.

**Comment by tigerw** [comment]
@Pokechu22 remarkable consitency :P

> https://github.com/cuberite/cuberite/pull/3422#issuecomment-258701982
> 
> The noteblock usage of the block action packet was more recently documented (here).  You don't need to (and shouldn't) actually send a play sound packet in addition to the block action; if you do it'll create two of the same sound (effectively making it twice as loud as it should be, IIRC)

we should probably get to fixing this

**Comment by Pokechu22** [comment]
> Tracked at #4827.

Uh, this issue is #4827.  Was there a different one you were thinking of?

And I completely forgot I wrote that before :P

**Comment by tigerw** [comment]
i have failed ._.

Updated issue link, many thanks.

**Comment by tigerw** [comment]
@Pokechu22 I don't seem to be able to get the Block Action packet to play sounds at all, for noteblocks or pistons. They both perform their primary actions fine, spawning the quaver particle with the right colour or moving the piston, but completely silent.

**Comment by Pokechu22** [comment]
Hm, I'm not sure why that'd be.  The same code that spawns the particle plays the sound, and it should be loud enough that you can hear it.  It might be related to volume settings (in 1.9+, note blocks go into the records category; I don't know how it behaves in 1.8 and earlier, while cuberite might have been defaulting to specifying no category).

**Comment by tigerw** [comment]
Thanks. Where should Block Action specify the sound category, I'm only seeing the field listed for explicit sound effects. Do we need to declare something beforehand?

**Comment by tigerw** [comment]
Thanks for the tip about debugging, I tried with 1.12 (1.16 was too slow and timed out) and it sent Sound Effect as well as Block Action, didn't dig farther though.
