### ISSUE TITLE
[Bug] Saplings may be placed on top of each other

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4828]
Client version: 12.2.2
Server OS: Windows
Cuberite Commit id: a3594f22c29f046ecb756b560da7fd5931dea970

### Expected behavior
Saplings can't be placed on top of each other

### Actual behavior
You can place one sapling on top of another. if you place one next to the new one the new one breaks and drops the item

### Steps to reproduce the behavior
- place a sapling
- place another one on top of the first one
- change a block next to the newer one (breaking, placing,..., didn't check for block updates by a plant growing)

**Comment by tigerw** [comment]
Part of a wider issue, see #4239. Fix at #4256 but it needs some work.

**Comment by 12xx12** [comment]
Closed in favour of #4293
