### ISSUE TITLE
Trapdoors do not behave properly

### ISSUE THREAD

**Issue by grntbg** [cuberite/cuberite#4831]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a473e8ba52243a1a2a4f3aac840ed884d994fb0b

### Expected behavior
The position of trapdoors should be retained upon server restart.

### Actual behavior
Trapdoors reset to the horizontal orientation upon server restart.

### Steps to reproduce the behavior
1. Place a trapdoor.
2. Right-click on the trapdoor (putting it in the vertical orientation).
3. Restart the server (the trapdoor will once again be in the horizontal orientation).

**Comment by tigerw** [comment]
Redstone simulator, on chunk load sees the trapdoor as unpowered and closes it... I remember vanilla having a similar issue with trapdoors randomly closing; I wonder how they fixed it.

**Comment by tigerw** [comment]
Probably involves saving some redstone simulator state to world storage.
