### ISSUE TITLE
Auth with using ely.by alternative to Mojang type Authorization

### ISSUE THREAD

**Issue by DartPower** [cuberite/cuberite#4832]
Client version: 1.12.2
Server OS: Android
Cuberite Commit id: Last at time writing this issue (a473e8b)

How can i use this? If trying to change addressess, error SSL Handshake -0x2700 
https://docs.ely.by/ru/api.html

**Comment by Titaniumtown** [comment]
huh, never heard of el.by

**Comment by DartPower** [comment]
Russian open-source skin system and custom mojang api realisation

**Comment by Titaniumtown** [comment]
interesting. Is that breaking mojang's eula or something?

**Comment by Titaniumtown** [comment]
I would think so, because it would allow people to play for free or something :shrug:

**Comment by DartPower** [comment]
This is good decision for servers, where needs a custom skins for standart nicknames (e.g. Admin, Player1 and etc)

**Comment by Titaniumtown** [comment]
But is it against mojang's EULA?

**Comment by Titaniumtown** [comment]
nvm found this on their site:
> Developer carefully read the Mojang Account EULA and quite confidently declares that it does not violate, implementing alternative service for Minecraft. The EULA says that users may redistribute any modifications to the client, without charging a fee for it. This is what we are doing here.

**Comment by madmaxoft** [comment]
If their API follows the Mojang API to the letter, then it would be possible to use, simply by changing the `Authentication` settings in settings.ini. If that doesn't work, we can't really help much there.

Quite frankly, their documentation is very vague and this issue's description is so lacking that I have problems understanding what is really wanted.

**Comment by tigerw** [comment]
Certificate validation probably failed. ely.by is using Sectigo, which isn't in our hardcoded list.

@DartPower can you compile the server? You can try turning validation off:

https://github.com/cuberite/cuberite/blob/d2de029c024309b0ac2429373cc8ef2e56f880e0/src/Protocol/MojangAPI.cpp#L167

Change to `eSslAuthMode::None`.

**Comment by DartPower** [comment]
Please, can you make the "SSL Auth Mode" selection menu?
Like the "experimental option" or like that.

**Comment by tigerw** [comment]
I think it would be best to add the ely.by certificate chain, but I can't test their service because it apparently needs a client modification. However they claim to be Mojang-compatible so we could just YOLO it. :p
