### ISSUE TITLE
No noteblock playback on left click

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4839]
Client version: any
Server OS: any
Cuberite Commit id: d2de029c024309b0ac2429373cc8ef2e56f880e0

### Expected behavior
When left clicking a note block in survival you play back the sound without changing the pitch

### Actual behavior
no sound playback or a animation

### Steps to reproduce the behavior
- place noteblock
- go into survival
- left click on it

**Comment by ProjectBM** [comment]
Will take a look into this in the next few weeks.

**Comment by ProjectBM** [comment]
It seems like there are no note block handlers at the moment for a note block (it’s currently using `cDefaultBlockEntityHandler`). I plan to make a new class called `cBlockNoteBlockHandler` that inherits from `cBlockEntityHandler` and overrides the `OnDigging` function. 

Does that sound good to you?

**Comment by 12xx12** [comment]
yes - that's the thing to do 👍

**Comment by ProjectBM** [comment]
I can't seem to find any easy way to call `cNoteEntity::MakeSound()`. I found `cChunk::GetBlockEntity()` but the comment states that this should not be used directly.

The only idea I have at the moment is to add a function to `cChunkInterface` and `cChunkMap` to indirectly call  `GetBlockEntity()`. The added functions will have to directly check if the block entity is a note block and if so, calls `MakeSound()`.

I'm rather hesitant to change the infrastructure like this, so I was wondering if I should go with this approach or if there's something that I'm missing.

**Comment by 12xx12** [comment]
There is `cWorldInterface::DoWithBedAt`

**Comment by 12xx12** [comment]
You can create a lambda in which you check if the block entity is actually a note block then cast to noteblock and play the sound

**Comment by ProjectBM** [comment]
I'll take another look at it. Thanks for the help btw :D
