### ISSUE TITLE
Server crashes when I change world

### ISSUE THREAD

**Issue by t4dev** [cuberite/cuberite#4847]
Client version: 1.12.2
Server OS: Linux (raspberry pi os x32)
Cuberite Commit id:  a3b5cba6be4dd1dbdcc6a0ce7f52fc429912d042

### Expected behavior
I want TP to other world

### Actual behavior
When i type "portal world_the_end" or "portal world_nether" or "portal world" after few seconds after server starts, i get **Segmentation Fault**.

### Steps to reproduce the behavior
1. Buy RPi 4b+
2. Install RPi OS x32
3. Get Cuberite
4. Type "./Cuberite"
5. Wait 5+ secs
6. Type "/portal WORLDNAME"
7. Get the error
8. Enjoy!

### Server log
```
[23:**16:06**] Startup complete, took 712ms!
Info [23:**20:56**] Player teket4 has joined the game
[23:21:08] Player teket4 is executing command "/portal world_nether" in world "world" at world age 11265.
Warn [23:21:08] Entity at 0xa9e1f198 (cPlayer, ID 15) spawning in a non-existent chunk, the entity is lost.
Info [23:21:08] Player teket4 has left the game
Err  [23:21:08]   D:    | Cuberite has encountered an error and needs to close
Err  [23:21:08] Details | SIGSEGV: Segmentation fault
Err  [23:21:08] Cuberite Jenkins arm-linux-gnueabihf -DCMAKE_BUILD_TYPE=Release (master) build id: #25
Err  [23:21:08] from commit id: a3b5cba6be4dd1dbdcc6a0ce7f52fc429912d042 built at: Sun Aug 30 15:33:51 UTC 2020
Err  [23:21:08]   D:    | Cuberite has encountered an error and needs to close
Err  [23:21:08] Details | SIGABRT: Server self-terminated due to an internal fault
Err  [23:21:08] Cuberite Jenkins arm-linux-gnueabihf -DCMAKE_BUILD_TYPE=Release (master) build id: #25
Err  [23:21:08] from commit id: a3b5cba6be4dd1dbdcc6a0ce7f52fc429912d042 built at: Sun Aug 30 15:33:51 UTC 2020

```

**Comment by tigerw** [comment]
Thank you! Could you verify if it's fixed now?

**Comment by t4dev** [comment]
> Thank you! Could you verify if it's fixed now?
Yes, i downloaded cuberite again and its working correctly. Thanks
