### ISSUE TITLE
No End dimension

### ISSUE THREAD

**Issue by t4dev** [cuberite/cuberite#4848]
Client version: 1.12.2
Server OS: Linux (raspberry pi os x32)
Cuberite Commit id: a3b5cba6be4dd1dbdcc6a0ce7f52fc429912d042

### Expected behavior
Generate correct END dimension

### Actual behavior
Bad chunk 16x16x256
Also i **can't** generate new chunks
P.S I can't build END portal ( it doesn't activate )

### Steps to reproduce the behavior
Tp to the end

### Server log
```
I Warn [23:27:55] Cannot read world settings from "world_the_end/world.ini", defaults will be used.
Info [23:27:55] Chosen a new random seed for world: 529915631
     [23:27:55] -- Loading Plugins --
     [23:27:55] Initialised Core
     [23:27:55] -- Loaded 1 Plugin --
     [23:27:57] Preparing spawn (world_the_end): 59.25% (237/400; 236.76 chunks / sec)
Warn [23:27:57] World "world_the_end": Did not find an acceptable spawnpoint. Generated a random spawnpoint position at {0.00, 168.00, 0.00}

```

**Comment by tigerw** [comment]
A known issue, see #4056, unfortunately End generation isn't yet implemented.

**Comment by t4dev** [comment]
> Известная проблема, см. [# 4056](https://github.com/cuberite/cuberite/issues/4056) , к сожалению, конечное поколение еще не реализовано.

Okay :c
