### ISSUE TITLE
[BUG] Sugar Canes error

### ISSUE THREAD

**Issue by t4dev** [cuberite/cuberite#4849]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: 5e670a050bb263ec66227e572eaf9fe0a95ccf1c

### Expected behavior
[screenshot0](https://ibb.co/s37ghVY)

### Actual behavior
[screenshot1](https://ibb.co/nz5TQNF)

### Steps to reproduce the behavior
get sugar canes and place it anywhere

### Server log
...

**Comment by tigerw** [comment]
Looks like we're not checking for water, or general validity (not in air etc.) when placing sugarcane. Another manifestation of #4237 and the client not checking these placements for us anymore.
