### ISSUE TITLE
[BUG] Can't edit command blocks in 1.11/12/13

### ISSUE THREAD

**Issue by t4dev** [cuberite/cuberite#4850]
Client version: 1.12.2
Server OS: Linux armbian
Cuberite Commit id: 5e670a050bb263ec66227e572eaf9fe0a95ccf1c

### Expected behavior
Edit commands in MC 1.8.8+

### Actual behavior
In MC Clients 1.8+ I can't edit commands in command blocks.
When I destroy the command block, this destroyed without particles and etc.
But if I create and setup command block in 1.8.8 (for example) and activate it, when I connect with 1.12 commands execute succesfully :^/

### Steps to reproduce the behavior
Place cmdblock in 1.8.8
Connect with 1.12 (for example)
You can't eddit anything

### Server log
``,
no data about it in log
``,

**Comment by tigerw** [comment]
I think command block updates used to be via a plugin message, but at some point are now via a packet, but we haven't implemented the latter.

**Comment by tigerw** [comment]
Closing in favor of #3239
