### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JoshuaRogetsWithPieAndSauce** [cuberite/cuberite#4851]
When I get to run the ./cuberite it says right after "Segmentation fault". I'm running the precompiled script on a raspberry pi 0 w running raspian lite. Fresh install.

**Comment by Titaniumtown** [comment]
Did you try and compile it yourself?

**Comment by JoshuaRogetsWithPieAndSauce** [comment]
i dit once complied it but it took 5 hrs. it was sucessful but i couldn't find a executable file.

**Comment by 12xx12** [comment]
the cuberite binary is put into %YourCompileFolder%/Server. All other needed files are also copied to that folder

**Comment by madmaxoft** [comment]
Unfortunately the official build doesn't run on the Pi Zero, because the CPU is slightly different there. You really need to compile (or cross-compile) for that platform yourself. Probably @bearbin can give more info / link the main report.

**Comment by JoshuaRogetsWithPieAndSauce** [comment]
Okay. Sorry I'm a beginner to cuberite. I will ask him now for some instructions

**Comment by JoshuaRogetsWithPieAndSauce** [comment]
Are you basically saying I need to get a special version for this program. I also want to know why it said segmentation error. 


(If you can. Could you lis5 any way to get a mc server oon a pi 0)

**Comment by madmaxoft** [comment]
The CPU on the Pi Zero doesn't have a few instructions that the other Pi CPUs have, so when a program (targeted at the other Pi-s) uses such instruction, it aborts with a segfault. That's the gist of it.

**Comment by JoshuaRogetsWithPieAndSauce** [comment]
I'm managed to get it working from what tigerw referenced. Thanks guys for your help.
