### ISSUE TITLE
Compile Cuberite on Linux x86_64 machine for ARM64

### ISSUE THREAD

**Issue by PT400C** [cuberite/cuberite#4853]
Hey,

do you recommend cross-compiling Cuberite to ARM64 or the straight-forward approach of using an ARM64 machine to compile it?

(The system I would like to compile Cuberite for is a rPi 4)

**Comment by Titaniumtown** [comment]
I just use my raspberry pi 4 to compile it. shouldn't take long.

**Comment by bearbin** [comment]
If you have access to the machine you want to run Cuberite on, direct compilation is much preferable.

Fiddling around with getting the correct crossc-compiler installed and working will take up much more time than waiting an hour (in the worst case!) for compilation to happen. The only time cross-compiling makes sense is if you _really_ need the speed, you don't have the hardware to spare, or you don't have the necessary compilers/priviliges on the machine you want to use.

**Comment by bearbin** [comment]
Oh, another thing for anyone else who comes across this issue - compiling Cuberite yourself is not essential, and builds are available from https://cuberite.org for the most used architectures (including Raspberry Pis).
