### ISSUE TITLE
Segmentation Fault upon first run

### ISSUE THREAD

**Issue by Picajoluna** [cuberite/cuberite#4854]
Client version: latest (just downloaded twenty minutes ago!)
Server OS: (Raspberry Pi Zero W) (Debian) `Linux version 5.4.51+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1333 Mon Aug 10 16:38:02 BST 2020`
Cuberite Commit id: I couldn't find the commit id, nothing opens, the program just segfaults.

### Expected behavior
Running ./Cuberite should launch the Cuberite program.

### Actual behavior
Cuberite crashes upon executing ./Cuberite and outputs `Segmentation Fault`.

### Steps to reproduce the behavior
Run the Cuberite executable.

### Server log
Here is my entire process, from installation to run:
```bash
pi@raspberrypi:~ $ mkdir Minecraft
pi@raspberrypi:~ $ cd Minecraft/
pi@raspberrypi:~/Minecraft $ curl -sSfL https://download.cuberite.org | sh
Identifying kernel: Linux
Identifying platform: armv6l
Downloading precompiled binaries.
Done.
Cuberite is now installed, run using 'cd Server; ./Cuberite'.
pi@raspberrypi:~/Minecraft $ ll
total 5780
drwxr-xr-x  7 pi pi    4096 Sep 10 10:49 .
drwxr-xr-x 17 pi pi    4096 Sep 10 10:49 ..
-rw-r--r--  1 pi pi     389 Sep  9 19:18 BACKERS
-rw-r--r--  1 pi pi    2748 Sep  9 19:18 brewing.txt
-rw-r--r--  1 pi pi     126 Sep  9 19:35 buildinfo.txt
-rw-r--r--  1 pi pi    1313 Sep  9 19:18 CONTRIBUTORS
-rw-r--r--  1 pi pi   58733 Sep  9 19:18 crafting.txt
-rwxr-xr-x  1 pi pi 5742824 Sep  9 19:35 Cuberite
-rw-r--r--  1 pi pi    2233 Sep  9 19:18 favicon.png
-rw-r--r--  1 pi pi    8484 Sep  9 19:18 furnace.txt
-rw-r--r--  1 pi pi   26108 Sep  9 19:18 items.ini
-rw-r--r--  1 pi pi   11641 Sep  9 19:18 LICENSE
-rw-r--r--  1 pi pi    3009 Sep  9 19:18 monsters.ini
drwxr-xr-x 11 pi pi    4096 Sep  9 19:18 Plugins
drwxr-xr-x  4 pi pi    4096 Sep  9 19:18 Prefabs
drwxr-xr-x  5 pi pi    4096 Sep  9 19:18 Protocol
-rw-r--r--  1 pi pi     692 Sep  9 19:18 README.txt
drwxr-xr-x  2 pi pi    4096 Sep  9 19:18 ThirdPartyLicenses
drwxr-xr-x  3 pi pi    4096 Sep  9 19:18 webadmin
pi@raspberrypi:~/Minecraft $ ./Cuberite 
Segmentation fault
pi@raspberrypi:~/Minecraft $ 
```

Should I be running sudo on `curl -sSfL https://download.cuberite.org | sh` or on the Cuberite executable?  All of the files seem to be correctly downloaded.
I am on also on university wifi -- I don't know whether this impacts anything (though I don't think it should).

Sorry, I'm completely new to this community and wanted to give Cuberite a spin on my raspberry pi, yet it seems that's not working. Thanks for the help.

**Comment by tigerw** [comment]
Nice timing :)

The precompiled builds aren't compatible with Pi Zero, see #4851.

Could you try the steps in the linked issue #4774?
