### ISSUE TITLE
Bed is placeable on top of one block, which it shouldn't

### ISSUE THREAD

**Issue by theophriene** [cuberite/cuberite#4860]
Client version: 1.10.2
Server OS: linux
Cuberite Commit id: approx: c2f8ceb554982a33bcd4a1e168f6c4e26d0b85dd built at: approx: 2020-09-05 17:13:44 +0200

### Expected behavior
Bed cannot be placed on top of one block

### Actual behavior
The opposite 
![2020-09-12_03 43 11](https://user-images.githubusercontent.com/60849082/92981356-02a0a200-f489-11ea-9d67-96688e8b523f.png)

**Comment by tigerw** [comment]
Minecraft Wiki says

> In Java Edition, beds do not require supporting blocks and can be placed anywhere, provided there is enough room.
> https://minecraft.gamepedia.com/Bed#Placement

Is it outdated?

**Comment by tigerw** [comment]
Tried this on 1.16.3 and beds place anywhere.

**Comment by tigerw** [comment]
There is multiprotocol support but game functionality follows the latest Minecraft behaviour :)

**Comment by theophriene** [comment]
Oops, sorry then. I only compared the behavior against vanilla 1.10.2. It's solved then
