### ISSUE TITLE
Detector rail replaces neighboring rails

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#4861]
Client version: 1.10.2
Server OS: linux
Cuberite Commit id:  approx: c2f8ceb554982a33bcd4a1e168f6c4e26d0b85dd built at: approx: 2020-09-05 17:13:44 +0200

### Steps to reproduce the behavior
1. Place detector rail next to or in between the track
![2020-09-12_03 59 56](https://user-images.githubusercontent.com/60849082/92981811-0503fb80-f48b-11ea-90f3-00c021786c51.png)

2. Place minecart on top of detector rail to activate it
![2020-09-12_03 59 59](https://user-images.githubusercontent.com/60849082/92981814-07feec00-f48b-11ea-8c5e-f96d35cf4aea.png)

3. Place minecart on top of the neighboring rail segment
![2020-09-12_04 00 03](https://user-images.githubusercontent.com/60849082/92981822-0fbe9080-f48b-11ea-8e8c-d746754e76e5.png)

4. Rail segment warps, creating a turn
![2020-09-12_04 00 14](https://user-images.githubusercontent.com/60849082/92981826-14834480-f48b-11ea-899f-a3604d61eb6e.png)

5. Destroy second minecart and the warped segment becomes the detector rail
![2020-09-12_04 00 27](https://user-images.githubusercontent.com/60849082/92981836-1baa5280-f48b-11ea-921c-1d4dbe364b71.png)
![2020-09-12_04 01 44](https://user-images.githubusercontent.com/60849082/92981848-2c5ac880-f48b-11ea-9221-6dd99a4f54f6.png)

**Comment by tigerw** [comment]
Looks like minecarts are SetBlock'ing detector rails where they shouldn't, possibly related issue #3049.
