### ISSUE TITLE
Piston base (ID 33:8-13) becomes passable through during extension/retraction animation

### ISSUE THREAD

**Issue by theophriene** [cuberite/cuberite#4865]
Client version: 1.10.2
Server OS: Linux
Cuberite Commit id: d9d71e1de65e5e46d02190667ee02776a6f641c6 built at: approx: 2020-09-13 14:44:20 +0100

#### Without WorldEdit
1.  Create a setup like this
![2020-09-14_21 56 08](https://user-images.githubusercontent.com/60849082/93121762-eb45fc80-f6b4-11ea-84fa-04d1e0ae36e8.png)
2. Stand next to the piston, and activate the lever, while holding W
![2020-09-14_21 56 25](https://user-images.githubusercontent.com/60849082/93121954-395b0000-f6b5-11ea-968d-b7f68732cf46.png)
3. Extension animation is played during which player can move forward into the piston base block, resulting in this. 
![2020-09-14_21 56 54](https://user-images.githubusercontent.com/60849082/93122067-6b6c6200-f6b5-11ea-8b4e-15a1d44734da.png)
4. If didn't work during extension, try flipping the lever a couple of times, while moving towards the lever. In my experience, it works better during the retraction.

#### With WorldEdit
1. Put a block of ID of anything from  33:9 through 33:13 (33:8 also works, but the setup is different, as during the retraction it'll push the player up )
![2020-09-14_22 11 58](https://user-images.githubusercontent.com/60849082/93122366-df0e6f00-f6b5-11ea-9cdb-80bdfad66bff.png)
2. Jump on top of it
![2020-09-14_22 12 03](https://user-images.githubusercontent.com/60849082/93122551-357bad80-f6b6-11ea-9721-4cebd6ab7e20.png)
3. Put/Destroy any of the adjacent blocks, causing block update
![2020-09-14_22 12 08](https://user-images.githubusercontent.com/60849082/93122576-41676f80-f6b6-11ea-9659-a9728be082f2.png)
4. During BU, when piston realizes it's no longer powered, retraction animation is played, during which
player is pushed into the space piston base occupies.

Update:
It seems to not work if there's no solid block behind the piston which would stop the player from being pushed out and behind the piston

**Comment by theophriene** [comment]
I don't know for sure, but looking up I found this #3696.
Because, when running OptiFine version of minecraft, which does heavy optimization on network - the pistons do in fact turn invisible during animation
![2020-09-14_15 24 11](https://user-images.githubusercontent.com/60849082/93126686-36174280-f6bc-11ea-8cc4-8ce64f7aa342.png)
![2020-09-14_15 21 15](https://user-images.githubusercontent.com/60849082/93126692-37486f80-f6bc-11ea-811a-af56e8e22d88.png)
![2020-09-14_15 21 14_6](https://user-images.githubusercontent.com/60849082/93126695-37e10600-f6bc-11ea-80ff-5816874e466c.png)
![2020-09-14_15 21 14_7](https://user-images.githubusercontent.com/60849082/93126700-39aac980-f6bc-11ea-9816-15e2a1a82471.png)

**Comment by theophriene** [comment]
Turns out It also works in vanilla, though the gap before block reappearance is smaller

![2020-09-15_00 01 49_2](https://user-images.githubusercontent.com/60849082/93132516-55ff3400-f6c5-11ea-898c-441058de1328.png)
![2020-09-15_00 01 48_2](https://user-images.githubusercontent.com/60849082/93132527-5ac3e800-f6c5-11ea-8aef-7f2d37d72024.png)

**Comment by tigerw** [comment]
Thanks for the detailed investigation. It looks like our piston animation behaviour isn't when the vanilla client expects.

**Comment by theophriene** [comment]
Possibly related:
By placing a piston in non-default rotation, it's very hard but possible to cause it's extension animation before it's realigned properly, resulting in this:

![2020-09-15_03 52 35](https://user-images.githubusercontent.com/60849082/93149308-7e972600-f6e5-11ea-9b55-a654118fd01d.png)

Found out by having a faulty mouse w/ double-clicking right button)

**Comment by theophriene** [comment]
## UPDATE: The base is removable during the animation
### Setup
1. ![2020-09-17_05 45 59](https://user-images.githubusercontent.com/60849082/93410333-51cf4400-f888-11ea-90f2-da6c21e0231f.png)
2. ![2020-09-17_05 47 52](https://user-images.githubusercontent.com/60849082/93410331-5136ad80-f888-11ea-8f81-8af5405417d8.png)
3. ![2020-09-17_05 48 00](https://user-images.githubusercontent.com/60849082/93410326-4f6cea00-f888-11ea-916d-eeaf9ef016f0.png)
4. ![2020-09-17_05 48 27](https://user-images.githubusercontent.com/60849082/93410324-4e3bbd00-f888-11ea-97dd-7f8fd181fcf6.png)

**Comment by tigerw** [comment]
I assume it's not just clientside?

**Comment by theophriene** [comment]
After some testing, looks like it is. And the last one as well.

**Comment by theophriene** [comment]
Confirmed to be client-side error. Not reproducible in 1.13.

**Comment by tigerw** [comment]
Many thanks again for the detailed testing.
