### ISSUE TITLE
[Unimportant] Top block of tall grass and double fern temporarilybecomes peony top block when the bottom block is replaced

### ISSUE THREAD

**Issue by theophriene** [cuberite/cuberite#4879]
Client version: 1.10.2
Server OS: Linux
Cuberite Commit id: 53549a1a4ce320c1e3f449165c290c74d3de54d4

###
![2020-09-17_03 46 52](https://user-images.githubusercontent.com/60849082/93403476-2a23b000-f877-11ea-9503-66704d3ba577.png)
![2020-09-17_03 46 56](https://user-images.githubusercontent.com/60849082/93403475-298b1980-f877-11ea-8893-05ebec1a4551.png)
![2020-09-17_03 47 00](https://user-images.githubusercontent.com/60849082/93403474-2859ec80-f877-11ea-8eb7-519e568d554b.png)

**Comment by Pokechu22** [comment]
This is a [vanilla issue](https://bugs.mojang.com/browse/MC-53439 "[MC-53439] The top block of a two-block plant temporarily becomes a peony/sunflower upon placing a block in the bottom") fixed in 1.13.

**Comment by theophriene** [comment]
Oh, my bad, then. Thanks.
