### ISSUE TITLE
Wolfes sometimes loose color on collar on server restart

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4884]
Client version: 1.11.1
Server OS: Windows
Cuberite Commit id: 53549a1a4ce320c1e3f449165c290c74d3de54d4

### Expected behavior
Collars can be colored and should keep their color on server restart

### Actual behavior
Color loss on restart

### Steps to reproduce the behavior
- tame wolf
- color collar
- stop server
- restart

**Comment by tigerw** [comment]
I can't reproduce this, was there a specific colour that you used? The code to save colours is definitely there.

Could you try executing `save-all` in the console before restarting?

**Comment by 12xx12** [comment]
I used light blue.

And gonna do this then. I used the stop command from console to stop the server

**Comment by 12xx12** [comment]
yeah - false alarm - i tried it again... did work. Same color, same minecraft version, ...

**Comment by tigerw** [comment]
Oh boy. We have a race condition between the Server tick thread queueing a save-all onto the World thread on shutdown, and the World thread being stopped on shutdown, thereby no longer processing any queued tasks.
