### ISSUE TITLE
The damage type dtEnvironment is not handled in cEntity::ArmorCoversAgainst

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4898]
Client version: 1.12.2

### Expected behavior
Server should not crash if a enderman gets wet or a snowman is created in nether world.

### Actual behavior
Server crashes with `Unsupported damage type` in method [cEntity::ArmorCoversAgainst](https://github.com/cuberite/cuberite/blob/55672ca5b3f63f31e6d7f09c8618ed6f167d2370/src/Entities/Entity.cpp#L621)

### Steps to reproduce the behavior
Place a enderman in water or create a snowman in nether world

**Comment by 12xx12** [comment]
whoops - gonna change that
