### ISSUE TITLE
Add boss health bar

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4915]
Cuberite Commit id: 23bca008317e125659d4b97f29cf13da81a7aecd

The ender dragon and the Wither have a health bar popping up on the players hud. this is also modifyable in the comman /bossbar

https://minecraft.gamepedia.com/Commands/bossbar

I didnt find any documentation on the bar itself sadly

**Comment by KingCol13** [comment]
https://wiki.vg/Protocol#Boss_Bar
