### ISSUE TITLE
Add daylight detector functionality

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4918]
Cuberite Commit id: 23bca008317e125659d4b97f29cf13da81a7aecd

https://minecraft.gamepedia.com/Daylight_Detector

**Comment by tigerw** [comment]
This was a feature that got left out when we migrated to IncrementalRedstoneSimulator, I think there was a issue for it somewhere...

**Comment by tigerw** [comment]
Maybe it was just mentioned. Anyway thanks!

**Comment by 12xx12** [comment]
i searched the issues for daylight didn't find anything :(

**Comment by tigerw** [comment]
Me neither xD
