### ISSUE TITLE
Add new colored glass pane recipe

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4922]
Cuberite Commit id: 23bca008317e125659d4b97f29cf13da81a7aecd

In minecraft 1.14 it was added that you can craft colored glass panes from uncolored

https://minecraft.gamepedia.com/Glass_Pane

**Comment by ProjectBM** [comment]
Can I have a go at this? 

I think this mostly involves adding recipes to the crafting.txt file.

**Comment by 12xx12** [comment]
You can try this. I tried this for myself but the ingame testing wasn't cussecfull.

Have a go at it. Although i'm not sure if the client itself is dening the recipies
