### ISSUE TITLE
Button functionality error after server update.

### ISSUE THREAD

**Issue by blueyshark** [cuberite/cuberite#4945]
Client version: 1.12
Server OS: DietPi
Cuberite Commit id: unsure, updated to latest armhf

### Expected behavior
Before DietPi OS server migration, button next to doors opened doors.

### Actual behavior
Since the migration and update, buttons only function when placed on the floor, or on the door itself. Video supplied here: https://drive.google.com/file/d/1tR848hIoUCOupkW3JVtf5fFGRBNYPxgt/view?usp=sharing

### Steps to reproduce the behavior
Install Cuberite on Raspi DietPi distro, copy Cuberite data folder to another/fresh instance of Cuberite on Raspi DietPi.

### Server log
Warn [14:29:30] Error in <attached> calling function <callback>()
Warn [14:29:30] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
Warn [14:29:30] Stack trace:
Warn [14:29:30]   Plugins/Core/worldlimiter.lua(8): (no name)
Warn [14:29:30] Stack trace end
Warn [14:29:30] Error in <attached> calling function <callback>()
Warn [14:29:30] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
Warn [14:29:30] Stack trace:
Warn [14:29:30]   Plugins/Core/worldlimiter.lua(8): (no name)
Warn [14:29:30] Stack trace end
Warn [14:29:30] Error in <attached> calling function <callback>()
Warn [14:29:30] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
Warn [14:29:30] Stack trace:
Warn [14:29:30]   Plugins/Core/worldlimiter.lua(8): (no name)
Warn [14:29:30] Stack trace end
Warn [14:29:30] Error in <attached> calling function <callback>()
Warn [14:29:30] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
Warn [14:29:30] Stack trace:
Warn [14:29:30]   Plugins/Core/worldlimiter.lua(8): (no name)
Warn [14:29:30] Stack trace end
Warn [14:29:30] Error in <attached> calling function <callback>()
Warn [14:29:30] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
```
Relevant part of server log
```

**Comment by 12xx12** [comment]
Thank you for your issue!

Out of curiosity:
- did you already try the same thing at another position?

**Comment by blueyshark** [comment]
> 
> 
> Thank you for your issue!
> 
> Out of curiosity:
> 
>     * did you already try the same thing at another position?

It seems to affect all my doors!

**Comment by KingCol13** [comment]
@tigerw we think @blueyshark was using an old version when he found this. It’d be great if you could let us know if you can reproduce this on the latest version @blueyshark.

**Comment by tigerw** [comment]
I can, it's a redstone sim bug :P

**Comment by tigerw** [comment]
No idea about the server log errors though, a potential Core issue?

**Comment by mathiascode** [comment]
The Core issue was most likely fixed in the latest version of the Core plugin. @blueyshark can you update the Core plugin and confirm? https://github.com/cuberite/Core
