### ISSUE TITLE
Cooked chicken ID mismatch

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4948]
Client version: 1.12.1
Server OS: Windows/Linux/macOS/BSD/...
Cuberite Commit id: 8eca58a1c9d3ea928b301de1ad772a46164372e1

### Expected behavior
External ID of cooked chicken = 412

### Actual behavior
Internal ID = 366

**Comment by mathiascode** [comment]
I'm not sure I understand. Item ID 412 has always been used for cooked rabbit, hasn't it?

**Comment by 12xx12** [comment]
Yeah - my bad... it was cooked rabit
