### ISSUE TITLE
I don't know where to  start reading the code

### ISSUE THREAD

**Issue by FrankHan052176** [cuberite/cuberite#4962]
I want to help develop version 1.13.2 of cuberite，but I can't find where to start.Could you briefly list the ideas？（I am Chinese, and there may be grammatical errors in writing English😀）

**Comment by KingCol13** [comment]
Hello and welcome! Thanks for looking to contribute, I'm not working on the transition to 1.13.2 myself but a good place to start looking is here: https://forum.cuberite.org/thread-3313.html

Best of luck :)

**Comment by tigerw** [comment]
Specifically 1.13.2 clients can already connect

**Comment by bearbin** [comment]
Thanks for your interest in Cuberite! KingCol13 had a good suggestion with the forum, but you should also be aware we have a Discord server if you prefer that: https://cuberite.org/discuss/

I'm going to close this issue as it isn't strictly an 'issue' with Cuberite as such, but feel free to keep on the discussion here if you would like.
