### ISSUE TITLE
Publish source releases

### ISSUE THREAD

**Issue by handow23** [cuberite/cuberite#4965]

**Comment by bearbin** [comment]
Can you explain precisely what you mean with this issue? Cuberite is already open source and is the source is available to download for free (from GH, or from the buildserver).

**Comment by bearbin** [comment]
Nevermind, I looked at your profile and I can see where you're actually coming from: https://github.com/void-linux/void-packages/issues/24801

Cuberite is distributed on a rolling-release basis and we currently have no desire to generate versioned releases, until the software is stabilised.
