### ISSUE TITLE
Water doesn't stop tnt from damaging blocks

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4966]
Client version: any
Server OS: Windows´
Cuberite Commit id: 64f4a41b1ba5a4f12ce0b1a330a82edb6b5ca251

### Expected behavior
Tnt shouldn't destroy any blocks when exploding in water

### Actual behavior
Tnt breaks some blocks but not as much as if it's ignited out of water

### Steps to reproduce the behavior
- ignite tnt below water

**Comment by tigerw** [comment]
Could you screenshot your setup?

**Comment by 12xx12** [comment]
i can't reproduce :/

**Comment by tigerw** [comment]
：P

could be some sort of floating point rounding error, or maybe the TNT drifted into a block or something? If it's the latter #4776 might fix.

**Comment by 12xx12** [comment]
It might be - I saw a tnt floating into another block

**Comment by 12xx12** [comment]
closing this - can't be recreated. Might be related to #4776
