### ISSUE TITLE
No lighting from beacon across chunk borders after server restart

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4971]
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: a9031b6bae742b333b1b390192fa590f2ecb07ea

### Expected behavior
Light around the beacon

### Actual behavior
![2020-10-07_13 40 13](https://user-images.githubusercontent.com/44411062/95326512-01557000-08a3-11eb-8ef6-0ded4016719f.png)

### Steps to reproduce the behavior
Set up beacon

**Comment by tigerw** [comment]
It looks, at least similar, to https://github.com/cuberite/cuberite/issues/134#issuecomment-75716741
Is it just beacons?

**Comment by 12xx12** [comment]
I didn't check this further - gonna do this

**Comment by 12xx12** [comment]
So I did some further testing... torches seem to work
![2020-10-09_10 33 44](https://user-images.githubusercontent.com/44411062/95561456-0e956a80-0a1b-11eb-99ea-5c809cf32c14.png)

I found some other funky bugs
![2020-10-09_10 32 34](https://user-images.githubusercontent.com/44411062/95561451-0d643d80-0a1b-11eb-8109-1ab40ca50ec9.png)
![2020-10-09_10 32 19](https://user-images.githubusercontent.com/44411062/95561448-0b9a7a00-0a1b-11eb-8412-904cfd3ed705.png)

**Comment by 12xx12** [comment]
![2020-10-10_22 49 48](https://user-images.githubusercontent.com/44411062/95664756-089ea700-0b4b-11eb-9271-6d3d40b5e1bd.png)

**Comment by tigerw** [comment]
Definitely looks like #134.

**Comment by 12xx12** [comment]
So do we close this as a duplicate

**Comment by bearbin** [comment]
Yep, this definitely looks like the same issue.
