### ISSUE TITLE
Nether portal being unlit on other side

### ISSUE THREAD

**Issue by OwenJF** [cuberite/cuberite#5007]
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: 2231

Nether portal should be lit on other side.

Nether portal is not lit on other side

Make nether portal, light, go through, other side is not lit.

**Comment by OwenJF** [comment]
Checking if has already been reported, may delete.

**Comment by tigerw** [comment]
Thanks!

Looks like Nether Portal generation relied incorrectly on SetBlock executing block handlers:

https://github.com/cuberite/cuberite/blob/64442b05f8aa39918f5cb75503c7f57b0bd62827/src/NetherPortalScanner.cpp#L266-L267

Changing it to `m_World.PlaceBlock` should do the trick. Would you like to try? :)

**Comment by cflep** [comment]
I'm gonna try (it's my second contribution ever)
