### ISSUE TITLE
Nether portal can be lit in the end

### ISSUE THREAD

**Issue by DrexYiii** [cuberite/cuberite#5009]
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: 2231

Nether portal just doesn't work in the end

Nether portal light-able though useless

Create nether portal outline in end, light it

**Comment by cflep** [comment]
Nether portals shouldn't be able to be lit in the end. I'm trying to fix it

**Comment by cflep** [comment]
I'm not sure where changes need to be made, I tried various things in src/NetherPortalScanner.cpp , but nothing changed. Any ideas?

**Comment by tigerw** [comment]
The code that makes the portal is in Blocks\BlockFire.h, also I think a similar issue exists for end portals (Items\ItemEyeOfEnder.h)

**Comment by cflep** [comment]
I've checked, the end portal can be lit in the nether like it should

**Comment by 12xx12** [comment]
Closed in #5068
