### ISSUE TITLE
Disabling checking breaking a bedrock is possible?

### ISSUE THREAD

**Issue by DartPower** [cuberite/cuberite#5022]
Disabling checking breaking a bedrock is possible?
Or write the simple cfg rule(s)? 
https://github.com/cuberite/cuberite/blob/3381c0f6d6671a485283c889b036c0a431e2a2b9/src/ClientHandle.cpp#L1359

**Comment by tigerw** [comment]
If you can compile the server yourself you could delete the check and change bedrock's hardness to zero.

Otherwise you should be able to write a plugin that will SetBlock the bedrock to air when a player clicks on it. [HOOK_PLAYER_LEFT_CLICK](https://api.cuberite.org/OnPlayerLeftClick.html) should work.

**Comment by DartPower** [comment]
It will probably be silly and ashamed to ask, but ...
Can I ask you to write a very simple script?
I don't know Lua very well.

**Comment by tigerw** [comment]
Try this

```lua
function Initialize(Plugin)
	Plugin:SetName("Rockdigger")
	Plugin:SetVersion(1)

	cRankManager:AddGroup("Rockdigger")
	cRankManager:AddPermissionToGroup("Can mine bedrock", "Rockdigger")
	cRankManager:AddGroupToRank("Rockdigger", "Admin")

	cPluginManager.AddHook(cPluginManager.HOOK_PLAYER_LEFT_CLICK, OnLeftClick)

	LOG("Initialized " .. Plugin:GetName() .. " v." .. Plugin:GetVersion())
	return true
end

function OnLeftClick(Player, BlockX, BlockY, BlockZ, BlockFace, Action)
	-- Action == 0 means digging start
	-- http://wiki.vg/Protocol#Player_Digging
	if Action ~= 0 or not Player:HasPermission("Can mine bedrock") then
		return false
	end

	local World = Player:GetWorld()
	local Position = Vector3i(BlockX, BlockY, BlockZ)

	if World:GetBlock(Position) == E_BLOCK_BEDROCK then
		World:SetBlock(Position, E_BLOCK_AIR, 0)
	end
	return false
end
```

Make a plugin.lua file in `Server/Plugins/Rockdigger/plugin.lua` and change `Server\settings.ini` to load it with `Rockdigger=1` under `[Plugins]`

**Comment by DartPower** [comment]
Thanks a lot! 😃

**Comment by tigerw** [comment]
hopefully it works... :p

**Comment by tigerw** [comment]
oh crud, we actually have a bug. The server just kicks a client the moment they even click on bedrock. That shouldn't happen.
