### ISSUE TITLE
Make cIniFile properly parse newline characters

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#5026]
It's currently impossible to add newline characters (`\n`) inside ini file values. Cuberite will use the characters litterally. Instead it would be nice to make Cuberite handle the newlines like actual newlines. The best place to do this would probably be the [ReadFile](https://github.com/cuberite/cuberite/blob/master/src/IniFile.cpp#L149) and [WriteFile](https://github.com/cuberite/cuberite/blob/master/src/IniFile.cpp#L226) functions. Otherwise all `GetValue` and `GetValueSet` variants would have to be updated.

**Comment by goelm08** [comment]
Hi, I would like to work on this issue

**Comment by bearbin** [comment]
Please do, since there is nobody already working on this you can just submit a PR when you're done :)

**Comment by JoeParimucha** [comment]
Hi, I would like to work on this issue to see if I can help if it has not been solved yet!

**Comment by 12xx12** [comment]
Hi,

feel free to do so. This issue hasn't been resolved
