### ISSUE TITLE
Mobs Y position glitch - 1.8.9

### ISSUE THREAD

**Issue by Day-OS** [cuberite/cuberite#5030]
Client version: 1.8.9
Server OS: Windows 10 Pro
Cuberite Commit id: 14a00d0051d9c0f97105145bd2ecf7679bb015a3

### Expected behavior
Mobs walking on the floor normally.

### Actual behavior
When using 1.8.9, Mobs Y axis gets crazy and makes them float. I've just tested in 1.8.9 and 1.12, It just happened with 1.8.9. Me and a friend were seeing the mobs at the same height, but it wouldn't happen with a newer minecraft version. Another thing to note is that horses that were floating became unridable, when interacted, it resets your camera position. 

![](https://cdn.discordapp.com/attachments/236576027646623746/776437894466109440/unknown.png)
![](https://cdn.discordapp.com/attachments/236576027646623746/776439656887222282/unknown.png)
![](https://cdn.discordapp.com/attachments/236576027646623746/776441097441640498/unknown.png)

### Steps to reproduce the behavior
Use 1.8.9 Vanilla and just walk thru the map watching the mobs as they will **somehow** render floating.

### Server log
Nothing was shown in the log, as it was client-sided.

**Comment by tigerw** [comment]
Int8 relative moves build up too much imprecision; we should probs have a counter that after X relatives send a teleport (absolute position) to resynchronise.

https://github.com/cuberite/cuberite/blob/280f7a81f4a6ec2c59768036b7e8ad8ebab00b4c/src/Protocol/Protocol_1_8.cpp#L507-L516

**Comment by tigerw** [comment]
Related #3258.

**Comment by adamj454545** [comment]
will this issue be fixed - it is very gamebreaking for all servers that want to support 1.8

**Comment by tonitch** [comment]
that's weird... I definitely seen this issue before, but now that I want to work on it, I can't reproduce it anymore...
do you know how I would do to force it ?

**Comment by adamj454545** [comment]
> 

this is using the windows prebuilt version btw - just go in the game from 1.8 and let mob AI follow you around for a bit, and they will just float higher and higher over time. noticed this even more with animals for some reason, though it’s present for mobs too

**Comment by tonitch** [comment]
> Int8 relative moves build up too much imprecision; we should probs have a counter that after X relatives send a teleport (absolute position) to resynchronise.
> 
> https://github.com/cuberite/cuberite/blob/280f7a81f4a6ec2c59768036b7e8ad8ebab00b4c/src/Protocol/Protocol_1_8.cpp#L507-L516

it might be really dumb to think this but i'm digging trough the packet system bit by bit so i'm not so familiar with it...
as we check if pos are not greater than the max of int8, shouldn't we also check that they aren't lesser than int8 ? ^^

in my mind max would be 011111111 and min would be 11111111. I don't really know how the cast handle the bit part exactly but maybe there is something to do with that ?

**Comment by tigerw** [comment]
Yes in theory min could be different from max, so more correct could be `if Delta >= Vector3d(min, min, min) && Delta <= Vector3d(max, max, max)` I think?

However I maintain the cause of this has something to do with the *32 on line 507. Worst case we lose 0.00001 precision each time a relative move happens on 1.8. On 1.9 where it's *32*128 there are apparently no issues.

**Comment by tonitch** [comment]
> However I maintain the cause of this has something to do with the *32 on line 507. Worst case we lose 0.00001 precision each time a relative move happens on 1.8. On 1.9 where it's _32_128 there are apparently no issues.

It's certainly that but I was wondering... why would this happen in cuberite and not in notchian's mc... I would assume that if such packet exist it meanst that notchian's don't use these kind of trick and they didn't have the problem (afaik). maybe they made the packet 16 bits the avoid a problem wich would be good. but I never seen this bug in vanilla. what is the difference then?

**Comment by tigerw** [comment]
I guess vanilla 1.8 sends a teleport once every so often? Either every X ticks, or X rel-move packets, or by looking at the error accumulated. If you want we can try getting cuberite/ProtoProxy working and find out what packets its sending.

I'm gonna try getting some empirical data on how fast the error accumulates.

**Comment by Janmm14** [comment]
vanilla server calculates the diff in full precision and sends a teleport every second

**Comment by tigerw** [comment]
Thanks to y'all's help I found an error with how we're calculating the diff. It should be `(byte)(⌊new×32⌋ - ⌊old×32⌋)` but was incorrectly changed to `(byte)((new - old)×32)`.

> Worst case we lose 0.00001 precision

This is actually wrong, got *32 and <<6 with /10000 in decimal confused >_<
More like the smallest move that will register is ~0.03, which is very imprecise. However after fixing the delta calculation it seems the errors tend to even out as mobs move around so its not noticeable.
