### ISSUE TITLE
Allow setting max build height to more than 256

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#5034]
One of the things that always felt limiting to me was the max build height of 256 blocks. In the past I played with mods which increased this, but sadly it always stayed to mods.

Afaik the client can actually support much higher build limits nowadays, but the limit is still set to 256. I was wondering if it would be possible to allow a server admin to increase this per world on Cuberite. The world generation doesn't have to be changed to make use of this extended height, but at least allowing to build above 256 would be nice.

**Comment by NiLSPACE** [comment]
Do you have a source that says Minecraft supports blocks higher than 256?

**Comment by 12xx12** [comment]
i'm not quite shure if the client actually can handle the blocks above the hight limit in older versions - this needs to be checks first.

I think the placement checks and the generation all refer the the same variable `cChunkdef::Height` so this won't make a difference

**Comment by PureTryOut** [comment]
I don't have source no, I just recall updates making it easier to extend the world height with external tools or mods. I'm looking for it now, maybe I can find something.

I was hoping anyway that a server implementation allowing higher limits would "just work" with vanilla Minecraft.

**Comment by NiLSPACE** [comment]
I just tried sending a block change to Y=256 or higher using cClientHandle:SendBlockChange and it did nothing, so Minecraft doesn't support it by default.

**Comment by PureTryOut** [comment]
Darn too bad, I guess I was mistaken. I was really hoping it was just an artificial limit nowadays. Never mind then I guess.

**Comment by 12xx12** [comment]
Maybe this will work with newer versions of minecraft?

**Comment by PureTryOut** [comment]
Maybe? Cuberite atm supports only up to 1.12 clients right? I guess it's worth revisiting once it allows newer clients.

**Comment by NiLSPACE** [comment]
There was a mod called Cubic chunks which made the build limit unlimited, but it had to completely overhaul the chunk system. I'm not surprised Anvil doesn't support chunks higher than 256 as it could mean one chunk could get really big.

**Comment by PureTryOut** [comment]
Yeah I know CubicChunks, it's one of the mods I used in the past. As the name says, it makes chunks cubic and allowed stacking them so it could load them in vertically rather than just horizontally. I guess that even if Cuberite supported this Minecraft of course wouldn't know how to handle vertically loaded chunks...

Too bad.

**Comment by tigerw** [comment]
Tentatively closing
