### ISSUE TITLE
Desert temples spawn with invisible and unusable chests

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#5035]
Client version: 1.12.2

Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
Chests to appear and be usable

### Actual behavior
![Screenshot_20201116_134733](https://user-images.githubusercontent.com/1565836/99254287-6d1be880-2812-11eb-9aa0-030c4f9ca471.png)

They can't be opened either so I can't verify if the type of loot is correct.

### Steps to reproduce the behavior
Start a new world with seed 1492584284 and go to the desert temple located at X -48 and Z 71.

**Comment by 12xx12** [comment]
hm... this is strange.

There is no loot at this point in the chests.
The generator doesn't create a block entity at the chest position

**Comment by 12xx12** [comment]
at some point the servers looses the block entity for the chest - investigating

**Comment by 12xx12** [comment]
got it - this is a bit weird - block entities are stored in `cChunkDesc` and in the `cChunkDesc::m_Blockentities`. The prefab generator places the items in the `cBlockArea` any other in the `cChunkDesc::m_Blockentities`. trying to unify this behaviour

**Comment by 12xx12** [comment]
whoops - it is worse... the rotation methods of block area misplace the block entities
