### ISSUE TITLE
Villagers don't harvest crops

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#5037]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
Villagers to harvest fully grown crops

### Actual behavior
They don't harvest the crops

### Steps to reproduce the behavior
1. Make a wheat farm and make them fully grown using some bonemeal
2. Spawn some villagers next to them

**Comment by 12xx12** [comment]
Actually there is code for that but it doesn't seem to run
