### ISSUE TITLE
Magma blocks don't hurt the player or mobs

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#5041]
Client version: 1.12.
Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
Walking on magma blocks should hurt a player in creative or adventure mode and mobs

### Actual behavior
Walking on magma blocks don't hurt mobs or the player

### Steps to reproduce the behavior
1. Find or place a magma block
2. Walk over it
3. Also let a mob walk over it, e.g. by leading an animal with a sheep over it or spawning one on top of it

**Comment by tigerw** [comment]
Tagging easy because we already have similar functionality for cacti, just adding another case should work.

**Comment by PureTryOut** [comment]
Awesome work @partypyro, thanks for your contribution to this issue! I hope we can see more from you in the future :smile:
