### ISSUE TITLE
Mobs don't enter minecarts or boats

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#5045]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
When pushing a mob into an empty boat or minecart, it should enter it

### Actual behavior
Mobs just push the boat or minecart out of the way

### Steps to reproduce the behavior
Place an empty boat or minecart next to a mob and try to push it into it

**Comment by jclever77** [comment]
Hey! I'm doing a school project that requires me to contribute to an open-source project, and after finding this I thought it was super interesting! I would like to be assigned to this issue so I can work on it.

**Comment by PureTryOut** [comment]
I guess, consider yourself assigned! The chance somebody else is working on this at the same time as you is quite small, so just go ahead :wink:

**Comment by bearbin** [comment]
@jclever77 I've assigned you, but you don't need to be assigned to work on any particular issue - we tend to use assignments only when there's a chance of a problematic conflict. As a new contributor you should take a look at the [getting started](https://github.com/cuberite/cuberite/blob/master/GETTING-STARTED.md) and [contributing](https://github.com/cuberite/cuberite/blob/master/CONTRIBUTING.md) files for some guidance and help with the project. If you have any other questions I recommend joining the Discord group or the forum as there are several contributors there that could offer help.

**Comment by jclever77** [comment]
@bearbin Awesome, thank you! I'll be sure to check those out as I'm working.
