### ISSUE TITLE
Beds should be dyeable

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#5048]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
Beds to be dyeable

### Actual behavior
Beds can't by colored by using dye

### Steps to reproduce the behavior
Try to combine a bed and dye with each other in a crafting grid

**Comment by Rorkh** [comment]
Was fixed with #5077 Can someone close it?
