### ISSUE TITLE
Gamemode is not set on join

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5051]
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688 

### Expected behavior
If asking for player gamemode woth API you should get the gamemode

### Actual behavior
you get -1 for the `Player:GetGameMode()`

### Steps to reproduce the behavior
Join game
ask for gamemode with API

**Comment by iulian3144** [comment]
Looking at the implementation this seems to be the expected behaviour...
You might want to use `GetEffectiveGameMode` instead. Or better, based on the documentation, `IsGameModeXXX()`.

**Comment by tigerw** [comment]
@12xx12 ?

**Comment by 12xx12** [comment]
Yeah - this was me not being able to read the docunentation. I still think this is unintuitive

**Comment by tigerw** [comment]
Docs are confusing, it claims GetEffectiveGameMode "is the same as" GetGameMode but clearly not.
