### ISSUE TITLE
Cant login to webadmin

### ISSUE THREAD

**Issue by Rekutor** [cuberite/cuberite#5070]
Client version: x.x.x
Server OS: raspbian
Cuberite Commit id: (Found at the top of the server's console output)

### Expected behavior
logging in webadmin would work

### Actual behavior
nothing happens
[User:SW]
Password=2xmag

[WebAdmin]
Ports=8080
Enabled=1

copied from webadmin.ini

### Steps to reproduce the behavior
try to login in webadmin

**Comment by cflep** [comment]
Did you remember to remove the ; at the beginning?

**Comment by Rekutor** [comment]
yes

**Comment by Rekutor** [comment]
> Did you remember to remove the ; at the beginning?
![2020-12-03-153922_1920x1080_scrot](https://user-images.githubusercontent.com/75429843/101042726-cce9f180-357d-11eb-8818-de0121aa6f0b.png)

**Comment by 12xx12** [comment]
Did you restart the server?
Can you move the login credentials below [Webadmin] just for testing? In my working configuration it's the other way around.

**Comment by Rekutor** [comment]
> Did you restart the server?
> Can you move the login credentials below [Webadmin] just for testing? In my working configuration it's the other way around.

uhhh well how do i restart? 
And yes i can move them below

**Comment by 12xx12** [comment]
Restart: stop the server with "stop" like the vanilla and the rerun the executeable

**Comment by Rekutor** [comment]
uhm in the terminal it says "stop" command doesnt exist and i dont have a exe

**Comment by cflep** [comment]
As a player ingame, type /stop, or if you still have the terminal open do Ctrl+C. Then rerun with ./Cuberite

**Comment by Rekutor** [comment]
i didnt even start it because it fails when i try to start it.
![2020-12-03-155325_1920x1080_scrot](https://user-images.githubusercontent.com/75429843/101044545-be9cd500-357f-11eb-803f-363f68f20751.png)

**Comment by cflep** [comment]
My installation doesn't do that, but that seems to be a seperate issue, since webadmin listens to port 8080. If you started the server end went into the configuration in webadmin, you could change the port of the game itself. (You'd probably have to do xxx.xxx.xxx.xxx:PORT)

**Comment by cflep** [comment]
Try letting the server start and then enter Webadmin to change the port of the game. I guess something else is already using 25565. 
That should be a seperate issue in that case.

**Comment by Rekutor** [comment]
i dont rly understand what am i supposed to do if the server wont start correctly?

**Comment by cflep** [comment]
Oh, sorry, I thought you stopped it while starting
I'm fairly new here, somebody else will have to help you then.......

**Comment by Rekutor** [comment]
well still thx for trying to help

**Comment by NiLSPACE** [comment]
It looks like there is either another program using the same port or your firewall is blocking Cuberite from using the port. My guess is the firewall as both 25565 and 8080 give an error, but since I'm not that experienced with Linux I'm not really sure what to do there. You'll have to find a way to add Cuberite to your firewall as an accepted application.

**Comment by 12xx12** [comment]
is there another Minecraft server running?

**Comment by NiLSPACE** [comment]
If that were the case you should still be able to connect to the instance which managed to bind to the ports.

**Comment by 12xx12** [comment]
Hm... that's right... I thought about paper, spigot... but that's a PI so no way that's that

**Comment by 12xx12** [comment]
Hm... but the tab of chromium sais that they can't login to the webadmin interface in the title 🤔

What's going on in the other shell tab?

**Comment by 12xx12** [comment]
@Rekutor

**Comment by Rekutor** [comment]
Okay i dont know why...but for some reason it works now, i did nothing at all but it works now idk what the problem was but since the problem is gone i would close this.
Anyway thank you, but i really dont know why it works now it just worked. Im really sorry for wasting your time though!
