### ISSUE TITLE
Mobs flying over the ground

### ISSUE THREAD

**Issue by Rekutor** [cuberite/cuberite#5071]
Client version: x.x.x
Server OS: Raspbian
Cuberite Commit id: (Found at the top of the server's console output)

### Expected behavior
Mobs are standing on the ground

### Actual behavior
Mobs flying over the ground

I followed a 2014 guide for installing minecraft server on Raspberry PI and the Mobs fly as i said over the ground
### Steps to reproduce the behavior
start the server

**Comment by tigerw** [comment]
Which client version? We have #5030 for 1.8.9.

**Comment by Rekutor** [comment]
Well yes it was 1.8.9 and i used 1.12.2 now and it works fine now but why can i only use 1.8.9-1.12 tho

**Comment by 12xx12** [comment]
You can connect with 1.13 but it's a mess. We're struggling with 1.13 because Mojang changed everything in this version

**Comment by PureTryOut** [comment]
So seeing the bug reported here was for 1.8.9 and thus already reported as #5030, this can be closed right?

**Comment by Rekutor** [comment]
Yea sry i close it but thank you
