### ISSUE TITLE
got an error when Compiling Cuberite  in windows with vs2019

### ISSUE THREAD

**Issue by ywjb** [cuberite/cuberite#5072]
I using Git to get the source,use the following command:
    git clone --recursive https://github.com/cuberite/cuberite.git
    cmake .
When I tried to compile, I got an error:
cuberite\src\Resources\Cuberite.rc(11): error RC2104: undefined keyword or key name: Cuberite

**Comment by 12xx12** [comment]
- create a folder in the cuberite directory called build
- cd into it
- do `cmake ..`

**Comment by ywjb** [comment]
> Try this:
> 
> * create a folder in the cuberite directory called build
> * `cd` into it
> * do `cmake ..`
> 
> worked for me
---------
I've done what you said, but the error is still there:
cuberite\src\Resources\Cuberite.rc(11): error RC2104: undefined keyword or key name: Cuberite

**Comment by tigerw** [comment]
Weird, `"Cuberite"` should be a string in that file, not a keyword.

If you delete the `Resources/Cuberite.rc` line in `src/CMakeLists.txt` does that fix the issue?

**Comment by 12xx12** [comment]
I tried again. I did

`git clone --recursive https://github.com/cuberite/cuberite.git`
`mkdir build`
`cd build`
`cmake ..`

and the generation proceeded

**Comment by 12xx12** [comment]
@ywjb any Updates?

**Comment by 12xx12** [comment]
@ywjb still there?

**Comment by 12xx12** [comment]
Closed for inactivity

**Comment by rld2014** [comment]
Same problem for me, making a directory build and run `cmake ..` didnt work
Trying to figure out the exact issues...... Any updates?

**Comment by rld2014** [comment]
> Weird, "Cuberite" should be a string in that file, not a keyword.
> 
> If you delete the Resources/Cuberite.rc line in src/CMakeLists.txt does that fix the issue?
That seems to be working, but I still cannot figure out why......
