### ISSUE TITLE
Rain sounds make no sense

### ISSUE THREAD

**Issue by UnNotchslayer1** [cuberite/cuberite#5073]
The closer you are to the ground, the loader rain sounds. If you fly away from the ground, it becomes quiet and you can't hear it anymore

**Comment by tigerw** [comment]
This seems to be Vanilla behaviour (1.12.2), though I agree it is strange.

**Comment by NiLSPACE** [comment]
Cuberite doesn't make the client play rain sounds. It just tells the client that it's raining.

**Comment by ikbenignace** [comment]
Close this pls. This issue doesn't make sense

**Comment by tigerw** [comment]
Tentatively closing as Vanilla client issue.
