### ISSUE TITLE
2 hoppers attached to double chest treat it as individual chests

### ISSUE THREAD

**Issue by Cliveptr** [cuberite/cuberite#5088]
Client version: 1.12.2
Server OS: Arch Linux
Cuberite Commit id: 53ae358d8c5db448e7f4b6deac66b3d9e42e59ee

### Expected behavior
Hoppers should treat double chests as double chests, not individual chests (shift clicking items works fine, I guess the client handles that?)

### Actual behavior
Hoppers treat double chests as 2 individual chests, as if the double chest were divided horizontally along the middle when open.

### Steps to reproduce the behavior
Build the following:
![2020-12-25_15 41 39](https://user-images.githubusercontent.com/72765037/103142842-eb698580-4702-11eb-9635-fed78afe6fc6.png)

- Place (eg.) stone anywhere in the top half of the top chest and wood in the bottom half.
- The stone will be in column 1 line 1 of the output chest and the wood will be in column 1 line 4 of the output chest.

### Server log
```
N/A
```

**Comment by graemeg** [comment]
I can confirm. I have seen the same behaviour.

**Comment by npresley0506** [comment]
I can try working on this, I have to work on an open-source project for my class and this one seems pretty interesting.

**Comment by npresley0506** [comment]
This issue can also be reproduced by putting a double chest on one hopper that feeds into a single chest. The top half of the large chest will be fed into the single chest while the bottom half will remain untouched until moved to the top.
