### ISSUE TITLE
Cuberite Fails to Compile with LTO on Pi 0/1

### ISSUE THREAD

**Issue by KingCol13** [cuberite/cuberite#5110]
Client version: N/A
Server OS: Linux Pi0, 1, (ARM1176JZF-S)
Cuberite Commit id: bdb45998c966905a8a69a59912e6c8855cca48e0

Cuberite fails to compile with link time optimisation (WHOLE_PROGRAM_OPTIMISATION) on the ARM1176JZF-S chip. Compiles and runs fine without LTO.

I believe this is due to libdeflate attempting to compile with CRC32 and NEON instructions that are not available on this chip. Changing `__arm__` to `__ARM_NEON__` in https://github.com/ebiggers/libdeflate/blob/e1803dc145aaecd531fb081de2b9e354fe27fda7/lib/adler32.c#L62

and `__arm__` to `__ARM_FEATURE_CRC32` in https://github.com/ebiggers/libdeflate/blob/e1803dc145aaecd531fb081de2b9e354fe27fda7/lib/crc32.c#L183 fixes this issue.

**Comment by tigerw** [comment]
It only tries to use those instructions when LTO is enabled?

**Comment by KingCol13** [comment]
Yes, I'm unsure exactly how libdeflate does this, my guess is that it compiles both generic functions and functions using the special instructions regardless of `-mfpu=x -mcpu=y` switches and then determines which function it should actually use at runtime. Then it would make sense that it compiles and runs fine without LTO. This comment might give some insight: https://github.com/ebiggers/libdeflate/blob/e1803dc145aaecd531fb081de2b9e354fe27fda7/lib/arm/cpu_features.c#L28

I just tested it again:
Compiling with LTO: fails to compile
Compiling without LTO: compiles and runs fine
Compiling with suggested fixes: compiles and runs fine

**Comment by KingCol13** [comment]
Here's the full compile error message (this is from a cross-compiler but I've verified the problem natively):

`/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h: In function 'crc32_arm':
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32b (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:199:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32w (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
   return __builtin_arm_crc32b (__a, __b);
          ^
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_acle.h:187:10: error: this builtin is not supported for this target
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_neon.h: In function 'crc32_pmull':
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_neon.h:7355:21: fatal error: You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use these intrinsics.
   return (uint8x8_t)__builtin_neon_vget_lowv16qi ((int8x16_t) __a);
                     ^
compilation terminated.
lto-wrapper: fatal error: /home/me/x-tools/armv6-rpi-linux-gnueabihf/bin/armv6-rpi-linux-gnueabihf-g++ returned 1 exit status
compilation terminated.
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/../../../../armv6-rpi-linux-gnueabihf/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Cuberite.dir/build.make:866: Server/Cuberite] Error 1
make[1]: *** [CMakeFiles/Makefile2:842: CMakeFiles/Cuberite.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by tigerw** [comment]
Could you try deleting https://github.com/ebiggers/libdeflate/blob/e1803dc145aaecd531fb081de2b9e354fe27fda7/lib/arm/crc32_impl.h#L67-L69

**Comment by KingCol13** [comment]
Ok that got rid of the CRC32 errors, just left with the NEON error now:

```/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_neon.h: In function 'crc32_pmull':
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/include/arm_neon.h:7355:21: fatal error: You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use these intrinsics.
   return (uint8x8_t)__builtin_neon_vget_lowv16qi ((int8x16_t) __a);
                     ^
compilation terminated.
lto-wrapper: fatal error: /home/me/x-tools/armv6-rpi-linux-gnueabihf/bin/armv6-rpi-linux-gnueabihf-g++ returned 1 exit status
compilation terminated.
/home/me/x-tools/armv6-rpi-linux-gnueabihf/lib/gcc/armv6-rpi-linux-gnueabihf/8.4.0/../../../../armv6-rpi-linux-gnueabihf/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Cuberite.dir/build.make:866: Server/Cuberite] Error 1
make[1]: *** [CMakeFiles/Makefile2:842: CMakeFiles/Cuberite.dir/all] Error 2
make: *** [Makefile:130: all] Error 2```

**Comment by tigerw** [comment]
I wonder if it's just some LTO compiler bug then (maybe when combined with `-march=native`?), the libdeflate function using those NEON instructions is tagged with `target` attribute that _should_ prevent it getting compiled when NEON is unsupported. I dunno

**Comment by tigerw** [comment]
The armhf builds have fallen over too: https://builds.cuberite.org/job/linux-armhf/156/

**Comment by tigerw** [comment]
When you have time, could you test again? There was an attempted fix recently.

**Comment by KingCol13** [comment]
It compiles natively now. Thanks for fixing this, I really couldn't tell what was going on. I'm still having trouble when cross compiling but that's not such a big deal and the build server's working so I'll figure it out eventually.

**Comment by coffeelack** [comment]
> Yes, I'm unsure exactly how libdeflate does this, my guess is that it compiles both generic functions and functions using the special instructions regardless of `-mfpu=x -mcpu=y` switches and then determines which function it should actually use at runtime. Then it would make sense that it compiles and runs fine without LTO. This comment might give some insight: https://github.com/ebiggers/libdeflate/blob/e1803dc145aaecd531fb081de2b9e354fe27fda7/lib/arm/cpu_features.c#L28
> 
> I just tested it again: Compiling with LTO: fails to compile Compiling without LTO: compiles and runs fine Compiling with suggested fixes: compiles and runs fine

Hi KingCol13,
I'm a bit too much of a rookie to understand how to change to compiling without LTO.
Could you help me with a bit of a step-by-step?
Thanks in advice!

**Comment by KingCol13** [comment]
> Hi KingCol13, I'm a bit too much of a rookie to understand how to change to compiling without LTO. Could you help me with a bit of a step-by-step? Thanks in advice!

Hi, sure no problem. It's a slight modification to the instructions under COMPILING.md, build:

```
mkdir Release
cd Release
cmake -DCMAKE_BUILD_TYPE=RELEASE -DWHOLE_PROGRAM_OPTIMISATION=0 ..
make -j`nproc`
```

If you're seeing these errors can I ask which version of gcc or clang you're using? (`gcc -v`/`clang -v`)

I wish you all the best with the 6 hour compile :)

**Comment by coffeelack** [comment]
Hi, I will try this this week.
The gcc version is 10.2.1 and clang is 11.0.1-2+rpi1.
Do they have incompatibilities?

**Comment by tigerw** [comment]
(If you didn't know we have [pre-built binaries](https://download.cuberite.org/linux-armhf-raspbian/Cuberite.tar.gz) available for the Pi)

The compiler versions should be ok. Does LTO still not work?
