### ISSUE TITLE
End crystal explosion pushes creative mode player away

### ISSUE THREAD

**Issue by PureTryOut** [cuberite/cuberite#5118]
Client version: 1.12.2
Server OS: Alpine Linux
Cuberite Commit id: b1b7424c43d6c89cbd772f76b7d405de4dd3b462

### Expected behavior
End crystal explosions to not influence a player if they are in creative mode like in vanilla Minecraft

### Actual behavior
Explosions don't harm the player, but they do push them away. Especially when flying the player gets pushed quite a lot

### Steps to reproduce the behavior
1. Place an end crystal on an obsidian or bedrock block
2. Let it explode by left-clicking on it

**Comment by tigerw** [comment]
Sorry, a regression in #4845. Originally implemented by @changyongGuo in #4251. We need to remove `cEntity/cPlayer::GetExplosionExposureRate` and add the creative mode special case to `cPlayer::GetEnchantmentBlastKnockbackReduction` to return `1`.

**Comment by tigerw** [comment]
And change SetSpeed to AddSpeed in the explosion code I expect
