### ISSUE TITLE
cuberite defect

### ISSUE THREAD

**Issue by Pantyhose-X** [cuberite/cuberite#5126]
Client version: 1.3.3.7
Server OS: Windows/Linux/Androird/BSD
Cuberite Commit id: 2285

### Expected behavior

1. import maps
2. bulk authorization enters server players all permissions

**Comment by 12xx12** [comment]
Hi there, thank you for your issue.

To help you further we need some other information:

What version of notchian Minecraft are you using to save the map? Did you follow the guide in how to set up the world.ini?
What do you mean by "bulk authorization enters server players all permissions"?

**Comment by tigerw** [comment]
Or write in Chinese if you feel it is appropriate

**Comment by Pantyhose-X** [comment]
> 或者如果您认为合适的话用中文写

功能缺陷
1、Minecraft java 地图，导入地图
2、批量授权进入服务器的 “玩家”  自动给予， 所有权限。
3、如果可以我希望你们有[Minetest](https://minetest.net) Cuberite 服务器

**Comment by 12xx12** [comment]
1. Minecraft 您使用哪个版本? 我们支持1.12. 用那个 
Minecraft Which version are you using? We support 1.12 use this

2. 每个球员?  我们可以有该网站的屏幕截图 `? 显示带有球员排名的页面  "Player Ranks"
Every Player? Can we have a screenshot of the webinterface? Showing the page with Player Ranks?

3. 网络浏览器警告我有关此网站的信息
The web browser warns me about this website 

由谷歌翻译
By Google Translate

**Comment by Pantyhose-X** [comment]
@12xx12  
Functional defect
1. No map import
2. No batch authorization, "players" who enter the server will be automatically granted all permissions.
3. No www.Minetest.net server

**Comment by tigerw** [comment]
1. We don't yet support reading the spawn/player location from the Vanilla level.dat (#2702). To load that map:

Download and extract into your Cuberite/ folder.
In settings.ini, under [Worlds] add `World=Novigrad` and under [WorldPaths] add `Novigrad=Novigrad`.
Start the server, join, type `/worlds`. You should see Novigrad listed. Type `/portal Novigrad`.
Now, you need to manually teleport to where the build is. `/tp 883 62 1310`.

3. Minetest support is very long term, we don't have enough developers...

-----

1. 暂时不支持阅读Vanilla的玩家重生位置。#2702 但是可以导入：

把地图下载并提取到你的Cuberite/文件夹。
在settings.ini的[Worlds]下面添加`World=Novigrad`、[WorldPaths] 下加 `Novigrad=Novigrad`.
启动服务器，加入游戏，写`/worlds`.应该看得到Novigrad. 输入 `/portal Novigrad`.
现在得手工走到建筑的位置：`/tp 883 62 1310`.

3. Minetest支持是非常长期的目标，开发者数量不够。。。

**Comment by Pantyhose-X** [comment]
@tigerw 
1、怎么设置批量授权，进入服务器的“玩家”将被自动授予所有权限。
2、希望可以导出地图格式是Minetest的

参考
https://forum.minetest.net/viewtopic.php?f=12&t=13709&sid=64ab4a65e2791ce2b615a536130c7014

https://forum.minetest.net/viewtopic.php?f=14&t=14271&sid=3cd2c3fc6dedd9d79bdc4bf396b1b7d9

**Comment by 12xx12** [comment]
1. Go into the webinterface and change the permissions of the Defaul group to "*"
进入Web界面，并将“默认”组的权限更改为“ *” 
![screenshot_20210217_110815_LI](https://user-images.githubusercontent.com/44411062/108189081-a2d1b580-7110-11eb-80b4-c48077d33af8.jpg)

![screenshot_20210217_111004_LI](https://user-images.githubusercontent.com/44411062/108189208-c5fc6500-7110-11eb-8500-7918a046320b.jpg)

![screenshot_20210217_111104](https://user-images.githubusercontent.com/44411062/108189318-e2000680-7110-11eb-9329-2a293decffd9.png)


2. we save the same way as minecraft 1.12 does
我们以与Minecraft 1.12相同的方式保存

**Comment by tigerw** [comment]
Closing, Minetest support is unlikely and default ranks with restricted permissions are available as shown.
