### ISSUE TITLE
Position offset

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5128]
Client version: 1.12.2
Server OS: Windows/Linux/macOS/BSD/...

![Inked2021-02-13_13 45 39_LI](https://user-images.githubusercontent.com/44411062/107850371-179bab80-6e02-11eb-9347-690d87331891.jpg)

### Expected behavior
Matching coordinates

### Actual behavior
Offset by 1

**Edit: The coordniate displayed by "looking at" is the coorect one**
**Edit2: the integer coordinate below the float coordinate says the same as the looking at**

**Comment by NiLSPACE** [comment]
This is from a single player world:
![2021-02-13_14 11 10](https://user-images.githubusercontent.com/1160867/107850792-68f96a00-6e05-11eb-8c83-354598491cbe.png)

I don't think Cuberite is able to modify the 'looking at' coordinates. They are probably just calculated client-side.

**Comment by 12xx12** [comment]
The one block offset is still kind of weird. You habe this too

**Comment by NiLSPACE** [comment]
Also, I believe the coordinates are correct. Try teleporting to 0, 0 and see for yourself by moving to -1, 0. It's just counter intuitive because you're dealing with negative numbers.

**Comment by Pokechu22** [comment]
See [MC-36602](https://bugs.mojang.com/browse/MC-36602 "[MC-36602] Commands with coordinates are NOW offset -1 x and/or z from where it should be (at negative X and Z coordinates)").  This is normal behavior; the confusion comes from the floating-point version's intervals `[-2, -1]`, `[-1, -0]`, `[0, 1]`, `[1, 2]` to the integer points -2, -1, 0, 1 - perfectly normal math, but somewhat confusing at first glance.  Note that the block coordinates (right below XYZ) are also integers, and behave the exact same way.

**Comment by 12xx12** [comment]
Oh - i see...
