### ISSUE TITLE
Slimes don't have designated chunks

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5130]
Client version: x.x.x
Server OS: Windows/Linux/macOS/BSD/...

**Comment by hle0** [comment]
This shouldn't be too hard. Slime chunks just depend on the seed and chunk XZ. It's documented [here](https://minecraft.fandom.com/wiki/Slime#.22Slime_chunks.22) in Java (I paraphrased it a bit):
```java
public boolean isSlimeChunk(long seed, long x, long z)
{
	Random rnd = new Random(
		seed +
		(int) (x * x * 0x4c1906) +
		(int) (x * 0x5ac0db) +
		(int) (z * z) * 0x4307a7L +
		(int) (z * 0x5f24f) ^ 0x3ad8025fL
	);
	
	return rnd.nextInt(10) == 0;
}
```
Java's `Random` is also rather easy to implement.

**Comment by tigerw** [comment]
Has the implementation of Random ever changed in Java's history?

**Comment by tigerw** [comment]
Thanks.

https://github.com/cuberite/cuberite/blob/a2b19de07836f7273c66e3cba9922e110bf559e7/src/MobSpawner.cpp#L209

Sounds like for this one we can just add an `IsSlimeChunk` condition somewhere around here.
