### ISSUE TITLE
Command blocks wont open/work

### ISSUE THREAD

**Issue by FreddyFeuerstein** [cuberite/cuberite#5131]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: b1b7424c43d6c89cbd772f76b7d405de4dd3b462

### Expected behavior
GUI should pop-up in Minecraft allowing you to enter a command.

### Actual behavior
Nothing happens

### Steps to reproduce the behavior
Run /gm 1
Get a command block using /give
Place the command block
Right click the command block.

### Server log
```
[10:04:54] Player mueller_minki is executing command "/give mueller_minki command_block" in world "world" at world age 216430.
[10:04:54] mueller_minki: Given [ commandblock ] x 1 to mueller_minki
[10:06:08] [AutoSave] Save successfully completed.
```

**Comment by 12xx12** [comment]
Hi and welcome to the project.

We are areware of this issue but didn't document it anywhere. I'm gonna keep this open to add it to the old feature roadmap

**Comment by FreddyFeuerstein** [comment]
Thank you

**Comment by 12xx12** [comment]
If you REALLY want to do this I think in 1.8 the command blocks seem to work (kind of... maybe...)

**Comment by tigerw** [comment]
Yeah, 1.8 works; don't forget to enable them in world.ini, under `CommandBlocksEnabled`.

**Comment by tigerw** [comment]
Closing in favor of #3239
