### ISSUE TITLE
Low TPS on Windows because chrono sleeps too long

### ISSUE THREAD

**Issue by AsteriaGamer** [cuberite/cuberite#5140]
Client version: 1.12.2
Server OS: Windows 10 Pro 19042.844 x64

Good day.

After installing a clean server for Windows x64, I found that the TPS does not rise above 16. I tried to build the server from the source code (release version), but I got exactly the same result. Reducing the view distance or disabling monsters and animals did not change the situation.

![Screen](https://i2.paste.pics/2a0449ab9fdee80f1f9323becdde25bf.png)

The server ran on two computers:
```
Ryzen 5 2600 6C12T 3.8GHz
32GB RAM
NVME SSD

Intel core i5 6500 4C
8GB RAM
SSD
```
Unfortunately, there is no time to check the work on Linux yet.

The following message appears in the server logs when a player spawns, but I'm not sure if it can somehow relate to the problem.
```
[23:05:20] cChunkMap::AddEntity: Entity at 0x2a970282010 (cPlayer, ID 55) spawning in a non-existent chunk.
```

**Comment by tigerw** [comment]
Seen this also, it seems like whatever sleep API on Windows the underlies std::chrono::sleep_for sleeps too long. It should be better on Windows.

We might want to look into the dedicated timer APIs. https://docs.microsoft.com/en-us/windows/win32/sync/waitable-timer-objects

**Comment by tigerw** [comment]
I did some reading and it's possible there isn't a good way to fix this, without either increasing the global system timer frequency, or using an undocumented `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION` flag; I don't have experience with either, and they each seem to have their own tradeoffs. The normal waitable timers also suffer the problem of not hitting exactly 20TPS.
