### ISSUE TITLE
GetTicksAlive() Is missnamed?

### ISSUE THREAD

**Issue by koutsie** [cuberite/cuberite#5152]
Client version: Any.
Server OS: Linux
Cuberite Commit id: 01a4e696b3d2c973cdd1fb4345d747bd10e93ad9

To simplify a lot:
GetTicksAlive() as of now is very confusingly named and i veto it should be changed to GetTicksExisted() instead.

**Comment by 12xx12** [comment]
Why was this closed?

**Comment by Titaniumtown** [comment]
The world may never know.

**Comment by koutsie** [comment]
> Why was this closed?

Because I need to rethink my life decisions and re-format this issue.

**Comment by tigerw** [comment]
Maybe we can re-set it back to zero on player death?

**Comment by 12xx12** [comment]
I think the reset is da wea

**Comment by koutsie** [comment]
yeah
