### ISSUE TITLE
Cuberite fails to compile with "lto-wrapper failed"

### ISSUE THREAD

**Issue by MiBra66** [cuberite/cuberite#5154]
Client version: N/A
Server OS: Linux Rasp-Pi 3B+ / 4
Cuberite Commit id: (Found at the top of the server's console output)

did ran:
`sh -c "$(curl -sSfL -o - https://compile.cuberite.org)"`

it fails with:
```
...
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Cuberite.dir/build.make:883: Server/Cuberite] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:866: CMakeFiles/Cuberite.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2

-----------------
Compilation failed. Failed command:
make -j 4
```

How can I get it running through (worked several years ago without an issue on Pi 3B+ , but fails today also with this hardware).

Thanks Mike

**Comment by tigerw** [comment]
Try updating your system (`sudo apt update && sudo apt dist-upgrade`). What's your gcc version? `gcc --version`

**Comment by MiBra66** [comment]
I usually ran "sudo apt-get update && sudo apt-get upgrade" once a week.
Did ran now, as You suggested - but I get the same errors.

lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Cuberite.dir/build.make:883: Server/Cuberite] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:866: CMakeFiles/Cuberite.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2

.................
pi@raspberrypi:~ $ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

c++ (Raspbian 8.3.0-6+rpi1) 8.3.0
GNU Make 4.2.1
cmake version 3.16.3

**Comment by tigerw** [comment]
In that case maybe turning off LTO is easiest:

```
cd ~/cuberite
rm -rf build-cuberite
mkdir build-cuberite
cd build-cuberite
cmake .. -DCMAKE_BUILD_TYPE=Release -DWHOLE_PROGRAM_OPTIMISATION=Off
cmake --build . --parallel 4
```

**Comment by MiBra66** [comment]
this worked and fixed my problem!!
Thanks!

**Comment by tigerw** [comment]
No problem. LTO builds improve performance, but unfortunately it seems very sensitive to system configuration...
