### ISSUE TITLE
World age isn't being sent to the client(?)

### ISSUE THREAD

**Issue by koutsie** [cuberite/cuberite#5159]
Client version: Any.
Server OS: Linux (Armbian)
Cuberite Commit id: 01a4e696b3d2c973cdd1fb4345d747bd10e93ad9

### Expected behavior
The client gets the worlds age.

### Actual behavior
It doesn't

![image](https://user-images.githubusercontent.com/18449778/111705428-5b426480-8849-11eb-9bea-9a34adf516ab.png)

### Steps to reproduce the behavior
Join a cuberite server. 
Press F3.
Look at Day counter.

**Comment by tigerw** [comment]
![So it would seem](https://user-images.githubusercontent.com/2939130/111762810-55746f80-8899-11eb-9c73-63e50b5a4a38.png)

**Comment by tigerw** [comment]
ah, we're sending the time of day modulo day length, but the client expects a value that isn't wrapped. That's why the day always remains at zero. Looks like the protocol docs are inaccurate.

**Comment by koutsie** [comment]
**Awesome!**

**Comment by tigerw** [comment]
Sounds like the fix worked?
