### ISSUE TITLE
Splash potion of harming has range issue

### ISSUE THREAD

**Issue by rehwinkel** [cuberite/cuberite#5164]
Client version: 1.9.4
Server OS: Arch Linux
Cuberite Commit id: 90369deb5a870674ab02a26a93a71f06eafe9293

### Expected behavior
If entities are far enough away, they should not receive any damage.

### Actual behavior
Entities take damage 10 or more blocks away from the potion impact. They seem to take 0 damage, however the damage effect is still shown and make damage sounds.

### Steps to reproduce the behavior
Throw potion of harming anywhere and look at entities nearby.

### Server log
```
[79ef0849918ae52f|12:05:58] HandleUseItem: Hand: 0; HeldItem: 373:16396:16396 * 1
[79ef0849918ae52f|12:05:58] Destroying entity #403 (cSplashPotionEntity) from chunk (-11, -6)
```

**Comment by 12xx12** [comment]
Fixed #5176
