### ISSUE TITLE
API access to Player Statistics/Achievements

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5166]
At this point it seems impossible to access the players statistics through the LUA API. At least it's not documented. This should be an  intermediate issue because all methods are already there in the C++ Code.

**Comment by tigerw** [comment]
Probably just stats, I guess we don't want to export achievements only to deprecate it later for advancements.

**Comment by 12xx12** [comment]
The old achievements are just stats that have a 0 or 1 value 🤤

**Comment by nshah25** [comment]
Hello! I have to contribute to an open-source project for my computer science class and thought I could take a shot at this issue. Do you have any tips on how or where I should start? I've been reading through the codebase to get a better understanding of how statistics are handled and was hoping for a little more guidance. Thank you!

**Comment by 12xx12** [comment]
Hi, thank you wanting to do your project with us.

At the core you have to reveal the statistics c++ stuff to the lua API and document it.

To mark anything for export you do //tolua_begin and //tolua_end in front of the first thing to export and after the last thing.

The you add the new stuff to Plugins/APIDump/APIDesc.lua and we're fine
