### ISSUE TITLE
API: cPlayer:PlaceBlock negative y pos crashes the server

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#5191]
Server OS: Linux
Cuberite Commit id: 5ae924ec74bab199284c451552040bcc6f39bb3a

### Actual behavior
Server crashes.

### Steps to reproduce the behavior
Pass a negative number for y pos:
`player:PlaceBlock(100, -100, 100, 1, 1)`

**Comment by Seadragon91** [comment]
This function calls, still crashes the server. Test them on windows.
```
	cRoot:Get():GetDefaultWorld():DigBlock(1, -100, 1, nil)
	cRoot:Get():GetDefaultWorld():IsBlockDirectlyWatered(1, -100, 1)
	cRoot:Get():GetDefaultWorld():SetTrapdoorOpen(1, -100, 1, false)
	cRoot:Get():GetDefaultWorld():QueueBlockForTick(1, -57, 1, 1)
	cRoot:Get():GetDefaultWorld():IsTrapdoorOpen(1, -100, 1)
```

**Comment by tigerw** [comment]
Noted, let's edit the title of #5220 to have it track the general case.
