### ISSUE TITLE
Can't teleport a player on move event

### ISSUE THREAD

**Issue by XfedeX** [cuberite/cuberite#5196]
### Expected behavior
Player should be teleported in both events, the move and the block place one.

### Actual behavior
Player only gets teleported on block place event, on move event it gets teleported to itself.

### Steps to reproduce the behavior
Run this code
```
function Initialize(Plugin)
    LOG("Initialising TESTPLUGIN")
	Plugin:SetName("TESTPLUGIN")
	Plugin:SetVersion(1)

	-- Hooks

	PLUGIN = Plugin

    cPluginManager.AddHook(cPluginManager.HOOK_PLAYER_MOVING, CheckMove);
    cPluginManager:AddHook(cPluginManager.HOOK_PLAYER_PLACED_BLOCK, OnBlockPlace);

    LOG("TESTPLUGIN initialised.")
     return true
end
function CheckMove(Player, OldPos, NewPos)
     Player:SendMessage("moved")
     Player:TeleportToCoords(0, 100, 0)
end
function BlockPlaced(Player)
     Player:SendMessage("BlockPlaced")
     Player:TeleportToCoords(0, 100, 0)
end
```

**Comment by HeCorr** [comment]
Hello! Can you try adding a `return true` to the end of `CheckMove`?

The `HOOK_PLAYER_MOVING` can be canceled, which would prevent the player from completing the move right after you teleport him, likely fixing your issue.
