### ISSUE TITLE
Typo in End generator settings

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5207]
https://github.com/cuberite/cuberite/blob/4a2d0ce9d32eac0df2acb116e6242490b2adf868/src/Generating/EndGen.cpp#L69

I'm not sure if we just fix it or do a strange we accept both thingy

**Comment by tigerw** [comment]
fix it quickly before anyone sees

**Comment by 12xx12** [comment]
The thing is that this will keep the one person that changed the value from using it

**Comment by tigerw** [comment]
If you know who it is tell them :)
I think this is too minor and too recent for backcompat
