### ISSUE TITLE
Add standadised way for plugins to log to console

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5209]
I think a standardised way for plugins to log to console including their name would be nice.

Something like:

`LOGPLUGIN("test")`

resulting in

`[MyPlugin] Test`

**Comment by uselessknickknacks** [comment]
Always hated how you had to do stupid CHAT.Color stuff in spigot several times over.
Add support for minecrafts own color codes to this and it would be absolutely golden, and add generalized stuff like
LOGINFOPLUGIN
LOGWARNPLUGIN
LOGERRORPLUGIN
And of course the one suggested by OP.
To cut down on the amount of text.
LOGP
LOGINFOP
LOGWARNP
LOGERRORP
Where P tells us that it's the plugin doing the logg.
The generalized ones default to a color (white/gray for normal log, light blue for info, yellow for warn, red for error). And could additionally be seperated by symbols.
For example:

Normal Log:
[MyPlugin] Moved bytes to the incineraqtor
Info: 
*MyPLugin* The requested action has been performed
WARN: 
!MyPLugin! Warning! The dinosaur is going to eat you!
ERROR:
!?!MyPlugin!?! THE DINOSAUR HAS GLITCHED OUT AND IS CONSUMING ALL THE KNOWN BITS OF THE UNIVERSE HA HA FUNNY CLAP

The reason for using different symbols for these additional generalized methods are for color blindness.

**Comment by 12xx12** [comment]
I would stick the the already used sceme for the info, warning, error messages.
