### ISSUE TITLE
TNT Fire

### ISSUE THREAD

**Issue by danilacasito** [cuberite/cuberite#5247]
Client version: 1.12.2
Server OS: Arch Linux (Latest Version)
Cuberite Commit id: 242

### Expected behavior
When you do right click in a tnt with a inigter, the fire would be put and tnt would be inigted a bit later

### Actual behavior
the tnt starts inmediatly when you shift click the tnt and when it explodes the fire are floating in the air

### Steps to reproduce the behavior

Place a tnt
get a inigter
hold shift key and right click tnt while you hold tnt

See results

### Server log
Nothing appears to be at log

**Comment by tigerw** [comment]
Probably server client desync, seems like shift click with flint n' steel isn't handled.
