### ISSUE TITLE
Slight creen shaking when standing on slime blocks

### ISSUE THREAD

**Issue by 99thGamer9** [cuberite/cuberite#5278]
Client version: 1.12.2
Server OS: Linuxc
Cuberite Commit id: 6a4460383e98fbdbdf568c0cb154dafec833ed44

### Expected behavior
Nothing

### Actual behavior
Slight shaking

### Steps to reproduce the behavior
Standing on a Slime block

**Comment by Ccode-lang** [comment]
Is this fixed?

**Comment by Janmm14** [comment]
This is client behaviour afaik.

**Comment by 99thGamer9** [comment]
> This is client behaviour afaik.

Yes, but i didn't knew that when i wrote the issue
