### ISSUE TITLE
Change plugins storage in settings.ini

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#528]
The current format for storing the enabled plugins in the ini file has some serious flaws and needs to change (See the IniFileFix branch). There have already been relevant discussions in the forum:
1. Keep a list of disabled plugins, rather than enabled ones. This way new plugins will work out-of-the-box:
   http://forum.mc-server.org/showthread.php?tid=865&pid=7440#pid7440
2. Use a unique key for each plugin, so that the INI file is standards-conformant:
   http://forum.mc-server.org/showthread.php?tid=764
3. Use the Info.lua file to automatically load plugins in the correct order, by having the plugin authors list the plugins that their plugin depends on, or should start before or after. Not yet talked about in the forum.

**Comment by SphinxC0re** [comment]
is this still something to worry about?

**Comment by madmaxoft** [comment]
We've neutralized most of the underlying problems with the addition of `cPluginManager:CallPlugin()`. This is now a purely cosmetic thing - how to represent the list of enabled plugins in the settings.

**Comment by mathiascode** [comment]
I suppose we can close this due to #4557, unless someone has some grandiose ideas for other formats (I hope not).
