### ISSUE TITLE
Some Hangables can be placed on blocks they aren't supposed to and won't break when blocks they are on are destroyed.

### ISSUE THREAD

**Issue by LittleBigBug** [cuberite/cuberite#5299]
Client version: 1.12
Server OS: Linux x64
Cuberite Commit id: 11ca2cf4c01426176e0b9f5111aa594afd10983a

Some hangable items like Paintings and Item frames can be placed on items they shouldn't be able to, like ladders and minecart rails.

![image](https://user-images.githubusercontent.com/10341753/133504974-af883498-cbe0-4e7b-8af8-a6b3749a337f.png)
![image](https://user-images.githubusercontent.com/10341753/133505105-d39ab521-451d-4011-bcc0-b4572e85ef46.png)
![image](https://user-images.githubusercontent.com/10341753/133505235-43e05177-2569-4766-9bb2-a205a909e2fd.png)
![image](https://user-images.githubusercontent.com/10341753/133505295-732689cc-5be0-4847-8377-22501f6d8e3d.png)

-----

Client version: 1.10.2
Server OS: linux
Cuberite Commit id:  approx: c2f8ceb554982a33bcd4a1e168f6c4e26d0b85dd built at: approx: 2020-09-05 17:13:44 +0200

### Expected behavior
Attachable objects are dropped once the block they were attached to is destroyed
![2020-09-12_03 36 27](https://user-images.githubusercontent.com/60849082/92981149-3202df00-f488-11ea-82ed-3908913372cc.png)
![2020-09-12_03 36 44](https://user-images.githubusercontent.com/60849082/92981164-3c24dd80-f488-11ea-92fc-222379ed9bad.png)

### Actual behavior
Certain objects still stay after the block underneath (or behind) they were attached to is destroyed
![2020-09-12_03 38 11](https://user-images.githubusercontent.com/60849082/92981183-4c3cbd00-f488-11ea-80da-8604bbd7fe3b.png)
![2020-09-12_03 38 22](https://user-images.githubusercontent.com/60849082/92981169-421abe80-f488-11ea-93a3-4369b09a4679.png)

**Comment by tigerw** [comment]
#4859

**Comment by tigerw** [comment]
We should be able to merge the images.
