### ISSUE TITLE
Entities positions are not sent immediately

### ISSUE THREAD

**Issue by LittleBigBug** [cuberite/cuberite#5306]
Client version: 1.8.9
Server OS: Linux Debian x64
Cuberite Commit id: 3b47eaadb85ac42b70d35d03d919181830b40a41

### Expected behavior
Entities appear where they are placed/spawned

### Actual behavior
Entities seem to interpolate from a different position to their spawnpoint. I was merging the armor stand patch and it seems to be lerping from z64

Doesn't seem to affect spawn eggs with monsters or mobs

### Steps to reproduce the behavior
Use 1.8.9 (doesn't seem noticable in 1.12) and place a boat or other entity you can place with a position.

**Comment by tigerw** [comment]
Beats me why this happens, as far as I could tell the initial position was correct.
