### ISSUE TITLE
Appveyor failing on master

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5309]
```
     Creating library C:/projects/cuberite/Debug x64/lib/Debug/Cuberite.lib and object C:/projects/cuberite/Debug x64/lib/Debug/Cuberite.exp
  Cuberite.vcxproj -> C:\projects\cuberite\Debug x64\Server\Cuberite.exe
  Building Custom Rule C:/projects/cuberite/CMakeLists.txt
cd Server
Install\PackWindowsExecutables.cmd
C:\projects\cuberite\Debug x64\Server>if defined APPVEYOR_PULL_REQUEST_NUMBER (
echo stop   1>>cmds.txt  
 Cuberite --port 32767   0<cmds.txt  
 exit /b 
) 
C:\projects\cuberite\Debug x64\Server>set lastexitcode=-1073741819 
C:\projects\cuberite\Debug x64\Server>set  1>C:\Users\appveyor\AppData\Local\Temp\1\tmp28F9.tmp 
C:\projects\cuberite\Debug x64\Server>echo C:\projects\cuberite\Debug x64\Server  1>C:\Users\appveyor\AppData\Local\Temp\1\tmp28FA.tmp 
C:\projects\cuberite\Debug x64\Server>exit /b -1073741819 
Command exited with code -1073741819
```

**Comment by tigerw** [comment]
That log looks like a PR build. Nonetheless current master is failing because

    C:\projects\cuberite\Release x64\Server>appveyor PushArtifact .luacheckrc 
    Error uploading artifact to the storage: One or more errors occurred.

**Comment by 12xx12** [comment]
This is taken from the master build

**Comment by tigerw** [comment]
Is this the one? https://ci.appveyor.com/project/Cuberite/cuberite/builds/40928160/job/0gk35fyrecxul98h

Not even sure what's wrong, seems like the executable insta-crashes with -1073741819 = 0xC0000005 "access violation". May be a TBB library issue.

**Comment by Project579** [comment]
The thing is it runs fine on both the windows systems I tried, not sure what could be causing it, there must be a way to get more info about that crash also it runs fine on release.

**Comment by tigerw** [comment]
master builds are confirmed working, close?
