### ISSUE TITLE
APIDump: could you provide generated .luacheckrc file in a repository?

### ISSUE THREAD

**Issue by ZwerOxotnik** [cuberite/cuberite#5319]
I use [GitHub actions](https://github.com/features/actions), but I have to manually change URLs in \*.yml files to make it work properly when the API changes.

It won't be necessary by using a repository/site with a link like this: https://github.com/cuberite/CuberitePluginChecker/raw/master/.luacheckrc

Example files:

*   lint.yml: https://gist.github.com/ZwerOxotnik/d223e9bed873ed73ccb7d4cc60b31984
*   .luacheckrc: https://gist.github.com/ZwerOxotnik/7db531cd3929535a79dc73359d9cc126

Why?

*   Less necessity in .luacheckrc in repositories
*   It gives possibility to lint with new API automatically, therefore it may warn about incompatibility with new version of API using GitHub actions

It's not so important, but I would like it.

**Comment by tigerw** [comment]
Forgive my lack of understanding, is this something which could be generated automatically or will we have to keep it up to up to date ourselves?

**Comment by ZwerOxotnik** [comment]
APIdump generates `.luacheckrc` semi-automatically, so it's possible to keep the file in a repository automatically by using scripts/GitHub actions, and it seems much easier to achieve by modifying `main_APIDump.lua` and not using it as a plugin.

And I tried plugins more, and I guess, currently, this request seems \*\*not important\*\* and \*\*quite specific\*\*.

**Comment by bearbin** [comment]
This is a reasonable request, I am minded to add it as a build artifact - do you absolutely need this as a repository or are you actually just asking for a consistent URL that will always have the latest version hosted there?

**Comment by ZwerOxotnik** [comment]
A consistent URL will be sufficient for all my possible needs.

**Comment by bearbin** [comment]
The file is now available on this link: https://builds.cuberite.org/job/cuberite/job/master/lastSuccessfulBuild/artifact/gcc_Release/Server/.luacheckrc
