### ISSUE TITLE
Add a way to send entity packets

### ISSUE THREAD

**Issue by AirOne01** [cuberite/cuberite#5327]
Client version: 1.12.2
Server OS: Manjaro Linux
Cuberite Commit id: 95bc2eac222a12c049b1aef799ac280fa9123af4

### Expected behavior
To have a way to send packet-level informations on entities to the client in the plugins.
Something like
- `cClientHandle:SendEntityAdd(cEntity)`
- `cClientHandle:SendEntityDestroy(cEntity)`
- `cClientHandle:SendEntityEdit(cEntity)`
(and maybe even add a constructor to the entity class), or
- `cClientHandle:SendEntityAdd(string, cEntity)`
- `cClientHandle:SendEntityDestroy(string)`
- `cClientHandle:SendEntityEdit(string, cEntity)`
(where `string` is an `UUID`).

This will literally be used everywhere (invisible armor stands with dynamic names, vanished players, anticheat, etc...). Using BungeeCord instead works, but it's not exactly ideal, and I don't think it will cost much performances.

### Actual behavior
There is no way to send informations about entities to a specific client.

**Comment by 12xx12** [comment]
seems like a duplicate of #5263

**Comment by AirOne01** [comment]
> seems like a duplicate of #5263

yup, my bad.
