### ISSUE TITLE
"Fire extinguishes" sound spam

### ISSUE THREAD

**Issue by AirOne01** [cuberite/cuberite#5331]
Client version: 1.12.2
Server OS: Windows 11
Cuberite Commit id: 95bc2eac222a12c049b1aef799ac280fa9123af4

### Expected behavior
No sound when swimming in both water and lava at the same time (except for eventual damage sound).

### Actual behavior
The "fire extinguishes" sound is spammed to the client.

### Steps to reproduce the behavior
Reproduce this setup and place your player between the two liquids, and make it so that you touch both of them at the same time.
![2021-11-20_13 10 52](https://user-images.githubusercontent.com/21955960/142725875-4fbc53f7-a401-42d8-9ed5-ddbdd777cd39.png)

**Comment by jaydevelopsshit** [comment]
Occurs in vanilla Minecraft too, pretty sure that's a client side thing.

**Comment by Pokechu22** [comment]
See [MC-148432](https://bugs.mojang.com/browse/MC-148432).  This was fixed in 21w05a (a 1.17 snapshot) apparently.

**Comment by AirOne01** [comment]
This is indeed client-sided.
