### ISSUE TITLE
Double tall grass drops seeds when broken in creative mode

### ISSUE THREAD

**Issue by AirOne01** [cuberite/cuberite#5333]
Client version: 1.12.2
Server OS: Windows 11
Cuberite Commit id: 95bc2eac222a12c049b1aef799ac280fa9123af4

### Expected behavior
When breaking double tall grass in creative, nothing is dropped

### Actual behavior
Seed sometimes drop when breaking double tall grass

### Steps to reproduce the behavior
Break double tall grass.

**Comment by bearbin** [comment]
I believe this is actually vanilla.

**Comment by AirOne01** [comment]
I just realised my issue can be missunderstood, sorry about that. I was actually refering to *double* tall grass.

**Comment by tigerw** [comment]
Easy because cBlockBigFlowerHandler literally calls DropBlockAsPickups in its OnBroken handler. This seems deliberate, so we mainly need to figure out if there's justification to do that and change to SetBlock(AIR) if not.

**Comment by QDaily117** [comment]
Are you guys still wanting this change to happen? I would be more than happy to make this change for you guys

**Comment by tigerw** [comment]
Yes, thanks! I agree it's a bug.

**Comment by RodargDev** [comment]
@bearbin this has been resolved and can be closed
