### ISSUE TITLE
Furnace accepts illegal blocks in fuel slot

### ISSUE THREAD

**Issue by RodargDev** [cuberite/cuberite#5366]
Client version: 1.12.x
Server OS: Windows
Cuberite Commit id: 1edc6c8601f9d00751bf7c9f7fcc69d1e18bb46a

### Expected behavior
Being unable to put cobblestone in the fuel slot of the furnace

### Actual behavior
Furnace accepts cobblestone in fuel slot of furnace

### Steps to reproduce the behavior
Place a furnace and put a cobblestone block in fuel slot

**Comment by InfRandomness** [comment]
I am taking a shot at solving this issue

**Comment by supopurskola** [comment]
And does the furnace burn it?

**Comment by RodargDev** [comment]
> And does the furnace burn it?

It does not, but it should be impossible to put an invalid block into the slot.
