### ISSUE TITLE
Chests disappear when killed or rejoining server

### ISSUE THREAD

**Issue by RodargDev** [cuberite/cuberite#5367]
Client version: 1.12
Server OS: Windows
Cuberite Commit id: 1edc6c8601f9d00751bf7c9f7fcc69d1e18bb46a

### Expected behavior
Chests should stay where they are and not disappear whenever someone gets killed or leaves the server

### Actual behavior
Chests disappear whenever you get killed or leave and rejoin the server 

### Steps to reproduce the behavior
1. Place a chest and put blocks in the chest
2. Get killed or leave and rejoin the server
3. Chest should not be there anymore

4. Place a newly crafted chest on the same location as the chest that disappeared and it wont use the chest to place another chest (So chest reappears but you still have your newly crafted chest in hand)
5. Open the reappeared chest and you will find the items you put in it in step 1.

**Comment by bearbin** [comment]
Thanks for sending these steps to reproduce, hopefully we'll get to the bottom of this.

**Comment by RodargDev** [comment]
> Thanks for sending these steps to reproduce, hopefully we'll get to the bottom of this.

Can now confirm unloading the chunk is probaply the problem. When just walking from render distance unloading the chunk and then loading the chunk again it will disapear too.

**Comment by tigerw** [comment]
fix incoming, stand by
