### ISSUE TITLE
Spider being able to walk through a 1 block wide entrance

### ISSUE THREAD

**Issue by RodargDev** [cuberite/cuberite#5368]
Client version: 1.12
Server OS: Windows
Cuberite Commit id: 1edc6c8601f9d00751bf7c9f7fcc69d1e18bb46a

### Expected behavior
Spiders shouldn't be able to walk through a 1 block wide entrance

### Actual behavior
Spiders are able to walk through a 1 block wide entrance having their legs clip through the walls

### Steps to reproduce the behavior
Be in survival and make a 1 block wide entrance, spawn a spider and hit him. He will follow you through the 1 block wide entrance

**Comment by tigerw** [comment]
arachnophobia mode

**Comment by bearbin** [comment]
Duplicate of #3747
