### ISSUE TITLE
Maybe display IP adress on startup

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5381]
We had someone needing help on the discord server, and some might be resolved by displaying the server's IP address.

This is just an idea. And i'd like to hear your thoughts

**Comment by tigerw** [comment]
We have a message saying "Webadmin running on port 8080" so extending that message would make sense. But getting the public IP? It may be more educational to tell people how to do it themselves via icanhazip.com or similar.

**Comment by bearbin** [comment]
It's not technically possible to get the public inbound IP. We can make a reasonable guess by pinging out to an internet server that returns the IP but that's relatively useless - if somebody doesn't know their public IP, they can't set up port forwarding; this will just cause more headaches for us.

Slightly different for local network IP, although a computer can have multiple network interfaces it should be possible to programmatically get all the IPs. This will be OS-specific and annoying though. I'm not opposed to this as it would certainly be a useful feature but (personally) it's more work than it's worth. If this issue really takes somebody then make a PR.

**Comment by bearbin** [comment]
#5593 is an unrelated improvement, we still don't print the IP address (just the port).

**Comment by Janmm14** [comment]
Due to the technical challenges I would advice to close this as not planned.
