### ISSUE TITLE
Latest pre-compiled armhf binary fails on aarch64

### ISSUE THREAD

**Issue by MichaIng** [cuberite/cuberite#5386]
Client version: x.x.x
Server OS: Debian Bullseye
Cuberite Commit id: https://builds.cuberite.org/job/linux-armhf/322/

### Expected behavior
Since `aarch64` is backwards compatible to ARMv6/ARMv7, the `armhf` binary should generally run on `aarch64` systems. It did in the past and the official installer explicitly expects this as well: https://github.com/cuberite/cuberite/blob/master/easyinstall.sh

### Actual behavior
```
# ls -l Cuberite
-rwxr-xr-x 1 cuberite cuberite 6796912 Jan 16 17:53 Cuberite
# ./Cuberite
-bash: ./Cuberite: No such file or directory
```
The error message is misleading, but we know this from specific cases where an executable binary is incompatible with the system architecture. I checked the executable with `readelf` and it basically looks fine, and most importantly on ARMv6/ARMv7 `armhf` systems it does run fine.

### Steps to reproduce the behavior
On an ARMv8/`aarch64` system:
```
curl -sSfL 'https://download.cuberite.org' | sh
./Cuberite
```

### Server log
```
-bash: ./Cuberite: No such file or directory
```

**Comment by bearbin** [comment]
This will _probably_ have to do with the recent update we made to polarssl/mbedtls. @tigerw did you make any changes to CMake that might have messed this up?

**Comment by tigerw** [comment]
Nothing changed in the CMake files, did the builds work before?

You may need the ARM32 C and C++ runtime installed on your ARM64 system for it to work, but not sure what exactly the magic commands are.

**Comment by tigerw** [comment]
Could also be the interpreter file which as I understand resolves and loads the shared libraries the binary needs, it's currently pointing to `/lib/ld-linux-armhf.so.3` so I guess that file has to be present on ARM64 DietPi.

**Comment by MichaIng** [comment]
Checking via `ldd`/`readelf`, there are no shared objects loaded at all, i.e. it is a statically compiled binary. Also it did work on `aarch64`/`arm64` systems before without installing `armhf` packages/libc6 🤔. I'll retest the older builds so verify and find the last binary which runs on `aarch64`.

Interesting that you mention `/lib/ld-linux-armhf.so.3`, where did you find the info that this is aim to be loaded? My first attempt to replicate the issue was on an `x86_64` VM running an `aarch64` container via `binfmt-support`=>`qemu-user-static` which showed exactly this error of missing `/lib/ld-linux-armhf.so.3`. However, I am pretty sure that it is `qemu-user-static` in this case which sees that it is an `armhf` binary and then tries to load `libc6` libraries automatically. Executing the file directly on a real `aarch64` machine doesn't give any hint about that, and as said, checking with the known tools there are no shared objects linked 🤔.

**Comment by tigerw** [comment]
We'd need the system's C/C++ runtime, so if I'm interpreting `readelf -d Cuberite` correctly:

```
Dynamic section at offset 0x51bee8 contains 30 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libdl.so.2]
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x0000000c (INIT)                       0x166f8
 0x0000000d (FINI)                       0x45e018
...
```

we do pull those in and some other stuff too.

I find the interpreter information from `file Cuberite` which says:

`Cuberite: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 4.20.8, with debug_info, not stripped`

**Comment by MichaIng** [comment]
You are right, running `ldd`/`readelf` on an ARMv6/ARMv7 system shows the dynamically linked libraries, doing the same on an `aarch64` system does not 🙈.

Wouldn't it be possible to link `ld-linux.so` instead of `ld-linux-armhf.so.3`? On ARMv6/ARMv7 it doesn't make a difference (the first is a symlink to the second) but on `aarch64` it should be resolved to the `aarch64` interpreter then:
```sh
# patchelf --set-interpreter ld-linux.so Cuberite
# ldd Cuberite
        linux-vdso.so.1 (0x7ef5d000)
        /usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x76f04000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76ef1000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76ecb000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76d66000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76cfe000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76cd5000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76bce000)
        ld-linux.so => /lib/ld-linux-armhf.so.3 (0x76f19000)
```
But to be true, manually patching the ELF header linke that breaks the binary on ARMv6/7 and doesn't allow to run it on `aarch64`, despite the link shown correctly. On `aarch64` (binfmt container though):
```sh
# ./Cuberite
arm-binfmt-P: Could not open 'ld-linux.so': No such file or directory
```
On ARMv7:
```sh
# ./Cuberite
bash: ./Cuberite: No such file or directory
```

I'll test older binaries now, I'm pretty sure it worked once.

**Comment by MichaIng** [comment]
Okay, linking the `aarch64` interpreter explicitly doesn't work either, also not on a real ARMv8 system. Looks like we blindly adopted from #5237.

As of #5221, does Ubuntu `aarch64` ship with `dpkg --add-architecture armhf` and `libc6:armhf` pre-installed?

**Comment by tigerw** [comment]
I don't have an aarch64 system to test on, I'm surprised it's not as easy as running ia32 on amd64.

Is DietPi all native arm64 software? For providing pre-built native binaries, @bearbin is the master of infrastructure.

**Comment by MichaIng** [comment]
> Is DietPi all native arm64 software?

Yes, all Debian `arm64` package repository only. I mean we could add `armhf` and install `libc6:armhf` for Cuberite on `aarch64` systems, but I'm no fans of installing a tail of `armhf` dependencies in favour of native `arm64` binaries.

**Comment by bearbin** [comment]
Providing native aarch64 would be nice - that said while I am the buildmaster I am no master of build tooling. If somebody can provide a CMake toolchain file that works, I can set up the build.

**Comment by bearbin** [comment]
This is the current toolchain file for armhf builds, which depends a load of header files manually extracted from a Raspberry Pi installation. Ideally debian should already have all the necessary headers already, or it should just be a new package to install (but which?) 

```cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_C_COMPILER ${CMAKE_CURRENT_LIST_DIR}/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_CURRENT_LIST_DIR}/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/arm-linux-gnueabihf)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

**Comment by MichaIng** [comment]
I'm no master of CMake, I just wrote this script for compiling, packing and uploading on a DietPi system 😄:
```sh
#!/bin/bash
. /boot/dietpi/func/dietpi-globals

# Dependencies
G_AGI git cmake make g++ python3

# Build
G_EXEC cd /tmp
[[ -d 'cuberite-master' ]] && G_EXEC rm -R cuberite-master
G_EXEC git clone --depth 1 'https://github.com/cuberite/cuberite.git'
G_EXEC cd cuberite-master
G_EXEC git submodule sync
G_EXEC git submodule update --init
G_EXEC mkdir build
G_EXEC cd build
G_EXEC_OUTPUT=1 G_EXEC cmake .. -DCMAKE_BUILD_TYPE='Release' -DCMAKE_C_FLAGS='-g0 -O3' -DCMAKE_CXX_FLAGS=CFLAGS='-g0 -O3' -- -j$(nproc)
G_EXEC_OUTPUT=1 G_EXEC make CFLAGS='-g0 -O3' CXXFLAGS='-g0 -O3' -j$(nproc)
G_EXEC cd Server
G_EXEC rm BindingsDocs Install lua
G_EXEC strip --remove-section=.comment --remove-section=.note Cuberite

# Archive
[[ -d '/tmp/cuberite' ]] && G_EXEC rm -R /tmp/cuberite
G_EXEC cd ..
G_EXEC cp -aL Server /tmp/cuberite
G_EXEC cd ..
G_EXEC rm -R cuberite-master
G_EXEC tar -cjf cuberite_$G_HW_ARCH_NAME.tar.bz2 cuberite

# Upload
G_EXEC curl -T cuberite_$G_HW_ARCH_NAME.tar.bz2 --key XXX --pubkey XXX "XXX"
G_EXEC rm cuberite_$G_HW_ARCH_NAME.tar.bz2
```
- `G_AGI` ~= `apt-get install`
- `G_EXEC` = error handler
- `G_HW_ARCH_NAME` == `aarch64`

So yes, Debian has everything that is required and CMake finds all tools and headers automatically, given you do the build on an actual `aarch64` system, i.e. no cross-compiling, when installing the packages `cmake` `make` `g++` and for one of the builds `python3`.

**Comment by bearbin** [comment]
Unfortunately cross-compiling is a given with our infrastructure. Adding additional flaky hardware is not possible without a budget (money to host it, and time to keep it up), so we'll have to stick with a toolchain file.

**Comment by MichaIng** [comment]
Just checking for cross-compiling tools and headers:
- https://packages.debian.org/g++-aarch64-linux-gnu
- https://packages.debian.org/libc6-dev-arm64-cross

Then, just derived from above:
```cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)
set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
Not sure about the last three here, and generally I guess that with `aarch64-linux-gnu-gcc`/`aarch64-linux-gnu-g++` the correct libraries/headers are found automatically without explicitly defining related paths.

**Comment by bearbin** [comment]
I've set up a build to test - I'd appreciate confirmation if this is working or not:

https://builds.cuberite.org/job/linux-aarch64/

**Comment by MichaIng** [comment]
Wow, many thanks for providing this so quickly, it works very well as far as I can say:
```
# ss -tlpn | grep Cuberite
LISTEN 0      4096               *:1339             *:*    users:(("Cuberite",pid=1941,fd=9))
LISTEN 0      4096               *:25565            *:*    users:(("Cuberite",pid=1941,fd=8))
# cat /mnt/dietpi_userdata/cuberite/logs/LOG_1642811740.txt
     [00:35:40] --- Started Log ---
     [00:35:40] Cuberite Jenkins arm-linux-gnueabihf -DCMAKE_BUILD_TYPE=Release (master) (id: #4)
     [00:35:40] from commit e3d0874f7d255e1d00cd2fd69b76b9414e8e3b5b built at: Sat Jan 22 00:15:02 UTC 2022
     [00:35:40] Creating new server instance...
     [00:35:40] Reading server config...
Warn [00:35:40] Regenerating settings.ini, all settings will be reset
     [00:35:40] Starting server...
Info [00:35:40] Compatible clients: 1.8.x-1.12.x
Warn [00:35:40] WebServer: The server will run in unsecured HTTP mode.
Info [00:35:40] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
Info [00:35:40] Creating default ranks...
Info [00:35:40] Default ranks created.
     [00:35:40] Loaded 789 crafting recipes
     [00:35:40] Loaded 1.12.2 380 recipe book
Warn [00:35:40] Cannot open file "Protocol/1.13/base.recipes.txt", no recipe book recipes will be available!
Warn [00:35:40] Cannot open file "Protocol/1.14.4/base.recipes.txt", no recipe book recipes will be available!
     [00:35:40] Loaded 67 furnace recipes and 66 fuels
     [00:35:40] Loaded 49 brewing recipes
Warn [00:35:40] Failed to load scoreboard from "world/data/scoreboard.dat": basic_ios::clear: iostream error
Warn [00:35:40] Cannot read world settings from "world/world.ini", defaults will be used.
Info [00:35:40] Chosen a new random seed for world: 1242690746
Warn [00:35:40] Invalid biome ("BambooJungle") specified in AllowedBiomes in cubeset file Prefabs/SinglePieceStructures/JungleTemple.cubeset. Skipping the biome.
Warn [00:35:40] Invalid biome ("BambooJungleHills") specified in AllowedBiomes in cubeset file Prefabs/SinglePieceStructures/JungleTemple.cubeset. Skipping the biome.
Warn [00:35:40] Failed to load scoreboard from "world_nether/data/scoreboard.dat": basic_ios::clear: iostream error
Warn [00:35:40] Cannot read world settings from "world_nether/world.ini", defaults will be used.
Info [00:35:40] Chosen a new random seed for world: 309286954
Warn [00:35:40] Failed to load scoreboard from "world_the_end/data/scoreboard.dat": basic_ios::clear: iostream error
Warn [00:35:40] Cannot read world settings from "world_the_end/world.ini", defaults will be used.
Info [00:35:40] Chosen a new random seed for world: 1749129777
     [00:35:40] -- Loading Plugins --
     [00:35:41] [Core] Initialised!
     [00:35:41] [ChatLog] Initialized ChatLog v.3
     [00:35:41] -- Loaded 2 Plugins --
     [00:35:42] Preparing spawn (world): 3.75% (15/400; 14.38 chunks / sec)
     [00:35:43] Preparing spawn (world): 14.00% (56/400; 38.90 chunks / sec)
     [00:35:44] Preparing spawn (world): 29.00% (116/400; 59.46 chunks / sec)
     [00:35:45] Preparing spawn (world): 42.75% (171/400; 53.55 chunks / sec)
     [00:35:46] Preparing spawn (world): 61.00% (244/400; 72.64 chunks / sec)
     [00:35:47] Preparing spawn (world): 75.75% (303/400; 58.01 chunks / sec)
     [00:35:48] Preparing spawn (world): 89.00% (356/400; 51.96 chunks / sec)
     [00:35:50] Preparing spawn (world): 45.75% (183/400; 177.33 chunks / sec)
     [00:35:51] Preparing spawn (world): 80.75% (323/400; 137.39 chunks / sec)
     [00:35:52] Preparing spawn (world): 94.50% (378/400; 54.95 chunks / sec)
Info [00:35:52] World "world":Generated spawnpoint position at {136, 42, 0}
     [00:35:53] Preparing spawn (world_nether): 9.50% (38/400; 37.66 chunks / sec)
     [00:35:54] Preparing spawn (world_nether): 28.50% (114/400; 75.92 chunks / sec)
     [00:35:55] Preparing spawn (world_nether): 51.00% (204/400; 89.91 chunks / sec)
     [00:35:56] Preparing spawn (world_nether): 74.50% (298/400; 93.44 chunks / sec)
Info [00:35:57] World "world_nether":Generated spawnpoint position at {0, 35, 16}
     [00:35:58] Preparing spawn (world_the_end): 32.50% (130/400; 128.97 chunks / sec)
     [00:35:59] Preparing spawn (world_the_end): 69.50% (278/400; 147.56 chunks / sec)
Warn [00:36:00] World "world_the_end": Did not find an acceptable spawnpoint. Generated a random spawnpoint position at {0, 68, 0}
```
It still says `Cuberite Jenkins arm-linux-gnueabihf`, but it works.
