### ISSUE TITLE
You can fall through farmland when it naturally turns into dirt

### ISSUE THREAD

**Issue by DarkoGNU** [cuberite/cuberite#5402]
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: de5b89dbea938db5a7ea58f59a9b1a91d0df4208

### Expected behavior

When farmland turns into dirt (because it's dry and there's no water sources nearby), you should stay on top of the block.

### Actual behavior

When farmland turns into dirt, you fall through it.

### Steps to reproduce the behavior

1. Create some farmland. Make sure there's no water source nearby and it doesn't rain.
2. Stand on it.
3. Wait patiently.
4. You've fallen through it.

### Additional notes

Vanilla Minecraft also had a similar bug - see [MC-104259](https://bugs.mojang.com/browse/MC-104259). I think I'll fix this bug when working on #5401, as I don't want farmland trampling to be buggy.

### Screenshots

![First](https://user-images.githubusercontent.com/42816979/161653886-8235104c-2453-40c8-a018-9d301f5bf805.png)
![Second](https://user-images.githubusercontent.com/42816979/161653900-bbddc817-ca08-41ec-a52c-0e348e1fb220.png)
(cute!)

![Third](https://user-images.githubusercontent.com/42816979/161653905-5f8bbaaf-6278-4dda-8522-cc186318b6cb.png)
![Fourth](https://user-images.githubusercontent.com/42816979/161653910-3da49f52-df6c-4eb0-b3fe-0bf2534e3462.png)

**Comment by DarkoGNU** [comment]
Also a note about hydration by rain - my issue originally contained a statement that it's buggy, but it's not buggy. Stupid me created some farmland under a tree and expected it to be hydrated by rain :relieved:

**Comment by tigerw** [comment]
It's an actual _edge_ case, wow. Thanks for reporting.
