### ISSUE TITLE
Checking for server status issue

### ISSUE THREAD

**Issue by Xgone-DEV** [cuberite/cuberite#5430]
Client version: 1.12.2
Server OS: Linux: Raspbian
Cuberite Commit id: a2b19de07836f7273c66e3cba9922e110bf559e7

### Expected behavior
For the server to continue just fine

### Actual behavior
it aborts the server as soon as i search in any external site if my server is in online status.

### Steps to reproduce the behavior

-Simply boot up the server and wait till its done starting up.

-got to an external site like https://www.minecraft-server-status.com/ and type in your domain to check the servers status.

-The server will immediately abort.

### Server log
```
[issue.txt](https://github.com/cuberite/cuberite/files/9075775/issue.txt)

Relevant part of server log

```[23:08:23] Verification failed: a_Out.WriteVarUTF8String(Response), file /jenkins/workspace/linux-armhf/src/Protocol/ProtocolRecognizer.cpp, line 452
./Cuberite[0x1b1804]
/lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0x0)[0xb6b73da0]
/lib/arm-linux-gnueabihf/libc.so.6(gsignal+0xbc)[0xb6b728c0]
[23:08:23] Failure report:

  :(   | Cuberite has encountered an error and needs to close
       | SIGABRT: Server self-terminated due to an internal fault
       |
       | Cuberite Jenkins arm-linux-gnueabihf-raspbian -DCMAKE_BUILD_TYPE=Release (master) (id: #349)
       | from commit a2b19de07836f7273c66e3cba9922e110bf559e7 
       
```

**Comment by tigerw** [comment]
Hi, thanks for the report, I think this is another manifestation of #5399 and #4337. Is your server icon very large?

**Comment by Xgone-DEV** [comment]
Nope its even by the same size the original image used which is 64x64.
![favicon](https://user-images.githubusercontent.com/54164730/178126180-1d09b481-5694-45d3-b485-ed3ca8039712.png)
.

**Comment by KingCol13** [comment]
It is 6.5kb which is larger than the default (2.18kb) and larger than the 6kb `cByteBuffer` that we allocate for it.

**Comment by tigerw** [comment]
Do you think we should just bump up the allocation size to hotfix the issue?

**Comment by KingCol13** [comment]
> Do you think we should just bump up the allocation size to hotfix the issue?

Maybe we could use `cServer::GetFaviconData()` to set the buffer to a size guaranteed big enough to store the icon? Otherwise potentially `cPacketizer`?
