### ISSUE TITLE
Invisible Torches after Reconnecting to Server

### ISSUE THREAD

**Issue by blueyshark** [cuberite/cuberite#5432]
Client version: 1.12.2
Server OS: DietPi (debian-based on Raspberry Pi 4)
Cuberite Commit id: unsure

### Expected behavior
Placing a torch during a session, will be visible, and remain visible when reconnecting to the server later. Client is running MX Linux (Debian), MultiMC 5, running instance 1.12.2 without mods/vanilla.

### Actual behavior
See image [here](https://photos.app.goo.gl/w4hZXxTcNPw24X8t8). A torch will remain visible after placing, during gameplay. After re-connecting to server, torch asset does not appear visible; light is cast, and when the block a torch is placed on is mined, the torch is retrievable.

### Server log
```
Relevant part of server log
```

**Comment by tigerw** [comment]
Thanks for the report, the regression was introduced in January!

Also your website is hella cool, the waddling spark plug is funny
