### ISSUE TITLE
Travis ci .org become jenkins No build since a year now

### ISSUE THREAD

**Issue by tonitch** [cuberite/cuberite#5459]
https://github.com/cuberite/cuberite/blob/70daa63478493b4269cf487fffec47e9ad040dce/GETTING-STARTED.md?plain=1#L134

When you go on the page, Travis CI won't build anything as explained in the orange bar a the top of the website

**Comment by 12xx12** [comment]
We don't even use travis. We are now using Jenkins

**Comment by tonitch** [comment]
I though so ^^ but maybe it could still be changed in the GETTING-STARTED.md ?

**Comment by bearbin** [comment]
Removed from getting-started, thanks for pointing it out.
