### ISSUE TITLE
Not Tested: Enderpearl should not make damage to mob

### ISSUE THREAD

**Issue by tonitch** [cuberite/cuberite#5461]
following the ender pearl page: https://minecraft.fandom.com/wiki/Ender_Pearl
there is a line at the end saying that the enderpearl should not make damage to other entities 
![image](https://user-images.githubusercontent.com/26271060/201543874-7c1472cf-ce9e-45cd-b671-b46915e55bc1.png)

by looking into the code for implementing endermite, i found that line https://github.com/cuberite/cuberite/blob/70daa63478493b4269cf487fffec47e9ad040dce/src/Entities/ThrownEnderPearlEntity.cpp#L20-L34 
which state the oppposite

I don't know if this is an old behaviour or anything and I haven't tested anything. just droping an issue in case someone whould like to figure it out.

**Comment by tonitch** [comment]
Sorry, my mistake.... I though the final 1 at Line 31 was the dammage but it's the knock back and the damage is clearly set to 0. which is the exact behaviour.

Gonna keep going on my own stuff then ^^

**Comment by 12xx12** [comment]
Now we are sure it's done correctly :D
