### ISSUE TITLE
Raspberry Pi aarch64 missing dependencies

### ISSUE THREAD

**Issue by anatolykopyl** [cuberite/cuberite#5465]
Easyinstall script identifies and downloads aarch64 binaries:
```
Identifying kernel: Linux
Identifying platform: aarch64
Downloading precompiled binaries.
```

But the server won't start:
```
./Cuberite: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./Cuberite)
./Cuberite: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Cuberite)
```

**Comment by bearbin** [comment]
This is more likely a problem with your machine - what OS and version are you using? If you're using something very old it won't be supported.

**Comment by KingCol13** [comment]
It could also be that your libc version is too new (debian bullseye is quite old) or that you use a distribution with musl libc which may not be supported (#5288). Compiling yourself takes a while but should produce a binary that works on your machine (provided it isn't using musl).

**Comment by anatolykopyl** [comment]
@bearbin Debian Buster. Switched to Ubuntu Server and everything works now. Thanks for the help!

**Comment by bearbin** [comment]
Yep, buster isn't one we support, we do debian stable or up, so you'd have to be on bullseye. Ubuntu also works if it's recent enough. Glad it's all sorted out.
