### ISSUE TITLE
cScoreBoard:RegisterTeam doesn't return cTeam

### ISSUE THREAD

**Issue by 209CATrus** [cuberite/cuberite#5466]
Client version: Latest
Server OS: Windows/Linux
Cuberite Commit id: Doesn't matter

### Expected behavior
cScoreBoard:RegisterTeam returning team handle

### Actual behavior
Apparently returns nil

### Steps to reproduce the behavior
@tonitch Can help with reproduction, but that shouldn't be necessary 

### Server log
```
Relevant part of server log
```

**Comment by tonitch** [comment]
for some reasons, here is the value of status (from gdb) at scoreboard.cpp#366
$1 = {first = <error reading variable: Cannot access memory at address 0x100000000>, second = false}
so obviously the return statement return false as second = false...

**Comment by tonitch** [comment]
a way to avoid confusion while not altering any change in the current plugins is to use
[std::map::insert_or_assign](https://en.cppreference.com/w/cpp/container/map/insert_or_assign) instead of insert... I don't think it's a bad idea ^^

**Comment by 12xx12** [comment]
The return value is NIL if a team with the same name already exists. I will add an error message to console and documentation to explain this
