### ISSUE TITLE
Reverse compiling Lua as C++

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#5492]
Previously it was possible to replace the Lua dll with a different one, even LuaJIT was able to work this way. I noticed this isn't possible anymore. After searching around I found out that our Lua binary is compiled as C++ code (https://github.com/cuberite/cuberite/pull/5248). When I reversed those changes I was able to use LuaJIT again. I suspect this has some other consequences like not being able to load any luarocks libraries, so I think we should consider reversing the change.

**Comment by madmaxoft** [comment]
Even worse, it's now impossible to use system-wide lua libraries (such as LuaSocket, LuaFileSystem et al.) in plugins. This especially breaks debugging Cuberite plugins using ZBS or any other editor that uses the MobDebug package, since it requires LuaSocket.
