### ISSUE TITLE
Replace hand-escaped JSON with proper JSON serialization

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#5496]
In several places within the codebase, we build a JSON string manually using `Printf` or `fmt::format`:
```cpp
SendChatRaw(fmt::format(FMT_STRING("{{\"text\":\"{}\"}}"), EscapeString(a_Message)), a_Type);
```

This should be replaced with code that uses the jsoncpp library already present within the codebase to serialize the object properly, such as:
```cpp
Json::Value RootValue;
RootValue["text"] = a_Message;
SendChatRaw(JsonUtils::WriteFastString(RootValue), a_Type);
```

Possibly the JSON serialization could be lifted to a separate string so that the call becomes:
```cpp
SendChatRaw(SerializeSingleValueJsonObject("text", a_Message), a_Type);
```

**Comment by Griezn** [comment]
I would like to start contributing to this project, and this is an excellent issue to get going. But my question is in which file would I need to create the `SerializeSingleValueJsonObject("text", a_Message)` function?

**Comment by madmaxoft** [comment]
Welcome. Try StringUtils, that's probably the best place for now.
