### ISSUE TITLE
是否有计划的添加基岩版协议的支持？【Are there plans to add support for the Bedrock Edition protocol?】

### ISSUE THREAD

**Issue by dyexlzc** [cuberite/cuberite#5512]
我想知道目前是否有考虑开发java&基岩版本同时支持的工作？
如果没有的话，我可以尝试一下

I would like to know if there is currently any work considering developing java & bedrock versions to support at the same time?
If not, I can try

### Server log
```
Relevant part of server log
```

**Comment by Q2297045667** [comment]
这个服务端做了很久了，要是想要支持的话早就支持了

**Comment by dyexlzc** [comment]
> 这个服务端做了很久了，要是想要支持的话早就支持了

群里问了，说是用现有的基岩java互通模块支持就行，不重新做一套了

**Comment by dxomg** [comment]
理论上，你可以通过使用带有以下插件（Geyser、Viaversion、ViaBackwards、ViaRewind）的代理和Cuberite服务器的组合来实现。【In theory you can achieve this by using a combination of a proxy with the following plugins (Geyser, Viaversion, ViaBackwards, ViaRewind) and a Cuberite Server】

**Comment by mathiascode** [comment]
Duplicate of https://github.com/cuberite/cuberite/issues/4191
