### ISSUE TITLE
[Building] What's the first GCC version which supports C++17?

### ISSUE THREAD

**Issue by f1refa11** [cuberite/cuberite#5527]
Wikipedia said that: "GCC has had complete support for C++17 language features since version 8.", but when i tried to run the compilation using version 8.1.0, an error appeared several times:
```
/src/cuberite/src/Globals.h:143:19: fatal error: variant: No such file or directory
 #include <variant>
```
and then the compilation crashes.
So what gcc version do i need to support c++17?

**Comment by bearbin** [comment]
In theory GCC 8 should work - are you sure you're actually using 8 to compile? 

In any case, it's not an officially supported configuration, we only support compilers back to what debian stable is using (gcc 10 ATM) so you're really on your own here.
