### ISSUE TITLE
Website download page windows does not work

### ISSUE THREAD

**Issue by vinoaryo** [cuberite/cuberite#5541]
![image](https://github.com/cuberite/cuberite/assets/73981680/f3fea35b-d401-4af9-a247-76eb5f125459)

Im using windows, when I try to download Cuberite using the website it says "{"message":"Artifact not found or access denied."}"

**Comment by Seadragon91** [comment]
That should be the reason:
`Artifacts older than 1 month are automatically deleted. For more details see [Artifacts retention policy](https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy).`

**Comment by 12xx12** [comment]
Wait a few minutes. The build is running
