### ISSUE TITLE
Move forum to new hosting provider

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#5561]
Since hopefully everyone involved is active on GitHub, this is an attempt to get a discussion rolling regarding the forum.

@sphinxc0re has previously mentioned on Discord that he wants to move the forum away from the current hosting provider. I believe he was also willing to continue hosting the forum (correct me if I'm wrong). @bearbin Is this fine with you?

Migration shouldn't be too difficult. We need the current forum files and a backup of the database. There are most likely instructions available online.

I've had FTP access to the forum for many years, mainly for updating the forum software. I'd be willing to continue doing so.

**Comment by bearbin** [comment]
I'm happy with the concept of migrating/updating the forum. I'm happy for SphinxC0re to host the forum, I'm also happy to host it as well (I have more than enough hardware).

I think we should also reconsider whether we want to keep MyBB as the forum software in the longer term. Lots of other forums I'm members of have moved across to using Discourse, which is definitely a lot more modern and usable (mobiles etc).

**Comment by mathiascode** [comment]
> I think we should also reconsider whether we want to keep MyBB as the forum software in the longer term. Lots of other forums I'm members of have moved across to using Discourse, which is definitely a lot more modern and usable (mobiles etc).

I don't think there's any urgency to change the forum software, but if/when we do:
- Carefully consider the alternatives. Go for something popular, to reduce the chances of having to migrate content again.
- Ensure everything is migrated properly, including attachments and likes (if possible, it's a custom plugin). No mangled post formatting, etc.

Changing the software should only be considered after we've moved the current forum to another hosting provider, in my opinion.

**Comment by NiLSPACE** [comment]
I wouldn't be against migrating away from MyBB, especially if we can get better anti-bot detection. I do agree with @mathiascode points though. We shouldn't migrate to something just because it's the current popular thing. Also, in addition to likes, the tag to format code in forum posts (`[shcode='lua']...[/shcode]`) is also a plugin which would have to be migrated.

If possible it would be nice if we can migrate to something that uses Markdown instead of tag-formatted posts. That would mean we'd have to convert all the posts though, but I wouldn't be surprised if there is a tool already to do that.

**Comment by sphinxc0re** [comment]
Small update: My provider is phasing out the VPS plan I'm using, and the OS used probably has a bazillion CVEs. We should act sooner than later.

**Comment by mathiascode** [comment]
> Small update: My provider is phasing out the VPS plan I'm using, and the OS used probably has a bazillion CVEs. We should act sooner than later.

Do you have a new hosting provider you can use, and do you need help with migrating the forum?

**Comment by bearbin** [comment]
My Cuberite dedi-box is also available for the forum, I'd also be happy to set it up there if you send over a backup file.

**Comment by mathiascode** [comment]
> My Cuberite dedi-box is also available for the forum, I'd also be happy to set it up there if you send over a backup file.

I could do that. Where do you want me to send the backup?

**Comment by bearbin** [comment]
However would be most convenient for you - email me a link to your preferred file sharing service, torrent file, onionshare... Or I could set you up an account on the box and you ssh it across if you prefer.

**Comment by mathiascode** [comment]
I've sent a link via email. You should be able to follow these instructions to get the forum running: https://docs.mybb.com/1.8/faq/moving-to-a-new-web-host/

Let me know if there's any issue with the backup.

**Comment by bearbin** [comment]
Which email have you sent to? I haven't received anything yet (maybe it's in greylisting if you sent to me@bearbin.net..?)

I'm ready to apply the backup to the server once I get it.

**Comment by bearbin** [comment]
Ah, arrived now, no worries. I am working on getting it set up, hopefully I'll have it done tonight :)

**Comment by bearbin** [comment]
The forum is now migrated onto the new infra, please check it works adequately! It seems to work for me but I know that's no guarantee...

**Comment by bearbin** [comment]
Ah, not quite. I can log in and view the control panels, but not posts themselves... did we have a custom rewrite rule for the post URLs?

**Comment by mathiascode** [comment]
We have a SEO plugin that adds rewrite rules to the .htaccess file. They should work as long as you're using the Apache HTTP Server.

**Comment by bearbin** [comment]
Ah, nginx rather than apache, I didn't spot the htaccess so I'll switch them over.

**Comment by bearbin** [comment]
Finally got it working, that was a nightmare! I converted the htacces rules to nginx rules but ended up with infinite redirects, so assumed I had somehow done it wrong. So I tried converting to apache, which was a huge pain as I was using a docker env and the official mybb docker assumes nginx with fpm so it all has to be done manually otherwise. Eventually got that working, except the infinite redirects were still there! Turns out the google SEO plugin is just badly written and breaks when it's behind a reverse proxy. So patched that and it seems to finally work. I could probably have stuck with the nice official nginx image in the first place :(

Anyway, it appears to be all working fine (maybe excepting file uploads, haven't tested them, but it's enough for tonight anyway) for now at least!

**Comment by mathiascode** [comment]
Thanks! Where exactly was the patch made?

 Two issues I've noticed so far:
- Post content is empty when logged in
- All users have the IP address 172.22.0.4 (can we forward the user's actual IP?)

**Comment by mathiascode** [comment]
Turns out the first issue was caused by the "Preparser Cache" plugin. I'm guessing it's not compatible with PHP 7.x. I don't think we need it anyway.

There are a couple of plugin updates listed [here](https://forum.cuberite.org/admin/index.php?module=config-plugins&action=check), including Google SEO with PHP 7.x compatibility fixes. Perhaps they could help, especially for these warnings:

![warning](https://github.com/cuberite/cuberite/assets/8754153/cfb2d15c-10ef-421f-8a37-f8996aa3c33a)

The "MWS Syntax Highlighter" plugin is currently showing warnings too. I'll have to see if there are any updates for it, or if we have to patch it manually...

**Comment by sphinxc0re** [comment]
Wow! 😯 you folks are amazing! That was so quick 😅

**Comment by bearbin** [comment]
Thanks for doing some QA.

The user IPs were being forwarded already, just MyBB was ignoring them - just needed to tweak a setting and it's now reading the X-Forarded-For values so that should be fixed.

I've updated the Google SEO plugin (and overwrote my patch), but it seemingly works without the patch now so they might have fixed the underlying issue... The issue was it was forcefully redirecting to the bburl config value if the host/protocol is different, which of course it was for reverse-proxying, and the patch was just to edit the check to compare against a fixed value rather than the bburl config.

I've patched the MWS syntax highlighter as well, that seemed to just require one regex change which was broken by PHP 7.

**Comment by sphinxc0re** [comment]
Is it safe for me to cancel the old server or should I keep it online for a while?

**Comment by mathiascode** [comment]
> The user IPs were being forwarded already, just MyBB was ignoring them - just needed to tweak a setting and it's now reading the X-Forarded-For values so that should be fixed.

It still seems to be ignoring them:

![ip](https://github.com/cuberite/cuberite/assets/8754153/16daa77e-b903-4876-b807-febabc6c6d31)

Thanks for fixing the other issues.

Some remaining ones:
- Folder permissions at the bottom of [this page](https://forum.cuberite.org/admin/index.php?module=tools)
- Is [4-byte UTF-8](https://forum.cuberite.org/admin/index.php?module=tools-system_health&action=utf8_conversion) support possible?

![google seo plugin](https://github.com/cuberite/cuberite/assets/8754153/8168361e-af86-46d5-aed9-90066a2b9168)

**Comment by bearbin** [comment]
Folder permissions fixed. No idea how to enable the 4-byte UTF8, I'm not a regular mysql admin and it's a vanilla install of the latest mariadb, should be enabled by default already?

The IP thing seems very strange, it shows my real IP but not yours apparently!

**Comment by mathiascode** [comment]
> No idea how to enable the 4-byte UTF8, I'm not a regular mysql admin and it's a vanilla install of the latest mariadb, should be enabled by default already?

Try changing

`$config['database']['encoding'] = 'utf8';`

to

`$config['database']['encoding'] = 'utf8mb4';`

in `inc/config.php`. Then run the [conversion tool](https://forum.cuberite.org/admin/index.php?module=tools-system_health&action=utf8_conversion) and see if anything changes.

> The IP thing seems very strange, it shows my real IP but not yours apparently!

Looks like it only happens while my VPN is enabled (AirVPN with WireGuard).

**Comment by bearbin** [comment]
IP issue now fixed, default docker IPv6 behaviour is a bit rubbish and it was removing the source addresses for IPv6 users. All sorted out now. Still no clue for the encoding issue, I made those changes and run the tool but it didn't make any difference. Not even sure there's a problem really.

**Comment by NiLSPACE** [comment]
It seems there is a problem with some posts where their contents don't show up. See for example: https://forum.cuberite.org/thread-2805-post-27527.html

I've noticed they all mention other people. Removing the mention shows their content again, at least in the preview page. Strangely this doesn't seem to affect new posts.

**Comment by mathiascode** [comment]
> IP issue now fixed, default docker IPv6 behaviour is a bit rubbish and it was removing the source addresses for IPv6 users. All sorted out now.

Makes sense, I can confirm the issue is fixed.

> Still no clue for the encoding issue, I made those changes and run the tool but it didn't make any difference. Not even sure there's a problem really.

Not sure either, maybe MyBB's UI has some issue. The Google SEO plugin isn't complaining about the encoding anymore at least.

> It seems there is a problem with some posts where their contents don't show up.

It's caused by the DVZ Mentions plugin. Most likely due to an ancient version incompatible with PHP 7.

@bearbin Can you update the Automention and DVZ Mentions plugins to the latest versions?

https://community.mybb.com/mods.php?action=view&pid=558
https://community.mybb.com/mods.php?action=view&pid=29

**Comment by mathiascode** [comment]
Looks like the encoding is still wrong (tried to use 4-byte emojis in a post). That's annoying, wonder why MyBB isn't allowing us to convert the database.

![error](https://github.com/cuberite/cuberite/assets/8754153/e28c278f-42de-49f0-85c4-7c109652c71f)

**Comment by mathiascode** [comment]
I'm going through these steps converting the tables manually... https://community.mybb.com/thread-239572-post-1389754.html#pid1389754

Seems to be giving green checkmarks in the MyBB ACP at least.

**Comment by mathiascode** [comment]
Looks like the conversion worked! Thanks for updating the plugins as well.
