### ISSUE TITLE
App crashes on opening settings

### ISSUE THREAD

**Issue by BrandgrandRealMe** [cuberite/cuberite#5562]
Client version: 1.6.1
Server OS: Android 15 beta 2.1
Cuberite Commit id: cc6459bf0e5d46edf572472ef63b6dc40b59e261

### Expected behavior
Settings open

### Actual behavior
App crashes

### Steps to reproduce the behavior
1. Open app
2. Click settings button

### Server log
N/A
```
Relevant part of server log
```

**Comment by NiLSPACE** [comment]
This was fixed a few months ago in 1.6.3: cuberite/android/issues/74.
