### ISSUE TITLE
The Cuberite.rc file is encoded incorrectly

### ISSUE THREAD

**Issue by 66hh** [cuberite/cuberite#5588]
Compiling Cuberite in vs2022 gives me an RC2104 error, which is suspected to be caused by the incorrect encoding of the rc file, I tried to change the file encoding from utf8 to gbk and successfully compiled Cuberite

#5072

**Comment by bearbin** [comment]
Created a PR with a potential solution, mind checking?

**Comment by 66hh** [comment]
> Created a PR with a potential solution, mind checking?

I tested it and this modification worked in my environment
