### ISSUE TITLE
WebAdmin: Reload user passwords regularly

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#600]
It is somewhat misleading that after the webadmin.ini file is changed to add or remove a user, the changes don't reflect till the server is restarted (not to mention webadmin has problems restarting, see #272). We should make periodic updates to the in-memory credentials - or if we can even detect file changes, the better.

**Comment by bearbin** [comment]
I believe that the server no longer overwrites the webadmin.ini file, but a restart is still needed.
