### ISSUE TITLE
World isn't saved on server stop

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#609]
When the server is stopped using the `stop` server console command, the world isn't saved.

The server queues a new `cWorld::cTaskSaveAllChunks` but doesn't wait for it to finish.

**Comment by SafwatHalaby** [comment]
Still relevant? Doesn't seem so.

**Comment by bearbin** [comment]
This issue is still relevant, AFAIK.

@madmaxoft is there any possibility of a deadlock if a save operation is called directly rather than being queued? I'm not entirely sure about when and where everything is locked.

**Comment by madmaxoft** [comment]
There's a problem that the stop command is processed in a different thread than the world tick, so it could deadlock. The "stop" operation needs to do two steps - first queue a "save" operation, and when it finishes, queue a "terminate" operation.

**Comment by yangm97** [comment]
Is this still an issue?

**Comment by williamhatcher** [comment]
I doubt it. I'm sure it can be closed by now
