### ISSUE TITLE
UTF-8 Characters not fully supported

### ISSUE THREAD

**Issue by antoniobenedetti** [cuberite/cuberite#631]
In the console i can see that some characters are not supported, i get question marks:

[15:03:49] [Lucifer]: за�о �и им ма�е

Characters like: ш, с, т

**Comment by SphinxC0re** [comment]
Is this still an issue? I thought we got rid of it this year

**Comment by Schwertspize** [comment]
it is probably a screen issue, unless both your terminal and the terminal emulator understands utf8 but you get strange output. best way to check is setting your tty using utf8 and changing tty (with strg + f1 for example)
