### ISSUE TITLE
Add optional cChunkStay usage to cEntity::TeleportToX() functions

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#670]
Teleporting the player somewhere where the chunks are not loaded results in the client drifting the player pos down slowly and then suffocating the player in the blocks once the chunk loads.

Add a new optional bool parameter to `cEntity:TeleportToCoords()` and `cEntity:TeleportToEntity()` functions specifying whether the teleport should be deferred until the destination chunk is loaded, via a `cChunkStay`. The parameter should be default-true, so that plugins teleporting players will use it by default.

**Comment by tigerw** [comment]
Solved through #2814 and #3097.
