### ISSUE TITLE
Pushing a block with a piston out of the world bound crashs the server

### ISSUE THREAD

**Issue by TheJumper** [cuberite/cuberite#714]
When a piston pushes a block for example above maximum height the server crashs.

**Comment by tigerw** [comment]
mhm not sure me adding a ShouldSendToClients is a good idea. It's confusing (https://forum.cuberite.org/thread-3193.html) and isn't being used in the piston code now anyway, animation is now done with a scheduled task.

What was that xoft said about not introducing desyncs between server and client? :P
