### ISSUE TITLE
The build system should use FindLua51 to load the system lua if present

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite#739]
Cmake provides a function FindLua51 to locate the system lua install if installed. We should use this function to find the system lua and use that instead of our own if installed. This should be bypassed when the CROSS_COMPILING flag is set so as to avoid dependencies on the build machine.

**Comment by PaddyMac** [comment]
I was thinking about opening a new bug, but then I found this open bug. I'd actually like to see the option to use system libraries for all of the dependencies if possible - maybe with a cmake commandline switch.
