### ISSUE TITLE
Use bed

### ISSUE THREAD

**Issue by Nikeron** [cuberite/cuberite#757]
How to send 0x0A packet to client from LuaAPI?
Or another packet...

**Comment by bibo38** [comment]
> Give some player the illusion that other players are sleeping? How useful :P

[Sleeping bags](http://ftb.gamepedia.com/Sleeping_Bag)! Dead people on an hardcore server! NPCs laying on the beach :smile: !

> You never know when a developer need it :)

Without direct packet access the plugins are more limited than e.g. Bukkit. And implementing every special wish is impossible.
