### ISSUE TITLE
Add ability to specify a custom shutdown message

### ISSUE THREAD

**Issue by Nikeron** [cuberite/cuberite#796]
Add a "shutdown message" settings...

**Comment by Gamerboy59** [comment]
Is it supported now?

**Comment by SphinxC0re** [comment]
I don't think so. But I believe this to be kinda easy to implement. On the other hand, this is very low on our todo list

**Comment by Gamerboy59** [comment]
Ya, it's no core feature but good for some extra comfort and also a good feature for the webadmin.

**Comment by Schwertspize** [comment]
well, i have looked in the code, i can nowhere find the "Disconnected" reason or any kick packet. should we kick players before shutting the server down? It appears that we dont or cannot send a reason if we just close the connection

**Comment by Gamerboy59** [comment]
Yes, players should be kicked before shutdown. I think that's the way to do it.

**Comment by Schwertspize** [comment]
Good. Then it should be rather easy to implement 😛 I just thought it was the case that we should handle the connection a bit different. Anyway, I am going to try that.

**Comment by sweetgiorni** [comment]
I'm gonna take a whack at this if no one objects.

**Comment by Seadragon91** [comment]
I think this can be closed?
