### ISSUE TITLE
Implement streams-based logging

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#799]
To avoid issues with printf()-based formatting, we should implement a logging framework that provides a stream-based access. The usage would then be something along the lines of:

``` cpp
size_t NumBytes = ...;
LOGD(__FUNCTION __ << "Allocating " << NumBytes << " bytes...");
...
LogWarning() << __FUNCTION__ << "Cannot alloc " << NumBytes << " bytes";
```

**Comment by peterbell10** [comment]
Closing in favour of #3542
