### ISSUE TITLE
Add  coloured armor crafting.

### ISSUE THREAD

**Issue by tonibm19** [cuberite/cuberite#815]
Actually you can't craft coloured armor, so it needs to be implemented. Unfortunately it's not meta, it's an NTB tag.

**Comment by tigerw** [comment]
Coloured armour crafting still isn't implemented, I don't think.

**Comment by bibo38** [comment]
I can craft colored armour. Maybe it got implemented unnoticed.

**Comment by SamJBarney** [comment]
I added it :)

**Comment by tonibm19** [comment]
Closing then
