### ISSUE TITLE
BlockStringToType in BlockID.cpp is broken

### ISSUE THREAD

**Issue by jfhumann** [cuberite/cuberite#962]
The following with the following signature:
BLOCKTYPE BlockStringToType(const AString & a_BlockTypeString)
in BlockID.cpp can not relaibly work. BLOCKTYPE is a typedef for unsigned int, which means it can only return positive integers.
However, the documentation comment for this function reads:
/// Translates a blocktype string into blocktype. Takes either a number or an items.ini alias as input. Returns -1 on failure.

Not good.

Internally BlockStringToType just tries to convert it's argument to a (signed) int and return that and if it can't it returns the return value of int cBlockIDMap::Resolve(const AString & a_ItemName), which also returns a signed int, especially -1 for failure.
But of course, all negative numbers will be converted to unsigned positive integers and therefore any users of this function (which is exported to lua!) will not receive -1 as failure state, but some arbitrary positive number.

I found this as coverity reports that this code is wrong in cChunkGenerator::GetIniBlock:

BLOCKTYPE Block = BlockStringToType(BlockType);
    if (Block < 0) // This can never happen as Block is unsigned!
    {
        LOGWARN("[%s].%s Could not parse block value \"%s\". Using default: \"%s\".", a_SectionName.c_str(), a_ValueName.c_str(), BlockType.c_str(),a_Default.c_str());
        return BlockStringToType(a_Default);
    }

The function BlockStringToType is only used in the sources in GetIniBlock, which in turn is not used at all...
My normal approach would be to delete both functions as they are clearly not used and actually can not be reliably used as they have heavy logical bugs. Or maybe refactor the first function, maybe to output to a reference and return a boolean to denote the state of success.
But the first one is exported to lua, so I do not know at all. How do we handle already exported functions? Not change at all? Freely change until a release is out?

What do you propose?

Also, I have a feeling that there could be more errors just like this in similar functions.

Also, do we support some kind of unit testing framework? Because bugs like these can be found easily by them, but of course unit tests create a lot of overhead when coding. I have no existing experience with unit tests in C++, though.

**Comment by Seadragon91** [comment]
Closing as fixed: [Fixed BlockStringToType return value](e3e13f552fe717256e2ba4cb9bea7c00834d1ec4)
